simplify the readme
Combodo/iTop pull request #143
Opened 2020-05-29 09:25 UTC by bruno-ds

evict version related content

2020-05-29 12:12 UTC, piRGoif requested changes
Perfect, thanks Bruno !

I would also move the "resources" section below "Latest release", so that TOC would change from :

> Features, Resources, Latest release, About us, Contributors

To :

> Features, Latest release, Resources, About us, Contributors

2020-05-29 12:12 UTC, piRGoif commented on README.md
> +## Lastest release
Shouldn't this be "Latest" instead of "Lastest" ?
```suggestion
## Latest release
```

2020-05-29 12:59 UTC, bruno-ds commented
> Perfect, thanks Bruno !
> 
> I would also move the "resources" section below "Latest release", so that TOC would change from :
> 
> > Features, Resources, Latest release, About us, Contributors
> 
> To :
> 
> > Features, Latest release, Resources, About us, Contributors

IMO, this file lust be easier for the newcomers, and a newcomer is more interested in finding resources than infos on the latest release (which interest more experienced users).

2020-06-04 14:36 UTC, bruno-ds commented
@v-dumas : your feedback concerning replacement of the versioned link would be appreciated:
[63]: https://www.itophub.io/wiki/page?id=latest:release:2_7_whats_new

(we are waiting for an orphaned page to become more visible)

2020-06-23 09:58 UTC, bruno-ds commented
> Perfect, thanks Bruno !
> 
> I would also move the "resources" section below "Latest release", so that TOC would change from :
> 
> > Features, Resources, Latest release, About us, Contributors
> 
> To :
> 
> > Features, Latest release, Resources, About us, Contributors

This is done, could you please review and if it please you: squash + merge?

2020-06-23 09:59 UTC, Molkobain approved these changes

2020-06-23 09:59 UTC, Molkobain commented
Looks all good to me!

2020-06-23 12:17 UTC, piRGoif approved these changes

2020-06-23 12:25 UTC, Molkobain commented
@bruno-ds we can't merge it, there are conflicts apparently. can you check it out?

2020-06-23 12:45 UTC, bruno-ds commented
> @bruno-ds we can't merge it, there are conflicts apparently. can you check it out?

yes, this commit generate a conflict: 
https://github.com/Combodo/iTop/commit/70835984de093d572eeb9efd0cdbe6b40b837431

I'll look at it :)

2020-06-23 12:51 UTC, merged