add boilerplate function and use it to intercept/enrich trigger exception loops…
Combodo/iTop pull request #158
Opened 2020-08-21 16:14 UTC by odain-cbd

we had difficulties to identify why a notification on timeout event was not sent. we focused on the wrong trigger. another one trigger a PHP exception and lost us. it took time to find the root cause of such a ticket. 

I propose to intercept the exception and enrich it with the ticket classname and its id. 

boilerplate function can be used at other places of the code....

2020-09-07 13:11 UTC, piRGoif commented on application/utils.inc.php
> +		throw $oException;
This seems quite weird
Why not encapsulate exception as this is commonly done ? 
Having for example a TriggerException and doing something like :
`return new TriggerException($oTrigger, $oException);`

2020-09-11 12:33 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
i agree with you. that's what i initially intended to do (encapsulating the original exception). 

but i'd prefer to keep the original exception to avoid to generate any regression in iTop core. somewhere we may rely on a specific kind of exception to do specific additional treatment...

last, we agreed with quality team to keep that PR in next 2.7.2. only modifying exception message attribute is safer.

2020-09-11 12:34 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
as discussed with Eric we will keep this change as is for the below reasons.

2020-09-11 12:37 UTC, eespie approved these changes, later dismissed

2020-09-11 12:38 UTC, piRGoif commented on application/utils.inc.php
> +		throw $oException;
Depends on what catch we are talking about O:)
Triggers are executed by iTop Core, so we should identify which catch are triggered. I bet they are `catch(Exception $e)` ? If so, throwing a typed expression won't affect iTop, and it will be far better for future uses (a specific catch when launching triggers).

We might need to discuss this directly ?

2020-09-14 12:02 UTC, Hipska commented on application/utils.inc.php
> +			! is_a($oCmdbAbstract, 'cmdbAbstractObject'))
```suggestion
			! is_a($oCmdbAbstract, \cmdbAbstractObject::class))
```

2020-09-14 12:02 UTC, Hipska commented on application/utils.inc.php
> +		throw $oException;
And what about making `Trigger::DoActivate` to not throw exceptions? But return a true/false on success? 

It seems it is always used inside a loop.

2020-09-14 12:57 UTC, piRGoif commented on application/utils.inc.php
> +			! is_a($oCmdbAbstract, 'cmdbAbstractObject'))
Thanks Hipska, this is indeed better for IDEs !
And this is compatible PHP 5.5 : https://www.php.net/manual/fr/language.oop5.basic.php#language.oop5.basic.class.class
And was already used in iTop

2020-09-14 13:11 UTC, piRGoif commented on application/utils.inc.php
> +		throw $oException;
As trigger are written in modules, they can throw any exception, we don't have any control on this :/
This PR aims to add some traces that helps when doing support, but without changing any behavior so that we can commit to a support branch (warning @odain-cbd you're based on develop by the way !!). We will certainly improves trigger exception catching in the next release (develop branch), but that will be done apart.

2020-09-14 13:57 UTC, piRGoif commented on application/utils.inc.php
> +		throw $oException;
Here is the catch I found !

Using the [Crud stack documentation](https://www.itophub.io/wiki/page?id=latest%3Acustomization%3Asequence_crud), we can see that triggers are launched by DBObject::DBInsertNoReload and DBObject::DBUpdate.

Here are the call stack we doing an insert or an update from the console UI :

```
UI.php operation=apply_new
  catch(CoreException $e)
  catch(Exception $e)
    catch (CoreCannotSaveObjectException $e)
      cmdbAbstractObject::DBInsert
        cmdbAbstractObject::DBInsertNoReload
          DBObject::DBInsertNoReload

UI.php operation=apply_modify
  catch(CoreException $e)
  catch(Exception $e)
    catch (CoreCannotSaveObjectException $e)
    catch (DeleteException $e)
      cmdbAbstractObject::DBUpdate
        CMDBObject::DBUpdate
          DBObject::DBUpdate
```

The portal does it using this stack :

```
\Combodo\iTop\Portal\Form\ObjectFormManager::OnSubmit
  \DBObject::DBWrite
    \DBObject::DBInsert // if m_bIsInDB
    \DBObject::DBUpdate // otherwise
```

There are no catch here at all.

So as a conclusion there are no place where we have very specific catch, and we can use exception encapsulation.

2020-09-15 07:53 UTC, Hipska commented on application/utils.inc.php
> +		throw $oException;
Looks much better now!

2020-09-15 07:56 UTC, Hipska commented on core/coreexception.class.inc.php
> +	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $previous = null)
```suggestion
	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $oPrevious = null)
```
Or maybe 
```suggestion
	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $ePrevious = null)
```

2020-09-15 07:56 UTC, Hipska commented on core/coreexception.class.inc.php
> +		parent::__construct($sMessage, 0, $previous);
```suggestion
		parent::__construct($sMessage, 0, $oPrevious);
```

2020-09-15 07:57 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
thanks. yes code seems nicer. but stack trace seems worst to me now. as we loose the root cause of the original exception raised. this is not final code.

2020-09-15 08:10 UTC, Hipska commented on application/utils.inc.php
> +		}
Why not like this?
```suggestion
	public static function EnrichRaisedException(\cmdbAbstractObject $oCmdbAbstract, Throwable $oException){
		if (is_null($oCmdbAbstract)){
			throw $oException;
		}
```

2020-09-15 08:10 UTC, Hipska commented on application/utils.inc.php
> +		$sMessage = $oException->getMessage() . " (" . get_class($oCmdbAbstract) . "::" . $oCmdbAbstract->Get('id') . ")";
Why not use predefined `__toString` method?

> HTML String representation of the object
> 
> Only a few meaningful information will be returned.
> This representation is for debugging purposes, and is subject to change.
> The returned string is raw HTML

```suggestion
		$sMessage = $oCmdbAbstract . " " . $oException->getMessage();
```

2020-09-15 08:23 UTC, Hipska commented on application/utils.inc.php
> +		throw $oException;
It's not lost, it's only not represented. I think it's just a matter of calling `$this->getPrevious()->GetTrace()` inside `CoreException::getTraceAsHtml()` to be added into `$aBackTrace`.

2020-09-19 19:40 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
thanks i'll try

2020-09-20 06:54 UTC, odain-cbd commented on core/coreexception.class.inc.php
> +		parent::__construct($sMessage, 0, $previous);
yes i'll change

2020-09-20 07:07 UTC, odain-cbd commented on application/utils.inc.php
> +		$sMessage = $oException->getMessage() . " (" . get_class($oCmdbAbstract) . "::" . $oCmdbAbstract->Get('id') . ")";
good idea for code refactoring. but __toString() currently returns html content. isn't it weard in logs?

2020-09-20 09:10 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
chaining the exception is nicer. as you proposed (Hipska), I can adapt CoreException->getTraceAsHtml() to keep previous stack trace. but i confirm that stacktrace is lost in getTraceAsString(). Reflection manipulation remains better to me.

https://stackoverflow.com/questions/31562724/php-chaining-error-handling

https://stackoverflow.com/questions/34923644/does-re-throwing-an-exception-in-php-destroy-the-stack-trace

2020-09-22 07:58 UTC, Hipska commented on application/utils.inc.php
> +		throw $oException;
These are 2 irrelevant links, see this example to prove the stack trace is not lost: https://3v4l.org/NnPbt
It's really is only matter of correctly retrieving the trace.

2020-09-22 08:03 UTC, Hipska commented on application/utils.inc.php
> +		$sMessage = $oException->getMessage() . " (" . get_class($oCmdbAbstract) . "::" . $oCmdbAbstract->Get('id') . ")";
True, but that is a weirdness of the `__toString` method.

Note that most of these messages do get displayed on the UI (Hence the existence of `CoreException::getTraceAsHtml()`)

2020-09-24 13:14 UTC, odain-cbd commented on application/utils.inc.php
> +		throw $oException;
trace is not lost when using __tostring($e) of your chained exception. on the other hand we dont have root cause when using getTrace() or getTraceAsString(). this is really annnoying as we cannot override them (final public methods).

as discussed with Pierre, we will keep your proposal (chaining the exception) and add a new method getFullStackTraceAsString().

2020-09-24 13:14 UTC, odain-cbd commented on application/utils.inc.php
> +		$sMessage = $oException->getMessage() . " (" . get_class($oCmdbAbstract) . "::" . $oCmdbAbstract->Get('id') . ")";
i will used __tostring() as recommanded.

2020-09-24 13:18 UTC, odain-cbd commented on application/utils.inc.php
> +		}
Type hinting is a good idea. but it is not authorized until latest develop branch. ie 2.8.

as we would like to benefit from this work in 2.7.x (long term support) I will not apply your proposal. even if it is better to me.

2020-09-24 13:21 UTC, Hipska commented on application/utils.inc.php
> +		}
So, starting from which version is type hinting authorised? I think there are lots of other places that already do type hinting..

2020-09-24 13:38 UTC, Hipska requested changes

2020-09-24 13:38 UTC, Hipska commented on core/coreexception.class.inc.php
> +		parent::__construct($sMessage, 0, $previous);
Although this conversation was marked as resolved, it is still not resolved.

2020-09-24 13:38 UTC, Hipska commented on pages/UI.php
> +				$oLog->Set('callstack', $e->getFullStackTraceAsString());
Previous method returned an array and now a string is returned. This is a huge difference.

2020-09-24 13:38 UTC, Hipska commented on pages/UI.php
> +		IssueLog::Error('UI.php operation='.$operation.', error='.$e->getMessage()."\n".$e->getFullStackTraceAsString());
Aren't you over-complicating thing?
```suggestion
		IssueLog::Error('UI.php operation='.$operation.', error='.$e->getMessage()."\n".$e);
```
Or this as the toString does give the message as well:
```suggestion
		IssueLog::Error('UI.php operation='.$operation.', error='.$e);
```

2020-09-24 13:39 UTC, piRGoif commented on application/utils.inc.php
> +		}
We decided to add type hinting only starting from 2.8.0 (develop branch), and only for new methods : a very conservative approach, but we wouldn't like to add bugs because of this...

2020-09-24 13:40 UTC, piRGoif commented on application/utils.inc.php
> +		}
Note that the [coding standard wiki page](https://www.itophub.io/wiki/page?id=latest%3Acustomization%3Acoding_standards) wasn't updated yet, as this decision was made only few weeks ago, and we want to test drive this internally first...

2020-09-24 13:40 UTC, Hipska commented on application/utils.inc.php
> +		}
Well, correct me if I'm wrong, but isn't this a new method?

2020-09-24 13:42 UTC, piRGoif commented on core/coreexception.class.inc.php
> -	public function __construct($sIssue, $aContextData = null, $sImpact = '')
There are some CoreException children that redefines the constructor, but we chose not to update them yet, as this modification aims to be merged to support/2.7 branch.
The work will continue later on, actually handling exceptions throwned by non iTop core code (modules, datamodel methods overrides, ...) is a vast subject O:)

2020-09-24 13:43 UTC, piRGoif approved these changes, later dismissed

2020-09-24 13:44 UTC, piRGoif commented on pages/UI.php
> +				$oLog->Set('callstack', $e->getFullStackTraceAsString());
You're right ! But the value is written to a string field anyway.

2020-09-24 13:45 UTC, piRGoif commented on pages/UI.php
> +		IssueLog::Error('UI.php operation='.$operation.', error='.$e->getMessage()."\n".$e->getFullStackTraceAsString());
Adding a new method allows us to have a clear PHPDoc explaining why we're doing this. And we're also not totally confident that Exception::toString will suit our needs in the future.

2020-09-24 13:46 UTC, Hipska commented on pages/UI.php
> +				$oLog->Set('callstack', $e->getFullStackTraceAsString());
Correct, but the structure of it will be completely different.

2020-09-24 13:47 UTC, Hipska commented on pages/UI.php
> +		IssueLog::Error('UI.php operation='.$operation.', error='.$e->getMessage()."\n".$e->getFullStackTraceAsString());
Okay, can be solved for me.

2020-09-24 13:49 UTC, piRGoif commented on application/utils.inc.php
> +		}
There are 2 conditions to add type hinting :
* code starting on the 2.8.0
* new method

We are adding a new method but on a previous version.

For now this PR is based on develop but this was a mistake and will be fixed very soon : it will be merged to the support/2.7 branch.

2020-09-24 13:50 UTC, piRGoif commented on pages/UI.php
> +				$oLog->Set('callstack', $e->getFullStackTraceAsString());
Right again, but this is debug traces and we though changing format won't matter.

2020-09-24 13:51 UTC, Hipska commented on application/utils.inc.php
> +		}
Oh, okay. That was not clear. 👍

2020-09-24 13:52 UTC, piRGoif commented on core/coreexception.class.inc.php
> +		parent::__construct($sMessage, 0, $previous);
Conversation reopened, thanks for your notice ! I'll tell @odain-cbd

2020-09-24 13:53 UTC, Hipska commented on application/utils.inc.php
> +		$sMessage = $oException->getMessage() . " (" . get_class($oCmdbAbstract) . "::" . $oCmdbAbstract->Get('id') . ")";
I didn't recommend it. I was just asking if this wouldn't be the better way.

2020-09-24 13:56 UTC, Hipska commented on core/coreexception.class.inc.php
> +	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $previous = null)
Same here @odain-cbd @piRGoif

2020-09-24 13:59 UTC, piRGoif commented on core/coreexception.class.inc.php
> +	 * we need stack of all previous exceptions
Having a PSR-3 compatible logger would allow to get rid of this... In such logger the exception is passed directly to the log method, whereas iTop logger only accept a string so logger consumer needs to call itself the getTrace() method.

We might need to add this to LogAPI, will discuss this with the team...

2020-09-24 14:02 UTC, piRGoif commented on core/coreexception.class.inc.php
> +	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $previous = null)
And also there is type hinting... And Throwable seems to have been added in PHP 7 only (https://www.php.net/manual/fr/class.throwable.php)

2020-09-24 14:27 UTC, odain-cbd commented on core/coreexception.class.inc.php
> +	public function __construct($sIssue, $aContextData = null, $sImpact = '', Throwable $previous = null)
type hinting removed

2020-09-24 14:27 UTC, odain-cbd commented on core/coreexception.class.inc.php
> +		parent::__construct($sMessage, 0, $previous);
code cleanup done

2020-09-24 14:49 UTC, Hipska approved these changes, later dismissed

2020-09-24 15:28 UTC, Hipska approved these changes, later dismissed

2020-09-24 15:49 UTC, piRGoif approved these changes, later dismissed

2020-09-25 05:23 UTC, odain-cbd commented
PR cherry-picked and commited in support/2.7 (4e0eed6e1)

2020-09-25 05:23 UTC, closed without merging