Fixing PT BR translations
Combodo/iTop pull request #159
Opened 2020-08-28 17:27 UTC by rokam

2020-08-28 17:32 UTC, rokam commented
Should I create the PR for also 2.7 and 2.8?

2020-08-28 17:51 UTC, Molkobain requested changes
Hello @rokam,

Thanks for the PR! This will go in the 2.8.0, so the develop branch is the good one, you don't have to change anything. Did you translated everything you wanted or should I wait a bit?

Also, as a contributor your name will be in the README of the project, how would you like to be mentioned, by your first/last names or only as rokam?

Cheers,
Guillaume

2020-08-28 17:51 UTC, Molkobain commented on datamodels/2.x/itop-tickets/dictionaries/pt_br.dict.itop-tickets.php
> +	'portal:itop-portal' => 'Portal do usuário~~', // This is the portal name that will be displayed in portal dispatcher (eg. URL in menus)
When an entry is translated, the "~~" should be removed as they are only here to indicate non translated entries.

```suggestion
	'portal:itop-portal' => 'Portal do usuário', // This is the portal name that will be displayed in portal dispatcher (eg. URL in menus)
```

2020-08-28 22:37 UTC, rokam commented
@Molkobain , you can use my first and last name.
About the translation, I'll look for more untranslated strings. Let me tell you when to merge it.

2020-08-29 10:57 UTC, Molkobain commented
Great!

2020-08-29 12:09 UTC, rokam commented
@Molkobain now you are ready to review it.

2020-08-29 12:13 UTC, rokam commented on dictionaries/pt_br.dictionary.itop.core.php
>  Dict::Add('PT BR', 'Brazilian', 'Brazilian', array(
I think this line should be different to be easier for Brazilians to pick the right language.

Something like:
`Dict::Add('PT BR', 'Brazilian Portuguese', 'Português Brasileiro', array(`

But IDK if this might impact into large parts of the software and also in extensions. That's why I kept that out of the PR.

2020-08-31 07:08 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
>  Dict::Add('PT BR', 'Brazilian', 'Brazilian', array(
Indeed, if we change this, it needs to be changed in all files and extensions as well, otherwise they would be seen as 2 different langages.

As most people won't upgrade the extensions for this change (or won't even notice), I'm afraid we cannot do this yet.

When you say that it would be easier for brazilians, does this mean that there are several langages in Brazil?

2020-08-31 07:12 UTC, Molkobain requested changes
Thanks for translating all those sentences, you did a great job! 🤩
Once the '~~' are removed from the 2 lines I mentioned, the PR will be merged.

2020-08-31 07:12 UTC, Molkobain commented on datamodels/2.x/itop-config/dictionaries/pt_br.dict.itop-config.php
> +	'config-current-line' => 'Editando linha: %1$s~~',
```suggestion
	'config-current-line' => 'Editando linha: %1$s',
```

'~~' needs to be removed

2020-08-31 07:12 UTC, Molkobain commented on datamodels/2.x/itop-core-update/dictionaries/pt_br.dict.itop-core-update.php
> +    'iTopUpdate:UI:CanCoreUpdate:ErrorFileNotExist' => 'Falha ao verificar arquivos de sistema (arquivo não existe %1$s)~~',
```suggestion
    'iTopUpdate:UI:CanCoreUpdate:ErrorFileNotExist' => 'Falha ao verificar arquivos de sistema (arquivo não existe %1$s)',
```

'~~' needs to be removed

2020-08-31 10:09 UTC, rokam commented on dictionaries/pt_br.dictionary.itop.core.php
>  Dict::Add('PT BR', 'Brazilian', 'Brazilian', array(
No, just portuguese. Brazilians are used to find Portuguese (in english or portuguese) to choose the language. The term Brazilian isn't usual.

I also consider that the use of Portuguese instead of Brazilian is more Portuguese speakers friendly, cause there are some differences but we're able to use the software in any Portuguese variation.

2020-08-31 10:13 UTC, rokam commented on datamodels/2.x/itop-config/dictionaries/pt_br.dict.itop-config.php
> +	'config-current-line' => 'Editando linha: %1$s~~',
Fixed

2020-08-31 10:13 UTC, rokam commented on datamodels/2.x/itop-core-update/dictionaries/pt_br.dict.itop-core-update.php
> +    'iTopUpdate:UI:CanCoreUpdate:ErrorFileNotExist' => 'Falha ao verificar arquivos de sistema (arquivo não existe %1$s)~~',
Fixed

2020-08-31 11:10 UTC, Molkobain approved these changes
All good!

2020-08-31 11:12 UTC, merged

2020-08-31 11:36 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
>  Dict::Add('PT BR', 'Brazilian', 'Brazilian', array(
Ok, thanks for the explanation. I tried to change the dictionary labels in some files only to see if it would conflict or duplicate the "PT BR" dictionnary but in the end it's fine!

So the good news is that if you want to make a PR which changes all `Dict::Add('PT BR', 'Brazilian', 'Brasileiro', array(` to `Dict::Add('PT BR', 'Brazilian Portuguese', 'Português Brasileiro', array(`, it's most likely to be integrated 😊

Just keep in mind that this will work on a standard iTop Community, but if the are some iTop extensions containing the "old" "Brazilian" string, it might fallback to it.

2020-08-31 12:16 UTC, rokam commented
@Molkobain the use of a tool like https://crowdin.com/ will help to archive better translations. Hope you guys consider it.

2020-08-31 12:18 UTC, Hipska commented
Correct, we also tried with Transifex as well: https://www.transifex.com/super-visions/

2020-08-31 12:54 UTC, Molkobain commented
I totally agree with you guys. Until recently most hosted services did not support iTop dictionaries format (PHP arrays), I just took a look at both you links and they seem to work, that's a good news!

The only problem I see is that their plans are pretty expensive when the app. has a lot of strings/words... And we cannot qualify as an open-source project as we sell subscriptions for iTop.

So as we don't have many translations updates, I don't think we will go this way for now, unless you know one tool which is cheaper / free... 😕

2020-08-31 13:04 UTC, rokam commented
@Molkobain , I think https://crowdin.com/pricing#crowdin-pricing-key-features can be used by iTop for free.

2020-08-31 13:08 UTC, rokam commented
https://pootle.translatehouse.org/index.html can also be used, but needs a hosting.

2020-09-01 09:02 UTC, Molkobain commented
Thanks for the links! We took a look a pootle but the repo has been dead for years now. We are taking a quick look at weblate right now, as it can be self-hosted and has a good pulse. This could be a great improvement for the community contributions, but to be honest we won't have the bandwidth to deploy it very soon.

2020-09-01 09:08 UTC, Hipska commented
Transifex can also be used for free since the community version is non commercial? The translations for the modules of Essential en Professional can not be hosted for free then.

2020-09-01 09:22 UTC, Molkobain commented
For Transifex and Crowdin, I checked their terms and iTop doesn't comply as we do have commercial offers "We offer Transifex for free to Open Source projects that have no funding, **revenue, and/or commercialization model**"