Correctly detect if connection to client is secure
Combodo/iTop pull request #161
Opened 2020-09-02 11:26 UTC by Hipska

The current code breaks the setup page when the iTop server is behind a proxy that handles [SSL termination](https://en.wikipedia.org/wiki/TLS_termination_proxy).

I have applied a better way to detect if iTop has been reached over HTTPS based on code already present in the project:
https://github.com/Combodo/iTop/blob/97e58c2d79355c71b91e44071d24796fe6449e67/datamodels/2.x/authent-cas/vendor/apereo/phpcas/source/CAS/Client.php#L3591-L3610

2020-09-07 12:46 UTC, piRGoif submitted a review, later dismissed
Seems OK to me :)
After integrating this PR we should change the CAS code to call the utils method...

2020-09-11 14:31 UTC, bruno-ds commented
http headers should be taken into account only for trusted remote.
If this is not done then, for instance, a man in the middle could trick iTop into assuming the connection is secure.

So, I think you should add a way to perform this configuration.


for instance, symfony name this conf "trusted proxies":
https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

2020-09-13 09:03 UTC, bruno-ds commented
Why a little more time to think about your code, I think that your assumption is harmless for your use case. But it indeed introduce  a misleading API, maybe conditioning the check of the headers to an optional second argument with a phpdoc mentioning the trust issue would be a good compromise since it would avoid the difficulty of setting a conf before the initial setup

2020-09-14 08:44 UTC, bruno-ds commented
I just found that there is a documented solution that seems simple to use: 
https://www.itophub.io/wiki/page?id=latest:admin:settings&s[]=nginx#accessing_itop_from_different_urls

Doesn't it work for your use case?

2020-09-14 08:55 UTC, Hipska commented
1. The instance is not accessed from different urls.
2. It's on Azure, I can't modify proxy headers of the SSL terminator.
3. During initial setup there is no config file yet, so the method `utils::GetDefaultUrlAppRoot()` gets executed.

2020-09-14 09:06 UTC, bruno-ds commented
> 2. It's on Azure, I can't modify proxy headers of the SSL terminator.

I don't get it, you can't add this on the iTop's webserver configuration?
```apache
RequestHeader set HTTPS On
```
This should be feasible either on the vhost's configuration or in a .htaccess file.

2020-09-14 09:11 UTC, Hipska commented
Ah, yes that is possible indeed.

But I see and understand your concerns, I see 2 uses of `utils::IsConnectionSecure()`:
https://github.com/Combodo/iTop/blob/0542a8e4f8c46f70c640c12f79e7480a899d94e9/application/loginwebpage.class.inc.php#L438-L442
https://github.com/Combodo/iTop/blob/0542a8e4f8c46f70c640c12f79e7480a899d94e9/application/utils.inc.php#L833-L837

Correct me if I'm wrong, but I think the security concern is only for the first one. So what if we add a `$bTrustProxy` parameter and set it `true` by default. And set it to false when use the method on the login page?

2020-09-14 09:39 UTC, bruno-ds commented
> Correct me if I'm wrong, but I think the security concern is only for the first one. So what if we add a `$bTrustProxy` parameter and set it `true` by default. And set it to `false` when use the method on the login page?

This is was I proposed you but since there is a solution in the documentation, I'd rather close the PR if you're ok with that.
If you're not, I'll trigger an internal debate over your proposal.

Please note that while it has the drawback to require the admin to find the wiki entry, I still think the wiki's solution is better because: 
 - it do not add complexity in the code
 - it put the administrator in charge of a security concern

2020-09-14 09:48 UTC, Hipska commented
The documentation has a workaround, not a 'solution'.

I don't agree to close the PR as I'm having the impression that PR's are too quickly/easily closed without any good reason or feedback. So please discuss internally first and come back with a good reason. I don't bite 😂

The workaround in the documentation also is not a good fit if iTop is reached via this SSL proxy for external clients, but if internal systems at the same side of the proxy are reaching over HTTP.

2020-09-14 09:53 UTC, bruno-ds commented
> I don't agree to close the PR as I'm having the impression that PR's are too quickly/easily closed without any good reason or feedback. So please discuss internally first and come back with a good reason. I don't bite 😂
I think that I gave you both reason and feedback, bu you have the right to think they are not good enough, so ok, we'll discuss it internally 😄 


> The workaround in the documentation also is not a good fit if iTop is reached via this SSL proxy for external clients, but if internal systems at the same side of the proxy are reaching over HTTP.
I don't think so, you'll just have to use two virtual host (one for the ssl, one for the http) and handle this conf. on the virtual host side.

2020-09-14 10:03 UTC, Hipska commented
> I think that I gave you both reason and feedback, bu you have the right to think they are not good enough, so ok, we'll discuss it internally 😄

I'm not only talking about this PR, you came with clear arguments indeed. Only sad that it is a workaround, while this PR (unintentionally) aims to fix the need of a workaround.

> I don't think so, you'll just have to use two virtual host (one for the ssl, one for the http) and handle this conf. on the virtual host side.

I could have thought that one would come up with this "workaround on a workaround" solution. I don't get why you as a vendor would prefer this over a fix in the code, so all these workarounds are not needed.

Discuss it internally, and let me know if it is not wanted, I just tried to help to fix stuff as I know there are a lot of bugs/features to be handled and you don't have time to work on these small ones.

2020-10-05 08:39 UTC, Hipska commented
Hi @bruno-ds, do you have an update?

2020-10-06 13:56 UTC, bruno-ds commented
> Hi @bruno-ds, do you have an update?

Sorry for the delay (my family was hit by the covid), I just restarted to work this monday, we will soon work on your PR.

2020-10-06 13:57 UTC, Hipska commented
Okay, no problem. I hope everything is ok.

2020-10-12 08:56 UTC, odain-cbd commented
Hi Hipska,

we just reviewed current PR with Pierre and Bruno. it seems nice to us if you agree to finalize it. 

here are following remaining things to be completed:
- add optional parameter and implement discussed logic. instead of `$bTrustProxy`,  $bTrustUnsecureHeaders` seems better to us.
- enhance PHP doc to reflect the security impact of the parameter
- (optional) add unit test to cover/document this enhancement. 
if you don't feel confident with testing, no pb. we will do this part for you.

BR
the team

2020-10-20 13:38 UTC, Hipska commented
The optional parameter should default to `true` or `false`?

2020-10-20 13:48 UTC, odain-cbd commented
"So what if we add a $bTrustProxy parameter and set it true by default. And set it to false when use the method on the login page?"

let's stick to your initial proposal. defaut is true.

2020-10-20 14:32 UTC, piRGoif commented
I was surprised by @odain-cbd answer, so I've just had a chat with him... And indeed we both agreed that `$bTrustProxy=false` is preferable : this way previous calls or modified calls with default parameter value will lead to the exact same behavior as before.

If a developer wants to had the extra check using the other http headers, then he'll have to specify the parameter, and it's a value that isn't the default one so we can assume the developer has read the phpdoc :o)

Thanks !

2020-10-20 15:40 UTC, bruno-ds commented
There are two reasons to set `$bTrustProxy=false` as default :
 - We do not want to introduce unnecessary breaking changes
 - Security must take precedence, and the default signature mustn't use insecure headers

2020-12-03 11:36 UTC, Hipska commented
Sorry for the late response, but here are my changes ;-)

2020-12-10 07:57 UTC, piRGoif requested changes
For now the $bTrustProxy is passed directly in \utils::GetDefaultUrlAppRoot, but it's not this method responsibility to know this.
Indeed this parameter value should be set by the final consumer : calls in WizStep* should pass true, all others nothing or false.

Also note that \utils::GetDefaultUrlAppRoot is called from another util method : \utils::GetAbsoluteUrlAppRoot. This one too should propagate this parameter with the same default value !
It is called multiple times, but never seems to be called directly from the setup : so we should just add the parameter and don't change the consumer so that default value would be used.

2020-12-10 09:12 UTC, Hipska commented
Done

2020-12-10 09:42 UTC, piRGoif requested changes
Many thanks !

As you found the call to \utils::GetAbsoluteUrlAppRoot in \SetupPage::output, I did a search of GetAbsoluteUrlAppRoot in the setup dir, and found another one in \MFCompiler::PathToPHP. Could you add true here as well ?

2020-12-10 09:42 UTC, piRGoif commented on setup/setuppage.class.inc.php
> +		$sLogo = utils::GetAbsoluteUrlAppRoot(true).'/images/itop-logo.png';
Good catch !

2020-12-10 11:04 UTC, Hipska commented
Hmm, this gets reflected in compiled code, so outside of the setup. So I think it should actually be false in that case.

2020-12-10 11:32 UTC, piRGoif commented
Do you have any call stack in mind ? I supposed calls to the compilator is done only in safe places like setup, toolkit, Designer or Hub connector ?

2020-12-10 13:10 UTC, Hipska commented
The call is indeed done in the setup, but the code you are referring to is this:
https://github.com/Combodo/iTop/blob/76fbd3790ff4a48e2de3d9730a67bb1107f08f97/setup/compiler.class.inc.php#L728-L767

That doesn't do the actual call to `utils::GetAbsoluteUrlAppRoot` but will place that in the generated datamodel php classes. And there, that piece of code will be called at normal iTop runtime, not inside the setup.

See https://github.com/Combodo/iTop/blob/76fbd3790ff4a48e2de3d9730a67bb1107f08f97/setup/compiler.class.inc.php#L2114-L2123

So I guess this is all that is needed for this PR and it can be merged?

2020-12-10 13:19 UTC, piRGoif commented
You are perfectly right ! My mistake, sorry :/
I'm changing my review !

2020-12-10 13:20 UTC, piRGoif approved these changes

2020-12-10 13:22 UTC, piRGoif commented
Awaiting a second Combodo review to merge, I've just pinged Bruno :)

2020-12-16 14:30 UTC, bruno-ds approved these changes
Alas some minor coding convention (`bTrustProxy = false` instead of `bTrustProxy=false`) and an explanation of the security implication of trusting insecure proxies inside the PhpDoc, everything seems fine.

I think that the merge can be performed as it (we would then fix the above-mentioned minor issues)

2020-12-16 14:37 UTC, merged

2021-03-03 19:02 UTC, bruno-ds commented
FYI, this commit (https://github.com/Combodo/iTop/commit/7b093a6bba505810d00f7937754e26e626f829b3) is built upon this PR.
It enhance it by providing getters for the most important parts of the url (the uri part is seems to not be really used, we didn't even find sufficient information about how it behave).

A few commit will add a few extra api endpoints, but the core logic is here.
Thanks @Hipska for pointing us in the right direction :)

2021-03-04 08:01 UTC, piRGoif commented
Also 7b093a6 was committed to the support/2.7 branch and will be available in iTop 2.7.4. This PR was merged to develop so next iTop 3.0.0.

2021-03-04 08:06 UTC, bruno-ds commented
> Also [7b093a6](https://github.com/Combodo/iTop/commit/7b093a6bba505810d00f7937754e26e626f829b3) was committed to the support/2.7 branch and will be available in iTop 2.7.4. This PR was merged to develop so next iTop 3.0.0.

Yes, and since it will then be merged to develop and overwrite part of Hipka's work. I thought he deserved an explanation (and a thank you).

2021-03-04 08:40 UTC, Hipska commented
Hey, thanks for pinging back. I don't know if Cherry-picking would have helped to keep my name in the `git blame` records.. That's maybe something to consider in the future.

I still want to express I am very happy that this PR got merged even it had some resistance and comments in the beginning, but in the end I could convince you all and it got merged! 👍

2021-06-25 15:33 UTC, Hipska commented
Hey all, just a heads-up. I just tried setup iTop Professional 2.7.4 in Azure and the setup is still broken.

It tries to load all resources as https://NAME.azurewebsites.net:80/... (I was under the impression it would have been solved in that version?) It seems the protocol is now trusted, but the port isn't?

2021-06-25 15:48 UTC, Molkobain commented
Hello Thomas,

Thanks for the feedback, I've just forwarded your message to the QA team.

2021-06-25 21:07 UTC, bruno-ds commented
Did you properly set `behind_reverse_proxy`, and could you please check if the requirements set in the link below are met?
https://wiki.combodo.com/doku.php?id=latest:install:reverse_proxy

Thanks

2021-06-26 06:25 UTC, Hipska commented
The link is private, but no, it’s an initial install, so settings cannot be set yet.

2021-06-28 06:14 UTC, piRGoif commented
>> Did you properly set behind_reverse_proxy, and could you please check if the requirements set in the link below are met?
>> https://www.itophub.io/wiki/page?id=latest%3Ainstall%3Areverse_proxy
> 
> The link is private

Here is the public link : 
https://www.itophub.io/wiki/page?id=3_0_0%3Ainstall%3Areverse_proxy

2021-06-28 06:43 UTC, bruno-ds commented
> The link is private, but no, it’s an initial install, so settings cannot be set yet.

When I said that I wanted you to check against [this page](https://www.itophub.io/wiki/page?id=latest%3Ainstall%3Areverse_proxy), I had this in mind:
Could you please check/indicate which ` X-Forwarded-*`  HTTP headers are present?

I think that either the port or the protocol is missing.

2021-06-28 09:05 UTC, Hipska commented
It seems only `X-Forwarded-Proto` is available:
![image](https://user-images.githubusercontent.com/228588/123607856-89e3ba00-d7fe-11eb-9338-c153a8f28692.png)

The problem seems to be at https://github.com/Combodo/iTop/blob/410948fb4e261f1bf4063525288873dd97508ff8/application/utils.inc.php#L1074-L1078

I think there should be assumed the default port if the proxy does not specify the `X-Forwarded-Port` parameter?

2021-06-30 15:10 UTC, bruno-ds commented
your capture seems to lack some informations, like:
 - on what port the webserver is contacted by the reverse proxy?
 - same for the protocol?

By inferring this from your symptoms, I would state that the reverse proxy forward the requests to the webserver using the port 80 in place of the 443 but does not send the header `X-Forwarded-port`.

Could you please check this, and add the `X-Forwarded-port` if I'm right?