N°3287 - Set from display name / label in action email
Combodo/iTop pull request #162
Opened 2020-09-03 14:53 UTC by larhip

With this PR you should be able to set the display name of the email sender (as well as reply to).

Two more attributes (from_label & reply_to_label) added to ActionEmail
dictionaries has been updated (at least with placeholders)

2020-09-03 15:24 UTC, Hipska submitted a review, later dismissed

2020-09-03 15:32 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to_label+' => 'Reply to display name will be sent into the email header~~',
```suggestion
	'Class:ActionEmail/Attribute:from' => 'Van (e-mail)',
	'Class:ActionEmail/Attribute:from+' => 'Wordt gebruikt in de hoofdtekst van de e-mail (headers)',
	'Class:ActionEmail/Attribute:from_label' => 'Van (label)',
	'Class:ActionEmail/Attribute:from_label+' => 'Wordt gebruikt in de hoofdtekst van de e-mail (headers)',
	'Class:ActionEmail/Attribute:reply_to' => 'Antwoord (e-mail)',
	'Class:ActionEmail/Attribute:reply_to+' => 'Wordt gebruikt in de hoofdtekst van de e-mail (headers)',
	'Class:ActionEmail/Attribute:reply_to_label' => 'Antwoord (label)',
	'Class:ActionEmail/Attribute:reply_to_label+' => 'Wordt gebruikt in de hoofdtekst van de e-mail (headers)',
```

2020-09-03 15:35 UTC, Hipska commented
I think you should mark the translations of `Class:ActionEmail/Attribute:from` and `Class:ActionEmail/Attribute:reply_to` (and the descriptions as well) as being new or to be translated (`~~`)..

2020-09-04 05:58 UTC, Hipska submitted a review, later dismissed

2020-09-04 06:04 UTC, larhip commented
Thanks @Hipska for dutch translations and the hint regarding the existing translations.
I updated the dict files and squash all changes into one commit

2020-09-04 06:17 UTC, Molkobain commented
Looks all good, thanks @larhip !

2020-09-04 07:51 UTC, Hipska requested changes

2020-09-04 07:51 UTC, Hipska commented on dictionaries/es_cr.dictionary.itop.core.php
>  	'Class:ActionEmail/Attribute:reply_to+' => 'Será enviando en el encabezado del Correo Electrónico',
```suggestion
	'Class:ActionEmail/Attribute:from' => 'Remitente~~',
	'Class:ActionEmail/Attribute:from+' => 'Será enviando en el encabezado del Correo Electrónico~~',
	'Class:ActionEmail/Attribute:from_label' => 'From (label)~~',
	'Class:ActionEmail/Attribute:from_label+' => 'Sender display name will be sent into the email header~~',
	'Class:ActionEmail/Attribute:reply_to' => 'Responder a~~',
	'Class:ActionEmail/Attribute:reply_to+' => 'Será enviando en el encabezado del Correo Electrónico~~',
```

2020-09-04 07:53 UTC, larhip commented on dictionaries/es_cr.dictionary.itop.core.php
>  	'Class:ActionEmail/Attribute:reply_to+' => 'Será enviando en el encabezado del Correo Electrónico',
oh.. I missed them thanks for that!

2020-09-04 08:23 UTC, Molkobain commented
Note for myself: Check derivated classes from ActionEmail to see if the new attributes should be added in the details zlist (eg. approval modules)

2020-09-04 08:32 UTC, Hipska commented
I was wondering, couldn't the FROM name come from the logged in user?

2020-09-04 08:44 UTC, larhip commented
Not sure whether this is always intended behavior..
Anyhow if you want to do it in this way you should be able to configure it with this PR (by setting from_label to a placeholder based on current user i.e. 
`$current_contact->friendlyname$`)

2020-09-04 09:00 UTC, Hipska approved these changes
Aha, that's perfect then!

2020-09-11 07:32 UTC, Molkobain approved these changes

2020-09-11 07:36 UTC, Molkobain requested changes

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Why did you change the translations and added "~~" at the end?

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/da.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => 'Svar sendes til~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/es_cr.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => 'Será enviando en el encabezado del Correo Electrónico~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/it.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/ja.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '電子メールのヘッダーに挿入されます~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => 'Será enviado para o cabeçalho de email~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/ru.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => 'Будет отправлено в заголовке email~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/sk.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/tr.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => 'e-posta başlığında gönderilecek~~',
Same comment

2020-09-11 07:36 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to' => '回复到~~',
Same comment

2020-09-11 07:45 UTC, larhip commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
In the German and English dictonary files I changed the translations from "From" to "From (email)", to make clear, you have to configure the sender mail here (and the sender label in a different attribute).
I took the idea of @Hipska and added "~~" to the existing translations:
> I think you should mark the translations of `Class:ActionEmail/Attribute:from` and `Class:ActionEmail/Attribute:reply_to` (and the descriptions as well) as being new or to be translated (`~~`)..

2020-09-11 07:48 UTC, Molkobain commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:reply_to+' => '~~',
Oh, ok, sorry I forgot that. Then it's all good. Thank you for the reminder!

2020-09-11 07:49 UTC, Molkobain approved these changes

2020-09-11 07:50 UTC, merged