Cleanup references to Flash
Combodo/iTop pull request #163
Opened 2020-09-04 13:12 UTC by Hipska

Since Flash support is deprecated, the codebase still has a lot of references to Flash.

This PR removes all the swf files and an unused swf library that get's loaded on every page.
It deletes a php page with abandoned code. Since it never got referenced, it is better/safer to completely remove it.
It also renames the action to load the relation graph as it still got a swf reference.

2020-09-07 09:41 UTC, piRGoif commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
I would recommend keeping the old operation, as there might be some modules out there depending on this. This will allow us to add the depreciation in our migration notes, and remove this operation on the next major version.

```suggestion
		case 'swf_navigate': // SWF was removed in iTop 
		case 'navigate': // Graphical display of the relations "impact" / "depends on"
```

2020-09-07 09:41 UTC, piRGoif commented
Many thanks, we should have done this long ago !

2020-09-07 09:43 UTC, Hipska commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
Good suggestion!

2020-09-07 09:43 UTC, Hipska commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
Maybe adding an `@depricated` doc as well?

2020-09-07 09:46 UTC, piRGoif commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
I did hesitate to add it : it suits very well in a function / class PHPDoc, but for just one line, I'm not sure ? But indeed it's a keyword we're looking before releasing :) Maybe add it in the inline comment like this :
```suggestion
		case 'swf_navigate': // @deprecated SWF was removed in iTop 
		case 'navigate': // Graphical display of the relations "impact" / "depends on"
```

2020-09-07 09:47 UTC, Hipska commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
I'm not sure this works with phpdoc. Can you verify first?

2020-09-07 10:09 UTC, piRGoif commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
I don't think that the deprecated tag is handled by IDEs for anything else than a class or a function... I didn't find any reference though :/ I was remembering that deprecated usages are strike through since a few versions in PHPStorm but I didn't find any release note about this (I didn't take time to do an exhaustive search...)

You version is ok for me :)

2020-09-07 10:18 UTC, Hipska commented on pages/UI.php
> +		case 'navigate': // Graphical display of the relations "impact" / "depends on"
Done: e0079a4

2020-09-07 10:24 UTC, piRGoif approved these changes, later dismissed
Ok for me, but we will need to do a team review... will keep you posted !

2020-09-11 16:10 UTC, piRGoif commented
Will be reviewed by Romain & Denis

2020-09-17 14:45 UTC, rquetiez requested changes
I would rather have 'navigate_relations' because 'navigate' is too common and grep is the solely option to connect the dots.

2020-09-17 15:04 UTC, Hipska commented
Or just 'relations', like you have 'details' and 'stimulus' for example?

2020-09-18 12:17 UTC, rquetiez requested changes, later dismissed
Yes, 'relations' is more meaningful than 'navigate', but I would prefer a more discriminant id like 'view-relations' because this will be helpfull on the long run when searching where this operation is used (and therefore perform a change or cleanup.

2020-09-25 14:16 UTC, Hipska commented
Done

2020-09-29 07:31 UTC, piRGoif approved these changes, later dismissed

2020-09-29 08:03 UTC, Molkobain requested changes

2020-09-29 08:03 UTC, Molkobain commented on application/displayblock.class.inc.php
> +								$aActions[$sRelationCode.'_down'] = array ('label' => $aRelationInfo['down'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view-relations&relation=$sRelationCode&direction=down&class=$sClass
I know @rquetiez told you to put a dash but it was a typo, we rather use underscores for operations like in the rest of the PHP endpoints.

```suggestion
								$aActions[$sRelationCode.'_down'] = array ('label' => $aRelationInfo['down'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view_relations&relation=$sRelationCode&direction=down&class=$sClass&id=$id{$sContext}") + $aActionParams;
```

2020-09-29 08:03 UTC, Molkobain commented on application/displayblock.class.inc.php
> +								$aActions[$sRelationCode.'_up'] = array ('label' => $aRelationInfo['up'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view-relations&relation=$sRelationCode&direction=up&class=$sClass&id=$i
```suggestion
								$aActions[$sRelationCode.'_up'] = array ('label' => $aRelationInfo['up'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view_relations&relation=$sRelationCode&direction=up&class=$sClass&id=$id{$sContext}") + $aActionParams;
```

2020-09-29 08:03 UTC, Molkobain commented on pages/UI.php
> +		case 'swf_navigate': /** @deprecated SWF was removed in iTop */
Did you mean "swf_navigat**or**"?

```suggestion
		case 'swf_navigator': /** @deprecated SWF was removed in iTop */
```

2020-09-29 08:03 UTC, Molkobain commented on pages/UI.php
> +		case 'view-relations': // Graphical display of the relations "impact" / "depends on"
```suggestion
		case 'view_relations': // Graphical display of the relations "impact" / "depends on"
```

2020-09-29 08:03 UTC, Molkobain commented on js/swfobject.js
> -/* SWFObject v2.1 <http://code.google.com/p/swfobject/>
Careful this file is included in the "approval-base" and "customer-survey" modules.

If we continue as is, there will be a 404 error for this file in the browser and the webserver logs until we make a new version of the extension (strategy TBD to keep BC).

We also need to check if these 2 modules completely abandoned usage of Flash (I can't anwser this without having a look at the code)

2020-09-29 08:05 UTC, Molkobain commented
Just made a few comment, once the one on the complementary modules is discussed and the small changes on the operation name fixed, it will be all good for me.

Thanks for the cleanup @Hipska 👍

2020-09-29 08:05 UTC, piRGoif commented on pages/UI.php
> +		case 'swf_navigate': /** @deprecated SWF was removed in iTop */
Ouch, nice catch Guillaume !

2020-09-29 08:05 UTC, Hipska commented on application/displayblock.class.inc.php
> +								$aActions[$sRelationCode.'_down'] = array ('label' => $aRelationInfo['down'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view-relations&relation=$sRelationCode&direction=down&class=$sClass
Thanks, will combine them in 1 commit if no problem..

2020-09-29 08:07 UTC, Hipska commented on pages/UI.php
> +		case 'swf_navigate': /** @deprecated SWF was removed in iTop */
Whoops indeed. Came from e0079a41e5df4bd106441ca518a107bdd31330da

2020-09-29 08:08 UTC, Molkobain commented on application/displayblock.class.inc.php
> +								$aActions[$sRelationCode.'_down'] = array ('label' => $aRelationInfo['down'], 'url' => "{$sRootUrl}pages/$sUIPage?operation=view-relations&relation=$sRelationCode&direction=down&class=$sClass
Yeah sure 😊

2020-09-29 08:13 UTC, Hipska commented on js/swfobject.js
> -/* SWFObject v2.1 <http://code.google.com/p/swfobject/>
Since there isn't any browser that supports Flash anymore (out of the box), I highly doubt these modules still actively use the framework referenced. But it's indeed better to check these modules and remove the include line as done  in `itopwebpage.class.inc.php` before this gets merged into the development branch.

2020-09-29 08:29 UTC, Molkobain commented on js/swfobject.js
> -/* SWFObject v2.1 <http://code.google.com/p/swfobject/>
Just checked, these 2 modules are included in the iTop commercial packages, so they will be worked on before the 2.8.0 release. Corresponding tickets have been created N°3344 and N°3345. We can proceed with this!

2020-09-29 13:27 UTC, Molkobain approved these changes

2020-09-29 13:27 UTC, Molkobain commented
All good, thanks @Hipska ! ✌

2020-09-29 13:30 UTC, Molkobain commented
We got a "This branch cannot be rebased safely: Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge."

Can you try rebasing your branch on develop? Or is it because your branch have diverged from develop?

2020-09-29 13:55 UTC, Hipska commented
That's why I don't like rebase's.. I checked and don't see any merge conflicts. Is a regular merge not possible instead?

2020-09-29 13:56 UTC, merged

2020-09-29 13:57 UTC, piRGoif commented
Hi @Hipska, Guillaume had an error message but I didn't. I've just done the merge !
Usually we are doing squash & merge, unless we absolutely want to keep the PR branch history - I've done squash here.

2020-09-29 13:58 UTC, Molkobain commented
Thanks @piRGoif !

2020-10-06 08:12 UTC, Hipska commented
Hi, could you please also add the `hacktoberfest` tag to this repo? digitalocean/hacktoberfest#596

2020-10-06 14:02 UTC, piRGoif commented
This was done here too