fix search error when search string '0'
Combodo/iTop pull request #170
Opened 2020-09-28 14:26 UTC by annProg

criterion `contains 0` will not work as expect
![image](https://user-images.githubusercontent.com/4145852/94444448-ea46bc00-01d8-11eb-9803-c168e7e2881c.png)

The redevelopped query expression should be ` SELECT `Server` FROM Server AS `Server` WHERE (`Server`.`friendlyname` LIKE '%0%')`

The problem is caused by `empty()` function considered "0"(0 as a string) to be empty.

2020-09-30 10:17 UTC, Hipska requested changes
The correct way to do it would be to use `strlen`.

2020-09-30 15:16 UTC, annProg commented
> The correct way to do it would be to use `strlen`.

new commit use `strlen`

2021-01-29 15:20 UTC, Molkobain commented
Hello @annProg ,

We reviewed this among the dev team and agreed that it should be merged. We are just checking if a unit test could be added to cover this, then we'll check with the product team if it's okay to put this in the 3.0.

Thanks and sorry for the delay!

Take care,
Guillaume

2021-01-29 15:23 UTC, Molkobain commented
Go for integration in 3.0, will be merged just before the beta

2021-01-29 15:42 UTC, Hipska approved these changes

2021-01-29 15:44 UTC, Molkobain approved these changes

2021-02-01 11:11 UTC, Molkobain commented
Corresponding unit test done in 43290c0f

2021-02-01 11:11 UTC, merged