ormPassword: allow use of different password hash algo
Combodo/iTop pull request #180
Opened 2020-12-04 15:40 UTC by samsk

Hi,
  this pull request introduces possibility to change password_hash algorithm via config file, ie. to use new, more advanced one, or to to use older algorithm if PASSWORD_DEFAULT changes.

example config:
```'password_hash_algo' => PASSWORD_ARGON2ID```

Along with this ormPassword::CheckPassword was fixed, because with different hash algo password_get_info() will return string and not integer as algo identificator, what results in code assuming that it is checking a legacy password.

Thank you

2020-12-04 17:04 UTC, Hipska requested changes

2020-12-04 17:04 UTC, Hipska commented on core/config.class.inc.php
> +	 * @var array Password hash algorithm to use.
```suggestion
	 * @var integer Password hash algorithm to use.
```

2020-12-04 17:04 UTC, Hipska commented on core/ormpassword.class.inc.php
> +			}
This suggestion is actually a question towards Combodo if this is wanted or not.
```suggestion
			$bResult = ($this->m_sHashed == $sHashedPwd);
```

2020-12-04 18:01 UTC, Molkobain commented on core/ormpassword.class.inc.php
> +			}
Yep, 💯

2020-12-04 18:04 UTC, Molkobain commented
Sounds like a nice feature improvement!

That being said I'm not an expert on that area of the code, so I can't approve the PR. But looks like you took care of the previously stored passwords and the backward compatibility right?

2020-12-06 08:27 UTC, samsk commented
Yes, backward compatibility is preserved. This only changes how password hashes are created, so hashes generated with different algo will still work.

2020-12-06 11:52 UTC, Hipska approved these changes, later dismissed

2020-12-07 13:34 UTC, steffunky commented
Hello,

These changes seem good to me, I'll wait for the R&D team to review it but it would be a nice addition to iTop and it's perfectly integrated with the way we intended to handle password with 2.6.0 👍
We may need to add a unit test as ormPassword is becoming configurable and may have to handle legacy passwords and maybe passwords with different hash algorithms.

2021-01-08 14:17 UTC, steffunky commented
Hi,
We just reviewed this feature and we think it would be safer to write a test along with this change.
I can find time in the next couple of weeks to write it and the team will review the test and merge this PR.

2021-01-08 14:20 UTC, Hipska commented on core/ormpassword.class.inc.php
> +			}
Okay, @samsk, can you apply the suggestion?

2021-01-25 11:17 UTC, piRGoif commented
Test was proposed with https://github.com/promitilus/iTop/pull/1
Awaiting this to be merged... @samsk please poke here when done !

2021-01-25 11:28 UTC, Hipska submitted a review, later dismissed

2021-01-25 12:23 UTC, samsk commented
Sorry that you've to wait, I missed somehow that pull notification.

2021-01-25 12:33 UTC, Hipska approved these changes

2021-01-25 13:12 UTC, Molkobain approved these changes

2021-01-25 13:14 UTC, Molkobain commented
Seems all good to me. Don't forget to create/update a/the corresponding ticket in the internal bug tracker.

2021-01-26 08:20 UTC, steffunky approved these changes

2021-01-26 08:20 UTC, merged

2021-01-26 08:20 UTC, steffunky commented
Merged, thanks for your contribution!
Internal bug ref: N°3662