iTop 3.0.0 badge dashlet : make whole badge clickable
Combodo/iTop pull request #191
Opened 2021-02-04 18:09 UTC by piRGoif

**Before :** only the text link was clickable (object name, "create" link)

**Now :** the whole badge is clickable.
* When clicking on the "create" label (the corresponding A tag actually) the create form opens.
* Otherwise the list appears.

2021-02-04 21:10 UTC, Molkobain requested changes
This would bring a way better UX to the badges indeed! ✌

Just a few remark regarding the current implementation to better match the UIBlock concepts and guidelines:
1. All the JS should be in a dedicated jQuery UI widget instantiated in the `layout.js.twig` of the block, not in a separated file, otherwise badges won't work on others pages (Friendly reminder: Blocks must be atomic and independant, meaning that they must work in any page)
2. Use the `data-role` attributes for JS selectors to keep segregation between style and interaction (you can check examples on other blocks)
3. Remove the HTML tags from the selectors (eg. `div`), again for the sake of the segregation as the markup could evolve.
4. Note: The jQuery UI widget provides an easier way to interact with elements within the block, making selectors simpler/clearer. (see points 2. and 3.)

I admit that I'm not fond of using all this JS just to work around the limitation of having an anchor within an anchor; but in this particular case I think it's worth it (and we don't have another choice 😁)

For the record, another (lighter?) implementation could be to have to "main" (list) anchor around the whole badge, than a `<span href="xxx" onclick="Someting to redirect here;">` instead of the anchor but:
- It will not be great for accessibility as the span could be focused
- It would be a shady hack not as easy to maintain as something following the blocks guidelines

2021-02-04 21:20 UTC, piRGoif commented on application/dashboard.class.inc.php
> +    .closest("div.ibo-dashlet-badge")
Using `$(this)`should allow to remove this DOM browsing !
TODO tomorrow !

2021-02-04 22:03 UTC, piRGoif commented
We'll need to have a chat about your propositions so I get a clear picture :)

2021-02-05 07:12 UTC, piRGoif commented
I forgot to say : currently there is just one click handler set in the dashboard code. I would prefer to keep it that way, as having one handler per page is far better than an handler per badge dashlet !

But of course this code is of the DashletBadge component responsibility... So we might add a method in DashletContainer to be implemented in each dashlet components, and having the dashboard code to call this method on each dashlet impl to get the JS code to return ?

2021-02-08 14:42 UTC, piRGoif commented
Discussed with @Molkobain : having only one handler on the dashboard level is nice, but we need to keep code responsability which is badge dashlet component.

So we agreed to : 
* create a dashlet badge JQuery widget
* instantiate this widget in all badge instance using a JS twig file

We will later on (maybe 3.1.0 ?) improve the API by adding a mean for components to add "static" JS code (added only once event if multiple instances provided). Combodo internal ref N°3710

2021-02-08 18:41 UTC, piRGoif commented
I pushed the last version that use : 
* a JQuery widget, instanciate in each component (JS twig)
* data-role attributes as selectors

Note that a badge dashlet contains 2 containers : one to contain the whole dashlet, and one again created inside the component (?!??)
So to get to the highest container I had to do weird stuffs :/ (see 209b91bd)

2021-02-08 21:02 UTC, Molkobain requested changes

2021-02-08 21:02 UTC, Molkobain commented on js/components/dashlet-badge.js
> +	$.widget('itop.dashletBadge',
Convention is (see other blocks)
```suggestion
	$.widget('itop.dashlet_badge',
```

2021-02-08 21:02 UTC, Molkobain commented on js/components/dashlet-badge.js
> +			dashletContainer: null,
No camel case properties, only snake case, see other blocks

2021-02-08 21:02 UTC, Molkobain commented on sources/application/UI/Base/Component/Dashlet/DashletBadge.php
> +	public const DEFAULT_JS_TEMPLATE_REL_PATH = 'base/components/dashlet/dashletbadge';
Template should be `dashlet-badge` (even though I understand you followed the naming from the HTML template, which should be fixed as well; if you could fix it while you are at it, it would be great 👍)

2021-02-08 21:02 UTC, Molkobain commented on sources/application/UI/Base/Component/Dashlet/DashletBadge.php
> +		'js/components/dashlet-badge.js',
Could you put this file in a `dashlet` sub-folder just like for the templates / stylesheets?

2021-02-08 21:02 UTC, Molkobain commented on sources/application/UI/Base/Component/Dashlet/DashletContainer.php
> +		$this->AddDataAttribute('role', 'ibo-dashlet');
```suggestion
		$this->AddDataAttribute('role', static::BLOCK_CODE);
```

2021-02-08 21:02 UTC, Molkobain commented on sources/application/UI/Base/Component/Dashlet/DashletContainer.php
> +	public function __construct(string $sId = null, array $aContainerClasses = [])
I'm not fond of this at it's clear that there is clearly a design problem in the dashlets block, this should be in a parent template, but for now I might it's acceptable. We might have to refactor the dashlets a bit later 😥

2021-02-09 17:59 UTC, piRGoif commented on application/dashboard.class.inc.php
> +    .closest("div.ibo-dashlet-badge")
Outdated comment, closing conversation !

2021-02-09 18:03 UTC, piRGoif commented on sources/application/UI/Base/Component/Dashlet/DashletContainer.php
> +	public function __construct(string $sId = null, array $aContainerClasses = [])
Comment well noted I agree as said in our IM !
Out of scope for now, so resolving this conversation

2021-02-09 18:06 UTC, piRGoif commented on js/components/dashlet-badge.js
> +	$.widget('itop.dashletBadge',
Will be solved by future commit

2021-02-09 18:06 UTC, piRGoif commented on js/components/dashlet-badge.js
> +			dashletContainer: null,
Will be solved by future commit

2021-02-09 18:06 UTC, piRGoif commented on sources/application/UI/Base/Component/Dashlet/DashletContainer.php
> +		$this->AddDataAttribute('role', 'ibo-dashlet');
Will be solved by future commit

2021-02-09 18:11 UTC, piRGoif commented on sources/application/UI/Base/Component/Dashlet/DashletBadge.php
> +	public const DEFAULT_JS_TEMPLATE_REL_PATH = 'base/components/dashlet/dashletbadge';
Will be solved by future commit

2021-02-09 18:15 UTC, piRGoif commented on sources/application/UI/Base/Component/Dashlet/DashletBadge.php
> +		'js/components/dashlet-badge.js',
You'll have to explain me directly, not sure to understand ?

2021-02-09 18:15 UTC, piRGoif commented
Changing state : not a draft anymore

2021-02-09 18:26 UTC, piRGoif commented on sources/application/UI/Base/Component/Dashlet/DashletBadge.php
> +		'js/components/dashlet-badge.js',
Discussed with Guillaume, changed in 59cd940b

2021-02-11 11:08 UTC, piRGoif commented
@Molkobain is OK to merge, so let's go !

2021-02-11 11:09 UTC, merged