Fix create CMDBChange without any corresponding CMDBChangeOp
Combodo/iTop pull request #192
Opened 2021-02-09 13:58 UTC by piRGoif

For now the CMDBChange objects are persisted immediatly.
This delays the insert call : this is now done only on the first CMDBChangeOp creation.

2021-02-09 15:38 UTC, piRGoif commented
Latest commits to : 
* fix "Call to a member function IsNew() on int" bug
* add a constraint on CMDBChangeOp::Set when called on the change attribute

There could be some unit test associated, will do this later

2021-02-11 11:03 UTC, bruno-ds commented
As seen with @piRGoif : 

 - The throw in the CMDBChangeOp::Set() seem dangerous since it change the behavior of iTop on a minor version. (@piRGoif has checked against itop and all our extensions but still, there is room for private ext. and customization)
 - the type returned by Get seems to always be an integer (I didn't know this aprt of the API) : we should check it against @dflaven or @rquetiez or @Molkobain 
 

there is a complex auto lock behavior : since the change is persisted very late (on insert), and the the api does not return the (not yet persisted) object but it's id, we simply can't persist it anymore.
This is why @piRGoif has made the setter enforce a persisted instance.

so, the behavior change are that now on 
 - the API let set a "current change" not yet persisted
 - the API forbid the set of a change not yet persisted and/or as integer

I think that setting a change with an id > 0 should be authorized. 
I think that setting a negative integer or a not persisted instance, should trigger an IssueLog and fall back on the OnInsert code that fetch the current change.
Doing so would not change the behavior of a minor version. If we want to migrate to the exception, maybe we could deprecate it with just an issue log, and throw on the 3.0?

2021-02-11 11:12 UTC, piRGoif commented
Thanks @bruno-ds ! I will do a review with @rquetiez next week and let you know !
In the meantime I'll have to fix a bug in \CMDBChangeOp::Set : for now it is crashing if setting using an int !

2021-02-12 10:12 UTC, Hipska requested changes

2021-02-12 10:12 UTC, Hipska commented on core/cmdbchangeop.class.inc.php
> +		}
I would revert this logic so that the exception is thrown first and otherwise continue to to existing `return parent::Set()`
```suggestion
		if ($sAttCode == 'change' && $value->IsNew()) {
			throw new CoreUnexpectedValue("Cannot set CMDBChangeOp.change with a non persisted CMDBChange !");
		}
```

That would improve the readability of the code.

2021-02-12 13:02 UTC, Hipska requested changes

2021-02-12 13:02 UTC, Hipska commented on core/cmdbchangeop.class.inc.php
> +		throw new CoreUnexpectedValue("Invalid value set to CMDBChangeOp.change");
Again, now you made it worse. There are now 3 places where you call the exact same return.

To improve readability, I would suggest to revert the logic to:
```suggestion
		if ($sAttCode == 'change') {
			if (is_int($value) && $value <= 0) {
				$this->ThrowInvalidCMDBChangeException();
			}
			elseif (is_object($value) && $value->IsNew()) {
				$this->ThrowInvalidCMDBChangeException();
			}
		}

		return parent::Set($sAttCode, $value);
```

2021-02-12 14:18 UTC, piRGoif commented on core/cmdbchangeop.class.inc.php
> +		throw new CoreUnexpectedValue("Invalid value set to CMDBChangeOp.change");
I like your first proposal : exit condition first. Will change this !

2021-02-15 13:09 UTC, piRGoif commented on core/cmdbchangeop.class.inc.php
> +		throw new CoreUnexpectedValue("Invalid value set to CMDBChangeOp.change");
Sorry I misread on friday : main exit condition is already on top. After reading again and more carefully your proposition, I agree grouping the error conditions is better. 
I've just pushed 38acbc87

2021-02-15 14:21 UTC, piRGoif commented
Rewrote the description according to the latest changes.

2021-02-22 11:14 UTC, piRGoif commented
We did a review with @rquetiez ! Here is a summary of what we said : 

* Romain agreed on the minimum modification, that is : 
  - removing DBInsert call in `\CMDBObject::CreateChange`
  - in `\CMDBChangeOp::OnInsert` persist the current change if it needs to be saved

* We agreed that the existing test in `\CMDBChangeOp::OnInsert` that set the current change without any information is a big risk for the developper. 
But the `\CMDBChangeOp::Set` overriding I did is a big risk, for a small gain...
We should warn clearly the developer that history should be handled by the API. Maybe add a warning when calling directly `\CMDBChangeOp::Set('change', ...)` or `CMDBChange::DBInsert` (only if dev env, call trigger_error ?)
There are only 2 extensions, but some core calls also...
This has to be discussed with the rest of the team, and we would upgrade the code in a separate PR.

* About `\CMDBObject::SetTrack*` methods : what I modified was not enough, as the current change could be already persisted, and simply modifying it would have no effect whatsoever !
We could change this so that if the current change is persisted, then we would create a new change.
This should be done in a dedicated PR !

2021-02-22 11:26 UTC, Hipska commented on core/cmdbchangeop.class.inc.php
> +		throw new CoreUnexpectedValue("Invalid value set to CMDBChangeOp.change");
Please see my suggestion again, the call to parent should not be inside an `if` for readability of the code..

2021-02-22 13:18 UTC, piRGoif commented on core/cmdbchangeop.class.inc.php
> +		throw new CoreUnexpectedValue("Invalid value set to CMDBChangeOp.change");
After a review with Romain (see last comment below), I will drop this to lower this PR's scope.
Thanks for your feedback !
I'm closing this conversation.

2021-02-22 13:29 UTC, Hipska requested changes

2021-02-22 13:29 UTC, Hipska commented on core/cmdbobject.class.inc.php
> +		$oChange = MetaModel::NewObject('CMDBChange');
```suggestion
		self::$m_oCurrChange = MetaModel::NewObject('CMDBChange');
```

2021-02-22 13:29 UTC, Hipska commented on core/cmdbobject.class.inc.php
> +		self::$m_oCurrChange->Set("userinfo", $sUserInfo);
Why is `self` used instead of `static` like in the SetTrack* methods?

2021-02-22 13:29 UTC, Hipska commented on core/cmdbobject.class.inc.php
> +		}
Is this needed?

2021-02-22 13:29 UTC, Hipska commented on core/cmdbobject.class.inc.php
> +			self::$m_oCurrChange->Set("origin", $sOrigin);
Why not
```suggestion
			static::SetTrackOrigin($sOrigin);
```

2021-02-22 13:49 UTC, piRGoif commented on core/cmdbobject.class.inc.php
> +		$oChange = MetaModel::NewObject('CMDBChange');
Wooopsy
Nice catch !
Will be fixed in the next commits

2021-02-22 13:50 UTC, piRGoif commented on core/cmdbobject.class.inc.php
> +		self::$m_oCurrChange->Set("userinfo", $sUserInfo);
Will be fixed in next commits

2021-02-22 13:52 UTC, piRGoif commented on core/cmdbobject.class.inc.php
> +		}
There are no default value for this field, as we need to call a PHP function to get it
No overrides will set it
So this is a workaround to get a default value O:)

2021-02-22 13:52 UTC, piRGoif commented on core/cmdbobject.class.inc.php
> +			self::$m_oCurrChange->Set("origin", $sOrigin);
This method update will be removed in next commits, closing this conversation

2021-02-22 14:05 UTC, piRGoif commented
I've just pushed modifications discussed with @rquetiez
Removing draft flag, and setting this PR to be reviewed by the dev team

2021-02-22 14:20 UTC, Hipska commented on core/cmdbobject.class.inc.php
> +		static::$m_oCurrChange->Set("date", $oDate);
What about
```suggestion
		static::SetTrackInfo($sUserInfo);
		static::SetTrackOrigin($sOrigin);
		static::CreateChange();

		if (!is_null($oDate)) {
			static::$m_oCurrChange->Set("date", $oDate);
		}
```

As it seems you are doing double code right now and it might be better to just reuse already existing code.

2021-02-23 09:54 UTC, piRGoif commented on core/cmdbobject.class.inc.php
> +		static::$m_oCurrChange->Set("date", $oDate);
I like this ! I'm committing this suggestion. Thanks !

2021-02-23 10:01 UTC, Hipska approved these changes

2021-03-01 07:51 UTC, piRGoif commented
Dev team is OK, but as I'm proposing this for the 2.7.5 version we will review it with the products team.

2021-03-01 08:17 UTC, Hipska commented on test/core/CMDBObjectTest.php
> +		$oTestObject = MetaModel::NewObject('DocumentWeb');
`DocumentNote` vs `DocumentWeb`

2021-03-01 09:35 UTC, piRGoif commented on test/core/CMDBObjectTest.php
> +		$oTestObject = MetaModel::NewObject('DocumentWeb');
Wooops, good catch thanks !
Fixed in a2e3940f

2021-03-12 10:15 UTC, piRGoif commented
Presentation was done to the products team. Waiting for their answer (maybe after 2.7.4 ?)

2021-12-22 15:34 UTC, piRGoif commented
Presentations to the product team was done 6 months ago, and no feedback for now :(
Version 2.7.6 will be out soon and contains another fix as a workaround for this API...

I updated this PR description to explain better the whole story, and will ask again the product team.

2021-12-31 09:19 UTC, piRGoif commented
Presentations to the product team was done 6 months ago, and no feedback for now :(
Version 2.7.6 will be out soon and contains another fix as a workaround for this API...

I updated this PR description to explain better the whole story, and will ask again the product team.

2022-01-11 16:08 UTC, piRGoif commented
Meeting planned for the end of next week

2022-01-12 14:22 UTC, piRGoif commented
We agreed to have a dedicated meeting on this : it is planned for next week.

2022-01-21 15:39 UTC, piRGoif commented
The meeting happened, I have some actions to do before going on !
Stay tune :)

2022-02-17 17:27 UTC, piRGoif commented
Actions done, next meeting planned in 2 weeks.

2022-03-02 14:49 UTC, piRGoif commented
The PR was accepted after review with the product team 🥳

But as we are aiming to deliver 3.0.1 very soon and don't want those modifications to be part of this release, we will merge after 3.0.1 delivery.

2022-04-19 15:13 UTC, merged