Polish translation added
Combodo/iTop pull request #194
Opened 2021-03-09 13:27 UTC by DudekArtur

Polish translation of **datamodels** and **dictionaries** added

2021-03-09 15:09 UTC, piRGoif commented
Hello @DudekArtur 
Many thanks for your contribution !

What files did you used as a baseline ? 
The develop branch hosts the future 3.0.0 version. If you used current 2.7.x file, then your PR should be based on the support/2.7 branch (which hosts the upcoming 2.7.4 version)

2021-03-09 15:48 UTC, DudekArtur commented
> Hello @DudekArtur
> Many thanks for your contribution !
> 
> What files did you used as a baseline ?
> The develop branch hosts the future 3.0.0 version. If you used current 2.7.x file, then your PR should be based on the support/2.7 branch (which hosts the upcoming 2.7.4 version)

I used the translation from my 2.7.3 instance, but I adapted some of the files to the current English version. All translations with the annotation "moved to dictionaries" were uploaded unchanged, the rest were adapted to version 3.0.0

2021-03-09 16:46 UTC, piRGoif commented
Ok thanks ! I was asking as, as you saw, dictionaries were refactored in the 3.0.0 version...

I would recommend we keep your code as is so that no extra work is required. But that means your translations won't be available before iTop 3.0.0 beta.

The other option would be : 
* you rebasing /force push your branch on the support/2.7 branch
* adapt the files to match the ones in your iTop 2.7.3 instance
* after PR  validation + merge, we will need to add some work on the merge from support/2.7 to develop in order to keep all of your translations (for the keys that were moved in 3.0.0) - we will ask you to review this merge certainly !

Note that iTop 2.7.4 is in its final dev stage so we won't be able to integrate your work before 2.7.5.

What do you think ?

2021-03-10 06:53 UTC, DudekArtur commented
Well. Today, in my free time, I will upload the translation to version 2.7. I use iTop and I am satisfied. Let the others be happy too.

2021-03-10 07:35 UTC, piRGoif commented
> Well. Today, in my free time, I will upload the translation to version 2.7. I use iTop and I am satisfied. Let the others be happy too.

Wow, many thanks !!
So you can add those 2.7 translations in a new PR, based on the support/2.7 branch.

We will review/integrate your 2.7 PR, wait for the merge (support/2.7 to develop) to be done, and then we will be able to deal will this one.

2021-03-10 08:14 UTC, piRGoif requested changes
I'v just finish reviewing your changes, what a wonderful job you've done here !

I've just notice some missing or extra keys, see the corresponding comments.

After merging your changes I will add you to the repo README.md file in the contributors section, but if you'd like to you can also add a `@author` mention in each of the files you've created. As an example see dictionaries/de.dictionary.itop.core.php

2021-03-10 08:14 UTC, piRGoif commented on dictionaries/pl.dictionary.itop.model.php
> +?>
This file doesn't exist anymore in EN, so you can get rid of it

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-welcome-itil/dictionaries/pl.dict.itop-welcome-itil.php
> +Dict::Add('PL PL', 'Polish', 'Polski', array(
The corresponding EN file is empty, pl file should be empty to ?

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-request-mgmt/dictionaries/pl.dict.itop-request-mgmt.php
> +	'Class:UserRequest/Attribute:cumulatedpending+' => '',
Warning, both of these keys no longer exists in the develop branch, nor in this file nor anywhere else

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/pl.dict.itop-request-mgmt-itil.php
> +	'Class:UserRequest/Attribute:cumulatedpending+' => '',
Same remark as in itop-request-mgmt (non itil) : both of those keys were removed in the develop branch.

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/dictionaries/pl.dict.itop-portal-base.php
> +	'Portal:Form:Close:Warning' => 'Chcesz opuścić ten formularz? Wprowadzone dane mogą zostać utracone',
Check the EN file : this constant is in a dedicated section, and this other section has also the 'Portal:Form:Caselog:Entry:Close:Tooltip' key : 

```
	'Portal:Calendar-FirstDayOfWeek' => 'en-us', //work with moment.js locales
));

// Object form
Dict::Add('EN US', 'English', 'English', array(
	'Portal:Form:Caselog:Entry:Close:Tooltip' => 'Close this entry',
	'Portal:Form:Close:Warning' => 'Do you want to leave this form ? Data entered may be lost',
));
```

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-core-update/dictionaries/pl.dict.itop-core-update.php
> +
Comparing with the EN file, missing this key : 

```suggestion
	'iTopUpdate:UI:CannotUpdateUseSetup' => 'You must use the <a href="%1$s">setup</a> to update the application.<br />Some modified files were detected, a partial update cannot be executed.~~',


```

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/itop-attachments/dictionaries/pl.dict.itop-attachments.php
> +));
Missing key here : 

```suggestion
	'UI:Attachments:DropYourFileHint' => 'Drop files anywhere in this area~~',
));

```

2021-03-10 08:14 UTC, piRGoif commented on datamodels/2.x/authent-ldap/dictionaries/pl.dict.authent-ldap.php
> +	'Class:UserLDAP/Attribute:password+' => 'ciąg uwierzytelniania użytkownika',
Those two keys aren't present anymore in the develop branch, you can remove them

```suggestion
```

2021-03-10 12:30 UTC, DudekArtur commented on dictionaries/pl.dictionary.itop.model.php
> +?>
Ok

2021-03-10 12:33 UTC, DudekArtur commented on datamodels/2.x/itop-welcome-itil/dictionaries/pl.dict.itop-welcome-itil.php
> +Dict::Add('PL PL', 'Polish', 'Polski', array(
I think so. If there were no translations in the EN version, I copied the file to the PL version.

2021-03-10 12:53 UTC, DudekArtur commented on datamodels/2.x/authent-ldap/dictionaries/pl.dict.authent-ldap.php
> +	'Class:UserLDAP/Attribute:password+' => 'ciąg uwierzytelniania użytkownika',
Done

2021-03-10 12:58 UTC, DudekArtur commented on datamodels/2.x/itop-welcome-itil/dictionaries/pl.dict.itop-welcome-itil.php
> +Dict::Add('PL PL', 'Polish', 'Polski', array(
Done. PL file is empty too.

2021-03-10 13:07 UTC, DudekArtur commented on datamodels/2.x/itop-request-mgmt/dictionaries/pl.dict.itop-request-mgmt.php
> +	'Class:UserRequest/Attribute:cumulatedpending+' => '',
Done

2021-03-10 13:08 UTC, DudekArtur commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/pl.dict.itop-request-mgmt-itil.php
> +	'Class:UserRequest/Attribute:cumulatedpending+' => '',
Done

2021-03-10 13:14 UTC, DudekArtur commented on datamodels/2.x/itop-portal-base/dictionaries/pl.dict.itop-portal-base.php
> +	'Portal:Form:Close:Warning' => 'Chcesz opuścić ten formularz? Wprowadzone dane mogą zostać utracone',
Done

2021-03-10 13:18 UTC, DudekArtur commented on datamodels/2.x/itop-core-update/dictionaries/pl.dict.itop-core-update.php
> +
Done

2021-03-10 13:20 UTC, DudekArtur commented on datamodels/2.x/itop-attachments/dictionaries/pl.dict.itop-attachments.php
> +));
Done

2021-03-10 14:48 UTC, piRGoif commented
I've just renamed the PR so that it will be easier to us :)

2021-03-10 17:41 UTC, piRGoif approved these changes
Thanks for the quick modifications after my first review !
I've just reviewed again, no problem. I had close the conversations, and creating this new review as approved !

2021-03-10 17:42 UTC, piRGoif commented
Cannot merge right now, as we must first : 
1. merge #195 
2. merger support/2/7 to develop

2021-03-26 08:54 UTC, piRGoif commented
As reviewed with the products team, #195 was rejected
In consequence I can merge this PR !

2021-03-26 08:55 UTC, merged

2021-03-26 08:56 UTC, piRGoif commented
@DudekArtur I'm going to add you to the README.md's contributor list
What mention would you prefer ? Your GitHub profile name only, or more ?

2021-03-29 07:48 UTC, DudekArtur commented
I think the GitHub profile name is enough. Regards.

2021-03-29 08:31 UTC, piRGoif commented
Thanks, done in 8846a42 !