Support/2.7 Polish translation added
Combodo/iTop pull request #195
Opened 2021-03-10 12:28 UTC by DudekArtur

A Polish translation has been added based on the instance used in 2.7.3. Differences due to the current English version of the translation have been taken into account.

2021-03-10 14:47 UTC, piRGoif commented
Thanks ! I will review this !
For reference #194 was added to integrate same translations but for the develop branch (next 3.0.0). This one is for 2.7.5 (2.7.4 is coming really close, so too late to integrate this PR in that version)

2021-03-10 14:49 UTC, piRGoif commented
I've just renamed the PR so that it will be easier to us :)

2021-03-10 18:16 UTC, piRGoif requested changes
Wonderful job, thanks ! Just a little change to make : one empty file should be removed

2021-03-10 18:16 UTC, piRGoif commented on dictionaries/pl.dictionary.itop.model.php
> +<?php
This file doesn't exist in the EN version, can you remove it ?

2021-03-11 12:08 UTC, DudekArtur commented on dictionaries/pl.dictionary.itop.model.php
> +<?php
Every other translation has an empty _**dictionaries/XX.dictionary.itop.model.php**_ file. That is why I also included an identical one in the Polish translation. It is not only in the English translation. I don't know what these files are for. Are you sure I should delete it?

2021-03-11 12:31 UTC, piRGoif commented on dictionaries/pl.dictionary.itop.model.php
> +<?php
I am :)
After merging your PR I'll delete dictionnary.model.php files in other languages.

2021-03-11 13:14 UTC, DudekArtur commented on dictionaries/pl.dictionary.itop.model.php
> +<?php
Done

2021-03-12 08:10 UTC, piRGoif approved these changes

2021-03-12 08:12 UTC, piRGoif commented
This seems all good to me thanks !
This PR is on hold waiting for the 2.7.4 to be packaged and published... It should take a few weeks then we'll be able to merge for 2.7.5, and deal with #194.

2021-03-26 08:53 UTC, piRGoif commented
I'm really sorry, as we had some troubles recently with bad dictionaries, the products team prefers not to integrate any new languages in the 2.7.* branch...
All my apologies, I should have checked with them earlier... 😢

However you could add those dictionaries in a dedicated GitHub repo, or maybe factorize them so they could be installed a additional modules ?

I'm closing this PR, again, all my apologies :(

2021-03-26 08:53 UTC, closed without merging