🌐 Update Dutch dictionaries for 3.0
Combodo/iTop pull request #199
Opened 2021-03-30 10:44 UTC by Hipska

2021-03-31 07:45 UTC, Hipska commented
Hi @jbostoen, do you want to help? Or give a review?

2021-03-31 07:56 UTC, piRGoif commented
Hello,
We should stop 3.0.0-beta dev this week... If you could finish this PR in the upcoming days it will be included.

2021-03-31 08:00 UTC, Hipska commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:RichText:ToolbarState:Collapsed' => 'Ingeklapt~~',
Not sure if it is good like this, that's why I kept the `~~`.

2021-03-31 08:07 UTC, jbostoen commented
For now a review due to lack of time to do a bigger effort. If necessary, I definitely want to do more for the final version

2021-03-31 08:11 UTC, Hipska commented
Great, feel free to do whatever you want, we will see the outcome 😉

2021-03-31 08:41 UTC, jbostoen requested changes

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.core.php
> +	'Change:State_Changed_NewValue_OldValue' => 'veranderd van %2$s naar %1$s',
Capital needed?

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status+' => 'Status beslist wie op de hoogte zal gesteld worden: enkel de testontvanger, iedereen (Aan, CC en BCC) of niemand',
Maybe "bepaalt" (determines) instead of "beslist" (decides)?

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:enabled+' => 'Alle Aan, CC and BCC emails zullen op de hoogte gesteld worden',
We should be consistent: "e-mail" or "email" (see next line)

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.ui.php
> +	'Class:Query/Attribute:is_template' => 'Sjabloon voor OQL velden',
OQL-velden

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.ui.php
> +	'Class:Query/Attribute:is_template+' => 'Bruikbaar als bron voor bestemming OQL Notificaties',
OQL-notificaties

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Button:SearchInHierarchy' => ' Zoek in hierarchie ',
hiërarchie

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/components/nl.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:Processing' => 'Even geduld…',
Is this a deliberate choice? (one character with three dots, rather than 3 separate dots)

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/components/nl.dictionary.itop.global-search.php
> +	'UI:Component:GlobalSearch:Input:Placeholder' => 'Zoek…',
See previous comment about dots

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/components/nl.dictionary.itop.quick-create.php
> +	'UI:Component:QuickCreate:Input:Placeholder' => 'Selecteer een objectsoort…',
See previous comment about dots

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/layouts/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:ClosedCover:Title' => 'Activiteiten paneel',
Activiteitenpaneel

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/layouts/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:ClosedCover:Tooltip' => 'Klik om het activiteiten paneel te openen',
activiteitenpaneel

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/layouts/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter…',
See comment about dots

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/layouts/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:Toggler:Tooltip' => 'Vergroot / Verberg',
Uitklappen / Verbergen (of in- of dichtklappen, you use 'inklappen' later)

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/pages/nl.dictionary.itop.errorpage.php
> +	'UI:ErrorPage:UnstableVersion' => 'Je gebruikt een instabiele versie die mogelijks fouten bevat. Als je denkt dat deze fout hierdoor komt, gelieve ons hierover te contacteren!~~',
~~ still present

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:ActivityPanel:Title' => 'Activiteiten paneel',
Activiteitenpaneel

2021-03-31 08:41 UTC, jbostoen commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
>  	'UI:Preferences:ActivityPanel:EntryFormOpened' => 'Entry form opened by default~~',
Is this still work in progress or why are some parts skipped?

2021-04-06 09:34 UTC, Hipska commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
>  	'UI:Preferences:ActivityPanel:EntryFormOpened' => 'Entry form opened by default~~',
It's a WIP indeed (see draft status), but for some, I just couldn't find good translation. Then I prefer not to translate at all.

2021-04-06 09:37 UTC, Hipska commented on dictionaries/ui/components/nl.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:Processing' => 'Even geduld…',
Yes, semantically more correct. Don't know what Combodo thinks about it? @piRGoif

2021-04-06 09:42 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Change:State_Changed_NewValue_OldValue' => 'veranderd van %2$s naar %1$s',
Not sure about this. Don't see its usage yet.

2021-04-06 09:43 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:enabled+' => 'Alle Aan, CC and BCC emails zullen op de hoogte gesteld worden',
Already solved

2021-04-06 09:49 UTC, piRGoif commented on dictionaries/ui/components/nl.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:Processing' => 'Even geduld…',
Hello,
We don't have a position on this for now... I don't think we have used this anywhere for now ? Certainly because it's not available directly on a standard keyboard ?
All files are encoded with and pages are served using UTF-8 so there shouldn't be any technical issue.

2021-04-06 09:54 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Button:SearchInHierarchy' => ' Zoek in hierarchie ',
Done in 53963e0f

2021-04-06 09:54 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'Class:Query/Attribute:is_template+' => 'Bruikbaar als bron voor bestemming OQL Notificaties',
Done in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/ui/layouts/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:ClosedCover:Title' => 'Activiteiten paneel',
Done in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/ui/layouts/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:ClosedCover:Tooltip' => 'Klik om het activiteiten paneel te openen',
Done in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/ui/pages/nl.dictionary.itop.errorpage.php
> +	'UI:ErrorPage:UnstableVersion' => 'Je gebruikt een instabiele versie die mogelijks fouten bevat. Als je denkt dat deze fout hierdoor komt, gelieve ons hierover te contacteren!~~',
Don't know anymore why I left it. Removed in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:ActivityPanel:Title' => 'Activiteiten paneel',
Done in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'Class:Query/Attribute:is_template' => 'Sjabloon voor OQL velden',
Done in 53963e0f

2021-04-06 09:55 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status+' => 'Status beslist wie op de hoogte zal gesteld worden: enkel de testontvanger, iedereen (Aan, CC en BCC) of niemand',
Done in 53963e0f

2021-04-06 09:57 UTC, Hipska commented on dictionaries/ui/layouts/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:Toggler:Tooltip' => 'Vergroot / Verberg',
Please see https://github.com/Combodo/iTop/pull/199#pullrequestreview-624999469 and comment there..

2021-04-06 10:38 UTC, jbostoen commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:RichText:ToolbarState:Collapsed' => 'Ingeklapt~~',
I actually prefer inklappen/uitklappen. It's closer to the original meaning.
With "vergroot" I think of resizing an area by drag/drop.
Definitely make sure it's consistent in the other strings.

2021-04-06 10:38 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.core.php
> +	'Change:State_Changed_NewValue_OldValue' => 'veranderd van %2$s naar %1$s',
I'm just going by the English translation

2021-04-06 10:43 UTC, Hipska commented on dictionaries/ui/pages/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:RichText:ToolbarState:Collapsed' => 'Ingeklapt~~',
I made them different, because they have different meaning. At the other place they are used as the action (verberg) when they become in the respective state (ingeklapt).

2021-04-06 13:40 UTC, piRGoif commented
Hello,
We are currently packaging 3.0.0-beta, so this PR won't be included.
It is very likely that we will release a beta2, I'll keep you informed !

2021-04-15 07:58 UTC, piRGoif commented
Hello,
Just to let you know : [in the official communication](https://sourceforge.net/p/itop/discussion/itop_beta/thread/2a8ef9f5a2/#do-you-want-to-contribute-to-itop-translation) Combodo asked translations to be submitted by May 15th.

2021-05-25 08:59 UTC, piRGoif commented
Hello,
@Hipska dans @jbostoen any news on this PR ? We are still OK to integrate it (and many thanks for your work !!), but are you done with it ? I see it is still in draft mode, and with some unresolved conversations ?

2021-05-28 10:27 UTC, Hipska commented
Its not complete, but I think we can already include the ones that are already translated 😉

2021-05-28 12:04 UTC, piRGoif commented
Ok thanks !

2021-05-28 15:14 UTC, Molkobain approved these changes

2021-05-28 15:17 UTC, merged

2021-05-28 15:17 UTC, Molkobain commented
Thanks everyone! ✌