Feature/2982 finalize
Combodo/iTop pull request #205
Opened 2021-04-14 16:20 UTC by odain-cbd

this branch contains few fixes/enhancement on top of develop regarding theme precompilation feature (FAF from Denis).

for more information on this 3.0 optimization:
https://wiki.combodo.com/doku.php?id=latest:advancedtopics:setup_theme_precompilation&s[]=precompilation

It includes:
- few fixes + associated tests
- a way to disable precompilation from itop configuration ('theme_precompilation_enabled', true by default)
- (in developpement mode only) a way to save declared precompiled stylesheets locally in order to easily push them via git.
they must be defined in datamodel XML (precompiled_stylesheet).

cf https://wiki.combodo.com/doku.php?id=latest:customization:xml_reference&s[]=precompilation#theme_compilation

2021-04-15 12:33 UTC, steffunky commented on test/setup/ressources/datamodels/datamodel-branding.xml
> +          <import id="style3" xsi:type="utility">style3.scss</import>
If we rename `variable` xsi:type into `variables` we should consider renaming `utility` in `utilities`

2021-04-15 12:33 UTC, steffunky commented on setup/compiler.class.inc.php
> +				else
We shouldn't get rid of this condition and maybe add an exception for xsi:type that aren't  `variables` nor `utilities`

2021-04-15 14:23 UTC, odain-cbd commented on setup/compiler.class.inc.php
> +				else
yes good catch. i would make simple and consider 'utility' as default (without any exception raised).

2021-04-15 14:25 UTC, odain-cbd commented on test/setup/ressources/datamodels/datamodel-branding.xml
> +          <import id="style3" xsi:type="utility">style3.scss</import>
should we rename in XML?
- xsi:type="variable" <= xsi:type="variables"
- xsi:type="utility" <= xsi:type="utilities"

and in precompilation signature?
- imports_utility by utility_imports
- imports_variable by variable_imports

2021-04-15 21:12 UTC, Molkobain requested changes

2021-04-15 21:12 UTC, Molkobain commented on core/config.class.inc.php
> +		'theme_precompilation_enabled' => [
```suggestion
		'theme.enable_precompilation' => [
```

Do you mind if we "namespace" this param (and the future ones) so it will be easier to find / documentation parameters related to themes? It's what we tried to do on the new 3.0 parameters (eg. quick_create.xxx, activity_panel.xxx, ...)

2021-04-15 21:12 UTC, Molkobain commented on setup/compiler.class.inc.php
> +				if (utils::GetConfig()->Get('theme_precompilation_enabled')){
```suggestion
				if (utils::GetConfig()->Get('theme.enable_precompilation')){
```

Just proposing a renaming of the config. param. up to date with my previous comment

2021-04-15 21:12 UTC, Molkobain commented on setup/compiler.class.inc.php
> +	public static function setThemeHandlerService(ThemeHandlerService $oThemeHandlerService): void {
```suggestion
	public static function SetThemeHandlerService(ThemeHandlerService $oThemeHandlerService): void {
```

2021-04-15 21:12 UTC, Molkobain commented on setup/compiler.class.inc.php
> +		if (! utils::GetConfig()->Get('theme_precompilation_enabled')) {
```suggestion
		if (! utils::GetConfig()->Get('theme.enable_precompilation')) {
```

Just renaming the param to be up to date with the proposition from previous commit

2021-04-15 21:12 UTC, Molkobain commented on test/setup/MFCompilerTest.php
> +			utils::GetConfig()->Set('theme_precompilation_enabled', false);
```suggestion
			utils::GetConfig()->Set('theme.enable_precompilation', false);
```

Just renaming param. to be up to date with proposal from previous commit

2021-04-15 21:12 UTC, Molkobain commented on setup/compiler.class.inc.php
> +				else
Agree that keeping the `elseif` for `utility` and throwing an exception in an `else` could ensure people use the XML grammar correctly and will be more future proof.

2021-04-15 21:12 UTC, Molkobain commented on setup/compiler.class.inc.php
> +					if (utils::IsDevelopmentEnvironment() && ! empty(trim($sPrecompiledStylesheet)))
Thanks! 🙏

2021-04-15 21:12 UTC, Molkobain commented on setup/modelfactory.class.inc.php
> +	public function getRootDirs() {
```suggestion
	 * @return mixed
	 * @since 3.0.0
	 */
	public function GetRootDirs() {
```

Can you just add a comment on what you mean by root dirs? Root dirs of the iTop app. ?

2021-04-16 06:50 UTC, Molkobain commented on test/setup/MFCompilerTest.php
> +		MFCompiler::setThemeHandlerService($oThemeHandlerService);
```suggestion
		MFCompiler::SetThemeHandlerService($oThemeHandlerService);
```

Rename to be up to date with the previous change

2021-04-16 06:51 UTC, Molkobain commented on setup/compiler.class.inc.php
> +							foreach ($this->oFactory->getRootDirs() as $sRootDir) {
```suggestion
						$aRootDirs = $this->oFactory->GetRootDirs();
						if (is_array($aRootDirs) && count($aRootDirs) !== 0) {
							foreach ($this->oFactory->GetRootDirs() as $sRootDir) {
```

Rename to be up to date with other comment

2021-04-16 09:45 UTC, odain-cbd commented on setup/compiler.class.inc.php
> +				else
I am not so confident on raising exception in setup context. if you are, I let you add this...

2021-04-16 10:03 UTC, odain-cbd commented on test/setup/ressources/datamodels/datamodel-branding.xml
> +          <import id="style3" xsi:type="utility">style3.scss</import>
signature renaming done

2021-04-16 11:19 UTC, Molkobain commented on setup/compiler.class.inc.php
> +				else
In that case, we could use the compiler logging system (`$this->Log('blahblah');`) to log a message explaining why the node has been ignored, which would be -IMHO- cleaner than accepting unknown types.

2021-04-16 12:04 UTC, merged