improved chinese for 3.0
Combodo/iTop pull request #207
Opened 2021-04-15 10:29 UTC by purplegrape

improved chinese for 3.0

2021-04-15 12:02 UTC, piRGoif commented
No conflicts this time, thanks !
We will review your contribution

2021-04-15 12:22 UTC, piRGoif requested changes
Many thanks for all of this work !
I've just add some remarks, mainly on the `ITOP_APPLICATION` constant and some few things

2021-04-15 12:22 UTC, piRGoif commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Organization:Overview:Users' => '该组织里所有的 iTop用户',
Please use the `ITOP_APPLICATION` constant instead of the hardcoded 'iTop' string. 

I know this is not done yet in other languages but this is something we will add in all translations soon !
Also, there aren't any constant for 'iTop Hub' now, whereas this is present in some keys.

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Hotkey' => 'Alt + M',
This wasn't in the original file nor in other languages files. Can you remove this key ?

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:UserInfo:WelcomeMessage:Text' => 'Hi %1$s!',
Are you sure this is the correct translation ? (you did remove the trailing "~~")

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 iTop', // Duplicated into itop-welcome-itil (will be removed from here...)
Same, please use `ITOP_APPLICATION`

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:Title' => '欢迎使用 iTop',
Again, please use `ITOP_APPLICATION`

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:ResetPwd-EmailSubject' => '重置 iTop 密码',
You may had already guest I was going to comment about `ITOP_APPLICATION` ? ;o)

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:LogOff:ThankYou' => '感谢使用 iTop',
ITOP_APPLICATION instead of iTop

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeToITop' => '欢迎使用 iTop ',
`ITOP_APPLICATION` instead of iTop

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:About:Title' => '关于 iTop',
`ITOP_APPLICATION` instead of iTop

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenuPage+' => '欢迎使用 iTop',
`ITOP_APPLICATION` instead of iTop

2021-04-15 12:22 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 iTop',
`ITOP_APPLICATION` instead of iTop

2021-04-16 01:47 UTC, purplegrape commented on dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:UserInfo:WelcomeMessage:Text' => 'Hi %1$s!',
yes，I am sure.  
every chinese people could understand "Hi" or "Hello" though it's not native

2021-04-16 01:55 UTC, purplegrape commented on dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Hotkey' => 'Alt + M',
have removed

2021-04-16 01:56 UTC, purplegrape commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Organization:Overview:Users' => '该组织里所有的 iTop用户',
OK

2021-04-16 01:59 UTC, purplegrape commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 iTop',
please review 4fc5182
use ITOP_APPLICATION  instead of iTop

2021-04-16 06:37 UTC, piRGoif commented on dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:UserInfo:WelcomeMessage:Text' => 'Hi %1$s!',
Ok, well noted ! 
So I'm closing this conversation

2021-04-16 06:39 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 iTop', // Duplicated into itop-welcome-itil (will be removed from here...)
Was done in 4fc51820

2021-04-16 06:40 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:Title' => '欢迎使用 iTop',
Was done in 4fc51820

2021-04-16 06:40 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:ResetPwd-EmailSubject' => '重置 iTop 密码',
This one is still present...

2021-04-16 07:02 UTC, piRGoif requested changes
All my apologies, I made a mistake, it's `ITOP_APPLICATION_SHORT`that should be used and not `ITOP_APPLICATION`
Also, you replaced "iTop" with "ITOP_APPLICATION", but as this is a constant there is some little things to change in the syntax also.

To ease modifications I added suggestions, you should be able to integrate them with just a click !

2021-04-16 07:02 UTC, piRGoif commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Organization:Overview:Users' => '该组织里所有的 ITOP_APPLICATION 用户',
```suggestion
	'Organization:Overview:Users' => '该组织里所有的 '.ITOP_APPLICATION_SHORT.' 用户',
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 ITOP_APPLICATION', // Duplicated into itop-welcome-itil (will be removed from here...)
```suggestion
	'Menu:WelcomeMenu+' => '欢迎使用 '.ITOP_APPLICATION_SHORT, // Duplicated into itop-welcome-itil (will be removed from here...)
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenuPage+' => '欢迎使用 ITOP_APPLICATION', // Duplicated into itop-welcome-itil (will be removed from here...)
```suggestion
	'Menu:WelcomeMenuPage+' => '欢迎使用 '.ITOP_APPLICATION_SHORT, // Duplicated into itop-welcome-itil (will be removed from here...)
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:Title' => '欢迎使用 ITOP_APPLICATION',
```suggestion
	'UI:WelcomeMenu:Title' => '欢迎使用 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:Login:Welcome' => '欢迎使用 iTop!',
```suggestion
	'UI:Login:Welcome' => '欢迎使用 '.ITOP_APPLICATION_SHORT.'!',
```

2021-04-16 07:02 UTC, piRGoif commented on datamodels/2.x/itop-hub-connector/dictionaries/zh_cn.dict.itop-hub-connector.php
> +	'iTopHub:DBBackupSentence' => '在升级之前,备份数据库和 iTop 配置文件',
```suggestion
	'iTopHub:DBBackupSentence' => '在升级之前,备份数据库和 '.ITOP_APPLICATION_SHORT.' 配置文件',
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:ResetPwd-EmailSubject' => '重置 iTop 密码',
```suggestion
	'UI:ResetPwd-EmailSubject' => '重置 '.ITOP_APPLICATION_SHORT.' 密码',
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:LogOff:ThankYou' => '感谢使用 ITOP_APPLICATION',
```suggestion
	'UI:LogOff:ThankYou' => '感谢使用 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeToITop' => '欢迎使用 ITOP_APPLICATION ',
```suggestion
	'UI:WelcomeToITop' => '欢迎使用 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:AboutBox' => '关于 ITOP_APPLICATION...',
```suggestion
	'UI:AboutBox' => '关于 '.ITOP_APPLICATION_SHORT.'...',
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:About:Title' => '关于 ITOP_APPLICATION',
```suggestion
	'UI:About:Title' => '关于 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenu+' => '欢迎使用 ITOP_APPLICATION',
```suggestion
	'Menu:WelcomeMenu+' => '欢迎使用 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 07:02 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Menu:WelcomeMenuPage+' => '欢迎使用 ITOP_APPLICATION',
```suggestion
	'Menu:WelcomeMenuPage+' => '欢迎使用 '.ITOP_APPLICATION_SHORT,
```

2021-04-16 08:58 UTC, piRGoif approved these changes
I've submitted some other changes that were forget
Now seems OK to me 👌
Many thanks for all the work @purplegrape 👏 !

2021-04-16 09:00 UTC, merged