N°3968 - Fixed mutex being silently released after wait_timeout seconds
Combodo/iTop pull request #209
Opened 2021-04-20 15:56 UTC by dflaven

iTop Mutexes are based on the MySQL GET_LOCK() command. This command creates a server-side lock which is released either by calling RELEASE_LOCK() or when the connection to the MySQL server ends (which is handy in case of a PHP crash).

However, when a MySQL connection remains idle for a certain time (defined by the server parameter **wait_timeout**), it gets automatically closed by MySQL.

Since each iTop mutex uses its own MySQL connection (which sees no further commands once the lock is acquired), a "locked" Mutex is automatically  (and silently) released after wait_timeout seconds.

Thi spull request ensures that the wait_timeout _for the connection used by the mutex_ is at least 86400 seconds (1 day).

2021-04-20 15:58 UTC, Hipska commented
Maybe not needed if it wouldn't have its own connection? Is there any conflict why they have their own connection?

2021-04-20 16:06 UTC, Hipska requested changes

2021-04-20 16:06 UTC, Hipska commented on core/mutex.class.inc.php
> +		if ($aRow = mysqli_fetch_array($result, MYSQLI_BOTH))
Using the default (both) while using only numeric value.
```suggestion
		if ($aRow = mysqli_fetch_array($result, MYSQLI_NUM))
```

2021-04-20 16:06 UTC, Hipska commented on core/mutex.class.inc.php
> +		    mysqli_free_result($result);
Not needed here, since it is executed anyway after the else block.

2021-04-20 16:06 UTC, Hipska commented on core/mutex.class.inc.php
> +		    throw new Exception("No result for query '".$sSql."'");
Would this ever occur? And does it need to kill the application? What about setting `$iTimeout` to zero then?

2021-04-21 06:42 UTC, piRGoif commented
> Maybe not needed if it wouldn't have its own connection? Is there any conflict why they have their own connection?

I wasn't absolutely sure why, but I think this is because : 

> Before MySQL 5.7, only a single simultaneous lock can be acquired
Source https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html

Also on the same page : 

> A lock obtained with GET_LOCK() is released explicitly by executing RELEASE_LOCK() or implicitly when your session terminates

The connection in CMDBSource shouldn't be closed, but by having independent connections this is something less to worry about ;)

We should add a comment in the code explaining why indeed !

2021-04-21 09:09 UTC, Hipska commented
Okay, and 2.7 still asks for minimal MySQL 5.6 so indeed, that can't be changed yet. Might be something to consider for 3.0 though 😉

2021-06-21 10:03 UTC, piRGoif commented on core/mutex.class.inc.php
> +		    mysqli_free_result($result);
@eespie and I are OK to leave it like that
Closing this conversation

2021-06-21 10:04 UTC, piRGoif commented on core/mutex.class.inc.php
> +		    throw new Exception("No result for query '".$sSql."'");
Good question
Indeed if this occurs we are in trouble :D 
We prefer to keep it this way

2021-06-21 10:28 UTC, piRGoif commented on core/mutex.class.inc.php
> +		if ($aRow = mysqli_fetch_array($result, MYSQLI_BOTH))
Thanks for the suggestion, but I'm not absolutly sure of the real benefits, and as there was already manual tests done with the current code I'm worried changing this could cause regressions : I'm keeping code like this for now.

2021-06-21 10:33 UTC, merged

2021-06-21 10:34 UTC, Hipska commented on core/mutex.class.inc.php
> +		if ($aRow = mysqli_fetch_array($result, MYSQLI_BOTH))
Memory optimisation: `$aRow`
before:
```
array(2) {
  [0]=>
  string(5) "12345"
  ["wait_timeout"]=>
  string(5) "12345"
}
```
after:
```
array(1) {
  [0]=>
  string(5) "12345"
}
```

See [docs](https://www.php.net/manual/en/mysqli-result.fetch-array.php)

2021-06-21 12:00 UTC, piRGoif commented on core/mutex.class.inc.php
> +		if ($aRow = mysqli_fetch_array($result, MYSQLI_BOTH))
Thanks !
Keeping this in mind for next similar operations