Update CONTRIBUTING.md with thanks stickers
Combodo/iTop pull request #213
Opened 2021-05-12 12:24 UTC by Molkobain

Hey everyone,

We just made some stickers to thank all the contributors of the iTop ecosystem, here is a PR to prepare the contributing guide. Feel free to help modeling the sentences as I'm having an hard time finding a good sentence 😅
Once this is done, we will contact all contributors from this year to get their email / postal address so we can send them to them.

Depending on how this go, we might add more kind of stickers in the near future.

Cheers ✌

*Note: Please don't tell us you want to change the stickers design as they are already printed 😁*

2021-05-12 12:25 UTC, Molkobain commented
(Will I get 1 for making this PR? 🤔)

2021-05-12 12:29 UTC, Molkobain commented
@jbostoen @Hipska @larhip @purplegrape @DudekArtur @nv35 @samsk @annProg @vbkunin @lazki feel free to comment and to send us your postal address at guillaume.lajarige (at) combodo (dot) com

2021-05-12 12:30 UTC, Hipska submitted a review, later dismissed

2021-05-12 14:15 UTC, piRGoif requested changes, later dismissed
Bravooooooo for this great initiative !
I can suggest some changes in the formulation though O:)

2021-05-12 14:15 UTC, piRGoif commented on CONTRIBUTING.md
> -
Can you revert this unrelated change ?

2021-05-12 14:15 UTC, piRGoif commented on CONTRIBUTING.md
> +### 🙏 We are thankful
I'm not very found of this title

Maybe simply : 

```suggestion
### 🙏 Many thanks to our great contributors !!
```

2021-05-12 14:15 UTC, piRGoif commented on CONTRIBUTING.md
> +We are thankful for all your contributions to the iTop universe, here are the 2021 stickers that will be sent to every iTop (& extensions) contributors this year. Design might change from one year to
My suggestion : 

```suggestion
We are thankful for all your contributions to the iTop universe ! As a thank you gift, we will send to every iTop (& extensions) contributors nice stickers ! 

Stickers' design might change from one year to another. For the first year we wanted to try a "craft beer label" look, see examples below : 
```

2021-05-12 14:30 UTC, larhip submitted a review, later dismissed

2021-05-12 14:32 UTC, Hipska commented on CONTRIBUTING.md
> +We are thankful for all your contributions to the iTop universe, here are the 2021 stickers that will be sent to every iTop (& extensions) contributors this year. Design might change from one year to
"we will send nice stickers to every.." 😉

2021-05-12 15:01 UTC, piRGoif commented on CONTRIBUTING.md
> +We are thankful for all your contributions to the iTop universe, here are the 2021 stickers that will be sent to every iTop (& extensions) contributors this year. Design might change from one year to
I've changed the suggestion, thanks !

2021-06-02 18:36 UTC, Molkobain commented on CONTRIBUTING.md
> +### 🙏 We are thankful
I'm not fond of the multiple "!", it's too much for me 😅
Also we already say "... thankful for all the contributions ..." in the following line so it feels redundant to me.

2021-06-02 18:36 UTC, Molkobain commented on CONTRIBUTING.md
> +We are thankful for all your contributions to the iTop universe, here are the 2021 stickers that will be sent to every iTop (& extensions) contributors this year. Design might change from one year to
This sounds ok to me if:
- We remove the space before the 2 "!" and the ":"
- Replace "send nice stickers" by "send stickers" as the "nice" feels a bit pretentious to 😁

2021-06-03 06:30 UTC, piRGoif commented on CONTRIBUTING.md
> +We are thankful for all your contributions to the iTop universe, here are the 2021 stickers that will be sent to every iTop (& extensions) contributors this year. Design might change from one year to
Hello,

Here is the amended modification : 

```suggestion
We are thankful for all your contributions to the iTop universe! As a thank you gift, we will send stickers to every iTop (& extensions) contributors! 

Stickers' design might change from one year to another. For the first year we wanted to try a "craft beer label" look, see examples below: 
```

2021-06-03 07:52 UTC, steffunky approved these changes

2021-06-03 07:53 UTC, merged

2021-07-03 08:59 UTC, Molkobain commented
> @jbostoen @Hipska @larhip @purplegrape @DudekArtur @nv35 @samsk @annProg @vbkunin @lazki feel free to comment and to send us your postal address at guillaume.lajarige (at) combodo (dot) com

Hello @purplegrape @DudekArtur @nv35 @samsk @annProg, mind to send us an email if you us to send them to you :)

2021-07-07 07:36 UTC, annProg commented
@Molkobain Please just send me electronic version（may be photo or scanning copy) to  tecbbs(at)qq(dot)com. Thanks!

2021-07-07 07:47 UTC, Hipska commented
@annProg digital original for the stickers is available in this PR or here: [![documentation/contributing-guide/contributing-stickers-side-by-side.png](https://github.com/Combodo/iTop/raw/develop/documentation/contributing-guide/contributing-stickers-side-by-side.png)](https://github.com/Combodo/iTop/blob/develop/documentation/contributing-guide/contributing-stickers-side-by-side.png)

2021-07-07 07:59 UTC, Molkobain commented
> @Molkobain Please just send me electronic version（may be photo or scanning copy) to tecbbs(at)qq(dot)com. Thanks!

Thanks, I just sent you the images in a better quality. Cheers!

2021-07-07 08:11 UTC, annProg commented
@Molkobain @Hipska I have received the email, thank you very much!

2021-07-13 05:30 UTC, purplegrape commented
@Molkobain  I just wanna a electronic version too,please send mail to purplegrape4(at)gmail(dot)com ,many thanks!

2021-07-13 07:25 UTC, Molkobain commented
> purplegrape4(at)gmail(dot)com

Thanks you! The email has just been sent.