If php memory_limit is lower than 256M, set 256M. If it's greater do …
Combodo/iTop pull request #215
Opened 2021-05-20 14:48 UTC by BGdu38

My memory_limit is set to 512M, but for csv import memory limit is hard coded in iTop.

2021-05-20 14:59 UTC, Hipska requested changes
iTop already has a helper method for that, so the code should be like:
```php
if (utils::ConvertToBytes(ini_get('memory_limit')) < '268435456') {
```
But it should be moved to after the includes in that case.

Question to combodo: Should `ini_set` actually happen?

2021-05-20 15:23 UTC, piRGoif commented
Hello,
Many thanks for this contribution !
This is a known limitation, that is referenced in Combodo internal db as N°3806. The fix is planned for 2.7.5 but as low priority, so it might not make its way to this version ? We'll see in the upcoming weeks as the development has just started.
I'm putting this PR on hold for now, as this may not be the solution that will be chosen ?

2021-05-20 15:24 UTC, Molkobain commented
> iTop already has a helper method for that, so the code should be like:
> 
> ```
> if (utils::ConvertToBytes(ini_get('memory_limit')) < '268435456') {
> ```

Indeed using the `utils::ConvertToBytes()` method is indeed a good practice, good catch.

> But it should be moved to after the includes in that case.

Not sure to follow? It was already before them.

2021-05-20 15:52 UTC, Hipska commented
> > But it should be moved to after the includes in that case.
> 
> Not sure to follow? It was already before them.

Well, the helper method needs to be loaded in php before it can be used. Currently the `ini_set` is before all the loading.

2021-05-20 17:10 UTC, Molkobain commented
> > Not sure to follow? It was already before them.
> 
> Well, the helper method needs to be loaded in php before it can be used. Currently the `ini_set` is before all the loading.

Right! I thought you were saying the `ini_set` itself had to be before.

2021-05-21 08:34 UTC, piRGoif commented
Using utils::ConvertToBytes would be a good idea indeed ! But Hipska you're right, we need to mind to call it AFTER the required calls, whereas the ini_set is currently before them.

Searching for other memory_limit occurrences, I found all of those ini_set calls : 
* csvimport.php of course O:)
* pages/ajax.render.php (operation "xlsx_run")
* setup/ajax.dataloader.php
* webservices/backoffice.dataloader.php

I will reference this in our internal ticket !

Also, in the setup (\SetupUtils::CheckPhpAndExtensions) we have a call to `\utils::IsMemoryLimitOk`, I think this should be the one to call !

2021-05-21 08:48 UTC, piRGoif commented
Also this PR is based and develop... We will certainly do a cherry pick manually to integrate it :/

2021-05-21 09:23 UTC, piRGoif commented
I've just wrote a proposition, I've contacted @BGdu38, awaiting for his answer.

2021-05-21 13:06 UTC, Hipska commented on application/utils.inc.php
> +
Seems not relevant for this PR?

2021-05-21 13:21 UTC, piRGoif commented on application/utils.inc.php
> +
You're right ! The formatter usually does this kind of things, modifying only modified lines... but just a few extra more. That was the case here also, it just added some formatting on existing code just above modified lines.

2021-05-21 13:21 UTC, piRGoif commented
I've pushed my modifications.
Comments & reviews are welcome !

2021-05-21 13:22 UTC, Hipska requested changes

2021-05-21 13:22 UTC, Hipska commented on application/utils.inc.php
> +	}
```suggestion
	 * @param int $iMemoryLimit set limit in bytes
	 * @param int $iRequiredLimit required limit in bytes
	 *
	 * @return bool
	 */
	public static function IsMemoryLimitOk($iMemoryLimit, $iRequiredLimit)
	{
		return ($iMemoryLimit >= $iRequiredLimit) || ($iMemoryLimit == -1);
	}
```

2021-05-21 13:22 UTC, Hipska commented on application/utils.inc.php
> +		if (($iMemoryLimit >= $iRequiredLimit) || ($iMemoryLimit === -1)) {
```suggestion
		if (static::IsMemoryLimitOk($iMemoryLimit, $iRequiredLimit)) {
```

2021-05-21 13:22 UTC, Hipska commented on test/application/UtilsTest.php
> +			'512M' => ['512M', 512 * 1024 * 1024],
Also add test for other options:
```suggestion
			'123' => ['123', 123],
			'56k' => ['56k', 56 * 1024],
			'512M' => ['512M', 512 * 1024 * 1024],
			'2G' => ['2G', 2 * 1024 * 1024 * 1024],
```

2021-05-21 14:47 UTC, piRGoif commented on application/utils.inc.php
> +		if (($iMemoryLimit >= $iRequiredLimit) || ($iMemoryLimit === -1)) {
Wooops !! I feel quite shamy huhu
Thanks, good catch !

2021-05-21 14:48 UTC, piRGoif commented on application/utils.inc.php
> +		if (($iMemoryLimit >= $iRequiredLimit) || ($iMemoryLimit === -1)) {
Also havin a strict comparison with -1 is a good think, I'll add it in another commit

2021-05-21 14:53 UTC, Hipska approved these changes, later dismissed

2021-05-21 15:38 UTC, Molkobain approved these changes, later dismissed

2021-05-25 09:19 UTC, piRGoif commented
Rebased the branch using `git rebase --onto support/2.7 develop PR/215_memory_limit`.
Then changed the base branch for the PR.

Ready to merge !

2021-05-25 10:03 UTC, merged

2021-05-25 10:03 UTC, Hipska approved these changes