N°3863 - exec.php : allow subdirectories in the page parameter
Combodo/iTop pull request #221
Opened 2021-07-08 12:42 UTC by piRGoif

For now, exec.php can only call pages at the root level of modules. This is caused by basename() calls on both page and module parameters.

This PR brings the possibility to call pages in the whole module hierarchy, still using `\utils::RealPath` to ensure we're not trying to access something outside of the module.

2021-07-08 15:06 UTC, Hipska submitted a review, later dismissed

2021-07-08 15:07 UTC, Hipska commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
Not `3.x` for new major iTop release?

2021-07-08 16:30 UTC, piRGoif commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
No we didn't changed the directory name, see https://github.com/Combodo/iTop/tree/develop/datamodels
Indeed there was just some little refactoring (like the itop-structure module creation) but no revolution : same iTop objects and attributes.

2021-08-06 13:18 UTC, piRGoif commented
Dev team review conclusions : 
* the new behavior should be explicitly enabled (white list of the modules, or better an option in the module.*.php file !)
* there is already an existing provider for the extension locations : \ModelFactory::GetRootDirs
* does a test exist for utils::RealPath ?
* add a test for CheckPageExists !

2021-08-09 11:57 UTC, Molkobain commented
Did you ask @dflaven about why he didn't enable this in the beginning? It might have been on purpose.

2021-08-09 12:05 UTC, piRGoif commented
I talk about this with @rquetiez who made this originally.
This code is very old, and now we have \utils::RealPath \o/

2021-08-09 13:24 UTC, Molkobain commented on pages/exec.php
> -$sModule = basename($sModule); // protect against ../.. ...
Did we loose this protection?
I understand the need to drill through the folders of the module, but we *must not* be able to execute something outside of the iTop folder (eg. `../../../home/foo/malicious.php`)

2021-08-09 13:25 UTC, Molkobain commented on pages/exec.php
> -$sPage = basename($sPage); // protect against ../.. ...
Same comment as above

2021-08-09 14:46 UTC, piRGoif commented on pages/exec.php
> -$sModule = basename($sModule); // protect against ../.. ...
We are now calling CheckPageExists function, which calls utils::RealPath
This later ensure we won't allow to access files in the directories above in the hierarchy

2021-08-09 17:49 UTC, Molkobain commented on pages/exec.php
> -$sModule = basename($sModule); // protect against ../.. ...
Thanks! 👌
I saw the call of `utils::RealPath` but didn't noticed that it was actually checking that the filepath was contained in the basepath; preventing that kind a vulnerability; my bad 🙈

2021-08-09 17:54 UTC, Molkobain approved these changes

2021-08-09 17:57 UTC, Molkobain commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
This means that the extensions made using this feature won't work on the iTop used internally at Combodo (poke @v-dumas ) and on other legacy packages. It might worth it to test for both 1.x and 2.x folders?

2021-08-10 06:25 UTC, v-dumas commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
Do not put any code inside iTop which would not be compatible with legacy packages, that would be too much of a nightmare for the legacies...

2021-08-10 07:23 UTC, Molkobain requested changes

2021-08-10 07:23 UTC, Molkobain commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
```suggestion
APPROOT.'datamodels/1.x', // Compatibility with legacy packages
APPROOT.'datamodels/2.x',
```

2021-08-10 07:34 UTC, piRGoif commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
Good point, thanks ! This should be solved by using \ModelFactory::GetRootDirs

2021-08-10 07:36 UTC, piRGoif commented on pages/exec.php
> -$sModule = basename($sModule); // protect against ../.. ...
No prb, better check twice this kind of things O:)

2021-12-23 15:43 UTC, piRGoif commented
Rebased branch

2021-12-23 15:47 UTC, Hipska commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
But it still isn't

2021-12-23 15:57 UTC, piRGoif commented on pages/exec.php
> +		APPROOT.'datamodels/2.x', // warning, won't work for datamodels/1.x for example !
Should be solved in 53a2fe2e

2021-12-23 16:26 UTC, Hipska approved these changes

2022-01-04 09:34 UTC, Molkobain approved these changes

2022-01-04 15:30 UTC, Molkobain commented
Accepted in technical team review

2022-01-11 15:31 UTC, Molkobain commented
Accepted in functional team review.

2022-01-12 16:23 UTC, piRGoif commented
This new feature needs to be documented, but this will be done later on, and the follow-up will be done using the Combodo private ticketing system.
I'm merging !

2022-01-12 16:24 UTC, merged