🐛 Allow setting of itop_env $_SESSION variable if $_SESSION is still empty (SF1976)
Combodo/iTop pull request #223
Opened 2021-07-12 06:45 UTC by jbostoen

* https://sourceforge.net/p/itop/tickets/1976/

This adds missing logic (I've put it on a separate line).
The startup process allows the user to explicitly use the **switch_env** parameter to change the environment if the configuration file exists and if it's not the same as what's already in the `$_SESSION['itop_env']` variable.

Original logic (relevant part on new line) checks whether the `$_SESSION['itop_env']` is set, probably even just to avoid a warning in the comparison part if the `$_SESSION['itop_env']` has NOT been set yet.
```
if (($sSwitchEnv != null) && (file_exists(APPCONF.$sSwitchEnv.'/'.ITOP_CONFIG_FILE)) && 
	(isset($_SESSION['itop_env']) && ($_SESSION['itop_env'] !== $sSwitchEnv))
)
```

But if people use the iTop REST/JSON API, definitely on the first call the `$_SESSION['itop_env']` has not been set yet. So you can not override the environment when using the API.

The fix is easy: allow this override if the variable has not been set yet (= also 'not equal to' the value of the variable).
```
if (($sSwitchEnv != null) && (file_exists(APPCONF.$sSwitchEnv.'/'.ITOP_CONFIG_FILE)) && 
	((isset($_SESSION['itop_env']) && ($_SESSION['itop_env'] !== $sSwitchEnv)) || !isset($_SESSION['itop_env']))
)
```

**Implementation risks are on the extremely low side**: it will only change things for people/processes explicitly using the switch_env parameter and if the `$_SESSION['itop_env']` has not been set yet.

The benefit is mostly for people who run multiple environments on one iTop "installation" (by installation, I mean: you can quickly grab all the code/installation package; keep all extensions you want in the web/extensions folder and run different environments on it (using the unattended install AND while still retaining the benefit of the API features).

This might be a faster way for people (probably mostly developers) to have multiple iTop (test) instances without having to set up dedicated Docker containers or similar solutions.

2021-07-12 07:14 UTC, Hipska submitted a review, later dismissed

2021-07-12 07:36 UTC, Molkobain commented
Correct me if I'm wrong but another way to summarize the purpose of this PR is to "fix the usage of the switch_env parameter in the REST/API" right? I think this way it will be way easier to sell it to the product team than "will benefits some devs" 😁🙊

2021-07-12 08:05 UTC, jbostoen commented
It does benefit anyone who uses both the API and the switch_env parameter 😁

2021-09-06 13:03 UTC, jbostoen commented
The above fix seems to work for the API.

For my use case, I was able to only put the iTop application files once on my computer and run multiple environments and connect to them with the API. Only using the switch_env URL parameter.

-

Open question is whether it should be extended. I do notice that cron jobs also lack this kind of support. There would at least need to be an additional change in the startup file so it also allows input from the CLI (switch_env). Some other refactoring is needed as well.

Before I start all that, I'm wondering if the original pull request will be accepted, as it already fixes missing logic and allows for a more flexible installation process.

2021-10-08 09:12 UTC, jbostoen commented on webservices/cron.php
> +require_once(APPROOT.'/application/startup.inc.php');
The startup line must be moved here as it defines the $sConfigFile variable; which is not always ITOP_DEFAULT_ENV.

Otherwise the check may fail if there's no regular "production" environment. It might also lead to other unwanted behavior.

2021-10-08 09:14 UTC, jbostoen commented on application/startup.inc.php
> +$sSwitchEnv = utils::ReadParam('switch_env', null, true);
'true' is to also allow the switch_env to be specified from CLI (for cron jobs)

2021-10-08 09:15 UTC, jbostoen commented on application/startup.inc.php
> -if (($sSwitchEnv != null) && (file_exists(APPCONF.$sSwitchEnv.'/'.ITOP_CONFIG_FILE)) && isset($_SESSION['itop_env']) && ($_SESSION['itop_env'] !== $sSwitchEnv))
The above condition should also consider that the session variable is simply not set; which would also mean that it is different from the environment specified using the switch_env parameter

2021-10-08 09:21 UTC, Hipska commented on application/startup.inc.php
> +$sSwitchEnv = utils::ReadParam('switch_env', null, true);
Are you now commenting your code in PR review threads? 😜 😂

2021-10-08 09:21 UTC, Hipska approved these changes

2021-10-08 09:34 UTC, jbostoen commented on application/startup.inc.php
> +$sSwitchEnv = utils::ReadParam('switch_env', null, true);
Yes, didn't want to add all of this info on the "why" in the code yet; as some of it may be overkill.

But it was the easiest way to explain some of the logic behind the changes here 😂

2022-02-01 16:15 UTC, Molkobain commented
Hello Jeffrey, this was reviewed today.

The technical team is open to approve it with the small following changes. This does not mean that it will be accepted during the functional review but it's a step forward.

**1.** Regarding the startup change, we would like you to add a unit test for the REST/API testing several environments to ensure that it works. You can check existing REST/API unit tests in iTop, as for creating a secondary environment you can check the methods used by the toolkit for example (don't use the unattended install script).

**2.** Regarding the CRON it seems alright, no changes needed, we will need to test it manually. Not great but we don't have tests for that yet.

Cheers,
Guillaume

2022-02-02 11:49 UTC, jbostoen commented
Haven't made these kind of tests before, I'll need to look into it :)

2022-02-08 10:55 UTC, Molkobain commented
Having a dedicated DB would be better as it is own it's used today by Combodo with the ITSM Designer and how you seem to be using it as well. No need to duplicate the BD content though, just create it empty if not already present. With the ITSM Designer we create a DB with the same name and a "_<ENV_NAME>" suffix.

2022-02-08 11:03 UTC, jbostoen commented
I really have no clue how to write those tests and add the custom database I'm afraid :|

2022-02-08 14:26 UTC, Hipska commented
I have the same here: #197
It would really help a lot if the GitHub PR did already the necessary CI checks, so you immediately see if your PR can be accepted.

2022-02-08 16:48 UTC, piRGoif commented
> It would really help a lot if the GitHub PR did already the necessary CI checks, so you immediately see if your PR can be accepted.

For any PHPUnit test that needs to have the datamodel loaded, I fear we cannot do much :/
And for now running any PR automatically in our test infrastructure would be risky (security)...

2022-03-09 12:13 UTC, Hipska commented
> And for now running any PR automatically in our test infrastructure would be risky (security)...

GitHub has options for that where you need to approve to run the CI for untrusted contributors. I'm using this on other repositories..

2022-03-11 07:40 UTC, jbostoen commented
Unfixed (just discovered): iTop's email action relies on the ITOP_DEFAULT_CONFIG_FILE parameter, which only seems to be used here:

* https://github.com/Combodo/iTop/blob/7c7386afc71a9191f5fdd66888fe3ec8248ceaf0/core/email.class.inc.php#L48
* https://github.com/Combodo/iTop/blob/5f575d524a7bcc7567cbc8b904204416e9b445e3/sources/Application/Status/Status.php#L86

Why should email (and status) rely on default config rather than environment config?

2022-03-11 09:12 UTC, Hipska commented
I would replace deprecate the `Email::LoadConfig` and replace this line: https://github.com/Combodo/iTop/blob/7c7386afc71a9191f5fdd66888fe3ec8248ceaf0/core/email.class.inc.php#L163

With either `self::$m_oConfig = MetaModel::GetConfig();` or even `$oConfig = MetaModel::GetConfig();`. It's even more remarkable that the constructor does use the meta model config: https://github.com/Combodo/iTop/blob/7c7386afc71a9191f5fdd66888fe3ec8248ceaf0/core/email.class.inc.php#L58-L63

For application status, I would leave it as is because of the nature of why/how it is used..

2022-03-11 09:17 UTC, Molkobain commented
Hum not sure why this was done, it might be a very old piece of code that wasn't updated to retrieve the config correctly.
Pierre might be able to tell us more about this.

2022-03-11 10:08 UTC, jbostoen commented
> I would deprecate the `Email::LoadConfig` method and replace this line:
> 
> https://github.com/Combodo/iTop/blob/7c7386afc71a9191f5fdd66888fe3ec8248ceaf0/core/email.class.inc.php#L163
> 
> With either `self::$m_oConfig = MetaModel::GetConfig();` or even `$oConfig = MetaModel::GetConfig();`. It's even more remarkable that the constructor does use the meta model config:
> 
> https://github.com/Combodo/iTop/blob/7c7386afc71a9191f5fdd66888fe3ec8248ceaf0/core/email.class.inc.php#L58-L63
> 
> For application status, I would leave it as is because of the nature of why/how it is used..

You're right, so wouldn't even need to check if MetaModel is already available. Perhaps there's cases where Email is constructed, but the "send" (and hence initial load config) only happens at a later point. You could argue the changes get picked up more instantly, but I doubt there will be use cases where this comes into play.

If you want to rely on self::$m_oConfig, it could indeed be set in the constructor.

2022-03-11 16:19 UTC, piRGoif commented
Hello,

Good catch Jeffrey, thanks !

Indeed this is old code : \EMail::LoadConfig was last modified in 87bf0999, some... 10 years ago !

We had quite a mess with retrieving the config in the whole application and extensions...
To solve most of the problems, we introduce in 2.7.0 lots of changes in \utils::GetConfig : since then this is THE method that should be used every time to get the config.

Indeed \MetaModel::GetConfig would only work if the datamodel is loaded... Whereas \utils::GetConfig has some fallbacks detailed in its phpdoc (see https://github.com/Combodo/iTop/blob/809ea2eb49bc00c6c3cad0e4544581947cf9f3e3/application/utils.inc.php#L769)
Also, if \utils::GetConfig needs to open the file directly from disk, it will use the current env, not a hardcoded one.

I've added N°4947 in Combodo internal DB, and will add a PR for this fix.

2022-03-12 08:34 UTC, jbostoen commented
Thanks for the very quick fix!

2022-05-04 18:38 UTC, jbostoen commented
Now that the mail issue has been addressed... Any ideas on how to get this approved? Basically environments are somewhat supported in iTop; this PR addresses some flaws in their implementation?

2022-05-04 20:32 UTC, Hipska commented
I would fix the merge conflicts first 😉

2022-05-05 06:01 UTC, jbostoen commented
> I would fix the merge conflicts first 😉

I'm going to wait on the feedback first before I spend time doing so. 😂

2022-05-05 06:36 UTC, piRGoif commented
Jeffrey:
> Now that the mail issue has been addressed...

Do you mean #278 ? It isn't merged yet... The decision was to merge it for 2.7.8. We are currently working on 2.7.7, so it won't be merged before second half of the year I think ?

2022-10-19 08:57 UTC, Hipska commented
That PR has been replaced with #331 and is merged already, so could @jbostoen get some feedback? Or does he need to fix the conflicts first? (as the PR is in "Pending contributor update" column)

2022-10-19 16:43 UTC, Molkobain commented
> Hello Jeffrey, this was reviewed today.
> 
> The technical team is open to approve it with the small following changes. This does not mean that it will be accepted during the functional review but it's a step forward.
> 
> **1.** Regarding the startup change, we would like you to add a unit test for the REST/API testing several environments to ensure that it works. You can check existing REST/API unit tests in iTop, as for creating a secondary environment you can check the methods used by the toolkit for example (don't use the unattended install script).
> 
> **2.** Regarding the CRON it seems alright, no changes needed, we will need to test it manually. Not great but we don't have tests for that yet.
> 
> Cheers, Guillaume

To me we are still in the "pending contributor" column waiting for the tests

2022-10-19 17:10 UTC, jbostoen commented
Thanks for the feedback! I simply have no idea how to create that kind of functional test.

2022-10-20 14:12 UTC, Molkobain commented
> Thanks for the feedback! I simply have no idea how to create that kind of functional test.

Maybe we could open a dedicated thread on the slack to bootstrap you, it would avoid to flood this PR as we might have many messages.

2022-10-21 08:27 UTC, Molkobain commented
Discussion started [here](https://itopbycombodo.slack.com/archives/C02D0C7NNQG/p1666276389307059)

2023-01-26 10:40 UTC, Hipska requested changes

2023-01-26 10:40 UTC, Hipska commented on application/startup.inc.php
> +	(Session::Get('itop_env', null) !== $sSwitchEnv || Session::Get('itop_env', null) === null)
If the session var is not set, the response will contain null and thus the first also already evaluate true.

```suggestion
	(Session::Get('itop_env', null) !== $sSwitchEnv)
```

2023-01-26 10:56 UTC, jbostoen commented on application/startup.inc.php
> +	(Session::Get('itop_env', null) !== $sSwitchEnv || Session::Get('itop_env', null) === null)
You mean the first part of the condition above?

`$sSwitchEnv = utils::ReadParam('switch_env', null, true);`

So if no switch_env is set, it would default to null.
If no itop_env is set as a session variable, it would default to null.
In this case, the condition ( null (itop_env) !== null (switch_env) ) would evaluate false, and the code would not be executed. 
Hence the second part of the condition: if no itop_env is set, forcefully do so.

But if I read the next part of the code, it would still be covered by the last "else"; but without resetting the opcache and APC.

I do think you're right, either I drop this part (since it's already covered at the end); or the last "else" doesn't really seem needed.

2023-01-26 11:00 UTC, Hipska commented on application/startup.inc.php
> +	(Session::Get('itop_env', null) !== $sSwitchEnv || Session::Get('itop_env', null) === null)
If no switch is set, this if will also not be executed, see the first condition. My suggestion only removes redundant code.

2023-01-26 11:14 UTC, jbostoen commented on application/startup.inc.php
> +	(Session::Get('itop_env', null) !== $sSwitchEnv || Session::Get('itop_env', null) === null)
I see where it comes from. Tried to adjust it to the iTop 3 logic (original PR was for iTop 2.7), so this part is indeed redundant now since it's covered in iTop's newer session implementation.

2023-06-02 13:01 UTC, Hipska commented on application/startup.inc.php
> +)
So currently the only change is just added braces and formatting? I would revert this and leave it to Combodo to handle that if needed.

2023-06-02 13:04 UTC, jbostoen commented on application/startup.inc.php
> +)
Also the more explicit default value.

2023-06-02 13:05 UTC, Hipska commented on application/startup.inc.php
> +)
Okay, missed that. Then it can stay 😉

2023-06-02 13:05 UTC, Hipska approved these changes

2023-07-26 20:22 UTC, jbostoen commented
The proposed bug fix above seems to need some additional work in iTop 3.1. It's the first thing I apply after downloading iTop for the last couple of releases. It always worked, but now it seems there's a dictionary-related issue when using the unattended install script (which seems to be unchanged for about a year in the Combodo GitHub repository).

It's initially the "trigger" class which is leading to the error.
``` 
PHP Warning:  require_once(C:\xampp64\htdocs\iTop3.1\web/env-production/dictionaries/en-us.dict.php): Failed to open stream: No such file or directory in C:\xampp64\htdocs\iTop3.1\web\core\dict.class.inc.php on line 261

Warning: require_once(C:\xampp64\htdocs\iTop3.1\web/env-production/dictionaries/en-us.dict.php): Failed to open stream: No such file or directory in C:\xampp64\htdocs\iTop3.1\web\core\dict.class.inc.php on line 261
load event servicePHP Fatal error:  Uncaught Error: Failed opening required 'C:\xampp64\htdocs\iTop3.1\web/env-production/dictionaries/en-us.dict.php' (include_path='C:\xampp64\htdocs\iTop3.1\web\lib/pear/archive_tar;C:\xampp64\htdocs\iTop3.1\web\lib/pear/console_getopt;C:\xampp64\htdocs\iTop3.1\web\lib/pear/pear-core-minimal/src;C:\xampp64\htdocs\iTop3.1\web\lib/pear/pear_exception;C:\xampp64\php\PEAR') in C:\xampp64\htdocs\iTop3.1\web\core\dict.class.inc.php:261
Stack trace:
#0 C:\xampp64\htdocs\iTop3.1\web\core\dict.class.inc.php(122): Dict::InitLangIfNeeded('EN US')
#1 C:\xampp64\htdocs\iTop3.1\web\core\contexttag.class.inc.php(139): Dict::S('Core:Context=RE...')
#2 C:\xampp64\htdocs\iTop3.1\web\core\trigger.class.inc.php(52): ContextTag::GetTags()
#3 C:\xampp64\htdocs\iTop3.1\web\core\metamodel.class.php(2953): Trigger::Init()
#4 C:\xampp64\htdocs\iTop3.1\web\core\metamodel.class.php(6486): MetaModel::InitClasses('')
#5 C:\xampp64\htdocs\iTop3.1\web\core\metamodel.class.php(6322): MetaModel::LoadConfig(Object(Config), false)
#6 C:\xampp64\htdocs\iTop3.1\web\setup\runtimeenv.class.inc.php(131): MetaModel::Startup(Object(Config), true, false, false, 'demo-authentica...')
#7 C:\xampp64\htdocs\iTop3.1\web\setup\applicationinstaller.class.inc.php(709): RunTimeEnvironment->InitDataModel(Object(Config), true)
#8 C:\xampp64\htdocs\iTop3.1\web\setup\applicationinstaller.class.inc.php(313): ApplicationInstaller::DoUpdateDBSchema(Array, 'env-demo-authen...', Array, 'demo-authentica...', '', 'https://127.0.0...')
#9 C:\xampp64\htdocs\iTop3.1\web\setup\applicationinstaller.class.inc.php(117): ApplicationInstaller->ExecuteStep('db-schema', NULL)
#10 C:\xampp64\htdocs\iTop3.1\web\toolkit\unattended_install.php(174): ApplicationInstaller->ExecuteAllSteps()
#11 {main}
  thrown in C:\xampp64\htdocs\iTop3.1\web\core\dict.class.inc.php on line 261
```

However, mind that it points to env-production rather than env-demo-authenticator.

Line 261 is unchanged:
```
$sDictFile = APPROOT.'env-'.utils::GetCurrentEnvironment().'/dictionaries/'.str_replace(' ', '-', strtolower($sLangCode)).'.dict.php';
```

So is the utils function. It's taking quite some time to debug the actual cause (did I forget something, or is it a regression). I'll try to dig deeper into this.

2024-01-27 14:35 UTC, jbostoen commented
Full disclosure: all of the above works very well.

But when signing out, it seems iTop somehow takes some of the config of the alternative environment (in this case, I'm logging out from an environment named "demo-mfa"); and then tries to load files from "env-production".

```
Fatal error: Uncaught Twig\Error\LoaderError: The "C:\Personal\htdocs\iTop3.1\web/env-production/jb-login-authenticator/templates/" directory does not exist ("C:\Personal\htdocs\iTop3.1\web/env-production/jb-login-authenticator/templates/"). in C:\Personal\htdocs\iTop3.1\web\lib\twig\twig\src\Loader\FilesystemLoader.php:92 Stack trace: #0 C:\Personal\htdocs\iTop3.1\web\lib\twig\twig\src\Loader\FilesystemLoader.php(78): Twig\Loader\FilesystemLoader->addPath('C:\\Personal\\htd...', '__main__') #1 C:\Personal\htdocs\iTop3.1\web\application\logintwig.class.inc.php(224): Twig\Loader\FilesystemLoader->setPaths(Array) #2 C:\Personal\htdocs\iTop3.1\web\application\loginwebpage.class.inc.php(377): LoginTwigRenderer->__construct() #3 C:\Personal\htdocs\iTop3.1\web\pages\logoff.php(107): LoginWebPage->DisplayLogoutPage(false) #4 {main} thrown in C:\Personal\htdocs\iTop3.1\web\lib\twig\twig\src\Loader\FilesystemLoader.php on line 92

iTop: An error occurred, check server error log for more information.
```

It seems the environment variable is removed too soon somewhere (perhaps the entire cookie or sth gets removed rather than just user credentials)

2024-02-10 14:12 UTC, jbostoen commented
The REST client from the data collector would also need a small adjustment to support environments.

2024-07-15 08:33 UTC, Hipska approved these changes

2024-07-15 08:33 UTC, Hipska commented on application/startup.inc.php
> +
```suggestion
```

2024-09-04 08:20 UTC, Hipska approved these changes

2024-09-04 08:20 UTC, Hipska commented on application/startup.inc.php
> +$sSwitchEnv = utils::ReadParam('switch_env', null, true);
```suggestion
$sSwitchEnv = utils::ReadParam('switch_env', null, true);
```

2024-09-04 08:55 UTC, Hipska approved these changes

2024-09-04 08:55 UTC, Hipska commented on application/startup.inc.php
> +)
Please mark as resolved, I cannot do that myself.

2025-02-07 11:42 UTC, jbostoen commented
Something I discovered just now: the REST service calls reset session at some point. 

So while you can initially perfectly connect to your intended environment *and* it takes the config (e.g. database settings etc) from that environment, it gets forcefully reset.
https://github.com/Combodo/iTop/blob/e85ec6bb470e309bbbf1e99ca595088bb051b817/webservices/rest.php#L101

https://github.com/Combodo/iTop/blob/e85ec6bb470e309bbbf1e99ca595088bb051b817/application/loginwebpage.class.inc.php#L398 

Also interesting to note that a lot of the calls to this method happen with "true" as parameter; while the method doesn't expect any parameters?

2026-03-06 09:58 UTC, jf-cbd reviewed
Since this PR is pretty old (sorry for the delay), we'll also check with the product team if these changes are (still) wanted.

2026-03-06 09:58 UTC, jf-cbd commented on webservices/cron.php
How do you compute $sConfigFile depending on the environment ?

2026-03-06 09:58 UTC, jf-cbd commented on pages/logoff.php
This is to allow user to have a logout page allowing to reconnect to the same environment, right ?
What is the use case ?
Could you please explain to us what is the purpose of the Unset ?

2026-03-06 10:09 UTC, jbostoen commented on webservices/cron.php
The logic remains the same as it's determined in startup.class.inc.php

2026-03-06 10:16 UTC, jbostoen commented on pages/logoff.php
The question here would be in terms of the login page.

If I previously indicated I want to access a certain iTop environment (which I can also do when unauthenticated, e.g. login page): in my opinion, it should not "forget" this when signing out.

It means that e.g., as a user:
* I navigate to a specific iTop environment (unauthenticated, but a deliberate choice.)
* This iTop environment has custom branding on the login page, so there's a clear difference.
* I sign in.
* I sign out.
* IMHO - we should still be on the specific iTop environment (e.g. with the custom branding) rather than on the "default" (production) one.

2026-04-23 13:19 UTC, closed without merging

2026-04-23 13:19 UTC, jf-cbd commented
As discussed with @jbostoen in private, this bug has been refused. Sorry again for closing this bug where you've been answering us actively 😔