Feature/dict apcu bug
Combodo/iTop pull request #224
Opened 2021-07-28 09:38 UTC by Molkobain

Creating this PR on behalf of @odain-cbd for an easier review

2021-08-09 07:55 UTC, Hipska commented on core/apc-service.class.inc.php
> +		return $this->function_exists($function_name);
That doesn't look good?

2021-08-09 07:55 UTC, Hipska commented on core/dict.class.inc.php
> +		if (self::GetApcService()->function_exists('apc_fetch')
Why still using `function_exists`. The function will always exist because of `/core/apc-emulation.php`. This is one of the cleanup actions to be done..

2021-08-09 07:55 UTC, Hipska commented on core/apc-service.class.inc.php
> +class ApcService {
What is the added value for this class?

2021-08-09 12:57 UTC, odain-cbd commented on core/apc-service.class.inc.php
> +class ApcService {
nothing fonctional. only testability. 

with this class we are able to isolate the piece of code to test and mock the outside services (here ApcService) used by it.

2021-08-10 07:47 UTC, odain-cbd commented on core/dict.class.inc.php
> +		if (self::GetApcService()->function_exists('apc_fetch')
I am not aware of cleanup action. thanks for the reminder.

but still I prefer to make something robust and clear for everybody. i still will keep function_exists to make clear that refactoring was made for testability purpose only. 3.0 is coming and we cannot afford any regression. 

when we will start cleanup actions this one will disappear with the others.

2021-09-09 09:27 UTC, Hipska requested changes

2021-09-09 09:27 UTC, Hipska commented on core/apc-service.class.inc.php
> +	 * @return mixed
```suggestion
	 * @see apc_fetch
```

2021-09-09 09:27 UTC, Hipska commented on core/apc-service.class.inc.php
> +	 * @return array|bool
```suggestion
	 * @see apc_store
```

2021-11-09 16:06 UTC, odain-cbd commented on core/apc-service.class.inc.php
> +		return $this->function_exists($function_name);
good point. it could not work.... i will fix

2021-11-24 14:29 UTC, piRGoif requested changes
Please fix the PHPUnit tests

2021-11-24 14:29 UTC, piRGoif commented on test/core/dictTest.php
> +		$this->sEnvName = date("c");
This isn't working on Windows, and I assume on many FS.
Sample directory name generated on my Windows env : `C:\Dev\wamp64\www\itop-27/env-2021-11-24T14:25:55+00:00/dictionaries/fr-fr.dict.php`

2021-11-24 14:29 UTC, piRGoif commented on test/core/dictApcuTest.php
> +		$this->sEnvName = date("c");
Same problem on both test : this isn't working on Windows

2021-11-24 15:10 UTC, Hipska commented on core/apc-service.class.inc.php
> +	 * @return mixed
Still need to remove the old `@param` and `@return` no?

2021-11-24 15:52 UTC, piRGoif commented on core/apc-service.class.inc.php
> +	 * @return mixed
I like the `@see` ! +1 to add it
I would keep the `@param` anyway, as it helps the IDE a lot :)

@odain warning, your `@param` order is reversed. See https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/param.html#param

I'm re-opening this thread

2021-11-24 16:04 UTC, Hipska commented on core/apc-service.class.inc.php
> +	 * @return mixed
I was under the impression, the IDE would fill them in that case. But if not, then please reuse the same description as the referenced function.

According to phpdoc reference it should even be `@see api_fetch()`.

2021-11-26 08:11 UTC, odain-cbd commented on test/core/dictTest.php
> +		$this->sEnvName = date("c");
i will use DIRECTORY_SEPARATOR for path compliancy with Windows

2021-11-26 08:12 UTC, odain-cbd commented on test/core/dictApcuTest.php
> +		$this->sEnvName = date("c");
idem

2021-11-26 08:18 UTC, odain-cbd commented on core/apc-service.class.inc.php
> +	 * @return mixed
phpdoc fixed based on your remarks. thank you.

2021-11-26 17:07 UTC, piRGoif requested changes

2021-11-26 17:07 UTC, piRGoif commented on core/dict.class.inc.php
> +				IssueLog::Warning("APCu corrupted data (with $sLangCode dictionnary). APCu configuration and running version should be troubleshooted...");
```suggestion
				IssueLog::Error("APCu corrupted data (with $sLangCode dictionnary). APCu configuration and running version should be troubleshooted...", LogChannels::APC);
```

2021-11-26 17:07 UTC, piRGoif commented on core/dict.class.inc.php
> +			IssueLog::Error("Cannot find $sLangCode in dictionnaries. default labels displayed", LogChannels::APC);
We made a mistake, this isn't the log that needs to be changed. The correct one is in InitLangIfNeeded (see my comment below).

Now I am wondering what is the purpose of this log, as it may happen that we are loading a dict key before the local cache is populated ?

2021-11-29 08:25 UTC, odain-cbd commented on core/dict.class.inc.php
> +			IssueLog::Error("Cannot find $sLangCode in dictionnaries. default labels displayed", LogChannels::APC);
this log can appear when there is an inconsistent dictionnary file. like declaring lables for french in a ru-ru dictionnary file path...

2021-12-02 08:35 UTC, Molkobain commented
All good for me, I'm more confortable with not changing the app behavior for a third-party failure that can be upgrade. The choosen solution (logging) seems nice 👍

I can't approve the PR as I created it for @odain-cbd but merge in support/2.7 is ok for me.

2021-12-02 08:45 UTC, Hipska requested changes

2021-12-02 08:45 UTC, Hipska commented on core/apc-service.class.inc.php
> +}
Fix file ending?

2021-12-02 08:45 UTC, Hipska commented on core/dict.class.inc.php
> +			IssueLog::Warning("Cannot find $sLangCode in dictionnaries. default labels displayed");
Isn't this going to give a lot of warnings in the log file? Maybe better to check in `InitLangIfNeeded`?

2021-12-02 11:03 UTC, Molkobain commented on core/dict.class.inc.php
> +			IssueLog::Warning("Cannot find $sLangCode in dictionnaries. default labels displayed");
Maybe we could dispatch it to the APC channel like for the error message.

2021-12-02 11:06 UTC, Hipska commented on core/dict.class.inc.php
> +			IssueLog::Warning("Cannot find $sLangCode in dictionnaries. default labels displayed");
Could be done indeed, but even then it would still be a massive amount of messages. I would log it in the init method once when it cannot load the lang..

2021-12-02 11:19 UTC, odain-cbd commented on core/dict.class.inc.php
> +			IssueLog::Warning("Cannot find $sLangCode in dictionnaries. default labels displayed");
1) this log is generated when there is a broken dictionnary.  it is not linked to APC.

2) iTop will generate one log per label to display on a specific page. so yes, it could be huge!!

but normally when we package iTop we have a test (./integration/DictionariesConsistencyTest.php) that prevents from releasing broken dictionnaries (Romain's work). it does not happen anymore....

for this reasons we can leave as is....

2021-12-02 11:22 UTC, merged

2021-12-06 15:56 UTC, piRGoif commented on core/dict.class.inc.php
> +			IssueLog::Error("Cannot find $sLangCode in dictionnaries. default labels displayed", LogChannels::APC);
Ok... 
This may generate lots of noise in the log... We'll have to monitor this ! After next iTop Combodo upgrade !

2021-12-07 08:04 UTC, Hipska reviewed
@odain-cbd No I meant that there is no newline at the end of the file. I (and php) don't care about the `?>`.

2021-12-07 08:04 UTC, Hipska commented on core/apc-service.class.inc.php
> +}
Not resolved!

2021-12-07 08:05 UTC, Hipska commented on core/dict.class.inc.php
> +			IssueLog::Error("Cannot find $sLangCode in dictionnaries. default labels displayed", LogChannels::APC);
That's what I said as well.. https://github.com/Combodo/iTop/pull/224#discussion_r760868804