Improve CMDBSource methods
Combodo/iTop pull request #229
Opened 2021-08-20 12:28 UTC by Hipska

This improves the function calls to use more relevant `QueryToScalar` instead of the `QueryToCol`.

This also deprecates `GetServerInfo` since the info is not always reliable. (Related to https://github.com/Combodo/itop-system-information/pull/5) (See https://www.php.net/manual/en/mysqli.get-server-info.php)

2021-09-10 07:33 UTC, piRGoif requested changes
Thanks for those improvements, seems good to me ! 
Just a little remark about the phpdoc

2021-09-10 07:33 UTC, piRGoif commented on core/cmdbsource.class.inc.php
> +	 * @see mysqli_get_server_info
```suggestion
	 * @uses mysqli_get_server_info
```

We prefer to write `@uses` in such case (see https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/uses.html#uses-used-by)

2021-09-10 07:34 UTC, Hipska commented on core/cmdbsource.class.inc.php
> +	 * @see mysqli_get_server_info
Thanks, didn't know that one.

2021-09-10 07:39 UTC, piRGoif approved these changes, later dismissed

2021-11-02 10:04 UTC, piRGoif approved these changes

2022-01-05 08:56 UTC, piRGoif requested changes
After a team review, we found that the behavior as changed : before, if the result was 0 we were returning an empty string... Can you modify that ? 

I've checked exceptions, seems to me that we are getting the same with \CMDBSource::QueryToArray and \CMDBSource::QueryToScalar

2022-01-17 09:24 UTC, Hipska commented
Fixed the conflicts

2022-02-22 15:46 UTC, piRGoif commented
Hello,

> After a team review, we found that the behavior as changed : before, if the result was 0 we were returning an empty string... Can you modify that ?

@Hipska you asked for a new review, but this wasn't changed right ?

2022-02-22 16:03 UTC, Hipska commented
Ah, you mean for `GetServerVariable`? You want me to return this instead?

```php
return static::QueryToScalar($sSql, 0) ?: '';
```

2022-02-28 16:15 UTC, piRGoif commented
> Ah, you mean for `GetServerVariable`? You want me to return this instead?
> 
> ```
> return static::QueryToScalar($sSql, 0) ?: '';
> ```

Would be perfect, thanks !

2022-03-01 11:26 UTC, Hipska commented
Applied, please review.

2022-03-01 11:32 UTC, piRGoif approved these changes

2022-03-01 18:07 UTC, piRGoif commented
Sorry, we missed technical review today (too much PR to review). Will be reviewed next month !

2022-04-04 11:37 UTC, Molkobain approved these changes

2022-04-05 15:08 UTC, Molkobain commented
Accepted during technical review.

2022-04-12 15:10 UTC, Molkobain commented
Accepted in functional review, will be part of 3.1.0

2022-04-12 15:10 UTC, merged