Setup : new "change permissions & reload" button
Combodo/iTop pull request #244
Opened 2021-11-15 08:40 UTC by piRGoif

When opening the setup, if the config file is read only then this screen is displayed : 

![image](https://user-images.githubusercontent.com/8947448/141749152-c4e65e86-2a80-43e9-a213-55c20a97670a.png)

To ease things when developing on iTop, this PR adds a new button : 

![image](https://user-images.githubusercontent.com/8947448/141749250-ef918525-8283-450f-bf41-fc507b0d4a24.png)

This button is displayed if an only if \utils::IsDevelopmentEnvironment returns true.

Clicking on the button call the new setup/confperm.php endpoint.
This endpoint is protected by : 
* checking that \utils::IsDevelopmentEnvironment returns true
* checking if an iTop instance already exists (\SetupUtils::GetPreviousInstance)
* checking the setup token

I used setup token instead of the usual transaction_id because those latter needs access to the config !

2021-11-19 15:45 UTC, piRGoif commented
Reviewed with the dev team : having the button in the setup directly without any protection other than dev mode is far too risky.
We could add a fileexists check on the endpoint, and also remove the endpoint from Combodo builds, but nevertheless...

One solution could be to add the button in an admin page (core update ? config editor ? ). For me this is ideal as it would allow to launch the setup for admin on production instances without needing to access the server's file system !
Also, we could improve the toolkit to be able to install new modules (but that won't address use case where we need to launch setup on an instance that doesn't have the toolkit).

I need to check with IT & product team if they think this is a good idea.

2021-12-23 16:06 UTC, piRGoif commented
Rebased branch

2021-12-23 16:43 UTC, piRGoif commented
Button was added in the config editor. it is really ugly for now, but this will allow some demo :)
Updating the description and we will ok !

2021-12-31 09:05 UTC, piRGoif commented
Changed button label
PR's description updated accordingly

2022-01-05 09:12 UTC, Molkobain commented
Now that this feature is only available from the backoffice, I think it will be a great addition, especially for iTop admins that don't have access to the system.

That being said in the current functional implementation there are a few things that unsettle me:
  * The "launch setup" button should not be in the config editor IMHO as functionally speaking it as nothing to do with it, it should rather be in the "Application upgrade" or in a dedicated page. (I see that the current style is temporary for the demo, but is its positioning too?)
  * The security warning is displayed to anyone who access the app. root URL, that means the iTop admin but also ALL the basic users. So to me we should keep it simple, not confusing and we should not give a direct link to the setup!

2022-01-11 15:47 UTC, Molkobain commented
Accepted in functional team review: "Needs to be discussed with both R&D / PO / IT as it could introduce a new vulnerability. Maybe we should rework the Application Upgrade feature instead to cover this and its other issues."

2022-01-11 16:13 UTC, piRGoif commented
I will implement your suggestion Guillaume, and then send a meeting invitation to stakeholders

2022-02-04 14:36 UTC, piRGoif commented
Rebased & force pushed branch

2022-02-04 16:02 UTC, piRGoif commented
Removed the button and changed the index message
Adding the button in the application upgrade screen ongoin

2022-02-08 11:08 UTC, Molkobain requested changes

2022-02-08 11:08 UTC, Molkobain commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +    'iTopUpdate:UI:Setup' => 'iTop Setup',
```suggestion
    'iTopUpdate:UI:Setup' => ITOP_APPLICATION_SHORT.' Setup',
```

Use the application name constant instead of 'iTop' please

2022-02-08 11:08 UTC, Molkobain commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunch' => 'Launch iTop Setup',
```suggestion
	'iTopUpdate:UI:SetupLaunch' => 'Launch '.ITOP_APPLICATION_SHORT.' Setup',
```

Same comment about the application name constant

2022-02-08 11:08 UTC, Molkobain commented on index.php
> +<p>Please contact the administrator to modify the access rights to this file !</p>
```suggestion
<p>Please contact the administrator to modify the access rights to this file!</p>
```

2022-02-08 11:08 UTC, Molkobain commented on index.php
> +<p><a href="$sStartPage">Continue</a></p>
Why change the original sentence?

2022-02-08 11:08 UTC, Molkobain commented on setup/wizardcontroller.class.inc.php
> +
Why this format change? We should migrate the whole block to HEREDOC or nothing.

2022-02-08 11:08 UTC, Molkobain commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch iTop setup, are you sure ?',
```suggestion
	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch '.ITOP_APPLICATION_SHORT.' setup, are you sure?',
```

2022-02-08 17:04 UTC, piRGoif commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch iTop setup, are you sure ?',
Fixed in 361ffe90

2022-02-08 17:04 UTC, piRGoif commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +    'iTopUpdate:UI:Setup' => 'iTop Setup',
Fixed in 361ffe90

2022-02-08 17:04 UTC, piRGoif commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunch' => 'Launch iTop Setup',
Fixed in 361ffe90

2022-02-08 17:06 UTC, piRGoif commented on index.php
> +<p><a href="$sStartPage">Continue</a></p>
In the original PR version I added some links here, but I rollbacked them.
I changed the phrase though, as I think it is better like this (majority of people seeing this message aren't administrators)

2022-02-08 17:09 UTC, piRGoif commented on setup/wizardcontroller.class.inc.php
> +
There were lots of changes asked since the beginning of this PR. This output was changed in the original version.
I kept the switch to dockblock with language injection as it was done and wont make any hurt.

2022-02-08 17:15 UTC, piRGoif commented
Complementary discussion will be held next week with a representative of the support team

2022-02-14 15:27 UTC, piRGoif commented
Result of the discussion, a modification to do : add a dedicated config parameter, hidden by default, default value to hide the button. We won't use the existing IsDevEnv flag, as it triggers too much options for now and this won't be suitable in some use cases when we need to enable the setup button (in particular more errors thrown : menunode, deprecated calls, ...).

Also, I should integrate the callback directly in the core update controller, and use the console transaction_id + auth.

2022-02-18 14:10 UTC, piRGoif commented
Rebased branch & force push

2022-02-18 14:13 UTC, piRGoif commented on index.php
> +<p><a href="$sStartPage">Continue</a></p>
I rollbacked the message with e9f7ac9b
Closing the conversation

2022-02-18 14:39 UTC, piRGoif commented
Pushed the new config param 
Updated the description accordingly

2022-02-18 15:02 UTC, piRGoif commented
2nd commit, updated the description also :)

The PR is now ready for the next review !

2022-03-01 15:58 UTC, Molkobain submitted a review, later dismissed
Accepted in technical review (once conf param name is changed)

2022-03-01 15:58 UTC, Molkobain commented on core/config.class.inc.php
> +		'setup_launch_button.enabled' => [
```suggestion
		'setup.launch_button.enabled' => [
```

2022-03-01 15:58 UTC, Molkobain commented on datamodels/2.x/itop-core-update/src/Controller/UpdateController.php
> +		$bSetupLaunchButtonEnabled = $oConfig->Get('setup_launch_button.enabled');
```suggestion
		$bSetupLaunchButtonEnabled = $oConfig->Get('setup.launch_button.enabled');
```

2022-03-02 14:03 UTC, piRGoif commented on core/config.class.inc.php
> +		'setup_launch_button.enabled' => [
Pushed on my side (was easier to do a full check and one commit in my IDE)

2022-03-02 14:03 UTC, piRGoif commented on datamodels/2.x/itop-core-update/src/Controller/UpdateController.php
> +		$bSetupLaunchButtonEnabled = $oConfig->Get('setup_launch_button.enabled');
Pushed on my side (was easier to do a full check and one commit in my IDE)

2022-03-02 14:19 UTC, piRGoif commented
Maj la description pour lister quand le boutton est affiché ou non.

2022-03-02 14:20 UTC, piRGoif commented on setup/wizardcontroller.class.inc.php
> +
Agreed to keep it during technical PR review : closing conversation !

2022-03-03 10:15 UTC, Molkobain commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch '.ITOP_APPLICATION_SHORT.' setup, are you sure ?',
```suggestion
	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch '.ITOP_APPLICATION_SHORT.' setup, are you sure?',
```

2022-03-03 11:35 UTC, piRGoif commented on datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
> +	'iTopUpdate:UI:SetupLaunchConfirm' => 'This will launch '.ITOP_APPLICATION_SHORT.' setup, are you sure ?',
Damn !! I'm still making that mistake :/
Thanks for the fix!

2022-03-08 16:59 UTC, piRGoif commented
The PR was reviewed and approved during functional review.
We will merge for 3.1.0, but as some tickets for Core Update are currently working on in 3.0.1, we should wait this release before !
Combodo internal ref is N°4919

2022-04-19 12:36 UTC, merged