Introduce new APIs due to iPageUIExtension deprecation
Combodo/iTop pull request #245
Opened 2021-11-18 22:51 UTC by Molkobain

Since we deprecated the \iPageUIExtension API in iTop 3.0.0, there is no simple way to add JS/CSS files/snippets to a backoffice page anymore. The only way is to use the \iPageUIBlockExtension but it requires to make a UIBlock which is not intuitive when you only want to include some files as a UIBlock is designed to be a specific UI element.

Unlike the previous interface, we decided to make more atomic one to improve evolution through the upcoming versions and avoid the necessity to implement all methods when you only need a few.

2021-11-19 08:35 UTC, steffunky commented on application/applicationextension.inc.php
> +interface iBackofficeEarlyScriptExtension
`Script` is singular in this interface name but but plural in others

2021-11-19 08:35 UTC, steffunky commented on application/applicationextension.inc.php
> +	public function GetEarlyScript(): string;
`Script` is singular in this method name but but plural in others

2021-11-19 08:49 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeEarlyScriptExtension
Good catch, indeed it should be plural as the interface could contain several methods. I'll change it.

2021-11-19 08:49 UTC, Molkobain commented on application/applicationextension.inc.php
> +	public function GetEarlyScript(): string;
In other interface the method name is single, only the interface name is plural.
This method only return 1 script, so I think it stay single, what do you think?

2021-11-19 15:37 UTC, piRGoif requested changes, later dismissed
Thanks for the proposition !

I made some comments / suggestions on little details.

But on the principle, Why adding so much interfaces with only one method each ? Maybe we could group all JS methods, and all CSS methods, and add for each an abstract class ? Stating interfaces aren't part of the API but the abstract classes are ?

Also, most of the comments are on the interface PHPDoc. I would better add those comments to the `@return` tag on each method's phpdoc ?

2021-11-19 15:37 UTC, piRGoif commented on application/applicationextension.inc.php
> + *   * If you need to include HTML (and optionally JS/CSS) use {@see \iPageUIBlockExtension} to manipulate {@see \Combodo\iTop\Application\UI\Base\UIBlock} instead
```suggestion
 * @deprecated 3.0.0 If you need to include  :
 *   * JS/CSS files/snippets : use {@see \iBackofficeLinkedScriptsExtension}, {@see \iBackofficeLinkedStylesheetsExtension}, etc instead
 *   * HTML (and optionally JS/CSS) : use {@see \iPageUIBlockExtension} to manipulate {@see \Combodo\iTop\Application\UI\Base\UIBlock} instead
```

2021-11-19 15:37 UTC, piRGoif commented on application/applicationextension.inc.php
> +	 * @return array An array of absolute URLs to the files to include
```suggestion
	 * @return array An array containing for each script to include its absolute URL. Deduplication will be done by iTop itself
```

2021-11-19 15:37 UTC, piRGoif commented on application/applicationextension.inc.php
> +	 * @see \iTopWebPage::$a_linked_scripts
```suggestion
	 * @see \iTopWebPage::$a_linked_scripts Each script will be included using this method
```

2021-11-19 15:37 UTC, piRGoif commented on application/applicationextension.inc.php
> +interface iBackofficeEarlyScriptsExtension
I'm not very fan of this naming... 
Maybe something like HeadBefore ? This will speak to any web developer ?
But the core iTop methods are already called like this, so you may prefer to stick with this naming to avoid confusion ?
On my opinion the naming for iTop extensions API should be the easiest to understand for anyone : and this public isn't the one that will use core methods so having 2 distinct names wouldn't be that bad ?

2021-11-22 10:02 UTC, steffunky commented on application/applicationextension.inc.php
> +	public function GetEarlyScript(): string;
You're right!

2021-11-29 20:58 UTC, rquetiez commented on application/applicationextension.inc.php
> +interface iBackofficeReadyScriptsExtension
Singular would be more relevant : iBackofficeReadyScriptExtension

2021-11-29 20:59 UTC, rquetiez commented on application/applicationextension.inc.php
> +interface iBackofficeEarlyScriptsExtension
Singular would be more relevant : iBackofficeEarlyScriptExtension

2021-11-29 21:00 UTC, rquetiez commented on application/applicationextension.inc.php
> +interface iBackofficeScriptsExtension
Singular...

2021-11-29 21:00 UTC, rquetiez commented on application/applicationextension.inc.php
> +interface iBackofficeInitScriptsExtension
Singular...

2021-11-29 21:01 UTC, rquetiez commented on application/applicationextension.inc.php
> +interface iBackofficeStylesExtension
Singular...

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> + *   * If you need to include HTML (and optionally JS/CSS) use {@see \iPageUIBlockExtension} to manipulate {@see \Combodo\iTop\Application\UI\Base\UIBlock} instead
Done

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +	 * @see \iTopWebPage::$a_linked_scripts
Done

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +	 * @return array An array of absolute URLs to the files to include
I rather have the info about removing duplicates only in the property documentation, it avoids maintaining 2x documentation and minimize the risk that they diverge over time.

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeEarlyScriptsExtension
Changed to singular as indeed this will return / include only 1 (might it be big / have several sections) script.

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeScriptsExtension
Changed to singular as indeed this will return / include only 1 (might it be big / have several sections) script.

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeInitScriptsExtension
Changed to singular as indeed this will return / include only 1 (might it be big / have several sections) script.

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeReadyScriptsExtension
Changed to singular as indeed this will return / include only 1 (might it be big / have several sections) script.

2021-12-02 12:36 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iBackofficeStylesExtension
Changed to singular as indeed this will return / include only 1 (might it be big / have several sections) style.

2021-12-02 12:38 UTC, merged