:bug: fix notice log when upload svg image
Combodo/iTop pull request #247
Opened 2021-12-03 12:50 UTC by annProg

Try to fix notice log when upload svg image to `AttributeImage` field.

```
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP Notice:  Trying to access array offset on value of type bool in /var/www/itop/application/cmdbabstract.class.inc.php on line 3802
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP Stack trace:
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   1. {main}() /var/www/itop/pages/UI.php:0
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   2. Server->UpdateObjectFromPostedForm($sFormPrefix = *uninitialized*, $aAttList = *uninitialized*, $aAttFlags = *uninitialized*) /var/www/itop/pages/UI.php:970
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   3. Server->PrepareValueFromPostedForm($sFormPrefix = '', $sAttCode = 'logo', $sClass = *uninitialized*, $aPostedData = *uninitialized*) /var/www/itop/application/cmdbabstract.class.inc.php:3732
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP Notice:  Trying to access array offset on value of type bool in /var/www/itop/application/cmdbabstract.class.inc.php on line 3803
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP Stack trace:
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   1. {main}() /var/www/itop/pages/UI.php:0
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   2. Server->UpdateObjectFromPostedForm($sFormPrefix = *uninitialized*, $aAttList = *uninitialized*, $aAttFlags = *uninitialized*) /var/www/itop/pages/UI.php:970
[03-Dec-2021 10:15:24 Asia/Shanghai] PHP   3. Server->PrepareValueFromPostedForm($sFormPrefix = '', $sAttCode = 'logo', $sClass = *uninitialized*, $aPostedData = *uninitialized*) /var/www/itop/application/cmdbabstract.class.inc.php:3732
```

2021-12-07 08:51 UTC, piRGoif requested changes
Good idea, thanks !
I would change the test though : do not call `ResizeImageToFit()` if `$aSize === false`
This would be more generic

2021-12-07 12:54 UTC, annProg commented
@piRGoif how about `if (is_array($aSize))` then call `ResizeImageToFit()`

2021-12-07 12:59 UTC, Hipska approved these changes, later dismissed
Looks good, what about adding an `IssueLog::Warning('Image could not be resized ...` when not an array?

2021-12-07 13:26 UTC, piRGoif commented
Yes, good suggestion for is_array... You may also add a count() > 2 ?
And I agree with Hipska, adding a log if resize can't be done would make perfect sense... if the image isn't SVG (again...). That might add too much complexity (adding a ne method to test if the image is a vector format or a bitmap) ?

2021-12-07 13:53 UTC, Hipska commented
As per [php documentation](https://www.php.net/manual/en/function.getimagesize.php), the function will always return the first 2 indexes when it is an array, so the count check is not needed as extra. Although, an extra check if those values are zero might need to be done!

2021-12-07 14:17 UTC, piRGoif requested changes
Many thanks ! A little change again, sorry

2021-12-07 14:17 UTC, piRGoif commented on application/cmdbabstract.class.inc.php
> +						IssueLog::Warning($sClass . ":" . $this->GetKey() . '/' . $sAttCode . ': Image could not be resized. Mimetype: ' . $oImage->GetMimeType());
Nice log, thanks ! You might also add the file name ? \ormDocument::GetFileName

2021-12-07 14:17 UTC, piRGoif commented on application/cmdbabstract.class.inc.php
> +					if (is_array($aSize) && count($aSize) > 1)
@Hipska pointed out that the documentation stated that if you have an array no extra check is needed : https://github.com/Combodo/iTop/pull/247#issuecomment-987946211
But hey, we could leave the test anyway O:)

About testing the values to be > 0, to my opinion this is utils::ResizeImageToFit() job to do it ?

2021-12-07 14:21 UTC, Hipska commented on application/cmdbabstract.class.inc.php
> +					if (is_array($aSize) && count($aSize) > 1)
This check is indeed fixed @piRGoif, see latest version.

The `utils::ResizeImageToFit()` already checks if the size is already smaller than the max allowed, but having width and height as zero is a specific behaviour of the `utils::GetImageSize()`, so IMHO it is checked at the right place.

2021-12-07 15:00 UTC, piRGoif commented on application/cmdbabstract.class.inc.php
> +						IssueLog::Warning($sClass . ":" . $this->GetKey() . '/' . $sAttCode . ': Image could not be resized. Mimetype: ' . $oImage->GetMimeType());
That was done later on : closing the conversation

2021-12-07 15:01 UTC, piRGoif commented on application/cmdbabstract.class.inc.php
> +					if (is_array($aSize) && count($aSize) > 1)
Well, I disagree but indeed this is done and it won't do no any harm :o)
Closing this conversation

2021-12-07 15:01 UTC, piRGoif approved these changes

2021-12-07 15:02 UTC, piRGoif commented
Ok for me !
Will ask other developers to validate this PR and we will be good to merge.

2021-12-07 15:04 UTC, Hipska approved these changes

2022-01-04 15:27 UTC, Molkobain commented
Accepted in technical team review

2022-01-11 15:21 UTC, Molkobain commented
Accepted in functional team review.
@annProg could you rebase on support/3.0 branch so it will be part of the 3.0.1 release?

Thanks,
Guillaume

2022-01-14 07:44 UTC, piRGoif commented
The rebase was done in #257

2022-01-14 08:35 UTC, closed without merging