N°4515 Fix default validation pattern for AttributeURL
Combodo/iTop pull request #249
Opened 2021-12-07 10:53 UTC by piRGoif

Will now handle properly Alfresco or Sharepoint URL

2021-12-07 11:05 UTC, Hipska requested changes

2021-12-07 11:05 UTC, Hipska commented on core/config.class.inc.php
>  			//            SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET.....................................
The comment below it doesn't match anymore.

2021-12-07 11:05 UTC, Hipska commented on test/core/AttributeURLDefaultPattern.php
> +}
This file doesn't have a EOL at the end..

2021-12-07 11:05 UTC, Hipska commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
Maybe also add a very simple one? And also one for `ftp` since that is supported by default as well.

2021-12-07 11:06 UTC, piRGoif commented on test/core/AttributeURLDefaultPattern.php
> +}
Is that a problem ?

2021-12-07 11:07 UTC, piRGoif commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
Yep, right
Do you have any suggestion of values to be added in this provider ?

2021-12-07 11:07 UTC, Hipska commented on test/core/AttributeURLDefaultPattern.php
> +}
It doesn't look nice in Git history and on the file system. It's just a good idea to be consistent on all files anyway.

2021-12-07 11:09 UTC, Hipska commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
What about `https://www.combodo.com/itop`? Don't know of any well known ftp locations that might be somehow relevant.

2021-12-07 11:11 UTC, piRGoif commented on core/config.class.inc.php
>  			//            SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET.....................................
What do you mean ?  The regexp was modified in the "path" part and its structure wasn't changed
The example is still valid
But indeed the line about the "regexp origin" can be updated to state we made a little modification, is that what you meant ?

2021-12-07 11:14 UTC, piRGoif commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
Added 2 more URL with 720b03a9
OK for you ?

2021-12-07 11:14 UTC, Hipska commented on core/config.class.inc.php
>  			//            SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET.....................................
The comment was perfectly aligned with the regex parts, but now it is not anymore because the regex is on a separate line.

```suggestion
			// SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ ANCHOR............................
```

2021-12-07 11:15 UTC, Hipska commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
Perfect

2021-12-07 11:17 UTC, piRGoif commented on core/config.class.inc.php
>  			//            SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET.....................................
Thanks, suggestion commited ! 
I've also modified the "reg exp origin" line with 7e6b8985

2021-12-07 11:17 UTC, piRGoif commented on test/core/AttributeURLTest.php
> +			'Alfresco URL 2' => ['http://alfresco.mydomain3.org/share/page/site/books/document-details?nodeRef=workspace://SpacesStore/6274f55f-a25b-4762-a863-77f7066f2034', 1],
Ok :) Thanks for the suggestions !
Closing this conversation

2021-12-07 11:20 UTC, piRGoif commented on test/core/AttributeURLDefaultPattern.php
> +}
Ok. I'm not really convinced :D But indeed this is just a little modification in this PR, updated with 5d6b1c7f

You made the same remark elsewhere, I wonder if we did a change in our .editorConfig recently that removed the auto add of leading newline in new files ? I'll have a look

2021-12-07 11:20 UTC, Hipska approved these changes, later dismissed

2021-12-07 11:22 UTC, Hipska commented on test/core/AttributeURLDefaultPattern.php
> +}
There is indeed no technical need for it.

2021-12-07 13:07 UTC, odain-cbd commented on test/core/AttributeURLTest.php
> +
good job! the enhancement is provided with tests. maybe you could add some test where validation fails...

2021-12-07 13:27 UTC, piRGoif commented on test/core/AttributeURLTest.php
> +
Thanks :)
And about adding more use cases in the data provider, I'm open to suggestions :o)

2021-12-07 19:02 UTC, jbostoen commented on core/config.class.inc.php
> +			// SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ ANC
Perhaps time to correct the (old) typo: should be 'scheme'

2021-12-08 09:00 UTC, piRGoif commented on core/config.class.inc.php
> +			// SHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ ANC
Thanks, done in d505d67c

2021-12-08 09:00 UTC, piRGoif commented
Rebased branch

2021-12-08 10:42 UTC, Hipska approved these changes, later dismissed
Perfect, only a minor request..

2021-12-08 10:42 UTC, Hipska commented on core/config.class.inc.php
> +			// SCHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ AN
Small alignment fix
```suggestion
			'(https?|ftp)\://([a-zA-Z0-9+!*(),;?&=\$_.-]+(\:[a-zA-Z0-9+!*(),;?&=\$_.-]+)?@)?([a-zA-Z0-9-.]{3,})(\:[0-9]{2,5})?(/([a-zA-Z0-9:%+\$_-]\.?)+)*/?(\?[a-zA-Z+&\$_.-][a-zA-Z0-9;:[\]@&%=+/\$_.-]*)?(#[a-zA-Z_.-][a-zA-Z0-9+\$_.-]*)?',
			// SCHEME....... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH......................... GET............................................ ANCHOR..........................
```

2021-12-08 11:24 UTC, piRGoif commented on core/config.class.inc.php
> +			// SCHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ AN
Thanks ! 
Ideally, using [named groups](https://www.regular-expressions.info/named.html) would ease the readability... maybe next time :)

2021-12-08 11:27 UTC, Hipska commented on core/config.class.inc.php
> +			// SCHEME.......... USER....................... PASSWORD.......................... HOST/IP........... PORT.......... PATH........................ GET............................................ AN
Correct, but then the viewer would need to know RegEx syntax 😁

2021-12-08 11:28 UTC, Hipska approved these changes, later dismissed

2021-12-23 13:25 UTC, piRGoif commented
N°4515 was reviewed and is planned for iTop 3.0.1 : changing this PR status !

2021-12-29 10:40 UTC, piRGoif commented
Rebased the branch and this PR on support/3.0

2021-12-29 10:43 UTC, merged