🌐improved translation for ZH_CN
Combodo/iTop pull request #252
Opened 2021-12-13 05:45 UTC by purplegrape

2021-12-13 05:48 UTC, purplegrape commented
1、translation update
2、fix some missing text
3、add some blank line against en.dict to keep the some line number

2021-12-13 09:15 UTC, Molkobain requested changes
Just a small change for an entry where the "~~" should be removed, otherwise it's all good, thank you very much!

2021-12-13 09:15 UTC, Molkobain commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> +	'Class:FAQ/Attribute:domains' => '领域~~',
```suggestion
	'Class:FAQ/Attribute:domains' => '领域',
```

2021-12-13 09:15 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:LeftBlock' => '<p>'.ITOP_APPLICATION_SHORT.' 是完全开源的IT 操作门户.</p>
Thank you! 🙏

2021-12-13 09:55 UTC, purplegrape commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> +	'Class:FAQ/Attribute:domains' => '领域~~',
yes ,I've noticed it.  
it's a temp solution, but I can't think about another word to describe it accurately

2021-12-13 10:04 UTC, Hipska commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> +	'Class:FAQ/Attribute:domains' => '领域~~',
The mark can stay for a temp solution IMHO, I did it as well for Dutch translations (NL-NL).

2021-12-13 10:06 UTC, purplegrape commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> +	'Class:FAQ/Attribute:domains' => '领域~~',
same issue via the translation of “profiles” （line 1674-1676），I add the suffix  ~~ 
hope someone or me  fix it later

2021-12-13 14:35 UTC, Molkobain commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> +	'Class:FAQ/Attribute:domains' => '领域~~',
Ok if it is temporary then it makes sense. Thanks!

2021-12-13 14:35 UTC, Molkobain approved these changes

2021-12-13 14:36 UTC, merged

2021-12-13 14:36 UTC, Molkobain commented
Merged, thanks!

2021-12-14 07:36 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:LeftBlock' => '<p>'.ITOP_APPLICATION_SHORT.' 是完全开源的IT 操作门户.</p>
I don't see this modification in the merge commit (05e98be6) ?

2021-12-14 08:08 UTC, Hipska commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:LeftBlock' => '<p>'.ITOP_APPLICATION_SHORT.' 是完全开源的IT 操作门户.</p>
Correct, see the actual merge commit of this PR: a00f415

2021-12-15 07:21 UTC, piRGoif commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:LeftBlock' => '<p>'.ITOP_APPLICATION_SHORT.' 是完全开源的IT 操作门户.</p>
Woops right, I made a mistake on the merge commit, thanks for the correction Thomas :) Both commits are for different PRs, but both of them don't have their respective PR ref in their message, too bad :/

About using the constant, I asked Guillaume and he said he asked the author to do it, but as it was an extra modification he merged the PR anyway without waiting for this to be done.

I'm closing the conversation