:bug: Rack - missing relation to other objects
Combodo/iTop pull request #254
Opened 2022-01-03 13:09 UTC by RohacRichard

There is a missing <relations> segment defined in Rack, resulting in a lack of relations to other objects in the rack - for examples Servers and subsequently other parts in iTop. This fixes it. See attached pictures please.

Before:
![rack_before](https://user-images.githubusercontent.com/44978845/147934082-0adcdf65-4ba1-40ee-8049-87eba95a01dd.png)

After:
![rack_after](https://user-images.githubusercontent.com/44978845/147934095-994ad44d-30a9-4316-9b25-3ecf26984341.png)

2022-01-05 09:20 UTC, Molkobain commented
Hello Rohac,

Thanks for the PR! We will review it with the product team next week.

Cheers,
Guillaume

2022-01-11 16:24 UTC, Molkobain commented
Pending after functional team review: "Datamodel changes are never simple, we need to
  * Audit existing instances to check whether this relation has been defined by some customers (@Molkobain )
  * Consider adding it to the next major version (3.1)"

We will get back to you in the coming weeks.

Cheers,
Guillaume

2022-01-12 10:10 UTC, RohacRichard commented
Hi Guillame,

thanks for the update. This issue was actually raised by our customer. There was some malfunction with one of their racks. When they wanted to see, what kind of impact this outage would have, they were surprised to see the not much in their impact graph.

We have fixed this problem with our temporary solution - custom extension with this relation defined. But I figured this might be something Combodo would like to look into. 

IMO the relation should logically be defined there, but I understand your hesitation regarding the impact on existing iTop instances.

Cheers,
Richard

2022-01-12 10:20 UTC, Molkobain commented
For further (internal) discussions: Audit revealed 10 customer instances as of today with an #impacts relation on `Rack`.

Will keep you up to date Richard. In the meantime, if you fixed it with an extension it's perfect, that way it will be preserved during future iTop upgrades.

2022-01-12 10:39 UTC, Hipska commented
I have some semantically doubts.

It is obvious the Rack has an impact on any Device that is in it. But Can't see how a server would be "Depending on" the Rack. That would only be a physical dependency and up to now it looks only logical dependencies are tracked in iTop.

2022-01-12 10:52 UTC, Hipska requested changes

2022-01-12 10:52 UTC, Hipska commented on datamodels/2.x/itop-datacenter-mgmt/datamodel.itop-datacenter-mgmt.xml
> +            </neighbour>
The Rack impacts Enclosures as much as any other Datacenterdevice.

```suggestion
            <neighbour id="datacenterdevice">
              <attribute>device_list</attribute>
            </neighbour>
            <neighbour id="enclosure">
              <attribute>enclosure_list</attribute>
            </neighbour>
```

2022-02-02 13:09 UTC, RohacRichard commented on datamodels/2.x/itop-datacenter-mgmt/datamodel.itop-datacenter-mgmt.xml
> +            </neighbour>
Yes, good point.

2022-02-08 16:01 UTC, Molkobain commented
Hello Richard,

PR was not accepted during functional review:
  * For some people, racks are used are as simple "closets" / "shelves" with no real impact on the CIs they contain, for example imagine having an Incident on a rack for its door not closing well. All attached CIs would be seen as impacted when it's actually not. We can't introduce this behavior change for existing users.
  * More globally, we don't accept much datamodel changes as it often has impact for existing users.

@v-dumas will create a tutorial about this in the documentation so people can learn how to di it :)
Do you feel like sharing your extension on the SourceForge forum?

Cheers,
Guillaume

2022-02-08 16:02 UTC, closed without merging

2022-02-09 07:46 UTC, RohacRichard commented
Hi Guillaume,

I understand. I am glad this was given a thought, I appreciate that :)

I can certainly upload the extension. Would you kindly tell me, where should I put it?

Cheers,
Richard

2022-02-09 08:35 UTC, Molkobain commented
You can create a new topic on the forum [here](https://sourceforge.net/p/itop/discussion/third-party-extensions/) (the section is dedicated to third-party extensions) and attach your extension or a link to your GitHub repository is it exists.

If you don't feel like creating a sourceforge account, send me the extension to guillaume.lajarige at combodo.com and I'll post it on your behalf.

Thanks!
Guillaume

2022-02-10 13:07 UTC, RohacRichard commented
It's [up](https://sourceforge.net/p/itop/discussion/third-party-extensions/thread/22c72456c6/) on SourceForge :)

Cheers,
Richard

2022-02-10 20:32 UTC, Molkobain commented
Thank you very much Richard! Much appreciated 🙌