N°4652 Better error message when XML node define fails from delta
Combodo/iTop pull request #256
Opened 2022-01-12 09:23 UTC by steffunky

This pull request adds more details to the error message displayed when an XML (inside a XML must_exist most of the time) fails in production.delta.xml.
This error message then contains very low exploitable information:

![Screenshot from 2022-01-12 10-17-50](https://user-images.githubusercontent.com/5959857/149099192-b0058248-af91-4d38-8df0-296c32b94d1a.png)

- No module (indeed it's from production.delta.xml)
- No xml node path
- And sometimes a line number (not always though)

This PR adds information on the existing node in order to ease debugging: 

![Screenshot from 2022-01-12 10-19-53](https://user-images.githubusercontent.com/5959857/149100079-4a289631-2282-4c21-99ab-5d0e1f86d4fa.png)

2022-01-12 09:30 UTC, Molkobain requested changes
Other than the 2 typos, seems all good and a great enhancement for debug!

2022-01-12 09:30 UTC, Molkobain commented on setup/modelfactory.class.inc.php
> +				$oExistingPath = MFDocument::GetItopNodePath($oExisting);
```suggestion
				$sExistingPath = MFDocument::GetItopNodePath($oExisting);
```

2022-01-12 09:30 UTC, Molkobain commented on setup/modelfactory.class.inc.php
> +				$oExistingLine = $oExisting->getLineNo();
```suggestion
				$iExistingLine = $oExisting->getLineNo();
```

2022-01-12 11:15 UTC, Molkobain approved these changes

2022-01-12 16:37 UTC, piRGoif requested changes
Wonderful change many thanks !
Just a little suggestion about the exception message formatting ?

2022-01-12 16:37 UTC, piRGoif commented on setup/modelfactory.class.inc.php
>  					$iLine, $sPath);
```suggestion
				$sExistingPath = MFDocument::GetItopNodePath($oExisting);
				$iExistingLine = $oExisting->getLineNo();
				
				$sExceptionMessage = <<<EOF
`{$sPath}` at line {$iLine} could not be added : already exists in `{$sExistingPath}` at line {$iExistingLine}
EOF;
				throw new MFException($sExceptionMessage, MFException::COULD_NOT_BE_ADDED, $iLine, $sPath);
```

2022-01-13 11:10 UTC, piRGoif approved these changes

2022-01-14 09:18 UTC, merged

2022-01-14 09:20 UTC, piRGoif commented
Hello Stephen, you did not rebase on support/2.7 before merging ? 😢