TwigBase : add possibility to control BreadCrumb
Combodo/iTop pull request #260
Opened 2022-01-18 15:22 UTC by piRGoif

Asked by @xtophe38 for TeemIP

I'm not very pleased with \Combodo\iTop\Application\TwigBase\Controller\Controller::GetOperationBreadCrumbEntry
If anyone has a better proposition it would be more than welcome !

2022-01-19 11:13 UTC, Hipska reviewed
I assume these new methods are intended to be overriden? Otherwise this code doesn't add anything. Also, wouldn't the default of `IsOperationBreadCrumbEnabled` be `false`?

2022-01-19 11:13 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +		return [];
Other parts of iTop make an associative array for it, see https://github.com/Combodo/iTop/blob/5f575d524a7bcc7567cbc8b904204416e9b445e3/sources/Application/WebPage/iTopWebPage.php#L580-L587

But I think the product would benefit from having a `BreadCrumbEntry` class type

2022-01-19 11:13 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
What about this?
```suggestion
				@list($sId, $sTitle, $sDescription, $sUrl, $sIcon) = $aBreadCrumbEntry;
```

2022-01-19 11:19 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
I tried this in PHP 7.1 and this produces a notice :(
See https://3v4l.org/QeIVr#v7.1.33

2022-01-19 11:21 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +		return [];
I agree, we rely far too much on PHP arrays instead of DTO !
But I hesitate to do it for this small modification... 

Let's see what other dev team members think of this ?

2022-01-19 11:22 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
Note the `@` 😉

2022-01-19 11:24 UTC, piRGoif commented
> I assume these new methods are intended to be overriden? 

Yes exactly !

> Also, wouldn't the default of `IsOperationBreadCrumbEnabled` be `false`?

Currently the breadcrumb is enabled, and contains the page title. I didn't want to change this behavior, so by default a Controller will still has its own breadcrumb entry.

Note that the corresponding method is \iTopWebPage::DisableBreadCrumb which is confusing... But I rather create the opposite meaning for readability (when dealing with boolean having double false is always very confusing : I prefer to have Enabled returning true than Disabled returning false...)

2022-01-19 11:25 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
Wooops didn't see that sorry :D
I'm integrating your suggestion :)

2022-01-19 13:13 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
To get exactly the same behavior I've pushed 0e63ad60

2022-01-19 13:18 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
Could be much simpler with `$this->m_oPage->SetBreadCrumbEntry($sId, $sTitle, $sDescription, $sUrl ?: '', $sIcon ?: '');` https://3v4l.org/cPjZJ

2022-01-19 16:22 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
I didn't find [in the doc](https://www.php.net/manual/fr/language.operators.comparison.php#language.operators.comparison.ternary) when this was introduced ?
iTop 2.7.* must support PHP 5.6

2022-01-19 16:38 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
See https://3v4l.org/20lfG Seems to be since 5.3

2022-01-19 17:54 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +				$sIcon = (count($aBreadCrumbEntry) >= 5) ? $aBreadCrumbEntry[4] : '';
Thanks ! Pushed with d7e28ea4

2022-02-01 13:55 UTC, Molkobain commented on sources/application/TwigBase/Controller/Controller.php
> +			$this->m_oPage->DisableBreadCrumb();
I might be missing something on the PR, but `$m_oPage` can be either an iTopWebPage or an AjaxPage.
The latest does not have breadcrumbs, so it makes no sense to manipulate it, and moreover the `$m_oPage->DisableBreadCrumb()` call will crash for AjaxPage.

2022-02-01 13:57 UTC, Molkobain commented
Could you include an example of how you need to do currently on iTop and an example of how it would be done after? So we can see the improvement.
For now I'm not in favor of this as it is hard-coded for iTopWebPages and does not consider AjaxPages.

2022-02-01 15:48 UTC, Molkobain commented
Accepted in technical team review.
Small rework will be done but globally accepted as-is as there are already some tradeoffs / coupling depending on the page class (eg. AddAjaxPage).
Will be reviewed in functional review next week.

2022-02-01 16:13 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +			$this->m_oPage->DisableBreadCrumb();
You are perfectly right !
Will be fixed in next iteration

2022-02-01 16:18 UTC, piRGoif commented
Discussion summary : 

* Flaws
  - we are calling iTopWebPage breadcrumb methods even if we haven't got an iTopWebPage instance :(
  - this allows to customize the breadcrumb for each Controller impl, but we want to change it for each operation !
* Solutions 
  - add 2 breadcrumb methods in Controller that will be called by operation impl, and save passed parameters to a Controller structure
  - use the saved parameters in Controller::CreatePage

Adding breadcrumb methods in Controller, which should be able to handle multiple WebPage impl isn't very elegant :/ But this is out of scope for this PR, and furthermore having one Controller class per WebPage impl would bring breaking changes... So we are postponing this for now.

2022-02-01 16:44 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +		return [];
I'm closing this conversation, as the solution discussed with the rest of the dev team is less ugly. It could still benefit of a dedicated DTO object, but won't be as necessary.

2022-02-01 16:45 UTC, piRGoif commented
Did a rebase + force push

2022-02-01 16:46 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +		return [];
So you will end up with sometimes having an associative array and sometimes an indexed array?

I don't think that's the intention of the dev team or product owners?

2022-02-01 16:52 UTC, piRGoif commented
Dev team review comments implemented in the last commit !

2022-02-01 16:54 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +			$this->m_oPage->DisableBreadCrumb();
Closing this conversation as I pushed the modification

2022-02-01 16:55 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +		return [];
Oh I see, it is only used internally now.

2022-02-01 16:57 UTC, Hipska requested changes

2022-02-01 16:57 UTC, Hipska commented on sources/application/TwigBase/Controller/Controller.php
> +						$this->m_oPage->SetBreadCrumbEntry($sId, $sTitle, $sDescription, $sUrl ?: '', $sIcon ?: '');
The internal member will always have the 5 items..
```suggestion
						list($sId, $sTitle, $sDescription, $sUrl, $sIcon) = $this->m_aBreadCrumbEntry;
						$this->m_oPage->SetBreadCrumbEntry($sId, $sTitle, $sDescription, $sUrl, $sIcon);
```

2022-02-01 16:58 UTC, piRGoif commented on sources/application/TwigBase/Controller/Controller.php
> +						$this->m_oPage->SetBreadCrumbEntry($sId, $sTitle, $sDescription, $sUrl ?: '', $sIcon ?: '');
Perfectly right, thanks !

2022-02-01 16:59 UTC, Hipska approved these changes

2022-02-01 16:59 UTC, piRGoif commented
> Could you include an example of how you need to do currently on iTop and an example of how it would be done after? So we can see the improvement. For now I'm not in favor of this as it is hard-coded for iTopWebPages and does not consider AjaxPages.

Already discussed together, but I've changed the description to add some details.

2022-02-08 15:53 UTC, piRGoif commented
Accepted during functionnal review

2022-02-08 16:04 UTC, merged

2022-02-08 16:07 UTC, piRGoif commented
Woops sorry, I did a rebase & merge instead of a squash & merge
commits pushed to support/2.7 are : 3ef3166b, 41f6e856, 1709082e, dd7e73e4, 2a3e6384, ce36c00b, 3000659e