🌐Updated Dutch translations
Combodo/iTop pull request #262
Opened 2022-01-23 14:12 UTC by jbostoen

Missing Dutch translations.

@Hipska please double check?

2022-01-23 14:13 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.ui.php
> -	'Menu:QueryMenu' => 'Favoriete query\'s',
This one is actually not new, but I feel like my previous translation for "Query phrasebook" is not a proper one. "Favorite queries" have a link for me with a person, not general defined queries.

2022-02-08 14:10 UTC, Hipska requested changes
I'm open to comments on my suggestions

2022-02-08 14:10 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/nl.dict.authent-cas.php
> +
Please don't add empty newlines for no reason. This is not relevant for this PR.

+ same remark on every other file..

2022-02-08 14:10 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/nl.dict.itop-attachments.php
> +of vraag de iTop administrator om na te kijken of de schijf van de iTop server vol zit',
```suggestion
of vraag de iTop administrator om de opslag van de iTop server na te kijken',
```
This eliminates the double use of "of".

2022-02-08 14:10 UTC, Hipska commented on datamodels/2.x/itop-core-update/dictionaries/nl.dict.itop-core-update.php
> +	'iTopUpdate:UI:CannotUpdateUseSetup' => 'Je moet de <a href="%1$s">setup</a> uitvoeren om de toepassing te updaten.<br />Er zijn gewijzigde bestanden gedetecteerd, er kan geen gedeeltelijke update w
```suggestion
	'iTopUpdate:UI:CannotUpdateUseSetup' => 'Je moet de <a href="%1$s">setup</a> gebruiken om de toepassing te updaten.<br />Er zijn gewijzigde bestanden gedetecteerd, er kan geen gedeeltelijke update worden uitgevoerd.',
```

And maybe "up te daten"?

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:CMDBChange/Attribute:origin/Value:interactive' => 'Interactie door gebruiker in de GUI',
```suggestion
	'Class:CMDBChange/Attribute:origin/Value:interactive' => 'Gebruikersinteractie in de GUI',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:TriggerOnObjectMention+' => 'Trigger bij vermelden object (@xxx) van een object van de opgegeven klasse (of subklasse ervan) in een log',
```suggestion
	'Class:TriggerOnObjectMention' => 'Trigger (bij vermelden van object)',
	'Class:TriggerOnObjectMention+' => 'Trigger bij vermelden (@xxx) van een object van de opgegeven klasse (of subklasse ervan) in een log',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.core.php
> +    'Class:AsyncTask:InvalidConfig_Class_Keys' => 'Ongeldig formmaat bij de configuratie van "async_tasks_retries[%1$s]". Er wordt een Array verwacht met de volgende sleutels: %2$s',
Typo
```suggestion
    'Class:AsyncTask:InvalidConfig_Class_Keys' => 'Ongeldig formaat bij de configuratie van "async_tasks_retries[%1$s]". Er wordt een Array verwacht met de volgende sleutels: %2$s',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'Class:User/Error:ProfileNotAllowed' => 'Profiel "%1$s" kan niet toegevoegd worden omdat het het toegang tot de backoffice zou ontzeggen.',
```suggestion
	'Class:User/Error:ProfileNotAllowed' => 'Profiel "%1$s" kan niet toegevoegd worden omdat het de toegang tot de backoffice zou ontzeggen.',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +<div>Deze versie heeft een volledig nieuw, modern en toegankelijk back office design.</div>
On other places "backoffice" is used.
"uiterlijk" instead of "design"?

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +<div>Customize your '.ITOP_APPLICATION.' preferences for a personalized experience.</div>',
```suggestion
<div>Wijzig je  '.ITOP_APPLICATION.' voorkeuren voor een nog meer gepersonaliseerde ervaring.</div>',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Button:Wait' => 'Even geduld terwijl de velden aangepast worden',
```suggestion
	'UI:Button:Wait' => 'Even geduld terwijl de velden vernieuwd worden',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Audit:AuditCategory:Subtitle' => '%1$s fouten van de  %2$s - %3$s%%',
Typo
```suggestion
	'UI:Audit:AuditCategory:Subtitle' => '%1$s fouten van de %2$s - %3$s%%',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:RunQuery:QueryResults' => 'Resultaten query',
```suggestion
	'UI:RunQuery:QueryResults' => 'Query resultaten',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:RunQuery:QueryArguments' => 'Argumenten query',
```suggestion
	'UI:RunQuery:QueryArguments' => 'Query argumenten',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Edit:SearchQuery' => 'Kies een voorgedefinieerde query',
Might sound clearer:
```suggestion
	'UI:Edit:SearchQuery' => 'Kies een vooraf gedefinieerde query',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	<li>Webhooks: Staat toe om te integreren met toepassingen van derde partijen, door gestructureerde iTop-data door te sturen naar een URL.</li>
```suggestion
	<li>Webhooks: Staat toe om te integreren met toepassingen van derde partijen, door gestructureerde data te sturen naar een URL.</li>
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	<li>Stuur een e-mail: bij deze acties definieer je een sjabloon voor de berichttekst en ook parameters zoals ontvanger(s), prioriteit, enz.<br />
```suggestion
	<li>Stuur een e-mail: Bij deze acties definieer je een sjabloon voor het bericht en ook parameters zoals ontvanger(s), prioriteit, enz.<br />
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +<i><b>Acties</b></i> definieer de acties die uitgevoerd moeten worden als de trigger geactiveerd wordt. Er zijn 2 soorten standaardacties:
```suggestion
<i><b>Acties</b></i> definieer de acties die uitgevoerd moeten worden als de triggers geactiveerd worden. Er zijn 2 soorten standaardacties:
```

Maybe also add "momenteel" as translation to "For now"?

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Dashboard:NotUpToDateUntilContainerSaved' => 'Dit dashboard toont informatie dat nog geen rekening houdt met de wijzigingen die nu gemaakt worden.',
```suggestion
	'UI:Dashboard:NotUpToDateUntilContainerSaved' => 'Dit dashboard toont informatie die nog geen rekening houdt met de wijzigingen die nu gemaakt worden.',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> -	'Menu:QueryMenu' => 'Favoriete query\'s',
"phrasebook" could be replaced by "woordenboek" or "lexicon" maybe?

(We could still use "voorgedefinieerde query's" as the alt(+) text.

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/activity-panel/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:LoadAllEntries:Tooltip' => 'Laad alle vorige iteems',
```suggestion
	'UI:Layout:ActivityPanel:LoadAllEntries:Tooltip' => 'Laad alle vorige items',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/activity-panel/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:NotificationEntry:MessageLink:Tooltip' => 'Klik om de tab met notificaties te openen en meer info te zien',
```suggestion
	'UI:Layout:ActivityPanel:NotificationEntry:MessageLink:Tooltip' => 'Klik om het notificaties tabblad te openen en meer info te zien',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
We already discussed this. The former one is semantically more correct.

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:Silo:Label' => 'Select de organisatie waarop gefilterd moet worden',
```suggestion
	'UI:Layout:NavigationMenu:Silo:Label' => 'Selecteer de organisatie waarop gefilterd moet worden',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/tab-container/nl.dictionary.itop.tab-container.php
> +	'UIBlock:TabContainer:RemoteTabLoad' => 'Klik om deze tab te laden',
```suggestion
	'UI:Layout:TabContainer:ExtraTabsListToggler:Label' => 'Andere tabbladen',
	'UIBlock:Error:AddBlockNotTabForbidden' => 'Kan blok %1$s niet toevoegen aan %2$s (enkel tabbladen zijn toegelaten)',
	'UIBlock:TabContainer:RemoteTabLoad' => 'Klik om dit tabblad in te laden',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/layouts/ui-content-block/nl.dictionary.itop.ui-content-block.php
> +	'UIBlock:Error:AddBlockForbidden' => 'Kan blok niet toevoegen aan %1$s',
```suggestion
	'UIBlock:Error:AddBlockForbidden' => 'Kan het blok niet toevoegen aan %1$s',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/pages/preferences/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:PersonalizeKeyboardShortcuts:Button:Reset'         => 'Standaard',
```suggestion
	'UI:Preferences:PersonalizeKeyboardShortcuts:Button:Reset'         => 'Reset',
```
```suggestion
	'UI:Preferences:PersonalizeKeyboardShortcuts:Button:Reset'         => 'Standaard',
```

2022-02-08 14:10 UTC, Hipska commented on dictionaries/ui/pages/preferences/nl.dictionary.itop.preferences.php
> +	'UI:Preferences:ChooseAPlaceholder+'                               => 'Kies een placeholder afbeelding die getoond wordt als het contact gelinkt aan jouw gebruiker geen eigen afbeelding heeft.',
```suggestion
	'UI:Preferences:ChooseAPlaceholder+'                               => 'Kies een standaard afbeelding die getoond wordt als het contact gelinkt aan jouw gebruiker geen eigen afbeelding heeft.',
```

2022-02-08 16:49 UTC, jbostoen commented on dictionaries/nl.dictionary.itop.ui.php
> -	'Menu:QueryMenu' => 'Favoriete query\'s',
Sounds still too vague for me, I'll leave this one open for now to consider

2022-02-08 16:50 UTC, jbostoen commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
Which one? The dots? They're rather uncommon and would not be consistent?

2022-02-08 16:51 UTC, piRGoif commented
Hello,
Warning there is a conflict on dictionaries/nl.dictionary.itop.core.php
Can you solve it also ?

2022-02-28 17:17 UTC, Hipska commented
There is now a `foo.txt` file added?

2022-08-09 16:13 UTC, Hipska requested changes
There is in the meantime also a merge conflict to be solved..

2022-08-09 16:13 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/nl.dict.itop-attachments.php
> +of vraag de iTop administrator om de opslag van de iTop server na te kijken',
```suggestion
of vraag de iTop administrator om de opslagruimte van de iTop server na te kijken',
```

2022-08-09 16:13 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/nl.dict.itop-incident-mgmt-itil.php
> + * @author Jeffrey Bostoen - <jbostoen.itop@outlook.com> (2018 - 2022)
```suggestion
 * @author Jeffrey Bostoen <jbostoen.itop@outlook.com> (2018 - 2022)
```
En dit eigenlijk voor alle bestanden..

2022-08-09 16:13 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
Yes, please restore the 3 dots by ellipsis again.

2022-08-09 16:16 UTC, Hipska commented on datamodels/2.x/itop-core-update/dictionaries/nl.dict.itop-core-update.php
> +	'iTopUpdate:UI:CannotUpdateUseSetup' => 'Je moet de <a href="%1$s">setup</a> uitvoeren om de toepassing te updaten.<br />Er zijn gewijzigde bestanden gedetecteerd, er kan geen gedeeltelijke update w
Solved

2022-08-09 16:17 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +<div>Deze versie heeft een volledig nieuw, modern en toegankelijk back office design.</div>
Solved

2022-08-09 16:17 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +<div>Customize your '.ITOP_APPLICATION.' preferences for a personalized experience.</div>',
Solved

2022-08-09 16:57 UTC, jbostoen commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
Implemented most of the comments. I know you're a huge fan of the ellipsis; but check the main English translations as well. Except for my recent comment on a Combodo commit, most of them are actually three dots. I'm just following their (main) convention here.

2022-08-10 08:13 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
If the translation was an ellipsis before, I would not change it to a less correct statement.

If other translations don't put the correct characters all the time doesn't mean we shouldn't do as well..

2022-08-10 08:20 UTC, Hipska approved these changes

2022-08-10 08:22 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +	'UI:Edit:SearchQuery' => 'Kies een voorgedefinieerde query',
Solved

2022-08-10 08:24 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/nl.dict.authent-cas.php
> +
Solved

2022-08-10 08:25 UTC, Hipska commented on dictionaries/ui/layouts/activity-panel/nl.dictionary.itop.activity-panel.php
> +	'UI:Layout:ActivityPanel:NotificationEntry:MessageLink:Tooltip' => 'Klik om de tab met notificaties te openen en meer info te zien',
Solved
(Can you mark these as resolved? I seem not able to do it)

2022-08-10 08:29 UTC, Hipska requested changes

2022-08-10 08:29 UTC, Hipska commented on dictionaries/nl.dictionary.itop.ui.php
> +=======
This didn't got merged correctly..

2022-08-10 15:00 UTC, jbostoen commented
Sorry, missed that last conflict.

Hope it just gets merged sooner now 😁

2022-08-11 09:52 UTC, Molkobain commented
Are you all done with this PR, ready to be reviewed / merged?

2022-08-11 09:55 UTC, Molkobain commented on dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
> +	'UI:Layout:NavigationMenu:MenuFilter:Input:Placeholder' => 'Filter...',
We haven't stated anything on ellipsis yet, we let you consider what is best regarding your language.

2022-08-11 10:03 UTC, jbostoen commented
I think the current work is ready to be merged; let's not wait for the ellipses discussion as it may be a more global discussion.

2022-08-11 12:07 UTC, merged

2022-08-12 08:07 UTC, Hipska commented
Yeah, still sad a good translation using ellipsis is now less good because it now has 3 dots. But indeed, could be a big refactor across all language dicts..