Updated PT-BR Translation
Combodo/iTop pull request #268
Opened 2022-02-09 13:22 UTC by eduardomozart

Removed the ``~~`` flag from translated strings.

2022-02-09 17:48 UTC, Molkobain requested changes
Thanks for the PR! Can you just accept the 2 changes I suggested? (you can click accept directly on the webpage, no need to do another PR)

2022-02-09 17:48 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Core:AttributeObsolescenceDate' => 'Data de obsolescência ',
```suggestion
	'Core:AttributeObsolescenceDate' => 'Data de obsolescência',
```

2022-02-09 17:48 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.ui.php
> +	'UI:Button:Clear' => ' Limpar ',
```suggestion
	'UI:Button:Clear' => ' Limpar',
```

2022-02-09 17:50 UTC, Molkobain commented
Nevermind, I was able to apply them myself.
I'll discuss this PR internally and get back to you soon.

2022-02-09 17:50 UTC, Molkobain approved these changes, later dismissed

2022-02-10 08:56 UTC, piRGoif commented
Hello,
Thanks for your contribution !

I see multiple "+" keys containing same values as their counterparts... For example Class:ActionEmail/Attribute:importance/Value:low and Class:ActionEmail/Attribute:importance/Value:low+.
This is the same in the EN files :/ @Molkobain what do you think ? Shouldn't we fix that ?

2022-02-10 08:56 UTC, piRGoif approved these changes, later dismissed

2022-02-10 08:58 UTC, Hipska commented
> I see multiple "+" keys containing same values as their counterparts... For example Class:ActionEmail/Attribute:importance/Value:low and Class:ActionEmail/Attribute:importance/Value:low+. This is the same in the EN files :/ @Molkobain what do you think ? Shouldn't we fix that ?

I would say, yes!

2022-02-10 20:33 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:CMDBChangeOp/Attribute:objkey+' => 'ID do objeto',
```suggestion
	'Class:CMDBChangeOp/Attribute:objkey+' => '',
```

2022-02-10 20:38 UTC, Molkobain approved these changes, later dismissed

2022-02-10 20:38 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:CMDBChangeOp/Attribute:objclass+' => 'Classe do objeto',
```suggestion
	'Class:CMDBChangeOp/Attribute:objclass+' => '',
```

2022-02-10 20:38 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:EventLoginUsage/Attribute:contact_name+' => 'Nome de usuário',
```suggestion
	'Class:EventLoginUsage/Attribute:contact_name+' => '',
```

2022-02-10 20:38 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:importance/Value:low+' => 'baixa',
```suggestion
	'Class:ActionEmail/Attribute:importance/Value:low+' => '',
```

2022-02-10 20:38 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:importance/Value:high+' => 'alta',
```suggestion
	'Class:ActionEmail/Attribute:importance/Value:high+' => '',
```

2022-02-10 20:39 UTC, Molkobain submitted a review, later dismissed

2022-02-10 20:41 UTC, Molkobain commented
@eduardomozart I took the liberty to remove entries for attribute descriptions that were identical to the attribute names. It's a best pratice now but they were indeed already present in the files you translated. :)

2022-02-14 14:51 UTC, eduardomozart commented
Hello guys,
I updated some strings from the iTop translation to Portuguese-Brazil during this weekend. Apparently most of the strings were translated with Google Translate at the time, since most strings lacked congruence, especially those that make up the table headers (which justifies this commit having so many translated strings updated). I also adjusted some terms to the Brazilian terms used in the study material and ITIL 4 exam in Brazil.
I intend to continue updating the translation as I use iTop and identify inconsistencies in the translation, as well as the release of new versions of iTop, becoming part of the iTop translation group. I intend to translate modules and extensions as I implement them in my environment.
Thank you for developing iTop, I hope to contribute with bug reports and new features to iTop.

2022-02-14 15:11 UTC, Hipska commented
That's great to hear! Currently our extensions to iTop are completely translated to Portuguese, but if you would like to sign up, you will be informed if new strings need to be translated: https://www.transifex.com/super-visions/public/

2022-02-15 03:35 UTC, eduardomozart commented
The Pull Request "[Fix notifications dropdown menu translation text](https://github.com/Combodo/iTop/pull/268/commits/c4aaabaeea8c9286cb92ec82366c32943e8c3835)" ended up being sent in this same Pull Request, which was not my intention. During the translation work, I found that the text in the "Status" drop-down menu of iTop Notifications was not displayed correctly, instead the translated but generic "Status" of other objects was displayed. By removing the "+" character from the notification parameters, the translated terms started to be displayed correctly. I made the change in the other language files.

2022-02-15 06:08 UTC, Hipska commented
Please mark this PR as draft asl long as you are still working on it.

2022-02-15 08:07 UTC, piRGoif commented
Hello,

> Please mark this PR as draft asl long as you are still working on it.

Yes please :)
And when you are ready for us to review your pr, add a comment stating so.

Thanks !

2022-02-15 15:10 UTC, Molkobain requested changes

2022-02-15 15:10 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/pt_br.dict.itop-attachments.php
> +	'Attachments:NoAttachment' => 'Nenhum anexo ',
```suggestion
	'Attachments:NoAttachment' => 'Nenhum anexo',
```

2022-02-15 18:02 UTC, piRGoif commented
> The Pull Request "[Fix notifications dropdown menu translation text](https://github.com/Combodo/iTop/pull/268/commits/c4aaabaeea8c9286cb92ec82366c32943e8c3835)" ended up being sent in this same Pull Request, which was not my intention. During the translation work, I found that the text in the "Status" drop-down menu of iTop Notifications was not displayed correctly, instead the translated but generic "Status" of other objects was displayed. By removing the "+" character from the notification parameters, the translated terms started to be displayed correctly. I made the change in the other language files.

By "itop notification" do you mean the bell icon on the bottom left of the UI ? 
Can you share some screenshots of the wrong behavior ?

2022-02-15 18:12 UTC, eduardomozart commented
Hello @piRGoif 
The requested screenshots are in attachment:

Before the fix:

![before-fix](https://user-images.githubusercontent.com/2974895/154123256-ba131abe-f3fe-475c-9d98-32ae38af4064.png)

After the fix:

![after-fix](https://user-images.githubusercontent.com/2974895/154123250-afe3e865-4059-471e-93ac-4fbeadf77a74.png)
.

2022-05-05 13:11 UTC, Molkobain commented
Hello Eduardo,

Product team is ok to include the translations in the future 3.0.2 of iTop. Do you think you will have finished what you want to translate by then? (After summer)

2022-05-09 16:10 UTC, eduardomozart commented
Hello,
Sorry for the late reply. Yes, the language file is near from complete and can be merged. Please close this pull request so I can pull the repo again and update newer strings added between 3.0.1/3.0.2 release.

2022-08-25 11:44 UTC, eduardomozart commented
Hello.

Why this translation was considered invalid? There was something missing?

2022-08-25 11:51 UTC, piRGoif commented
Hello,
You closed this PR on may 9 ? You said :

> Please close this pull request so I can pull the repo again and update newer strings added between 3.0.1/3.0.2 release.

The "invalid" label for us means precisely that : the PR cannot be merged and will be replaced by something else.

Did you create a new PR ? Do you wish to restart work on this one ?

2022-08-25 12:06 UTC, eduardomozart commented
Sorry, I closed this to say it was finished, not to end it as it is. I fixed the inconsistences and now it can be safely merged. Tested this translation at our production environment and it seems to be working just fine. Hope to see this translation into next iTop major version, as it will greatly improve PT-BR experience for Portuguese users. Thank you!

2022-08-25 12:24 UTC, piRGoif commented
Oh ok ! Close is a final state, opposed to merge (a close pr is unmerged)
Thanks for updating your fork branch !
We will review your modifications !

2022-08-30 17:50 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/pt_br.dict.itop-attachments.php
> +	'Attachments:NoAttachment' => 'Nenhum anexo ',
@eduardomozart please accept this change so we can merge your PR.
You can also check the "allow maintainers to edit PR" on the PR so we can apply changes directly :)

2022-08-30 18:02 UTC, eduardomozart commented on datamodels/2.x/itop-attachments/dictionaries/pt_br.dict.itop-attachments.php
> +	'Attachments:NoAttachment' => 'Nenhum anexo ',
@Molkobain this merge was already applied to the PR and "Allow edits by maintainers" was already enable for this PR. Please let me know if anymore changes are needed.

2022-08-30 21:50 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/pt_br.dict.itop-attachments.php
> +	'Attachments:NoAttachment' => 'Nenhum anexo ',
Then it's alright, i'll fix it myself during merge

2022-08-30 21:51 UTC, Molkobain approved these changes

2022-09-13 14:15 UTC, Molkobain commented
Accepted in functional review, will be part of the upcoming 3.1.0

2022-09-13 15:20 UTC, merged

2022-09-13 15:24 UTC, Molkobain commented
Hello @eduardomozart , translations will part of the upcoming 3.1.0; thanks again for the contribution! 🙌
Could you send me your fullname and postal address so we can send you contributor stickers?

Cheers,
Guillaume

2022-09-13 16:45 UTC, eduardomozart commented
Hello @Molkobain, thank you! Of course I can. Here's my address information (but there's any problem if you can't send it to my country):

Full Name: Eduardo Mozart de Oliveira
Address: R. Novo Hamburgo, 460 - Pavto Superior
City: Dois Irmãos
State: RS
Zip Code: 93950-000
Country: Brazil

I pretend to keep contributing with iTop with translations and backport some GLPI plugins (like ["accounts"](https://github.com/InfotelGLPI/accounts) plugin) as an iTop extension and offer an iTop course at Udemy at the near future.

2022-09-13 17:33 UTC, Molkobain commented
Thanks! I'll send them this week, keep up the good work! 🤩🤩🤩