N°4920 - Fix "undefined index" notice in user rights
Combodo/iTop pull request #271
Opened 2022-02-16 13:38 UTC by odain-cbd

this PR aims at avoiding such noise in iTop logs:
`2022-02-16 14:33:01 | Error   | 648   | 8 - Undefined index: Organization in /var/www/html/addons/userrights/userrightsprofile.class.inc.php:744 | IssueLog |||`

2022-02-16 13:57 UTC, Hipska requested changes

2022-02-16 13:57 UTC, Hipska commented on addons/userrights/userrightsprofile.class.inc.php
> +			if (is_array($aTest)) return $aTest;
Only one `isset` is needed.
```suggestion
		if (isset($this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode])){
			$aTest = $this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode];
			if (is_array($aTest)) return $aTest;
```
Proof: https://3v4l.org/hYPZq

2022-02-16 18:05 UTC, Molkobain commented
Did you check with @eespie ? These logs are not supposed to be there anymore, they are added by the "Enhanced global search" extension.

2022-02-16 18:10 UTC, Molkobain approved these changes, later dismissed

2022-02-16 18:11 UTC, Molkobain commented
Do you aim to have this in iTop 3.1 or 3.0.x?

2022-02-16 20:05 UTC, Hipska approved these changes, later dismissed

2022-02-17 07:18 UTC, odain-cbd commented
@Molkobain ideally it would be nice to leave it in any 3.x version, no?

2022-02-17 07:36 UTC, Molkobain commented
> @Molkobain ideally it would be nice to leave it in any 3.x version, no? in that case I should change the PR merge target to branches/3.0 i guess?

Yes, I would suggest to rebase the PR on support/3.0 as well as the fix is likely to have no negative impact.

2022-02-17 09:30 UTC, Hipska commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
Not sure if the array test is still needed?

```suggestion
		if (isset($this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode])){
			return $this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode];
		}
```

Otherwise, you could just add this in one go:
```suggestion
		if (isset($this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode]['permission'])){
			return $this->m_aObjectActionGrants[$iUser][$sClass][$iActionCode];
		}
```

2022-02-17 13:06 UTC, odain-cbd commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
after a quick searck, $aTest must be an array at this point of the code. iis_array seems useless yes. 

but i prefer that this code remains defensive (until types are reenforced by method signatures?)... one day someone may add another entry which is not an array anymore (by mistake). at least it will not break anything...

2022-02-17 13:07 UTC, odain-cbd commented
closing this PR and creating another one from develop->branches/3.0. thank you for your reviews

2022-02-17 13:08 UTC, Hipska commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
Then my second suggestion could be used ;)

2022-02-17 13:14 UTC, odain-cbd commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
this is not a code that i know very well. 2nd proposal seems ok to me. fonctionnaly i cannot approve or reject on my own.

@Molkobain ?

2022-02-17 13:20 UTC, Molkobain commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
TBH I never went to this part of the code, so I would rather just keep the defensive test as proposed by Olivier. No real need to go further (yet).

2022-02-17 14:50 UTC, Hipska approved these changes

2022-02-17 14:53 UTC, piRGoif approved these changes

2022-02-17 14:55 UTC, piRGoif commented
We did the rebase with Olivier, using the `git rebase --onto support/3.0 develop features/userprofile-avoidindexerror` command, then force push then change the PR base branch.

2022-02-17 14:55 UTC, piRGoif commented on addons/userrights/userrightsprofile.class.inc.php
> +		}
Closing conversation as everyone agrees

2022-02-17 14:55 UTC, piRGoif commented
Next step technical review - it will be held in 2 weeks

2022-02-17 16:44 UTC, Molkobain approved these changes

2022-03-01 13:26 UTC, Molkobain approved these changes

2022-03-01 15:52 UTC, Molkobain commented
Accepted in technical review.
Will be presented during functional review next week as we want it in the next maintenance release.

2022-03-08 17:21 UTC, Molkobain commented
Accepted in maintenance release during functional review.
Rebased on support/2.7 branch with Pierre command (🙌) so it can be part of 2.7.7 and 3.0.1

2022-03-08 17:21 UTC, merged