Add UI.php support for attcode & attvalue parameters
Combodo/iTop pull request #273
Opened 2022-02-18 16:32 UTC by piRGoif

Since iTop 2.7.0, we are using a different method to init the ref field. Since then in certain cases we can have a different value stored in the reference and in the id field. For more technical details see [Ticket Ref generation](https://www.itophub.io/wiki/page?id=2_7_0%3Arelease%3A2_7_whats_new#ticket_ref_generation)

This can become problematic for the user when he has a ref field containing "R-000100" and an id=99
This means we cannot build an URL to access the object using the ref field value, as accessing object details is done using UI.php with parameters `class` and `id`. For example : `http://localhost/itop-27/pages/UI.php?operation=details&class=UserRequest&id=99`

A first workaround is already implemented : the id parameter can contain the friendly name value : in UI.php the object is then seeked using `\MetaModel::GetObjectByName`.
But in certain datamodels the friendlyname can be quite complex...

This PR brings new URL parameters : `attcode` and `attvalue`.
With the previous example, that means the same object can be accessed using one of those URL : 
`http://localhost/itop-27/pages/UI.php?operation=details&class=UserRequest&id=99`
`http://localhost/itop-27/pages/UI.php?operation=details&class=UserRequest&attcode=ref&attvalue=R-000100`

When using the new parameters, the object retrieval is done using `\MetaModel::GetObjectByColumn`, with the `bMustBeFound` parameter set to `true` : in consequence an exception will be thrown if no object is found, as if multiple instances are.

2022-02-23 19:05 UTC, jbostoen commented
Question: does it simply take the first object, if the attribute value is not unique?

2022-02-23 19:26 UTC, Hipska commented
It throws exception:
> in consequence an exception will be thrown if no object is found, as if multiple instances are.

2022-02-24 08:46 UTC, Molkobain commented on pages/UI.php
> +			} else if (is_numeric($id)) {
I would rather keep the test on the ID as the first test, it would insist on the fact that it's the main / best way to access an object, especially for performance reason. To me, accessing the object via another attribute is a last resort thing.

2022-02-24 09:35 UTC, Hipska commented on pages/UI.php
> +					throw new ApplicationException(Dict::Format('UI:Error:3ParametersMissing', 'class', 'attcode', 'attvalue'));
```suggestion
					throw new ApplicationException(Dict::Format('UI:Error:ParametersMissing', 'attcode', 'attvalue'));
```

2022-02-24 10:40 UTC, piRGoif commented on pages/UI.php
> +			} else if (is_numeric($id)) {
I changed the way param handling is done in a9eaba21
Ok for you @Molkobain  ?

2022-02-24 10:59 UTC, piRGoif commented
Updated description to add error messages

2022-02-24 11:02 UTC, piRGoif commented on pages/UI.php
> +			} else if (is_numeric($id)) {
Just pushed 92329bd9 also : if only the class param is provided, we will now display that id is missing (instead of attcode/attvalue)

2022-03-01 18:06 UTC, piRGoif commented
Missed technical review today (too much PR to review). Will be reviewed next month !

2022-03-01 21:22 UTC, Molkobain requested changes

2022-03-01 21:22 UTC, Molkobain commented on pages/UI.php
> +				if (empty($sAttCode) || empty($sAttValue)) {
```suggestion
				if ( (strlen($sAttCode) === 0) || (strlen(empty($sAttValue) === 0) ) {
```

We need to use `strlen()` otherwise accessing an object with $sAttValue at `"0"` will not work.

2022-03-02 09:31 UTC, piRGoif commented on pages/UI.php
> +				if (empty($sAttCode) || empty($sAttValue)) {
Damn :( Thanks !
Fixed in 217e796c (your suggestion kept the empty() call for the second param)

2022-03-03 08:00 UTC, Molkobain commented on pages/UI.php
> +				if (empty($sAttCode) || empty($sAttValue)) {
Woops, sorry! 😬

2022-03-04 14:28 UTC, piRGoif commented
Just pushed 2 new commits adding a new route in the user portal.
Description updated accordingly.

Thanks to @Molkobain for the precious help !
And @v-dumas for the suggestion :)

2022-03-07 09:52 UTC, Molkobain approved these changes, later dismissed

2022-03-07 09:52 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
>  	 * Displays an cmdbAbstractObject if the connected user is allowed to.
```suggestion
	 * Displays an cmdbAbstractObject (from its ID) if the connected user is allowed to.
```

2022-03-07 09:52 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +	 * @param \Symfony\Component\HttpFoundation\Request $oRequest
```suggestion
	 * Displays an cmdbAbstractObject (if the connected user is allowed to) from a specific attribute. If several or none objects are found with the attribute value, an exception is thrown.
	 * 
	 * @param \Symfony\Component\HttpFoundation\Request $oRequest
```

2022-03-07 13:26 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
>  	 * Displays an cmdbAbstractObject if the connected user is allowed to.
This is the old code, so this suggestion is an error right ?

2022-03-07 16:13 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
>  	 * Displays an cmdbAbstractObject if the connected user is allowed to.
As we introduced a new method to display an object, it makes sense (to me) to explain how the old one is now different than the new one.

2022-03-08 17:14 UTC, piRGoif commented
Approved during functional review, for 3.1.0

2022-03-08 17:28 UTC, piRGoif commented
Rebased branch on develop

2022-03-08 18:49 UTC, Molkobain approved these changes

2022-03-08 18:50 UTC, Molkobain commented
Ok to merge @piRGoif !

2022-03-09 09:51 UTC, merged