N°4849 - Enable notification emails grouping in threads in email clients
Combodo/iTop pull request #275
Opened 2022-02-23 09:19 UTC by Molkobain

This PR is an attempt and a call for help 😁

### Issue
When we receive notification emails from iTop, they are display as different conversations in the email client (eg. Outlook) event though they have the same subject and are about the same iTop object. One of the main drawback if that the mailbox can feel spammed.

_The 3 first emails are notifications about the same object, but they are already filling the mailbox folder_
![image](https://user-images.githubusercontent.com/5130468/155285216-424219fc-813e-4e01-a908-1606b2d94500.png)

### Expectation
Find a way to group notification emails for a same object in a thread like email clients do when receiving emails from other platforms.

_Example with comments on a PR on GitHub here_ 
![image](https://user-images.githubusercontent.com/5130468/155285481-adad7a3b-0671-4248-801b-795772fca154.png)

_Example of desired behavior with iTop notification emails_
![image](https://user-images.githubusercontent.com/5130468/155285539-a8716916-9d63-40c3-bfd1-3e06b80f33ef.png)

### What was done so far
#### Specs
From what I saw [here](https://en.wikipedia.org/wiki/Email#Header_fields) and on other sites, it seems that the email needs to have the `In-Reply-To` header, the spec says that it should contain the `Message-ID` of the email to chain to. But we can't do that when it comes to notifications as they are not replies, they have no previous `Message-ID`.

For instance, GitHub is using the same value as in the `References` header in the `In-Reply-To`, this seems to allow emails to group around the same "object", here a PR, but it can be an issue or a commit.
```
[...]

From: xxxx <notifications@github.com>
Reply-To: Combodo/iTop <noreply@github.com>
To: Combodo/iTop <iTop@noreply.github.com>
Cc: Push <push@noreply.github.com>
Message-ID: <Combodo/iTop/pull/262/push/9043873881@github.com>
In-Reply-To: <Combodo/iTop/pull/262@github.com>
References: <Combodo/iTop/pull/262@github.com>
Subject: =?UTF-8?Q?Re:_[Combodo/iTop]_=F0=9F=8C=90Updated_Dutch_transl?=
 =?UTF-8?Q?ations_=28PR_#262=29?=

[...]
```

It is pretty clear that the `Message-ID` is unique to the email, but that `References` and `In-Reply-To` are common to all emails regarding this PR.

#### Implementation
Previously, both `Message-ID` and `References` headers had the same value, it contained the object class, the object ID, the current timestamp and an identifier of the current instance.

```
[...]

Message-ID: <iTop_UserRequest_542_1645547692.537156@8c43a16d628776c7a7098fae22c1e880-production.openitop.org>
Date: Tue, 22 Feb 2022 17:35:00 +0100
Subject: The ticket R-000561 has been updated
From: <guillaume.lajarige@combodo.com>
To: <guillaume.lajarige@combodo.com>
References: <iTop_UserRequest_542_1645547692.537156@8c43a16d628776c7a7098fae22c1e880-production.openitop.org>

[...]
```

With this PR the following things have been done:
  * Change the `References` header so it is common to all emails about the triggering object by removing the timestamp part.
  * Add a `In-Reply-To` header with the same value as the `References`

```
Message-ID: <iTop_UserRequest_542_1645604682@8c43a16d628776c7a7098fae22c1e880-production.openitop.org>
Date: Wed, 23 Feb 2022 09:24:42 +0100
Subject: The ticket R-000561 has been updated
From: <guillaume.lajarige@combodo.com>
To: <guillaume.lajarige@combodo.com>
References: <iTop_UserRequest_542@8c43a16d628776c7a7098fae22c1e880-production.openitop.org>
In-Reply-To: <iTop_UserRequest_542@8c43a16d628776c7a7098fae22c1e880-production.openitop.org>
```

#### Results
  * Grouping works in GMail, but it was actually already working before as it seems to match on the subject anyway.
  * Grouping works in Evolution since the PR.
  * Grouping does NOT works in Outlook 2013 or Outlook Online.

### What's next
  - [ ] Find why it's not working on Outlook
  - [ ] Add a unit test for the \ActionEmail::GenerateIdentifierForHeaders() method

2022-02-23 10:32 UTC, steffunky commented
Outlook seems to use `Thread-Topic` and `Thread-Index` to group multiple emails (https://bugzilla.mozilla.org/show_bug.cgi?id=411601 , https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/9e994fbb-b839-495f-84e3-2c8c02c7dd9b?redirectedfrom=MSDN).

If GMail uses subject match to group iTop notifications, would this still work if an attribute value used in the notification subject changes ?

An other question would be, do we want different notifications (change, new caslog entry, state change, mention) for the same object to group ?

2022-02-23 15:02 UTC, Molkobain commented
> If GMail uses subject match to group iTop notifications, would this still work if an attribute value used in the notification subject changes ?

After a quick test, this doesn't work, a new subject means a new thread on GMail.
 
> An other question would be, do we want different notifications (change, new caslog entry, state change, mention) for the same object to group ?

Ideally yes, I would like to have all emails about the same object to be on the same thread, but if you could just group on similar mail subject it would already be a great step forward.

2022-02-23 15:19 UTC, Molkobain commented
After playing a bit, Stephen found that simply prefixing the mail subject with "Re: " in the action allowed the grouping in Outlook.
So we could imagine that iTop would add it automatically to ActionEmail but we haven't found a great condition yet.

2022-02-23 15:29 UTC, Hipska requested changes
Hereby I confirm grouping is currently also not working for Apple's Mail (macOS,iOS)

2022-02-23 15:29 UTC, Hipska commented on core/action.class.inc.php
> +				$sPrefix = sprintf('iTop_%s_%d', $sObjClass, $sObjId);
What about
```suggestion
				$sPrefix = sprintf(ITOP_APPLICATION_SHORT.'_%s_%d', $sObjClass, $sObjId);
```
or
```suggestion
				$sPrefix = sprintf('%s_%s_%d', ITOP_APPLICATION_SHORT, $sObjClass, $sObjId);
```

2022-02-23 15:29 UTC, Hipska commented on core/action.class.inc.php
> +					'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->Get('friendlyname').')',
```suggestion
					'Object' => $sObjClass.'::'.$sObjId.' ('.$oObject->GetRawName().')',
					'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->GetRawName().')',
```

Also, the `DBObject` class should have a `__toString`-like method that does this in one go. Unfortunately, the existing one returns html representation. (a `ToRawString` or something)

2022-02-23 15:34 UTC, Molkobain commented on core/action.class.inc.php
> +					'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->Get('friendlyname').')',
Exactly my thought, we repeat this pattern on several occasion and it would be great to have it, but I'm didn't find a good name for it yet.

2022-02-23 15:36 UTC, Molkobain commented on core/action.class.inc.php
> +				$sPrefix = sprintf('iTop_%s_%d', $sObjClass, $sObjId);
I'm not sure of the consequences if an app has white-space or a special char within this constant (it is redefined by people building a different application upon iTop Community)

2022-02-23 15:49 UTC, Hipska commented on core/action.class.inc.php
> +				$sPrefix = sprintf('iTop_%s_%d', $sObjClass, $sObjId);
Maybe sanitise it first?

2022-02-23 16:24 UTC, Molkobain commented on core/action.class.inc.php
> +				$sPrefix = sprintf('iTop_%s_%d', $sObjClass, $sObjId);
Yes, done in b22d8dce7a1d19c568388eeb5f4287f67241eb6f (I was lazy, I admit it 🙈)

2022-02-23 16:24 UTC, Hipska approved these changes

2022-02-24 08:44 UTC, Hipska commented
@Molkobain If you want me to test this behaviour on Apple's mail, just send me 2 notification mails and I'll let you know if it worked..

2022-02-24 09:42 UTC, Hipska commented on core/action.class.inc.php
> +					'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->Get('friendlyname').')',
Yeah, looking at the other existing methods, `ToRawString` or `GetAsRawString` would suffice. I also had a look and maybe we can just adapt the existing `__toString` method:
```php
	/**
	 * String representation of the object
	 *
	 * Only a few meaningful information will be returned.
	 * This representation is for debugging purposes, and is subject to change.
	 *
	 * @param bool $bHTML The returned string is raw HTML
	 *
	 * @return string
	 * @throws \ArchivedObjectException
	 * @throws \CoreException
	 * @throws \DictExceptionMissingString
	 */
	public function __toString($bHTML = true)
	{
        $sRet = '';
        $sClass = static::GetClassName(get_class($this));
        $iPKey = $this->GetKey();
        if ($bHTML) {
	        $sRootClass = MetaModel::GetRootClass($sClass);
	        $sFriendlyName = $this->GetAsHTML('friendlyname');
	        $sRet .= "<b title=\"$sRootClass\">$sClass</b>::$iPKey ($sFriendlyName)<br/>\n";
        } else {
        	$sFriendlyName = $this->GetRawName();
        	$sRet .= sprintf('%s::%d (%s)', $sClass, $iPKey, $sFriendlyName);
        }
        return $sRet;
	}
```

2022-02-24 09:49 UTC, Molkobain commented
> @Molkobain If you want me to test this behaviour on Apple's mail, just send me 2 notification mails and I'll let you know if it worked..

Sent, thanks!

2022-02-24 10:34 UTC, Hipska commented
Works perfectly:
![image](https://user-images.githubusercontent.com/228588/155507814-de63232e-17f4-43c4-9dfb-636122c6d8f0.png)

2022-02-24 10:42 UTC, Molkobain commented
> Works perfectly [...]

For real?!

Well, I guess this isn't perfect as it does not group all messages about an object on the same thread, but this could already be a step forward. Thanks Thomas for the test! 😊

2022-03-01 16:22 UTC, Molkobain commented
Accepted in technical review.

2022-03-01 16:28 UTC, Hipska approved these changes

2022-03-01 16:29 UTC, piRGoif requested changes
Very nice phpdoc and comments, bravo !
I'm just asking for a small change in GenerateIdentifierForHeaders method as I find the current code not very readable ?

2022-03-01 16:29 UTC, piRGoif commented on core/action.class.inc.php
> +		switch ($sHeaderName) {
I found the switch syntax kinda difficult to read

I would rather move the exit condition directly in the method first lines.
Then having the regular code below...

2022-03-01 21:13 UTC, Molkobain commented on core/action.class.inc.php
> +		switch ($sHeaderName) {
With the current implementation, when new identifier types will be added, we'll only need to add code (new case), no refactor will be necessary (change of code of the exit condition), reducing the risk of regressions.

What I can propose to simplify a bit is:
  * Move the exception after the switch as the fallback behavior
  * Move the return condition in the case block

That way we keep the "code addition" principle and get a bit of simplification.

2022-03-02 09:34 UTC, piRGoif commented on core/action.class.inc.php
> +		switch ($sHeaderName) {
YAGNI and KISS ?
When we'll add new header types, it will be time to refactor.
You're introduce now an unnecessary complexity for something we're not sure we will even need one day... I don't like it much :/

2022-03-03 08:00 UTC, Molkobain commented on core/action.class.inc.php
> +		switch ($sHeaderName) {
_Just pushed a commit to move the invalid condition after the switch_

To me it's way more simpler to understand/read the logic as-is than to use the header type constants in several IF conditions, but if the rest of the team feels like you I'll change it. (For logic changes, I think we should tend to something most of the devs are confortable with, rather than just choose between the two of us)

PS: Is the following what you had in mind?

```
	protected function GenerateIdentifierForHeaders(DBObject $oObject, string $sHeaderName): string
	{
		$sObjClass = get_class($oObject);
		$sObjId = $oObject->GetKey();
		$sAppName = utils::Sanitize(ITOP_APPLICATION_SHORT, '', utils::ENUM_SANITIZATION_FILTER_VARIABLE_NAME);

		if (! in_array($sHeaderName, [static::ENUM_HEADER_NAME_MESSAGE_ID, static::ENUM_HEADER_NAME_REFERENCES])) {
			$sErrorMessage = sprinf('%s: Could not generate identifier for header "%s", only %s are supported', static::class, $sHeaderName, implode(' / ', [static::ENUM_HEADER_NAME_MESSAGE_ID, static::ENUM_HEADER_NAME_REFERENCES]));
			IssueLog::Error($sErrorMessage, LogChannels::NOTIFICATIONS, [
				'Object' => $sObjClass.'::'.$sObjId.' ('.$oObject->GetRawName().')',
				'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->GetRawName().')',
			]);
			throw new Exception($sErrorMessage);
		}
		
		if (in_array($sHeaderName, [static::ENUM_HEADER_NAME_MESSAGE_ID, static::ENUM_HEADER_NAME_REFERENCES])) {
			// Prefix
			$sPrefix = sprintf('%s_%s_%d', $sAppName, $sObjClass, $sObjId);
			if ($sHeaderName === static::ENUM_HEADER_NAME_MESSAGE_ID) {
				$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
			}
			// Suffix
			$sSuffix = sprintf('@%s.openitop.org', MetaModel::GetEnvironmentId());
			// Identifier
			$sIdentifier = $sPrefix.$sSuffix;
			if ($sHeaderName === static::ENUM_HEADER_NAME_REFERENCES) {
				$sIdentifier = "<$sIdentifier>";
			}
		}
		
		return $sIdentifier;
	}
```

2022-03-03 08:55 UTC, Hipska commented on core/action.class.inc.php
> +					$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
You're adding the time as part of the identifier? Not sure if that is a good idea, there are better and more secure ways to add some random data.

2022-03-03 09:05 UTC, piRGoif commented on core/action.class.inc.php
> +		switch ($sHeaderName) {
Here is what I suggest : 

```
	/**
	 * @param \DBObject $oObject
	 * @param string $sHeaderName one of {@see \ActionEmail::ENUM_HEADER_NAME_REFERENCES} or {@see \ActionEmail::ENUM_HEADER_NAME_MESSAGE_ID}
	 *
	 * @return string The formatted identifier for $sHeaderName based on $oObject
	 * 
	 * @throws CoreUnexpectedValue if sHeaderName is not one of the expected value
	 * @throws \CoreException
	 * 
	 * @since 3.0.1 N°4849
	 */
	protected function GenerateIdentifierForHeaders(DBObject $oObject, string $sHeaderName): string
	{
		$sObjClass = get_class($oObject);
		$sObjId = $oObject->GetKey();

		if (false === in_array($sHeaderName, [static::ENUM_HEADER_NAME_MESSAGE_ID, self::ENUM_HEADER_NAME_REFERENCES], true)) {
			$sErrorMessage = sprinf('%s: Could not generate identifier for header "%s", only %s are supported', static::class, $sHeaderName, implode(' / ', [static::ENUM_HEADER_NAME_MESSAGE_ID, static::ENUM_HEADER_NAME_REFERENCES]));
			IssueLog::Error($sErrorMessage, LogChannels::NOTIFICATIONS, [
				'Object' => $sObjClass.'::'.$sObjId.' ('.$oObject->GetRawName().')',
				'Action' => get_class($this).'::'.$this->GetKey().' ('.$this->GetRawName().')',
			]);
			throw new CoreUnexpectedValue($sErrorMessage);
		}

		$sAppName = utils::Sanitize(ITOP_APPLICATION_SHORT, '', utils::ENUM_SANITIZATION_FILTER_VARIABLE_NAME);

		// Prefix
		$sPrefix = sprintf('%s_%s_%d', $sAppName, $sObjClass, $sObjId);
		if ($sHeaderName === static::ENUM_HEADER_NAME_MESSAGE_ID) {
			$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
		}
		// Suffix
		$sSuffix = sprintf('@%s.openitop.org', MetaModel::GetEnvironmentId());
		// Identifier
		$sIdentifier = $sPrefix.$sSuffix;
		if ($sHeaderName === static::ENUM_HEADER_NAME_REFERENCES) {
			$sIdentifier = "<$sIdentifier>";
		}

		return $sIdentifier;
	}
```

2022-03-03 09:06 UTC, piRGoif commented on core/action.class.inc.php
> +					$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
This is what was implemented before the PR... Changing this should be done in another PR I think ?

2022-03-03 09:08 UTC, Hipska commented on core/action.class.inc.php
> +					$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
Correct, but before it was also using "iTop" instead of `ITOP_APPLICATION_SHORT`.

Next to that, I also think the app name should be part of the suffix, not the prefix.

2022-03-03 10:08 UTC, Molkobain commented on core/action.class.inc.php
> +					$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
Indeed microtime was already part of the `Message-ID` and `References`.
With this PR we remove the microtime from `References` to enable the grouping as intended. It is now only in `Message-ID`.

We could find something else maybe but in another PR I agree.
Replacing "iTop" with the constant doesn't introduce a change of the generated header for standard products (iTop Community / Essential / Professional); it might change behavior for people repackaging / rebranding the app, but it's out of our scope (should be documented in migration notes though).

2022-03-08 15:58 UTC, Molkobain commented
Accepted in functional review, will be part of 2.7.7 / 3.0.2

2022-03-08 16:23 UTC, piRGoif commented on core/action.class.inc.php
> +					$sPrefix .= sprintf('_%f', microtime(true /* get as float*/));
As Hipska agrees, closing this conversation

2022-03-10 08:31 UTC, merged