N°4947 Fix \EMail::LoadConfig
Combodo/iTop pull request #278
Opened 2022-03-11 16:27 UTC by piRGoif

In \EMail::SendSynchronous we are calling \EMail::LoadConfig, which is always loading config using the production environment.
We should instead use the standard \utils::GetConfig method !

Thanks to @jbostoen for the bug report (see https://github.com/Combodo/iTop/pull/223#issuecomment-1064854430) !

2022-03-11 16:30 UTC, Hipska requested changes

2022-03-11 16:30 UTC, Hipska commented on core/email.class.inc.php
> +			self::$m_oConfig = utils::GetConfig();
Why using `utils::GetConfig()` while the constructor uses `MetaModel::GetConfig()`? This seems inconsistent..

2022-03-11 16:33 UTC, piRGoif commented on core/email.class.inc.php
> +			self::$m_oConfig = utils::GetConfig();
Ouch, didn't see that, thanks !

2022-03-11 16:35 UTC, piRGoif commented on core/email.class.inc.php
> +			self::$m_oConfig = utils::GetConfig();
Fixed in 12951f8a

2022-03-11 16:41 UTC, Hipska requested changes
When the LoadConfig is already done in the constructor, there is no need to do it on other places anymore..

2022-03-11 16:41 UTC, Hipska commented on core/email.class.inc.php
> +		);
```suggestion
		$this->SetRecipientFrom(
			static::$m_oConfig->Get('email_default_sender_address'),
			static::$m_oConfig->Get('email_default_sender_label')
		);
```

2022-03-11 16:41 UTC, Hipska commented on core/email.class.inc.php
> +			self::$m_oConfig = utils::GetConfig();
```suggestion
		if (is_null(static::$m_oConfig)) {
			static::$m_oConfig = utils::GetConfig();
```

2022-03-11 16:44 UTC, piRGoif commented on core/email.class.inc.php
> +		);
I found my solution easier to read...
Guess we'll see what other devs will say during the review

2022-03-11 16:47 UTC, Hipska commented on core/email.class.inc.php
> +		);
What if removing the `LoadConfig` and `$m_oConfig` completely and do this in construct then: `$oConfig = utils::GetConfig()`. It doesn't make much sense to have it as a static var.

2022-03-15 09:35 UTC, piRGoif commented on core/email.class.inc.php
> +		);
In the legacy code, there were lots of static attributes to save the config object (it was the case in the utils class before 2.7.0 and that was the main reason why I was calling it a mess :o) ). I guess this was done for performance reasons ? 
Removing `\EMail::$m_oConfig` is something we'll have to discuss during this PR dev review indeed !
I have some doubt personally, as the class can be called multiple times without the MetaModel loaded, so this would mean opening the config file each time...

There are no reasons to keep the `\EMail::LoadConfig` call in `\EMail::SendSynchronous` though, so I'm removing it ! (commit 1ab3a51f)

2022-03-15 09:43 UTC, Hipska approved these changes

2022-03-15 09:43 UTC, Hipska commented on core/email.class.inc.php
> +		);
It indeed makes sense to not to have to load the config multiple times if metamodel isn't loaded yet. I agree to keep it static for now.

PS; just make sure it's using `static::$m_oConfig` instead of `self::$m_oConfig` everywhere.

2022-03-15 11:21 UTC, piRGoif commented
Indeed, there were quite a few remaining uses of the attribute with the "self" keyword. I've changed them in 8640918d
Thanks !

2022-03-15 12:31 UTC, Hipska approved these changes

2022-04-05 15:06 UTC, Molkobain commented on core/email.class.inc.php
> +	public function LoadConfig()
Can you just add an `@since` to notify of the param removal?

2022-04-05 15:06 UTC, Molkobain approved these changes

2022-04-05 15:06 UTC, Molkobain commented
Accepted during technical review.

2022-04-05 15:43 UTC, piRGoif commented on core/email.class.inc.php
> +	public function LoadConfig()
Waiting for the functional review so that we know in which version this will be merged

2022-04-12 15:01 UTC, Molkobain commented
Accepted in functional review.
Will be merged on support/2.7 branch **only once the 2.7.7 is out**, so we can test it on 3.0.2 first.

2022-04-12 15:53 UTC, Hipska commented on core/email.class.inc.php
> +		);
Sorry to come back on this, but what do you think of the following?
```php
$oConfig = $this->LoadConfig();
```

2022-04-19 14:11 UTC, piRGoif commented on core/email.class.inc.php
> +	public function LoadConfig()
Done in 9ea94415

2022-04-19 14:17 UTC, piRGoif commented on core/email.class.inc.php
> +		);
Done in 99ab128d :)
Closing this conversation

2022-08-17 09:26 UTC, piRGoif commented
The Email class was totally refactored in iTop 2.7.7 : 

* eb1d56f43942b3f49275005073919a701f13d109
* 754946bf62fcc9f62ddaf8120951b6c6127001e1
* 622f40c06cf9d3dbe170416498c4906dd1314318

Rebasing this branch cannot be done anymore. I'm closing this PR and opening a new one.

2022-08-17 09:26 UTC, closed without merging

2022-08-17 09:51 UTC, Molkobain commented
Can the delete the branch?

2022-08-17 09:54 UTC, piRGoif commented
Now that I finished the new PR, yes :)