Fix default priority to undefined
Combodo/iTop pull request #279
Opened 2022-03-11 16:53 UTC by TimotheEchirolles

By default, if no urgency or impact have been selected in a user request, the priority shown is Critical
![priority_01](https://user-images.githubusercontent.com/101416770/157911742-4b311f87-b720-411c-929e-948e7c80315e.png)

It is misleading when the impact is set to only one person : changing the value of urgency from undefined to critical change the priority from critical to high !
![priority_02](https://user-images.githubusercontent.com/101416770/157910724-bb6237d3-9a55-4023-9414-b28bfde2c399.png)

I suggest changing the default priority (when no priority can be computed) to undefined ($iPriority is null)
![priority_fixed](https://user-images.githubusercontent.com/101416770/157911233-fd1e87f9-4d40-462d-a3b3-2c2f2a571136.png)

The provided implementation has been tested on the 4 cases : user request (all in one), user request (itil), incident and problem

2022-03-14 09:05 UTC, Hipska commented
IMHO `null` should be selected when a non-existing mapping for impact & urgency combination is used. (for example when user added new options via extensions). And the default priority in all other cases could maybe be lowered to "medium" or even "low", but that actually doesn't matter much as both fields are required.

2022-03-14 18:08 UTC, piRGoif commented
Hello,
Can you modify this PR's description to add the info that this was always present ? As your screenshots represent a 3.0.0 version, there is an ambiguity that this is a regression fix :/

2022-03-15 08:10 UTC, Hipska commented
> Can you modify this PR's description to add the info that this was always present ? As your screenshots represent a 3.0.0 version, there is an ambiguity that this is a regression fix :/

Pierre, this doesn't seem more relevant than on any other PR IMHO. So I would either request this for all fix-PR's or none. Not just only this one because it happens to be the first one since 3.0 release.

2022-03-15 09:53 UTC, piRGoif commented
Thomas, believe me we will need this information during internal PR review meeting !
Especially cause this PR is based on the develop branch (not on support/2.7) and has iTop 3.0.0 screenshots only in its description.

If you have any other PR in mind where this should be necessary, just comment on those.
Do not add the needed information just because it might also be needed in other PR doesn't seems right to me.
There are 30 PR in Combodo org repos that were created after iTop 3.0.0 delivery (search with : `org:Combodo is:public is:pr created:>=2022-01-01`), 10 of them contains the "bug" label, none opened PR are based on the develop branch.

2022-03-15 10:31 UTC, Hipska commented
This is actually not really the place to discuss this, but I'm going to add one example:
PR's on branch develop created after release of 2.7 would have the same ambiguity: Screenshots could meant it was a bug in 2.7, 2.6, 2.5 or even older..

I do agree it's useful information to know on which versions a problem/bug exists, but not just because of there happens to be screenshots from the latest version only in the PR.

2022-03-15 11:30 UTC, piRGoif commented
> IMHO `null` should be selected when a non-existing mapping for impact & urgency combination is used. (for example when user added new options via extensions). And the default priority in all other cases could maybe be lowered to "medium" or even "low", but that actually doesn't matter much as both fields are required.

Not sure what you meant ? 
After this PR if no mapping exists in `$aPriorities` we will return null indeed ?

Adding new values will force to override the whole method just to specify new elements in `$aPriorities`, this is bad :/ We might change that in another PR.

2022-03-15 11:31 UTC, piRGoif approved these changes, later dismissed

2022-03-15 12:36 UTC, Hipska commented
What I was hinting to, was actually; If a person already selects an Impact (or Urgency) only, the Priority could be set to "low" or "medium" instead of "undefined". But as said, it doesn't matter much, since both the fields are required.

2022-03-15 12:37 UTC, Hipska approved these changes, later dismissed

2022-03-15 13:22 UTC, piRGoif commented
Oh ok, seems to make sense. We should talk about this in the functionnal review meeting

2022-04-05 15:05 UTC, Molkobain submitted a review, later dismissed

2022-04-05 15:05 UTC, Molkobain commented
Accepted during technical review

2022-04-12 15:41 UTC, Molkobain commented
Functional review: Setting value to null can be an issue for someone who customized the datamodel and allowed 1 of the 2 attributes to not be mandatory anymore. In that case, the user will get an exception on save.

Code should be adjusted so it sets the default value to either:
  * null is attribute is nullable
  * its default value if attribute is NOT nullable

2022-04-12 15:43 UTC, Molkobain commented
Also @Timmy38 can you create the corresponding ticket in our internal tracker? If already existing, please prefix the PR title with its reference (eg. "N°1234 - Blah blah") thanks!

2022-04-13 14:23 UTC, Hipska commented on datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
> +		$this->Set('priority', $iPriority);
What about this?

```suggestion
		$oAttDef = MetaModel::GetAttributeDef(get_class($this), 'priority');
		$iDefaultPriority = $oAttDef->GetDefaultValue();
		$this->Set('priority', $this->ComputePriority($iDefaultPriority));
```
Then you always start with setting priority to the default value and apply the correct one if there is a mapping..

2022-05-03 10:42 UTC, Hipska commented on datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
> +		$this->Set('priority', $iPriority);
@Timmy38 what do you think of my suggestion?

2022-05-03 11:14 UTC, Molkobain requested changes

2022-05-03 11:14 UTC, Molkobain commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
Mind the indentation please, same on the other files.

Also, now that the nullable property is tested in this method, we could make it even simpler, lines 1171-1175 could become the following. What do you think?
```
$oAttDef = MetaModel::GetAttributeDef(get_class($this), 'priority');
$iPriority = $oAttDef->IsNullAllowed() ? null : $oAttDef->GetDefaultValue();
```

2022-05-03 13:53 UTC, Timmy38 commented on datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
> +		$this->Set('priority', $iPriority);
Hello, I think it's better to compute everything priority-related (including default values) inside ComputePriority()

2022-05-03 14:00 UTC, Hipska commented on datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
> +		$this->Set('priority', $iPriority);
You got a point on that, but then I would also remove all datamodel dependent stuff from `ComputePriority` 😉

2022-05-03 14:02 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
@Molkobain What about this?

```php
$iPriority = (int) $this->Get('priority');
```

I think that will also always return the default value.

2022-05-03 14:19 UTC, Molkobain commented
Accepted in technical review

2022-05-03 15:20 UTC, Molkobain commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
I guess that in the case the attribute is nullable and has a default value of let say '4', it will return '4' which is not what we aim at.

2022-05-03 15:24 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
🤔 I think we do. If datamodel is set to `<default />` then we would get `null`.

2022-05-03 15:29 UTC, Molkobain commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
Hum, you are right. The excepted returned value in that case will be discussed next Tuesday

2022-05-10 15:33 UTC, Molkobain commented
Accepted in functional review

2022-05-10 15:36 UTC, merged

2022-05-10 15:41 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
What was the outcome, it seems to be merged as-is?

2022-05-11 08:13 UTC, Molkobain commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
Keeping it as-is was the preferred solution as some attributes are not prefilled on init.
Now this is going to be tested by the quality team.

2022-05-11 08:16 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
> +				}
👍 Thanks, my suggestion wasn't good anyway as it would return `0` when value would be `null`.