N°5090 Setup : improve missing dependencies message
Combodo/iTop pull request #280
Opened 2022-03-21 16:16 UTC by piRGoif

To reproduce, simply add a single module that is part of a multi module extension. 
For example itop-approval-portal or itop-standard-email-synchro

Before PR you'll get : 

![image](https://user-images.githubusercontent.com/8947448/159303923-3e5699d0-f4b6-4d9a-8514-5d9ec42e5f06.png)

After PR : 

![image](https://user-images.githubusercontent.com/8947448/159687942-22d70ff6-f17c-44d8-a5d8-65c5c6bebe94.png)

I also changed the MissingDependencyException parent (from Exception to CoreException), as this is an iTop exception !

2022-03-23 09:37 UTC, Molkobain commented on setup/modulediscovery.class.inc.php
> +	public function GetMessageForHtml()
Some PHPDoc and `@since` could be cool

2022-03-23 09:37 UTC, Molkobain commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
I find it a bit hard to read having the impacted module name in bold. It seems to big to me and I would rather have it all in regular weight, the hierarchy is enough to understand, but not a blocking point to me.

2022-03-23 09:37 UTC, Molkobain commented
Very nice initiative, should have been done so long ago... 😅😅😅

2022-03-23 09:43 UTC, Hipska commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
Maybe only the label in strong, and the module Id normal?

2022-03-23 09:53 UTC, Molkobain commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
Worth a try

2022-03-23 11:16 UTC, piRGoif commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
Without bold : 

![image](https://user-images.githubusercontent.com/8947448/159687169-d3dde839-74a2-447e-8980-7cae56757dbc.png)

Bold only on module label only: 

![image](https://user-images.githubusercontent.com/8947448/159687375-42595af9-7274-48dd-9910-7be4b3899be8.png)

And module code only:
![image](https://user-images.githubusercontent.com/8947448/159687501-3d94cca3-0dc9-4ad7-887e-f89e596c373d.png)

I like the second option ! 
Will commit that

2022-03-23 11:18 UTC, piRGoif commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
Done in 32896df9

2022-03-23 11:19 UTC, Hipska commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
I do like it as well, great!

2022-03-23 11:21 UTC, piRGoif commented on setup/modulediscovery.class.inc.php
> +	public function GetMessageForHtml()
Done in a1cc8d1c

2022-03-23 11:22 UTC, Hipska approved these changes

2022-03-23 14:09 UTC, jbostoen commented
Looks much nicer!

Is this also tackled in the CLI (unattended install)?

2022-03-23 14:31 UTC, piRGoif commented
> Looks much nicer!

Nice to see people liking this change :)
 
> Is this also tackled in the CLI (unattended install)?

I'll have to take a look !
Actually I didn't change the original behavior : the exception message is still set as before, so other consumers calling $e->getMessage() will still see the same thing.

I'll look at the code and keep you posted !

2022-03-23 15:53 UTC, Molkobain commented on setup/modulediscovery.class.inc.php
> +	<li><strong>{$sModuleLabel} ({$sModuleId})</strong>:
Great indeed 🙌

2022-03-23 15:54 UTC, Molkobain approved these changes

2022-03-24 08:28 UTC, piRGoif commented
> Is this also tackled in the CLI (unattended install)?

The [unattended_install script](https://www.itophub.io/wiki/page?id=latest:advancedtopics:automatic_install) will call this stack :

```
\SetupUtils::CheckSelectedModules
   \ModuleDiscovery::GetAvailableModules
      \ModuleDiscovery::GetModules
         \ModuleDiscovery::OrderModulesByDependencies
```

The MissingDependencyException will be thrown in \ModuleDiscovery::OrderModulesByDependencies
It will be catched in \SetupUtils::CheckSelectedModules and the exception's message will be thrown in the returned $aResult array.

So, no change here.

2022-04-05 15:17 UTC, Molkobain requested changes

2022-04-05 15:17 UTC, Molkobain commented on setup/modulediscovery.class.inc.php
> +	public function GetMessageForHtml()
Reviewed today, @piRGoif will rename the method to match `CoreException::getHtmlDesc()`

2022-04-05 16:03 UTC, piRGoif commented on setup/modulediscovery.class.inc.php
> +	public function GetMessageForHtml()
Done in b4840cca

2022-04-06 12:23 UTC, Molkobain approved these changes

2022-04-06 12:25 UTC, Molkobain commented
Accepted in technical review.

2022-04-12 15:00 UTC, Molkobain commented
Accepted in functional review, will be part of 2.7.7.
@piRGoif can you create the corresponding ticket and update the PR's title before we merge?

2022-04-15 15:26 UTC, piRGoif commented
Done !
Merging...

2022-04-15 15:30 UTC, merged