N°5867 Display binary data size in SynchroReplica details
Combodo/iTop pull request #286
Opened 2022-04-07 13:10 UTC by Hipska

Currently the SynchroReplica details page shows all data from the `synchro_data` table as unformatted/raw. With this change it doesn't try to display binary data directly anymore, but it now shows the size of the data.

Before:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/228588/162205457-0efce859-34a1-4971-a611-6308186690ce.png">

After:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/228588/182122174-61683cc1-4002-4734-b556-d1284a7ad4d8.png">

Disclaimer: The sample data is not an actual image, but just 128 sample bytes.

2022-04-07 13:29 UTC, piRGoif commented
Hello,
Do you need to see the base64 content ? Or should we replace it with the mention "blob" and value size maybe ?

2022-04-07 14:28 UTC, Hipska commented
No, but with it being base64 encoded, the user could copy and download/convert the data easier. But I like your suggestion as well.. Hmm 🤔

2022-05-11 07:33 UTC, Hipska commented
@piRGoif @Molkobain Do you have any update? What route should we take? Show content, show meta (size), show both?

2022-05-17 09:19 UTC, piRGoif commented
Hello,
Sorry I moved this PR to the "pending contributor" state and it was a bad idea...
I'll change the state again so that this PR will be processed on next reviews !

2022-06-07 15:53 UTC, piRGoif commented
Reviewed during PR technical review : actually the main problem is that we are getting raw data and display them as is... This will create problems also for HTML attributes for example...
We don't have any helper method for now that could help displaying raw values from a MySQL table (datasynchro data table)...

Can you also add a \utils::EscapeHtml call on value for attributes other than AttributeBlob ?
We all agreed displaying base64 data won't be very useful. What can be displayed instead ? I suggested the size, but there might be other metadata brought from the DB ? Having a download link would be ideal but that would mean create a new endpoint...

2022-06-08 12:47 UTC, Hipska commented
Hi @piRGoif I added the HTML escaping..

2022-06-29 13:14 UTC, piRGoif commented
Thanks Thomas !
Would you also replace the base64 value by something else, maybe the size ? To display the value properly you could use `\SetupUtils::HumanReadableSize`

2022-06-29 13:43 UTC, Hipska commented
I have done the change, but I feel like we still need to show the first x bytes (encoded)

2022-06-29 15:36 UTC, piRGoif commented
> I have done the change

Thanks !

> I feel like we still need to show the first x bytes (encoded)

Can you give some use cases where it would be useful ? We didn't find any when discussing about the feature ?

2022-06-29 15:36 UTC, piRGoif approved these changes

2022-06-29 15:40 UTC, Hipska commented
Yeah, what is the use case of this whole feature.. It gives the ability for the user to see if the data makes any sense or not.

But if you all agree that purely showing something as follows is good enough, then that's fine by me.
> _234 kB_

2022-06-29 15:42 UTC, piRGoif commented
:D
I understand !
There's no doubt this is far from ideal now, and still after this PR. 
But your PR improves things a bit, for us it's better now !
The PR will be reviewed again next week.

2022-06-30 08:10 UTC, Hipska commented
Maybe it should say something like this instead of only the size?
> _Binary data (234kB)_

2022-06-30 12:15 UTC, piRGoif commented
Very nice idea, OK for me ! I would maybe prefer "binary data", as "blob" is more of an implementation detail ?
Can you change it before the review on thursday ?

2022-06-30 12:31 UTC, Hipska commented
I would have used the dictionary for `Core:AttributeBlob`. But anyway, applied the requested change.

2022-06-30 12:34 UTC, piRGoif commented
Oh, I didn't knew `Core:AttributeBlob` : you're right, it's better to use it ! Sorry :/
Can you do this last change ?

2022-06-30 12:36 UTC, Hipska commented
It was also you that suggested to use "blob" anyway 😛 
> Hello,
> Do you need to see the base64 content ? Or should we replace it with the mention "blob" and value size maybe ?

2022-07-05 14:25 UTC, Molkobain commented
Accepted in technical review.

2022-07-26 21:49 UTC, Molkobain commented
Hello Thomas, next review in a few weeks, do you mind updating the picture in the OP to reflect the new result? It will ease convincing. Thanks!

2022-07-26 21:50 UTC, Molkobain requested changes

2022-07-26 21:50 UTC, Molkobain commented on synchro/synchrodatasource.class.inc.php
> +				else $aRows[] = array('attcode' => $sKey, 'data' => utils::EscapeHtml($value));
```suggestion
				else {
					$aRows[] = array('attcode' => $sKey, 'data' => utils::EscapeHtml($value));
				}
```

One line if statement are not part of the code conventions.

2022-07-26 21:50 UTC, Molkobain commented on synchro/synchrodatasource.class.inc.php
> +				if ((strpos(CMDBSource::GetFieldType($sSQLTable, $sKey), 'blob') !== false))
```suggestion
				if (strpos(CMDBSource::GetFieldType($sSQLTable, $sKey), 'blob') !== false)
```

2022-08-02 16:14 UTC, Molkobain commented on synchro/synchrodatasource.class.inc.php
> +				}
```suggestion
				if (strpos(CMDBSource::GetFieldType($sSQLTable, $sKey), 'blob') !== false) {
					$aRows[] = array('attcode' => $sKey, 'data' => sprintf('<i>%s (%s)</i>', Dict::S('Core:AttributeBlob'), utils::BytesToFriendlyFormat(strlen($value))));
				} else {
					$aRows[] = array('attcode' => $sKey, 'data' => utils::EscapeHtml($value));
				}
```

2022-08-02 16:15 UTC, Molkobain commented
_(Nevermind the notification, I thought I would be able to commit it directly myself. I'll do it aftermerge)_

2022-08-02 16:15 UTC, Molkobain approved these changes

2022-08-03 07:51 UTC, Hipska commented
Didn't got any notifications. If you still have suggestions, you can add them here..

2022-08-03 08:49 UTC, Molkobain commented on synchro/synchrodatasource.class.inc.php
> +				}
```suggestion
				if (strpos(CMDBSource::GetFieldType($sSQLTable, $sKey), 'blob') !== false) {
					$aRows[] = array('attcode' => $sKey, 'data' => sprintf('<i>%s (%s)</i>', Dict::S('Core:AttributeBlob'), utils::BytesToFriendlyFormat(strlen($value))));
				} else {
					$aRows[] = array('attcode' => $sKey, 'data' => utils::EscapeHtml($value));
				}
```

2022-08-03 08:51 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
> +				}
I already found your previous suggestion about the style a strange one 🙂

2022-08-03 08:53 UTC, Molkobain commented on synchro/synchrodatasource.class.inc.php
> +				}
Indeed 😅

2022-08-09 15:25 UTC, Molkobain commented
Hello Thomas,

This was accepted in functional review. Exceptionnaly as the rest of the feature (#269) was merged in support/3.0 we would like to merge this one in support/3.0 as well, can you rebase the PR?

Thanks,
Guillaume

2022-08-09 15:34 UTC, Hipska commented
These two are not dependant on each other.. It was already possible to sync binary data by directly connecting the datasynchro tables..

2022-08-10 07:24 UTC, Molkobain commented
So you won't rebase it?

2022-08-17 13:54 UTC, piRGoif commented
> These two are not dependant on each other.. It was already possible to sync binary data by directly connecting the datasynchro tables..

Well, I think Guillaume meant that we would like to group those 2 blob sync fixes in the same release :)
Are you ok to rebase this pr branch ?

2022-08-17 16:54 UTC, Molkobain commented
Indeed

2023-01-09 19:58 UTC, Molkobain commented
What is the status on this PR, I see it's on "pending contributor update". Did we just wanted to rebase on support/3.0 so we could merge it in the 3.0.2? If so, that train departed a long time ago, we could merge it in support/3.0 any time now.

@piRGoif @Hipska any memories?

2023-01-10 05:59 UTC, Hipska commented
I see in conversation history it was requested to base on 3.0, which I did.

2023-01-10 08:07 UTC, piRGoif commented
Hello,
Indeed we asked to rebase the branch on support/3.0.
Currently the branch start is 42599eae which is in develop...
Can you do the rebase Thomas ?

2023-01-10 08:28 UTC, Molkobain commented
Once rebased we can merge :)

2023-01-10 08:31 UTC, Hipska commented
Will look into it..

2023-01-10 16:39 UTC, Hipska commented
Whoa, that was a hard one, but it worked!

2023-01-10 17:50 UTC, piRGoif commented
Well done ! 
Merging !

2023-01-10 17:53 UTC, merged