🌐 Add dictionary items for integrity checks
Combodo/iTop pull request #288
Opened 2022-05-06 09:01 UTC by Hipska

Added dictionary items for:

- Leading message for `DBObject::CheckValue` result
- Leading message for `DBObject::CheckConsistency` result

Also cleaned up code for synchro replica slave attribute checks.

2022-05-06 09:20 UTC, Molkobain requested changes

2022-05-06 09:20 UTC, Molkobain commented on core/dbobject.class.php
> +				$this->m_aCheckIssues[] = Dict::Format('Core:CheckValueError', $sAttLabel, $sAttCode, $res);
Why put 3 parameters if only 2 are used in the dict. entry? This will lead to having the other parameter displayed after the string, not very slick.

2022-05-06 09:20 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
Same comment about the extra param not being used in the dict. entry

2022-05-06 09:23 UTC, Molkobain commented
Skip technical review as it's just new dict entries.

2022-05-06 09:24 UTC, Hipska commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
See the removed ToDo, there seems to be the intention of Combodo to add both in the message. So now users can already use it with their extension and/or Combodo only needs to update the respective dictionary item.

2022-05-06 09:25 UTC, Hipska commented on core/dbobject.class.php
> +				$this->m_aCheckIssues[] = Dict::Format('Core:CheckValueError', $sAttLabel, $sAttCode, $res);
Same here, I think it might be useful in the future, and then there is only a dictionary item change needed..

2022-05-06 09:30 UTC, Hipska commented on core/dbobject.class.php
> +				$this->m_aCheckIssues[] = Dict::Format('Core:CheckValueError', $sAttLabel, $sAttCode, $res);
> This will lead to having the other parameter displayed after the string, not very slick.

Whut? https://3v4l.org/pqZ5I

2022-05-06 12:25 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
For the PR either update the corresponding dict entry in EN / NL or remove this change.
We rather go all the way through an enhancement or keep as-is as the result in the UI will not be great : `The field start_date is not writable because it is mastered by the data synchronization. Value not set. - 2022-05-06 14:24:00`

2022-05-06 12:36 UTC, Hipska commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
I really don't see how you get to that result.. https://3v4l.org/pqZ5I

2022-05-06 12:50 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
I'm a bit confused, previously when we put a parameter in Dict::Format that was not used in the dict entry, it was appending it to the dict entry like on my previous comment. But I can't get this behavior now on a 3.0. Not sure if it is because of a PHP version change or something else.

2022-05-06 12:52 UTC, Hipska commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
No, that only happens if a dict entry doesn't exist. But in this PR I clearly created those dict entries.

2022-05-06 12:52 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
Anyway, either we update the dict entry or leave the TODO  as is; with the PR this is still a "TODO" as the dict entry does not use it.

2022-05-06 12:52 UTC, Molkobain commented on core/dbobject.class.php
> +				$this->m_aCheckIssues[] = Dict::Format('Core:CheckValueError', $sAttLabel, $sAttCode, $res);
_See discussion on the other thread_

2022-05-06 12:59 UTC, Hipska commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
I checked the code and for `Dict::Format` it hasn't been changed for 11 years. So we can safely assume it has been always like this.

2022-05-06 13:07 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
> I checked the code and for `Dict::Format` it hasn't been changed for 11 years. So we can safely assume it has been always like this.

Yeah, I might have seen this on dict entries for which I had not ran a setup yet I guess 👀 (as you said in https://github.com/Combodo/iTop/pull/288#discussion_r866796716)

> Anyway, either we update the dict entry or leave the TODO as is; with the PR this is still a "TODO" as the dict entry does not use it.

This is not resolved yet IMHO

2022-05-06 13:09 UTC, Hipska commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
I don't know how Combodo wants this entry to be formatted..

2022-05-11 07:10 UTC, Molkobain requested changes
Accepted in functional review once the 2 dict entries will be adjusted.

2022-05-11 07:10 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Core:CheckValueError' => 'Unexpected value for attribute \'%1$s\': %3$s',
This changes the printed string, it's now displaying the attribute label instead of the attribute code.
Proposed change so it displays everything:
```suggestion
	'Core:CheckValueError' => 'Unexpected value for attribute \'%1$s\' (%2$s) : %3$s',
```

2022-05-11 07:10 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
`'The field %1$s (%2$s) is not writable because it is mastered by the data synchronization. Value not set.~~'`

2022-05-11 08:16 UTC, Molkobain commented on core/dbobject.class.php
> +						$this->m_aCheckIssues[] = Dict::Format('UI:AttemptingToSetASlaveAttribute_Name', $sAttLabel, $sAttCode);
_Note: Just to be clear we'll wait on that entry update before merging the PR_

2022-05-11 08:21 UTC, Molkobain commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
Why this change?

2022-05-11 08:24 UTC, Hipska commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
See the commit message. My IDE was complaining return value would always be `false` if it isn't `true`. Which is not  correct, as in that case it's a string.

2022-05-17 09:25 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
Indeed, the caller \DBObject::DoCheckToWrite does use yes or a string, as of CheckValue()...

2022-05-17 09:26 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
I suggest we do a separate commit to update this PHPDoc ? 
@Molkobain if this modification is removed, the PR can be merged right ?

2022-05-17 13:36 UTC, Molkobain commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
Yep

2022-05-17 13:53 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @return true|string true if successful, the error description otherwise
PHPDoc updated directly in iTop support/2.7 branch, see 424e2a57
@Hipska can you remove this modification, and we'll be good to merge ?

2022-05-17 15:00 UTC, piRGoif approved these changes

2022-05-17 15:01 UTC, merged