Translation/zh cn
Combodo/iTop pull request #293
Opened 2022-05-18 05:23 UTC by bdejin

:globe_with_meridians: improve and add missing translation for Chinese (zh_cn)

2022-05-18 06:45 UTC, piRGoif requested changes
I don't understand the reason of some of the changes you made : removing spaces, changing some standard ascii characters by homographs...
Please explain this ?

2022-05-18 06:45 UTC, piRGoif commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> +	'bkp-next-backup-unknown' => '下一次备份<b>尚未被计划</b。',
Why changing "." to "。" ?

2022-05-18 06:45 UTC, piRGoif commented on datamodels/2.x/itop-config/dictionaries/zh_cn.dict.itop-config.php
> +	'config-apply-title' => '应用（Ctrl+S）',
Why changing "(" (U+0028) to "（" (U+FF08) ?

2022-05-18 06:45 UTC, piRGoif commented on datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
> +	'Class:NAS/Attribute:nasfilesystem_list+' => '此NAS中的所有文件系统',
Does removing the space after "NAS" was really intended ?

2022-05-18 07:10 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> +	'bkp-next-backup-unknown' => '下一次备份<b>尚未被计划</b。',
Also, the `<b>` tag is incorrectly closed..

2022-05-18 08:16 UTC, bdejin commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> +	'bkp-next-backup-unknown' => '下一次备份<b>尚未被计划</b。',
typo, correcting right now.

2022-05-18 08:32 UTC, bdejin commented on datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
> +	'Class:NAS/Attribute:nasfilesystem_list+' => '此NAS中的所有文件系统',
in English we have space (' ') between each word (to make them two words instead of one word), but in Chinese we do not use space - each Chinese character is a Chinese word. Having space in between make the sentence looks twisted, even mix with English word.

2022-05-18 08:35 UTC, bdejin commented on datamodels/2.x/itop-config/dictionaries/zh_cn.dict.itop-config.php
> +	'config-apply-title' => '应用（Ctrl+S）',
"(" (U+0028) is the punctuation mark for left bracket in English while "（" (U+FF08)  in Chinese. same as ")" in English but "）“ in Chinese.

2022-05-18 11:12 UTC, bdejin commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> +	'DBAnalyzer-Integrity-FinalClass' => '字段`%2$s`.`%1$s`必须有相同值而不非`%3$s`.`%1$s`',
typo, fix in following commit. 
'字段`%2$s`.`%1$s`必须有相同值而非`%3$s`.`%1$s`

2022-05-18 11:13 UTC, bdejin commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> +	'DBTools:LostAttachments:Disclaimer' => '您可以在此搜索数据库中丢失或错放的附件。这不是数据恢复同居，其无法恢复已删除的数据。',
typo, fix in next commit.
您可以在此搜索数据库中丢失或错放的附件。这不是数据恢复工具，其无法恢复已删除的数据。

2022-05-18 11:18 UTC, bdejin commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> +	'bkp-mysqldump-issue' => 'mysqldump无法运行（retcode=%1$d）：请确认它正确的安装路径,或者调整'.ITOP_APPLICATION_SHORT.'配置文件的选项mysql_bindir',
English comma, fix in following commit.
mysqldump无法运行（retcode=%1$d）：请确认它正确的安装路径**_，_**或者调整'.ITOP_APPLICATION_SHORT.'配置文件的选项mysql_bindir

2022-05-18 15:22 UTC, bdejin commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> +	'Class:Incident/Method:ResolveChildTickets+' => '级联解决子工单（事件自动解决），和调整以下内容保持一至：服务，团队，处理人，解决方案',
typo, fix in following commit.
级联解决子工单（事件自动解决），和调整以下内容保持一**_致_**：服务，团队，处理人，解决方案

2022-05-19 01:33 UTC, bdejin commented on datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
>  	'Error:XHR:Fail' => '无法加载数据, 请联系管理员',
change "," to "，"

2022-05-19 01:35 UTC, bdejin commented on datamodels/2.x/itop-problem-mgmt/dictionaries/zh_cn.dict.itop-problem-mgmt.php
>  	'Class:Problem/Attribute:knownerrors_list' => '已知问题',
change knowerror from "已知问题" to "已知错误"

2022-05-19 02:01 UTC, bdejin commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/zh_cn.dict.itop-request-mgmt-itil.php
> +	'Class:UserRequest/Method:ResolveChildTickets+' => '将此解决方案直接挪给子请求（自动解决），包括下列字段：服务，团队，处理人，解决方案',
improve "cascade to" and "align"

2022-05-19 02:08 UTC, bdejin commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Menu:ConfigManagement:AllContacts' => '所有联系人:%1$d',
change ":" to "："

2022-05-19 02:16 UTC, bdejin commented on dictionaries/ui/layouts/ui-content-block/zh_cn.dictionary.itop.ui-content-block.php
> +	'UIBlock:Error:AddBlockForbidden' => '无法添加块至%1$s~~',
remove "~~"

2022-05-19 02:19 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Core:UnknownObjectTip' => '找不到对象。其可能已经被删除了一段时间了并且日志已经被随之清楚了。',
fix typo
找不到对象。其可能已经被删除了一段时间了并且日志已经被随之**_清除_**了。

2022-05-19 02:34 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Core:DeletedObjectTip' => '此对象已经被删除位于%1$s（%2$s）',
improve
此对象已经被**_删除于_**%1$s（%2$s）

2022-05-19 02:37 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Core:AttributeExternalField+' => '映射道外键的字段',
fix typo
映射**_到_**外键的字段

2022-05-19 02:38 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Core:AttributePropertySet+' => '无类属性列表（名称和值）',
fix typo
无**_类型_**属性列表（名称和值）

2022-05-19 02:41 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:CMDBChangeOp/Attribute:finalclass+' => '类名称',
improve
**_终态类_**名称

2022-05-19 02:45 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:TriggerOnObject' => '触发器（类无关）',
fix typo
触发器（类**_相关_**）

2022-05-19 02:48 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
>  	'Class:lnkTriggerAction' => '操作/触发器',
improve
**_关联_**操作/触发器

2022-05-19 02:49 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
>  	'Class:SynchroDataSource/Attribute:delete_policy/Value:never' => 'Nobody',
improve.
**_没人_**

2022-05-19 02:55 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Core:BulkExport:InvalidParameter_Query' => '参数“query”的值不合法。没有查询手册对应此id：“"%1$s”。',
fix typo.
参数“query”的值不合法。没有查询手册对应此id：**_“%1$s”_**。

2022-05-19 02:59 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Class:AuditCategory/Attribute:description+' => '以前审计类别的详细描述',
fix typo.
**_此_**审计类别的详细描述

2022-05-19 02:59 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'Class:AuditCategory/Attribute:rules_list+' => '以前类别的审计规则',
fix typo.
**_此_**类别的审计规则

2022-05-19 03:02 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:WelcomeMenu:LeftBlock' => '<p>'.ITOP_APPLICATION_SHORT.'是完全开源的I 操作门户。</p>
fix typo.
是完全开源的**_IT_**操作门户。

2022-05-19 03:06 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:CSVImport:MappingNotApplicable'            => '--忽略此栏--',
improve.
--忽略此**_字段_**--

2022-05-19 03:12 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:AutoApplyConfirmationMessage' => '有些修改尚未生效。您希望'.ITOP_APPLICATION_SHORT.'估计这些吗？',
fix typo.
有些修改尚未生效。您希望'.ITOP_APPLICATION_SHORT.'**_顾及_**这些吗？

2022-05-19 03:13 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:ExtKey_AsFriendlyName' => '%1$s（昵称）',
improve.
%1$s（**_通用名_**）

2022-05-19 03:27 UTC, bdejin commented on dictionaries/zh_cn.dictionary.itop.ui.php
> +	'UI:DashletUnknown:RenderNoDataText:Edit' => '此组件五预览（类“%1$s”）。',
fix typo.
此组件**_无_**预览（类“%1$s”）。

2022-05-19 04:49 UTC, bdejin reviewed
fix typo and make a few improvments in following commit - done.

2022-05-19 04:54 UTC, bdejin reviewed
fix typo and make a few improvements in following commit - done.

2022-05-19 12:08 UTC, bdejin commented
> I don't understand the reason of some of the changes you made : removing spaces, changing some standard ascii characters by homographs... Please explain this ?

in Chinese there's no space between words, it make the sentence looks twisted, even mix with English word.
Chinese punctuation mark is different with English's. Chinese "，" is "," in English (comma), Chinese "。" is "." in English (full stop), Chinese "（" is "(" in English (open parenthesis). The punctuation mark is also Unicode.

2022-05-19 12:09 UTC, bdejin commented
> I don't understand the reason of some of the changes you made : removing spaces, changing some standard ascii characters by homographs... Please explain this ?

2022-05-19 12:10 UTC, bdejin commented
> closed

my bad... clicked the wrong button. :-(

2022-05-19 12:16 UTC, bdejin reviewed
new commit added.

2022-05-20 05:04 UTC, purplegrape commented
@bdejin 感谢对翻译工作的改进，多数改进都是有意义的，改进的质量也相当高，有部分内容需要商榷。
1、中文标点符号
我之前都是统一用的英文符号，无论用哪种标准都是可接受的，但要求统一。
2、专有名词缩写或中英文混合的情况下的缩进
语句里中英文混合的情况下，英文后加一个空格
3、翻译和代码改进分开提交

2022-05-20 05:11 UTC, purplegrape commented
@piRGoif  
translation and php code should have seperate PRs

2022-05-20 06:57 UTC, piRGoif commented
> translation and php code should have seperate PRs

I totally agree
But where do you see any PHP changed code in this PR ?

2022-05-20 07:01 UTC, piRGoif commented
> > I don't understand the reason of some of the changes you made : removing spaces, changing some standard ascii characters by homographs... Please explain this ?
> 
> in Chinese there's no space between words, it make the sentence looks twisted, even mix with English word. Chinese punctuation mark is different with English's. Chinese "，" is "," in English (comma), Chinese "。" is "." in English (full stop), Chinese "（" is "(" in English (open parenthesis). The punctuation mark is also Unicode.

Hello,

My reaction might seems a bit strange but some years of experience made me VERY cautious with everything related to Unicode parsers, homographs, and generally speaking everything outside of the Basic Multilingual Plane.

So, can you send 2 distinct references documenting those rules ?

2022-05-20 07:03 UTC, piRGoif commented
Also @bdejin you made lots of commits, are you still working on this ? 
And @purplegrape would you mind take a look at those new / modified translations ? (seems you began to do so ?)

2022-05-20 08:11 UTC, purplegrape commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> +	'DBTools:Disclaimer' => '免责申明：应用修复前备份数据库',
'DBTools:Disclaimer' => '免责申明：在修复之前, 请备份数据库',

2022-05-20 08:13 UTC, piRGoif commented
@purplegrape many thanks for the review !
May I suggest you use suggestions ? See point 6 in https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

2022-05-20 08:23 UTC, purplegrape commented on dictionaries/ui/components/datatable/zh_cn.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:LengthMenu'        => '_MENU_每页',
连字符后无空格，会不会可能造成代码异常？

2022-05-20 08:25 UTC, purplegrape commented on dictionaries/ui/components/datatable/zh_cn.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:Info'              => '_TOTAL_项',
连字符

2022-05-20 08:26 UTC, purplegrape commented on dictionaries/ui/pages/errorpage/zh_cn.dictionary.itop.errorpage.php
> +	'UI:ErrorPage:UnstableVersion' => '您正在使用可能有缺陷的不稳定版。如果您认为这个错误的产生与此相关，请您与我们发聩！',
反馈

2022-05-20 08:30 UTC, bdejin commented
> Also @bdejin you made lots of commits, are you still working on this ? And @purplegrape would you mind take a look at those new / modified translations ? (seems you began to do so ?)

Hi piRGoif, I finished the translation. The rests commits are for typo fixing during the review.

2022-05-20 08:32 UTC, bdejin commented on dictionaries/ui/pages/errorpage/zh_cn.dictionary.itop.errorpage.php
> +	'UI:ErrorPage:UnstableVersion' => '您正在使用可能有缺陷的不稳定版。如果您认为这个错误的产生与此相关，请您与我们发聩！',
> 反馈

@purplegrape 多谢。如何将review的反馈放入更改呢？是我继续在我的brach中修改然后commit吗？还是说这些修改会自动进入PR？

2022-05-20 08:46 UTC, bdejin commented
> @bdejin 感谢对翻译工作的改进，多数改进都是有意义的，改进的质量也相当高，有部分内容需要商榷。 1、中文标点符号 我之前都是统一用的英文符号，无论用哪种标准都是可接受的，但要求统一。 2、专有名词缩写或中英文混合的情况下的缩进 语句里中英文混合的情况下，英文后加一个空格 3、翻译和代码改进分开提交

@purplegrape，谢谢。我之前的本意是补充原翻译中遗漏的部分，在翻译过程中：1、发现绝大多数标点符号为英文标点但是少数为中文标点，所以想都统一处理为中文标点；2. 占位字符与翻译文的空格问题，如果替换占位符的为数字或者英文还好，一旦是中文，就会在长句中出现空格断句，因此想统一去掉空格。

您说的很对，翻译的时候其实想有个规范可以参照，比如前述的标点符号以及空格的处理，另外还有：1.一些专用词的翻译，如user request，究竟是用户需求还是用户请求？2.通用词的翻译，比如new翻译为新建还是创建，modify翻译为修改还是更改还是更新，我的习惯是尽量参照微软产品的翻译，虽然怎么翻译都还好但是最好统一。3.是一些英文语法与中文的差异，比如%1s for %2s，只是翻译英文单词可能在中文阅读习惯上就会有问题，如：%1s为%2s。这时翻译为%2s的%1s可能会更适合。原翻译中存在一些这样的情况但是我并没有来得及全部修改。

不知道我是不是应该取消这个PR，等上述所有点统一后重新review所有的翻译文字，确保统一后重新提交PR？您的建议是？

2022-05-20 09:06 UTC, purplegrape commented
> > @bdejin 感谢对翻译工作的改进，多数改进都是有意义的，改进的质量也相当高，有部分内容需要商榷。 1、中文标点符号 我之前都是统一用的英文符号，无论用哪种标准都是可接受的，但要求统一。 2、专有名词缩写或中英文混合的情况下的缩进 语句里中英文混合的情况下，英文后加一个空格 3、翻译和代码改进分开提交
> 
> @purplegrape，谢谢。我之前的本意是补充原翻译中遗漏的部分，在翻译过程中：1、发现绝大多数标点符号为英文标点但是少数为中文标点，所以想都统一处理为中文标点；2. 占位字符与翻译文的空格问题，如果替换占位符的为数字或者英文还好，一旦是中文，就会在长句中出现空格断句，因此想统一去掉空格。
> 
> 您说的很对，翻译的时候其实想有个规范可以参照，比如前述的标点符号以及空格的处理，另外还有：1.一些专用词的翻译，如user request，究竟是用户需求还是用户请求？2.通用词的翻译，比如new翻译为新建还是创建，modify翻译为修改还是更改还是更新，我的习惯是尽量参照微软产品的翻译，虽然怎么翻译都还好但是最好统一。3.是一些英文语法与中文的差异，比如%1s for %2s，只是翻译英文单词可能在中文阅读习惯上就会有问题，如：%1s为%2s。这时翻译为%2s的%1s可能会更适合。原翻译中存在一些这样的情况但是我并没有来得及全部修改。
> 
> 不知道我是不是应该取消这个PR，等上述所有点统一后重新review所有的翻译文字，确保统一后重新提交PR？您的建议是？

我在维护过程中，也碰到过你说的疑问，有一点感想分享
1、专用名词，
user request这类大标题肯定是要翻译的，至于是需求还是请求，前后一致就好，个人认为需求更显专业一点。
主题名称之类，比如dark moon，建议保留原样

2、通用词的翻译
前后一致为第一原则，适当考虑上下文语境，同一个词在中文里可能有多个意义。

3、英文语法与中文的差异问题
建议还是按照中文语法断句，不然怪怪的，该意译的意译。

4、标点符号
标点符号建议统一采用英文，方便开发者维护，界面显示差异不大，完全可以接受（可批量替换，很容易做到）
连字符之类的一定要空格，防止破坏代码

这个PR如果不涉及代码修改，可以一次性过掉。我再去review一下。

2022-05-20 09:07 UTC, Hipska commented
I think it would be best to keep conversations in English, so non-native speakers can follow as well..

2022-05-20 09:12 UTC, Molkobain commented on dictionaries/ui/components/datatable/zh_cn.dictionary.itop.datatable.php
> +	'UI:Datatables:Language:LengthMenu'        => '_MENU_每页',
I think you should leave the `_MENU_` placeholder as it will be replaced by the datatables lib

2022-05-20 09:25 UTC, purplegrape commented
@bdejin  please rollback punctuation to the english style

2022-05-20 09:29 UTC, bdejin commented
> > > @bdejin 感谢对翻译工作的改进，多数改进都是有意义的，改进的质量也相当高，有部分内容需要商榷。 1、中文标点符号 我之前都是统一用的英文符号，无论用哪种标准都是可接受的，但要求统一。 2、专有名词缩写或中英文混合的情况下的缩进 语句里中英文混合的情况下，英文后加一个空格 3、翻译和代码改进分开提交
> > 
> > 
> > @purplegrape，谢谢。我之前的本意是补充原翻译中遗漏的部分，在翻译过程中：1、发现绝大多数标点符号为英文标点但是少数为中文标点，所以想都统一处理为中文标点；2. 占位字符与翻译文的空格问题，如果替换占位符的为数字或者英文还好，一旦是中文，就会在长句中出现空格断句，因此想统一去掉空格。
> > 您说的很对，翻译的时候其实想有个规范可以参照，比如前述的标点符号以及空格的处理，另外还有：1.一些专用词的翻译，如user request，究竟是用户需求还是用户请求？2.通用词的翻译，比如new翻译为新建还是创建，modify翻译为修改还是更改还是更新，我的习惯是尽量参照微软产品的翻译，虽然怎么翻译都还好但是最好统一。3.是一些英文语法与中文的差异，比如%1s for %2s，只是翻译英文单词可能在中文阅读习惯上就会有问题，如：%1s为%2s。这时翻译为%2s的%1s可能会更适合。原翻译中存在一些这样的情况但是我并没有来得及全部修改。
> > 不知道我是不是应该取消这个PR，等上述所有点统一后重新review所有的翻译文字，确保统一后重新提交PR？您的建议是？
> 
> 我在维护过程中，也碰到过你说的疑问，有一点感想分享 1、专用名词， user request这类大标题肯定是要翻译的，至于是需求还是请求，前后一致就好，个人认为需求更显专业一点。 主题名称之类，比如dark moon，建议保留原样
> 
> 2、通用词的翻译 前后一致为第一原则，适当考虑上下文语境，同一个词在中文里可能有多个意义。
> 
> 3、英文语法与中文的差异问题 建议还是按照中文语法断句，不然怪怪的，该意译的意译。
> 
> 4、标点符号 标点符号建议统一采用英文，方便开发者维护，界面显示差异不大，完全可以接受（可批量替换，很容易做到） 连字符、变量之类的还是要空格，防止破坏代码
> 
> 这个PR如果不涉及代码修改，可以一次性过掉。我再去review一下。

好的，那等你review完我统一修改。

论文写作有两个参考规范，有空可以看下。不过软件翻译里我觉得purplegrape和Hipska说的没错，用英文标点可能更好点。
https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md
http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75604.html

2022-05-20 09:37 UTC, piRGoif commented
> https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md
> http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75604.html

Are those documents that detail chinese punctuation rules ? 
The first link is a document written solely in chinese I can't understand,
And following the second one my AV detects a malware :/

2022-05-20 09:48 UTC, purplegrape commented
> 

标点符号先回滚，其它没什么大问题

2022-05-20 09:49 UTC, purplegrape commented
> > > > @bdejin 感谢对翻译工作的改进，多数改进都是有意义的，改进的质量也相当高，有部分内容需要商榷。 1、中文标点符号 我之前都是统一用的英文符号，无论用哪种标准都是可接受的，但要求统一。 2、专有名词缩写或中英文混合的情况下的缩进 语句里中英文混合的情况下，英文后加一个空格 3、翻译和代码改进分开提交
> > > 
> > > 
> > > @purplegrape，谢谢。我之前的本意是补充原翻译中遗漏的部分，在翻译过程中：1、发现绝大多数标点符号为英文标点但是少数为中文标点，所以想都统一处理为中文标点；2. 占位字符与翻译文的空格问题，如果替换占位符的为数字或者英文还好，一旦是中文，就会在长句中出现空格断句，因此想统一去掉空格。
> > > 您说的很对，翻译的时候其实想有个规范可以参照，比如前述的标点符号以及空格的处理，另外还有：1.一些专用词的翻译，如user request，究竟是用户需求还是用户请求？2.通用词的翻译，比如new翻译为新建还是创建，modify翻译为修改还是更改还是更新，我的习惯是尽量参照微软产品的翻译，虽然怎么翻译都还好但是最好统一。3.是一些英文语法与中文的差异，比如%1s for %2s，只是翻译英文单词可能在中文阅读习惯上就会有问题，如：%1s为%2s。这时翻译为%2s的%1s可能会更适合。原翻译中存在一些这样的情况但是我并没有来得及全部修改。
> > > 不知道我是不是应该取消这个PR，等上述所有点统一后重新review所有的翻译文字，确保统一后重新提交PR？您的建议是？
> > 
> > 
> > 我在维护过程中，也碰到过你说的疑问，有一点感想分享 1、专用名词， user request这类大标题肯定是要翻译的，至于是需求还是请求，前后一致就好，个人认为需求更显专业一点。 主题名称之类，比如dark moon，建议保留原样
> > 2、通用词的翻译 前后一致为第一原则，适当考虑上下文语境，同一个词在中文里可能有多个意义。
> > 3、英文语法与中文的差异问题 建议还是按照中文语法断句，不然怪怪的，该意译的意译。
> > 4、标点符号 标点符号建议统一采用英文，方便开发者维护，界面显示差异不大，完全可以接受（可批量替换，很容易做到） 连字符、变量之类的还是要空格，防止破坏代码
> > 这个PR如果不涉及代码修改，可以一次性过掉。我再去review一下。
> 
> 好的，那等你review完我统一修改。
> 
> 论文写作有两个参考规范，有空可以看下。不过软件翻译里我觉得purplegrape和Hipska说的没错，用英文标点可能更好点。 https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75604.html

标点符号先回滚吧

2022-05-20 09:50 UTC, Hipska commented
Please use English!

2022-05-20 09:54 UTC, purplegrape commented
> Please use English!

waiting for another commit from @bdejin to rollback punctuation to the english style ，
after that，this PR will be mostly OK

2022-05-20 10:13 UTC, bdejin commented
> > https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md
> > http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75604.html
> 
> Are those documents that detail chinese punctuation rules ? The first link is a document written solely in chinese I can't understand, And following the second one my AV detects a malware :/

@piRGoif Never mind - it's a draft standard from Ministry of Education of China, for native writer.
I'm rolling the punctuation back to the english style, and will make another commit.

2022-05-20 11:44 UTC, piRGoif commented
> I'm rolling the punctuation back to the english style, and will make another commit.

Ok thanks !

2022-05-20 11:46 UTC, piRGoif commented
> after that，this PR will be mostly OK

Many thanks for your mutual work !

2022-05-31 07:44 UTC, piRGoif commented
Hello @bdejin, I've just reviewed the first files but still there are some changes in standard characters like parenthesis, comma and dot (for example in authent-local dict file). 
You may forgot to push the modifications to set back the original characters ?

2022-06-08 05:34 UTC, purplegrape commented
@bdejin any updates ?

2022-06-28 09:41 UTC, piRGoif commented
Closing this PR as said in #293

2022-06-28 09:41 UTC, closed without merging

2023-10-31 07:31 UTC, bdejin commented
@piRGoif @purplegrape Sorry I was transferred to another position and was blocked away from github for about a year 👎 
Anyway I'm back and made another PR for the translation improvement.
Glad to be here again and see you around. 👍