N°5235 Add tmp dir is writable check in setup
Combodo/iTop pull request #301
Opened 2022-06-15 13:25 UTC by piRGoif

If not present, will crash curing compilation (in \MFCompiler::Compile, when doing `unlink($sTempTargetDir);`)

2022-07-05 14:17 UTC, Molkobain commented
Accepted in technical review. @piRGoif will test on Windows / Linux env to ensure it does not bring any regression before reviewing it in functional review.

2022-07-05 15:24 UTC, piRGoif commented
For now, \SetupUtils::CheckWritableDirs only checks under APPROOT :(

2022-07-05 15:45 UTC, piRGoif commented
Now the readonly is correctly detected !
Rebased the branch by the way O:)

2022-07-05 15:47 UTC, piRGoif commented
Error message : 

![image](https://user-images.githubusercontent.com/8947448/177366846-588a9e8e-57e5-4b00-bab7-45e47674a66a.png)

And success message : 

![image](https://user-images.githubusercontent.com/8947448/177367052-f761bae7-3838-4e37-8036-e49b981d6b38.png)

2022-07-26 21:14 UTC, Molkobain requested changes

2022-07-26 21:14 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable for the application. Change its permission or use another dir (sys_temp_dir option in php
```suggestion
			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable by the application. Change its permission or use another dir (sys_temp_dir option in php.ini).");
```

To be consistent with the success message.

2022-07-26 21:14 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +		// check temp dir (N°5235)
```suggestion
		// Check temp dir (N°5235)
```

2022-07-26 21:17 UTC, Molkobain commented
Nice addition to the preliminary checks ✌

2022-07-27 08:44 UTC, Molkobain approved these changes

2022-08-02 14:31 UTC, Molkobain commented
Discussed during technical review: Why not include the directory test in the already existing `self::CheckWritableDirs()` method? Is it just for the specific error message?

2022-08-16 07:37 UTC, piRGoif commented
> Discussed during technical review: Why not include the directory test in the already existing `self::CheckWritableDirs()` method? Is it just for the specific error message?

That was what I wrote in my message dated of 5th july : this method is meant only to check dirs under approot for now... I tried first to refactor it, but it made the code complicated so I added the tmp dir check as a standalone test : simplier, much easier to read and understand.

2022-08-16 15:58 UTC, Molkobain commented
Ok thanks for the clarification, maybe we should add a comment above it to avoid someone to refactor this and put the tmp dir in the above array. What do you think?

2022-08-16 16:09 UTC, piRGoif commented
Yep, adding a phpdoc block to \SetupUtils::CheckWritableDirs would be a good idea !
I'll do it in the upcoming days

2022-08-17 07:25 UTC, piRGoif commented
Rebase branch  + force push

2022-08-17 07:56 UTC, piRGoif commented
PHPDoc added : 4a026469

2022-09-06 14:23 UTC, piRGoif commented
Processed today in technical review : good to go for functional review next week !

2022-09-06 14:35 UTC, Hipska approved these changes

2022-09-06 14:35 UTC, Hipska commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
```suggestion
	 * @return \CheckResult[] full path as key, CheckResult error as value
	 *
```

2022-09-06 16:26 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
I'm unsure this is right ? 
For me `\CheckResult[]` would mean there are no keys ? I mean we don't have an associative array ?

2022-09-06 21:33 UTC, Hipska commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
It says it’s an array, nothing about keys. But that is in the description. 

To me it is more clear than just “array”. I’m only not sure about the correct syntax.

2022-09-07 06:36 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
Not sure either :(

The phpdoc reference doesn't help as it does say nothing about associative arrays : https://docs.phpdoc.org/guide/references/phpdoc/types.html#arrays

In the PHPStan syntax I suppose the 3rd syntax is dedicated to associative arrays ? https://phpstan.org/writing-php-code/phpdoc-types#general-arrays
It says more in the Psalm reference : https://psalm.dev/docs/annotating_code/type_syntax/array_types/#generic-arrays

This article does sum up, and list indeed the type[] syntax as a standard indexed array (no keys), and describe both the phpstan and psalm syntax and array shapes.

This psalm / phpstan syntax seems to be understood well by PHPStorm, I've pushed ca699a45

2022-09-07 06:36 UTC, piRGoif commented
Rebased & forced pushed !

2022-09-07 07:14 UTC, Hipska commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
Yup indeed, if you want to be that specific, then it should become this: `* @return array<string, \CheckResult>`. Otherwise `* @return \CheckResult[]` or `* @return array<\CheckResult>` are sufficient.

2022-09-13 14:55 UTC, Molkobain commented
Functional review: See with @Rorcha07 for possible complications on exotic setups (eg. lodabalancers, netwrk drives, ...)
If any concern raised will be part of 3.1.0, if green light from Stephane then 2.7.8

2022-09-13 15:02 UTC, piRGoif commented
Discussed with Stephane : we will switch the check to warning so it will become non blocking. 
The information will still be there, and we won't block setup wrongly !

2022-09-13 16:18 UTC, piRGoif commented
New message when dir isn't writable moved to warning : 

![image](https://user-images.githubusercontent.com/8947448/189954139-eda2e2a5-d50a-40ab-948f-1dc60cfea8c3.png)

And after opening the details : 

![image](https://user-images.githubusercontent.com/8947448/189954190-ccc76a1a-1b20-46f0-9e52-b1c6d776f114.png)

2022-09-13 16:20 UTC, merged

2022-09-14 08:29 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +	 * @uses \CheckResult
I've just updated our [coding standards wiki page](https://www.itophub.io/wiki/page?id=latest:customization:coding_standards#phpdoc)

2022-09-14 19:28 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable by the application. Change its permission or use another dir (sys_temp_dir option in php.
Did you push your last modifications for changing the error into a warning? Because it still looks an error here.

2022-09-14 19:33 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable by the application. Change its permission or use another dir (sys_temp_dir option in php.
Nevermind I just saw it's done bdfe3a3b

2022-09-14 19:34 UTC, Molkobain commented
_Extra commit under bdfe3a3b to actually push the error to warning change_

2022-09-15 07:27 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable by the application. Change its permission or use another dir (sys_temp_dir option in php.
Yep, I made a mistake, forgot to push the modification before merging the PR (!!)
To make things a little clearer I've added a reference to this PR in the commit I've pushed after the pr merging.

2022-09-15 07:27 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +			$aResult[] = new CheckResult(CheckResult::ERROR, "The temp directory <b>'".$sTmpDir."'</b> is not writable by the application. Change its permission or use another dir (sys_temp_dir option in php.
See in the log : 

![image](https://user-images.githubusercontent.com/8947448/190341957-29bc93a3-1f5f-4e23-bc74-63dc85fc3329.png)