Parallelized cron
Combodo/iTop pull request #304
Opened 2022-07-04 11:28 UTC by eespie

Allow cron process to execute in parallel running different tasks.

Each task is only executed once at a time, but different tasks can run in parallel if multiple cron are executed.
The maximum number of parallel cron processes is configurable in iTop configuration.

The number of concurrent cron processes is obtained by configuring the 'cron_max_execution_time' and playing with the period of the cron. For example if the cron process last 10 minutes and the cron is launched every minute there will be roughly 10 parallel  cron running.

Another change is that the 'next_run_date' is calculated before running the task in order to have an update in case of problem and avoid running the same task again and again.

2022-07-04 15:40 UTC, Hipska approved these changes
Looks good. Plain simple implementation!

2022-07-04 15:40 UTC, Hipska commented on webservices/cron.php
> +		if ($aTasks == []) {
Wouldn't it be better to do this?
```suggestion
		if (empty($aTasks)) {
```

2022-07-05 14:32 UTC, Molkobain commented on core/config.class.inc.php
> +		'cron.max_process' => [
```suggestion
		'cron.max_processes' => [
```

2022-07-05 14:33 UTC, Molkobain commented on core/config.class.inc.php
> +			'description' => 'Maximum number of cron process to run',
```suggestion
			'description' => 'Maximum number of cron processes to run',
```

2022-07-05 14:33 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +			$iMaxCronProcess = $oConfig->Get('cron.max_process');
```suggestion
			$iMaxCronProcess = $oConfig->Get('cron.max_processes');
```

2022-07-05 14:37 UTC, Molkobain commented on webservices/cron.php
> +	$iMaxCronProcess = MetaModel::GetConfig()->Get('cron.max_process');
```suggestion
	$iMaxCronProcess = MetaModel::GetConfig()->Get('cron.max_processes');
```

2022-07-05 14:38 UTC, Molkobain commented on webservices/cron.php
> +		if ($aTasks == []) {
Yes, but we rather use `count($aTasks) === 0` than `empty()`

2022-07-05 14:38 UTC, Molkobain commented on webservices/cron.php
> +			if ($bVerbose && $aTasks == [])
There also

2022-07-05 14:41 UTC, Molkobain commented
@eespie will:
- Create the corresponding bug in the bug tracker.
- Discuss with @Rorcha07 about it
- Study debug / verbose output when several CRON instances are running, which could be an issue when trying to debug something

2022-08-17 11:26 UTC, Molkobain commented on sources/Service/Cron/CronLog.php
> +class CronLog extends LogAPI
```suggestion
/**
 * @since 3.1.0
 */
class CronLog extends LogAPI
```

2022-08-17 11:26 UTC, Molkobain commented on webservices/cron.php
> +				CronLog::Debug(sprintf('Task Class: %1$-25.25s Status: %2$-7s Last Run: %3$-19s Next Run: %4$-19s', $sTaskName, $sStatus, $sLastRunDate, $sNextRunDate));
Can you give an example of output? Seems more complicated to read than the previous way as there will be no columns anymore.

2022-08-17 11:26 UTC, Molkobain commented on webservices/cron.php
> +		if (count($aTasks) == 0) {
Missing "Sleeping...\n" debug message

2022-08-17 11:26 UTC, Molkobain commented on webservices/cron.php
> +			CronLog::Debug("Already $iMaxCronProcess are running...");
Having "Already 5 are running..." in the log might be clear to understand for someone troubleshooting/browsing the logs if it doesn't know the code.

What do you think of "Already 5/5 CRON processes are running, cannot start another one..." (or something similar) ?

2022-08-22 10:26 UTC, Hipska requested changes

2022-08-22 10:26 UTC, Hipska commented on webservices/cron.php
> - * @param bool $bDebug
debug param is still present..

2022-08-22 10:26 UTC, Hipska commented on webservices/cron.php
>  			}
I also think we have a mismatch with number of tasks planned and the number of tasks displayed. (When a tasks unable to get a mutex lock.)

2022-08-22 10:26 UTC, Hipska commented on webservices/cron.php
> +				$oTask = array_shift($aTasks);
Why not a simple foreach? Also, might be better to use `count($aTasks)`.

Edit: Just saw that was originally the case..

2022-11-18 10:24 UTC, Hipska commented on core/config.class.inc.php
> -		],
`cron_task_max_execution_time` is a settting that should stay I assume?

2022-11-18 10:41 UTC, eespie commented
Well, the parameter will stay, but the behaviour will change (the « multiplicated by its periodicity (in seconds) » part is not pertinent anymore)

From: Thomas Casteleyn ***@***.***>
Sent: Friday, November 18, 2022 11:25 AM
To: Combodo/iTop ***@***.***>
Cc: Eric Espié ***@***.***>; Mention ***@***.***>
Subject: Re: [Combodo/iTop] Parallelized cron (PR #304)


@Hipska commented on this pull request.

________________________________

In core/config.class.inc.php<https://github.com/Combodo/iTop/pull/304#discussion_r1026263712>:

> -            'cron_task_max_execution_time' => [

-                      'type' => 'integer',

-                      'description' => 'Background tasks will use this value (integer) multiplicated by its periodicity (in seconds) as max duration per cron execution. 0 is unlimited time',

-                      'default' => 0,

-                      'value' => 0,

-                      'source_of_value' => '',

-                      'show_in_conf_sample' => false,

-              ],

cron_task_max_execution_time is a setting that should stay I assume?

—
Reply to this email directly, view it on GitHub<https://github.com/Combodo/iTop/pull/304#pullrequestreview-1185842264>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA5LFBVWAAFE2MMPIQLEUP3WI5KO7ANCNFSM52S3YZZA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-18 10:42 UTC, eespie commented on core/config.class.inc.php
> -		],
Well, the parameter will stay, but the behaviour will change (the « multiplicated by its periodicity (in seconds) » part is not pertinent anymore)

2022-11-18 10:44 UTC, Hipska commented on core/config.class.inc.php
> -		],
Okay, but the current state of this PR just removes this setting parameter. Or did I miss something?

2022-11-18 10:51 UTC, eespie commented on core/config.class.inc.php
> -		],
right, it's an error, I should have just change the description... thx

2022-11-18 11:18 UTC, eespie commented on core/config.class.inc.php
> -		],
In fact 'cron_max_execution_time' is yet used, but 'cron_task_max_execution_time' is not used anymore... sorry for the confusion. The limit of execution of one task is the remaining cron execution time as it won't block other tasks anymore.
I'm sorry this project is pretty old now, and I'm not sure it will be integrated soon :(

2022-11-18 22:04 UTC, eespie commented on webservices/cron.php
> +				CronLog::Debug(sprintf('Task Class: %1$-25.25s Status: %2$-7s Last Run: %3$-19s Next Run: %4$-19s', $sTaskName, $sStatus, $sLastRunDate, $sNextRunDate));
The debug array has been removed because when logs are interleaved it's more complicated to read.
Here is a run of one cron instance:

```
cron1  3 Tasks planned to run now (2022-11-18 23:02:29):
cron1  Task Class: InlineImageGC             Status: active  Last Run: 2022-11-18 23:02:27 Next Run: 2022-11-18 23:02:28
cron1  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:02:27 Next Run: 2022-11-18 23:02:29
cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:02:29 Next Run: 2022-11-18 23:02:29
cron1  >> === 2022-11-18 23:02:29 Start task: InlineImageGC ==================================
cron1  InlineImageGC: Cleaned 0 old temporary InlineImage(s) and 0 old temporary Attachment(s).
cron1  << === 2022-11-18 23:02:29 End of:     InlineImageGC ================================== Next: 2022-11-18 23:02:30
cron1  2 Tasks planned to run now (2022-11-18 23:02:29):
cron1  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:02:27 Next Run: 2022-11-18 23:02:29
cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:02:29 Next Run: 2022-11-18 23:02:29
cron1  >> === 2022-11-18 23:02:29 Start task: ExecAsyncTask ==================================
cron1  ExecAsyncTask: processed 0 tasks
cron1  << === 2022-11-18 23:02:29 End of:     ExecAsyncTask ================================== Next: 2022-11-18 23:02:31
cron1  1 Tasks planned to run now (2022-11-18 23:02:29):
cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:02:29 Next Run: 2022-11-18 23:02:29
cron1  >> === 2022-11-18 23:02:29 Start task: PersonalDataAnonymizer =========================
cron1  << === 2022-11-18 23:02:29 End of:     PersonalDataAnonymizer ========================= Next: 2022-11-18 23:02:29
cron1  -- Skipping task: InlineImageGC -------------------------- until: 2022-11-18 23:02:30
cron1  -- Skipping task: ExecAsyncTask -------------------------- until: 2022-11-18 23:02:31
cron1  -- Skipping task: CheckStopWatchThresholds --------------- until: 2022-11-18 23:02:33
cron1  -- Skipping task: FullTextBackgroundRefresh -------------- until: 2022-11-18 23:02:43
cron1  -- Skipping task: ObsolescenceDateUpdater ---------------- until: 2022-11-18 23:12:07
cron1  -- Skipping task: BulkExportResultGC --------------------- until: 2022-11-19 11:12:51
cron1  -- Skipping task: FullTextBackgroundRebuildFullIndex ----- until: 2022-11-20 01:30:00
cron1  -- Skipping task: LogFileRotationProcess ----------------- until: 2022-12-01 00:00:00
cron1  -- Skipping task: BackupExec ----------------------------- until: 3000-01-01 00:00:00
cron1  sleeping...
```

2022-11-18 22:49 UTC, eespie commented on webservices/cron.php
> +				CronLog::Debug(sprintf('Task Class: %1$-25.25s Status: %2$-7s Last Run: %3$-19s Next Run: %4$-19s', $sTaskName, $sStatus, $sLastRunDate, $sNextRunDate));
An interleaved example (yes it's hard to follow):

```
2022-11-18 23:41:23 | Debug   | 1     | cron1  4 Tasks planned to run now (2022-11-18 23:41:23): | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  4 Tasks planned to run now (2022-11-18 23:41:23): | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:21 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:21 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: InlineImageGC             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:22 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: InlineImageGC             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:22 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: CheckStopWatchThresholds  Status: active  Last Run: 2022-11-18 23:41:13 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: CheckStopWatchThresholds  Status: active  Last Run: 2022-11-18 23:41:13 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  >> === 2022-11-18 23:41:23 Start task: PersonalDataAnonymizer ========================= | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  >> === 2022-11-18 23:41:23 Start task: InlineImageGC ================================== | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  InlineImageGC: Cleaned 0 old temporary InlineImage(s) and 0 old temporary Attachment(s). | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  << === 2022-11-18 23:41:23 End of:     InlineImageGC ================================== Next: 2022-11-18 23:41:24 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  << === 2022-11-18 23:41:23 End of:     PersonalDataAnonymizer ========================= Next: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  3 Tasks planned to run now (2022-11-18 23:41:23): | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: CheckStopWatchThresholds  Status: active  Last Run: 2022-11-18 23:41:13 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron4  3 Tasks planned to run now (2022-11-18 23:41:23): | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron4  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron4  Task Class: CheckStopWatchThresholds  Status: active  Last Run: 2022-11-18 23:41:13 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron1  >> === 2022-11-18 23:41:23 Start task: ExecAsyncTask ================================== | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron4  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  3 Tasks planned to run now (2022-11-18 23:41:23): | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: ExecAsyncTask             Status: active  Last Run: 2022-11-18 23:41:21 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: CheckStopWatchThresholds  Status: active  Last Run: 2022-11-18 23:41:13 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:23 | Debug   | 1     | cron2  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  ExecAsyncTask: processed 0 tasks | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  << === 2022-11-18 23:41:24 End of:     ExecAsyncTask ================================== Next: 2022-11-18 23:41:25 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron4  >> === 2022-11-18 23:41:24 Start task: CheckStopWatchThresholds ======================= | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  >> === 2022-11-18 23:41:24 Start task: ExecAsyncTask ================================== | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  2 Tasks planned to run now (2022-11-18 23:41:24): | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  Task Class: PersonalDataAnonymizer    Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:23 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  Task Class: InlineImageGC             Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:24 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  ExecAsyncTask: processed 0 tasks | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  << === 2022-11-18 23:41:24 End of:     ExecAsyncTask ================================== Next: 2022-11-18 23:41:25 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron1  >> === 2022-11-18 23:41:24 Start task: PersonalDataAnonymizer ========================= | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  1 Tasks planned to run now (2022-11-18 23:41:24): | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  Task Class: InlineImageGC             Status: active  Last Run: 2022-11-18 23:41:23 Next Run: 2022-11-18 23:41:24 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  >> === 2022-11-18 23:41:24 Start task: InlineImageGC ================================== | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  InlineImageGC: Cleaned 0 old temporary InlineImage(s) and 0 old temporary Attachment(s). | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  << === 2022-11-18 23:41:24 End of:     InlineImageGC ================================== Next: 2022-11-18 23:41:25 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: ExecAsyncTask -------------------------- until: 2022-11-18 23:41:25 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: CheckStopWatchThresholds --------------- until: 2022-11-18 23:41:33 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: FullTextBackgroundRefresh -------------- until: 2022-11-18 23:41:43 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: ObsolescenceDateUpdater ---------------- until: 2022-11-18 23:42:07 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: BulkExportResultGC --------------------- until: 2022-11-19 11:12:51 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: FullTextBackgroundRebuildFullIndex ----- until: 2022-11-20 01:30:00 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: LogFileRotationProcess ----------------- until: 2022-12-01 00:00:00 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  -- Skipping task: BackupExec ----------------------------- until: 3000-01-01 00:00:00 | Cron |||
2022-11-18 23:41:24 | Debug   | 1     | cron2  sleeping... | Cron |||
```

2023-01-09 10:05 UTC, Hipska commented on webservices/cron.php
> - * @param bool $bDebug
Can be marked as resolved..

2023-01-09 10:09 UTC, Hipska commented on webservices/cron.php
> +				$oTask = array_shift($aTasks);
Why this change?

2026-07-15 07:12 UTC, closed without merging