N°3213 - Add the possibility to manage the attributs' prompt order during a transition
Combodo/iTop pull request #306
Opened 2022-07-08 08:02 UTC by accognet

Transition screen before setting
 
![image](https://user-images.githubusercontent.com/57360138/177946123-4a21bf67-15d1-4e12-a133-7aaf73e93032.png)

Add this settings in xml file :
 
![image](https://user-images.githubusercontent.com/57360138/177946143-d6ca2f90-23e3-4df4-961a-0c0ff0f32799.png)

Transition screen after setting:
 
![image](https://user-images.githubusercontent.com/57360138/177946156-a97a14d1-ce08-4e26-8343-daf5ff0ab537.png)

The fields which should be displayed but which are not in the presentation config are added after.
If you add a field that should not be displayed, it is not displayed. Ex:
 
![image](https://user-images.githubusercontent.com/57360138/177946177-f37536b9-5b8d-40c9-85a9-83120a9dea42.png)

->	No modification of the display, the agent does not appear

2022-07-27 18:43 UTC, Molkobain commented
@accognet as this bug was planned on iTop 3.x I'm assuming that it is not a development for the upcoming 3.1, is it a proposition that you want to pitch during the bug review?

2022-08-01 14:00 UTC, accognet commented
No, this is a FAF

2023-02-06 10:05 UTC, accognet commented
Planned on iTop 3.1

2023-04-04 15:42 UTC, Molkobain commented
Discussed during technical review: Good PR but we need to discuss more deeply within the R&D team and with the Product team:
- Where to put the XML definition of this.
- How to make transition forms display as expected most of the time (ordered as the "details" zlist instead of ordered by dependencies) without forcing people to declare a zlist for a transition.

This will be discussed next week during functional review.

2023-04-05 07:33 UTC, Hipska requested changes

2023-04-05 07:33 UTC, Hipska commented on setup/compiler.class.inc.php
> +				$sZlists .= "		MetaModel::Init_SetZListItems('$sStimulusCode', $sZAttributes);\n";
What if a stimulus is named `details`, `list` or one of the search? There is no check and thus it will override them.

2023-04-05 07:51 UTC, Hipska commented on setup/compiler.class.inc.php
> +				$sZlists .= "		MetaModel::Init_SetZListItems('$sStimulusCode', $sZAttributes);\n";
I also think a call to `MetaModel ::RegisterZList()` is needed as otherwise this line will also generate a `CoreException` for "Wrong value".

2023-04-11 15:31 UTC, piRGoif commented
Functional review : 

Only one zlist for all transitions ? Simpler, yes do it ! But don't forget the fallback for forgotten fields (not defined in XML but present in the transition anyway) 
What name for the XML node ? To be discussed with Romain + Vincent (we might add a possibility to specify each transition in the future, but a transition is defined both by the stimulus and the target state)

In the meantime, implement the fallback : return the order similar to the one defined in the details zlist. This will be the new default behavior, product team is OK to change it in 3.1 (major release + nobody likes the current one)

Note that in the portal we already have one form per stimulus (see forms/form/modes/mode apply_stimulus)
Also note that there is an ongoing bug on n-n relations in transition forms (not enough width for now)

2023-05-02 11:26 UTC, Molkobain requested changes

2023-05-02 11:26 UTC, Molkobain commented on setup/compiler.class.inc.php
No need to change that file, revert changes.

2023-05-02 11:26 UTC, Molkobain commented on core/metamodel.class.php
Why this change? Please elaborate.

2023-05-02 11:26 UTC, Molkobain commented on application/cmdbabstract.class.inc.php
> +		}
As the new specification is to just display required (msut_xxx and mandatory attributes with no value), you don't need to do all that, we retrieve the flatten "details" zlist.

2023-05-02 14:21 UTC, Molkobain commented
Discussed during technical review:
  * Code needs to be simplified / commented
  * Attributes list / ordering has to be extracted in a dedicated method so we can add a unit test to it. Moreover, this will be discussed with the product team as the specifications / use cases do not seem to be clear for everyone.

2023-05-09 15:07 UTC, piRGoif commented
Accepted during Functional Review.
Warning : the current screenshot of a transition with the fix isn't up to date !

Anne Catherine did some changes to handle Guillaume feedbacks, they need to be reviewed technically.
Also we need to figure out how to add an automatic test.

2023-05-16 07:04 UTC, piRGoif commented on setup/compiler.class.inc.php
There are only formatting changes remaining now, so closing conversation

2023-05-16 07:05 UTC, piRGoif commented on core/metamodel.class.php
Seems like the change you're referring to isn't there anymore. Closing conversation.

2023-05-16 07:32 UTC, piRGoif requested changes
Ok changed reviewed !
Agree that we should create a test to document the ordering 
@accognet we might try to code it together ?

2023-05-16 07:34 UTC, piRGoif commented on setup/compiler.class.inc.php
> +				$sZlists .= "		MetaModel::Init_SetZListItems('$sStimulusCode', $sZAttributes);\n";
The changes were removed since then. Closing conversation.

2023-06-08 15:27 UTC, Molkobain commented on application/cmdbabstract.class.inc.php
> +		//Add forgotten attributes to the list
```suggestion
		// First attributes from the "details" zlist as they were sorted...
		$aList = $this->FlattenZList(MetaModel::GetZListItems($sClass, 'details'));

		// ... then append forgotten attributes
```

2023-06-08 15:27 UTC, Molkobain approved these changes

2023-06-08 15:29 UTC, merged