N°4342 - Generic bulk deletion function with memory limit handling
Combodo/iTop pull request #321
Opened 2022-08-08 12:52 UTC by accognet

Change function PurgeData in order to delete data by lot

2022-08-31 13:49 UTC, Molkobain requested changes

2022-08-31 13:49 UTC, Molkobain commented on core/config.class.inc.php
> +	 * @var integer Number of objects treated in a lot for bulk action (as anonymize, archival..)
```suggestion
	 * @var integer Number of objects treated in a lot for bulk action (as anonymize, archival..)
	 * @since 3.1.0	 
```

2022-08-31 13:49 UTC, Molkobain commented on core/config.class.inc.php
> +	public function GetMaxBufferSize()
```suggestion
    /*
     * @since 3.1.0
     */
	public function GetMaxBufferSize()
```

2022-08-31 13:49 UTC, Molkobain commented on core/config.class.inc.php
> +	public function SetMaxBufferSize($iMaxBufferSize)
```suggestion
    /*
     * @since 3.1.0
     */
	public function SetMaxBufferSize($iMaxBufferSize)
```

2022-08-31 13:49 UTC, Molkobain commented on core/metamodel.class.php
> +			$oSet = new DBObjectSet($oFilter, array(), array(), null, $iMaxBufferSize);
Rather than passing many default values, you can use the `SetLimit()`:

```suggestion
			$oSet = new DBObjectSet($oFilter);
			$oSet->SetLimit($iMaxBufferSize);
```

2022-08-31 13:49 UTC, Molkobain commented on core/metamodel.class.php
> +			if ($iNbIds == 0 || $iNbIds < $iMaxBufferSize) {
Not sure to understand this statement correctly, will discuss IRL

2022-09-01 06:20 UTC, Molkobain commented
I feel like we should rename the conf parameter to be more explicit about what it does and its usage. It's not a generic buffer size but a "chunk size" or "batch size" for purging data.

Also, why didn't added the conf parameter like the others in the big array instead of a constant?

2022-09-06 16:15 UTC, piRGoif commented
Discussed during technical review today.

Romain and Anne-Catherine will do a pre-review together. In particular we need to be sure : 
- where is this \MetaModel::PurgeData mehod used in iTop ?
- why do we have a memory limit error ? Does the GetColumnAsArray() will load the whole objects besides we only asked for 2 fields (id and finalclass) ?

About the config parameter : 
- using an attribute + a getter is the "old way". @accognet please move the declaration to the \Config::$m_aSettings instead
- the parameter shouldn't be visible by default (`show_in_conf_sample` array key)
- the param name could be `purge_data.chunk_size` ? 
- default value could be 1000

2023-08-22 09:38 UTC, Molkobain requested changes

2023-08-22 09:38 UTC, Molkobain commented on core/config.class.inc.php
> +			'description' => 'Maximum item deleted per loop. Used in function MetaModel::purgeData',
```suggestion
			'description' => 'Maximum item deleted per loop. Used in function MetaModel::PurgeData',
```

2023-08-22 09:38 UTC, Molkobain commented on core/config.class.inc.php
> +			// examples... not used
```suggestion
```

2023-08-22 09:38 UTC, Molkobain commented on core/metamodel.class.php
> +				$bExecuteQuery = false;
Can this be simplify to `$iNbIds < $iMaxChunkSize` ?

2023-08-29 13:37 UTC, favincen commented
Hi guys,
I am one of those who asked for a generic bulk deletion solution a while back, in Combodo's ticket R-032835 (which is linked to ER N°4342).
But discovering and reading the content of this PR, while I'm happy something is being done on this front, I realize we might not mean the same : 

As far as I understand the code, PurgeData will do only a brutal SQL purge of the object matching the provided filter. But it will NOT guarantee data integrity because it will not do a proper update or delete of related data (update N:N link tables and related objects' history, purge deleted objects' related CMDBChangeOp, block deletions not respecting mandatory link with manual deletion, etc.). As its comments state, "it bypasses standard objects handlers".
So it seems this current work would be useless for the use case where the data to be purged has datamodel dependencies (so any instance of class inheriting from cmdbAbstractObject).

What I meant when asking for a generic bulk deletion what to be able to mass delete any instance of classes inheriting cmdbAbstractObject, while respecting all iTop data handeling standards. So it would need to perform all iTop's standard data management to respect data integrity and proper historysation (like any deletionPlan would do). 
I saw that last version 1.3 of PersonnalDataAnonymizer extension includes some sort of such a batch mass data processing but at the moment I could not find any documentation on how it could be used outside of personal data anonymation for mass delete.

If that's ok with you, I would be interested to discuss this matter with you in any way you would see fit.

2023-08-29 13:41 UTC, Hipska commented
Hi @favincen, some of the developers are available on the [iTop community Slack team](https://join.slack.com/t/itopbycombodo/shared_invite/zt-uoat5wuf-C0g_1tqaeI9~EaqHxV7Q1Q).

2024-02-26 09:10 UTC, Molkobain commented
Remaining tasks:
- Add a unit test on the method
- Apply suggestions

2024-02-27 13:28 UTC, Molkobain commented on core/config.class.inc.php
> +			'description' => 'Maximum item deleted per loop. Used in function MetaModel::PurgeData',
```suggestion
			'description' => 'Maximum number of items deleted per loop. Used in function MetaModel::PurgeData',
```

2024-02-27 13:28 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
> +        $oConfig->Set('purge_data.max_chunk_size',2);
```suggestion
        $oConfig->Set('purge_data.max_chunk_size', 2);
```

2024-02-27 13:28 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
> +        for ($i=0;$i<10;$i++) {
```suggestion
        for ($i=0; $i < 10; $i++) {
```

2024-02-27 13:28 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
> +        $sDeleteOQL = 'SELECT '.$sClass.' WHERE id IN ('.implode(',',$aPkPerson).')';
```suggestion
        $sDeleteOQL = 'SELECT '.$sClass.' WHERE id IN ('.implode(',', $aPkPerson).')';
```

2024-02-27 13:28 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
> +        //Set max_chunk_size to 2 (default 1000) to test chunk deletion with only 10 items
```suggestion
        // Set max_chunk_size to 2 (default 1000) to test chunk deletion with only 10 items
```

2024-02-27 13:30 UTC, Molkobain commented on core/metamodel.class.php
> +				$bExecuteQuery = false;
This hasn't been fixed or argumented.

2024-02-27 13:31 UTC, Molkobain reviewed
Just the remaining conversation

2024-02-27 16:26 UTC, accognet commented on core/metamodel.class.php
> +				$bExecuteQuery = false;
Done

2024-02-27 19:53 UTC, Molkobain approved these changes

2024-02-27 19:53 UTC, Molkobain commented
Great, you can "squash & merge" !

2024-02-28 08:55 UTC, merged