N°4792 - memory limit is reached when an AttributeExternalKey is pointing to a class with an AttributeBlob
Combodo/iTop pull request #322
Opened 2022-08-08 14:29 UTC by eespie

What was done:
  * When requesting values for external keys in the case of combobox (request all possible values) the columns fetched are limitted to the minimum to avoid loading the full objects including blobs
  * __toString() was also added to DBSearch to ease debug

2022-08-08 15:08 UTC, Molkobain requested changes
Except from the "typo" seems all good to me ✌

2022-08-08 15:08 UTC, Molkobain commented on application/ui.extkeywidget.class.inc.php
> +			// #4792 - load only the required fields
```suggestion
			// N°4792 - load only the required fields
```

Just change this as #XXX are usually used for SourceForge ticket reference.

2022-08-08 15:09 UTC, Molkobain commented
_Also, for internal PRs can you add the "internal" label? Thanks_

2022-08-08 15:46 UTC, eespie commented
changed comment and fix data used from MetaModel::GetNameSpec()

2022-08-09 07:17 UTC, merged

2022-08-09 07:33 UTC, Hipska commented
Problem was the whole object from the external key was loaded? And the solution is now only the fields to make the friendlyname? Great improvement!

One question, will a programmer still be able to get any other field (by lazy loading) like this: `$oObject->Get('external_id')->Get('blob_field')`?

2022-08-09 07:58 UTC, eespie commented
The use of OptimizeColumnLoad() method is to be used with caution. If another column is requested with Get() then the object will be fully reloaded. So yes, it works, but the performances will be very bad.
In this specific case, the object is not used anymore after building the list.