N°3979 - Handle initial values on dependent fields
Combodo/iTop pull request #325
Opened 2022-08-10 14:23 UTC by accognet

When a field is hidden (due to display conditions), his initial (or previous) value is kept in metadata and post in a new field named previous_value. 
Some changes for this feature are in templates-base extension.

2022-08-11 14:43 UTC, rquetiez commented on js/console_form_handler.js
> +		    let me=this;
Please respect the spaces (me = this)

2022-08-11 14:45 UTC, rquetiez commented on js/console_form_handler.js
> +	    	if(this.element.find('[data-attribute-previous-value]').length>0) {
this.element.find('[data-attribute-previous-value]') is used three times. I suggest to factorize it into a variable previousValuesElements

2022-08-11 15:44 UTC, rquetiez commented
Work still to be done

1. Implement the same new behavior in the portal
2. Check that the change on readonly fields -cosmetic but not requested- is ok for every use case.

2022-08-12 07:43 UTC, accognet commented on js/console_form_handler.js
> +	    	if(this.element.find('[data-attribute-previous-value]').length>0) {
I think it's not necessary just for 2 times (the third time doesn't work). and for me,  it's easier to undestand like this.

2022-08-12 08:01 UTC, accognet commented
Done

2022-08-12 08:09 UTC, Molkobain requested changes

2022-08-12 08:09 UTC, Molkobain commented on js/console_form_handler.js
> +	                me.element.find('[data-field-id=previous_values]').find('input[type=hidden]').val('{}');
Please put quotes around attribute value in selectors.

```suggestion
	                me.element.find('[data-field-id="previous_values"]').find('input[type="hidden"]').val('{}');
```

2022-08-12 08:09 UTC, Molkobain commented on js/form_handler.js
> +				me.element.find('[data-field-id=previous_values]').find('input[type=hidden]').val(JSON.stringify(aPreviousValues));
Please put quotes in selectors, we discussed about this several times.

```suggestion
				me.element.find('[data-field-id="previous_values"]').find('input[type="hidden"]').val(JSON.stringify(aPreviousValues));
```

2022-08-12 08:09 UTC, Molkobain commented on sources/Renderer/Console/FieldRenderer/ConsoleSimpleFieldRenderer.php
> +						$oValue->AddSubBlock($oText);
You are adding several CSS classes so use the corresponding method `AddCSSClasses`, otherwise it will mess with the internal representation and possibly with some processing.

2022-08-12 08:09 UTC, Molkobain commented on js/form_handler.js
> +		_updatePreviousValues: function()
Add comment with iTop versions in which this is introduced (3.0.2, 3.1.0)

2022-08-12 15:48 UTC, merged