Feature/5024
Combodo/iTop pull request #327
Opened 2022-08-11 11:45 UTC by accognet

2022-08-11 13:24 UTC, Molkobain commented
PR is targeted to branch "develop" but is must be "support/3.0"

2022-08-12 06:26 UTC, eespie approved these changes

2022-08-12 07:41 UTC, Molkobain commented on pages/ajax.render.php
> -            $sAutocompleteOperation = utils::ReadParam('sAutocompleteOperation', null, false, 'raw_data');
I think we should keep this parameter as this endpoint can be use by something else with a specific operation.
(The following change needs to be rollbacked as well then)

2022-08-12 07:42 UTC, Molkobain commented on js/search/search_form_criteria_enum.js
> -                                });
Good catch!

2022-08-12 08:29 UTC, accognet commented on pages/ajax.render.php
> -            $sAutocompleteOperation = utils::ReadParam('sAutocompleteOperation', null, false, 'raw_data');
This argument is not used below. So for me, it's easier if we don't get the unused variables.

2022-08-12 08:45 UTC, Molkobain commented on pages/ajax.render.php
> -            $sAutocompleteOperation = utils::ReadParam('sAutocompleteOperation', null, false, 'raw_data');
Oh you are right, I didn't check the content of the `UIExtKeyWidget::AutoComplete()` method. Indeed it is not used anymore there, might be due to 3.0 refactoring.

Then it all good!

2022-08-12 08:46 UTC, Molkobain approved these changes

2022-08-12 08:47 UTC, Molkobain requested changes

2022-08-12 08:47 UTC, Molkobain commented on pages/ajax.render.php
> +				$oWidget->AutoComplete($oPage, $sFilter, $oObj, $sContains, $sOutputFormat, '');
Default value is not `''` but `null`. Anyway we might just not pass this argument if it is not used, what do you think?

```suggestion
				$oWidget->AutoComplete($oPage, $sFilter, $oObj, $sContains, $sOutputFormat);
```

2022-08-12 08:55 UTC, Molkobain approved these changes

2022-08-12 16:23 UTC, merged