Unit tests on XML assembly
Combodo/iTop pull request #329
Opened 2022-08-16 10:35 UTC by rquetiez

XML assembly has been developped originally under a TDD-like process, the test being a function direclty implemented into ModelFactory::testAlteration.

Running this function requires the implementation of a class derived from ModelFactory, just for that purpose.

Moreover, the tests were very limited. 

This works aims at writing a complete set of PHPUnit tests, that check the following algorithms in the area of XML assembly:
- Alterate the model by the mean of a Delta (XML with flags _delta)
- Alterate the model by the mean of MFElement APIs: Delete, SetChildNode, AddChildNode, RedefineChildNode and Rename
- Apply changes on the model
- Retrieve a Delta

2022-09-02 14:18 UTC, eespie approved these changes

2022-09-06 16:17 UTC, piRGoif commented
Discussed during the technical review today.
Ok to merge, but : 
- we need to rebase on support/2.7 first !
- also check the phpunit XML and advise when to run the tests

I'll do that :)

2022-09-07 13:50 UTC, piRGoif commented
Rebased on support/2.7 and forced pushed
Warning @rquetiez you'll need to destroy your local branch and ref and checkout again from origin !

2022-09-07 14:00 UTC, piRGoif commented
About phpunit xml : the added test is in test/setup/ModelFactoryTest.php, and this directory is indeed included in test/phpunit.xml.dist.
The whole test class takes 277ms to process on my laptop, so no problem to keep this test on commit !

2022-09-07 14:10 UTC, piRGoif commented
@rquetiez on \Combodo\iTop\Test\UnitTest\Core\ModelFactoryTest::testAlterationsByAPIs I've got an error on the `@covers \MFElement::GetDelta` phpdoc :
> [EA] @covers referencing to a non-existing entity '\MFElement::GetDelta'

I don't see any call to this method in the test ?

Also when checking each of those `@covers` tag seems like also `\MFElement::RedefineChildNode` and `\MFElement::Rename` aren't either called anywhere in the test ?

2022-09-12 08:20 UTC, Molkobain approved these changes

2022-09-28 14:47 UTC, rquetiez commented
> @rquetiez on \Combodo\iTop\Test\UnitTest\Core\ModelFactoryTest::testAlterationsByAPIs I've got an error on the `@covers \MFElement::GetDelta` phpdoc :
> 
> > [EA] @Covers referencing to a non-existing entity '\MFElement::GetDelta'
> 
> I don't see any call to this method in the test ?
> 
> Also when checking each of those `@covers` tag seems like also `\MFElement::RedefineChildNode` and `\MFElement::Rename` aren't either called anywhere in the test ?

Fixed, but RedefineChildNode is covered.

2022-10-07 15:40 UTC, piRGoif commented
> RedefineChildNode is covered.

Indeed : https://github.com/Combodo/iTop/pull/329/files?show-viewed-files=true&file-filters%5B%5D=#diff-da66df5f4729571ab380f32efac6c09f98f4993db648ec4b89ee51ab9c71c5e5R662

Thanks, ok for me !

2022-10-07 15:41 UTC, piRGoif approved these changes

2022-11-02 15:41 UTC, Molkobain requested changes

2022-11-02 15:41 UTC, Molkobain commented on test/ItopTestCase.php
> +	public function RecurseRmdir($dir) {
Discussed during technical review, `RecurseRmDir()` and following methods should not be there, they are not used.

2022-11-02 15:43 UTC, Molkobain commented on setup/modelfactory.class.inc.php
> +	}
Discussed with @rquetiez, he will check why this method was added.

2022-11-02 15:46 UTC, Molkobain commented on setup/modelfactory.class.inc.php
> +	}
It's because PR was originally made on the develop branch, rebase on the support/2.7 was not done correctly. Romain will fiw it.

2022-11-02 15:47 UTC, Molkobain commented on test/ItopTestCase.php
> +	public function RecurseRmdir($dir) {
It's because PR was originally made on the develop branch, rebase on the support/2.7 was not done correctly. Romain will fix it.

2022-11-02 15:48 UTC, Molkobain commented
_Moved to functional review to avoid loosing another month as it won't change functionally speaking_

2022-11-02 16:25 UTC, rquetiez commented on test/ItopTestCase.php
> +	public function RecurseRmdir($dir) {
I've done the cleanup

2022-11-02 16:26 UTC, rquetiez commented on setup/modelfactory.class.inc.php
> +	}
I've done the cleanup

2022-11-02 18:47 UTC, Molkobain requested changes
Since annotations are essentially for extension devs who add unit tests so they know in which version this methods were introduced.

Then the PR will be ok for me.

2022-11-02 18:47 UTC, Molkobain commented on test/ItopTestCase.php
> +	 * @throws \ReflectionException
```suggestion
	 * @throws \ReflectionException
	 * @since 2.7.8 3.0.3 3.1.0
```

2022-11-02 18:47 UTC, Molkobain commented on test/ItopTestCase.php
> +	 * @throws \ReflectionException
```suggestion
	 * @throws \ReflectionException
	 * @since 2.7.8 3.0.3 3.1.0
```

2022-11-02 18:47 UTC, Molkobain commented on test/setup/ModelFactoryTest.php
> +	protected function setUp():void
```suggestion
	protected function setUp(): void
```

2022-11-08 16:30 UTC, Molkobain commented
Accepted during functional review.

@rquetiez will create the corresponding bug in our internal tracker on the 2.7.8 milestone and update the PR's title accordingly.

2022-11-08 18:40 UTC, Molkobain approved these changes

2022-11-08 18:43 UTC, merged