N°1350 - audit improvements
Combodo/iTop pull request #330
Opened 2022-08-16 15:11 UTC by larhip

With this PR I would like to improve the audit feature of iTop in two aspects:

- 47414cc - Make it possible to configure the report color in the audit results (i.e. configure that the result should be only display as green in case of zero audit errors)
-  3dd1e90 - Deals with the issue that currently it is not possible to evaluate only some audit categories

Especially for the second commit the implementation is not final, but it should give you an idea about the concept:
What I basically did:

- Create a new class "Audit Domain" with an many to many relation to audit categories (for some reasons it was not possible to use tag set so I used a "normal" relation)
- For the audit page it is now possible to select an audit domain which should get evaluated rather than evaluate always all categories
- It is configureable where the start page of audits should the new "pre-selection" or the old behavior

Before going further with my implementation I would be pretty thankful for some feedback, whether the direction would be okay for you? 🙏 

Cheers
Lars

2022-08-31 13:38 UTC, Molkobain commented
Putting this PR to "Pending functional review" directly so we can give Lars feedback on how we would like things to be done.
Technical review can be done later on.

2022-08-31 14:13 UTC, Hipska commented
@larhip would you have some screenshots on how it looks after your change?

2022-08-31 14:41 UTC, larhip commented
For sure, find some screenshots below (created with Safari :-P)

_Linking Domains to Audit Category_

<img width="609" alt="image" src="https://user-images.githubusercontent.com/24569763/187705542-3a768536-baa3-48ca-ad40-e5aa988b6aec.png">

_Select wich domain to be reviewed_

<img width="957" alt="image" src="https://user-images.githubusercontent.com/24569763/187706056-ce6aec66-69d1-44ec-849c-48ce2b145263.png">

_Audit result for a domain_
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/24569763/187706198-b5096819-d6b6-40df-a4cf-1064e9d15a4a.png">

_Configure error tolerance_
<img width="530" alt="image" src="https://user-images.githubusercontent.com/24569763/187706487-8ed7294f-1637-47a9-af2e-bd08637a40e5.png">

2022-09-12 15:22 UTC, v-dumas commented
I had a demo by Lars on this PR. All the proposed ideas are useful and I have no better design than what is proposed. 
For me the PR is functionally ok and can be processed further, with a goal of being included in the 3.1 version

2022-09-13 14:15 UTC, Molkobain commented
Accepted in functional review, technical review will be next month.

2022-12-06 12:55 UTC, Molkobain requested changes

2022-12-06 12:55 UTC, Molkobain commented on application/application.inc.php
> +require_once(APPROOT.'/application/audit.domain.class.inc.php');
Is this necessary? Dumping the autoloaders through the composer.json file should enable this class to be autoloaded on demand.

2022-12-06 12:55 UTC, Molkobain commented on application/audit.category.class.inc.php
> +		if ( ($iTotal == 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
```suggestion
	/**
	 * @param int $iTotal
	 * @param int $iErrors
	 *
	 * @return string The color to use for this category depending on its error count and tolerance
	 * @since 3.1.0
	 */
	public function GetReportColor(int $iTotal, int $iErrors): string
	{
		$sResult = 'red';
		if ( ($iTotal === 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
```

2022-12-06 12:55 UTC, Molkobain commented on dictionaries/de.dictionary.itop.ui.php
>  ));
Following entries are missing:
```
	'Class:AuditCategory/Attribute:domains_list' => 'Domains',
	'Class:AuditCategory/Attribute:domains_list+' => 'List of domains linked to this category',

	'Class:AuditDomain' => 'Audit Domain',
	'Class:AuditDomain+' => '',
	'Class:AuditDomain/Attribute:name' => 'Name',
	'Class:AuditDomain/Attribute:name+' => '',
	'Class:AuditDomain/Attribute:description' => 'Description',
	'Class:AuditDomain/Attribute:description+' => '',
	'Class:AuditDomain/Attribute:icon' => 'Icon',
	'Class:AuditDomain/Attribute:icon+' => '',
	'Class:AuditDomain/Attribute:categories_list' => 'Categories',
	'Class:AuditDomain/Attribute:categories_list+' => 'Linked audit categories',

	'Class:lnkAuditCategoryToAuditDomain' => 'Link AuditCategory / AuditDomain',
	'Class:lnkAuditCategoryToAuditDomain+' => '',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:category_id' => 'Category',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:category_id+' => 'Audit Category',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:category_name' => 'Category name',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:category_name+' => 'Audit category name',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:domain_id' => 'Domain',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:domain_id+' => 'Audit domain',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:domain_name' => 'Domain name',
	'Class:lnkAuditCategoryToAuditDomain/Attribute:domain_name+' => 'Audit domain name',
```

2022-12-06 12:55 UTC, Molkobain commented on application/audit.category.class.inc.php
> +		if ( ($iTotal == 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
Can add in the PHPDoc if the returned color should be a valid HTML color or one of a predefined set?

2022-12-06 12:55 UTC, Molkobain commented on application/audit.domain.class.inc.php
> +require_once(APPROOT.'/application/audit.category.class.inc.php');
Is this necessary? Dumping the autoloaders through the composer.json file should enable this class to be autoloaded on demand.

2022-12-06 12:55 UTC, Molkobain commented on application/audit.domain.class.inc.php
> +class AuditDomain extends cmdbAbstractObject
```suggestion
/**
 * @since 3.1.0
 */
class AuditDomain extends cmdbAbstractObject
```

2022-12-06 12:55 UTC, Molkobain commented on application/audit.domain.class.inc.php
> +class lnkAuditCategoryToAuditDomain extends cmdbAbstractObject
```suggestion
/**
 * @since 3.1.0
 */
class lnkAuditCategoryToAuditDomain extends cmdbAbstractObject
```

2022-12-06 12:55 UTC, Molkobain commented on core/autoload.php
> +MetaModel::IncludeModule('application/audit.domain.class.inc.php');
Is this necessary? Dumping the autoloaders through the composer.json file should enable this class to be autoloaded on demand.

2022-12-06 12:55 UTC, Molkobain commented on pages/audit.php
> +	$bSelectionAuditRulesByDefault = MetaModel::GetConfig()->Get('audit.enable_selection_landing_page');
```suggestion
	$bSelectionAuditRulesByDefault = utils::GetConfig()->Get('audit.enable_selection_landing_page');
```

We tend to always retrieve conf params through the `utils` class now as when doing so through the `MetaModel` class it can fail if the MetaModel has not been started yet.
In this particular case it will always be started, but as people tend to copy/paste pattern we rather keep the good one as much as possible 😁

2022-12-06 12:55 UTC, Molkobain commented on pages/audit.php
> +			{
```suggestion
			while($oAuditDomain = $oDomainSet->Fetch()) {
```

2022-12-06 12:55 UTC, Molkobain commented on pages/audit.php
> +		$sCategories = utils::ReadParam('categories', '', false, 'raw_data');  // May contain commas
```suggestion
		$sCategories = utils::ReadParam('categories', '', false, utils::ENUM_SANITIZATION_FILTER_RAW_DATA);  // May contain commas
```

2022-12-06 16:30 UTC, Molkobain commented
> * Create a new class "Audit Domain" with an many to many relation to audit categories (for some reasons it was not possible to use tag set so I used a "normal" relation)

@larhip why couldn't you use a tagset attribute instead of the lnk relation?
Otherwise it was accepted during technical review once requested changes have been made.

2022-12-21 13:56 UTC, piRGoif commented on pages/audit.php
> +		$sCategories = utils::ReadParam('categories', '', false, 'raw_data');  // May contain commas
Maybe \utils::ENUM_SANITIZATION_FILTER_STRING would be enough ? Seems like this value is only used in an OQL query parameter so it could be safe keeping raw_data but nevertheless keeping a parameter without any sanitization should be done if there are absolutely no other possibility.

2022-12-30 11:11 UTC, larhip commented on application/application.inc.php
> +require_once(APPROOT.'/application/audit.domain.class.inc.php');
Since AuditDomain is a data model class it seems to be necessary.
Just using autoloader seem not to bee enough, since it should autoloader always not just on demand, otherwise the class is not available in the data model.
![image](https://user-images.githubusercontent.com/24569763/210063971-7d67f473-1ec7-4489-aeca-45c700cb2ba8.png)

Which leads into error like this:
![image](https://user-images.githubusercontent.com/24569763/210064027-f5947944-b0e2-45a2-ba44-b1cef92e46aa.png)

Anyhow It seems to make sense to update die autoloader (`composer dump-autoload -o`) so I did it.
And I removed the require_once from the other files (see below)

2022-12-30 11:11 UTC, larhip commented on application/audit.category.class.inc.php
> +		if ( ($iTotal == 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
Done

2022-12-30 11:11 UTC, larhip commented on dictionaries/de.dictionary.itop.ui.php
>  ));
Done, thanks for the hint

2022-12-30 11:17 UTC, larhip commented on application/audit.domain.class.inc.php
> +require_once(APPROOT.'/application/audit.category.class.inc.php');
not necessary at this point -> removed the line

2022-12-30 11:17 UTC, larhip commented on application/audit.domain.class.inc.php
> +class AuditDomain extends cmdbAbstractObject
Done

2022-12-30 11:18 UTC, larhip commented on core/autoload.php
> +MetaModel::IncludeModule('application/audit.domain.class.inc.php');
Remove at this file, but see my comment below regarding data model for the file `application.inc.php`

2022-12-30 11:18 UTC, larhip commented on pages/audit.php
> +	$bSelectionAuditRulesByDefault = MetaModel::GetConfig()->Get('audit.enable_selection_landing_page');
Check :-)
This is done

2022-12-30 11:19 UTC, larhip commented on pages/audit.php
> +			{
Check

2022-12-30 11:19 UTC, larhip commented on pages/audit.php
> +		$sCategories = utils::ReadParam('categories', '', false, 'raw_data');  // May contain commas
This is done as well. You are right Pierre `utils::ENUM_SANITIZATION_FILTER_STRING` will fit my need as well. 👍

2022-12-30 11:23 UTC, larhip commented
Thanks for your Review @Molkobain !
Sorry for my delay but I was not able to find some time earlier :-(

> @larhip why couldn't you use a tagset attribute instead of the lnk relation? Otherwise it was accepted during technical review once requested changes have been made.

I tired to use attribute tags during an initial implementation, but I was not able to use them, since `AuditCategory` is a "core class" defined in PHP and loaded earlier that the tags stuff..
Unfortunately the audit stuff is not a separated module (like `itop-data-audit`) so I needed a different solution.

2023-01-02 17:41 UTC, Molkobain commented on application/audit.category.class.inc.php
> +		if ( ($iTotal == 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
I don't see in the PHPDoc any mention of if it should be any valid HTML color or a predefined set.

2023-01-03 16:11 UTC, Molkobain commented
Accepted during technical review

2023-01-04 10:27 UTC, Molkobain commented
Hello @larhip ,

When checking out the PR, AuditDomain and lnkAuditCategoryToAuditDomain tables are not created in the DB during setup, which leads to a crash when opening the audit categories. Can you check your branch on a clean iTop instance?

Thanks

2023-01-09 15:58 UTC, larhip commented on core/autoload.php
> +MetaModel::IncludeModule('application/audit.domain.class.inc.php');
Ignore my last comment. 
It **is necessary**.
Without these line tables in database will be not created / altered.

2023-01-09 15:59 UTC, larhip commented
> When checking out the PR, AuditDomain and lnkAuditCategoryToAuditDomain tables are not created in the DB during setup, which leads to a crash when opening the audit categories. Can you check your branch on a clean iTop instance?

Checked this and added a "require_once" in `core/autoload.php` again to make it run.

2023-01-09 16:02 UTC, larhip commented on application/audit.category.class.inc.php
> +		if ( ($iTotal == 0) || ($iErrors / $iTotal) <= ($this->Get('ok_error_tolerance') / 100) )
Now I have updated PHPDoc: In detail the method should return a "semantic color" which could be used with the prefix `iso-is-`. In Example: To return the `success` should be fine as well. 
It might be difficult to use a predefined set here, since there are a lot of semantic colors. What do you think?

2023-01-09 19:05 UTC, Molkobain commented on core/autoload.php
> +MetaModel::IncludeModule('application/audit.domain.class.inc.php');
Damn, feels like we missed something within iTop as those classes should be loaded automatically not manually included in this file 😕
But that's outside of your PR's scope.

2023-01-09 19:14 UTC, Molkobain approved these changes

2023-01-09 19:25 UTC, Molkobain commented on application/audit.category.class.inc.php
> +	 * @return string A semantic color name (eg. red, green, orange, success, failure, ...) to use for this category depending on its error count and tolerance
```suggestion
	 * @return string A semantic color name (eg. red, green, orange, success, failure, ... {@see css/backoffice/utils/variables/colors/_semantic-palette.scss}) to use for this category depending on its error count and tolerance.
```

2023-01-09 19:26 UTC, Molkobain requested changes

2023-01-09 19:26 UTC, Molkobain commented on application/audit.category.class.inc.php
> +	 * @return string A semantic color name (eg. red, green, orange, success, failure, ...) to use for this category depending on its error count and tolerance
```suggestion
	 * @return string A semantic color name (eg. red, green, orange, success, failure, ... {@see css/backoffice/utils/variables/colors/_semantic-palette.scss}) to use for this category depending on its error count and tolerance
```

2023-01-09 19:27 UTC, Molkobain approved these changes

2023-01-09 19:27 UTC, Molkobain commented on application/audit.category.class.inc.php
> +	 * @return string A semantic color name (eg. red, green, orange, success, failure, ...) to use for this category depending on its error count and tolerance
Damn, I can't apply the suggestion myself. Nevermind, I'll apply it afterward.
PR is going to hit its final review tomorrow, then we are most likely to finally merge it!

2023-01-09 19:47 UTC, larhip commented on application/audit.category.class.inc.php
> +	 * @return string A semantic color name (eg. red, green, orange, success, failure, ...) to use for this category depending on its error count and tolerance
Not necessary, pushed it already :-)

2023-01-10 13:51 UTC, Molkobain commented on application/audit.category.class.inc.php
> +	 * @return string A semantic color name (eg. red, green, orange, success, failure, ...) to use for this category depending on its error count and tolerance
Thanks!

2023-01-10 15:54 UTC, piRGoif commented
Accepted during functional review for 3.1

2023-01-10 17:20 UTC, merged

2023-01-10 17:21 UTC, Molkobain commented
_As the 2 commits were clean enough and make sense, I made a rebase instead of a squash_

2023-01-24 08:59 UTC, v-dumas commented
Just wondering, how is the user supposed to create new AuditDomain?
I tried to create a Dashet Badge with Audit Domain without success, it's not in the list.
Should we create a specific menu, just for creating Audit Domain, or replace the Audit Category Search menu, by a dashboard menu, with a list of Category and a list of Domain?
Why AuditDomain wasn't created as a Typology? Any reason not to move it as a Typology child class?

2023-04-18 15:34 UTC, v-dumas commented
@larhip and @Molkobain the PR is supposed to be merged, also, with itop develop branch, running the audit does not propose me to select any Audit Domain, it directly performs the audit for All. Have we mist something in the merge?

I have not found any mean to run it just for one Audit Domain. 
Wondering if this resulting audit could be in an asynchronous tab of the Audit Domain object itself or an action from that Audit Domain...

2023-04-18 15:39 UTC, v-dumas commented
Ok, my fault, I mist this new configuration parameter: audit.enable_selection_landing_page to enable Audit Domain selection