Feature/5305 csvimport enhancement
Combodo/iTop pull request #332
Opened 2022-08-22 14:52 UTC by odain-cbd

N°5305 - CSV import ergonomy

we have seen that without any training on iTop it is hard to successively perform CSV imports. this PR aims at performing few UI changes that will help the user understanding his import issues on some specific fields. and myabe let him go through this process with some explanation on parsing or CMDB issues...

in details UI feedbacks have been improved to highlight in red the CSV import errors and message have been reworked as well on following attributes:

1- external fields:

- if there are no object at all related to the external field provided in the csv import (object Rack used here for example to create Server during import operation):

`There are no 'Rack' objects`

- if there are no object related to the external field provided in the csv import **that the user can see**

`There are no 'Rack' objects found with your current profile`

- if current user can see some objects but not all of them (2nd message limited to max 3 values)

`There are some 'Organization' objects not visible with your current profile
Possible 'Organization' value(s): Démo, Combodo, Schneider`

- if current user can see all objects (2nd message limited to max 3 values)

`No match for value 'XXX'
Possible 'Organization' value(s): Démo, Combodo, Schneider`

2- date fields

when there is date format error we propose always the same unambiguous date as an example to illustrate the current iTop valid date format:  '2022-10-23 16:17:33' 

3- enum/ tagset fields

below message is displayed with all possible values:

`Allowed 'type' value(s): production,staging,dev`

2022-08-26 10:02 UTC, odain-cbd commented
current work needs to be rebased properly in-between 3.0.x and 3.1.x... another PR will come soon

2022-08-26 12:37 UTC, piRGoif commented
Discussed with Olivier and Guillaume : PR re-opened as we will continue discussion here.
Before merging though we need to determine our branch model, we will do it next week, and rebase the PR as needed.

2022-08-31 15:34 UTC, piRGoif requested changes
Thanks for this nice work !

A few comments : 
- PR description : could you add a screenshot of the error messages before and after (they are now all in red color you said)
- PR description : add titles to ease reading...
- Too much inline comments in your code :( Prefer a readable code, and if a comment is absolutly necessary add it in PHPDoc block on structural element... 
- Document the \BulkChange::PrepareObject returned array structure ?

2022-08-31 15:34 UTC, piRGoif commented on test/ItopDataTestCase.php
> +		$oSet->AddItem($oUserProfile);
Are you sure ? DBObjectSet doesn't seem to have such method ?

2022-08-31 15:34 UTC, piRGoif commented on webservices/import.php
>  				}
I would prefer creating a dedicated method in CellChangeSpec, and a different impl in CellStatusIssue

Also, we should add a PHPDoc in this method detailing why we are changing the formatting in the CellStatus_Issue case

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		if (null == $this->m_sReason) {
Having === would be better, right ?

Or you may also use \utils::IsNullOrEmptyString instead ? (won't test the same thing, warning !)

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +
please add type hinting with phpdoc

also, explaining the meaning would be great !

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			return '';
Use instead \utils::IsNullOrEmptyString :)

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return Dict::Format('UI:CSVReport-Value-NoMatch-PossibleValues', $this->m_sTargetClass, $this->m_sAllowedValues);
Are null values correctly handled by this method ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +class RowStatus_Error extends RowStatus
Please use a PHPDoc block instead ! You're documenting the class itself not an isolated line of code

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
Woo, 5 elements returned by a method !! That's a lot :(
Would it be possible to use a DTO to explain the meaning ? Or at least document returned values in method PHPDoc block ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
targetclass and foreignattclass are contained in the AttDefinition right ? Maybe return $oExtKey instead ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
>  				switch($iCount)
I had hard time understanding what count we are talking about :/ Not your fault, this was made before, but can you rename the variable with a more meaningful name by the way ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +					//N°595 - display allowed valued for UI ergonomy
I this comment really useful ? Here the code speaks for itself I think ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +
This is the whole reason why this method exists : please move those comments in the method PHPDoc block !

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			//search link for exhaustive values
Why this comment line ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			//no objects at all
Your variables are named very well, not sure this comment line is useful ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			$oExtObjectSetWithCurrentUserPermissions->SetLimit(4);
Explaining why we are limiting could be an idea O:)

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			IssueLog::Error("failure when fetching few visible objects: " . $e->getMessage());
This log message doesn't have any context and won't be usable :( 

You may add first of all that we are in CSV import context... And also use the aContext param and add more information : for which class / attcode we are searching for example

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			IssueLog::Error("failure when fetching few visible objects: " . $e->getMessage());
Shouldn't there be a return block directly here ? Assuming the rest of the code will always behave safely is quite dangerous I think...

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			//__ERRORS__ used by tests only
Ideally this should be documented in a phpdoc with array shapes for example, or we could use a DTO...
But as we already discussed, here it won't be easy... and out of scope of this PR ! There are too much undocumented arrays passed from function to function in iTop :(

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +							$sDateExample = $oFormat->Format(new DateTime('2022-10-23 16:17:33'));
Good to have a value > 12 for the day, and > 12 for the hour. Might also have something > 23 for minute and seconds ?

2022-08-31 15:34 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +								$aResult[$iRow][$iCol] = new CellStatus_Issue(utils::HtmlEntities($sValue), null, $sErrorMsg);
Shouldn't it be the business of \CellChangeSpec::GetDisplayableValue to call HtmlEntities ? 
Also, prefer using the \utils::EscapeHtml method !

2022-08-31 15:34 UTC, piRGoif commented on test/webservices/ImportTest.inc.php
> +	const USE_TRANSACTION = false;
You are creating objects in setUp that aren't removed in tearDown, why disabling transactions so ?

2022-08-31 15:34 UTC, piRGoif commented on test/webservices/ImportTest.inc.php
> +		if (is_object($oRestProfile) && is_object($oAdminProfile))
Can the test go on if this is false ?

2022-08-31 15:34 UTC, piRGoif commented on test/webservices/ImportTest.inc.php
> +	public function ImportProvider(){
Won't it be clearer to have testImport as a private method, and each data provider extracted in a test method ?

2022-08-31 15:34 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +class BulkChangeExtKeyTest extends ItopDataTestCase {
Move those inline comments to the class phpdoc block please :)

2022-08-31 15:34 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +//DO NOT CHANGE USE_TRANSACTION value to avoid any DB loss!
The constant value isn't changed in the test ? maybe add the declaration once again and add a comment in the constant phpdoc block ?

2022-08-31 15:34 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +
This can be removed right ?

2022-08-31 15:34 UTC, piRGoif commented on test/ItopDataTestCase.php
> +	protected $iTestOrgId;
Why ? I see you're using this attribute in your tests, but it can be replaced by \Combodo\iTop\Test\UnitTest\ItopDataTestCase::getTestOrgId ?

2022-09-02 18:50 UTC, odain-cbd commented on test/ItopDataTestCase.php
> +		$oSet->AddItem($oUserProfile);
some phpunit test raised a warning and I have to replace AddObject with AddItem due to deprecation notices... I hope phpunit does not lie :)

2022-09-02 18:52 UTC, odain-cbd commented on webservices/import.php
>  				}
that portion of code "if ($value instanceof CellStatus_Issue){ " covers about 4 differents subclasses that inherit from CellStatus_Issue. one that I added in the scope of current PR.

2022-09-02 18:53 UTC, odain-cbd commented on core/bulkchange.class.inc.php
> +		if (null == $this->m_sReason) {
ok for "===" or is_null. I will change

2022-09-02 18:57 UTC, odain-cbd commented on core/bulkchange.class.inc.php
> +
good catch

2022-09-02 19:00 UTC, odain-cbd commented on test/core/BulkChangeExtKeyTest.inc.php
> +class BulkChangeExtKeyTest extends ItopDataTestCase {
ok

2022-09-02 19:02 UTC, odain-cbd commented on test/core/BulkChangeExtKeyTest.inc.php
> +
right :)

2022-09-02 19:05 UTC, odain-cbd commented on test/ItopDataTestCase.php
> +	protected $iTestOrgId;
sorry I did see that function getTestOrgId. even if it exists since 2017!

2022-09-02 19:35 UTC, odain-cbd commented on core/bulkchange.class.inc.php
> +			return '';
right

2022-09-02 19:36 UTC, odain-cbd commented on test/webservices/ImportTest.inc.php
> +	public function ImportProvider(){
ok for readability/maintenance reasons.

2022-09-06 07:28 UTC, piRGoif commented on test/ItopDataTestCase.php
> +	protected $iTestOrgId;
Ok, rolled back in e4eed8d9, closing conversation

2022-09-06 07:30 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		if (null == $this->m_sReason) {
Ok changed in e4eed8d9, closing conversation

2022-09-06 08:00 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +
Warning, you did add typing for `\CellStatus_SearchIssue::$m_sTargetClass` in e4eed8d9... But this isn't compatible with PHP < 7.4.0 (see https://www.php.net/manual/en/language.oop5.properties.php).
I was proposing adding phpdoc to explain the meaning of those attributes and also add type hinting (inside the phpdoc with `@var`).

Considering : 

* those attributes are new
* the min php version for the develop branch is PHP 7.4

It would be OK to keep the type declaration. But you are targeting the saas branch, so you may reconsider ? 

Also, both attributes are concerned O:)

2022-09-06 08:02 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			return '';
Ok, I saw you changed the test and add more conditions about array. I'm surprised you are testing that ? I'm closing this conversation, I'll add another comment in a review on the latest commit.

2022-09-06 08:03 UTC, piRGoif commented on test/webservices/ImportTest.inc.php
> +	public function ImportProvider(){
Done in e4eed8d9, thanks ! Closing this conversation

2022-09-06 08:04 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +class BulkChangeExtKeyTest extends ItopDataTestCase {
Done in https://github.com/Combodo/iTop/commit/e4eed8d94e3258b23d61de24f60b4a93b534f4e6, thanks ! Closing this conversation

2022-09-06 08:06 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +//DO NOT CHANGE USE_TRANSACTION value to avoid any DB loss!
Ok, you added the constant declaration, but the comment about this constant is still above the class, not above the constant itself :/

2022-09-06 08:06 UTC, piRGoif commented on test/core/BulkChangeExtKeyTest.inc.php
> +
Ok, it was done in e4eed8d9, closing this conversation

2022-09-06 08:09 UTC, piRGoif commented on webservices/import.php
>  				}
To replace this code, I would create a method in CellChangeSpec and add an override in CellStatus_Issue.
This would give the same behavior, and allows to clearly document the distinct behavior.
Do you think it would break something ?

2022-09-06 13:03 UTC, odain-cbd commented on test/core/BulkChangeExtKeyTest.inc.php
> +//DO NOT CHANGE USE_TRANSACTION value to avoid any DB loss!
ok

2022-09-06 13:04 UTC, odain-cbd commented on core/bulkchange.class.inc.php
> +
ok i will change the typing

2022-09-06 13:12 UTC, odain-cbd commented on webservices/import.php
>  				}
ok good idea

2022-09-07 14:16 UTC, piRGoif commented on webservices/import.php
>  				}
Thanks for the modification :)
Can you just add a phpdoc block on \CellStatus_Issue::GetDisplayableValueAndDescription explaining why we need this override ? Just a little phrase ?

2022-09-13 10:19 UTC, Molkobain requested changes

2022-09-13 10:19 UTC, Molkobain commented on dictionaries/en.dictionary.itop.ui.php
> +	'UI:CSVReport-Value-SetIssue' => 'invalid value for attribute',
```suggestion
	'UI:CSVReport-Value-SetIssue' => 'Invalid value for attribute',
```

_Also needs to be corrected in other languages_

2022-09-13 10:19 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.ui.php
> +	'UI:CSVReport-Value-NoMatch-PossibleValues' => 'Valeur(s) possible(s) pour l\'objet \'%1$s\': %2$s~~',
```suggestion
	'UI:CSVReport-Value-NoMatch-PossibleValues' => 'Valeur(s) possible(s) pour l\'objet \'%1$s\' : %2$s',
```

2022-09-13 10:19 UTC, Molkobain commented on test/webservices/ImportTest.inc.php
> +	const USE_TRANSACTION = false;
Have you talked about this IRL?

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	public function GetDisplayableValueAndDescription() : string
```suggestion
	/**
	 * @since 3.1.0
	 */
	public function GetDisplayableValueAndDescription(): string
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +class RowStatus_Error extends RowStatus
Please write a proper class PHPDoc (Capitals, spaces, `/**`, `@since`)

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	public function __construct($sReason, $sClass=null, $sAllowedValues=null)
```suggestion
	public function __construct($sReason, $sClass = null, $sAllowedValues = null)
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	/** @var string|null $m_sAllowedValues */
`@since` please

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	/** @var string|null $m_sTargetClass */
`@since` please

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	 * @param null $sAllowedValues : used for additional message that provides allowed values $sAllowedValues for current class
String type hint

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
+1

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		//let's search why and give some more feedbackst to the user
```suggestion
		// Current search with current permissions did not match
		// let's search why and give some more feedbacks to the user
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		//count all objects with all permissions
```suggestion
		// Count all objects with all permissions
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		//count all objects with current user permissions
```suggestion
		// Count all objects with current user permissions
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +				$sTargetClass);
```suggestion
			// No objects visible by current user
			$sReason = Dict::Format('UI:CSVReport-Value-NoMatch-NoObject-ForCurrentUser', $sTargetClass);
```

_We don't wrap before 240 in code conventions_

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			$oExtObjectSetWithCurrentUserPermissions->SetLimit(4);
```suggestion
			$aDisplayedAllowedValues = [];
			$sAllowedValues = "";
			$oExtObjectSetWithCurrentUserPermissions->SetLimit(4);
```

Code convention for readability
Missing type hint in the variable name (Careful if you apply this suggestion, you'll have to fix the rest of the file on your own)

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			for($i=0; $i<3; $i++){
```suggestion
			for($i = 0; $i < 3; $i++){
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	 * @param $value : unfound value
Type hint, capitals, `@since`

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			if ($oExtObjectSetWithCurrentUserPermissions->Count()>3){
```suggestion
			if ($oExtObjectSetWithCurrentUserPermissions->Count() > 3){
```

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +				$sTargetClass);
```suggestion
			$sReason = Dict::Format('UI:CSVReport-Value-NoMatch-SomeObjectNotVisibleForCurrentUser', $sTargetClass);
```

No wrap below 240 chars

2022-09-13 10:19 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		//search link for exhaustive values
?

2022-09-13 10:20 UTC, Molkobain commented
_As I agree with many of the points already raised by Pierre I didn't raised them again_

2022-09-13 11:15 UTC, Molkobain requested changes

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	public function GetDisplayableValueAndDescription() : string
```suggestion
	/*
	 * @since 3.1.0
	 */
	public function GetDisplayableValueAndDescription(): string
```

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +	protected $m_sError;
```suggestion
	/** @var string */
	protected $m_sError;
```

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			//search link for exhaustive values
```suggestion
			// Search link for exhaustive values
```

Is this necessary?

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			//no match and some objects NOT visible by current user. including current search maybe...
```suggestion
			// No match and some objects NOT visible by current user. including current search maybe...
```

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +			//search link for exhaustive values
```suggestion
			// Possible values: DD,DD
			// Search link for exhaustive values
```

2022-09-13 11:15 UTC, Molkobain commented on core/bulkchange.class.inc.php
> +		//possible values: DD,DD
```suggestion
		// No match. This is not linked to any right issue
		// Possible values: DD,DD
```

2022-09-13 12:53 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +	protected $m_sError;
Commited separatly

2022-09-13 12:55 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +class RowStatus_Error extends RowStatus
Already done

2022-09-13 12:55 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
Viewed with Olivier : too much effort :/

2022-09-13 12:55 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return Dict::Format('UI:CSVReport-Value-NoMatch-PossibleValues', $this->m_sTargetClass, $this->m_sAllowedValues);
Corrected with Olivier

2022-09-14 07:19 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
Discussed with Olivier : sForeignAttCode contains reconciliation keys (see \BulkChange::$m_aExtKeys phpdoc L302)
Currently we are returning the latest reconciliation key... but there can be multiple ones :/ 
Olivier will had a test case and change its code.

2022-09-14 07:20 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			$oExtObjectSetWithCurrentUserPermissions->SetLimit(4);
Done with Olivier

2022-09-14 07:22 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			IssueLog::Error("failure when fetching few visible objects: " . $e->getMessage());
Done with Olivier

2022-09-14 07:24 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			IssueLog::Error("failure when fetching few visible objects: " . $e->getMessage());
Done with Olivier

2022-09-14 07:26 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +			//__ERRORS__ used by tests only
Discussed with Olivier, would be too hard to document properly :/

2022-09-14 07:26 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +							$sDateExample = $oFormat->Format(new DateTime('2022-10-23 16:17:33'));
Done with Olivier

2022-09-14 07:27 UTC, piRGoif commented on core/bulkchange.class.inc.php
> +								$aResult[$iRow][$iCol] = new CellStatus_Issue(utils::HtmlEntities($sValue), null, $sErrorMsg);
Done with Olivier

2022-09-14 07:28 UTC, piRGoif commented on test/webservices/ImportTest.inc.php
> +		if (is_object($oRestProfile) && is_object($oAdminProfile))
Done with Olivier

2022-09-15 10:17 UTC, odain-cbd commented on core/bulkchange.class.inc.php
> +		return array($oReconFilter->ToOql(), $aKeys, $oExtKey->GetTargetClass(), $sForeignAttCode, $value);
done

2022-09-20 14:00 UTC, merged

2022-09-20 14:15 UTC, piRGoif commented
Well done, thanks Olivier 👏🍾🥳