🐛 Clear session storage on logout
Combodo/iTop pull request #333
Opened 2022-08-26 12:50 UTC by RohacRichard

Hi everyone,

there is existing cleanup of PHP SESSION variable on logout, but session storage with breadcrumb stays there. This makes the session storage stick between logins and more importantly, between users. 

I am logged in as admin, have a breadcrumb of admin operations, then log out. Another user can theoretically go onto my computer and my session, login as user account and see, what I was doing as admin in the breadcrumb. There are of course proper security checks in place, so the user cannot get anywhere he shouldn't get.

This is matter of proper cleanup and very minor security concern, but still valid.

Thanks for consideration,
Richard

2022-08-29 08:13 UTC, Hipska approved these changes
Looks good, although I think they would want it in a `script` or `ready_script` block in the logout.html.twig template, as it would then only be executed when actually logged out and not in the pre-step. (Or maybe just the same command between line 99 and 100)

2022-08-29 13:16 UTC, Molkobain commented
Hello Rohac,

Thanks for the PR! I think we have a internal bug tracked for this, we could hit 2 birds with 1 stone with that PR. @v-dumas do you recall a tracked bug for this?

2022-08-29 21:30 UTC, Molkobain commented
@RohacRichard is this working on your instance? We recently made the logout page redirect to the login page but it was on another part of the application, not the file you changed. See [this commit](https://github.com/Combodo/iTop/commit/1655a377f08efb959a31417f4ca58f7da84c33db)

2022-08-30 05:13 UTC, RohacRichard commented
@Molkobain Hey Guillaume, I am not sure I understand the question. Is the change I commited working on my instance? If so, yes, it is. I tested it multiple times.

If you believe the session storage emptying should occur elsewhere, I can move it, no problem 😊

2022-08-31 13:34 UTC, Molkobain commented
Indeed, the emptying should rather be in [this file](https://github.com/Combodo/iTop/blob/develop/templates/pages/login/logout.html.twig).
Your current fix is working (just tested it) but it might not in the near future as we changed the login/logout mechanism, so moving it to the dedicated file would be great :)

On a side note, you are completely emptying the session storage.
For now it's ok as it only includes data on the breadcrumbs, but if it contains non-user-related data (brought by an extension or the core in the future) it will remove them as well.

Not sure if this is something we should worry about right now, I'll discuss it with the rest of the team.

2022-08-31 13:35 UTC, Molkobain requested changes

2022-08-31 13:35 UTC, Molkobain commented on pages/logoff.php
> +	$oPage->add_script("sessionStorage.clear();");
Move this to [this file](https://github.com/Combodo/iTop/blob/develop/templates/pages/login/logout.html.twig)

2022-09-01 05:18 UTC, RohacRichard commented on pages/logoff.php
> +	$oPage->add_script("sessionStorage.clear();");
Ok, it is done 😊

2022-09-01 05:20 UTC, RohacRichard commented
IMHO if the iTop session ended, both the browser session storage and the PHP session should be cleared. If one wants to persist some data between logins, it's better to use a cookie or browser local storage.

But this is up to Combodo and it's team to decide 😁

2022-09-01 06:42 UTC, Molkobain commented
> [...] it's better to use a cookie or browser local storage.
> 
> [...]

You are totally right!

2022-09-01 06:47 UTC, Molkobain commented on templates/pages/login/logout.html.twig
> +{% endblock %}
```suggestion
{% block script %}
    {{ parent() }}
    
	sessionStorage.clear();
{% endblock %}
```

Just this change to avoid loosing scripts from the parent template and it will be ok for me (you can accept the suggestion directly here, no need to change on you computer)

2022-09-01 06:47 UTC, Molkobain approved these changes

2022-09-01 06:47 UTC, Molkobain commented
All good for me, will be reviewed next week. Thanks!

2022-09-01 08:33 UTC, Hipska approved these changes

2022-09-01 12:22 UTC, piRGoif commented on pages/logoff.php
> +	$oPage->add_script("sessionStorage.clear();");
Closing the conversation as it is now done !

2022-09-06 16:23 UTC, piRGoif commented
Hello,

We discussed this PR during the technical review today.

Do we agree this can only happen if the browser is left open after logout, and iTop is opened in the same context (I mean in a Firefox container sense) ? 
If so can you update your PR description to reflect this condition ?

For us the only security issue would be to see the friendlynames of objects you can't normally see.

It is more a functional question than a technical one (and Guillaume already checked the only technical aspect : where to put the reset), it will be discussed in the functional review next week !

2022-09-07 07:50 UTC, RohacRichard commented
Hi @piRGoif,

I agree and updated the PR description, is this alright with you?

Thank you,
Richard

2022-09-07 13:32 UTC, piRGoif commented
Perfect, many thanks !

2022-09-13 14:30 UTC, Molkobain commented
Accepted in functional review, will be part of the upcoming 3.1.0

2022-09-13 15:15 UTC, merged

2022-09-13 15:18 UTC, Molkobain commented
@RohacRichard is your postal still the same? (So we can you new stickers) Otherwise send me an email :)

2022-09-14 04:51 UTC, RohacRichard commented
@Molkobain Yes, the postal address is still the same :) Can I also get my name on that sweet sweet contributor list? 😁

2022-09-14 08:52 UTC, piRGoif commented
> Can I also get my name on that sweet sweet contributor list? 😁

This is done in 7d1893a2 :)

2022-09-14 08:55 UTC, RohacRichard commented
Awesome, thank you Pierre. Glad I could contribute to iTop 😁

Cheers,
Richard

2022-09-14 20:33 UTC, Molkobain commented
> @Molkobain Yes, the postal address is still the same :) Can I also get my name on that sweet sweet contributor list? 😁

Sorry I thought I already added you with your previous PR!

2022-09-15 05:47 UTC, RohacRichard commented
@Molkobain It's alright, no worries :)