Update wizardsteps.class.inc.php
Combodo/iTop pull request #335
Opened 2022-09-05 13:28 UTC by xtophe38

These changes replace, where it makes sense, the usage of iTop as a product name to the variable ITOP_APPLICATION as it is already done in most of the setup process.

2022-09-05 13:42 UTC, Hipska commented on setup/wizardsteps.class.inc.php
>  				);
There is no added benefit for adding the text in a var before adding in another var.

I would just do this: `$oPage->add($sCronMessage)` or leave it as a single line without the intermediate var.

2022-09-06 07:23 UTC, piRGoif requested changes
Same comment as Hipska :)

2022-09-12 08:30 UTC, Molkobain commented on setup/wizardsteps.class.inc.php
> +                $sCronMessage = '<div class="message">An '.ITOP_APPLICATION.' cron process is being executed on the target database. '.ITOP_APPLICATION.' cron process will be stopped during the setup
It's a bit sad to rollback from a clear HEREDOC to a PHP concatenated string, I would rather keep the HEREDOC.

2022-09-12 08:45 UTC, Hipska commented on setup/wizardsteps.class.inc.php
> +                $sCronMessage = '<div class="message">An '.ITOP_APPLICATION.' cron process is being executed on the target database. '.ITOP_APPLICATION.' cron process will be stopped during the setup
@Molkobain How to add a STATIC inside a HEREDOC?

2022-09-13 07:53 UTC, piRGoif commented
@xtophe38 can you do the asked changes ?

2022-09-13 08:31 UTC, Hipska approved these changes

2022-09-13 08:32 UTC, piRGoif approved these changes

2022-09-13 08:32 UTC, piRGoif commented on setup/wizardsteps.class.inc.php
> +                $sCronMessage = '<div class="message">An '.ITOP_APPLICATION.' cron process is being executed on the target database. '.ITOP_APPLICATION.' cron process will be stopped during the setup
Discussed with @xtophe38 directly : the constant cannot remain in heredoc, so we choose to adopt Hipska suggestion.
Closing the conversation

2022-09-13 08:33 UTC, piRGoif commented on setup/wizardsteps.class.inc.php
>  				);
That what was done in the last commit :) 
Closing conversation.

2022-09-13 08:34 UTC, Hipska approved these changes
@piRGoif I already reviewed and approved 😉

2022-09-13 08:37 UTC, piRGoif commented
> @piRGoif I already reviewed and approved 😉

Wooops sorry !
Thanks for the review !

2022-09-13 09:07 UTC, Molkobain approved these changes

2022-09-13 14:42 UTC, Molkobain commented
Accepted in functional review, will be part of the upcoming 2.7.8 / 3.1.0

2022-09-13 14:43 UTC, Molkobain commented on setup/wizardsteps.class.inc.php
> +				$oPage->add('<div class="message">An '.ITOP_APPLICATION.' cron process is being executed on the target database. '.ITOP_APPLICATION.' cron process will be stopped during the setup execution.</div
```suggestion
				$oPage->add('<div class="message">'.ITOP_APPLICATION.' cron process is being executed on the target database. '.ITOP_APPLICATION.' cron process will be stopped during the setup execution.</div>');
```

2022-09-13 15:09 UTC, Molkobain commented
@xtophe38 next steps are:
  * Create a ticket in our bug tracker
  * Add ticket number in the PR title (`N°XXXX - Setup wizard : use the ITOP_APPLICATION constant instead of hardcoded "iTop" string`)
  * Merge PR using "Squash & merge" as there are several commits and it's not relevant to keep them separated
  * Merge support/2.7 into support/3.0 into develop
  * Resolved ticket as usual

Feel free to come to us for a copilot 👨‍✈️

2022-09-13 18:11 UTC, merged