N°5758 GDPR consent : apply to all instances containing the Hub connector
Combodo/iTop pull request #336
Opened 2022-09-05 13:42 UTC by xtophe38

Up to now,  we define that RGPD consent is required if iTop is not an "iTop Product". This is, I think, too restrictive as other products based on iTop (TeemIp std alone today and ESM products tomorrow) may not require RGPD consent even if they are not "iTop Products". Since instance data are collected through iTop Hub only, I suggest to base the test of RGPD consent requirement on the fact that iTop Hub Connector extension is installed.

2022-09-05 13:45 UTC, Hipska commented
I also think the ITSM connectors also require this consent.

PS, the correct English term is GDPR.

2022-09-06 07:16 UTC, piRGoif requested changes
I like your suggestion !
Just a little change request : you should create a SetupUtils method, as what was done with IsProductVersion. To test for the presence of the Hub Connector, maybe call it IsItopHubInstance ?

2022-09-06 07:19 UTC, piRGoif commented
> I also think the ITSM connectors also require this consent.

For now it isn't. I suppose it is because if you have a package including the ITSM Designer Connector then you have a contract with Combodo or one of its partner ? 

@dcoille can you confirm ?

2022-09-12 08:26 UTC, Molkobain commented
> I like your suggestion ! Just a little change request : you should create a SetupUtils method, as what was done with IsProductVersion. To test for the presence of the Hub Connector, maybe call it IsItopHubInstance ?

Like Pierre I would rather have the test using a detection method than an "hard-coded" test, so we can factorize this kind of detections.

2022-09-12 15:18 UTC, xtophe38 commented
Factorization done as required.

2022-09-13 07:33 UTC, piRGoif approved these changes
Thanks, perfect now !

2022-09-13 07:37 UTC, Hipska commented
For a private function, it is perfectly doable to do a refactoring to correct english naming:
```php
	private function NeedsGdprConsent()
```

2022-09-13 07:42 UTC, piRGoif commented
> For a private function, it is perfectly doable to do a refactoring to correct english naming:
> 
> ```
> 	private function NeedsGdprConsent()
> ```

Yeah, we should do that, but it won't be mandatory for this PR to be accepted.
I'll do the rename :)

2022-09-13 07:44 UTC, Hipska commented
Sure, it can be accepted as is indeed. I was just mentioning as it could be done in this PR as well, no need for a separate PR.

Or, indeed, just do it directly on the branch without PR, that works as well 😄

2022-09-13 07:46 UTC, piRGoif commented
I've done the rename directly in this PR branch as it will lower the possible conflicts :)

2022-09-13 07:48 UTC, Hipska approved these changes

2022-09-13 09:04 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +	public static function IsItopHubInstance($aModules)
_Reminder:
  * Add `@since` once version is chosen
  * Discuss about the function name during technical review as "IsItopHubInstance", to me it means that "this is an iTop Hub instance" (which is not possible) rather than "this iTop instance connects to iTop Hub"_

2022-09-13 14:56 UTC, Molkobain commented
Ok pour 2.7.8 si on a une implé tres safe, sinon 3.0.3. Implé technique a terminer à la R&D
Repondre a Thomas sur le contrat.

Functional review: R&D still to do some checks but it is accepted. If chosen implementation is very safe plan for 2.7.8, otherwise 3.0.3

2022-09-20 08:39 UTC, piRGoif commented
Rebased (there were conflicts due to #335) and forced pushed !

2022-09-20 08:40 UTC, piRGoif commented on setup/wizardsteps.class.inc.php
> +	private function NeedsGdprConsent()
We'll need a `@since` here also so that the method rename would be documented !

2022-11-02 15:29 UTC, Molkobain requested changes

2022-11-02 15:29 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +	public static function IsItopHubInstance($aModules)
Discussed during technical review, still waiting for a better function name, eg. `IsConnectableToITopHub()`.
Once changed, PR will be technically accepted  @xtophe38

2022-11-02 15:30 UTC, Molkobain commented
_Moved to functional review to avoid loosing another month while function is renamed_

2022-11-08 10:07 UTC, Molkobain commented
@xtophe38 once method changed, it's ok to merge

2022-11-29 17:52 UTC, piRGoif commented
Rebased & force pushed

2022-11-29 17:57 UTC, piRGoif commented on setup/wizardsteps.class.inc.php
> +	private function NeedsGdprConsent()
Done !

2022-11-29 17:58 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +	public static function IsItopHubInstance($aModules)
Renaming done !

2022-11-29 18:00 UTC, merged