Issue/5073
Combodo/iTop pull request #337
Opened 2022-09-14 07:41 UTC by bdalsass

Below is a sample of extra param to enable feature:

		$aExtraParams['row_actions'] = [
			[
				'tooltip'        => 'add an element',
				'icon_css_class' => 'fa-plus',
				'css_class'      => 'ibo-is-success',
				'level'          => 'secondary',
				'on_action_js'   => 'console.log(aData);',
			],
			[
				'tooltip'        => 'remove an element',
				'icon_css_class' => 'fa-minus',
				'css_class'      => 'ibo-is-danger',
				'level'          => 'secondary',
				'on_action_js'   => 'console.log("You clicked the remove button");',
			],
			[
				'tooltip'        => 'open in new tab',
				'icon_css_class' => 'fa-external-link-square-alt',
				'on_action_js'   => 'window.open("http://localhost/itop-branchs/dev/pages/UI.php?operation=details&class=UserRequest&id=" + aData.id + "&c[menu]=UserRequest%3AOpenRequests");',
			],
			[
				'tooltip'        => 'other actions',
				'icon_css_class' => 'fa-ellipsis-v',
				'on_action_js'   => 'console.log(event);',
			],
		];

2022-09-15 10:22 UTC, Hipska commented
Do you have a screenshot of such an action in action?

2022-09-15 12:15 UTC, bdalsass commented
> 

<img width="1273" alt="2022-09-15_14h11_50" src="https://user-images.githubusercontent.com/95754414/190401044-cda0778b-8085-467b-90a0-d0f6df95d4fe.png">

2022-09-22 15:02 UTC, Molkobain submitted a review, later dismissed

2022-09-22 15:02 UTC, Molkobain commented on js/dataTables.main.js
> +	if(iColumnTargetIndex != -1){
```suggestion
	if (iColumnTargetIndex !== -1) {
```

We rather have strict type comparisons unless it is known that the data type can vary (eg. can be either `'1'` or `1` depending on the consumer).
This avoid future regression like the one we had on _template-base_ for instance.

2022-09-22 15:02 UTC, Molkobain commented on js/dataTables.main.js
> + * @returns {*}
```suggestion
 * @returns {*}
 * @since 3.1.0
```

2022-09-22 15:02 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +	public static function MakeActionRowToolbarTemplate($oTable)
If I understand correctly, `$oTable` will be a `UIBlock` using the `tTableRowActions` trait right?

We can't type hint the argument with the trait, nor can we type hint with a union of the table classes as it is only supported by PHP 8.0+.

Maybe we can type hint with a `\Combodo\iTop\Application\UI\Base\iUIBlock` at least and explicit in the PHPDoc that the object needs to use the said trait. What do you think?

2022-09-22 15:02 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/StaticTable/FormTable/FormTable.php
> +
You don't need this as the trait is already inherited from `StaticTable`

2022-09-22 15:02 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/StaticTable/StaticTable.php
> +	 * @return int
```suggestion
	 * @return int
	 * @since 3.1.0
```

2022-09-22 15:02 UTC, Molkobain commented on sources/Application/UI/Base/Component/Template/Template.php
> +	use tUIContentAreas;
If your `Template` UIBlock is very simple and only have 1 area where sub blocks will be added, you don't need the whole `tUIContentAreas` trait overhead, it can be removed. You'll just have to use the AddSubBlock / GetSubBlocks methods.

2022-09-22 15:02 UTC, Molkobain commented on templates/base/components/datatable/row-actions/handler.js.twig
> +            let aData = $('#{{ oUIBlock.GetId() }}').DataTable().row(oTrElement).data();
```suggestion
            let aData = oDatatable.row(oTrElement).data();
```

2022-09-23 07:13 UTC, bdalsass commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +	public static function MakeActionRowToolbarTemplate($oTable)
👍I update the code

2022-09-23 10:00 UTC, Molkobain requested changes
_PS: If you want to apply several suggestion at once you can "add them to batch", then apply them._

2022-09-23 10:00 UTC, Molkobain commented on js/dataTables.main.js
> + * @since 3.1.0
```suggestion
 * @since 3.1.0
```

2022-09-23 10:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +		if (!Utils::IsClassUsesDeepTrait($sTableClass, tTableRowActions::class)) {
```suggestion
		if (!utils::IsClassUsesDeepTrait($sTableClass, tTableRowActions::class)) {
```

The `Utils` class with a capital "U" is not the class from iTop core, it's from another collector or extension. It might work but it can be misleading when doing "grep" on the codebase.

2022-09-23 10:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +			/** array of blocks displayed on every row */
Is that change on purpose? Seems less readable to me (but it would be fine)

2022-09-23 10:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/StaticTable/StaticTable.php
> +	 * @since 3.1.0
```suggestion
	 * @return int
	 * @since 3.1.0
```

2022-09-23 10:00 UTC, Molkobain commented on application/utils.inc.php
> +  }
```suggestion
	/**
	 * Return traits array used by a class and by parent classes hierarchy.
	 *
	 * @see https://www.php.net/manual/en/function.class-uses.php#110752
	 *
	 * @param string $sClass Class to scan
	 * @param bool $bAutoload Autoload flag
	 *
	 * @return array traits used
	 * @since 3.1.0
	 */
	public static function ClassUsesDeep(string $sClass, bool $bAutoload = true): array
	{
		$aTraits = [];
		do {
			$aTraits = array_merge(class_uses($sClass, $bAutoload), $aTraits);
		} while ($sClass = get_parent_class($sClass));
		foreach ($aTraits as $sTrait => $same) {
			$aTraits = array_merge(class_uses($sTrait, $bAutoload), $aTraits);
		}

		return array_unique($aTraits);
	}

	/**
	 * Test trait usage by a class or by parent classes hierarchy.
	 *
	 * @param string $sClass Class to check
	 * @param string $sTrait Trait to search for
	 *
	 * @return bool
	 * @since 3.1.0
	 */
	public static function IsClassUsesDeepTrait(string $sClass, string $sTrait): bool
	{
		return in_array($sTrait, self::ClassUsesDeep($sClass, true));
  }
```

2022-09-23 10:00 UTC, Molkobain commented on application/utils.inc.php
> +	public static function ClassUsesDeep(string $class, bool $autoload = true): array
The method name is not very intuitive (to me at least) as it does not mention that it will only return traits.
What about:
  * (Enum|List)ClassTraits
  * (Enum|List)TraitsUsedByClass

2022-09-23 10:00 UTC, Molkobain commented on application/utils.inc.php
> +	public static function IsClassUsesDeepTrait(string $class, string $trait): bool
More understandable (still for my PoV at least), that being said do you think something like "IsClassUsingTrait" would be more understandable or am I the only that it bothers? 😁

2022-09-23 14:54 UTC, bdalsass commented on application/utils.inc.php
> +	public static function ClassUsesDeep(string $class, bool $autoload = true): array
done

2022-09-23 14:54 UTC, bdalsass commented on application/utils.inc.php
> +	public static function IsClassUsesDeepTrait(string $class, string $trait): bool
done with IsTraitUsedByClass

2022-09-23 16:38 UTC, Molkobain commented on application/cmdbabstract.class.inc.php
> +		];
Is this for debug purposes?

- Tooltip should be a dict entry and start with a capitalized letter
- JS console outputs should be removed

2022-09-23 16:38 UTC, Molkobain approved these changes

2022-09-25 08:32 UTC, steffunky approved these changes

2022-09-26 06:09 UTC, bdalsass commented on application/cmdbabstract.class.inc.php
> +		];
yes, unwanted commit.
I remove it before merging branch.

2022-09-26 06:20 UTC, merged