N°5588 Improve PDFExport robustness when AttributeImage size cannot be determined
Combodo/iTop pull request #350
Opened 2022-10-07 07:44 UTC by piRGoif

Avoid errors like : 

```
2022-10-07 01:27:33 | Error   | 1     | Uncaught DivisionByZeroError: Division by zero in /var/www/html/iTop/core/pdfbulkexport.class.inc.php:232
Stack trace:
#0 /var/www/html/iTop/core/htmlbulkexport.class.inc.php(68): PDFBulkExport->GetValue(Object(Person), 'picture')
#1 /var/www/html/iTop/core/tabularbulkexport.class.inc.php(297): HTMLBulkExport->GetSampleData(Object(Person), 'picture')
#2 /var/www/html/iTop/core/htmlbulkexport.class.inc.php(49): TabularBulkExport->GetInteractiveFieldsWidget(Object(AjaxPage), 'interactive_fie...')
#3 /var/www/html/iTop/core/pdfbulkexport.class.inc.php(117): HTMLBulkExport->GetFormPart(Object(AjaxPage), 'interactive_fie...')
#4 /var/www/html/iTop/webservices/export-v2.php(318): PDFBulkExport->GetFormPart(Object(AjaxPage), 'interactive_fie...')
#5 /var/www/html/iTop/webservices/export-v2.php(423): DisplayForm(Object(AjaxPage), 'http://webserve...', 'SELECT `Person`...', NULL, 'pdf')
#6 /var/www/html/iTop/webservices/export-v2.php(689): InteractiveShell('SELECT `Person`...', NULL, 'pdf', '', 'dialog')
#7 {main}
  thrown | IssueLog |||
array (
  'type' => 1,
  'file' => '/var/www/html/iTop/core/pdfbulkexport.class.inc.php',
  'line' => 232,
)
```

2022-10-20 07:58 UTC, piRGoif commented on core/pdfbulkexport.class.inc.php
> +							if (($iWidth === 0) && ($iHeight === 0)) {
|| instead of && !

2022-11-03 08:50 UTC, Molkobain requested changes

2022-11-03 08:50 UTC, Molkobain commented on core/pdfbulkexport.class.inc.php
> +							if (($iWidth === 0) && ($iHeight === 0)) {
```suggestion
							if (($iWidth === 0) || ($iHeight === 0)) {
```

2022-11-03 08:50 UTC, Molkobain commented on core/pdfbulkexport.class.inc.php
> +								// avoid division by zero exception :/
```suggestion
								// Avoid division by zero exception (SVGs, corrupted images, ...)
```

2022-11-03 08:50 UTC, Molkobain commented on core/pdfbulkexport.class.inc.php
> +								IssueLog::Warning('AttributeImage : cannot read image size', LogChannels::EXPORT, [
```suggestion
								IssueLog::Warning('AttributeImage: Cannot read image size', LogChannels::EXPORT, [
```

Shouldn't this be an error instead of a warning?

2022-11-03 08:51 UTC, Molkobain commented
_As a reminder that was the cause of CI tests failures due to a backup with corrupted images_

2022-11-07 15:05 UTC, piRGoif commented on core/pdfbulkexport.class.inc.php
> +								IssueLog::Warning('AttributeImage : cannot read image size', LogChannels::EXPORT, [
Thanks ! About the log level, it won't be an error for svg files for example, and it shouldn't be blocking...
Kept the discussion opened so that it can be discussed on next review !

2022-11-07 15:07 UTC, piRGoif commented on core/pdfbulkexport.class.inc.php
> +							if (($iWidth === 0) && ($iHeight === 0)) {
Done in b09b665, thanks Molkobain !

2022-12-06 12:09 UTC, Molkobain commented
You'll have to rebase this branch as the other PR on PDF export has been merged.

2022-12-06 12:34 UTC, piRGoif commented
Thanks for pointing that out, I didn't saw there was a conflict...
The modified code was extracted in a new method... No way to rebase easily :(
Too sad, I will certainly miss the review... again :(

2022-12-06 12:44 UTC, piRGoif commented
Rebase / force push done (wasn't easy :~( )

2022-12-06 13:08 UTC, Molkobain approved these changes

2022-12-06 16:23 UTC, Molkobain commented
Accepted during technical review.

2022-12-13 16:44 UTC, Molkobain commented
Accepted during functional review. Will be part of the upcoming 2.7.9.
@piRGoif will add a reproduction procedure in bug (providing faulty images if possible)

2022-12-13 17:44 UTC, piRGoif commented
The branch isn't working anymore :(
I'm looking on why (certainly errors made during rebase...)

2022-12-13 17:58 UTC, piRGoif commented
Fixed the branch, and rebased on support/2.7 (yeah, no conflicts !)

But as I added a param to the \PDFBulkExport::GetAttributeImageValue for logging purpose only I'm setting this PR to be reviewed again on next technical review. What do you think @Molkobain ?

The Combodo ticket was updated with more info (how to reproduce + new log)

2022-12-14 14:39 UTC, Molkobain requested changes

2022-12-14 14:39 UTC, Molkobain commented on core/log.class.inc.php
> +	 * @since 2.7.8
```suggestion
	 * @since 2.7.9
```

2022-12-14 14:39 UTC, Molkobain commented on core/pdfbulkexport.class.inc.php
> +	protected function GetAttributeImageValue(DBObject $oObj, AttributeImage $oAttDef, ormDocument $oValue, string $sOutputType)
```suggestion
	protected function GetAttributeImageValue(DBObject $oObj, string $sAttCode, string $sOutputType)
```

If we have to pass the whole object, then passing the att. def. and the value makes no sense anymore. We should only pass the object and the att. code IMO.

_Mind to update the PHPDoc and the consumers as well_

2022-12-20 10:17 UTC, piRGoif commented on core/pdfbulkexport.class.inc.php
> +	protected function GetAttributeImageValue(DBObject $oObj, AttributeImage $oAttDef, ormDocument $oValue, string $sOutputType)
Updated the signature with 06259546
Indeed getting again attdef and value shouldn't be that bad as everything is in memory.
Consumers were already updated on last modification, I did it also for this modification.

2022-12-20 15:16 UTC, Molkobain approved these changes

2023-02-13 13:45 UTC, Molkobain commented
Accepted during technical review.

2023-02-14 15:59 UTC, Molkobain commented
Accepted during functional review.
@piRGoif will ensure that the corresponding ticket is marked to retrofit in 2.7.9 / 3.0.3 / 3.1.0

2023-02-23 10:45 UTC, merged