Do not verify ca in mysqldump if not configured
Combodo/iTop pull request #354
Opened 2022-10-14 14:36 UTC by larhip

### Symptom

Using mysql-client (not MariaDB) during the backup the CA is always verified even if no CA Path is configured.

_Current behavior_
<img width="718" alt="image" src="https://user-images.githubusercontent.com/24569763/195871316-4ec5abd1-a6b7-436d-ab7f-29d33ee2e61f.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/24569763/195870977-9d2a9d40-7572-4b35-a38a-8ffec56caa54.png">

_ Expected behavior_
Backup should be successful using mysql client and ssl without configured ca

### Reproduction

- Setup iTop (3.0 or 2.7) with separate web and database host
- Install mysql-client (not mariadb) on web server
- Add the config setting `'db_tls.enabled' => true`
- Do _not_ add `db_tls.ca` or leave it empty

### Cause

iTop adds the mysql option `--ssl-mode=VERIFY_CA` in case of mysql and tls enabled, but do not check whether ca is configured.
If no ca path is configured it should be `--ssl-mode=REQUIRED` instead of `VERIFY_CA`.

2022-10-14 15:13 UTC, Hipska approved these changes

2022-10-17 08:06 UTC, piRGoif requested changes
Good catch, thanks ! 

Just a note : this method (\DBBackup::GetMysqldumpCommand) is called from the setup as from the manual backup or the scheduled one.

Can you change accordingly the corresponding test ? 
It is in `test/setup/DBBackupTest.php`
If you feel uncomfortable doing it, just tell me I can do it (if you check the "[Allow edits from maintainers](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" option)

Also the doc url might be changed to the 5.7 version : it contains the `--ssl_mode` parameter values, whereas the current 5.6 link doesn't show them
https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode

2022-10-17 08:07 UTC, piRGoif commented
Also this is a good candidate to be merged in the support/2.7 branch, but we'll have to wait the functional review to discuss this.

2022-10-17 11:36 UTC, larhip commented
HI @piRGoif 

> Can you change accordingly the corresponding test ? It is in `test/setup/DBBackupTest.php`
I already checked the test cases previously, but since the test did just check whether the options starts with `--ssl` I did not see a need for a change. Anyhow I changed the comment in the test now.
I have no idea how to implement a test which will check it more in detail, since the current implementation is not able to mock the database client, is it?

> If you feel uncomfortable doing it, just tell me I can do it (if you check the "[Allow edits from maintainers](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" option)
I tried to allow you as maintainer, but unfortunate I was not aber to find the corresponding checkbox :-(
![image](https://user-images.githubusercontent.com/24569763/196166324-63d7f4c7-6546-4e10-b531-f0e94b81c608.png)

> Also the doc url might be changed to the 5.7 version : it contains the `--ssl_mode` parameter values, whereas the current 5.6 link doesn't show them https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode
I changed the link from 5.6 to 5.7 but thought it would be better to set the anchor to the top chapter (encrypted-connection-options) since the depreciation info of `--ssl` is not the the chapter you mentioned.

2022-11-03 08:42 UTC, Molkobain approved these changes

2022-11-03 08:45 UTC, Molkobain commented
@larhip the test cases can be update to check that the right `--ssl-mode` option is passed, I think that would suffice. Once done, the PR will be mature enough for me.

2022-11-03 08:55 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Also, since iTop 3.x only supports MySQL 5.7+ the version check can be removed and this part should always be executed?

2022-11-03 08:57 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Oh wait, does MariaDB still use `--ssl`? In that case, it can be this:
```suggestion
		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
```

2022-11-03 08:59 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Another note on this: It's perfectly possible to have a DB server with MySQL and the `mysqldump` tool from MariaDB and vice versa, so be careful with these checks.

2022-11-03 09:00 UTC, Molkobain commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
> Also, since iTop 3.x only [supports](https://www.itophub.io/wiki/page?id=3_0_0:install:requirements) MySQL 5.7+ the version check can be removed and this part should always be executed?

Depends if we manage to make this merged in the `support/2.7` branch 🤞

2022-11-03 09:08 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Currently it is targeted at `develop`, which means iTop 3.1
My other point still counts..

2022-11-03 09:40 UTC, Molkobain commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
> Currently it is targeted at develop, which means iTop 3.1

> Also this is a good candidate to be merged in the support/2.7 branch, but we'll have to wait the functional review to discuss this.

2022-11-03 09:41 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Correct, but my other point still stands..

2022-11-03 11:41 UTC, larhip commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Damn you are right @Hipska `CMDBSource::GetDBVendor` will check the server version / vendor not the client, missed that :-(

I'll try to find a way to check the client version and come back as soon as I got a solution..

2022-11-03 12:18 UTC, larhip commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
OK I checked it.
Looks like the only other way to figure out the client version, would be by executing `mysqldump --version`
So it might be possible to do something like this:
```
$sMySQLDump = $this->GetMysqldumpCommand() . " --version";
exec($sCommand, $aOutput, $iRetCode);
```
and use a RegEx to get the vendor and the version from the output (not sure how is is such a RegEx since the version string ist not really standardized).

I am really not sure how "stable" such an implementation is...
It does feel a little bit "dirty" to grep for the version in the output of an exec command, doesn't it?

Anyhow the change would be bigger that originally planned from my side..

Another way would be the add a warning in the documentation, that it would be recommended to use that same mysql client and server version in case of an TLS encryption (in fact this warning is true for the current code without this PR as well, since currently you are already using the server version to check which client options to be set). But for sure a comment in the documentation will not address the real technical issue..

What do you think @Molkobain @Hipska ?

2022-11-03 12:23 UTC, larhip commented
> @larhip the test cases can be update to check that the right `--ssl-mode` option is passed, I think that would suffice. Once done, the PR will be mature enough for me.

@Molkobain I tried to update the test case to check for the right `--ssl-mode`. Would you mind to review those changes?

2022-11-03 12:30 UTC, Hipska commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
IMO as said before, only a check if it is MySQL or MariaDB should be enough. (then it is not possible to backport to 2.7)

2022-11-03 13:04 UTC, larhip commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
It that case the problem regarding the usage of DB server with MySQL and the mysqldump tool from MariaDB (and vice versa) will still exist an a brief note in the documentation would make sense anyhow, wouldn't it?

Reading to backport or not, I do not have a strong opinion, so up to the Combodo as the maintainer :-)

2022-11-03 13:46 UTC, Molkobain commented on test/setup/DBBackupTest.php
> +		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
This is duplicated 3 times (2 in unit tests, 1 in the business logic), I would rather have it extracted in a dedicated (both version and condition) method to avoid changes in the business logic to make the tests diverge from reality.

2022-11-03 14:47 UTC, Molkobain commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
To me it depends how much we want to backport this fix to the `support/2.7`.

It would be great to do it, but if we are not sure on how to detect the vendor (uncertain RegEx), then I'll rather just fix this in the `support/3.0` to ensure stability.
Also as this is the first time this issue is reported, it might not be some frequent, so the need to backport it is not that big to me.

So long story short I'll go the Hipska way.

2022-11-03 15:11 UTC, larhip commented on setup/backup.class.inc.php
>  		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Fine for me, I've already updated the code ✅

2022-11-03 15:14 UTC, larhip commented on test/setup/DBBackupTest.php
> +		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
This should be obsolete since there will be no backport to 2.7 :-)

2022-11-03 16:04 UTC, Molkobain reviewed
_All in comments_

2022-11-03 16:16 UTC, Molkobain approved these changes

2022-11-03 16:17 UTC, Molkobain commented
All good to me, thank you both 🙌

2022-11-03 16:27 UTC, Hipska commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith('--ssl-mode=REQUIRED', $sCliArgsMinCfg);
Does this assert pass? As the string should start with a space.

2022-11-03 16:28 UTC, Hipska approved these changes

2022-11-03 21:07 UTC, Molkobain commented on test/setup/DBBackupTest.php
> +		if ($sDBVendor === CMDBSource::ENUM_DB_VENDOR_MYSQL && version_compare($sDBVersion, $sMysqlSSLModeVersion, '>='))
Indeed, I wrote all comments at once. It can be discarded :)

2022-11-03 21:18 UTC, Molkobain commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith('--ssl-mode=REQUIRED', $sCliArgsMinCfg);
+1

2022-11-04 07:34 UTC, larhip commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith('--ssl-mode=REQUIRED', $sCliArgsMinCfg);
Shame on me :-(
I did not run the tests again, since they are not platform independent and on my MySQL-Test-Env I got no phpunit and no composer and I would like to save that time, my fault :-(

Anyhow it's no fixed and the tests pass.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/24569763/199917763-6d432c7a-8b9a-4580-acec-58c691a4000f.png">

Thanks for your watchful eye @Hipska

2022-11-07 08:53 UTC, Hipska requested changes

2022-11-07 08:53 UTC, Hipska commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith(' --ssl', $sCliArgsCapathCfg);
This test also succeeds when the string is ` --ssl-mode=VERIFY_CA`.

2022-11-07 08:53 UTC, Hipska commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith(' --ssl', $sCliArgsMinCfg);
This test also passes when the string is ` --ssl-mode=REQUIRED`

2022-11-07 15:37 UTC, piRGoif requested changes

2022-11-07 15:37 UTC, piRGoif commented on setup/backup.class.inc.php
> +	 * @link https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options "Command Options for Encrypted Connections"
Thanks for the change !
You can remove the quotes around the title, see https://docs.phpdoc.org/guide/references/phpdoc/tags/link.html#link

```suggestion
	 * @link https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options Command Options for Encrypted Connections
```

I didn't get what you were saying in your comment ? 

> I thought it would be better to set the anchor to the top chapter (encrypted-connection-options) since the depreciation info of --ssl is not the the chapter you mentioned.

The old and the new URL are pointing to the same `encrypted-connection-options` anchor ? And in the 5.6 URL there is the `--ssl` parameter documented ?

2022-11-07 15:37 UTC, piRGoif commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Why removing the version_compare call ? Because MySQL min version is 5.7.0 ? (N°2330 in iTop 3.0.0)
I would keep it anyway so that the code snippet won't rely on any assertions other that testing the real thing (and plus it could cause a bug if we decide to rebase on support/2.7 !)

2022-11-07 15:37 UTC, piRGoif commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith(' --ssl', $sCliArgsMinCfg);
You're right ! 
Maybe add a test to confirm that the string doesn't start with `--ssl-mode=` ?

2022-11-07 15:54 UTC, Hipska commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Do we know if `--ssl-mode` isn't supported on MySQL 5.7?

2022-11-07 16:08 UTC, piRGoif commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Well I digged in a little more

In the [param documentation for MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode) it is said : 

> The [--ssl-mode](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode) option was added in MySQL 5.7.11.

And on [the --ssl doc](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl) : 

> The client-side [--ssl](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl) option is deprecated as of MySQL 5.7.11 and is removed in MySQL 8.0

So indeed the previous test wasn't correct and should be fixed...
To my understanding : 
* `--ssl` should be returned for MySQL if version < 5.7.11, or for MariaDB (?)
* And `--ssl-mode` must be returned for MySQL >= 5.7.11.

2022-11-07 20:15 UTC, larhip commented on setup/backup.class.inc.php
> +	 * @link https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options "Command Options for Encrypted Connections"
> You can remove the quotes around the title
Will do that 👍 

> I didn't get what you were saying in your comment ?

OK now I am not sure whether I got what you are saying 😀 
In your comment at the top you suggested to change the link to 5.7 (instead of 5.6). But you suggested a link to the sub-chapter for the `--ssl-mode`-option 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/24569763/200405550-2cf72713-dd12-407a-8148-e96146f30d49.png">

Since the option `--ssl-mode` would be only used for mysql >= 5.7.11 and vor older versions `--ssl` IMHO it would make more sense to link to the top chapter (encrypted-connection-options) which includes the description von the sub chapter for `--ssl` and `--ssl-mode`

Does my explanation make sense to you or do you prefer the link to the `--ssl-mode`-sub chapter?

2022-11-07 20:22 UTC, larhip commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
So ok, I will
  * Add the version compare again (using version 5.7.11 as "break point")
    * `--ssl` for MariaDB and MySQL version < 5.7.11
    * `--ssl-mode` for MySQL version >= 5.7.11
  * Change the test cases as well (keeping the comment of @Molkobain in mind regarding extracting it in a method and add an assertion in case it should not be `--ssl-mode`)

Did I forgot anything?

2022-11-08 08:06 UTC, piRGoif commented on setup/backup.class.inc.php
> +	 * @link https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options "Command Options for Encrypted Connections"
Oh yeah sorry :D

Totally agree to link to https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options ("Command Options for Encrypted Connections" chapter)  !
Instead of https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode (--ssl_mode param) I suggested earlier, which is indeed a bad idea !

Sorry for the confusion, thanks for the clarification :)

2022-11-10 09:31 UTC, piRGoif commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Seems all good to me, many thanks !

2022-11-21 14:56 UTC, larhip commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Sorry for the delay!

So ok that should be done now, so what I did:
  * Add a new method in `CMDBSource` to check which ssl option to be used
    * Do check vendor and version within this method
  * Using this method in `DBBackup::GetMysqlCliTlsOptions`
  * Change the Test cases as well

Could you please check again? :)

2022-12-06 14:47 UTC, piRGoif approved these changes

2022-12-06 14:57 UTC, piRGoif commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith('--ssl-mode=REQUIRED', $sCliArgsMinCfg);
Problem solved, closing conversation

2022-12-06 14:58 UTC, piRGoif commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith(' --ssl', $sCliArgsCapathCfg);
Problem solved, closing conversation

2022-12-06 14:58 UTC, piRGoif commented on test/setup/DBBackupTest.php
> +			$this->assertStringStartsWith(' --ssl', $sCliArgsMinCfg);
Problem solved, closing conversation

2022-12-06 14:58 UTC, piRGoif commented on setup/backup.class.inc.php
> +	 * @link https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options "Command Options for Encrypted Connections"
Problem solved, closing conversation

2022-12-06 14:59 UTC, piRGoif commented on setup/backup.class.inc.php
> +		if (CMDBSource::GetDBVendor() === CMDBSource::ENUM_DB_VENDOR_MYSQL)
Modification done, closing conversation

2022-12-06 15:19 UTC, Hipska approved these changes

2022-12-06 16:05 UTC, Molkobain commented
Accepted during technical review

2022-12-13 17:04 UTC, Molkobain commented
Accepted during functional review.
@larhip did you test the patch on your customer's env?

2022-12-14 08:03 UTC, larhip commented
Yes we did test on customer's env, but just an early version of this patch (like it was in the initial PR)
I could test the final version beginning of January in this env.

2022-12-14 09:18 UTC, piRGoif commented
Hello,

> I could test the final version beginning of January in this env.

Ok thanks, will wait for your feedback (as an extra precaution) before merging.

2023-01-10 10:45 UTC, larhip commented
Hi @piRGoif 
we just tested it on test env of customer and the patch works fine.

Cheers
Lars

2023-01-10 11:12 UTC, piRGoif commented
Thanks Lars ! 
Marging !

2023-01-10 11:13 UTC, merged