N°4494 - Log save and transition fails
Combodo/iTop pull request #358
Opened 2022-11-04 16:49 UTC by accognet

It may be better fixes with more code changes. This one works for a quick fix.

2023-08-08 11:44 UTC, Molkobain requested changes
The analysis of the root cause is good, sometimes the redirection to the transition form is done before the XHR to release the lock is complete.

That being said, we should rather use a promise to solve this than using a `setInterval`

2023-08-09 06:54 UTC, Molkobain requested changes

2023-08-09 06:54 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +			action_promise: null,
```suggestion
			action_promise: null,	// N°4494 - Promise used to do the action (following the log entry send) only once the lock is released
```

2023-08-09 06:54 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +										//todo
```suggestion
										// We do nothing in case of failure for now
```

2023-08-09 06:54 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +							me.element.find(me.js_selectors.caselog_entry_form).trigger('clear_entry.caselog_entry_form.itop');
It's no longer necessary to move this right? So we can just revert these lines and 994-997.

2023-08-09 06:54 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +							if (me.action_promise != null) {
```suggestion
							if (me.action_promise !== null) {
```

2023-08-09 08:17 UTC, accognet commented on js/layouts/activity-panel/activity-panel.js
> +							me.element.find(me.js_selectors.caselog_entry_form).trigger('clear_entry.caselog_entry_form.itop');
Yes, you're right. I just commit the change.

2023-08-10 07:30 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +								me.action_promise.promise().then(function () {
Why did you changed from `new Promise()` to this? I would rather keep the [vanilla JS way](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise) of using promises.

2023-08-22 08:28 UTC, Molkobain approved these changes

2023-08-22 08:29 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +								me.action_promise.promise().then(function () {
Done in [fb77491](https://github.com/Combodo/iTop/pull/358/commits/fb77491a63834c009cb97cdd1022db9046f2d939)

2023-08-22 08:58 UTC, steffunky approved these changes

2023-08-31 09:23 UTC, merged