New PT-BR Translation
Combodo/iTop pull request #362
Opened 2022-11-10 13:21 UTC by eduardomozart

2022-11-10 13:33 UTC, eduardomozart commented
This new translation also includes the PR`s #360 and #361, so they can be closed.

2022-11-17 13:14 UTC, Molkobain commented
@saulob have you checked the translations and are you ok with them as well?

2022-11-17 13:19 UTC, Molkobain requested changes

2022-11-17 13:19 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
@eduardomozart this is the chinese file, please don't modify other languages.

2022-11-17 13:19 UTC, Molkobain commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Please don't change other languages, you have modified all languages.

2022-11-17 13:19 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
This changes the enum label to the long tooltip description, which won't display well.  It won't be accepted. Please, restore the "+" on the entry codes and modify the labels themselves if necessary but keep it short.

2022-11-17 13:19 UTC, Molkobain commented on js/ckeditor/lang/pt-br.js
> +CKEDITOR.lang['pt-br']={"editor":"Editor de Rich Text","editorPanel":"Painel do editor de Rich Text","common":{"editorHelp":"Pressione ALT+0 para ajuda","browseServer":"Localizar no Servidor","url":"
This file cannot be changed, it's a third party lib. Please revert changes.

2022-11-17 13:19 UTC, eduardomozart commented
Hello @Molkobain , yes, I checked them, and they are working as expected. It can be commited as soon as you guys planned to release a newer version of iTop.

2022-11-17 13:27 UTC, eduardomozart commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
I'm not even sure how this is at my commit, as I'm not even finding it at my edition history and I have no knowledge of Chinese language at all. I believe my git software conflicted with the develop branch and uploaded an outdated file to the repo, because I didn't changed this file. As I can't revert this commit (I didn't found it), I simply replaced the contents of this file with the version currently available at the repo. If you guys can revert it or simply commit the newer version that I sent, it's fine.

2022-11-17 13:28 UTC, eduardomozart commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Same as chinese, can't find this commit. Updated my repo to reflect the current one at the Combodo develop branch as I can't revert it.

2022-11-17 13:31 UTC, eduardomozart commented on js/ckeditor/lang/pt-br.js
> +CKEDITOR.lang['pt-br']={"editor":"Editor de Rich Text","editorPanel":"Painel do editor de Rich Text","common":{"editorHelp":"Pressione ALT+0 para ajuda","browseServer":"Localizar no Servidor","url":"
I'd reverted it.

2022-11-17 13:31 UTC, Hipska commented on .gitignore
> +.DS_Store
Don't do this, this should be in your global .gitignore file..

2022-11-17 13:39 UTC, eduardomozart commented on .gitignore
> +.DS_Store
Hello Hipska,
It should also be included at iTop itself, because those kind of files are created automatically by Finder and any macOS developer that contributes for this project can send those ``.DS_Store`` files.

2022-11-17 13:43 UTC, Hipska commented on .gitignore
> +.DS_Store
No, those are system specific files and should be in the global gitignore file. (as I did, and others also doing for 10+ years)

2022-11-17 13:49 UTC, eduardomozart commented on .gitignore
> +.DS_Store
If it's possible for the iTop team also includes this at the ``.gitignore`` file of the project, why not? Why assumes that all developers knows how to deal with Git appropriately? I know how to do so, but most indie developers uses GitHub Desktop and just want to contribute with small code changes, why assume that them know that them must edit their ``.gitignore`` global file manually before contributing? No local code changes should be needed by anyone before contributing.

2022-11-17 14:15 UTC, eduardomozart commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
Hello @Molkobain,
Now I remembered why I edited those files. It was changes that I made to fix a glitch where the "Status" dropdown from mail action doesn't show the text, as seem here: https://github.com/Combodo/iTop/pull/268/commits/c4aaabaeea8c9286cb92ec82366c32943e8c3835

I'd created a Issue ticket at SourceForge for the iTop team deal with this glitch appropriately: https://sourceforge.net/p/itop/tickets/2138/

So, by now, I'll not revert this change, because without it, the Status dropdown text isn't show correctly at my language.

2022-11-17 14:20 UTC, Hipska commented on .gitignore
> +.DS_Store
Simply because this is not a thing to discuss inside a PR for updating a translation.

And to tackle your scenario; They are not obliged to stage and commit all the changed files that appear in the list.

2022-11-17 14:23 UTC, eduardomozart commented on .gitignore
> +.DS_Store
Yes, but if they want to ignore a file (not commit them) through the GitHub Desktop, it changes the ``.gitignore`` file from the iTop project, which is worse, because it doesn't use any kind of RegEx and instead add the full path of the file to the iTop project ``.gitignore`` file, so there will be multiple references to ".DS_Store" files.

2022-11-17 17:02 UTC, saulob commented
Yes @Molkobain , I checked. It's all good.

2022-11-17 20:44 UTC, Molkobain commented
Great guys! There will probably be some modifications required, will look into it soon.
In the meantime @saulob can you send me your fullname and postal address to guillaume.lajarige at combodo.com ? So we can send you thankful stickers :) Thanks!

2022-11-18 08:26 UTC, piRGoif commented on .gitignore
> +.DS_Store
Hello,
Indeed if you want to suggest a .gitignore modification please do it in a dedicated PR so that we can discuss on one subject at a time.

2022-11-18 09:12 UTC, Hipska commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
This is also a thing to be discussed in another PR and has nothing to do with translations of PT-BR. Please revert.

2022-11-18 11:29 UTC, eduardomozart commented on .gitignore
> +.DS_Store
Thank you @piRGoif, I'll do so. I'll revert this change by now.

2022-11-18 12:53 UTC, piRGoif commented on .gitignore
> +.DS_Store
Thanks ! I see revert was done in this branch (4c6f810) and the new PR created (#367)
Closing this conversation.

2022-12-16 08:03 UTC, Molkobain requested changes

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/da.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/de.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'Keine Benachrichtigung wird versendet',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'La notification n\'est pas envoyée',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/it.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/ja.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'De e-mailmelding zal niet verstuurd worden',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/pl.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'Powiadomienie e-mail nie zostanie wysłane',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/ru.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/sk.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/tr.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Do not change another language please. Revert this file.

2022-12-16 08:03 UTC, Molkobain commented on js/ckeditor/lang/pt-br.js
> +CKEDITOR.lang['pt-br']={"editor":"Editor de Rich Text","editorPanel":"Painel do editor de Rich Text","common":{"editorHelp":"Pressione ALT+0 para ajuda","browseServer":"Localizar no Servidor","url":"
This file is from a dependancy, we can't change it, please revert this file.

2022-12-16 08:03 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
Hello Eduardo, I understand but this is another issue. You would like to displayed a detailed description on the dropdown elements. For now we can't accept the PR with this, please revert this.

In the meantime we can help you make a small extension to override these 3 translations in a dedicated extension that you could deploy on your iTop.

2022-12-16 11:20 UTC, eduardomozart commented
Hello @Molkobain,
It's not that I want to add a detailed description on the dropdown element - it is that it isn't shown at all! As stated in https://sourceforge.net/p/itop/tickets/2138/ it shows the default "Status" text from iTop core instead of showing the text from the dropdown menu. It's a bug, I don't want add a custom text to the dropdown menu at all.

2022-12-16 11:29 UTC, eduardomozart commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
Hello @Molkobain,
It's not that I want to add a detailed description on the dropdown element - it is that it isn't shown at all! As stated in https://sourceforge.net/p/itop/tickets/2138/ it shows the default "Status" text from iTop core instead of showing the text from the dropdown menu. It's a bug, I don't want add a custom text to the dropdown menu at all.

2022-12-16 11:45 UTC, Hipska commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Should be solved by doing a new commit that re-adds the +

2022-12-16 11:49 UTC, Hipska commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'The email notification will not be sent~~',
Great, looks ok now 👍

2022-12-16 11:54 UTC, Hipska commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
I also see a bug in my instance related to that.

2022-12-16 12:02 UTC, eduardomozart commented
Hello @Molkobain,
About the ``dictionaries/pt_br.dictionary.itop.core.php`` file commit, please see https://github.com/Combodo/iTop/pull/362#discussion_r1050644850

2022-12-16 13:55 UTC, Hipska commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
But still, this is not the place to discuss bugs/problems.

2023-01-09 13:49 UTC, piRGoif commented
Hello,

Eduardo we won't accept the enum standard / plus swap modification.
But indeed we are ok it could be discussed in another SF ticket / PR dedicated to the display of standard / plus labels in drop downs.

2023-03-15 08:37 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:ActionEmail/Attribute:status/Value:disabled' => 'A notificação de e-mail não será enviada',
```suggestion
	'Class:ActionEmail/Attribute:status/Value:test+' => 'Apenas o destinatário de teste é notificado',
	'Class:ActionEmail/Attribute:status/Value:enabled+' => 'Todos os endereços de e-mails dos campos Para, CC e CCO são notificados',
	'Class:ActionEmail/Attribute:status/Value:disabled+' => 'A notificação de e-mail não será enviada',
```

2023-03-16 12:55 UTC, Hipska approved these changes

2025-09-22 16:23 UTC, jf-cbd commented
Hello @eduardomozart, sorry for the - very - late answer, and thanks for your PR.
Since there's a lot of merge conflicts, I'll resolve them, trying to choose the best translations for all conflict cases.
After that, I'll push it to your branch, and if you're still active (sorry again for this very long delay), I'd appreciate it if you could review it, to see if I didn't make any bad choice.
Thanks in advance

2025-09-22 21:32 UTC, eduardomozart commented
Hello,
Yes, I did think that this PR had been approved a while ago, but I do understand, and I'm willing to help.

2025-09-23 10:07 UTC, jf-cbd commented
Thanks for your message and proposition :)
I noticed a few differences between this PR (compare to the actual translations) but I can't decide which one are improvements and which one or not.
On our side it has been a lot of changes concerning translations, that's why the current PR has so many conflicts.
@saulob and @eduardomozart (I see you're both active, that's awesome !) I'll now push the differences (so it shouldn't be conflict anymore), could you please review them, and indicate the one that should be kept and the one that shouldn't ?
Thanks a lot !

2025-09-23 11:25 UTC, Hipska requested changes
Some minor changes

2025-09-23 11:25 UTC, Hipska commented on dictionaries/pt_br.dictionary.itop.ui.php
> +	 'UI:CurrentObjectIsLockedBy_User' => 'O objeto está bloqueado, pois está sendo modificado por %1$s',
Alignment
```suggestion
	'portal:backoffice' => 'Interface de usuário back-office do '.ITOP_APPLICATION_SHORT,
	'UI:CurrentObjectIsLockedBy_User' => 'O objeto está bloqueado, pois está sendo modificado por %1$s',
```

2025-09-23 11:25 UTC, Hipska commented on datamodels/2.x/itop-core-update/dictionaries/pt_br.dict.itop-core-update.php
> +	'iTopUpdate:UI:Action' => 'Atualizar','iTopUpdate:UI:Setup' => ITOP_APPLICATION_SHORT.' Setup~~',
Newline
```suggestion
	'iTopUpdate:UI:Action' => 'Atualizar',
	'iTopUpdate:UI:Setup' => ITOP_APPLICATION_SHORT.' Setup~~',
```

2025-09-23 12:32 UTC, Hipska approved these changes

2025-09-23 14:29 UTC, eduardomozart commented
Hello,
How can I see the changes to review?

2025-09-23 14:53 UTC, jf-cbd commented
You can see them on https://github.com/Combodo/iTop/pull/362/files.
You can put review directly through GitHub's interface

2025-09-23 15:17 UTC, eduardomozart commented
For me it seems just fine.

2025-09-28 14:57 UTC, saulob commented
Fine by me. Thank you guys

2025-09-29 09:01 UTC, merged

2025-09-29 09:10 UTC, jf-cbd commented
Perfect, thanks @saulob and @eduardomozart for your reviews. I just merged it !
If you want some contributing stickers, the current version (different from the 2022 edition), just put a thumbs up on this message :)

2025-09-29 15:02 UTC, eduardomozart commented
I love to show the stickers (I'm an undergraduate IT teacher) to my students to motivate them to contribute to open-source projects.

2025-09-29 15:27 UTC, piRGoif commented
By the way, the stickers image is no longer present in the CONTRIBUTING file :/        
call in https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful    
and linked file is https://github.com/Combodo/iTop/blob/develop/.doc/contributing-guide/2024.contributing-stickers-side-by-side.png

2025-09-30 07:07 UTC, jf-cbd commented
Hey @eduardomozart @saulob, please send me your address at community[at]combodo.com 😉
@piRGoif thanks for reporting 😊 Yes, we're aware of it, we're trying to find a proper way to fix it.
GitHub doesn't support base64 in md file, and it would be nice if the image wasn't in iTop's package to reduce its size (even if we can compress it)

2025-09-30 07:10 UTC, Hipska commented
The `.doc/` directory isn't in the iTop package, so it can stay there, no?

2025-09-30 07:15 UTC, piRGoif commented
> it would be nice if the image wasn't in iTop's package

Use exclude.txt like for any other files ?

2025-09-30 07:40 UTC, jf-cbd commented
We removed the .doc in a previous commit, but it could be a good idea to restore it, and put this picture, as well as the version schema.
Concerning the exclude.txt, I'm not sure if it's a good way to do (to add many exclusions etc.)

2025-09-30 12:54 UTC, jf-cbd commented
Fixed

2025-09-30 15:25 UTC, eduardomozart commented
> Hey @eduardomozart @saulob, please send me your address at community[at]combodo.com 😉
Sent mine by mail! Thank you!

2025-09-30 21:26 UTC, saulob commented
> Hey @eduardomozart @saulob, please send me your address at community[at]combodo.com 😉 

Sent my address, thanks!

2026-06-11 21:41 UTC, saulobenignoBraza commented
Hello, 

I noticed that PR #362 was merged, but the change is still not available in the latest 3.2.3-1 release

Could you please confirm in which iTop version this PT-BR translation fix will be available?

Thanks

2026-06-12 12:01 UTC, jf-cbd commented
Hello @saulobenignoBraza, the issue has been merged in develop so it will be available in iTop 3.3.0