N°5619 - hide newsroom menu when no provider
Combodo/iTop pull request #363
Opened 2022-11-15 08:12 UTC by dflaven

The newsroom menu can be hidden by configuration, but is not automatically hidden when there is no newsroom provider installed.
This pull request just hides the menu automatically in such a case.

2022-11-17 10:13 UTC, dflaven commented
The second commit fixes a crash when there is actually no provider at all (not reproducible on a Community iTop, since there is the iTop Hub provider...)

2022-11-17 13:10 UTC, Molkobain requested changes

2022-11-17 13:10 UTC, Molkobain commented on sources/application/UI/Base/Component/PopoverMenu/NewsroomMenu/NewsroomMenuFactory.php
> +
Please add the `@since 3.1.0 N°5619` annotation in the PHPDoc as well as the `: bool` return type hint.

Moreover, I feel like this should be a method of the `Combodo\iTop\Application\UI\Base\Component\PopoverMenu\NewsroomMenu`NewsroomMenu` class itself rather than the factory. The factory isn't an helper, it's just there to ease the assembly or a specific use case.

2022-12-13 17:13 UTC, Molkobain commented on sources/application/UI/Base/Component/PopoverMenu/NewsroomMenu/NewsroomMenuFactory.php
> +
@dflaven

2023-01-03 14:52 UTC, Molkobain requested changes

2023-01-03 14:52 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		return (MetaModel::GetConfig()->Get('newsroom_enabled') && NewsroomMenuFactory::HasProviders());
But it does work on Essential/Professional products though, are you sure this is the root cause?

2023-01-09 09:03 UTC, Hipska commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		return (MetaModel::GetConfig()->Get('newsroom_enabled') && NewsroomMenuFactory::HasProviders());
According to https://github.com/Combodo/iTop/pull/363#issuecomment-1318400298 it's "crashing". Don't know what exactly he means with that.

2023-01-09 10:32 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		return (MetaModel::GetConfig()->Get('newsroom_enabled') && NewsroomMenuFactory::HasProviders());
@dflaven

2023-04-06 15:54 UTC, Molkobain commented on sources/application/UI/Base/Component/PopoverMenu/NewsroomMenu/NewsroomMenu.php
> +	 * @return boolean
```suggestion
	 * @return bool
```

2023-04-12 15:32 UTC, dflaven commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		return (MetaModel::GetConfig()->Get('newsroom_enabled') && NewsroomMenuFactory::HasProviders());
Without the second commit it was crashing (during the construction of the iTop WebPage) on Essential/Professional because the (empty) newsroom menu object was not created (because there is not newroom provider on such products).

2023-05-04 12:55 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		return (MetaModel::GetConfig()->Get('newsroom_enabled') && NewsroomMenuFactory::HasProviders());
Discussed with Denis, I could not reproduce the issue on a Professional package. We would like to be able to reproduce the issue in order to ensure the fix is necessary and correct. Denis will dig further to have a reproduction procedure.

2024-08-19 09:20 UTC, closed without merging

2024-08-19 09:20 UTC, Molkobain commented
Closing this PR as it could be reproduced.