N°5620 - Hide the organization filter with a conf parameter
Combodo/iTop pull request #365
Opened 2022-11-16 13:22 UTC by odain-cbd

This enhancement helps hiding menu organization filter via configuration variable.

By default this UI part is visible:
![image](https://user-images.githubusercontent.com/56586767/202207622-dc49e014-c3e7-4566-a020-91cf16bd5527.png)

for backward compatibility reason this is the default behaviour. ie if this new option is not set or set to true.

 To remove it set 'allow_menu_organization_filter' to false.
![image](https://user-images.githubusercontent.com/56586767/202207799-f039c944-8567-4822-8ac8-2a3142a51978.png)

2022-11-16 16:49 UTC, jbostoen commented
Is this properly described? Setting "allow_menu_organization_filter" to "true" means it's... hidden? It seems counter-intuitive?

2022-11-17 09:01 UTC, odain-cbd commented
sorry it is the opposite. to hide this part of the menu you have to set this option to false. I fixed the PR description.

2022-11-17 09:51 UTC, Molkobain requested changes

2022-11-17 09:51 UTC, Molkobain commented on core/config.class.inc.php
> +		'allow_menu_organization_filter' => [
We tend to "namespace" the configuration parameters for easier understanding and to avoid collision. Can you rename it to something like `navigation_menu.show_organization_filter` and move this parameter with the existing one (`navigation_menu.show_menus_count`) ? Thanks

2022-11-17 09:51 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		if (! MetaModel::GetConfig()->Get('allow_menu_organization_filter')){
Mind to update the conf. param. once renamed

2022-11-21 09:11 UTC, odain-cbd commented on core/config.class.inc.php
> +		'allow_menu_organization_filter' => [
thanks I renamed this conf variable.

2022-11-21 18:25 UTC, Molkobain requested changes
Small changes, you can apply them all at once in the GitHub web interface if you want.

2022-11-21 18:25 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +	private function IsOrgMenuFilterAllowed() : bool {
```suggestion
	/**
	 * @return True if the silo selection is enabled, false otherwise
	 * @since 3.1.0
	 */
	public function IsSiloSelectionEnabled() : bool {
```
Rename: Consistency with other methods/properies such as `$bHasSiloSelected`
Visibility: That way the method can be used in TWIG and such. Even though we tend to use defensive programming in some parts of iTop, we rather be dev-friendly in others.

2022-11-21 18:25 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +		if (! $this->IsOrgMenuFilterAllowed()){
```suggestion
		if (! $this->IsSiloSelectionEnabled()){
```

2022-11-21 18:25 UTC, Molkobain commented on test/application/UI/Base/Layout/NavigationMenuTest.php
> +		$isAllowed = $this->InvokeNonPublicMethod(NavigationMenu::class, "IsOrgMenuFilterAllowed", $oNavigationMenu, []);
```suggestion
		$isAllowed = $this->InvokeNonPublicMethod(NavigationMenu::class, "IsSiloSelectionEnabled", $oNavigationMenu, []);
```
Note that as the method is now public, you can change this if you wish.

2022-11-21 18:25 UTC, Molkobain commented on test/application/UI/Base/Layout/NavigationMenuTest.php
> +		$isAllowed = $this->InvokeNonPublicMethod(NavigationMenu::class, "IsOrgMenuFilterAllowed", $oNavigationMenu, []);
```suggestion
		$isAllowed = $this->InvokeNonPublicMethod(NavigationMenu::class, "IsSiloSelectionEnabled", $oNavigationMenu, []);
```

Same as previous comment

2022-11-22 12:27 UTC, Molkobain commented on sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
> +	public function IsSiloSelectionEnabled() : bool {
```suggestion
	/**
	 * @return True if the silo selection is enabled, false otherwise
	 * @since 3.1.0
	 */
	public function IsSiloSelectionEnabled() : bool {
```

2022-11-22 12:30 UTC, Molkobain approved these changes

2022-11-22 13:00 UTC, odain-cbd commented
branch merged apart from PR.

"This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
sources/application/UI/Base/Layout/NavigationMenu/NavigationMenu.php "

2022-11-22 13:00 UTC, closed without merging