Allow 'start' attribute in 'ol' tag
Combodo/iTop pull request #368
Opened 2022-11-18 18:34 UTC by jbostoen

Just an example here. This fork is based on Combodo's Mail to Ticket Automation, which relies on internal methods.

The real contents look like this in MS Outlook (text censored):
![image](https://user-images.githubusercontent.com/6421683/202776735-9a9a359e-808d-4119-92d7-88c92238f396.png)

The contents in iTop look like this:
![image](https://user-images.githubusercontent.com/6421683/202776774-d91c6350-25db-4f4e-af06-6aa26b8a8e69.png)

HTML source:

```
<ol style="margin-top:0in" start="1" type="1"><li class="MsoListParagraph" style="margin-left:0in;mso-list:l0 level1 lfo1">xxx.</li></ol>

<p class="MsoNormal"> </p>

<ol style="margin-top:0in" start="2" type="1"><li class="MsoListParagraph" style="margin-left:0in;mso-list:l0 level1 lfo1">xxxx.</li></ol>
```

After stripping: there is indeed a paragraph in between, and iTop will ignore the "start".

2022-11-18 21:05 UTC, Molkobain approved these changes

2022-11-18 21:06 UTC, Molkobain commented
Thanks for the PR Jeffrey! Makes total sense, will push it forward during next reviews.

2022-11-18 23:18 UTC, Hipska approved these changes

2022-11-21 08:10 UTC, piRGoif approved these changes
As a reference : https://www.w3.org/TR/html4/struct/lists.html#edef-OL

2022-12-06 16:27 UTC, Molkobain commented
The idea was accepted during the technical review.
We would like you to update the corresponding unit test though, it can be found in test/core/sanitizer.

_PR will be reviewed functionally next week anyway to save time for the next iteration._

2022-12-06 16:27 UTC, Molkobain requested changes
Update corresponding unit test please.

2022-12-07 09:15 UTC, jbostoen commented
Do I just need to edit utf-8_wrong_character_email_truncated.txt ?
Or create a new file? (and if so, do I need to add a reference to it somewhere in another file?)

2022-12-07 11:40 UTC, Molkobain commented
I think it should rather be `whitelist_test.html` but its content doesn't seem right. @piRGoif ?

2022-12-07 16:05 UTC, piRGoif commented
Hello !

About the test, I would add the new attribute in the \Combodo\iTop\Test\UnitTest\Core\Sanitizer\HTMLDOMSanitizerTest::WhiteListProvider method, to check if the attribute is kept after the sanitize run.

Maybe add also a new data set in \Combodo\iTop\Test\UnitTest\Core\Sanitizer\HTMLDOMSanitizerTest::RemoveBlackListedTagContentProvider, to check for OL with attributes to remove and the new one to keep ?

2022-12-13 16:52 UTC, Molkobain commented
Accepted during functional review.
Will be merged once unit test is updated.

2022-12-14 08:28 UTC, jbostoen commented
Would this qualify?

I extended the PR a bit based on info from W3Schools:
* https://www.w3schools.com/tags/tag_li.asp
* https://www.w3schools.com/tags/tag_ol.asp

Basically:
* li: also allow 'value' (to set a starting value)
* ol: also allow 'reversed' (decreasing list), 'type' (see link above) and 'start' (to set a starting value).

I quickly fiddled around, but didn't see the real difference between li > value and ol > start. ( https://stackoverflow.com/questions/33374212/difference-value-and-start-in-html-lists )

2022-12-14 14:41 UTC, Molkobain approved these changes

2022-12-14 14:42 UTC, Molkobain commented
Yes, it's closely related :)

2022-12-14 14:45 UTC, Molkobain commented on test/core/sanitizer/HTMLDOMSanitizerTest.php
> +			'list test' => array(
```suggestion
			'ordered list with attributes' => array(
```

2022-12-14 14:47 UTC, merged

2023-01-17 16:25 UTC, jbostoen commented
Mind to also update https://www.itophub.io/wiki/page?id=latest:admin:rich_text_limitations

2023-01-17 18:41 UTC, Molkobain commented
Done but will only appear once 3.1 wiki is published :)