:memo: CONTRIBUTING improvements
Combodo/iTop pull request #371
Opened 2022-11-23 13:42 UTC by piRGoif

Add some info on what the PR description should contain.
Also 2 little modification (header level and text case)

2022-11-23 13:57 UTC, Hipska approved these changes

2022-11-23 18:18 UTC, Molkobain commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
Do you mean "squash"?

2022-11-24 07:57 UTC, piRGoif commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
Woops, this typo is here from the beginning :/  Better late than never :o)
Will fix it directly in the current file starting from support/2.7 !

2022-11-24 08:03 UTC, piRGoif commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
Done in e9c91d98
Closing conversation

2022-12-01 11:57 UTC, Molkobain requested changes

2022-12-01 11:57 UTC, Molkobain commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
It still says "Stash" for me even though you fixed it at some point in the past

2022-12-01 12:06 UTC, Hipska commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
That commit doesn't seem to be on this branch anymore. But also, what a strange advise: "Squash as much as possible"? What does that even mean?

To me, it makes reviewing easier if the changes are separate commits, compared to how Jeffrey does it by force pushing the branch completely. Then it is not easy to see what has been changed between your last view/review and the latest push..

Stashing as much as possible still looked as a good advise..

2022-12-01 12:32 UTC, Molkobain commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
> Stashing as much as possible still looked as a good advise..

But what does it mean in case of a PR? You only stash locally what you don't want to commit/push don't you?

2022-12-01 13:02 UTC, Hipska commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
You are right. Both ways don't make much sense 😄

2022-12-02 15:49 UTC, Molkobain commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
To me "squash you commits" meant : Clean your branch as much as possible by squashing commits that can be (eg. "Fix 1", "Fix 2", ...) which we strongly suggest. Otherwise in some case we have to make a "Squash and merge" to keep the history clean.

2022-12-02 16:28 UTC, piRGoif commented on CONTRIBUTING.md
> +* Stash as much as possible your commits,
The typo fix was pushed in e9c91d98, and I didn't rebased this branch afterwards. 
Going to fix it ! 

About the meaning of the sentence : we wanted to ask to make the history as much logic as possible before asking for a review. 
During dev, you will often push multiple commits in a row, the history will just represent your coding workflow and can be hard to understand. 
So we are asking to do the appropriate history corrections before asking for a review : regroup same modifications together in particular.

2022-12-02 16:30 UTC, piRGoif commented
Branch rebased & force pushed.
Now we get the stash/squash typo fix !

2022-12-05 19:40 UTC, Molkobain approved these changes

2022-12-06 16:17 UTC, Molkobain commented
Accepted during technical review.
Functional review will be skipped as this is purely on the technical side.

2022-12-06 16:19 UTC, merged