:memo: SECURITY : add disclose policy
Combodo/iTop pull request #372
Opened 2022-11-23 16:53 UTC by piRGoif

2022-11-23 18:21 UTC, Molkobain requested changes

2022-11-23 18:21 UTC, Molkobain commented on SECURITY.md
> +Once the fix done and acknowledge by every stakeholder, it will be included in next iTop version.
```suggestion
Once the fix is done and acknowledged by every stakeholder, it will be included in next iTop version.  
```

_Not sure of the "is done" 👀_

2022-11-24 09:55 UTC, BenGrenoble approved these changes

2022-11-24 12:52 UTC, Molkobain approved these changes

2022-11-25 13:12 UTC, jbostoen commented on SECURITY.md
> +## 🔍 Combodo feedbacks
just "feedback" without s?

2022-11-25 13:13 UTC, jbostoen commented on SECURITY.md
> +Once the fix is done and acknowledged by every stakeholder, it will be included in next iTop version.
in the next iTop version

2022-11-25 16:33 UTC, piRGoif commented on SECURITY.md
> +Once the fix is done and acknowledged by every stakeholder, it will be included in next iTop version.
Fix in 2d39a56d, thanks !

2022-11-25 16:33 UTC, piRGoif commented on SECURITY.md
> +## 🔍 Combodo feedbacks
I've decided to completely change the title :D See in 2d39a56d
What do you think ?

2022-12-06 16:19 UTC, Molkobain commented
Accepted during technical review.

2022-12-13 16:42 UTC, Molkobain commented
Accepted during functional review.

2022-12-13 17:15 UTC, merged