Feature/modals - generic modal API
Combodo/iTop pull request #373
Opened 2022-11-30 16:05 UTC by bdalsass

Default modal JS Implementation:
- Add title option
- Add buttons option
- Change template cloning

Confirmation Modal:
- Add implementation
- Do not show again functionality

Web Page:
- Add blocks array with twig loop insertion

2022-12-01 13:48 UTC, steffunky submitted a review, later dismissed

2022-12-01 13:48 UTC, steffunky commented on css/backoffice/components/_modal.scss
> +  margin-top: 16px;
Could you put this value in a dedicated SCSS variable so it's easier to overload it with a theme?
Also, you should use `$ibo-spacing-500` instead of hardcoding `16px` into this new variable

2022-12-01 13:48 UTC, steffunky commented on css/backoffice/components/_modal.scss
> +  input[type="checkbox"]{
Could you bring back your `--do-not-show-again--checkbox` class for this rule so it's easier to overload it with a theme?

2022-12-01 13:48 UTC, steffunky commented on sources/Application/UI/Base/Component/Modal/DoNotShowAgainOptionBlock.php
> +		$this->AddSubBlock($checkBox);
```suggestion
		$oCheckbox = InputUIBlockFactory::MakeStandard('checkbox', 'do_not_show_again', false);
		$oCheckbox->SetLabel(Dict::S('UI:UserPref:DoNotShowAgain'));
		$this->AddSubBlock($oCheckbox);
```

2022-12-01 13:48 UTC, steffunky commented on sources/Application/WebPage/iTopWebPage.php
> +		$this->add_dict_entry('UI:Modal:DefaultConfirmationTitle');
You could use `add_dict_entries('UI:Modal')` as we'll probably need every Modal dictionary entries to be loaded with the page

2022-12-02 06:00 UTC, bdalsass commented on css/backoffice/components/_modal.scss
> +  margin-top: 16px;
done

2022-12-02 06:00 UTC, bdalsass commented on css/backoffice/components/_modal.scss
> +  input[type="checkbox"]{
done

2022-12-02 06:01 UTC, bdalsass commented on sources/Application/UI/Base/Component/Modal/DoNotShowAgainOptionBlock.php
> +		$this->AddSubBlock($checkBox);
done

2022-12-02 06:02 UTC, bdalsass commented on sources/Application/WebPage/iTopWebPage.php
> +		$this->add_dict_entry('UI:Modal:DefaultConfirmationTitle');
cool tip 👾

2022-12-02 06:03 UTC, bdalsass commented on sources/Application/WebPage/iTopWebPage.php
> +		$this->add_dict_entry('UI:Modal:DefaultConfirmationTitle');
done

2022-12-02 10:12 UTC, steffunky approved these changes

2022-12-02 14:27 UTC, Molkobain requested changes

2022-12-02 14:27 UTC, Molkobain commented on css/backoffice/components/_modal.scss
> +  margin-top: $ibo-spacing-500;
Introduce a SCSS variable for this, so this margin can be overridden in themes without redefining the whole class.
Typical variable name would be `$ibo-modal-option--do-not-show-again--margin-top`

2022-12-02 14:27 UTC, Molkobain commented on dictionaries/ui/components/modal/en.dictionary.itop.modal.php
> +	'UI:Modal:DefaultConfirmationTitle' => 'Confirmation',
```suggestion
	'UI:Modal:Confirmation:DefaultTitle' => 'Confirmation',
```

As we might have more and more predefined modals, what to think of namespacing things like this?
This way we can add more and more modals in the future and still find what is related to each easily.

2022-12-02 14:27 UTC, Molkobain commented on dictionaries/ui/components/modal/en.dictionary.itop.modal.php
> +// Input
Not relevant

2022-12-02 14:27 UTC, Molkobain commented on dictionaries/ui/components/modal/fr.dictionary.itop.modal.php
> +));
Same comment as in english file

2022-12-02 14:27 UTC, Molkobain commented on js/dataTables.settings.js
> +					if(me.options.bHasRowActions){
```suggestion
					// Append row actions column
					if (me.options.bHasRowActions) {
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +		buttons: CombodoModal.ConvertButtonDefinition(oOptions.buttons)
```suggestion
		buttons: this.ConvertButtonDefinition(oOptions.buttons)
```

Do you think using "this" instead of a full class name would be more explicit in understanding that it actually refers to something of the same object?

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +CombodoModal.ConvertButtonDefinition = function(aButtonsDefinitions){
Is that a protected/private method that is only meant to be used within CombodoModal? Is so, please prefix the method name with a "_". It's only a convention, it has no constraint.

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +	// merge external options with confirmation modal default options
```suggestion
	// Merge external options with confirmation modal default options
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +			if(oOptions.callback_on_confirm != null){
```suggestion
	// Check do not show again preference key
	if(oOptions.do_not_show_again_pref_key !== null){
		if(GetUserPreference(oOptions.do_not_show_again_pref_key, false)){
			if(oOptions.callback_on_confirm !== null){
```

We tend not to rely on type conversion

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +					// call confirm handler and close dialog
```suggestion
					// Call confirm handler and close dialog
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +						// handle "do not show again" user preference
```suggestion
						// Handle "do not show again" user preference
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +			// add option do not show again from template
```suggestion
			// Add option do not show again from template
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +						bCanClose = oOptions.callback_on_cancel(...aData) != false;
```suggestion
						bCanClose = oOptions.callback_on_cancel(...aData) !== false;
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +						bCanClose = oOptions.callback_on_confirm(...aData) != false;
```suggestion
						bCanClose = oOptions.callback_on_confirm(...aData) !== false;
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +						let bDoNotShowAgain = oOptions.do_not_show_again_pref_key != null ?
```suggestion
						let bDoNotShowAgain = oOptions.do_not_show_again_pref_key !== null ?
```

2022-12-02 14:27 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +			if(oOptions.do_not_show_again_pref_key != null) {
```suggestion
			if(oOptions.do_not_show_again_pref_key !== null) {
```

2022-12-02 14:27 UTC, Molkobain commented on js/utils.js
> +	OpenUrlInModal: function(sTargetUrl, bCloseOtherModals, oCallbackOnContentLoaded) {
```suggestion
	OpenUrlInModal: function(sTargetUrl, bCloseOtherModals, oCallbackOnContentLoaded) {
```

In that case, OCallbackOnContentLoaded isn't really an object, it's an anonymous function. We rather not prefix the type or define a prefix for this as a convention (but this has to be done with the whole team)

2022-12-02 14:27 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/tTableRowActions.php
> +	protected $aRowActions = array();
```suggestion
	protected $aRowActions = [];
```

Short array syntax is preferred

2022-12-02 14:27 UTC, Molkobain commented on sources/Application/UI/Base/Component/Modal/DoNotShowAgainOptionBlock.php
> +		$oCheckBox->SetLabel(\Dict::S('UI:UserPref:DoNotShowAgain'));
```suggestion
		$oCheckBox->SetLabel(Dict::S('UI:UserPref:DoNotShowAgain'));
```

Add use statement instead for clearer reading please.

2022-12-02 14:27 UTC, Molkobain commented on sources/Application/UI/Base/Component/Template/TemplateUIBlockFactory.php
> +	public static function MakeForBlock(string $sId, UIContentBlock $oContentBlock)
Add a simple description of what the method is intended for. It will be displayed in the generated documentation.

2022-12-02 14:27 UTC, Molkobain commented on sources/Application/WebPage/iTopWebPage.php
> +		// confirmation modal
```suggestion
		// Modals
```

2022-12-02 14:27 UTC, Molkobain commented on templates/pages/backoffice/itopwebpage/layout.html.twig
> +    {# templates #}
```suggestion
    {# Templates #}
```

2022-12-06 07:01 UTC, bdalsass commented on dictionaries/ui/components/modal/en.dictionary.itop.modal.php
> +// Input
done

2022-12-06 07:03 UTC, bdalsass commented on css/backoffice/components/_modal.scss
> +  margin-top: $ibo-spacing-500;
done

2022-12-06 07:06 UTC, bdalsass commented on sources/Application/UI/Base/Component/Template/TemplateUIBlockFactory.php
> +	public static function MakeForBlock(string $sId, UIContentBlock $oContentBlock)
done

2022-12-06 09:18 UTC, merged