Feature/links table row actions
Combodo/iTop pull request #377
Opened 2022-12-12 10:15 UTC by bdalsass

Linkset updates, feedbacks 09/12:
- Distinguish action label and tool tip message
- Change default action button label Ok => Confirm
- Use action label in place of default  confirm button label
- Attach do not show again preference key to table instance

2022-12-13 14:00 UTC, steffunky approved these changes

2022-12-14 14:13 UTC, Molkobain requested changes

2022-12-14 14:13 UTC, Molkobain commented on dictionaries/ui/application/links/en.dictionary.itop.links.php
>  	'UI:Links:ActionRow:delete:confirmation' => 'Do you really want to delete <b>{item}</b> from current object ?',
Capital on first letters please

2022-12-14 14:13 UTC, Molkobain commented on dictionaries/ui/application/links/fr.dictionary.itop.links.php
> +	'UI:Links:ActionRow:delete:confirmation' => 'Voulez-vous supprimer <b>{item}</b> de l\'objet courant ?',
```suggestion
	'UI:Links:ActionRow:Detach'              => 'Détacher',
	'UI:Links:ActionRow:Detach+'             => 'Détacher cet objet',
	'UI:Links:ActionRow:Detach:Confirmation' => 'Voulez-vous détacher <b>{item}</b> de l\'objet courant ?',
	'UI:Links:ActionRow:Delete'              => 'Supprimer',
	'UI:Links:ActionRow:Delete+'             => 'Supprimer cet objet',
	'UI:Links:ActionRow:Delete:Confirmation' => 'Voulez-vous supprimer <b>{item}</b> de l\'objet courant ?',
```

Same as previous comment. Mind to update the rest of their usages.

2022-12-14 14:13 UTC, Molkobain commented on sources/Application/UI/Links/AbstractBlockLinksViewTable.php
> +	protected function GetTableId()
```suggestion
	protected function GetTableId(): string
```

2022-12-14 14:13 UTC, Molkobain commented on sources/Application/UI/Links/AbstractBlockLinksViewTable.php
> +	protected function GetDoNotShowAgainPreferenceKey()
```suggestion
	protected function GetDoNotShowAgainPreferenceKey(): string
```

2022-12-14 14:13 UTC, Molkobain commented on templates/base/components/datatable/layout.live.js.twig
> +    var oSelectedItems{{ oUIBlock.GetOption('sListId')|sanitize(constant('utils::ENUM_SANITIZATION_FILTER_VARIABLE_NAME')) }} = [];
Sorry for that 🤭

2022-12-14 14:13 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +				text: oOptions.confirm_button_label != null ? oOptions.confirm_button_label : Dict.S('UI:Button:Confirm'),
```suggestion
				text: oOptions.confirm_button_label ?? Dict.S('UI:Button:Confirm'),
```

Can we simplify it like this? I think so.

2022-12-14 14:14 UTC, Molkobain commented
_Mind to rename the PR with the bug number as prefix to ease history reading please (eg. "N°1234 - Doing something on links table row actions")_

2022-12-19 07:21 UTC, bdalsass commented on dictionaries/ui/application/links/en.dictionary.itop.links.php
>  	'UI:Links:ActionRow:delete:confirmation' => 'Do you really want to delete <b>{item}</b> from current object ?',
done

2022-12-20 08:33 UTC, Molkobain approved these changes

2022-12-20 08:34 UTC, Molkobain commented
> _Mind to rename the PR with the bug number as prefix to ease history reading please (eg. "N°1234 - XXX")_

@bdalsass this will also be important for squash & merge

2022-12-20 09:10 UTC, merged