N°3136 - Add creation and modification of n-n objects in object details
Combodo/iTop pull request #378
Opened 2022-12-14 13:21 UTC by steffunky

Allows for the creation and modification of links in popups when accessing an object in visualization.

TODO

- [x] Move "Create" button in accordance with #222 and af804a9 principles.
- [x] In the event that CheckTo* fails, obtain the return value from the `apply_new` and `apply_modify` operations and allow retry.

2022-12-15 10:52 UTC, Molkobain commented on application/utils.inc.php
> +			$aResult[] = new JSPopupMenuItem('UI:Menu:New', Dict::S('UI:Menu:New'), "LinkSetWorker.CreateLinkedObject('$sDataTableId')");
Shouldn't this rather be the first menu item when not in the favorite actions?

2022-12-15 10:58 UTC, Molkobain commented on js/links/link_set_worker.js
>  	const ROUTER_BASE_URL = '../pages/ajax.render.php';
I know this ain't from your commit, but could you use the JS helper to make it an absolute URL? This way the script won't break if we ever move it to another folder

2022-12-15 11:04 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +	if(aButtonsDefinitions !== null) {
What about making it an exit condition instead? It makes it easier to read IMO

2022-12-15 11:07 UTC, Molkobain commented on sources/Controller/Links/LinksetController.php
> +	public function OperationCreateLinkedObject()
Where is all that business logic copied from? We might be able to factorize part of it.

2022-12-21 10:03 UTC, steffunky commented on application/utils.inc.php
> +			$aResult[] = new JSPopupMenuItem('UI:Menu:New', Dict::S('UI:Menu:New'), "LinkSetWorker.CreateLinkedObject('$sDataTableId')");
I thought it'd always be in the favorite actions as it's not an action on the list but rather a linkset action

2022-12-22 14:30 UTC, steffunky commented on js/pages/backoffice/toolbox.js
> +	if(aButtonsDefinitions !== null) {
Fixed in [e8c7292](https://github.com/Combodo/iTop/pull/378/commits/e8c7292e6353bb2885bec060e5d3282c96352641)

2022-12-22 14:32 UTC, steffunky commented on sources/Controller/Links/LinksetController.php
> +	public function OperationCreateLinkedObject()
Copied from UILinksWidgetDirect::GetObjectCreationDlg but I'm not sure we want to mess with this bit of code

2023-01-10 09:50 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					->SetOnClickJsCode("LinkSetWorker.CreateLinkedObject('$sId')");
Discussed with Stephen IRL, we need to rework that part to avoid coupling it to linksets.

2023-01-10 09:55 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					Dict::S('UI:Links:New:Button:Tooltip'),
Discussed with Stephen IRL, will change to a label

2023-01-10 09:55 UTC, Molkobain commented on css/backoffice/components/_modal.scss
> +  }
Discussed with Stephen IRL, try to factorize this with the one from the alert block. This way, on next UI rework it will all be done at once.

2023-01-10 09:55 UTC, Molkobain commented on sources/Application/UI/Links/AbstractBlockLinksViewTable.php
> +		$this->SetDataAttributes(['role' => 'ibo-block-links-table', 'link-attcode' => $sAttCode, 'link-class' => $this->oAttDef->GetLinkedClass()]);
See if we must align `ibo-block-links-table` with the real block code (`ibo-abstract-block-links-view-table`).
Mind to update call to parent constructor as well.

2023-01-13 09:45 UTC, steffunky commented on css/backoffice/components/_modal.scss
> +  }
Fixed in 400b155

2023-01-13 10:04 UTC, steffunky commented on sources/Application/UI/Links/AbstractBlockLinksViewTable.php
> +		$this->SetDataAttributes(['role' => 'ibo-block-links-table', 'link-attcode' => $sAttCode, 'link-class' => $this->oAttDef->GetLinkedClass()]);
Discussed with Guillaume IRL, it's used to have a common data-role with its child classes and a common value with block classes

2023-01-13 10:06 UTC, steffunky commented on application/displayblock.class.inc.php
> +					Dict::S('UI:Links:New:Button:Tooltip'),
Fixed in 112d763

2023-01-17 09:41 UTC, steffunky commented on application/displayblock.class.inc.php
> +					->SetOnClickJsCode("LinkSetWorker.CreateLinkedObject('$sId')");
Fixed in d42f984

2023-01-17 13:16 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTable.php
> +	protected string $sModalCreationHandler;
Add a description in the PHPDoc of what we expect (a JS snippet) and how it will be used.

2023-01-17 14:26 UTC, Molkobain requested changes

2023-01-17 14:26 UTC, Molkobain commented on application/displayblock.class.inc.php
> +				if($this->m_sStyle === 'list' || $this->m_sStyle === 'links'|| $this->m_sStyle === 'listInObject'){
Discussed IRL with Stephen, will be changed to a `in_array` instead of three conditions

2023-01-17 14:26 UTC, Molkobain commented on application/displayblock.class.inc.php
> +				if ($bIsCreationAllowed && !$bCreationInModalAllowed) {
Discussed IRL with Stephen, will be renamed `$bIsCreationInModalAllowed` to be consistent with the other variable?

2023-01-17 14:26 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					->SetOnClickJsCode("$('#$sRealId').trigger('creation_in_modal');");
Discussed IRL with Stephen, will be namespaced to `open_creation_modal.object.itop`

2023-01-17 14:26 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +			/** Handler to call when trying to create a new object in modal */
Should we name it `xxx_js_handler` to explicit that it's a JS handler, not a PHP thing yo be called on the server?

2023-01-17 14:26 UTC, Molkobain commented on sources/Application/UI/Base/Component/DataTable/DataTable.php
> +	protected string $sModalCreationHandler;
Add a description in the PHPDoc of what we expect (a JS snippet) and how it will be used.

2023-01-17 14:26 UTC, Molkobain commented on templates/base/components/datatable/layout.ready.js.twig
> +$('#{{ oUIBlock.GetId() }}').on('creation_in_modal.object.itop', function (){
Rename as well

2023-01-18 09:06 UTC, steffunky commented on application/displayblock.class.inc.php
> +				if($this->m_sStyle === 'list' || $this->m_sStyle === 'links'|| $this->m_sStyle === 'listInObject'){
Fixed in 22a19aa

2023-01-18 09:07 UTC, steffunky commented on application/displayblock.class.inc.php
> +				if ($bIsCreationAllowed && !$bCreationInModalAllowed) {
Fixed in 686b09c

2023-01-18 09:08 UTC, steffunky commented on application/displayblock.class.inc.php
> +					->SetOnClickJsCode("$('#$sRealId').trigger('creation_in_modal');");
Fixed in 856b549

2023-01-18 09:08 UTC, steffunky commented on sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
> +			/** Handler to call when trying to create a new object in modal */
Fixed in 0bf698c

2023-01-18 09:09 UTC, steffunky commented on templates/base/components/datatable/layout.ready.js.twig
> +$('#{{ oUIBlock.GetId() }}').on('creation_in_modal.object.itop', function (){
Fixed in 89fa65a

2023-01-18 09:09 UTC, steffunky commented on sources/Application/UI/Base/Component/DataTable/DataTable.php
> +	protected string $sModalCreationHandler;
Fixed in 89fa65a

2023-01-18 09:12 UTC, Hipska commented
Sounds great, do you have a before and after screenshot please?

2023-01-18 09:24 UTC, Molkobain requested changes

2023-01-18 09:24 UTC, Molkobain commented on application/utils.inc.php
> +	public static function ToCamelCase($sInput)
Needs to be reverted

2023-01-18 09:39 UTC, steffunky commented on application/utils.inc.php
> +	public static function ToCamelCase($sInput)
Fixed in 496d862

2023-01-18 10:14 UTC, steffunky commented
> Sounds great, do you have a before and after screenshot please?

I don't have any before, but this is the current linkset workflow on this branch

![untitled](https://user-images.githubusercontent.com/5959857/213144850-e1cffc41-1f10-46dd-be80-87cbda2868a3.gif)

![untitled2](https://user-images.githubusercontent.com/5959857/213144885-7a671d25-e049-44e8-a4d9-75ad4581a090.gif)

2023-01-18 10:24 UTC, Molkobain approved these changes
Nice job ✌

2023-01-18 12:35 UTC, merged