N°4852 sub-menu tooltip: display "+" dict entries
Combodo/iTop pull request #380
Opened 2022-12-20 13:52 UTC by v-dumas

2022-12-20 14:20 UTC, piRGoif requested changes
Maybe some more efforts on the corresponding documentation...

2022-12-20 14:20 UTC, piRGoif commented on application/menunode.class.inc.php
> +				'sLabel'           => $oSubMenuNode->GetLabel(),  // Bug #4852
No need to add this inline comment : we will get the information from the git history.

However, it would be interesting to understand what is the value returned by \MenuNode::GetLabel, so maybe add more information in this later method PHPDoc block ? 

Also, you can document the \ApplicationMenu::GetSubMenuNodes returned array with the [array shapes syntax](https://www.itophub.io/wiki/page?id=latest:customization:coding_standards#arrays_with_named_keysarray_shapes) ?

2022-12-20 15:23 UTC, Molkobain requested changes

2022-12-20 15:23 UTC, Molkobain commented on templates/base/layouts/navigation-menu/menu-node.html.twig
> +    {% endif %}
Careful, your IDE replaced the tab indentions with white spaces. Please revert it and adjust your IDE settings.

2022-12-20 15:23 UTC, Molkobain commented on application/menunode.class.inc.php
> +				'sLabel'           => $oSubMenuNode->GetLabel(),  // Bug #4852
I'm not comfortable with the description being retrieved with a method named `GetLabel` as it is very similar to `GetTitle`. Not intuitive at all to me, something like `GetDescription` should have been way better, but that's not your fault, they are already named like this 😕

As for Pierre's comment, indeed the bug number is not mandatory but if you keep it, please use the internal bug tracker convention (eg N°4852) as `#` is for SourceForge tickets.

2022-12-22 13:30 UTC, v-dumas commented on application/menunode.class.inc.php
> +				'sLabel'           => $oSubMenuNode->GetLabel(),  // Bug #4852
Does [this](https://github.com/Combodo/iTop/pull/380/commits/8902033b78dab1cd6acba9b7ec87f47f8be2caad) do the job ?

2022-12-22 20:37 UTC, Molkobain commented on application/menunode.class.inc.php
> +	 * @return string the + dictionary entry for this menu if exists, otherwise the Title
```suggestion
	 * @return string The "+" dictionary entry for this menu if exists, otherwise the Title
```

2022-12-22 20:38 UTC, Molkobain approved these changes
All good to me!

2022-12-22 20:39 UTC, Molkobain commented
Once it's ok with Pierre as well, poke us so we squash & merge the PR

2022-12-23 10:52 UTC, piRGoif requested changes
Thanks for all those modifications 👌
Just a little remark on a phpdoc

2022-12-23 10:52 UTC, piRGoif commented on application/menunode.class.inc.php
> +	 * @return string The "+" dictionary entry for this menu if exists, otherwise the Title
Actually this isn't totally true as if there aren't any "+" dict key, we won't simply call GetTitle...

```suggestion
	 * @return string The "+" dictionary entry for this menu if exists, otherwise the Title (if we have a parent title, will output parentTitle / currentTitle)
```

2022-12-23 10:52 UTC, piRGoif commented on application/menunode.class.inc.php
> +				'sLabel'           => $oSubMenuNode->GetLabel(),  // Bug #4852
Thanks for the modifications ! I've just made a new review.
Closing this conversation.

2022-12-23 11:22 UTC, v-dumas commented on application/menunode.class.inc.php
> +	 * @return string The "+" dictionary entry for this menu if exists, otherwise the Title
Do you have an example, where this combination of title is occurring, I have never seen it on any iTop...
![sub-menu-title](https://user-images.githubusercontent.com/42336698/209327684-5093691e-e8c8-4b6f-b324-8c57f26c2d52.png)

2022-12-23 13:08 UTC, piRGoif commented on application/menunode.class.inc.php
> +	 * @return string The "+" dictionary entry for this menu if exists, otherwise the Title
I described the code I saw in GetLabel(), but currently we are using GetTitle in the menu right ? 
There are multiple callers for this \MenuNode::GetLabel method but might not be very easy to spot where the parent + current string can appear ?

2022-12-23 14:36 UTC, piRGoif approved these changes

2022-12-23 14:48 UTC, merged