N°2916 - Import of IPv6 addresses fails when reconciliation is done on the ip
Combodo/iTop pull request #382
Opened 2022-12-22 17:23 UTC by accognet

Add an interface that should be implemented in order to handle  object type fields on import. It adds a function to transform the object (like ormIPv6) into a string.
This function is used twice during the CVS import:
- to find the corresponding objects in iTop if the field is a search criterion.
- when updating the object if the field is read-only.

2022-12-23 09:14 UTC, Hipska requested changes

2022-12-23 09:14 UTC, Hipska commented on core/metamodel.class.php
> +						if (is_object($value) && method_exists($value, 'GetValueForQuery')) {
```suggestion
						if ($value instanceof iOrmset) {
```
https://3v4l.org/RRMSR

2022-12-23 09:14 UTC, Hipska commented on core/iOrmset.php
> +interface iOrmset
I don't think this is actually a set of ORM objects? If it is, shouldn't the naming more be like this?
```suggestion
interface iOrmSet
```

2023-01-03 14:36 UTC, accognet commented on core/metamodel.class.php
> +						if (is_object($value) && method_exists($value, 'GetValueForQuery')) {
This was my first idea, but this fix is ​​for Teemip first. I waited to meet xtophe and validate that it's ok for him to lose 3.0 compatibility in his extension. I can now make this change.

2023-01-03 16:18 UTC, Molkobain commented
Discussed during technical review, Anne-Catherine and Christophe will:
- Revert modifications in the core
- Work on the AttributeIPXX attributes to implement the `MakeVaueFromString` methods as it is how the CSV import should build the value for reconcialiation.
- Check were it fails then
- Adjust the PR with the new fix if necessary

2023-01-03 16:18 UTC, Molkobain requested changes
Check previous comment

2023-01-09 09:27 UTC, Hipska commented on core/metamodel.class.php
> +						if (is_object($value) && method_exists($value, 'GetValueForQuery')) {
How will this break 3.0 compatibility?

2023-01-09 13:56 UTC, piRGoif commented
> * Work on the AttributeIPXX attributes to implement the `MakeValueFromString` methods as it is how the CSV import should build the value for reconcialiation.

The method PHPDoc might be changed also ? Currently it is : 

`Get the value from a given string (plain text, CSV import)`

Maybe explain "the value" is for example ormSet, etc ?

2023-01-09 14:16 UTC, Hipska commented on core/iOrmset.php
> +interface iOrmset
Hi @accognet,  you resolved, but I didn't see an answer to my question?

2023-01-11 11:04 UTC, Hipska approved these changes

2023-01-13 09:21 UTC, Hipska commented
Would this also solve the issue mentioned in https://github.com/TeemIp/teemip-core-ip-mgmt/issues/14?

2023-02-13 13:54 UTC, Molkobain commented
Accepted during technical review.
Anne-Catherine will check with Olivier to add a test for a composite attribute (eg. a linkset)

2023-02-13 14:59 UTC, Molkobain approved these changes

2023-02-21 14:43 UTC, Molkobain commented
Discussed with Alexandre during iTop 3.0.3 init meeting, if the unit test is made / validated before code freeze (2023/03/10), the PR will be merged into the 3.0.3, otherwise it will be postponed.

2023-02-28 11:08 UTC, merged

2023-03-02 10:14 UTC, xtophe38 commented
Successfully tested on develop & support/3.0 branches with coming TeemIp 3.1.