N°2783 - Add support for custom zlists
Combodo/iTop pull request #389
Opened 2023-01-17 19:47 UTC by Molkobain

This is a reboot of #100 as we need to move forward and Thomas lacks time.

**Collection**
  * Custom zlists must be defined under the `/itop_design/classes/class/presentation/customs` which will contain zlists brought by customizations (extensions, Designer, ...)
  * This collection node must be added empty to all standard DM classes
  * This collection node must be added empty by the compiler on XML datamodel files during the version upgrade (see _iTopDesignFormat::From30To31()_)

**Definition of the zlist**
  * Each custom zlist will be represented by a `<custom id="ZLIST_ID">[...]</custom>` node
  * The node must contain the same XML structure as other zlists (no particular test to do at compile time)
  * Custom zlist can (optional) expose a description of their purpose so it will be displayed in the Designer as they will be no specific UI display (nothing to there for you Thomas, just to explain why it's in the example below)

**Implementation**
  * Compiler should **append** custom zlist to the standard ones (= same PHP structure)
  * Compiler should throw an exception if a custom zlist has the same name (ID) as a standard one (need for explicit ID will be added in the documentation)
  * `MetaModel::GetZListItems()` will be used to retrieve both standard and custom zlists. If a custom zlist does not exist, it will return an empty array as it already does.

**Example**
```
<itop_design>
    <classes>
        <class id="UserRequest">
            <presentation>
                <details>[...]</details>
                <list>[...</list>
                [...]
                <customs>
                    <custom id="webhook-action-slack">
                        <items>
                            <item id="caller_id">
                                <rank>10</rank>
                            </item>
                            <item id="org_id">
                                <rank>20</rank>
                            </item>
                        </items>
                    </custom>
                </customs>
            </presentation>
        </class>
        <class id="Incident">
            <presentation>
                <customs>
                    <custom id="webhook-action-slack">
                        <items>
                            <item id="caller_id">
                                <rank>10</rank>
                            </item>
                        </items>
                    </custom>
                </customs>
            </presentation>
        </class>
    </classes>
    <meta>
        <presentation>
            <customs>
                <custom id="webhook-action-slack">
                    <description><![CDATA[Will be used by the "Slack notification" Action to display the corresponding attributes in the Slack message. Refer to the "Webhooks integration" extension documentation for more information.]]></description>
                </custom>
            </customs>
        </presentation>
    </meta>
</itop_design>
```

**Needs to be done**
  * [ ] Discuss what we cant to do in XML conversion methods (iTopDesignFormat)
    * Add empty <custom_presentations/> to all XML classes being converted to XML v3.1?
      * Con: Would not allow an extension compatible with iTop 2.7+ (XML v1.7) to have the custom zlist already present in its XML but used only in iTop 3.1+. possible use case would be something like:
         ```
         // First try to get items from custom zlist
         $aItems = MetaModel::GetZlistItems($sClass, 'my-list');
         // If not present, fallback on a standard one
         if (count($aItems) === 0) {
           $aItems = MetaModel::GetZlistItems($sClass, 'list');
         }
         ```
  * [ ] Add unit tests for XML conversion methods
  * [ ] Add unit tests for custom zlists declarations

2023-01-18 06:01 UTC, Hipska commented
Not “customs”. As said that’s a totally different thing. (Douane)

2023-01-18 09:03 UTC, Molkobain commented
> Not “customs”. As said that’s a totally different thing. (Douane)

It already "custom_presentations" if you look at the code, just forgot to update the description. Thanks 😁

2023-01-18 09:09 UTC, Hipska approved these changes
Looks good, I just don't think it's needed to be added on every class already? Doesn't harm either anyway..

2023-01-20 16:34 UTC, Molkobain commented
> Looks good, I just don't think it's needed to be added on every class already? Doesn't harm either anyway..

Yeah, that was reverted. I don't recall why we said it should be in the first place 😅

2023-01-20 16:46 UTC, Hipska approved these changes

2023-01-20 16:46 UTC, Hipska commented on setup/itopdesignformat.class.inc.php
> +		$this->RemoveNodeFromXPath("/itop_design/classes//class/presentation/custom_presentations");
The item above only has 1 / between `classes` and `class`. Typo?

2023-01-20 16:46 UTC, Hipska commented on setup/compiler.class.inc.php
> +		}
Strange, a method named `GetXXXAsArray` not returning an array?

2023-01-20 17:45 UTC, Molkobain commented on setup/compiler.class.inc.php
> +		}
Yeah... Check the method documentation / implementation. it can return a string 😕

2023-01-20 17:47 UTC, Molkobain commented on setup/itopdesignformat.class.inc.php
> +		$this->RemoveNodeFromXPath("/itop_design/classes//class/presentation/custom_presentations");
The item above should be fixed (and has actually been fixed in the develop branch with 8e3bad11ae7bd6ae580a4cfbebce5c0b801b54a3). The double slash is there because in some contexts the classes can be represented as a tree, not flatten.

2023-01-24 09:29 UTC, piRGoif requested changes
Indeed missing tests ;)
You could add easily the code for the XML migration methods as a start ?

2023-01-24 09:29 UTC, piRGoif commented on setup/compiler.class.inc.php
> +			if (false === in_array($sListCode, $this->aCustomListsCodes)) {
Might log a warning if there is a duplicate id ?

2023-01-24 09:49 UTC, Molkobain commented on setup/compiler.class.inc.php
> +			if (false === in_array($sListCode, $this->aCustomListsCodes)) {
Why? A same custom list ID can be defined in 2 classes.

2023-01-24 09:50 UTC, Molkobain commented
> Indeed missing tests ;) You could add easily the code for the XML migration methods as a start ?

Yes, it's in the checklist at the bottom of the description and why the PR is still in draft.
Why the "requested changes"?

2023-01-24 09:53 UTC, piRGoif commented
> Why the "requested changes"?
Because of missing tests :D But yes your pr is in draft, I should have added simple comments instead of a review.

2023-01-24 09:55 UTC, piRGoif commented on setup/compiler.class.inc.php
> +			if (false === in_array($sListCode, $this->aCustomListsCodes)) {
Well I was thinking of multiple declarations of the same custom id on the same class... but actually the compiler should already deal with that thanks to the _delta standard processing. 
Closing conversation, sorry for the noise :/

2023-02-08 18:24 UTC, Molkobain commented
_As discussed in the original PR (#100), this was already accepted during functional review. Only technical review is necessary._

2023-02-08 19:35 UTC, Hipska approved these changes

2023-02-13 13:37 UTC, Molkobain commented
Accepted during technical review.

2023-02-13 15:13 UTC, merged