N°5929 - Update hungarian translations thanks to @tacsaby
Combodo/iTop pull request #438
Opened 2023-01-26 13:45 UTC by Hipska

> Full hungarian translation

Thanks @tacsaby, the @Combodo team will close  your PRs:

closes #395
closes #396
closes #397
closes #398
closes #399
closes #400
closes #401
closes #402
closes #403
closes #404
closes #405
closes #406
closes #407
closes #408
closes #409
closes #410
closes #411
closes #412
closes #413
closes #414
closes #415
closes #417
closes #418
closes #419
closes #420
closes #421
closes #422
closes #423
closes #424
closes #425
closes #426
closes #427
closes #428
closes #429
closes #430
closes #431
closes #432
closes #433
closes #434
closes #435
closes #436
closes #437

2023-01-26 13:46 UTC, piRGoif commented
Thank you very much Thomas !

2023-01-26 13:54 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
> +	'Attachment:Max_Ko' => '(Maximum fájlméret: %1$s Ko)',
@tacsaby do you use "o" for "octets" in hungarian or "B" for "bytes" like in english?

2023-01-26 13:56 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
@tacsaby can this one be translated to "Ütemezett Backup" as well? If so, I can apply the correction directly.

```suggestion
	'bkp-status-title' => 'Ütemezett Backup',
```

2023-01-26 13:56 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
> +	'bkp-name-sample' => 'A backup fájlok neve a DB azonosítóktól, a dátumtól és az időponttól függ. Példa: %1$s~~',
```suggestion
	'bkp-name-sample' => 'A backup fájlok neve a DB azonosítóktól, a dátumtól és az időponttól függ. Példa: %1$s',
```

2023-01-26 13:57 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
> +	'bkp-name-sample' => 'A backup fájlok neve a DB azonosítóktól, a dátumtól és az időponttól függ. Példa: %1$s~~',
@Hipska I can't apply the suggestion. is it because the "allow maintainers to edit" isn't checked?

2023-01-26 13:58 UTC, Molkobain commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:Change:Overview+' => '~~',
```suggestion
	'Menu:Change:Overview+' => '',
```

2023-01-26 13:58 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
> +	'bkp-name-sample' => 'A backup fájlok neve a DB azonosítóktól, a dátumtól és az időponttól függ. Példa: %1$s~~',
Could be that it wasn't checked when creating the PR. It's not possible to check or change this afterwards.

2023-01-26 14:13 UTC, Molkobain requested changes

2023-01-26 14:13 UTC, Molkobain commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:Change:Shortcuts+' => '~~',
```suggestion
	'Menu:Change:Shortcuts+' => '',
```

2023-01-26 14:13 UTC, Molkobain commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:WaitingAcceptance+' => '~~',
```suggestion
	'Menu:WaitingAcceptance+' => '',
```

2023-01-26 14:13 UTC, Molkobain commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:WaitingApproval+' => '~~',
```suggestion
	'Menu:WaitingApproval+' => '',
```

2023-01-26 14:13 UTC, Molkobain commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:MyChanges+' => 'Changes assigned to me (as Agent)~~',
@tacsaby Is this change wanted?

2023-01-26 14:13 UTC, Molkobain commented on datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
> + */A
```suggestion
 */
```

2023-01-26 15:23 UTC, tacsaby commented on datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
> +	'Attachment:Max_Ko' => '(Maximum fájlméret: %1$s Ko)',
Oh,
yes Bytes are better 
GB, MB, KB

2023-01-26 15:26 UTC, tacsaby commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
I missed this...
'Ütemezett backup-ok'     is the correct sentence.
Thanks!

2023-01-26 15:28 UTC, tacsaby commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +	'Menu:MyChanges+' => 'Changes assigned to me (as Agent)~~',
I cannot see there any hungarian phrases. Sure not...
Thanks!

2023-01-26 15:34 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
> +	'Attachment:Max_Ko' => '(Maximum fájlméret: %1$s Ko)',
```suggestion
	'Attachment:Max_Go' => '(Maximum fájlméret: %1$s GB)',
	'Attachment:Max_Mo' => '(Maximum fájlméret: %1$s MB)',
	'Attachment:Max_Ko' => '(Maximum fájlméret: %1$s KB)',
```

2023-01-27 15:32 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
So like this?
```suggestion
	'bkp-status-title' => 'Ütemezett backup-ok',
```

2023-01-27 15:35 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
Doesn't seem right, this is the title of the page, the "ok" should not be there right? It's not a status return message

2023-01-27 15:40 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
It seems like `-ok` is Hungarian for words in plural. But asking this confirmation from @tacsaby to be sure..

2023-01-27 15:44 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
My bad then 😅😬

2023-01-30 15:54 UTC, Molkobain commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
>  	'bkp-status-title' => 'Scheduled Backups~~',
You can apply your last suggestion Thomas as it was the suggestion from tacsaby. Then I can move this PR forward.

2023-01-30 15:55 UTC, Molkobain commented on datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
> +	'Attachment:Max_Ko' => '(Maximum fájlméret: %1$s Ko)',
Could you also merge this one? Tacsaby replied it should be using Bytes.

2023-01-30 16:15 UTC, merged

2023-01-30 16:15 UTC, Molkobain commented
Thanks to both of you @tacsaby / @Hipska 🙌

2023-01-30 16:19 UTC, Molkobain commented on dictionaries/ui/layouts/page-content/hu.dictionary.itop.page-content.php
> -]);
Parsing error due to missing end of array. Fix in progress.

2023-01-30 16:22 UTC, Molkobain commented on dictionaries/ui/layouts/page-content/hu.dictionary.itop.page-content.php
> -]);
Fixed in 002e52cc