N°5993 - Add purge mechanism to log system
Combodo/iTop pull request #447
Opened 2023-02-16 08:20 UTC by bdalsass

Add purge mechanism:

If `log_purge_enable `is set to true, clean log folder by deleting files with last modification time older than `log_purge_max_keep_daysdays`.

- Add 2 new configuration parameters: log_purge_enable, log_purge_max_keep_days.
- Add purge process to log rotating scheduled task

2023-02-16 09:27 UTC, Hipska commented on core/config.class.inc.php
> +		],
Would it make sense to enable this by default? Or at least show the option in the config file, as that will make it easier to enable.

2023-02-16 09:37 UTC, Hipska commented on core/log.class.inc.php
> +			$this->PurgeLogs();
Nothing is done with the returned `$aFilesResult`. Intentional?

2023-02-16 09:53 UTC, Molkobain requested changes

2023-02-16 09:53 UTC, Molkobain commented on core/config.class.inc.php
> +		'log_purge_enable'                   => [
```suggestion
		'log_purge_enabled'                   => [
```

Preterit form is used in all params, I would like to keep the consistency.

2023-02-16 09:53 UTC, Molkobain commented on core/log.class.inc.php
> +	public const ENUM_CONFIG_PARAM_PURGE_ENABLE = 'log_purge_enable';
```suggestion
	public const ENUM_CONFIG_PARAM_PURGE_ENABLED = 'log_purge_enabled';
```

2023-02-16 09:53 UTC, Molkobain commented on core/log.class.inc.php
> +		if (MetaModel::GetConfig()->Get(LogAPI::ENUM_CONFIG_PARAM_PURGE_ENABLE)) {
```suggestion
		if (MetaModel::GetConfig()->Get(LogAPI::ENUM_CONFIG_PARAM_PURGE_ENABLED)) {
```

2023-02-16 09:53 UTC, Molkobain commented on core/log.class.inc.php
> +	 * @return array process feedback
```suggestion
	 * @return array process feedback
	 * @since 3.1.0
```

2023-02-16 09:53 UTC, Molkobain commented on core/log.class.inc.php
> +	 * files that haven't modifications since ENUM_CONFIG_PARAM_PURGE_MAX_KEEP_DAYS
```suggestion
	 * files that haven't modifications since {@see \LogAPI::ENUM_CONFIG_PARAM_PURGE_MAX_KEEP_DAYS}
```

2023-02-16 09:53 UTC, Molkobain commented on core/log.class.inc.php
> +			$this->PurgeLogs();
+1, seems like the errors are not output anywhere.

2023-02-16 10:11 UTC, bdalsass commented on core/log.class.inc.php
> +			$this->PurgeLogs();
This method can be accessed by the future log center module controller. (I actually work on it)
It will allow to trigger the purge manually and see the purge result client side.
I check with product team to ensure it makes sense.

2023-02-16 10:17 UTC, bdalsass commented on core/config.class.inc.php
> +		],
I check with product team.

2023-02-16 10:20 UTC, bdalsass commented on core/log.class.inc.php
> +			$this->PurgeLogs();
Also, i will output the JSON representation in a info log entry.

2023-02-23 11:28 UTC, piRGoif commented
Hello,

Before doing a review I have some questions on the basics : 

* why adding the purge inside the existing LogFileRotationProcess and not in a dedicated iScheduledProcess impl ?
* isn't a single log_purge_max_keep_days config param would be enough ? If value is anything else than a positive integer > 0 then purge will be done, else nothing happens ?

2023-03-06 14:02 UTC, bdalsass commented on core/config.class.inc.php
> +		],
The log_purge_enable initial value will be set to false to keep the system iso functional.
The show_in_conf_sample will be set to false to be homogeneous with other logs settings.

2023-03-06 14:06 UTC, bdalsass commented
> 



> 

The process is very closed to the file rotating background process, so we have decided to keep the 2 tasks together.
Having 2 parameters allows to disable the purge without loosing the max_keep_days value.

2023-03-06 14:25 UTC, merged

2023-03-06 17:09 UTC, piRGoif commented
No time to do a review :(

2023-03-06 17:32 UTC, Molkobain commented
> No time to do a review :(

Recent changes (76f667b) have been reviewed by 3 people already

2023-03-07 09:10 UTC, Hipska commented on core/config.class.inc.php
> +		],
Meh 👎

2023-03-07 09:10 UTC, Hipska commented
1 with comments, 1 with requesting changes and the last one is a pending review. I don't think that counts 🙂

2023-03-07 12:30 UTC, Molkobain commented
> > No time to do a review :(
> 
> Recent changes ([76f667b](https://github.com/Combodo/iTop/commit/76f667b1bd093ac988aaf80de194eb55f036f63a)) have been reviewed by 3 people already

> 1 with comments, 1 with requesting changes and the last one is a pending review. I don't think that counts 🙂

I meant reviewed IRL

2023-03-07 13:47 UTC, Hipska commented
Why creating public pull requests if they are reviewed discussed internally/privately?

2023-03-07 14:07 UTC, Molkobain commented
We already had that conversation [here](https://github.com/Combodo/iTop/pull/383#issuecomment-1369060827)

2023-03-07 18:01 UTC, piRGoif commented
> Recent changes have been reviewed by 3 people already

Next time, please make it implicit by adding a comment before merging O:)

> Why creating public pull requests if they are reviewed discussed internally/privately?

Pull request are a very good tool for review, but there aren't any mean to make them private.

2023-03-09 10:08 UTC, Hipska commented
@Molkobain Yes, and I still stand on the same point. The discussion ended in silence.

@piRGoif Yes, there are many ways: https://github.com/Combodo/iTop/pull/383#issuecomment-1375286918

2023-03-09 13:07 UTC, piRGoif commented
To my knowledge, private forks on public repo can only be created in a security advisory draft ? 
But anyway, that would be very costly either on merging complexity and team productivity. I wouldn't consider this technique as a valid option.

2023-03-09 18:35 UTC, Molkobain commented
> @Molkobain Yes, and I still stand on the same point. The discussion ended in silence.

> To my knowledge, private forks on public repo can only be created in a security advisory draft ? But anyway, that would be very costly either on merging complexity and team productivity. I wouldn't consider this technique as a valid option.

Exactly, that's why for me the discussion was closed on that matter for now. Especially as we stated the criteria that allow you to know if a PR is strictly internal or public.

These criteria could be communicated for widely I agree or we could find a way to flag internal PRs but we won't set a secondary repo just for that it's too much overhead regarding the benefits and our workforce.

Among possible way to flag PRs:
  * Dedicated GiHub project for public PRs (always the case, but we could rename it) and dedicated GitHub project for internal PRs.
  * Prefix on PRs' title
  * Add a "Private" label on these PRs

_But I don't thuink this PR is not the place to have this conversation._

2023-03-10 08:35 UTC, Hipska commented
So where can we discuss this? (Preferably in public so other community members can join) Or will we end again in silence?

2023-03-10 09:06 UTC, Molkobain commented
I don't know, Slack may be the best place as people on SF don't really come here for PRs.