Feature/4762 menucompilation
Combodo/iTop pull request #451
Opened 2023-03-02 08:04 UTC by odain-cbd

When menus are reworked (moved/deleted) somehow via XML customization, setup can still work successfully and you get an iTop broken with white page and empty menus. This PR aims at fixing such usecases.

Example:
setup algorithm is meant to generate model_XXX.php files one after the other in the order of module dependencies. this PHP generated files contain menu/menu group declarations. if you rebrand the menus,  a menu group defined in module 1 could be removed by XML customization. where as it is required for module2 as there are menu leafs linked to the removed menu group. when loading iTop page you get error messages like this on any module file (not specifically itop-stucture):

![image](https://user-images.githubusercontent.com/56586767/222367820-80c57c09-95b5-49ec-be1a-997117b9505d.png)

 

a menu group is

2023-03-06 08:12 UTC, Molkobain commented
(I see this is still in draft, let us know when it's ready for review)

2023-03-06 16:31 UTC, odain-cbd commented
it is not draft anymore

2023-03-30 08:31 UTC, Molkobain requested changes
Appart from the

2023-03-30 08:31 UTC, Molkobain commented on application/menunode.class.inc.php
> +				if (is_array($aSubMenuNodes) && 0 === sizeof($aSubMenuNodes)){
```suggestion
				if (is_array($aSubMenuNodes) && 0 === count($aSubMenuNodes)){
```

Usage of `count()` if prefered over `sizeof()` as the later as a different meaning in other languages so it avoids confusion. Also it's an alias of `count()` so it might be deprecated.

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> + * @since 3.1 N°4762
```suggestion
 * @since 3.1.0 N°4762
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var MFCompiler */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Admin menus declaration lines: result of module menu compilation */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Non-admin menus declaration lines: result of module menu compilation */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Use to handle menu group compilation recurring algorithm */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Used by overall algo */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Used by new algo */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 */
```suggestion
	/** @var array Used by overall algo */
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 * Initialize menu nodes arrays
```suggestion
	 * Initialize menu nodes arrays
	 * @param \ModelFactory $oFactory
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	 * Initialize arrays related to parent/child menus
```suggestion
	 * Initialize arrays related to parent/child menus
	 * @param $aModules
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	public function GetMenusByModule(string $sModuleName) : ?array
```suggestion
	public function GetMenusByModule(string $sModuleName): ?array
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	public function CompileParentMenuNode(string $sMenuId, $sTempTargetDir, $sFinalTargetDir, $sRelativeDir, $oP = null) : void
```suggestion
	public function CompileParentMenuNode(string $sMenuId, $sTempTargetDir, $sFinalTargetDir, $sRelativeDir, $oP = null): void
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	public function CompileModuleMenus(MFModule $oModule, $sTempTargetDir, $sFinalTargetDir, $sRelativeDir, $oP = null) : void
```suggestion
	public function CompileModuleMenus(MFModule $oModule, $sTempTargetDir, $sFinalTargetDir, $sRelativeDir, $oP = null): void
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	public function LoadModuleMenuInfo($aModules) : void
```suggestion
	public function LoadModuleMenuInfo($aModules): void
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +	public function LoadXmlMenus(\ModelFactory $oFactory) : void {
```suggestion
	public function LoadXmlMenus(\ModelFactory $oFactory): void {
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +						if ($oMenuNode->getAttribute("xsi:type") == 'MenuGroup') {
```suggestion
						if ($oMenuNode->getAttribute("xsi:type") === 'MenuGroup') {
```

2023-03-30 08:31 UTC, Molkobain commented on setup/parentmenunodecompiler.class.inc.php
> +				if ($oMenuNode->getAttribute("xsi:type") == 'MenuGroup') {
```suggestion
				if ($oMenuNode->getAttribute("xsi:type") === 'MenuGroup') {
```

2023-03-30 09:29 UTC, Hipska approved these changes

2023-03-31 13:22 UTC, Molkobain approved these changes

2023-03-31 13:23 UTC, Molkobain commented
All good for me, you can "squash & merge", please ensure that the commit is named "N°4762 - Designer customization of menus moved in itop-structure crashs in iTop 3.0 (#451)" as it sometimes use the old PR's title.

2023-10-31 11:14 UTC, Molkobain commented
Discussed with Olivier, this was done in // of N°5085 ([2b84c03](https://github.com/Combodo/iTop/commit/2b84c0384d9a1da6964a6f6ef5199c262720d935)) by Benjamin, so it should no longer be necessary. This is fix is merged in the SaaS branch though, so we close this PR for now, but it might be re-opened in the future if the SaaS finds out that N°5085 didn't fix all of it.

2023-10-31 11:14 UTC, closed without merging