N°541 - GraphBar labels too long: unreadable >> increase chart size
Combodo/iTop pull request #452
Opened 2023-03-02 10:59 UTC by accognet

For bar chart: set chart size depending on label size
For pie chart : increase the size of the chart proportionnaly to number of labels if there are more than 50 labels in the legend

2023-04-04 15:33 UTC, Molkobain requested changes

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +						$iMaxNbCharInLabel = strlen($sValue);
```suggestion
					if ($iMaxNbCharInLabel < strlen($sValue)) {
						$iMaxNbCharInLabel = strlen($sValue);
```

Rather use [mb_strlen](https://www.php.net/manual/fr/function.mb-strlen.php) to ensure it works as expected with non latin alphabets.

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +var iSizeOfChar = (200 + 6 * $iMaxNbCharInLabel);
Add comment to explain the calculation

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +$('#my_chart_$sId').height(iSizeOfChar + 'px');
```suggestion
var iChartHeight = (200 + 6 * $iMaxNbCharsInLabel);
$('#my_chart_$sId').height(iChartHeight + 'px');
```

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +				$iMaxNbCharInLabel = 0;
```suggestion
				$iMaxNbCharsInLabel = 0;
```

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +						$iMaxNbCharInLabel = strlen($sValue);
```suggestion
					if ($iMaxNbCharsInLabel < strlen($sValue)) {
						$iMaxNbCharsInLabel = strlen($sValue);
```

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					$iNbLineToAddForName = ceil ( count($aNames) / 5) - 10;
```suggestion
				$iNbLinesToAddForName = 0;
				if (count($aNames) > 50) {
					// Increase size of the graph in order to have a maximum of 5 columns of legend
					$iNbLinesToAddForName = ceil(count($aNames) / 5) - 10;
```

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					$iNbLineToAddForName = ceil ( count($aNames) / 5) - 10;
Add comment to explain the calculation

2023-04-04 15:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +$('#my_chart_$sId').height(iSizeOfChar + 'px');
```suggestion
var iChartHeight = (200 + 20 * $iNbLinesToAddForName);
$('#my_chart_$sId').height(iChartHeight + 'px');
```

2023-04-04 15:34 UTC, Molkobain commented
Accepted during technical review once changes have been made.

2023-04-07 20:33 UTC, Molkobain approved these changes

2023-04-07 20:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +				$iMaxNbCharsInLabel = 0;
```suggestion
				$iMaxNbCharsInLabel = 0;
				
```

2023-04-07 20:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +					if ($iMaxNbCharsInLabel < mb_strlen($sValue)) {
```suggestion

					if ($iMaxNbCharsInLabel < mb_strlen($sValue)) {
```

2023-04-07 20:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +//calculate height of chart : 200px (height of the chart) + 6*iMaxNbCharsInLabel for the legend
```suggestion
// Calculate height of chart : 200px (height of the chart) + 6*iMaxNbCharsInLabel for the legend
```

2023-04-07 20:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +//calculate height of graph : 200px (minimum height for the chart) + 20*iNbLinesToAddForName for the legend
```suggestion
// Calculate height of graph : 200px (minimum height for the chart) + 20*iNbLinesToAddForName for the legend
```

2023-04-07 20:33 UTC, Molkobain commented on application/displayblock.class.inc.php
> +$('#my_chart_$sId').height(iHeightOfChar + 'px');
```suggestion
var iChartHeight = (200 + 6 * $iMaxNbCharsInLabel);
$('#my_chart_$sId').height(iChartHeight + 'px');
```

2023-04-11 10:06 UTC, piRGoif requested changes
As said during the review : inline comments can be lost easily after some modifications done to the code ! So it is a good practice to replace them with readable code when applicable.

Here we can introduce intermediate variables to explain the meaning of each block, so I would definitively prefer that : it will be far better in the long run, and even clearer for the developers.

2023-04-11 10:06 UTC, piRGoif commented on application/displayblock.class.inc.php
> +$('#my_chart_$sId').height(iChartHeight + 'px');
```suggestion
var iChartDefaultHeight = 200,
      iChartLegendHeight = 6 * $iMaxNbCharsInLabel,
      iChartTotalHeight = iChartDefaultHeight + iChartLegendHeight;
$('#my_chart_$sId').height(iChartTotalHeight+ 'px');
```

2023-04-11 10:06 UTC, piRGoif commented on application/displayblock.class.inc.php
> +					$iNbLinesToAddForName = ceil(count($aNames) / 5) - 10;
```suggestion
					// Calculation of the number of legends line add to the height of the graph to have a maximum of 5 legend columns
					$iNbLinesIncludedInChartHeight = 10;
					$iNbLinesToAddForName = ceil(count($aNames) / 5) - $iNbLinesIncludedInChartHeight;
```

2023-04-11 10:06 UTC, piRGoif commented on application/displayblock.class.inc.php
> +$('#my_chart_$sId').height(iChartHeight + 'px');
```suggestion
var iChartDefaultHeight = 200,
      iChartLegendHeight = 20 * $iNbLinesToAddForName,
      iChartTotalHeight = (200 + iChartLegendHeight);
$('#my_chart_$sId').height(iChartTotalHeight + 'px');
```

2023-04-11 15:25 UTC, piRGoif commented
Functional review : OK for 2.7
@accognet can you check my review before merging ?

2023-04-13 09:23 UTC, merged