N°6097 - Enable PHP unit tests on a custom DataModel
Combodo/iTop pull request #457
Opened 2023-03-13 10:50 UTC by Molkobain

_Internal PR_

**Objective**
Enable developers to add unit tests on DataModel elements that are not part of the standard DM (iTop Community), for example:
  * New attribute types that are not used yet
  * An AttributeExternalField pointing on a composite attribute (eg. an AttributeImage)

Being able to add these tests would increase confidence on core changes and their consequences on customizations in extensions / Designer.

**What it does**
  * Refactor existing test classes for better extensibility
  * Add a new `ItopCustomDatamodelTestCase` class for tests that need an XML delta

For each test class extending `ItopCustomDatamodelTestCase`, a temporary "php-unit-tests" environment is compiled from the current "production" environment and the XML delta. Then the tests are ran in that environment.

The main drawback of that approach is the compilation time for each class, but I don't really see another way to do it. So it would require to factorize as much as possible test cases in the same test class.

**What needs to be done**
  * [ ] Finish cleanup after tests are ran

**How to use it**
  * Extend `ItopCustomDatamodelTestCase`
  * Overload `ItopCustomDatamodelTestCase::GetDatamodelDeltaAbsPath()` method to specify your XML delta
  * Add your test cases

**Example**
_XML delta_
```xml
<?xml version="1.0" encoding="UTF-8"?>
<itop_design xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.1">
  <classes>
    <class id="Person">
      <fields>
        <field id="tested_attribute" xsi:type="AttributeString" _delta="define">
          <sql>tested_attribute</sql>
          <default_value/>
          <is_null_allowed>true</is_null_allowed>
        </field>
      </fields>
    </class>
  </classes>
</itop_design>
```

_Test class_
```php
namespace Combodo\iTop\Test\UnitTest\Core;

use Combodo\iTop\Test\UnitTest\ItopCustomDatamodelTestCase;
use DBObjectSet;
use DBSearch;
use MetaModel;

/**
 * Tests of the DBSearch class.
 * <ul>
 * <li>MakeGroupByQuery</li>
 * </ul>
 *
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 * @backupGlobals disabled
 */
class TestGLATest extends ItopCustomDatamodelTestCase
{
	/**
	 * @inheritDoc
	 */
	public function GetDatamodelDeltaAbsPath(): string
	{
		return APPROOT.'tests/php-unit-tests/unitary-tests/core/TestGLATest.delta.xml';
	}

	public function testFoo()
	{
		static::assertFalse(MetaModel::IsValidAttCode('Person', 'non_existing_attribute'));
		static::assertTrue(MetaModel::IsValidAttCode('Person', 'tested_attribute'));
	}
}
```

2023-03-13 13:19 UTC, Molkobain commented
Ready for discussion

2023-08-03 15:25 UTC, Molkobain commented
Ready for review @piRGoif @rquetiez ! 🙌

2023-08-07 10:13 UTC, piRGoif requested changes, later dismissed
Bravo for this great improvement !

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
> +	}
Why this method, instead of the existing setUp overrides ? 
To provide additional value, maybe have instead 2 methods, LoadRequiredItopFiles / LoadRequiredTestFiles, which would return a simple array ?

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopDataTestCase.php
> +	}
Having a method allows to create overrides in children classes to have the env name computed
But I'm not sure we need such customization for now ? To keep things simple, I would say just use the constant in PrepareEnvironment() ?

2023-08-07 10:13 UTC, piRGoif commented on application/utils.inc.php
> +		return APPROOT.'data/';
in approot we already have an APPCONF constant, maybe we can add an APPDATA constant and use it here ?

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +	}
We absolutely need to report this modification in ItopDataTestCase, so we can remove any annotations in its children classes !
Of course this is subject of another task, I've added N°6632 in our db.

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +	}
This is much alike \utils::GetCompiledEnvironmentPath
Maybe create \utils::GetEnvironmentPath with an env parameter, and use it here and in \utils::GetCompiledEnvironmentPath ?

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +	}
Again, simply overriding the DEFAULT_TEST_ENVIRONMENT would be enough

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +		// - a file generated at the beginning of the global test run {@see \Combodo\iTop\Test\UnitTest\Hook\TestsRunStartHook}
Pull up this in the method phpdoc block
Inline comments always get lost and have less visibility :/

2023-08-07 10:13 UTC, piRGoif commented on tests/php-unit-tests/src/Hook/TestsRunStartHook.php
> + * IMPORTANT: This will no longer in PHPUnit 10.0 and there is no alternative for now, so we will have to migrate it when the time comes
```suggestion
 * IMPORTANT: This will no longer work in PHPUnit 10.0 and there is no alternative for now, so we will have to migrate it when the time comes
```

2023-08-10 13:20 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
> +	}
Discussed IRL on tuesday, finally I kept the methods but separated it in 2.
Having the methods and calling the parent is less error prone than merging arrays IMO.

2023-08-10 13:21 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopDataTestCase.php
> +	}
Discussed IRL on tuesday, we keep the method.

2023-08-10 13:21 UTC, Molkobain commented on application/utils.inc.php
> +		return APPROOT.'data/';
Discussed IRL on tuesday, we keep the method as it is a utility of the utils class. Also, constants in approot.inc.php should only be what is strictly neccessary for the app as it is both its foundation and included in a lot of pages/scripts.

2023-08-10 13:22 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +	}
Discussed IRL on tuesday, method doesn't exists in support/2.7.

2023-08-10 13:22 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +	}
Done

2023-08-10 13:23 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
> +		// - a file generated at the beginning of the global test run {@see \Combodo\iTop\Test\UnitTest\Hook\TestsRunStartHook}
Discussed IRL on tuesday, method PHPDoc explains the purpose of the method itself and how it should be used / what to expect from it. This block of doc explains how / why we did it internally, it is not for the consumer but the futur maintainers.

2023-08-10 13:24 UTC, Molkobain commented on tests/php-unit-tests/src/Hook/TestsRunStartHook.php
> + * IMPORTANT: This will no longer in PHPUnit 10.0 and there is no alternative for now, so we will have to migrate it when the time comes
Done, thanks

2023-08-10 13:45 UTC, merged