updateLicenses : check availability of the JQ command which is required
Combodo/iTop pull request #458
Opened 2023-03-14 14:07 UTC by piRGoif

This packaging script requires both bash and the JQ command.
If the later isn't available, it will run without throwing an error...

With this change the script will now check directly at launch for the JQ command availability, and exit in error if it isn't.

2023-06-06 13:56 UTC, Molkobain requested changes

2023-06-06 13:56 UTC, Molkobain commented on .make/license/updateLicenses.php
> +	die - 1;
```suggestion
	die - 1;
```

Like for `exit()`, return code should be in parenthesis. I don't recall the symptom if we don't but we had similar issues with CLI scripts within the SaaS team if I recall correctly. Poke @odain-cbd

2023-06-06 14:05 UTC, Hipska commented on .make/license/updateLicenses.php
> +$jqExec = shell_exec("jq --help"); // --help param is mandatory otherwise the script will freeze
Or just `jq -V` or `which jq`?

2023-06-06 14:06 UTC, Hipska commented on .make/license/updateLicenses.php
> +	die - 1;
I also don't like this notation..

2023-06-06 15:13 UTC, piRGoif commented
Technical review : parenthesis on die call, plus check `jq -V`

2023-06-06 15:27 UTC, piRGoif commented on .make/license/updateLicenses.php
> +	die - 1;
Woops, thanks ! 
Fixed in 6b52da4d

2023-06-06 15:30 UTC, piRGoif commented on .make/license/updateLicenses.php
> +$jqExec = shell_exec("jq --help"); // --help param is mandatory otherwise the script will freeze
I like the `-V` param ! Implemented in 76450e8e
About which, I'm not sure it is widely available on Windows systems ?

2023-06-06 15:39 UTC, Hipska commented on .make/license/updateLicenses.php
> +$jqExec = shell_exec("jq --help"); // --help param is mandatory otherwise the script will freeze
On windows it would at least be `jq.exe`

2023-06-06 15:59 UTC, piRGoif commented on .make/license/updateLicenses.php
> +$jqExec = shell_exec("jq --help"); // --help param is mandatory otherwise the script will freeze
Calling a command without the extension works on Windows

2023-06-07 06:01 UTC, Molkobain approved these changes

2023-06-13 14:15 UTC, Molkobain commented
Accepted during functional review

2023-06-14 08:17 UTC, merged