N°7068 - Add emulation for apc_exists function
Combodo/iTop pull request #460
Opened 2023-03-20 16:54 UTC by Hipska

Since #201 wasn't accepted, we had a long time figuring out why a custom extension didn't work. It turned out APCu isn't available and the apc_exists method wasn't emulated in the apc-compat file caching replacement.

2023-05-08 09:02 UTC, Hipska commented
Any feedback?

2023-05-08 10:17 UTC, Hipska commented on core/apc-emulation.php
> +		else return is_file(self::GetCacheFileName($sKey));
Could also be rewritten as this if preferred:
```suggestion
		return is_file(apcFile::GetCacheFileName('-' . $sKey)) || is_file(apcFile::GetCacheFileName($sKey));
```

2023-06-13 11:08 UTC, Hipska commented
Anyone?

2023-06-28 17:29 UTC, Molkobain commented
Hello Thomas,

This might be reviewed next week. Can you provide the condition (system and functional) as well as the symptom so we can check on our end?

Thanks

2023-06-28 18:01 UTC, Hipska commented
As said, it was with a custom extension on a system without APCu. This fix did work perfectly on that system.

Calling apc_exists would fail if this fix is not applied.

2023-08-04 07:57 UTC, Hipska commented
@Molkobain was this also on the wrong dashboard column to be reviewed?

2023-08-04 07:59 UTC, piRGoif commented
We need a way to reproduce
You didn't provide a precise guide, so someone on Combodo side has to figure it out.

2023-08-04 08:01 UTC, Hipska commented
Oh, okay:
```php
var_dump(apc_exists('footer'));
```

2023-12-14 08:46 UTC, Molkobain commented
Discussed internally, ok for Eric and I.

2023-12-14 08:50 UTC, Molkobain approved these changes

2023-12-14 08:50 UTC, Molkobain commented on core/apc-emulation.php
> +			if (apcFile::ExistsOneFile($sKey)) $aExistingKeys[] = $sKey;
```suggestion
			if (apcFile::ExistsOneFile($sKey)) {
				$aExistingKeys[] = $sKey;
			}
```

2023-12-14 08:50 UTC, Molkobain commented on core/apc-emulation.php
> +	} else return apcFile::ExistsOneFile($keys);
```suggestion
	} else {
		return apcFile::ExistsOneFile($keys);
	}
```

2023-12-14 08:50 UTC, Molkobain commented on core/apc-emulation.php
> +		else return is_file(self::GetCacheFileName($sKey));
Yes please

2023-12-14 08:52 UTC, Molkobain requested changes
I accepted the PR as I thought I would be abble to apply the suggestion right away. As I'm unable to, I switch to "request changes"

2023-12-14 09:22 UTC, Hipska commented
Thanks, applied..

2023-12-14 09:42 UTC, Molkobain commented
Do you have a need for this to be in an older version of iTop (which one) ? So we can check if it's ok to retrofit during the next functional review.

2023-12-14 09:42 UTC, Molkobain approved these changes

2023-12-14 10:51 UTC, Hipska commented
I currently patched the iTop 3.0 on a setup where this was used. Would be nice to have it in the next 3.1 release?

2023-12-14 10:58 UTC, Molkobain commented
Alright, thanks for the feedback

2023-12-14 11:07 UTC, Molkobain commented
I don't know if you opened a ticket about this, but this is now referenced as N°7068.

2024-02-06 15:38 UTC, Molkobain commented
Accepted during technical review
  * Guillaume will create a modernization ticket to add all missing functions (eg. apc_add, apc_cas, apc_dec, ...)

2024-02-07 15:13 UTC, Molkobain commented
> * Guillaume will create a modernization ticket to add all missing functions (eg. apc_add, apc_cas, apc_dec, ...)

Ticket _N°7227 - APC: Complete emulated functions_

2024-02-13 20:13 UTC, Molkobain commented
Accepted during functional review.

2024-02-13 20:13 UTC, merged