Feature/6132 disabling tabs dynamically
Combodo/iTop pull request #470
Opened 2023-03-28 12:44 UTC by dflaven

2023-03-29 17:45 UTC, Molkobain requested changes

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +            disableTab: function(iIdx){
Rather pass the tab ID instead of its index (and `_getTabIndexFromTabId()`), it will improve the DX and the robustness.

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +            enableTab: function(iIdx){
Same comment as above

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +	enable: function(index) {
```suggestion
	// JQuery UI overload
	enable: function(index) {
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		panel.css({display: 'none'});
We rather use `.show()` / `.hide()` methods directly than CSS properties

```suggestion
		panel.hide();
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		panel.css({display: 'block'});
```suggestion
		panel.show();
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +               let tabElement = this._getTabElementFromTabIndex(iIdx);
We rather use `const` as the variable itself isn't supposed to be rewritten.

```suggestion
               const tabsWidget = this.GetTabsWidget();
               tabsWidget.disable(iIdx);
               const tabElement = this._getTabElementFromTabIndex(iIdx);
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +	enable: function(index) {
```suggestion
	// JQuery UI overload
	enable: function(index) {
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.css({display: 'none'});
Same comments as for regular-tabs.js

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.css({display: 'block'});
Same comments as for regular-tabs.js

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		let panel = this._getPanelForTab( index );
```suggestion
		const panel = this._getPanelForTab( index );
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		let panel = this._getPanelForTab( index );
```suggestion
		const panel = this._getPanelForTab( index );
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		let panel = this._getPanelForTab( this.tabs[index] );
```suggestion
		const panel = this._getPanelForTab( this.tabs[index] );
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		let panel = this._getPanelForTab( this.tabs[index] );
```suggestion
		const panel = this._getPanelForTab( this.tabs[index] );
```

2023-03-29 17:45 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +                }
Now that I've tried it in action, hiding the extra tab (drop down menu) when disabled feels clunking as the "normal" tab remains there. So when you resize your window or more probably when you resize the activity panel or modal the behavior is not natural.

I would rather keep it in the drop down menu with an `aria-disabled` propagated to it,
click interception and a CSS rule for the cursor.

2023-03-30 09:00 UTC, Hipska commented
Could someone elaborate what functionality this feature will enable?

2023-03-30 09:10 UTC, Molkobain commented
Enable / disable tabs of a panel in the backoffice through JS API (eg. "Impact analysis" on a "User request", or any tab of a panel for a specific use case)

2023-03-30 09:12 UTC, Hipska commented
With enable/disable you mean to hide it? Or just not clickable? What would be a scenario you have in mind to use this?

2023-03-30 09:18 UTC, Molkobain commented
> With enable/disable you mean to hide it? Or just not clickable?
The header would remain there but it would not be clickable.

> What would be a scenario you have in mind to use this?
Typically choosing an option in a tab would disable another tab.

2023-03-30 14:48 UTC, Molkobain approved these changes

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +                if (oTabHeaderElem.attr('aria-disabled') == 'true') {
```suggestion
                if (oTabHeaderElem.attr('aria-disabled') === 'true') {
```

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +            disableTab: function(sId){
```suggestion
            /**
             * @param sId {string} The [data-tab-id] of the tab
             * @return {Object} The jQuery object representing the tab element
             */
            disableTab: function(sId){
```

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +            enableTab: function(sId){
```suggestion
            /**
             * @param sId {string} The [data-tab-id] of the tab
             * @return {Object} The jQuery object representing the tab element
             */
            enableTab: function(sId){
```

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/tab-container.js
> +            _getTabElementFromTabId: function(sId) {
```suggestion
            /**
             * @param sId {string} The [data-tab-id] of the tab
             * @return {Object} The jQuery object representing the tab element
             *
             * @private
             */
            _getTabElementFromTabId: function(sId) {
```

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.css({display: 'none'});
```suggestion
		panel.hide();
```

2023-03-30 14:48 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.css({display: 'block'});
```suggestion
		panel.show();
```

2023-03-30 14:52 UTC, Molkobain commented
@dflaven I applied some code convention changes. Can you check that it still works? Then we can do the merge whenever you like (but we need to change the destination branch)

2023-04-04 08:16 UTC, Molkobain requested changes
Rather use `this.css_classes.is_hidden`, this allows better robustness if you change the classes name in the future.

Also beware when we merge the PR, it will be into support/3.0, not support/3.0.2

2023-04-04 08:16 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		panel.addClass('ibo-is-hidden'); // Do not use .hide() since it alters the tab state
```suggestion
		panel.addClass(this.css_classes.is_hidden); // Do not use .hide() since it alters the tab state
```

2023-04-04 08:16 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		panel.removeClass('ibo-is-hidden'); // Do not use .show() since it alters the tab state
```suggestion
		panel.removeClass(this.css_classes.is_hidden); // Do not use .show() since it alters the tab state
```

2023-04-04 08:16 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.addClass('ibo-is-hidden'); // Do not use .hide() since it alters the tab state
```suggestion
		panel.addClass(this.css_classes.is_hidden); // Do not use .hide() since it alters the tab state
```

2023-04-04 08:16 UTC, Molkobain commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.removeClass('ibo-is-hidden'); // Do not use .show() since it alters the tab state
```suggestion
		panel.removeClass(this.css_classes.is_hidden); // Do not use .show() since it alters the tab state
```

2023-04-06 09:37 UTC, dflaven commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.removeClass('ibo-is-hidden'); // Do not use .show() since it alters the tab state
As far as I can see, there is no this.css_classes in the widgets scrollable-tabs and regular tabs, css classes (ui-*) are hard-coded al over the place in the code of the widget.

2023-04-06 09:37 UTC, dflaven commented on js/layouts/tab-container/scrollable-tabs.js
> +		panel.addClass('ibo-is-hidden'); // Do not use .hide() since it alters the tab state
As far as I can see, there is no this.css_classes in the widgets scrollable-tabs and regular tabs, css classes (ui-*) are hard-coded al over the place in the code of the widget.

2023-04-06 09:37 UTC, dflaven commented on js/layouts/tab-container/regular-tabs.js
> +		panel.removeClass('ibo-is-hidden'); // Do not use .show() since it alters the tab state
As far as I can see, there is no this.css_classes in the widgets scrollable-tabs and regular tabs, css classes (ui-*) are hard-coded al over the place in the code of the widget.

2023-04-06 09:49 UTC, Molkobain commented on js/layouts/tab-container/regular-tabs.js
> +		panel.removeClass('ibo-is-hidden'); // Do not use .show() since it alters the tab state
Discussed IRL with Denis, the 2 widgets don't inherit from the tab-container widget and thus don't have these options.

2023-04-06 10:12 UTC, Molkobain approved these changes

2023-04-06 10:12 UTC, merged