Update hu.dictionary.itop.ui.php
Combodo/iTop pull request #472
Opened 2023-03-28 14:04 UTC by tacsaby

Some corrections

2023-03-28 14:05 UTC, tacsaby commented
Please update translation by recent changes! Thanks!

2023-03-29 07:49 UTC, piRGoif commented
Hello,
I see you emptied lots of "+" dict entries. Can you explain why ? 
Also lots of apos were removed around parameters, for example on `Class:User/Error:LoginMustBeUnique`. They are present in other languages, why should they be removed in HU ?

2023-06-06 13:20 UTC, piRGoif commented
Hello @tacsaby , any news ?

2023-06-07 21:51 UTC, tacsaby commented
Hello,

I removed some "+" dict entries because it was trivial in my language,
makes not sense to describe it more.
Don't know why, but if parameters in " double quotes, the values of
parameter not printed, but the name of parameter.  This is not desirable.
I wait a little with sending all my translations, if the new translation
app released.
I have problems to commit translation on github, because that not familiar
to me and you don't like the method that i can do that.


Pierre Goiffon ***@***.***> ezt írta (időpont: 2023. jún. 6.,
K 15:20):

> Hello @tacsaby <https://github.com/tacsaby> , any news ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Combodo/iTop/pull/472#issuecomment-1578756939>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU2J7G44IOTRD25O3EZEFDTXJ4VBNANCNFSM6AAAAAAWKT6DUE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-13 11:02 UTC, Hipska requested changes

2023-06-13 11:02 UTC, Hipska commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:AuditCategory/Attribute:rules_list+' => '',
So you are saying it does not make sense to have a description (or even a translated description) for this list in your language?

2023-06-13 11:02 UTC, Hipska commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Error:ProfileNotAllowed' => 'A %1$s profil nem adható hozzá, le lesz tiltva',
Double quotes in single quotes should just work. Please revert this change. (and all others)

2023-06-13 13:26 UTC, Molkobain requested changes

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:AuditCategory/Attribute:rules_list+' => '',
```suggestion
    'Class:AuditCategory/Attribute:rules_list+' => 'Audit rules for this category~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:Query+' => '',
```suggestion
    'Class:Query+' => 'A query is a data set defined in a dynamic way~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:Query/Attribute:name+' => '',
```suggestion
    'Class:Query/Attribute:name+' => 'Identifies the query~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:Query/Attribute:description+' => '',
```suggestion
    'Class:Query/Attribute:description+' => 'Long description for the query (purpose, usage, etc.)~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:Query/Attribute:is_template+' => '',
```suggestion
    'Class:Query/Attribute:is_template+' => 'Usable as source for recipient OQL in Notifications~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:QueryOQL/Attribute:fields+' => '',
```suggestion
    'Class:QueryOQL/Attribute:fields+' => 'Comma separated list of attributes (or alias.attribute) to export~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:QueryOQL+' => '',
```suggestion
    'Class:QueryOQL+' => 'A query based on the Object Query Language~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Attribute:profile_list+' => '',
```suggestion
    'Class:User/Attribute:profile_list+' => 'Roles, granting rights for that person~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Attribute:allowed_org_list+' => '',
```suggestion
    'Class:User/Attribute:allowed_org_list+' => 'The end user is allowed to see data belonging to the following organizations. If no organization is specified, there is no restriction.~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Attribute:status+' => '',
```suggestion
    'Class:User/Attribute:status+' => 'Whether the user account is enabled or disabled.~~',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Error:LoginMustBeUnique' => 'A felhasználónévnek egyedinek kell lennie - %1s már létezik.',
```suggestion
    'Class:User/Error:LoginMustBeUnique' => 'A felhasználónévnek egyedinek kell lennie - "%1s" már létezik.',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'Class:User/Error:ProfileNotAllowed' => 'A %1$s profil nem adható hozzá, le lesz tiltva',
```suggestion
    'Class:User/Error:ProfileNotAllowed' => 'A "%1$s" profil nem adható hozzá, le lesz tiltva',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Error:UnsupportedStyleOfBlock' => 'Hiba: nem támogatott stílus tömb: %1$s.',
```suggestion
    'UI:Error:InvalidGroupByFields' => 'Csoportosításnál használt érvénytelen mezők: "%1$s".',
    'UI:Error:UnsupportedStyleOfBlock' => 'Hiba: nem támogatott stílus tömb: "%1$s".',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Error:UploadFailedUnknownCause_Code' => 'Fájl feltöltés sikertelen ismeretlen hiba miatt. (Hibakód = %1$s).',
```suggestion
    'UI:Error:CannotWriteToTmp_Dir' => 'Az átmeneti fájl nem írható. upload_tmp_dir = "%1$s".',
    'UI:Error:UploadStoppedByExtension_FileName' => 'Feltöltés megállt a fájl kiterjesztés miatt. (Eredeti fájl név = "%1$s").',
    'UI:Error:UploadFailedUnknownCause_Code' => 'Fájl feltöltés sikertelen ismeretlen hiba miatt. (Hibakód = "%1$s").',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Error:Invalid_Stimulus_On_Object_In_State' => 'Hiba: érvénytelen stimulus %1$s a következő objektum %2$s következő állapotában %3$s.',
```suggestion
    'UI:Error:Invalid_Stimulus_On_Object_In_State' => 'Hiba: érvénytelen stimulus "%1$s" a következő objektum %2$s következő állapotában "%3$s".',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:ResetPwd-Error-WrongLogin' => '%1$s nem érvényes fiók',
```suggestion
    'UI:ResetPwd-Error-WrongLogin' => '\'%1$s\' nem érvényes fiók',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:CSVImport:ErrorExtendedAttCode'            => 'Belső hiba: %1$s nem megfelelő kód, mert %2$s nem külső kulcsa a %3$s osztálynak',
```suggestion
    'UI:CSVImport:ErrorExtendedAttCode'            => 'Belső hiba: "%1$s" nem megfelelő kód, mert "%2$s" nem külső kulcsa a "%3$s" osztálynak',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:CSVReport-Value-NoMatch' => 'Nincs egyezés a %1$s értékhez',
```suggestion
    'UI:CSVReport-Value-ChangeIssue' => '\'%1$s\' egy érvénytelen érték',
    'UI:CSVReport-Value-NoMatch' => 'Nincs egyezés a \'%1$s\' értékhez',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:CSVReport-Value-Issue-Readonly' => 'A %1$s attribútum csak olvasható (jelenlegi érték: %2$s, várható érték: %3$s)',
```suggestion
    'UI:CSVReport-Value-Issue-Readonly' => 'A \'%1$\'s attribútum csak olvasható (jelenlegi érték: %2$s, várható érték: %3$s)',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:CSVReport-Value-Issue-Unknown' => 'A %1$s attribútum nem várt értéket kapott: %2$s',
```suggestion
    'UI:CSVReport-Value-Issue-NoMatch' => 'A \'%1$s\' attribútum nem várt értéket kapott: nincs egyezés, ellenőrizze a beírást',
    'UI:CSVReport-Value-Issue-Unknown' => 'A \'%1$s\' attribútum nem várt értéket kapott: %2$s',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Schema:Default_Description' => 'Alapértelmezett: %1$s',
```suggestion
    'UI:Schema:Default_Description' => 'Alapértelmezett: "%1$s"',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Schema:DefaultNullValue' => 'Alapértelmezett null érték : %1$s',
```suggestion
    'UI:Schema:DefaultNullValue' => 'Alapértelmezett null érték : "%1$s"',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:Search:Ongoing' => '%1$s keresése',
```suggestion
    'UI:Search:NeedleTooShort' => 'A \\"%1$s\\" kereső karakterlánc túl rövid. Legalább %2$d karaktert írjon be.',
    'UI:Search:Ongoing' => '\\"%1$s\\" keresése',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:FullTextSearchTitle_Text' => '%1$s keresés eredményei:',
```suggestion
    'UI:FullTextSearchTitle_Text' => '"%1$s" keresés eredményei:',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:OQL:UnknownClassNoFix' => 'Ismeretlen osztály: %1$s',
```suggestion
    'UI:OQL:UnknownClassAndFix' => 'Ismeretlen osztály: \\"%1$s\\". Próbálja meg \\"%2$s\\" -t helyette',
    'UI:OQL:UnknownClassNoFix' => 'Ismeretlen osztály: \\"%1$s\\"',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:DashletUnknown:RenderNoDataText:Edit' => 'Nincs előnézet ehhez a műszerhez (%1$s osztály).',
```suggestion
    'UI:DashletUnknown:RenderText:Edit' => 'Nem lehet megjeleníteni ezt a műszert ("%1$s" osztály). Ellenőriztesse a rendszergazdával, hogy elérhető-e.',
    'UI:DashletUnknown:RenderNoDataText:Edit' => 'Nincs előnézet ehhez a műszerhez ("%1$s" osztály).',
```

2023-06-13 13:26 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
> +    'UI:DashletProxy:RenderNoDataText:Edit' => 'Nincs előnézet ehhez a harmadik féltől származó műszerhez (%1$s osztály).',
```suggestion
    'UI:DashletProxy:RenderNoDataText:Edit' => 'Nincs előnézet ehhez a harmadik féltől származó műszerhez ("%1$s" osztály).',
```

2023-06-13 13:28 UTC, Molkobain approved these changes

2023-06-13 13:30 UTC, Hipska approved these changes

2023-06-13 15:53 UTC, Molkobain commented
Accepted during functional review

2023-06-13 16:00 UTC, merged