N°3767 - Impact analysis : add filtering box on CI list
Combodo/iTop pull request #473
Opened 2023-03-31 15:51 UTC by accognet

2023-08-08 14:47 UTC, Molkobain commented
Accepted during function review for 3.1.1
Technical review to do next.

2023-09-05 15:17 UTC, piRGoif commented
Technical review : just Pierre & Anne Catherine attending. Pierre will do a review on its own.

2023-09-06 10:15 UTC, piRGoif requested changes
To discuss with Anne Catherine in next review meeting

2023-09-06 10:15 UTC, piRGoif commented on pages/UI.php
> +				$oTitle->SetIcon($sClassIcon);
The icon is now on the new title block, whereas it was on the class panel before. Can you explain with screenshots before/after why this modification ?

2023-09-06 10:15 UTC, piRGoif commented on pages/UI.php
> +			$oP->AddUiBlock($oTitle);
Can you move the $oTitle init here ? It's confusing to have block init and add so far away from each other :(

2023-09-06 10:15 UTC, piRGoif commented on core/displayablegraph.class.inc.php
> +	 * @deprecated 3.1.1
Tell why and what to use instead please

2023-09-06 10:15 UTC, piRGoif commented on core/displayablegraph.class.inc.php
> +	 * @deprecated 3.1.1
Why deprecated ? This is still the method called in UI.php

2023-09-06 10:15 UTC, piRGoif commented on pages/UI.php
> -	$oImpactedObject->AddSubBlock(AlertUIBlockFactory::MakeForWarning(Dict::S("Relation:impacts/FilteredData"), '', "alert_filtered_list")->SetIsHidden(true));
I need an explanation on this removal. I see the dict key is used now in displayablegraph, but in a different type of block ?

2023-09-06 10:15 UTC, piRGoif commented on core/displayablegraph.class.inc.php
> +	public function GetFiltering(string $sContextKey, array $aContextParams, array $aExcludedObjects): array
To me the name is not very clear (filtering ?? uiblock, data, other ??). As far as I understand this is getting the filter options data ?

2023-09-15 15:00 UTC, piRGoif commented on core/displayablegraph.class.inc.php
> +	 * @deprecated 3.1.1
Solved

2023-09-15 15:02 UTC, piRGoif commented on core/displayablegraph.class.inc.php
> +	 * @deprecated 3.1.1
Don't forget this comment please O:)

2023-09-15 15:02 UTC, piRGoif commented on pages/UI.php
> +				$oTitle->SetIcon($sClassIcon);
Discussed with Anne Catherine directly, closing conversation

2023-09-15 15:03 UTC, piRGoif commented on pages/UI.php
> +			$oP->AddUiBlock($oTitle);
Don't forget this Anne Catherine !

2023-09-15 15:06 UTC, piRGoif commented on pages/UI.php
> +			$oTitle = TitleUIBlockFactory::MakeForPage(MetaModel::GetRelationDescription($sRelation, $bDirDown).' '.$oObj->GetName());
To check with @steffunky or @Molkobain if there is a better looking component for this ?

2023-09-18 14:12 UTC, accognet commented on pages/UI.php
> -	$oImpactedObject->AddSubBlock(AlertUIBlockFactory::MakeForWarning(Dict::S("Relation:impacts/FilteredData"), '', "alert_filtered_list")->SetIsHidden(true));
Filter box is now always visible. This warning message is therefore unnecessary.

2023-09-19 08:27 UTC, piRGoif commented
The PR was reviewed and accepted in last functional review
Just the oTitle potential replacement to be checked, and it'll be ok to merge !

2023-09-19 15:37 UTC, Molkobain commented
I still have to review it as well as we discussed it with Anne-Catherine a while back.

2023-11-20 12:45 UTC, Molkobain approved these changes

2023-11-23 13:06 UTC, merged