N°1646 - Enum: logical ordering defined in datamodel (dashlet, list, transition menu...)
Combodo/iTop pull request #475
Opened 2023-04-06 08:55 UTC by accognet

Order in select list
In xml, definition of values with rank:
![image](https://user-images.githubusercontent.com/57360138/230327058-e7a6882a-f56a-45b4-b707-2236e5651e6a.png)

In designer, add other values without rank:
![image](https://user-images.githubusercontent.com/57360138/230327095-d63be156-88cc-409b-9462-82dd30b31fb5.png)

Result in screen :
![image](https://user-images.githubusercontent.com/57360138/230327130-92a6054d-ffde-4218-9fff-af04f4426a88.png)

2023-04-06 09:03 UTC, jbostoen commented
Would be nice if sort could happen alphabetically (the order may be different for some languages) 😁

I suppose there could be a field property "sorting" with could default to "rank" or "alphabetical" in such case.

2023-04-06 09:20 UTC, accognet commented
Yes, if there is no rank, order is alphabetically depending of language

2023-04-06 09:30 UTC, Hipska commented
> Yes, if there is no rank, order is alphabetically depending of language

So the default behaviour will change then? As currently it is sorted on the enum value?

2023-04-06 09:33 UTC, Hipska commented on core/attributedef.class.inc.php
> +			asort($aLocalizedValues);
Duplicate sort of array
```suggestion
		asort($aLocalizedValues);
		
		if ($bHaveSortedValues) {
```

2023-04-06 09:37 UTC, accognet commented
Yes, , this is the idea.

2023-04-06 09:42 UTC, Hipska commented
Okay, but then this PR should also add orderings to the fields `impact`, `priority` and `urgency` on the different`Ticket` subclasses like for example on `UserRequest`.

https://github.com/Combodo/iTop/blob/2907efde4ba53ead6c797acad37d8b5a404ca2fd/datamodels/2.x/itop-request-mgmt/datamodel.itop-request-mgmt.xml#L150-L233

There might be also other cases in the default datamodel that need to be fixed as well..

2023-04-06 09:47 UTC, accognet commented
Yes, there is still work on this subject. This is the reason why this PR is on draft .

2023-04-06 09:48 UTC, Hipska commented
Perfect, just wanted to make sure!

2023-04-11 08:43 UTC, Hipska commented on core/attributedef.class.inc.php
> +		if ($bHaveSortedValues) {
I don't think this boolean is needed:
```suggestion
		if (!empty($aSortedValues)) {
```

2023-04-11 08:51 UTC, Hipska commented on datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
>              </value>
If you want to mimic current ordering, it should be according to order in xml:
```suggestion
            <value id="implementation">
              <code>implementation</code>
              <rank>2</rank>
            </value>
            <value id="stock">
              <code>stock</code>
              <rank>3</rank>
            </value>
```

2023-04-11 09:51 UTC, accognet commented on datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
>              </value>
I have to validate this ordering with the product team. It's always work in progress.

2023-04-11 10:08 UTC, Hipska requested changes
Shouldn't it be like this? Or am I wrong with how iTop currently orders enums?

2023-04-11 10:08 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.expected.xml
> +          </values>
This is the expected order:
```suggestion
          <values>
            <value id="new">
              <code>new</code>
              <rank>0</rank>
            </value>
            <value id="assigned">
              <code>assigned</code>
              <rank>1</rank>
            </value>
          </values>
```

2023-04-11 10:08 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.expected.xml
> +            </value>
```suggestion
            <value id="ongoing">
              <code>ongoing</code>
              <rank>0</rank>
            </value>
            <value id="resolved">
              <code>resolved</code>
              <rank>1</rank>
            </value>
            <value id="closed">
              <code>closed</code>
              <rank>2</rank>
            </value>
```

2023-04-11 10:08 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
> +            </value>
The input suggested `assigned` before `new`.
```suggestion
            <value id="assigned">
              <code> assigned</code>
            </value>
            <value id="new">
              <code>new</code>
            </value>
```

2023-04-11 10:08 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
> +          </values>
```suggestion
          <values>
            <value id="closed">
              <code>closed</code>
            </value>
            <value id="ongoing">
              <code>ongoing</code>
            </value>
            <value id="resolved">
              <code>resolved</code>
            </value>
          </values>
```

2023-04-11 10:35 UTC, Hipska commented on datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
>              </value>
Sorry, I was wrong. The current sorting is indeed based on code.

2023-05-09 15:14 UTC, piRGoif commented
Functional review : 
- Transitions buttons order : nee to check with other people in Combodo (align with business needs)
- Maybe split the PR : enum order solely in this PR, transition buttons in a dedicated new PR

2023-06-05 07:19 UTC, Molkobain requested changes

2023-06-05 07:19 UTC, Molkobain commented on setup/itopdesignformat.class.inc.php
> +		$this->RemoveNodeFromXPath("/itop_design/classes//class/fields/field/values/value/rank");
Missing `sort_order` node removal

2023-06-05 07:19 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.expected.xml
Not necessary as we don't add nodes automatically on XML upgrade

2023-06-05 07:19 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.input.xml
Not necessary as we don't add nodes automatically on XML upgrade

2023-06-05 07:19 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
Reduce XML to only what we are testing for better readability / maintenability.
Name class / attribute with explicit name of the test case so we know what we are testing exactly.

2023-06-05 07:19 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.input.xml
Reduce XML to only what we are testing for better readability / maintenability.
Name class / attribute with explicit name of the test case so we know what we are testing exactly.

2023-06-05 07:19 UTC, Molkobain commented on setup/compiler.class.inc.php
> +					} else {
Rank should not be prepend to the value code, values should be sorted then "output" in the correct order in the PHP definition like for other ranked elements.
- Simplifies logic and manipulations at runtime
- Easier maintainability

2023-06-05 07:19 UTC, Molkobain commented on setup/compiler.class.inc.php
>  		} elseif ($sAttType == 'AttributeEnum') {
Compilation missing for `AttributeMetaEnum`

2023-06-05 07:19 UTC, Molkobain commented on core/valuesetdef.class.inc.php
See comment in compiler

2023-06-05 07:19 UTC, Molkobain commented on core/attributedef.class.inc.php
> +	public $m_sSortOrder = 'code'; // Encryption library used for all encrypted fields
What's that comment? Please verify what you copy/paste.

2023-06-05 07:19 UTC, Molkobain commented on setup/compiler.class.inc.php
> +				$aParameters['sort_order'] = "'code'";
Why the single quotes within the double quotes, doesn't seem necessary. Single quotes are only necessary when you are about to print compiled code.

2023-06-05 07:20 UTC, Molkobain commented
Closing this PR as we need to correct it and merge it quickly. I'll handle it. Anne-Catherine might not have time to rework it as she is on support.

2023-06-05 07:21 UTC, closed without merging