N°3191 - Introduce summary cards for objects hyperlinks
Combodo/iTop pull request #476
Opened 2023-04-06 11:11 UTC by steffunky

This feature adds a way to preview objects by hovering a hyperlink

![summarycards](https://user-images.githubusercontent.com/5959857/230359271-a935672a-7d65-4a1b-81df-56aa99879446.png)

Summary cards are displayed on every link for every object that meets the following conditions:
- Object's class has a non-empty `summary` zlist **or** a non-empty `complementary_attributes` list
- User is allowed to view this object
- User allows summary cards in its preferences

Summary cards are cached for each object for the current page to avoid server overload, they are called asynchronously when hovering a hyperlink of an object meeting the aforesaid conditions.

2023-04-06 15:50 UTC, Molkobain commented on core/metamodel.class.php
> +MetaModel::RegisterZList("summary", array("description" => "All attributes to be displayed for shorter 'details' of an object", "type" => "attributes"));
Maybe put this right after the "details" zlist for better comprehension of their similarity?

2023-04-06 15:50 UTC, Molkobain commented on css/backoffice/blocks-integrations/_summary-card-within-tippy.scss
> +  color: $ibo-vendors-tippy--summary--color;
```suggestion
$ibo-vendors-tippy--object-summary--background-color: $ibo-color-transparent !default;
$ibo-vendors-tippy--object-summary--color: $ibo-body-text-color !default;

.tippy-box[data-theme~='object-summary'] {
  background-color: $ibo-vendors-tippy--object-summary--background-color;
  color: $ibo-vendors-tippy--object-summary--color;
```
And rename file "_object-summary-within-tippy.scss".

This way it is more compliant with the "object-details" and "object-summary" blocks.

2023-04-06 15:50 UTC, Molkobain commented on css/backoffice/blocks-integrations/_all.scss
> +@import "summary-card-within-tippy";
```suggestion
@import "object-summary-within-tippy";
```

See comment below.
Also move this under the object-details partial.

2023-04-06 15:50 UTC, Molkobain commented on css/backoffice/layout/object/_object-summary.scss
> +}
```suggestion
.ibo-object-summary--content--attributes {
  display: table;
  width: 100%;
  margin-top: $ibo-object-summary--content--attributes--margin-top;
}

.ibo-object-summary--content--attributes--code, .ibo-object-summary--content--attributes--value {
  display: table-cell;
}
```

Avoid nested selectors when they are discriminant enough. (Also typo in a class)

2023-04-06 15:50 UTC, Molkobain commented on js/utils.js
> +	aTooltipRemoteContent: {},
```suggestion
	/**
	 * @var aTooltipRemoteContent {Object}
	 * @since 3.1.0
	 */
	aTooltipRemoteContent: {},
	
```

Detail what its purpose is.
Also plural.

2023-04-06 15:50 UTC, Molkobain commented on js/utils.js
> +			(typeof sHideDelay === 'undefined') ? null :  parseInt(sHideDelay),
```suggestion
			(typeof sHideDelay === 'undefined') ? null : parseInt(sHideDelay),
```

2023-04-06 15:50 UTC, Molkobain commented on dictionaries/ui/pages/preferences/en.dictionary.itop.preferences.php
> +	'UI:Favorites:General:ShowSummaryCard+'                         => 'When hovering an hyperlink targeting an object, display a short summary of the object',
```suggestion
	'UI:Favorites:General:ShowSummaryCards'                          => 'Show summary cards',
	'UI:Favorites:General:ShowSummaryCards+'                         => 'When hovering an hyperlink targeting an object, display a short summary of the object',
```

Here it's ok to keep "summary cards" instead of "object summary" IMO as this feature (display content on hover of something) could also be used for other things in the future.

2023-04-06 15:50 UTC, Molkobain commented on pages/preferences.php
> +	$oMiscOptionsFieldset->AddSubBlock(GetSummaryCardFieldBlock());
```suggestion
	$oMiscOptionsFieldset->AddSubBlock(GetSummaryCardsFieldBlock());
```

2023-04-06 15:50 UTC, Molkobain commented on pages/preferences.php
> +		<input type="checkbox" name="show_summary_card" value="1"{$sSelectedForHtmlAttribute}>
```suggestion
function GetSummaryCardsFieldBlock(): iUIBlock
{
	$bShow = appUserPreferences::GetPref('show_summary_cards', true);
	$sSelectedForHtmlAttribute = $bShow ? 'checked="checked"' : '';

	$sLabel = Dict::S('UI:Favorites:General:ShowSummaryCards');
	$sLabelDescription = Dict::S('UI:Favorites:General:ShowSummaryCards+');
	$sHtml = <<<HTML
<p>
	<label data-tooltip-content="{$sLabelDescription}">
		<span>{$sLabel}</span>
		<input type="checkbox" name="show_summary_cards" value="1" {$sSelectedForHtmlAttribute}>
```

2023-04-06 15:50 UTC, Molkobain commented on pages/preferences.php
> +				appUserPreferences::SetPref('show_summary_card', $bShowSummaryCard);
```suggestion
				// - Summary cards
				$bShowSummaryCards = (bool)utils::ReadParam('show_summary_cards', 0);
				appUserPreferences::SetPref('show_summary_cards', $bShowSummaryCards);
```

2023-04-06 15:50 UTC, Molkobain commented on setup/compiler.class.inc.php
> +			'summary' => 'summary'
Maybe put this right after the "details" zlist for better comprehension of their similarity?

2023-04-06 15:50 UTC, Molkobain commented on sources/Application/UI/Base/Layout/ObjectSmallDetails/ObjectSummary.php
File should be in "sources/Application/UI/Base/Layout/Object" instead of "sources/Application/UI/Base/Layout/ObjectSmallDetails".
Mind to redump the autoloaders.

2023-04-06 15:50 UTC, Molkobain commented on sources/Application/UI/Base/Layout/ObjectSmallDetails/ObjectSummary.php
> +		$this->sObjectId = $oObject->GetKey();
Would already be taken care of by the parent constructor, can't you move it at here and remove these lines?

2023-04-06 15:50 UTC, Molkobain commented on sources/Controller/Base/Layout/ObjectController.php
> +		$sClass = utils::ReadParam('obj_class', '', false, 'class');
```suggestion
		$sClass = utils::ReadParam('obj_class', '', false, utils::ENUM_SANITIZATION_FILTER_CLASS);
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Controller/Base/Layout/ObjectController.php
> +			$oPage->AddUiBlock(AlertUIBlockFactory::MakeForFailure(Dict::S('UI:Error:ActionNotAllowed'))->SetIsCollapsible(false)->SetIsClosable(false));
```suggestion
			$oPage->AddUiBlock(
				AlertUIBlockFactory::MakeForFailure(Dict::S('UI:Error:ActionNotAllowed'))
					->SetIsCollapsible(false)
					->SetIsClosable(false)
			);
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +class SummaryCardService extends AbstractController {
PHPDoc on what its purpose and that it is not only for object summary could helped in the future.
Also since 3.1.0

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +		return "data-tooltip-content=\"$sRoute\" data-tooltip-interaction-enabled=\"true\" data-tooltip-is-async=\"true\" data-tooltip-html-enabled=\"true\" data-tooltip-sanitizer-skipped=\"false\" data-to
You might be able to use a HEREDOC there with line break on each HTML attribute. Would help the readability / maintenance. We did it in other places.

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +	 *  Check if the user is allowed to see this class and if the class is allowed to display its summary
```suggestion
	 * Check if the user is allowed to see this class and if the class is allowed to display its summary
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +		if(UserRights::IsActionAllowed($sClass, UR_ACTION_READ) === UR_ALLOWED_NO){
```suggestion
		if (UserRights::IsActionAllowed($sClass, UR_ACTION_READ) === UR_ALLOWED_NO) {
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +		if(appUserPreferences::GetPref('show_summary_card', true) === false){
```suggestion
		if (appUserPreferences::GetPref('show_summary_cards', true) === false) {
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +		if(!empty($aDetailsList)){
```suggestion
		if(count($aDetailsList) > 0) {
```

2023-04-06 15:50 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +		if (!empty($aAdditionalField)) {
```suggestion
		if (!empty($aAdditionalField)) {
```
```suggestion
		if (count($aAdditionalField) > 0) {
```

2023-04-06 15:50 UTC, Molkobain commented on templates/base/layouts/object/object-summary/layout.html.twig
> +{% block iboPanelBody %}
```suggestion
{% extends 'base/layouts/object/object-details/layout.html.twig' %}

{% block iboPanelHeaderOuter %}
{% endblock %}
    
{% block iboPanelBody %}
```

2023-04-06 15:50 UTC, Molkobain commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
This is risky for XSS attacks.

2023-04-06 15:51 UTC, Molkobain commented
This is gonna be such a great feature 🙌

2023-04-06 21:40 UTC, Molkobain commented on sources/Service/SummaryCard/SummaryCardService.php
> +class SummaryCardService extends AbstractController {
Feels weird that this inherits from `AbstractController`, is it a relic from a past refactorisation?

2023-04-07 08:24 UTC, steffunky commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
If you check the `cmdbabstract::GetBareProperties` you can see that it's the same usage that's done for the `GetAsHTML` value:
GetASHTML -> FieldBlock (raw) -> HtmlBlock (raw)

2023-04-07 08:36 UTC, steffunky commented on sources/Service/SummaryCard/SummaryCardService.php
> +class SummaryCardService extends AbstractController {
Done in [87c80c1](https://github.com/Combodo/iTop/pull/476/commits/87c80c1aa2d2b5d4c8681c1b1baf9ad7f225b2ec)

2023-04-07 08:36 UTC, steffunky commented on core/metamodel.class.php
> +MetaModel::RegisterZList("summary", array("description" => "All attributes to be displayed for shorter 'details' of an object", "type" => "attributes"));
Done in [7416c16](https://github.com/Combodo/iTop/pull/476/commits/7416c163ac7647bfa36bceb0a61afb19a015cfe9)

2023-04-07 08:37 UTC, steffunky commented on setup/compiler.class.inc.php
> +			'summary' => 'summary'
Done in [7416c16](https://github.com/Combodo/iTop/pull/476/commits/7416c163ac7647bfa36bceb0a61afb19a015cfe9)

2023-04-07 08:37 UTC, steffunky commented on css/backoffice/blocks-integrations/_summary-card-within-tippy.scss
> +  color: $ibo-vendors-tippy--summary--color;
Done in [13320b8](https://github.com/Combodo/iTop/pull/476/commits/13320b87bbb5c3492b82ba76ba92d14f2dfac4be)

2023-04-07 08:37 UTC, steffunky commented on css/backoffice/blocks-integrations/_all.scss
> +@import "summary-card-within-tippy";
Done in [13320b8](https://github.com/Combodo/iTop/pull/476/commits/13320b87bbb5c3492b82ba76ba92d14f2dfac4be)

2023-04-07 08:37 UTC, steffunky commented on js/utils.js
> +	aTooltipRemoteContent: {},
Done in [20d5e65](https://github.com/Combodo/iTop/pull/476/commits/20d5e657346868a93b265edaccb5c8acde03e664)

2023-04-07 08:38 UTC, steffunky commented on sources/Application/UI/Base/Layout/ObjectSmallDetails/ObjectSummary.php
Done in [a7dc0f3](https://github.com/Combodo/iTop/pull/476/commits/a7dc0f374b2135f0ccd50809bff7a112478f9cfe)

2023-04-07 08:38 UTC, steffunky commented on sources/Service/SummaryCard/SummaryCardService.php
> +		return "data-tooltip-content=\"$sRoute\" data-tooltip-interaction-enabled=\"true\" data-tooltip-is-async=\"true\" data-tooltip-html-enabled=\"true\" data-tooltip-sanitizer-skipped=\"false\" data-to
Done in [87c80c1](https://github.com/Combodo/iTop/pull/476/commits/87c80c1aa2d2b5d4c8681c1b1baf9ad7f225b2ec)

2023-04-07 09:28 UTC, steffunky commented on sources/Application/UI/Base/Layout/ObjectSmallDetails/ObjectSummary.php
> +		$this->sObjectId = $oObject->GetKey();
Done in [954cad5](https://github.com/Combodo/iTop/pull/476/commits/954cad5ade06ced0dc2229ac34dcc1ac8beb1861)

2023-04-07 09:30 UTC, steffunky commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
Moreover it seems ok in practice:
![image](https://user-images.githubusercontent.com/5959857/230584484-3f05279b-877e-44ef-b0ad-fea2b409b1d2.png)

2023-04-07 20:17 UTC, Molkobain commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
Can you check with an AttributeText (as plain text) and an AttributeHTML as well please? Just to be sure.

2023-04-07 20:18 UTC, Molkobain commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
Can you check with an AttributeText (as plain text) and an AttributeHTML as well please? Just to be sure.

2023-04-11 07:19 UTC, steffunky commented on templates/base/layouts/object/object-summary/layout.html.twig
> +            <span class="ibo-object-summary--content--attributes--value ibo-field--value">{{ attval|raw }}</span>
![image](https://user-images.githubusercontent.com/5959857/231085365-59fed4d9-4109-4310-b70d-5086fb8ae471.png)

2023-04-17 08:20 UTC, Molkobain requested changes

2023-04-17 08:20 UTC, Molkobain commented on css/backoffice/blocks-integrations/object-details/_object-details-with-tab-container.scss
Rename directory "object"

2023-04-17 08:20 UTC, Molkobain commented on css/backoffice/blocks-integrations/_all.scss
> +@import "object-details/all";
```suggestion
@import "object/all";
```

2023-04-17 08:20 UTC, Molkobain commented on pages/preferences.php
> + * @since 3.0.0
```suggestion
 * @since 3.1.0
```

2023-04-17 09:03 UTC, steffunky commented on css/backoffice/blocks-integrations/_all.scss
> +@import "object-details/all";
Fixed in [2816357](https://github.com/Combodo/iTop/pull/476/commits/281635786c92a0dd23e35bc6ea2b91203804d4df)

2023-04-17 09:03 UTC, steffunky commented on css/backoffice/blocks-integrations/object-details/_object-details-with-tab-container.scss
Fixed in [2816357](https://github.com/Combodo/iTop/pull/476/commits/281635786c92a0dd23e35bc6ea2b91203804d4df)

2023-04-17 09:03 UTC, steffunky commented on pages/preferences.php
> + * @since 3.0.0
Fixed in [aca6f12](https://github.com/Combodo/iTop/pull/476/commits/aca6f1209b2c74a82e84f04dbf1cb9785dc690ad)

2023-04-17 09:29 UTC, Molkobain approved these changes

2023-04-17 10:20 UTC, merged