N°6179 - Tooltip attribute in field component (in Twig)
Combodo/iTop pull request #478
Opened 2023-04-12 12:30 UTC by jf-cbd

New way to add a tooltip to a field component.

Example :

{% UIField Standard {sLabel: 'myLabel', sTooltip:'myTooltip'} %}

2023-04-14 08:28 UTC, piRGoif commented
Hello,
Can you provide a screenshot of the final result ? 
Is tooltip the right naming ? As the modification occurs in the Field class, I was expecting a title HTML attribute but it isn't : this naming may lead to confusions ? 
Also warning you have conflicts, can you resolve them ?

2023-04-17 08:50 UTC, Molkobain requested changes
We tend to use "description" of the field instead of "tooltip" qs it is more semantic and could be displayed elsewhere (eg. below the field) in a future UI rework.

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/Field.php
> +	protected $sTooltip = '';
```suggestion
	/**
	 * @var string
	 * @since 3.1.0
	 */
	protected $sDescription = '';
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/Field.php
> +	}
```suggestion
	 * @return string
	 * @since 3.1.0
	 */
	public function GetDescription(): string
	{
		return $this->sDescription;
	}

	/**
	 * @param string $sDescription
	 *
	 * @return $this
	 * @since 3.1.0
	 */
	public function SetDescription(string $sDescription)
	{
		$this->sDescription = $sDescription;
		return $this;
	}

	/*
	 * @return bool
	 * @since 3.1.0
	 */
	public function HasDescription(): bool
	{
		return utils::IsNotNullOrEmptyString($this->GetTooltip());
	}
```

_Mind to import the \utils class_

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	 * @param string $sTooltip
```suggestion
	 * @param string $sDescription
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	public static function MakeLarge(string $sLabel, string $sValueHtml = '', string $sTooltip = '')
```suggestion
	public static function MakeLarge(string $sLabel, string $sValueHtml = '', string $sDescription = '')
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +		$oField->SetTooltip($sTooltip);
```suggestion
		$oField->SetDescription($sDescription);
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	 * @param string $sTooltip
```suggestion
	 * @param string $sDescription
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	public static function MakeSmall(string $sLabel, string $sValueHtml = '', string $sTooltip = '')
```suggestion
	public static function MakeSmall(string $sLabel, string $sValueHtml = '', string $sDescription = '')
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +		$oField->SetTooltip($sTooltip);
```suggestion
		$oField->SetDescription($sDescription);
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	 * @param string $sTooltip
```suggestion
	 * @param string $sDescription
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +	public static function MakeStandard(string $sLabel = '', string $sLayout = Field::ENUM_FIELD_LAYOUT_SMALL, ?string $sId = null, string $sTooltip = '')
```suggestion
	public static function MakeStandard(string $sLabel = '', string $sLayout = Field::ENUM_FIELD_LAYOUT_SMALL, ?string $sId = null, string $sDescription = '')
```

2023-04-17 08:50 UTC, Molkobain commented on sources/application/UI/Base/Component/Field/FieldUIBlockFactory.php
> +		$oField->SetTooltip($sTooltip);
```suggestion
		$oField->SetDescription($sDescription);
```

2023-04-17 08:50 UTC, Molkobain commented on templates/base/components/field/layout.html.twig
> +        {% endif %}
```suggestion
        {% if oUIBlock.HasDescription() %}
            <span class="ibo-has-description" data-tooltip-content="{{ oUIBlock.GetDescription() }}" data-tooltip-max-width="600px" ></span>
        {% endif %}
```

2023-04-19 08:09 UTC, jf-cbd commented
> Hello, Can you provide a screenshot of the final result ? Is tooltip the right naming ? As the modification occurs in the Field class, I was expecting a title HTML attribute but it isn't : this naming may lead to confusions ? Also warning you have conflicts, can you resolve them ?

![Screenshot from 2023-04-19 10-04-47](https://user-images.githubusercontent.com/121934370/233009912-f97c7057-7c2f-4096-bae8-2937a36a2858.png)
Hello, the purpose is to add a description in Twig when it's not an iTop object. Concerning the title attribute, I saw with @Molkobain and there is actually no title attribute when the tippy library is used.

2023-04-19 09:02 UTC, merged

2023-04-19 15:28 UTC, Molkobain commented
Nice addition to the API thanks!