N°6251 - 1:n - Actions must not be proposed to user not allowed
Combodo/iTop pull request #491
Opened 2023-05-04 09:24 UTC by bdalsass

2023-05-04 11:22 UTC, Molkobain commented on sources/Application/UI/Links/Direct/BlockDirectLinkSetEditTable.php
> +				if (UserRights::IsActionAllowed($this->oAttributeLinkedSet->GetLinkedClass(), UR_ACTION_CREATE) == UR_ALLOWED_YES) {
Maybe you could factorize all these `IsActionAllowed()` calls into `$bIsCreationAllowed`, `$bIsDeletionAllowed`, ... before the switch statement instead ? It would ease reading and maintenance.

2023-05-04 11:22 UTC, Molkobain commented on sources/Application/UI/Links/Direct/BlockDirectLinkSetViewTable.php
> +				if (UserRights::IsActionAllowed($this->oAttDef->GetLinkedClass(), UR_ACTION_MODIFY) == UR_ALLOWED_YES) {
Same comment than previous file

2023-05-05 09:14 UTC, Hipska requested changes
Looks good, watch out for some indentations which are not correct.

2023-05-05 09:14 UTC, Hipska commented on sources/Application/UI/Links/Direct/BlockDirectLinkSetEditTable.php
> +	private bool $bIsAllowDelete;
```suggestion
	protected bool $bIsAllowCreate;
	protected bool $bIsAllowModify;
	protected bool $bIsAllowDelete;
```

2023-05-05 09:14 UTC, Hipska commented on sources/Application/UI/Links/Indirect/BlockIndirectLinkSetEditTable.php
> +	private bool $bIsAllowDelete;
Forgot the modify?
```suggestion
	protected bool $bIsAllowCreate;
	protected bool bIsAllowModify;
	protected bool $bIsAllowDelete;
```

2023-05-05 09:39 UTC, Molkobain approved these changes

2023-05-05 12:26 UTC, bdalsass commented on sources/Application/UI/Links/Indirect/BlockIndirectLinkSetEditTable.php
> +	private bool $bIsAllowDelete;
Hi Hipska, thank's for your suggestion.
The modify permission is unecessary in this case because the remove action (witch delete a link object) is done with delete permission on lnk object. The modify is used for 1:n relation because it modify the remote object and need the modify permission on remote object.

2023-05-05 12:28 UTC, merged

2023-05-05 12:30 UTC, Hipska commented on sources/Application/UI/Links/Indirect/BlockIndirectLinkSetEditTable.php
> +	private bool $bIsAllowDelete;
Okay, but you are targeting the modify var here: https://github.com/Combodo/iTop/pull/491/files/dca3643bedaa33412b8df31120138c18cdddcf15#diff-0b811ee6ae6b5be8c70559abfab3df659f0adfb02361232030e39b49d908cf6fR111

2023-05-05 12:32 UTC, Hipska commented
Wait, why is it merged with some having the new vars as `private` and others as `protected`? It doesn't seem consistent?

2023-05-05 12:34 UTC, bdalsass commented
One is done in abstract context (for linkset in view mode) so it needs the protected visibility.