Possibility to not only force synchronous sending of e-mails, but also asynchronous sending
Combodo/iTop pull request #501
Opened 2023-06-04 10:11 UTC by jbostoen

Possibility to not only force synchronous sending of e-mails, but also asynchronous sending.

Currently, the sending of an e-mail in iTop respects whatever is configured (synchronous/asynchronous) in the configuration parameter. iTop already supports an option to forcefully send synchronous e-mails instead, which is mostly useful for sending immediate test e-mails.

Coming to the use case for this PR: extensions such as customer survey, the opposite would be needed. Customer survey sends a lot of individual e-mails, which may trigger a limit with the e-mail provider which starts blocking the e-mails, returning in many failed send attempts. As an iTop admin, I want to send synchronous by default; and asynchronous only for such a specific use case.

This draft is here to open discussion whether the iTop core should already have something on this (customer survey extension still needs a minor update then), or whether the customer survey extension should briefly override the configuration instead.

2023-06-05 07:20 UTC, Hipska reviewed
Code logic looks good, some minor remarks

2023-06-05 07:20 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
> +		if(is_bool($iSyncAsync) == true && $iSyncAsync == true) {
```suggestion
		if(is_bool($iSyncAsync) && $iSyncAsync == true) {
```
Or maybe just like this (less explicit):
```suggestion
		if($iSyncAsync === true) {
```

2023-06-05 07:20 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
>  	}
Those empty lines can be left out?

2023-06-05 07:20 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
> +					else {
```suggestion
					} else {
```

2023-06-05 07:20 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
> +		else {
```suggestion
		} else {
```

2023-06-17 13:55 UTC, jbostoen commented
@piRGoif @Molkobain Can this idea be discussed?

2023-06-19 16:13 UTC, piRGoif commented
Corresponding SF ticket : https://sourceforge.net/p/itop/tickets/2157/
Will be discussed on next reviews.

2023-07-06 14:26 UTC, Molkobain commented
Technical review: Sounds like a good idea, will check during functional review if ok for product, them will dig more into how we would like it to be implemented.

2023-07-11 12:59 UTC, Molkobain commented on sources/Core/Email/EmailLaminas.php
> +		if(is_bool($iSyncAsync) == true && $iSyncAsync == true) {
I would be in favor of the second proposal :)

2023-07-11 17:06 UTC, jbostoen commented
Alright, let me know when to proceed :)

2023-07-11 20:43 UTC, Molkobain commented
Functional review:
- Ok on the principle for this PR (Core part. Customer survey part would be part of another PR later)
- Deeper discussion on how we would like it to be done will take place during next technical release
- Target is iTop 3.2, so develop branch is ok
- For future Customer Survey PR: 
  - Sync/Async param. should not be a module param but an enum attribute (`"sync" / "async"`) of the `Survey` object itself. That way it will be easier to see how it will behave in a glance and to manage what is what (same behavior is planned on the `ActionWebhook`)
  - Add a check to write on `Survey` to warn user if it is configured as async and CRON is not running
  - Later, Combodo will try to introduce a standard API to do this on classes

2023-07-12 07:10 UTC, jbostoen commented
Alright, adjusted everything according to our discussion above.

Would be nice to still have it in iTop 3.1 (even if it's in a maintenance release, as iTop 3.1 will be LTS I think?). 😁

2023-07-12 07:15 UTC, Molkobain commented
> Would be nice to still have it in iTop 3.1 (even if it's in a maintenance release, as iTop 3.1 will be LTS I think?). 😁

LTS won't be iTop 3.1, it is more likely to be a 3.2.x but this is no sure yet.

2023-08-01 15:51 UTC, Molkobain requested changes

2023-08-01 15:51 UTC, Molkobain commented on core/email.class.inc.php
> +	/** @var Integer ENUM_SEND_DEFAULT This option can be used when sending an e-mail to respect the default configuration parameter. */
```suggestion
	/** @var int ENUM_SEND_DEFAULT This option can be used when sending an e-mail to respect the default configuration parameter. */
```

2023-08-01 15:51 UTC, Molkobain commented on core/email.class.inc.php
> +	/** @var Integer ENUM_SEND_FORCE_SYNCHRONOUS This option can be used when sending an e-mail to ignore the default and force synchronous sending instead. Example of a use case: instant e-mail test. *
```suggestion
	/** @var int ENUM_SEND_FORCE_SYNCHRONOUS This option can be used when sending an e-mail to ignore the default and force synchronous sending instead. Example of a use case: instant e-mail test. */
```

2023-08-01 15:51 UTC, Molkobain commented on core/email.class.inc.php
> +	/** @var Integer ENUM_SEND_FORCE_ASYNCHRONOUS This option can be used when sending an e-mail to ignore the default and force synchronous sending instead. Example of a use case: Bulk mails. */
```suggestion
	/** @var int ENUM_SEND_FORCE_ASYNCHRONOUS This option can be used when sending an e-mail to ignore the default and force synchronous sending instead. Example of a use case: Bulk mails. */
```

2023-08-01 15:51 UTC, Molkobain commented on sources/Core/Email/EmailLaminas.php
> +	 * @param Integer|Boolean $iSyncAsync Specify whether the e-mail will be sent per default configuration, or whether there will be a forced (a)synchronous sending. One of Email::ENUM_SEND_* constants
```suggestion
	 * @param string[] $aIssues Array to add any potentially encountered issues to.
	 * @param int|bool $iSyncAsync Specify whether the e-mail will be sent per default configuration, or whether there will be a forced (a)synchronous sending. One of Email::ENUM_SEND_* constants. To support legacy, it also allows a boolean (true = send synchronous). 
```

2023-08-01 15:51 UTC, Molkobain commented on sources/Core/Email/EmailLaminas.php
> +	 * @details By default, the send method will respect the preference to send e-mails in an (a)synchronous way as defined in the iTop configuration by the administrator.
Add `@since 3.2.0` to explain that $bForceSynchronous changed to $iSyncAsync

2023-08-01 15:52 UTC, Molkobain commented
Accepted during technical review.
Final functional review next week.

2023-08-02 10:50 UTC, jbostoen commented
Updated per discussion above and squashed into one commit.

2023-08-03 07:29 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
>  			return $this->SendSynchronous($aIssues, $oLog);
Is this check even needed? In php a boolean true will evaluate equal to int 1, which should match the case `Email::ENUM_SEND_FORCE_SYNCHRONOUS` and thus execute the same method.

2023-08-03 07:43 UTC, Molkobain commented on sources/Core/Email/EmailLaminas.php
>  			return $this->SendSynchronous($aIssues, $oLog);
This is a strict comparison (triple `=`) so it will work. The behavior you describe would happen with a weak comparison (double `==`)

2023-08-03 07:44 UTC, Hipska commented on sources/Core/Email/EmailLaminas.php
>  			return $this->SendSynchronous($aIssues, $oLog);
Yes indeed. I'm just wondering if a switch case is strict or weak, so that this extra if can be removed..

2023-08-03 07:57 UTC, Molkobain commented on sources/Core/Email/EmailLaminas.php
>  			return $this->SendSynchronous($aIssues, $oLog);
Either way I'd rather keep the code as is, it is more explicit about how the legacy type is handle.

2023-08-03 08:11 UTC, Hipska approved these changes

2023-08-08 14:18 UTC, Molkobain commented
Accepted during functional review.
@jbostoen can you mark the PR as ready?

For future Customer Survey PR:
- Sync/Async param. should not be a module param but an enum attribute ("sync" / "async") of the Survey object itself. That way it will be easier to see how it will behave in a glance and to manage what is what (same behavior is planned on the ActionWebhook)
- Add a check to write on Survey to warn user if it is configured as async and CRON is not running
- Later, Combodo will try to introduce a standard API to do this on classes

2023-08-10 07:56 UTC, Molkobain commented
_This PR is not forgotten, it will be handle when the 3.2 development starts (in the coming months)_

2023-12-21 10:03 UTC, piRGoif commented on sources/Core/Email/EmailLaminas.php
> +		if(is_bool($iSyncAsync) == true && $iSyncAsync == true) {
Closing conversation as the code as evolved since then

2023-12-21 10:06 UTC, piRGoif commented on sources/Core/Email/EmailLaminas.php
>  	}
Code did change since this comment. Closing conversation.

2023-12-21 10:06 UTC, piRGoif commented on sources/Core/Email/EmailLaminas.php
> +					else {
Code did change since this comment. Closing conversation.

2023-12-21 10:06 UTC, piRGoif commented on sources/Core/Email/EmailLaminas.php
> +		else {
Code did change since this comment. Closing conversation.

2023-12-21 10:15 UTC, merged

2023-12-21 10:15 UTC, piRGoif commented
Hello,
I'm really sorry I missed that PR, and it took 4 months to merge :/ 
It is done now !

@jbostoen when creating the customer-survey corresponding PR, can you mention this one ?

2023-12-21 10:31 UTC, jbostoen commented
No problem Pierre.

I moved web hosts 3 weeks ago, now it's no longer an issue for me personally anymore. But it's good it's part of the iTop core; and perhaps someone else will be happy to see this enhancement and create a PR for it.