Add class description in tooltip of Dashlet badge
Combodo/iTop pull request #504
Opened 2023-06-06 09:18 UTC by accognet

Instead of the class name, display the class description in the tooltip on the dashlet badge
![image](https://github.com/Combodo/iTop/assets/57360138/e1690bbb-ff12-46e2-b178-6dc02115758e)

2023-06-06 09:41 UTC, Hipska approved these changes

2023-06-06 13:27 UTC, piRGoif requested changes

2023-06-06 13:27 UTC, piRGoif commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +		return $this->sClassDescription;
To be completly independant of the twig template, I think we should return the escaped value using \utils::EscapeHtml

2023-06-07 06:20 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +		return $this->sClassDescription;
No, never! Only the consumer should encode/escape data as it is the only one to know when it is necessary. For example is that method was used elsewhere we should have HTML characters when not desired.

2023-06-07 06:26 UTC, Molkobain requested changes
The class label should remain in the tooltip as it is necessary when it is so long that it is truncated.
You should rather display the class label on the first line, then the description below if there is one.

Check what has been done in an object tabs when there are hidden the extra tabs menu.

2023-06-07 07:10 UTC, piRGoif commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +		return $this->sClassDescription;
Indeed make perfect sense to escape in the presentation layer only.
Plus the current template will escape, so double escaping will produce an invalid result :(
What i feared was we may not control which template is used, if it is escaping or not. But here we are in a core dashlet class.
Closing discussion.

2023-06-08 12:16 UTC, accognet commented
Done

2023-06-08 12:19 UTC, Hipska approved these changes
Great, do you also have a new example screenshot?

2023-06-08 13:44 UTC, accognet commented
Yes, I just updated the description

2023-06-09 14:09 UTC, Molkobain requested changes

2023-06-09 14:09 UTC, Molkobain commented on application/displayblock.class.inc.php
> +		if ($sClassDescription != '') {
```suggestion
		if (utils::IsNotNullOrEmptyString($sClassDescription)) {
```

I didn't check if it's necessary to add an `@use utils;` statement.

2023-06-09 14:09 UTC, Molkobain commented on templates/base/components/dashlet/dashlet-badge.html.twig
> +         data-tooltip-show-delay="300">
```suggestion
            {% if oUIBlock.HasClassDescription() %}
                {# Display both class name and description as the name could be truncated if too long #}
                data-tooltip-content="{{ '<div class="ibo-dashlet-badge--body--tooltip-title">'|escape }}{{ oUIBlock.GetClassLabel() }}{{ '</div><div class="ibo-dashlet-badge--body--tooltip-description">'|escape }}{{ oUIBlock.GetClassDescription() }}{{ '</div>'|escape }}"
                data-tooltip-html-enabled="true"
            {% else %}
                {# Display only class name as it could be truncated if too long #}
                data-tooltip-content="{{ oUIBlock.GetClassLabel() }}"
            {% endif %}
         {# Delay display to avoid having all tooltips appearing when mouse is just passing through the tabs #}
         data-tooltip-show-delay="300">
```

`data-tooltip-html-enabled` is not necessary if only the label is display as there is no markup.

2023-06-09 14:09 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	protected $sClassDescription = '';
In UIBlock we tend to not initialize property values there, but in the constructor. Even though this could be discuss within the team, I would rather keep consistency.

Please:
  * Initialize the property in the constructor
  * Add a `@since 3.1.0`

2023-06-09 14:09 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	 * @return string
`@since 3.1.0`

2023-06-09 14:09 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	 * @param string $sClassDescription
`@since 3.1.0`

2023-06-09 14:10 UTC, Molkobain commented
A few more changes and it should be ok.
This will be a nice addition 🙌

2023-07-11 21:10 UTC, Molkobain commented
Accepted during function review, target is 3.1.1.

Anne-Catherine will:
- Create the corresponding bug
- Rebase branch onto support/3.1 (feel free to ask how to "rebase onto" as it can mess up the branch)

Then Guillaume will do a final review

2023-08-21 14:00 UTC, Molkobain approved these changes

2023-08-21 14:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	 */
```suggestion
	/**
	 * @var string
	 * @since 3.1.1 3.2.0
	 */
```

2023-08-21 14:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	 * @since 3.1.1
```suggestion
	 * @since 3.1.1 3.2.0
```

2023-08-21 14:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	 * @since 3.1.1
```suggestion
	 * @return DashletBadge
	 * @since 3.1.1 3.2.0
```

2023-08-21 14:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +	public function SetClassDescription(string $sClassDescription): void
```suggestion
	public function SetClassDescription(string $sClassDescription)
```

2023-08-21 14:00 UTC, Molkobain commented on sources/Application/UI/Base/Component/Dashlet/DashletBadge.php
> +		$this->sClassDescription = $sClassDescription;
```suggestion
		$this->sClassDescription = $sClassDescription;
		
		return $this;
```

2023-08-21 14:04 UTC, Hipska approved these changes

2023-08-31 12:37 UTC, merged