N°6167 - API for the content of the Welcome Popup
Combodo/iTop pull request #505
Opened 2023-06-07 08:24 UTC by dflaven

The current "Welcome popup" displayed when a user connects to the iTop console has a number of limitations:
  - the content is the same for all users
  - the content is a dictionary entry and the image is hard coded, thus it can not be easily extended
  - there is only one message in a given version of iTop.

This pull request proposes an API (iWelcomePopup) to control the content of the "Welcome popup" with the ability to:
  - display several messages in the popup (simple "carousel like" display)
  - display different messages for different users/profiles
  - provide "welcome popup" messages via an extension
  - hide (auto acknowledge) a given message

Note: the ackowledgement of a message is no longer stored as a user preference, thus when the implementation provided by this pull request is integrated into iTop, the welcome popup will be displayed again to users even if the previously acknowledged the welcome popup. This could be fixed, but this is also the opportunity to renew the content of the welcome popup, for example to advertise the new version of iTop.

2023-10-27 08:59 UTC, Molkobain commented on application/applicationextension.inc.php
> +interface iWelcomePopup
```suggestion
interface iWelcomePopupExtension
```

Match naming convention of other APIs

2023-10-27 08:59 UTC, Molkobain commented on application/applicationextension.inc.php
> +	const IMPORTANCE_HIGH = 1;
```suggestion
	public const IMPORTANCE_CRITICAL = 0;
	public const IMPORTANCE_HIGH = 1;
```

PHP 7.4 min so we can set visibility

2023-10-27 08:59 UTC, Molkobain commented on application/applicationextension.inc.php
> +	public function GetMessages();
```suggestion
	 * @return array [
	 *			[
	 *				'importance' => IMPORTANCE_CRITICAL|IMPORTANCE_HIGH,
	 *				'id' => '...',
	 *				'title' => '',
	 * 			'html' => '',
	 *				'twig' => ''
	 *			],
	 *			...
	 *		]
	 */
	public function GetMessages(): array;
```

2023-10-27 08:59 UTC, Molkobain commented on application/applicationextension.inc.php
> +	public function AcknowledgeMessage(string $sMessageId): void
```suggestion
abstract class AbstractWelcomePopupExtension implements iWelcomePopupExtension
{
	/**
	 * @inheritDoc
	 */
	public function GetMessages(): array
	{
		return [];
	}
	
	/**
	 * @inheritDoc
	 */
	public function AcknowledgeMessage(string $sMessageId): void
```

2023-10-27 08:59 UTC, Molkobain commented on application/datamodel.application.xml
> +        <comment>/* Acknowledge welcome popup messages */</comment>
```suggestion
        <comment>/** Acknowledge welcome popup messages */</comment>
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/DefaultWelcomePopup.php
> +use AbstractWelcomePopup;
```suggestion
use AbstractWelcomePopupExtension;
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/DefaultWelcomePopup.php
> +class DefaultWelcomePopup extends AbstractWelcomePopup
```suggestion
class DefaultWelcomePopup extends AbstractWelcomePopupExtension
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/DefaultWelcomePopup.php
> +	public function GetMessages()
```suggestion
	/**
	 * @inheritDoc
	 */
	public function GetMessages(): array
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +	static $aAcknowledgedMessage = null;
```suggestion
	public static $aAcknowledgedMessage = null;
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +	public function GetMessages()
```suggestion
	public function GetMessages(): array
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +	protected function GetProviderByUUID(string $sMessageUUID): ?iWelcomePopup
```suggestion
	 * @return iWelcomePopupExtension|NULL
	 */
	protected function GetProviderByUUID(string $sMessageUUID): ?iWelcomePopupExtension
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +	 * @param iWelcomePopup[] $aMessagesProviders
```suggestion
	 * @param iWelcomePopupExtension[] $aMessagesProviders
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +		$aProviderClasses = utils::GetClassesForInterface(iWelcomePopup::class, '', array('[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]test[\\\\/]', '[\\\\/]tests[\\\\/]'));
```suggestion
		$aProviderClasses = utils::GetClassesForInterface(iWelcomePopupExtension::class, '', array('[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]test[\\\\/]', '[\\\\/]tests[\\\\/]'));
```

2023-10-27 08:59 UTC, Molkobain commented on sources/Application/WelcomePopup/WelcomePopupService.php
> +use iWelcomePopup;
```suggestion
use iWelcomePopupExtension;
```

2023-10-27 09:34 UTC, Hipska commented on application/applicationextension.inc.php
> +	public function GetMessages();
Both are not a correct way to document: https://phpstan.org/writing-php-code/phpdoc-types#array-shapes

2023-10-27 13:35 UTC, Molkobain commented on application/applicationextension.inc.php
> +	public function GetMessages();
I know, WIP rework

2024-04-18 13:07 UTC, steffunky requested changes

2024-04-18 13:07 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--messages-stack--width: 300px !default;
This could use $ibo-size-XXX (-650 is 256px, -700 is 384px though).

2024-04-18 13:07 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--stack-item--border-color--is-active: $ibo-color-grey-600 !default;
I think we always put the intended use last, this should probably be `$ibo-welcome-popup--stack-item--is-active--border-color`

2024-04-18 13:07 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--stack-item--opacity--is-acknowledge: 0.6 !default;
Same as above, `$ibo-welcome-popup--stack-item--is-acknowledge--opacity`

2024-04-18 13:07 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--message-content-wrapper--max-height: 80vh !default;
Shouldn't the parent limit this? Probably a modal here limiting the content size

2024-04-18 13:07 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--message-illustration--min-width: 230px !default;
`$ibo-size-650` would be great here

2024-04-18 13:39 UTC, Molkobain commented on pages/UI.php
> +	if (true || !Session::IsSet("welcome")) {
```suggestion
	if (!Session::IsSet("welcome")) {
```

Woops, I forgot to remove this.

2024-04-18 13:41 UTC, Molkobain commented on application/applicationextension.inc.php
> + * @private
```suggestion
```

Need to remove this

2024-04-18 13:46 UTC, Molkobain commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--stack-item--border-color--is-active: $ibo-color-grey-600 !default;
Alright

2024-04-18 13:46 UTC, Molkobain commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--stack-item--opacity--is-acknowledge: 0.6 !default;
Alright

2024-04-18 13:47 UTC, Molkobain commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--message-illustration--min-width: 230px !default;
Alright

2024-04-18 13:48 UTC, Molkobain commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--messages-stack--width: 300px !default;
Tried both, but it feels less balanced. I'll stick with the hardcoded value if that's ok with you

2024-04-18 14:00 UTC, steffunky commented on css/backoffice/application/welcome-popup/_welcome-popup.scss
> +$ibo-welcome-popup--messages-stack--width: 300px !default;
Sure

2024-04-18 14:50 UTC, Molkobain commented on sources/Application/WelcomePopup/Provider/DefaultProvider.php
> + * @since 3.1.0
```suggestion
 * @since 3.2.0
```

2024-04-18 14:57 UTC, merged