N°918 - Translate placeholder in notifications
Combodo/iTop pull request #506
Opened 2023-06-12 09:51 UTC by dflaven

This PR adds three fields on the ActionEmail class used for sending notificaitons via email:
- A "Language" field to specify in which language the notification is written. Setting a language forces the placeholders to be rendered in this language (useful for fields like enums/states and date/time).
- An "Ignore-notify" field (by default = "yes" for backward compatibility), which tells the system whether or not to take into account the "Notify" flag on contacts. (You no longer need to take this into account when writing an OQL for the To: Cc: and Bcc: fields)
- An "HTML template" field in which you can upload your own HTML template for a nicer formatting/branding of the emails.

2023-06-12 14:00 UTC, Molkobain requested changes

2023-06-12 14:00 UTC, Molkobain commented on core/action.class.inc.php
> +					//	$sBody = '<div style="border:2px dashed #6800ff;position:relative;padding:2px;"><div style="background-color:#6800ff;color:#fff;font-family:Courier New, sans-serif;font-size:14px;line-height:
Remove commented line

2023-06-12 14:00 UTC, Molkobain commented on core/action.class.inc.php
> +					$sBody = '<div style="border:2px dashed #6800ff;position:relative;padding:2px;"><div style="background-color:#6800ff;color:#fff;font-family:Courier New, sans-serif;font-size:14px;line-height:16p
Factorize both inline styles.

2023-06-12 14:00 UTC, Molkobain commented on core/action.class.inc.php
> +	 * {@inheritDoc}
```suggestion
	 * @inheritDoc
```

2023-06-12 14:00 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'ActionEmail:preview_more_info'                        => 'For more information about the CSS features supported by the different eMail clients, refer to <a target="_blank" href="https://www.caniema
Put URL in a placeholder and use Dict::Format. Otherwise it will be painful to maintain and duplicated in all languages.

2023-06-12 14:00 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.core.php
> +	'ActionEmail:preview_more_info'                        => 'Pour plus d\'informations sur les fonctionnalités CSS supportées par les différents client mèl, consultez <a target="_blank" href="https://
Put URL in a placeholder and use Dict::Format. Otherwise it will be painful to maintain and duplicated in all languages.

2023-06-12 14:00 UTC, Molkobain commented on templates/datamodel/ActionEmail/email-notification-preview.html.twig
Name CSS classes following the convention. Example `.ibo-dm-class--ActionEmail` in `css/backoffice/datamodel/_action.scss`. (Add SCSS partial for action-email)

Put inline style in dedicated CSS classes in that partial.

2023-06-13 07:34 UTC, Molkobain approved these changes

2023-06-13 07:50 UTC, Hipska commented
I'm not really convinced by this new html_template attribute. What benefits does it give?

2023-06-13 07:51 UTC, merged

2023-06-13 07:52 UTC, Hipska commented
Okay, so far for open communication?

2023-06-13 09:39 UTC, Molkobain commented
> I'm not really convinced by this new html_template attribute. What benefits does it give?

It allows to use a file template rather than trying to build it in CKEditor:
  * Both CKE and the sanitizer remove HTML attributes, styles etc. So it was impossible to match expectations for some people
  * Easier to build a nice template in a third party tool (Word, ...) for some people

2023-06-13 09:52 UTC, Hipska commented
Aha okay, in that case it makes sense. 👍 

But then I don't understand the part where it seems both the body and the template are used in the email?

2023-06-13 13:33 UTC, Molkobain commented
For example you could want to have a corporate layout with a banner, a footer and some styling rules; and use it in several notifications.

To do so, you can make the HTML template and put `$content$` in it which will be replaced with the content of the `ActionEmail->body` attribute of the action.

It allows to factorize layout.

2023-06-13 13:41 UTC, Hipska commented
But you would still need to upload this template to each email action, meaning it not really is a reusable template. A linked object with the template as file field would make it really a template.

2023-06-19 07:05 UTC, Molkobain commented
Indeed yes, but that would be for another PR I guess. :/