N°5324 - [ERGO] Avoid to have users with non-standalone power portal profile only
Combodo/iTop pull request #507
Opened 2023-06-14 13:38 UTC by odain-cbd

Context
A user with only 'Power portal user' cannot access iTop (broken page). we propose this repair mecanism to stop trapping new iTop users and increase product adoption.

Fix
This fix relies on 3.1 event mecanism. it consists in adding 'Power portal user' to any User that would end up with only 'Power portal user'. either by creating/editing any user. either by editing the associated URP_UserProfiles directly.

By default repair mecanism is enabled.
It could be forced/tuned by adding below configuration (you could choose any URP_UserProfile not only 'Portal user'): 
`$MyModuleSettings = array(
	'itop-profiles-itil' => array(
		'poweruserportal-repair-profile' => 'Portal user'
	),`

Repair mecanism will be disabled if
- Fallback profile does not exist. ie 'User portal' by defaut or the one mentioned in 'poweruserportal-repair-profile' configuration
- current iTop has more than 2 portal XML configured (<portal>). our customer may have more than these 2 portals (itop-portal-base and backoffice). we dont want to silently give direct access to a specific portal during user edition.

2023-06-19 09:40 UTC, Molkobain reviewed
Discussed with Olivier IRL

2023-06-19 09:40 UTC, Molkobain commented on datamodels/2.x/itop-profiles-itil/src/UserProfilesEventListener.php
> +		if (!is_null($oUser))
Isn't this condition redundant as `$oUser` is typed and mandatory?
Or add a `?` in the function signature.

2023-06-19 09:40 UTC, Molkobain commented on datamodels/2.x/itop-profiles-itil/src/UserProfilesEventListener.php
> +		$sRepairmentProfile = \utils::GetConfig()->GetModuleSetting('itop-profiles-itil', 'poweruserportal-repair-profile', null);
Use underscores instead of dashes.
What about naming the parameter "default_portal_user_profile"?

2023-06-19 09:40 UTC, Molkobain commented on datamodels/2.x/itop-profiles-itil/src/UserProfilesEventListener.php
> +			//when there are further portals we dont want to force a specific portal by repairing the associated profiles to a user
```suggestion
		
		if (is_null($sRepairmentProfile) && count($aPortalDispatcherData) > 2){
			// When there are several portals we don't want to force a specific portal by repairing the associated profiles to a user as we don't know which portal instance should be the default one ("Greater than 2" as the "backoffice" is considered as a "portal" here)
```

2023-06-26 12:59 UTC, odain-cbd commented on datamodels/2.x/itop-profiles-itil/src/UserProfilesEventListener.php
> +		if (!is_null($oUser))
il will add ? and leave this function public. that way anyone can reuse this API even with null User.

2023-06-28 16:44 UTC, Molkobain requested changes

2023-06-28 16:44 UTC, Molkobain commented on datamodels/2.x/itop-profiles-itil/datamodel.itop-profiles-itil.xml
> +  </dictionaries>
```suggestion
  <dictionaries>
    <dictionary id="EN US">
      <entries>
        <entry id="Class:User/NonStandaloneProfileWarning" _delta="define">User profile %1$s cannot be standalone. You should add
          other prrofiles otherwise you may encounter access issue with this user.</entry>
      </entries>
    </dictionary>
    <dictionary id="FR FR">
      <entries>
        <entry id="Core:DeletedObjectLabel" _delta="define">Le profil %1$s ne peut être seul. Sans rajout d'autres profiles,
          l'utilisateur peut rencontrer des problèmes dans iTop.</entry>
      </entries>
    </dictionary>
  </dictionaries>
```

You don't need the `_alteration` flags, did you do this through the ITSM Designer?
Also, you don't the node I removed as they are for the language definition and both english / french are already present.

2023-06-28 16:44 UTC, Molkobain commented on core/config.class.inc.php
> +		'security.single-profile-completion' => [
```suggestion
		'security.single_profile_completion' => [
```

We use underscores instead of dashes.

2023-06-28 16:44 UTC, Molkobain commented on datamodels/2.x/itop-profiles-itil/src/UserProfilesEventListener.php
> +	const USERPROFILE_REPAIR_ITOP_PARAM_NAME = 'security.single-profile-completion';
```suggestion
	const USERPROFILE_REPAIR_ITOP_PARAM_NAME = 'security.single_profile_completion';
```

2023-06-28 19:28 UTC, odain-cbd commented on datamodels/2.x/itop-profiles-itil/datamodel.itop-profiles-itil.xml
> +  </dictionaries>
sorry XML built via a copy/paste from datamodel-production. i will fix.

FR entry id was incorrect as well...

2023-06-28 19:30 UTC, odain-cbd commented on core/config.class.inc.php
> +		'security.single-profile-completion' => [
ok i will rename it

2023-06-29 08:04 UTC, Molkobain requested changes

2023-06-29 08:04 UTC, Molkobain commented on addons/userrights/userrightsprofile.class.inc.php
> +			"is_link" 			  => true, //since 3.1 N°5324
```suggestion
```

Done in [12dbd0e](https://github.com/Combodo/iTop/commit/12dbd0ed3da279e49ae4858055ebc05180c913d8)

2023-06-29 08:04 UTC, Molkobain commented on addons/userrights/userrightsprofile.db.class.inc.php
> +			"is_link" 			  => true, //since 3.1 N°5324
```suggestion
```

Done in [12dbd0e](https://github.com/Combodo/iTop/commit/12dbd0ed3da279e49ae4858055ebc05180c913d8)

2023-06-29 08:04 UTC, Molkobain commented on addons/userrights/userrightsprojection.class.inc.php
> +			"is_link" 			  => true, //since 3.1 N°5324
```suggestion
```

Done in [12dbd0e](https://github.com/Combodo/iTop/commit/12dbd0ed3da279e49ae4858055ebc05180c913d8)

2023-06-29 08:04 UTC, Molkobain commented on core/datamodel.core.xml
> +          <is_link>1</is_link> <!-- since 3.1 N°5324 -->
```suggestion
```

Done in [12dbd0e](https://github.com/Combodo/iTop/commit/12dbd0ed3da279e49ae4858055ebc05180c913d8)

2024-01-10 16:42 UTC, piRGoif commented
Discussed with Olivier : the functionality was implemented differently and merged.
Closing this PR !

2024-01-10 16:42 UTC, closed without merging