N°3363 - Add favicon in branding
Combodo/iTop pull request #522
Opened 2023-07-07 08:49 UTC by accognet

Add 2 methods to custom favicon : first in xml : 
`  
<branding>
   <favicon _delta="define">
       <fileref ref="logo_rvb"/>
    </favicon>
</branding>
`
and the second one in configuration file : 
`
// favicon: url of favicon. Default null in order to take value given by the designer
'favicon' => '/itop/images/info.png',
`

2023-08-08 12:00 UTC, Molkobain requested changes
Review not complete, I'll dig more into it later.

2023-08-08 12:00 UTC, Molkobain commented on core/config.class.inc.php
> +		'favicon'                           => [
Rename and compartiment it to "branding.favicon_url" like we did for all new parameters and also to show that intent is an URL.

2023-08-08 12:00 UTC, Molkobain commented on core/config.class.inc.php
> +	public function GetUrl($sPropCode)
Add type hint and rename to `GetHttpUrl` so we explicit it's only for that protocol as we prepend the AbsRootUrl in case of relative URL.

2023-08-08 12:00 UTC, Molkobain commented on core/config.class.inc.php
> +	 * @return ?string
Explain that the value will be prepend with the app root URL in case it's not an absolute URL

2023-08-08 12:00 UTC, Molkobain commented on core/config.class.inc.php
> +		$sUrl = utils::StartsWith($sValue, "http") ? $sValue : utils::GetAbsoluteUrlAppRoot().$sValue;
An URL is not necessarily with the HTTP(S) protocol, so we might want to rethink that, maybe in technicalk review.

2023-08-08 14:55 UTC, Molkobain commented
Accepted during functional review for 3.2.0

Update conf. param. description to explain that it will override the one defined in the datamodel

2023-08-09 07:22 UTC, Molkobain requested changes

2023-08-09 07:22 UTC, Molkobain commented on application/loginwebpage.class.inc.php
> +
To factorize in a `\Branding::GetConfigFavIconOverride()` method and called in `\Branding::GetLoginFavIconAbsoluteUrl()`

2023-08-09 07:22 UTC, Molkobain commented on core/config.class.inc.php
> +			'description'         => 'url of favicon. Default null in order to take value given by the designer',
```suggestion
			'description'         => 'Overrides the favicon defined in the datamodel for all GUIs (login, backoffice, portals). Value can be either an URL relative to iTop root folder or an absolute URL',
```

2023-08-09 07:22 UTC, Molkobain commented on core/config.class.inc.php
> +			'value'               => '',
```suggestion
			'value'               => null,
```

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/WebPage/UnauthenticatedWebPage.php
> +
To factorize in a `\Branding::GetConfigFavIconOverride()` method and called in `\Branding::GetLoginFavIconAbsoluteUrl()`

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/WebPage/WebPage.php
> +
To factorize in a `\Branding::GetConfigFavIconOverride()` method and called in `\Branding::GetMainFavIconAbsoluteUrl()`

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/WebPage/UnauthenticatedWebPage.php
> +	protected function GetFaviconAbsoluteUrl()
Don't put a protected method before the constructor, put it after `LoadTheme()`

2023-08-09 07:22 UTC, Molkobain commented on application/loginwebpage.class.inc.php
> +	protected function GetFaviconAbsoluteUrl()
Don't put a protected method before the constructor, put it before / after `SetStylesheet()` for example to group methods of the same domain.

2023-08-09 07:22 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
> -					$aPortalConf['properties'][$oPropertyNode->nodeName] = $oPropertyNode->GetText(
Good catch

2023-08-09 07:22 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
> +	 * @throws \Exception
```suggestion
	 * @throws \Exception
	 * @since 3.2.0 N°3363
```

2023-08-09 07:22 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
> +		$sFaviconUri = \MetaModel::GetConfig()->GetUrl('favicon');
```suggestion
		$sFaviconUri = \utils::GetConfig()->GetUrl('favicon');
```

2023-08-09 07:22 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/templates/layout.html.twig
> +<link rel="shortcut icon" href="{{ app['combodo.portal.instance.conf'].properties.favicon }}"/>
```suggestion
<link rel="shortcut icon" href="{{ app['combodo.portal.instance.conf'].properties.favicon|add_itop_version }}"/>
```

Otherwise the favicon might still be in cache after a change in the datamodel or configuration.

2023-08-09 07:22 UTC, Molkobain commented on setup/compiler.class.inc.php
> +				['sNodeName' => 'login_favicon', 'sTargetFile' => 'login_favicon', 'sType' => Branding::ENUM_LOGO_TYPE_LOGIN_FAVICON],
```suggestion
				['sNodeName' => 'login_favicon', 'sTargetFile' => 'login_favicon', 'sType' => Branding::ENUM_LOGO_TYPE_LOGIN_FAVICON],
				['sNodeName' => 'main_favicon', 'sTargetFile' => 'main_favicon', 'sType' => Branding::ENUM_LOGO_TYPE_MAIN_FAVICON],
				['sNodeName' => 'portal_favicon', 'sTargetFile' => 'portal_favicon', 'sType' => Branding::ENUM_LOGO_TYPE_PORTAL_FAVICON],
```

_Just keeping things organized in the same order._

2023-08-09 07:22 UTC, Molkobain commented on setup/itopdesignformat.class.inc.php
This will be discussed during technical review, we might leave nodes when downgrading the XML. There was some discussion about this during the 3.1 development.

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/Branding.php
> +	public const ENUM_LOGO_TYPE_LOGIN_FAVICON = 'login_favicon ';
Add `@since 3.2.0 N°3363`

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/Branding.php
> +	protected static function GetLogoPath(string $sType, string $sAppPath, ?string $sModulePath = null): ?string
We have to discuss this, this is changing the return type for logos as well, when they cannot be null.

2023-08-09 07:22 UTC, Molkobain commented on sources/Application/Branding.php
> +	/**
For all 3 methods:
*  Add `@since 3.2.0 N°3363`
*  Add return type `?string`
* Remove logs

2023-09-05 14:33 UTC, piRGoif commented
Technical review : not ready, Anne Catherine will update this PR

2023-09-20 12:00 UTC, Molkobain commented
This new approach (several brandings) changes a lot a things unlike the original approach.
It is neither the same need nor the same ticket.

If you want to go with several brandings:
- Create a dedicated ticket in the bug tracker and rename the PR accordingly.
- Then we shall discuss with @rquetiez and @v-dumas about the specs of having multiple brandings.
- (Then finish to handle XML properly, merge old branding config. param., ...)

If you want to go back to just adding the favicon to the branding:
- Rollback changes to what we originally discussed
- Drop the config. param. to define which favicon to use, it should be done in the other approach

2023-09-20 12:01 UTC, Molkobain requested changes
This new approach (several brandings) changes a lot a things unlike the original approach.
It is neither the same need nor the same ticket.

If you want to go with several brandings:
- Create a dedicated ticket in the bug tracker and rename the PR accordingly.
- Then we shall discuss with @rquetiez and @v-dumas about the specs of having multiple brandings.
- (Then finish to handle XML properly, merge old branding config. param., ...)

If you want to go back to just adding the favicon to the branding:
- Rollback changes to what we originally discussed
- Drop the config. param. to define which favicon to use, it should be done in the other approach

2024-02-27 13:26 UTC, Molkobain requested changes
Almost good, only thing missing is to update the unit test about XML conversion.
- Add dedicated files for 3.1 <=> 3.2 conversion (mind to put **only** what is relevant to keep the test case clear, see other files) in `tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples`
- Add the test case in `\Combodo\iTop\Test\UnitTest\Setup\iTopDesignFormatTest::ConvertProvider()`

2024-02-28 08:57 UTC, Molkobain approved these changes

2024-02-28 08:58 UTC, Molkobain commented
Great! You can squash & merge.

2024-02-28 08:59 UTC, merged