N°3441 - Portal : link to an archived object
Combodo/iTop pull request #523
Opened 2023-07-11 12:19 UTC by larhip

Portal : cannot open an object containing a link to an archived object

2023-07-11 12:32 UTC, Molkobain commented
_Moving to functional review as it will be this afternoon and we might have to discuss expected behavior._

2023-07-11 21:05 UTC, Molkobain commented
Functional review:
- Ok to avoid crashes and display the information in read-only instead
- We would go furthermore with the display and be similar to what is done in the back office with the "archive" icon prefixed (see screenshot below)

Thanks for the PR Lars!

2023-07-12 06:49 UTC, larhip commented
Thanks @Molkobain for your feedback.

Display an archive icon in the portal as well is done now.

It might be checked during technical review, wehster there is some smarter way to do so.
I was also thinking about using the method DBObject::GetHyperlink to do it in a similar way like the back office. So something like this:

```
if ($this->oField->GetCurrentValue() !== null && $this->oField->GetCurrentValue() !== 0 && $this->oField->GetCurrentValue() !== '')
{
	// Note : AllowAllData set to true here instead of checking scope's flag because we are displaying a value that has been set and validated
	$oFieldValue = MetaModel::GetObjectWithArchive($sFieldValueClass, $this->oField->GetCurrentValue(), true, true);
	$sFieldHtmlValue = $oFieldValue->GetHyperlink();
}
else
{
	$sFieldHtmlValue = Dict::S('UI:UndefinedObject');
}
```

But in this case the archived icon will be displayed as well and the attribute `data-toggle="itop-portal-modal"` is missing..

2023-07-12 07:29 UTC, Molkobain commented
Indeed, methods in `\DBObject` or `\AttributeDefinition` are backoffice-oriented, so we can't rely on them for now. What you did goes in the right direction, I'll take a closer look during the review :)

2023-08-03 21:12 UTC, Molkobain requested changes

2023-08-03 21:12 UTC, Molkobain commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive object-archived fa-1x fa-fw"></span></span>' . $sFieldHtmlValue;
```suggestion
					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive"></span></span>' . $sFieldHtmlValue;
```

I would defintively remove the `fa-1x fa-fw` classes as they are not necessary here, it will be more consistent with the other decorations (email, phone, ...).

Regarding the `object-archived` class, I have mixed feelings. We don't have convention yet for that type of meta-information in the portal, but we could still add it and migrate it in the future.

So once suggestion is applied, it will be ok for me.

2023-08-03 21:14 UTC, Molkobain commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive object-archived fa-1x fa-fw"></span></span>' . $sFieldHtmlValue;
_I cant' apply the suggestion myself as the PR doesn't seem to allow editing for maintainers. The I'll push it through functional review on tuesday, then it should be merged._

2023-08-04 05:55 UTC, larhip commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive object-archived fa-1x fa-fw"></span></span>' . $sFieldHtmlValue;
I always forget to set this option during PR creation and I am not able to change it later :-(

Anyhow I just committed your suggestions.

Thanks for your feedback and the review :-)

2023-08-04 07:01 UTC, Molkobain approved these changes

2023-08-04 08:07 UTC, Hipska commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive object-archived fa-1x fa-fw"></span></span>' . $sFieldHtmlValue;
Yes, as this option doesn't seem to exist anymore (or disabled for this repo?)
<img width="1257" alt="image" src="https://github.com/Combodo/iTop/assets/228588/89f047f3-50ae-4a05-851f-98b848474509">

2023-08-04 08:37 UTC, piRGoif commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					$sFieldHtmlValue = '<span class="text_decoration"><span class="fas fa-archive object-archived fa-1x fa-fw"></span></span>' . $sFieldHtmlValue;
Hello,
I guess the option appearance would be based on the fork options instead of the initial repository options ? 

I'v just checked [the documentation](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) again : there is now a red warning box stating "If your fork contains GitHub Actions workflows, the option is Allow edits and access to secrets by maintainers."

Also seems like it is again possible to change an existing PR : "Additionally, you can modify an existing pull request to let repository maintainers make commits to your branch." ?

2023-08-08 14:24 UTC, Molkobain commented
Accepted during functional for 3.1.1 as it can be blocking for people archiving objects.

2023-08-09 09:44 UTC, Molkobain commented
Hello Lars,

Could you rebase your branch on support/3.1 so we can merge it?
If you are not comfortable doing so, feel free to ask. :)

2023-08-09 10:04 UTC, larhip commented
Hi Guillaume,

should be done now, could you please check again?

2023-08-10 07:17 UTC, Molkobain requested changes

2023-08-10 07:17 UTC, Molkobain commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +					CombodoPortalToolbox.OpenModal({
```suggestion
					CombodoModal.OpenModal({
```

Revert this, it is not related to that PR and this API has been deprecated.

2023-08-10 07:17 UTC, Molkobain commented on sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
> +				CombodoPortalToolbox.OpenModal(oOptions);
```suggestion
				CombodoModal.OpenModal(oOptions);
```
Revert this, it is not related to that PR and this API has been deprecated.

2023-08-10 07:19 UTC, Molkobain commented
I'm sorry Lars but I still can't apply suggestions :/

Could you apply the 2 I just made, I didn't noticed them earlier but you changed the usages to the deprecated API.
You should be able to apply the suggestion directly from GitHub GUI.

Then I'll be able to merge, the rebase was done correctly 👍

2023-08-10 07:42 UTC, larhip commented
Hi Guillaume,

I have just committed your suggestions, so you should be able to merge now.
BTW: When I got it correctly it is not able to set the option "editable by maintainers" if the fork belong to an organization.
Which means it should be possible to set the option for an PR is created from larhip/iTop but not from itomig-de/iTop.
Maybe I could do a quick test today :-)

2023-08-10 07:48 UTC, Hipska commented
> BTW: When I got it correctly it is not able to set the option "editable by maintainers" if the fork belong to an organization. Which means it should be possible to set the option for an PR is created from larhip/iTop but not from itomig-de/iTop.

Ooh, this is interesting.. The same problem I'm running into.

2023-08-10 07:48 UTC, Molkobain commented
> > BTW: When I got it correctly it is not able to set the option "editable by maintainers" if the fork belong to an organization. Which means it should be possible to set the option for an PR is created from larhip/iTop but not from itomig-de/iTop.
> 
> Ooh, this is interesting.. The same problem I'm running into.

Indeed, it's a shame though 😁

2023-08-10 07:49 UTC, Molkobain commented
> Hi Guillaume,
> 
> I have just committed your suggestions, so you should be able to merge now. [...]

Perfect thanks, merge incoming!

2023-08-10 07:51 UTC, Molkobain approved these changes

2023-08-10 07:52 UTC, merged

2023-08-10 08:03 UTC, larhip commented
Just tested it, it is for real related to the owner of the fork (organization vs. personal):

Personal fork:
![image](https://github.com/Combodo/iTop/assets/24569763/6c7e627c-091c-41c4-829c-9f8fc1a9beba)

Organization fork:
![image](https://github.com/Combodo/iTop/assets/24569763/5f3d59b5-561a-482b-b979-320c2f36fbaa)

2023-08-10 08:06 UTC, Molkobain commented
Thanks for the feedback Lars! @piRGoif you might interested by this.

2023-08-10 08:07 UTC, Hipska commented
hmm, could be worked around that?

2023-08-10 09:07 UTC, piRGoif commented
Wooo ! Many thanks Larhip ! I didn't saw this in the documentation :(
I already saw issues opened for GitHub bugs/enhancement, maybe we could open one ?

2023-08-10 09:08 UTC, Hipska commented
Please do and let us know the reference..

2023-09-05 15:28 UTC, piRGoif commented
Well, the issue already exists : https://github.com/orgs/community/discussions/5634
I've just added a comment. Feel free to add yours, and vote !