N°5786 - Problem with text color in public log and in AttributeHTML
Combodo/iTop pull request #527
Opened 2023-07-31 09:53 UTC by accognet

Internal

2023-08-10 07:26 UTC, Molkobain requested changes

2023-08-10 07:26 UTC, Molkobain commented on css/backoffice/vendors/_bulma-variables-overload.scss
> +$text-strong: inherit !default;;
```suggestion
/*N°5786 - Avoid strong text to always be grey (default Bulma color for this var.) so strong text can keep its color. This  is mostly for text within the .ibo-is-html-content. */
$text-strong: inherit !default;
```

2023-08-10 08:19 UTC, Molkobain approved these changes

2023-08-10 08:20 UTC, Molkobain commented
@steffunky the drawback is that it applies to more than the .ibo-is-html-content, but as we don't use bulma classes much, I felt it was okay. What do you think?

2023-08-10 09:03 UTC, steffunky commented
Doest it affect Alerts block ?
Or Backoffice communications' alerts ?

2023-09-01 14:28 UTC, accognet commented
Yes, it solves the same problem

2023-09-05 14:44 UTC, piRGoif commented
Technical review : OK

2023-09-12 15:00 UTC, piRGoif commented
Functional review : OK

2023-10-17 10:09 UTC, merged