Feature/3448 field size check not correctly implemented
Combodo/iTop pull request #528
Opened 2023-07-31 13:58 UTC by accognet

internal

2023-07-31 14:37 UTC, Hipska requested changes
Don't forget to also change the `substr` functions as you might get unexpected results otherwise..

2023-07-31 14:37 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
YOYO? 🤓

2023-07-31 14:37 UTC, Hipska commented on webservices/webservices.class.inc.php
>  				$sValue = substr($sValue, 0, $iMaxSize);
```suggestion
				$sValue = mb_substr($sValue, 0, $iMaxSize);
```

2023-07-31 14:37 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
>  			$sWarningMessage = substr($sWarningMessage, 0, $MAX_WARNING_LENGTH - 3).'...';
```suggestion
			$sWarningMessage = mb_substr($sWarningMessage, 0, $MAX_WARNING_LENGTH - 3).'...';
```

2023-07-31 14:37 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
>  			$sText = substr($sText, 0, 200).'...('.strlen($sText).' chars)...';
```suggestion
			$sText = mb_substr($sText, 0, 200).'...('.strlen($sText).' chars)...';
```

2023-07-31 14:37 UTC, Hipska commented on core/event.class.inc.php
> +			$this->Set('issue', substr($this->Get('issue'), 0, 210)." -truncated ($sLength chars)");
```suggestion
			$this->Set('issue', mb_substr($this->Get('issue'), 0, 210)." -truncated ($sLength chars)");
```

2023-07-31 14:37 UTC, Hipska commented on core/event.class.inc.php
> +			$this->Set('impact', substr($this->Get('impact'), 0, 210)." -truncated ($sLength chars)");
```suggestion
			$this->Set('impact', mb_substr($this->Get('impact'), 0, 210)." -truncated ($sLength chars)");
```

2023-07-31 14:37 UTC, Hipska commented on core/event.class.inc.php
> +			$this->Set('page', substr($this->Get('page'), 0, 210)." -truncated ($sLength chars)");
```suggestion
			$this->Set('page', mb_substr($this->Get('page'), 0, 210)." -truncated ($sLength chars)");
```

2023-07-31 14:37 UTC, Hipska commented on core/dbobject.class.php
>  			$sValue = substr($sValue, 0, $iMaxSize);
```suggestion
			$sValue = mb_substr($sValue, 0, $iMaxSize);
```

2023-07-31 15:06 UTC, accognet commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
Yes, modify or not ? I'm not familiar with this code and I don't want to forget to discuss it 😁

2023-07-31 15:12 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
I get the meaning, but what does the YOYO abbreviation stand for?

2023-08-03 12:55 UTC, piRGoif commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
You may instead use a classic TODO or FIXME, they are recognized by default by most IDE including PHPStorm.
Maybe something like : `//TODO PR #528 to discuss : should we modify or not ?`

2023-08-03 12:57 UTC, Hipska commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
Is it a French abbreviation perhaps?

2023-08-03 13:13 UTC, piRGoif requested changes
First, many thanks to propose a fix for this bug ! I don't like having it around, and the ticket not planned :/

I agree with Hipska suggestions...
I propose some modifications in the test.

We will discuss about your fix on next technical review, but I'm not sure why there are so much methods touched ? I would say, either we are touching only the code involved in the ticket use cases, or we replace any substr() and strlen() call by their mb_* equivalent ? There are lots remaining...

2023-08-03 13:13 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			'Title with ééé'            => [
Seems like the use case in the original ticket, but you should describe it : something like 'Title with 200 é, failing before N°3448'

2023-08-03 13:13 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			'Title with smiley'         => [
Same, I would go with something like "title with 232 characters, ending with smileys (259 bytes)"

2023-08-03 13:13 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			'Title with 255 characters' => [
```suggestion
			'Title with 255 characters,  us-ascii only' => [
```

2023-08-03 13:13 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +		];
In the original ticket there was an issue also with loading an email in a 64KB blob fiels (I guess a TEXT ?)
It would be nice to test that too !

2023-08-03 13:13 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			$oPerson->Set('org_id', $this->getTestOrgId());*/
Remove code in comment

And use ItopDataTestCase::CreateUserRequest instead so that object can be rollbacked on tearDown !

2023-08-03 14:08 UTC, accognet commented on synchro/synchrodatasource.class.inc.php
> +		//YOYO or not ?
No, I'm the only one using that word. It's easier to find in the code than a meaningful word :-).

2023-08-04 07:10 UTC, piRGoif commented
As a reference, the mbstring functions list : https://www.php.net/manual/en/ref.mbstring.php

2023-08-07 13:15 UTC, piRGoif commented
> We will discuss about your fix on next technical review, but I'm not sure why there are so much methods touched ? I would say, either we are touching only the code involved in the ticket use cases, or we replace any substr() and strlen() call by their mb_* equivalent ? There are lots remaining...

One of them is solved in #529...

2023-09-05 15:15 UTC, piRGoif commented
Technical review : Anne Catherine and Pierre will improve the test before functional review.

2023-09-07 07:32 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			'Title with ééé'            => [
Solved by Anne Catherine

2023-09-07 07:32 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			'Title with smiley'         => [
Solved by Anne Catherine

2023-09-07 07:33 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			$oPerson->Set('org_id', $this->getTestOrgId());*/
Solved by Anne Catherine

2023-09-12 15:02 UTC, piRGoif commented
Functional review : OK !
Note there is another PR on object deletion : #529

Before merge test review to be done by Pierre.

2023-09-15 07:59 UTC, piRGoif commented
Discussed with Anne Catherine : the test for the 64Ko should be simplified. 
Use case to test:
- a content < 64Ko
- > 64Ko that would cut normally before fix
- > 64Ko that would cut inside a multi bytes character before fix

Pass to the test only the content, and if value is bigger then also the expected cut value

Do the CheckToWrite and SetTrim (if CheckToWrite is returning false when content to big then just do the SetTrim in this case ?)

2023-09-29 06:36 UTC, odain-cbd commented
that's a real progress for our customers! especially those that speak arabic or asian languages....

2023-09-29 11:06 UTC, Hipska approved these changes

2023-12-21 14:33 UTC, piRGoif commented
Tests still to be reviewed. We began last monday, but Anne-Catherine and I will continue after our holidays.

2024-01-09 10:23 UTC, piRGoif commented
Tests reviewed ! Planned PR for functional review.

2024-01-10 08:39 UTC, piRGoif commented
We should rebase the PR, as its starting point is a commit made in... july !!

2024-01-10 08:50 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +		];
Test rewritten with Anne Catherine yesterday, closing this conversation

2024-01-10 08:50 UTC, Molkobain commented
Accepted during functional review for 3.1.2 if finished in time.
Still need to be reviewed technically.

2024-01-10 13:55 UTC, piRGoif approved these changes
Thanks for the rebase ! And also the duplicated test removal !

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			$this->assertEquals($iAttrMaxSize, mb_strlen($sValueInObject));
```suggestion
			$this->assertEquals($iAttrMaxSize, mb_strlen($sValueInObject),'Should truncate at the same length than attribute max length');
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			$this->assertStringContainsString(' -truncated', $sLastCharsOfValueInObject);
```suggestion
			$this->assertStringContainsString(' -truncated', $sLastCharsOfValueInObject, 'Should end with "truncated" comment');
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +			$this->assertEquals($sValueToSet, $sValueInObject);
```suggestion
			$this->assertEquals($sValueToSet, $sValueInObject,'Should not alter string that is already shorter than attribute max length');
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +		$this->assertEquals($bIsValueToSetBelowAttrMaxSize, $bCheckStatus, "CheckResult result:".var_export($aCheckIssues,true));
```suggestion
		$this->assertEquals($bIsValueToSetBelowAttrMaxSize, $bCheckStatus, "CheckResult result:".var_export($aCheckIssues, true));
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +		$this->assertSame($sValueToSet, $sValueInObject);
```suggestion
		$this->assertSame($sValueToSet, $sValueInObject, 'Set should not alter the value even if the value is too long');
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +	 * @covers       DBObject::DBIncrement
```suggestion
	 * @covers       DBObject::Set
	 * @covers       DBObject::CheckToWrite
	 * @covers       DBObject::SetTrim
```

2024-01-15 13:35 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +	 * @covers       DBObject::DBIncrement
```suggestion
	 * @covers       EventIssue::OnInsert
```

2024-01-15 13:50 UTC, Molkobain requested changes

2024-01-15 13:50 UTC, Molkobain commented on core/dbobject.class.php
>  			$sValue = substr($sValue, 0, $iMaxSize);
+1

2024-01-15 13:50 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +		$this->assertEquals($sResult,$oOrganisation->Get('name'),'SetTrim must limit string to 255 characters');
```suggestion
		$oOrganisation->SetTrim('name', $sName);
		$this->assertEquals($sResult, $oOrganisation->Get('name'), 'SetTrim must limit string to 255 characters');
```

2024-01-15 15:10 UTC, merged