N°5547 - Object deletion fails if friendlyname too long
Combodo/iTop pull request #529
Opened 2023-07-31 15:51 UTC by accognet

Internal

2023-12-13 08:28 UTC, Molkobain requested changes
There is something wrong with your PR, 163 commits / 1600 files changed. It's most likely because you rebased on the wrong branch or forgot to change the target branch here.

![image](https://github.com/Combodo/iTop/assets/5130468/4f8e4208-46e9-400b-b3a9-7f85a8aa7aee)

2024-01-15 15:29 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +	 * @covers       DBObject::DBIncrement
```suggestion
	 * @covers       DBObject::DBDelete
```

2024-01-22 13:57 UTC, Molkobain commented
Support PR review: Technically ok, ready for functional review

2024-01-22 18:44 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +				str_repeat('e',250),
```suggestion
				str_repeat('e', 250),
```

2024-01-22 18:44 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +				str_repeat('e',250),
```suggestion
				str_repeat('e', 250),
```

2024-01-22 18:44 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +			$oDeletionPlan = $this->InvokeNonPublicMethod(CMDBObject::class,'RecordObjDeletion',$oPerson, [$oPerson->GetKey()]);
```suggestion
			$oDeletionPlan = $this->InvokeNonPublicMethod(CMDBObject::class, 'RecordObjDeletion', $oPerson, [$oPerson->GetKey()]);
```

2024-01-22 18:44 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +
```suggestion
```

2024-01-22 18:44 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +
```suggestion
```

2024-01-22 18:44 UTC, Molkobain approved these changes

2024-01-23 08:34 UTC, piRGoif requested changes
Thanks for the modifications ! Good work !
I just see those 2 details remaining

2024-01-23 08:34 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +		// Create a UserRequest with 2 contacts
This comment is false and can be removed

2024-01-23 08:34 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
> +
Maybe revert this change if possible ?

2024-01-23 09:02 UTC, Molkobain approved these changes

2024-01-23 09:02 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +			'friendlyname longer than 255 characters ending with multi-bytes characters' => [
```suggestion
			'friendlyname longer than 255 characters which will be truncated on a multi-bytes characters' => [
```

2024-01-23 09:02 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +			'friendlyname longer than 255 characters ending with single byte characters' => [
```suggestion
			'friendlyname longer than 255 characters which will be truncated after a single byte characters' => [
```

2024-01-23 10:39 UTC, accognet commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +		// Create a UserRequest with 2 contacts
done

2024-02-05 13:26 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +	public function testRecordObjDeletionProvider()
```suggestion
	public function RecordObjDeletionProvider()
```

2024-02-05 13:26 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +	 * @dataProvider testRecordObjDeletionProvider
```suggestion
	 * @dataProvider RecordObjDeletionProvider
```

2024-02-05 13:30 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +		$this->assertTrue($bDeletionOK);
```suggestion
		// We d'ont need to test the result (truncated string), it's already done in \DBObject::SetTrim() with N°3448
		$this->assertTrue($bDeletionOK);
```

2024-02-05 13:30 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
> +		// We d'ont need to test the result (truncated string), it's already done in \DBObject::SetTrim() with N°3448
```suggestion
		// We don't need to test the result (truncated string), it's already done in \DBObject::SetTrim() with N°3448
```

2024-02-05 13:33 UTC, Molkobain commented
Accepted during support PRs review with Anne-Cath, Pierre & Romain.
PR will reviewed in functional review next week.

We would like it to be merged in support/3.1 as the previous / similar issue was also merged in 31.

2024-02-14 18:34 UTC, Molkobain commented
Accepted during functional review
@accognet you can "squash & merge", please mind to keep the PR number in the commit.

2024-02-14 18:36 UTC, Molkobain commented
Also mind to rebase your PR branch on support/3.1 AND to change the target branch here on the PR to support/3.1

2024-02-27 16:59 UTC, merged