N°6619 - Attachment : Make contact_id an AttributeExternalKey instead of AttributeExternalField
Combodo/iTop pull request #532
Opened 2023-08-02 12:41 UTC by accognet

Description here : [https://sourceforge.net/p/itop/tickets/2167/](url)

2023-08-09 07:26 UTC, Molkobain requested changes

2023-08-09 07:26 UTC, Molkobain commented on datamodels/2.x/itop-attachments/module.itop-attachments.php
> +			if (version_compare($sPreviousVersion, '3.2.0', '<')) {
Test whether the attribute exists in the datamodel rather than the version number.

2023-08-09 07:26 UTC, Molkobain commented on datamodels/2.x/itop-attachments/module.itop-attachments.php
> +				$sAddContactId = "UPDATE `$sTableName` att, `$sUserTableName` us SET att.contact_id = us.contactid WHERE att.user_id = us.id AND att.contact_id = 0";
Get column name from the attribute definition instead of hardcoding it as they can differ between the datamodel and the database.

We need to check with others if `\MetaModel::GetAttributeDefinition()->Get('sql')` is the right method to do so.

2023-09-18 22:04 UTC, Molkobain approved these changes
Good job!

2023-09-19 07:04 UTC, Hipska commented on datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
> +              $this->SetIfNull('contact_id', $oUser->Get('contactid'));
Isn't there a better (already cached) way to retrieve the current user, or the current contact (id)?

2023-09-19 08:51 UTC, piRGoif commented on datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
> +              $this->SetIfNull('contact_id', $oUser->Get('contactid'));
Mind this code can be called from CLI context where it isn't the connected User we want to get...

2023-09-19 14:00 UTC, Molkobain commented on datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
> +              $this->SetIfNull('contact_id', $oUser->Get('contactid'));
> Isn't there a better (already cached) way to retrieve the current user, or the current contact (id)?

In that particular case (`CMDBChange::GetCurrentUserId()`) we retrieve the ID of the "real" user (in case of impersonation).
We can't use `UserRights::GetContactId()` as it will retrieve the wrong Contact ID in case of impersonation.

We might need to add the necessary APIs to manipulate the "real" contact as well.
I'm not an expert of that part, it would be good to discuss with @rquetiez as well.

Personally I don't think this is a blocking issue. That pattern is used amongst the app, we can choose to improve its performances but it can be part of another PR with a broader scope.

2023-09-19 14:04 UTC, Molkobain commented
Moved the PR to "technical review" as HIspka's point will discussed there.

2023-11-07 16:21 UTC, Molkobain commented on datamodels/2.x/itop-attachments/module.itop-attachments.php
> +				$sAddContactId = "UPDATE `$sTableName` att, `$sUserTableName` us SET att.$sAttachmentFieldContactId = us.$sUserFieldContactId WHERE att.$sAttachmentFieldUserId = us.id AND att.$sAttachmentFieldCo
```suggestion
				$sAddContactId = "UPDATE `$sTableName` att, `$sUserTableName` us SET att.`$sAttachmentFieldContactId` = us.`$sUserFieldContactId` WHERE att.`$sAttachmentFieldUserId` = us.id AND att.`$sAttachmentFieldContactId` = 0";
```

2023-11-07 16:21 UTC, Molkobain commented
Accepted during technical review, Anne-Cath you can merge.

2023-11-07 16:32 UTC, piRGoif commented on datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
> +              $this->SetIfNull('contact_id', $oUser->Get('contactid'));
Discussed during technical review, where Romain was present.

We do have a cached user with \UserRights::GetUser, but this represent the logged in user. 

But with attachment, we can create instances with a different user than the logged one... For example in the Mail To Ticket background process, on each mail processed we are getting the corresponding user and setting it to be used by the history API. So we must use the history API to get the correct user (that's what we are doing with CMDBChange::GetCurrentUserId())

For now only the user id is saved by the history API. 
We think that in Attachment::DBInsertNoReload, getting the User object from the id saved in the history API won't be that bad ?

2024-02-05 13:07 UTC, merged

2024-03-08 16:19 UTC, Molkobain commented
For the record, we missed a missing "allow all data" when setting the user_id which causes a regression in the portal. Fixed with [0c3e839](https://github.com/Combodo/iTop/commit/0c3e839381fb70ad7856576de4fc1da17278dfa2)