N°1681 - Notification on Attachment creation
Combodo/iTop pull request #534
Opened 2023-08-03 14:00 UTC by accognet

Create a new trigger "on object's attachment creation"

2023-08-22 09:03 UTC, Molkobain requested changes
Discussed IRL with Anne-Catherine, several things to change:

**Point 1**
Hacking the standard "Trigger on update" with JS to remove the "Attachment" class from proposed value doesn't seem like a good option.

Instead we would rather improve the `\AttributeClass` class to add a `class_exclusion_list` like we do for `\AttributeClassAttCodeSet` with `attribute_definition_exclusion_list`. Check with @rquetiez or @eespie , they can guide you.

**Point 2**
The way it is currently done, you can't limit the trigger to attachments of a specific class only, which is most likely something we'll want to do.

**Point 3**
Because of the previous points, you can't rely on the ComputeValues method and the fact it derived from the standard TriggerOnObjectUpdate, you'll need to call your trigger when attachments are finalized. We might want to add an event for that actually, check with Eric.

2023-08-30 07:22 UTC, Hipska commented
May I ask why the existing triggers aren’t sufficient?

2023-08-30 07:29 UTC, accognet commented
It does but to get an attachment creation notification, we need to create an "on object update" trigger on the attachment with the temp_id field. It's not really logical.

2023-10-25 12:45 UTC, Molkobain commented
During the technical review, we'll need to discuss the possible impacts of adding the `class_exclusion_list` property on the existing `AttributeClass` attribute: 
  * Can it be omitted in an `AttributeClass` instantiation (existing customizations using that type of attribute)
  * Create the corresponding Designer ticket
  * ...

2024-09-03 14:57 UTC, Molkobain commented on core/attributedef.class.inc.php
> +		return array_merge(parent::ListExpectedParams(), array('class_category', 'more_values', 'class_exclusion_list'));
Discussed during technical review: We'll actually remove it from expected params as it would force any `AttributeClass` usage to provide it, which would lead to regression on any module / custos using it.

We'll just add a comment to inform that this option exists.

2024-10-18 10:25 UTC, larhip commented on core/trigger.class.inc.php
> +			array("class_category" => "bizmodel", "more_values" => "User,UserExternal,UserInternal,UserLDAP,UserLocal", "sql" => "target_class", "default_value" => null, "is_null_allowed" => false, "depends_o
Just a note: Since there is no `TriggerOnAttachmentCreate` actually, I know of some iTop instances that use a TriggerOnObject with a target class `Attachment`.
Your implementation will make this impossible in the future, so you are forcing these people to migrate. At least this should be documented, as it may be a breaking change for some iTop instances?

I assume that in such a case (Triggers with target class `Attachment` already exist) the setup will not break, but there will be a warning in the DB tools? Have you checked this?

2024-10-23 09:25 UTC, rquetiez commented on core/trigger.class.inc.php
> +			array("class_category" => "bizmodel", "more_values" => "User,UserExternal,UserInternal,UserLDAP,UserLocal", "sql" => "target_class", "default_value" => null, "is_null_allowed" => false, "depends_o
One effect for the end-user (verified) is that, when opening the form to edit the trigger, the "class" value is reset and prevents the user from modifying it (mandatory field).

In order to preserve this constraint, a solution would be to migrate automatically the existing triggers at setup time (ModuleInstaller). Could be implemented in the form of a helper in ModuleInstallerAPI.

2024-11-28 13:59 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/nl.dict.itop-attachments.php
> +	'Class:TriggerOnAttachmentDelete+'                        => 'Trigger on object\'s attachment delete~~',
```suggestion
    'Class:TriggerOnAttachmentCreate'                         => 'Trigger (Bij het toevoegen van een bijlage)',
    'Class:TriggerOnAttachmentCreate+'                        => 'Trigger bij het toevoegen van een bijlage aan een object van de opgegeven klasse (of subklasse ervan)',
	'Class:TriggerOnAttachmentCreate/Attribute:file_in_email' => 'Bestand toevoegen in e-mail',
	'Class:TriggerOnAttachmentCreate/Attribute:file_in_email+'=> 'If checked, the file will be automatically attached to the email when an email action is triggered~~',
	'Class:TriggerOnAttachmentDelete'                         => 'Trigger (Bij het verwijderen van een bijlage)',
	'Class:TriggerOnAttachmentDelete+'                        => 'Trigger bij het verwijderen van een bijlage van een object van de opgegeven klasse (of subklasse ervan)',
```

2024-12-09 13:20 UTC, rquetiez commented
Code review : dehardcode the banner message (ongoing)
Other developments in the current PR, that must be documented in the corresponding ticket: hide the "edit" button, automatically add the attachment to an email on user demand

2024-12-10 08:33 UTC, merged