N°5170 - In a transition DoCheckToWrite returned error, generes a Fatal error
Combodo/iTop pull request #539
Opened 2023-08-08 11:55 UTC by accognet

Internal

2023-09-12 14:57 UTC, piRGoif commented
Functional review : OK for 3.1.1

2023-09-20 11:36 UTC, Molkobain requested changes
Did you discussed it with Vincent? I'm not sure it doesn't exactly what the spec says.

2023-09-20 11:36 UTC, Molkobain commented on pages/UI.php
> +					$aIssues = $e->getIssues();
Why retrieve this? It doesn't seem to be used.

2023-09-20 11:36 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Form/ObjectFormManager.php
> +			$aData['messages']['error'] += array('_main' => array($e->getHtmlMessage()));
Are you sure you want the HTML message? It could lead to XSS.

2023-09-20 11:36 UTC, Molkobain commented on pages/UI.php
> +					$sMessage = $e->getHtmlMessage();
Are you sure you want the HTML message? It could lead to XSS.

2023-09-20 11:36 UTC, Molkobain commented on application/cmdbabstract.class.inc.php
> +
This duplicates the lock release logic, I would rather try something like the following. But it needs another look to it. (Mind that it factorize lines 3594-3603 as well but I can't modify them in the PR)

```suggestion
			try {
				$bApplyStimulus = $this->ApplyStimulus($sStimulus); // Will write the object in the DB
			}
			catch (Exception $oException) {
				// Catch any exception happening during the stimulus
				$bApplyStimulus = false;
				throw $oException;
			}
			finally {
				if (!$bApplyStimulus) {
					// Throw an application oriented exception if necessary
					throw new ApplicationException(Dict::S('UI:FailedToApplyStimuli'));
				} else {
					if ($sOwnershipToken !== null) {
						// Release the concurrent lock, if any
						iTopOwnershipLock::ReleaseLock($sClass, $iKey, $sOwnershipToken);
					}

				return true;
			}

```

2023-09-21 15:35 UTC, accognet commented on application/cmdbabstract.class.inc.php
> +
This code does not have the same behavior as the one I wrote....

2023-09-21 15:36 UTC, accognet commented on datamodels/2.x/itop-portal-base/portal/src/Form/ObjectFormManager.php
> +			$aData['messages']['error'] += array('_main' => array($e->getHtmlMessage()));
I don't know but this is the current behavior..

2023-09-21 15:51 UTC, accognet commented on pages/UI.php
> +					$sMessage = $e->getHtmlMessage();
Yes, for CoreCannotSaveObjectException, this is the message that is usually displayed

2023-09-21 15:52 UTC, accognet commented on pages/UI.php
> +					$aIssues = $e->getIssues();
CoreCannotSaveObjectException was not catch. Without this catch, we don't see the error message

2023-09-21 16:35 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Form/ObjectFormManager.php
> +			$aData['messages']['error'] += array('_main' => array($e->getHtmlMessage()));
It is a matter of where the message will consumed / displayed, not how it is usually done for this type of exception.

2024-02-29 15:14 UTC, merged