Add a setting to change default "password change" URL
Combodo/iTop pull request #540
Opened 2023-08-17 15:54 UTC by peckpeck

When we use an LDAP authentication, iTop still displays its own change password URL whereas it doesn't work since it cannot change the users' password.

This PR adds a setting to allow the administrator to specify this URL so that users can click on it in the login form and user the proper form.

2023-08-22 18:47 UTC, jbostoen commented
Just wondering, is this a generic service URL or something built-in of your LDAP server? If it's not something standard: wouldn't it make more sense to hide/disable iTop's native "change password" URL altogether in case of certain user type accounts? I suppose it could be something like a static function on the User child classes?

I'm support engineer for a product where the changing of the LDAP password can actually be done in the application as well. Makes for a more integrated solution, but I think it's Kerberos based.

2023-08-23 07:27 UTC, peckpeck commented
In my case, it is the URL of change password service configured for our LDAP server. It may also be interesting to allow removing the URL in your case.

2023-08-24 07:42 UTC, Hipska commented
This implementation changes the URL for all types of users, so also for `UserLocal` who will then not be able to change their password anymore.

2023-09-25 13:48 UTC, peckpeck commented
It indeed does not work for all cases, but it at least works for the case when all users are in LDAP.
We are in the login form, so we don't know yet if the user is in LDAP yet or not since the login is inknown.

2023-09-25 13:54 UTC, Hipska commented
Oh, I see.

I would at least also change the URL for the menu item when logged in (if applicable to that User class)
<img width="226" alt="image" src="https://github.com/Combodo/iTop/assets/228588/ce54eb67-a95f-421c-97e0-a0b25550e18c">

2023-11-07 16:32 UTC, Molkobain requested changes

2023-11-07 16:32 UTC, Molkobain commented on application/loginform.class.inc.php
> +		}
```suggestion
		$sResetPasswordUrl = MetaModel::GetConfig()->Get('forgot_password.url');
		if ($sResetPasswordUrl == '')
		{
			$sResetPasswordUrl = utils::GetAbsoluteUrlAppRoot() . 'pages/UI.php?loginop=forgot_pwd';
		}
```

2023-11-07 16:32 UTC, Molkobain commented on core/config.class.inc.php
> +		],
```suggestion
		'forgot_password.url' => [
			'type'                => 'string',
			'description'         => 'Set this value to your "forgot password" service URL if it should be handled out of '.ITOP_APPLICATION_SHORT.'. Note that it will apply to all users (iTop users, LDAP users, ...)',
			'default'             => '',
			'value'               => '',
			'source_of_value'     => '',
			'show_in_conf_sample' => false,
		],
```

2023-11-07 16:34 UTC, Molkobain commented on core/config.class.inc.php
> +		],
@peckpeck can you move this block of code just below the existing `forgot_password` declaration?

2023-11-07 16:35 UTC, Molkobain commented
Technical review:
- Ok with the idea of overloading the URL with a conf parameter, we just renamed the conf. param. name as it is only for the "forgot/reset password" URL (login page), not the "change password" (menu for logged users).
- Guillaume will document in the Wiki that it is not recommended to change it when several types of users are available
- @Hipska , regarding the "change password" url, the link is already displayed or not depending on `\User::CanChangePassword()`, ideally we could have another `\User::ChangePasswordURL()` method, but this is for a dedicated PR.

2023-11-07 19:07 UTC, Hipska approved these changes

2023-11-14 19:20 UTC, Molkobain commented
Functional review:
  - We have an internal use case: ITSM Designer users which need to be redirected to our support portal for password change
  - Guillaume will check with SaaS teams if they have a similar use case
  - As stated before, this PR only makes sense when there are only LDAP users, we need to discuss how it could be handle for iTops with a mix of users and external OAuth providers like (Google, ...), we'll think about it until next review
  - @peckpeck in the meantime you can set the `forgot_password` parameter to false in order to hide the link (if you haven't done it yet 😁)

2023-11-21 13:48 UTC, Hipska approved these changes

2023-11-22 08:31 UTC, Molkobain commented
@peckpeck you reverted my suggestions to your original proposition, was that intended? We would like this suggestions to be applied in order to proceed with the PR.

2023-11-22 08:42 UTC, peckpeck commented
@Molkobain sorry, I made a mistake, I thought I was pushing to a different branch.
I apologize for the mess

2023-11-22 09:59 UTC, Molkobain commented
> @Molkobain sorry, I made a mistake, I thought I was pushing to a different branch. I apologize for the mess

No problem, do you want me to apply the suggestions directly? I was able to restore them on the PR.

2023-11-22 11:22 UTC, peckpeck commented
Yes you can apply the suggestions, directly

2023-12-12 16:24 UTC, Molkobain commented
Accepted during functional review.
Guillaume will add the documentation.

2023-12-14 09:08 UTC, merged

2023-12-14 09:21 UTC, Molkobain commented
Hello @peckpeck ,

Thanks again for the contribution, as a thank you, we would like to
- Add your name on the [contributors list](https://github.com/Combodo/iTop?tab=readme-ov-file#contributors), would you like to appear with your fullname or just your nickname?
- Send [you stickers](https://github.com/Combodo/iTop/raw/develop/.doc/contributing-guide/2023.contributing-stickers-side-by-side.png), could you send me your fullname and postal address to guillaume.lajarige at combodo.com ?