N°6695 Handle multiline dict entries in portal tooltips
Combodo/iTop pull request #542
Opened 2023-09-01 12:10 UTC by piRGoif

This bug was submitted in a SourceForge ticket : [#2171](https://sourceforge.net/p/itop/tickets/2171/)

To reproduce add this XML to your iTop instance : it will change the UserRequest.status field tooltip.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<itop_design xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.7">
    <dictionaries>
        <dictionary id="EN US">
            <entries>
                <entry id="Class:UserRequest/Attribute:status+" _delta="redefine"><![CDATA[This is the first line.
This is the second line.]]></entry>
            </entries>
        </dictionary>
    </dictionaries>
</itop_design>
```
 
On the admin console you'll get this tooltip :
![image](https://github.com/Combodo/iTop/assets/8947448/2d67a6a9-79b9-4e2e-bac1-2eacb70d297e)

But in the user portal : 
![image](https://github.com/Combodo/iTop/assets/8947448/d5193630-2b1f-4a6e-afec-1ccd8157e06e)

With this modification both tooltips will keep the line feed.

2023-09-05 14:58 UTC, piRGoif commented
Technical review : we have in combodo-approval-extended dict key containing br, check if they are handled ok !
In iTop there are already some dict keys with line feeds.

2023-09-06 14:04 UTC, piRGoif commented
For dict keys with <br>, the result is the same in both portal and console : the <br> is displayed as is.
Example : 
![image](https://github.com/Combodo/iTop/assets/8947448/989647c8-3e94-4f51-b54a-812780f34044)

2023-09-12 14:59 UTC, piRGoif commented
Functional review : 
- Search which key(s) contains a `<br>`
- Multiple multiline dict keys are currently added by Vincent, so yes should be fixed !
- Check which behavior if CrLf or Cr instead of Lf ?

Technical review to be done with Guillaume and Stephen.

2023-09-12 15:33 UTC, piRGoif commented
Of all the dict keys containing `<br>`, none are "+" keys which are displayed in a tooltip, so I think we are OK.

2023-09-15 14:51 UTC, piRGoif commented
Please @steffunky and/or @Molkobain can you have a look and check if the portal hack implementation is OK for you ?

2023-09-20 12:22 UTC, Molkobain requested changes
Fix seems good.
Where did you see a lot of changes in the compiled file? I only see what you added.

2023-09-20 12:22 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/public/css/portal.scss
> +/* Tippy customizations */
```suggestion
/* Tippy: Handle multi-line content */
```

2023-09-20 16:09 UTC, piRGoif commented
> Where did you see a lot of changes in the compiled file? I only see what you added.

Indeed in the PR there is only the added scss code as a difference. But in rocket chat I called for help, the message is still there ? Maybe I did report the modification manually ?

2023-09-20 16:10 UTC, merged

2023-09-20 16:47 UTC, Molkobain commented
> Indeed in the PR there is only the added scss code as a difference. But in rocket chat I called for help, the message is still there ? Maybe I did report the modification manually ?

Discussed on IM, issue not reproduced. We let it go for now as it have been a particular dev env.