5491 brokenui dictformat
Combodo/iTop pull request #545
Opened 2023-09-12 07:01 UTC by odain-cbd

**Issue:**
iTop UI can explode anywhore because of unprotected Dict::Format API. it depends on language used and dictionaries label to display...

in details such a case can occur at any time translation is not safe to vsprint PHP API. for example if there are not enough placeholders provided in dictionary:

**Example**: labelkey = "this will break %1$"

**Fix**
in this PR a try/catch has been added to avoid any UI white page (worst UX effect ever). in that case an error log is printed as well to identify which label/language has to be fixed. in UI the label key will be displayed.

we also added a testcase to identify all broken dictionaries to fix them as soon as possible...

2023-09-12 07:31 UTC, Hipska commented on core/dict.class.inc.php
> +		}
Looking at the code of `GetLabelAndLangCode`, the return will always contain `label`..

2023-09-12 07:31 UTC, Hipska commented on core/dict.class.inc.php
> +			\IssueLog::Error("Broken label", null, ["sFormatCode" => $sFormatCode, "sLangCode" => $sLangCode ]);
Maybe also include the actual error message to help debugging/fixing?

2023-09-12 07:31 UTC, Hipska commented on core/dict.class.inc.php
> +		}
The keys are always existing..
```suggestion
		['label' => $sLocalizedFormat, 'lang' => $sLangCode] = self::GetLabelAndLangCode($sFormatCode);
```

2023-09-12 15:55 UTC, piRGoif requested changes
Will be discussed with Olivier tomorrow !

2023-09-12 15:55 UTC, piRGoif commented on core/dict.class.inc.php
> +	 * @return array with localized label string and used lang code
Please document using the array shapes syntax (https://wiki.combodo.com/doku.php?id=latest:customization:coding_standards#arrays_with_named_keysarray_shapes)

2023-09-12 15:55 UTC, piRGoif commented on core/dict.class.inc.php
> +		}
+1 ! This method content should be rewritten ? Maybe return another key than label for error cases ?

2023-09-12 15:55 UTC, piRGoif commented on core/dict.class.inc.php
>  			IssueLog::Warning("Cannot find $sLangCode in dictionnaries. default labels displayed");
This should say that we cannot find this dict key in any language

2023-09-12 15:55 UTC, piRGoif commented on core/dict.class.inc.php
> +		}
+1

2023-09-12 15:55 UTC, piRGoif commented on core/dict.class.inc.php
> +			\IssueLog::Error("Broken label", null, ["sFormatCode" => $sFormatCode, "sLangCode" => $sLangCode ]);
I would change the error message for something like "Cannot format dict key with existing placeholders"
Also I agree with Thomas about the error message, as we saw different PHP versions can have different behaving. You may use ExceptionLog ? (only exists starting with support/3.0 for now, but it may be added in support/2.7)

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
> +		$oProperty = $this->GetProperty($sClass, $sProperty);
What will be the behavior if the attribute isn't static ? I'm afraid it won't crash and have unpredictable results (depends on PHP version) ? Maybe test that before doing anything ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		try{
instead of commenting out all this code, add a markTestSkipped with a clear message please (it's nice to keep this method for evaluating results with different PHP versions, and document uses cases causing errors)

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +
Check our internal wiki to have the proper copyright header

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	 * Dict::Format
Is this line a typo ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function testFormat($sTemplate, $sExpectedTraduction){
$sExpectedTranslation instead :)

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		$sLangCode = \Dict::GetUserLanguage();
In this context there are no real user connected, so I found this confusing ? Maybe set clearly the default value (\Dict::$m_sDefaultLanguage) ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +				$aDictByLang[$sLangCode] = [$sDictKey => $sTemplate];
Can't the assignment be always done the same way ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function testFormat($sTemplate, $sExpectedTraduction){
Document (with @param ?) that if null is set to $sTemplate that means we won't set the dict key value

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function testFormat($sTemplate, $sExpectedTraduction){
I would rename the method name to a less generic name ? Something like testFormatWithOneArgumentAndCustomKey ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function LangCodeProvider(){
See DictionariesConsistencyAfterSetupTest::testDictEntryValues
Between the var in this method and the language lists done during setup, we should pick one of those ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		\Dict::InitLangIfNeeded($sLangCode);
Why do we make the call twice ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		\Dict::InitLangIfNeeded($sLangCode);
This method will read compiled dict keys in the current env. We are in a ItopTestCase and not an ItopDataTestCase so I doubt we will have enough data ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		$aLabelCodeNotToCheck = [
To ease maintenance, maybe extract this list to a new class ? Like what was done with \Combodo\iTop\Composer\iTopComposer::ListAllowedTestDir / ListDeniedTestDir ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +				}*/
Why is this commented code kept ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function testDictEntryValues($sCode)
$sCode is quite generic. Maybe rename to something like $sLanguageCodeToTest ?

2023-09-12 15:55 UTC, piRGoif commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		$sErrorMsg = sprintf("%s broken propertie(s) on $sCode dictionaries!", $iCount);
Why doing var_dump of the details instead of adding the details at the end of the error message ? I fear the var_dump might be hard to spot in a Jenkins failed test report ?

2023-09-13 09:14 UTC, odain-cbd commented on tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
> +		$oProperty = $this->GetProperty($sClass, $sProperty);
this PR starts from support/2.7. there were missing test APIs that exist already in support/3.x.

to avoid painfull merges I will keep these changes as is

2023-09-13 09:15 UTC, odain-cbd commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		$sLangCode = \Dict::GetUserLanguage();
added a comment

2023-09-13 09:15 UTC, odain-cbd commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +	public function LangCodeProvider(){
added a comment

2023-09-13 09:16 UTC, Hipska commented on core/dict.class.inc.php
> +		}
This conversation is marked as resolved, but nothing has changed. So not resolved yet..

2023-09-13 09:16 UTC, odain-cbd commented on tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
> +		$sErrorMsg = sprintf("%s broken propertie(s) on $sCode dictionaries!", $iCount);
topic discussed directly and feedback enhanced

2023-09-13 09:19 UTC, odain-cbd commented on core/dict.class.inc.php
> +		}
sorry I repaired it.

2023-09-13 09:19 UTC, odain-cbd commented on core/dict.class.inc.php
> +		}
this should be fixed now....

2023-09-13 09:20 UTC, odain-cbd commented
Thank you to Hispka and Pierre. I took all (or almost all) your comments into account and fixed

2023-09-13 10:02 UTC, merged