Add operation on replica
Combodo/iTop pull request #546
Opened 2023-09-14 14:35 UTC by accognet

On synchronized object, add a link to replicas on padlock
![image](https://github.com/Combodo/iTop/assets/57360138/9d0cffc7-41f4-4aa3-b25a-82e9fdc6cf46)
This link search all replicas linked to the current object.
![image](https://github.com/Combodo/iTop/assets/57360138/16f920be-da7d-490a-abbf-935f7c6309b0)

Add operation on replicas :

2023-09-25 07:11 UTC, Hipska commented
I very much like the delete option :)

2023-09-25 07:33 UTC, Hipska approved these changes

2023-09-25 07:33 UTC, Hipska commented on synchro/replica.php
> +			$oReplica->DBWrite();
Should `dest_class` also be reset? (IMHO not really, but made this comment so that Combodo made sure they think about it, see also #551)

2025-04-04 12:38 UTC, favincen commented
This feature would be an extremely useful addition for Synchro troubleshooting and testing, but this PR seems stuck.
Any chance to see its processing resumed ?

2026-05-11 08:04 UTC, steffunky commented on application/cmdbabstract.class.inc.php
> +					$sFilter = 'SELECT SynchroReplica WHERE dest_class=\''.get_class($this).'\' AND dest_id='.$this->GetKey();
Could be cleaner to use `DBObjectSearch::FromOQL` with parameters placehoders and then use `DBObjectSearch::serialize` (even if I don't see any security risk)

2026-05-11 08:04 UTC, steffunky commented on application/displayblock.class.inc.php
> +					$bIsBulkModifyAllowed = (!MetaModel::IsAbstract($sSelectedClass)) && UserRights::IsActionAllowed($sSelectedClass, UR_ACTION_BULK_MODIFY) && (($oReflectionClass->IsSubclassOf('cmdbAbstractObject'
This seems very specific and I don't know if we'll add another exception here, but using a `in_array($sSelectedClass, $aBulkModifyAllowedClasses)` where `$aBulkModifyAllowedClasses = ['SynchroReplica']` could allow more flexibility

2026-05-11 08:04 UTC, steffunky commented on dictionaries/en.dictionary.itop.core.php
> +	'Core:SynchroReplica:ListOfReplicas'                                       => 'Replicas of the data source: %1$s',
This would break existing translations, should we revert all languages entries to `Replicas of the data source: %1$s~~` ?

2026-05-11 08:04 UTC, steffunky commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:appUserPreferences/Attribute:userid'      => 'User',
You'll need to add these entries to other dictionaries and translate the French one, otherwise you'll break unit tests

2026-05-11 08:04 UTC, steffunky commented on synchro/replica.php
> +				//$oBackButton = ButtonUIBlockFactory::MakeIconLink('fas fa-chevron-left', Dict::Format('Core:SynchroReplica:BackToDataSource', $oSource->GetName()), ApplicationContext::MakeObjectUrl('SynchroDat
Remove comment

2026-05-11 08:04 UTC, steffunky commented on synchro/synchrodatasource.class.inc.php
> +		$oPage->add_style('.ibo-page-header--replica-title>.ibo-toolbar--button{ display: table-cell;  vertical-align:middle;}');
Use `css/backoffice/pages/_data-synchro.scss` or a dedicated SCSS file in `css/backoffice/pages/`

2026-05-28 07:49 UTC, bdalsass requested changes

2026-05-28 07:49 UTC, bdalsass commented on application/cmdbabstract.class.inc.php
> +				if (UserRights::IsActionAllowed('SynchroReplica', UR_ACTION_READ)) {
```suggestion
				if (UserRights::IsActionAllowed(SynchroReplica::class, UR_ACTION_READ)) {
```

2026-05-28 07:49 UTC, bdalsass commented on application/cmdbabstract.class.inc.php
> +					$oDBSearch = DBObjectSearch::FromOQL('SELECT SynchroReplica WHERE dest_class=:sClass AND dest_id=:id');;
```suggestion
					$oDBSearch = DBObjectSearch::FromOQL('SELECT SynchroReplica WHERE dest_class=:sClass AND dest_id=:id');
```

2026-05-28 07:49 UTC, bdalsass commented on application/displayblock.class.inc.php
> +					$bIsBulkModifyAllowed = (!MetaModel::IsAbstract($sSelectedClass)) && UserRights::IsActionAllowed($sSelectedClass, UR_ACTION_BULK_MODIFY) && (($oReflectionClass->IsSubclassOf('cmdbAbstractObject'
```suggestion
					$bIsBulkModifyAllowed = (!MetaModel::IsAbstract($sSelectedClass)) && UserRights::IsActionAllowed($sSelectedClass, UR_ACTION_BULK_MODIFY) && (($oReflectionClass->IsSubclassOf(cmdbAbstractObject::class) || $sSelectedClass === SynchroReplica::class));
```

2026-05-28 07:49 UTC, bdalsass commented on application/displayblock.class.inc.php
> +						if($sSelectedClass === 'SynchroReplica'){
```suggestion
						if($sSelectedClass === SynchroReplica::class){
```

2026-05-28 07:49 UTC, bdalsass commented on css/backoffice/pages/_data-synchro.scss
> +    vertical-align:middle;
```suggestion
    vertical-align: middle;
```

2026-05-28 07:49 UTC, bdalsass commented on sources/Controller/UI.php
> +class UI
Could we choose a more domain oriented name than UI ?

2026-05-28 07:49 UTC, bdalsass commented on synchro/replica.php
> +				$oSource = MetaModel::GetObject('SynchroDataSource', $iSourceId);
```suggestion
				$oSource = MetaModel::GetObject(SynchroDataSource::class, $iSourceId);
```

2026-05-28 07:49 UTC, bdalsass commented on synchro/replica.php
> +				$oSource = MetaModel::GetObject('SynchroDataSource', $iSourceId);
```suggestion
				$oSource = MetaModel::GetObject(SynchroDataSource::class, $iSourceId);
```

2026-05-28 07:49 UTC, bdalsass commented on synchro/synchrodatasource.class.inc.php
> +		$oDataSource = MetaModel::GetObject('SynchroDataSource', $this->Get('sync_source_id'));
```suggestion
		$oDataSource = MetaModel::GetObject(SynchroDataSource::class, $this->Get('sync_source_id'));
```

2026-05-28 07:49 UTC, bdalsass commented on sources/Controller/Links/SynchroReplicaController.php
> +			$oReplica = MetaModel::GetObject('SynchroReplica', $iId);
```suggestion
			$oReplica = MetaModel::GetObject(SynchroReplica::class, $iId);
```

2026-06-04 08:08 UTC, bdalsass approved these changes

2026-06-15 13:58 UTC, merged