Allow to include backup extra files via interface
Combodo/iTop pull request #547
Opened 2023-09-19 11:52 UTC by larhip

In case a custom extension write some files into data directory, it might be necessary to include those files in the backup.

Currently it is just possible to add extra files via config entry, but this will always depend on the local config file. It might be interesting to define extra files via an extension as well.

What do you think?

2023-09-19 12:01 UTC, Hipska approved these changes

2023-09-19 12:01 UTC, Hipska commented on application/applicationextension.inc.php
> +	 * @return array
```suggestion
	 * @return string[]
```

2023-09-19 12:27 UTC, larhip commented on application/applicationextension.inc.php
> +	 * @return array
yep, thank one make sense :-)

2023-09-19 12:29 UTC, Hipska approved these changes

2023-09-19 15:26 UTC, Molkobain commented on setup/backup.class.inc.php
> +			}
You might want to move this outside of the if condition as the file can be saved even though there is no configuration yet no?

2023-09-19 15:36 UTC, Molkobain reviewed
Is it working on your instance? It shouldn't until the interface is declared in `\MetaModel::InitExtensions()`.
When doing so, please add the interface to the unit test `tests/php-unit-tests/unitary-tests/application/applicationextension/ApplicationExtensionTest.php::ExtensionAPIRegisteredAndCalledProvider()` as well.

2023-09-19 20:22 UTC, larhip commented on setup/backup.class.inc.php
> +			}
Changed with Commit d16c37b

2023-09-19 20:29 UTC, larhip commented
Damn you are right I forgot to add my changes in `metamodel.class.php` 
I just added this one. (see 3851042)

I have also updated the PHP unit test as requested (9ce61eb)

Beside that there was a little issue, in case you would like to include a subdirectory into the backup (fixed with (234c1b5)

One more issue: Could it be possible that you did not run your php unit tests with PHP 8.1? 
Running those test with 8.1 will throw a php warning: ` Private methods cannot be final as they are never overridden by other classes in /var/www/html/tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php on line 90`
So I removed the `Final`flag for those private methods (see 36483f)
This last commit might be better to do not via this PR since it is not directly related to this topic, what do you think?

2023-09-20 12:26 UTC, Molkobain commented
> One more issue: Could it be possible that you did not run your php unit tests with PHP 8.1? Running those test with 8.1 will throw a php warning: ` Private methods cannot be final as they are never overridden by other classes in /var/www/html/tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php on line 90` So I removed the `Final`flag for those private methods (see [36483fb](https://github.com/Combodo/iTop/commit/36483fb00f45d1abdbed43310f14ffb4ccde6951)) This last commit might be better to do not via this PR since it is not directly related to this topic, what do you think?

It's possible yes, I might have ran them on 7.4 at the time. Thanks for pointing it out! I'll handle it :)

2023-09-20 12:27 UTC, Molkobain commented on application/applicationextension.inc.php
> + * @api
```suggestion
 * @api
 * @since 3.2.0
```

2023-09-20 12:29 UTC, Molkobain requested changes

2023-09-20 12:29 UTC, Molkobain commented on application/applicationextension.inc.php
> + * @api
Damn, I thought I would be able to apply the suggestion myself, sorry. I forgot the "edit maintainers" was not active on itomig-de fork.

2023-09-20 12:29 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
Remove these changes please, it's not part of the PR and I have to fix it from support/2.7 to develop :)

2023-09-20 14:03 UTC, larhip commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
Corresponding commit has been dropped 👍

2023-09-20 14:21 UTC, Molkobain approved these changes

2023-09-20 14:21 UTC, Molkobain commented on tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
Perfect thanks! I fixed the unit test class with [2a6e5b2](https://github.com/Combodo/iTop/commit/2a6e5b21a945538498e2fda2e5ba7e54ffab5a12)

2023-09-21 08:00 UTC, Hipska approved these changes

2023-11-07 15:40 UTC, Molkobain commented
Accepted during technical review:
- Guillaume creates a modernization ticket to split the `applicationextension.inc.php` file into separate files
- Guillaume creates a modernization ticket to migrate usages of `\MetaModel::EnumPlugins()` to `\utils::GetClassesForInterface()`

2023-11-08 08:28 UTC, Molkobain requested changes

2023-11-08 08:28 UTC, Molkobain commented on application/applicationextension.inc.php
> +	public function GetExtraFiles();
```suggestion
	public function GetExtraFiles(): array;
```

2023-11-08 08:28 UTC, Molkobain commented on core/metamodel.class.php
> +			'iBackupExtraFilesExtension',
```suggestion
```

See next comment

2023-11-08 08:28 UTC, Molkobain commented on setup/backup.class.inc.php
> +		}
```suggestion
		foreach (utils::GetClassesForInterface('iBackupExtraFilesExtension', '', ['[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]tests[\\\\/]']) as $sExtensionClass)
		{
			/** @var iBackupExtraFilesExtension $oExtensionInstance */
			$oExtensionInstance = new $sExtensionClass();
			$aExtraFiles = array_merge($aExtraFiles, $oExtensionInstance->GetExtraFiles());
		}
```

Rather use this method to retrieve classes implementing the API, it has 2 main advantages (and 1 drawback):
- No need to declare the API interface in `\MetaModel::InitExtensions()`
- No need to explicit require class in the `module.xxx.php` file, it can be autoloaded

_The drawback is that you get FQCN of classes implementing the interface instead of an instance of these classes_

2023-11-08 08:28 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/application/applicationextension/ApplicationExtensionTest.php
> +				static::ENUM_API_CALL_METHOD_ENUMPLUGINS,
```suggestion
				static::ENUM_API_CALL_METHOD_GETCLASSESFORINTERFACE,
```

2023-11-08 08:28 UTC, Molkobain commented
Unfortunately I can't apply these changes, could you apply them Lars?

2023-11-08 08:52 UTC, Molkobain commented
> * Guillaume creates a modernization ticket to split the `applicationextension.inc.php` file into separate files

N°6932

> * Guillaume creates a modernization ticket to migrate usages of `\MetaModel::EnumPlugins()` to `\utils::GetClassesForInterface()`

N°6936

2023-11-08 09:03 UTC, larhip commented
> Unfortunately I can't apply these changes, could you apply them Lars?

@Molkobain should be done, could you please check?

2023-11-08 10:39 UTC, Molkobain reviewed
Sorry I forgot this change. Then it's ok, it's works like a charm locally.

2023-11-08 10:39 UTC, Molkobain commented on setup/backup.class.inc.php
> +		foreach (utils::GetClassesForInterface('iBackupExtraFilesExtension', '', ['[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]tests[\\\\/]']) as $sExtensionClass)
```suggestion
		foreach (utils::GetClassesForInterface('iBackupExtraFilesExtension', '', ['[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]test[\\\\/]', '[\\\\/]tests[\\\\/]']) as $sExtensionClass)
```

2023-11-08 13:09 UTC, Molkobain approved these changes

2023-11-14 19:41 UTC, Molkobain commented
Functional review:
  - Globally ok for the PR, but curious about the concrete use case you have in mind @larhip ?
  - Including huge files could break the backup archive, making it un-restorable. Guillaume will discuss with Stéphane about the checks/protections we would like to be done.

2023-11-16 16:11 UTC, Molkobain commented
> * Including huge files could break the backup archive, making it un-restorable. Guillaume will discuss with Stéphane about the checks/protections we would like to be done.

Discussed with Stephane:
  - There is no size limitation of the tar archive itself
  - The limitation is that each file included in the tar cannot exceed 68GB

As the main issue is the SQL dump, we consider that there is no need to check file size. If something needs to be addressed, it would be outside of that PR to handle the SQL dump size correctly.

2023-11-16 16:11 UTC, Molkobain commented
Just waiting for Lars use case before merging

2023-11-16 16:23 UTC, larhip commented
We are currently working on an extension, which is writing some files into the filesystem those files are related to the itop data in the database. 
Due to that relation it would be pretty clever to include those file into the backup (and restore).

When I got you right the "only" limitations might be that files bigger than 68GB become problematic?

2023-11-16 16:36 UTC, Molkobain commented
> We are currently working on an extension, which is writing some files into the filesystem those files are related to the itop data in the database. Due to that relation it would be pretty clever to include those file into the backup (and restore).

Thanks for the feedback

> When I got you right the "only" limitations might be that files bigger than 68GB become problematic?

Yes, we currently have the problem with instances on which the SQL dump (which is included in the backup) exceeds 68GB in which case the archive cannot be opened. 
That can happen on SQL dumps, but it should be very very rare on files.

2023-11-16 18:01 UTC, Hipska commented
According to the specs of tar, there is no real file size limitation. Unless you use a version from before 2004?

2023-11-17 09:00 UTC, Molkobain commented on application/applicationextension.inc.php
> +	 * Returns an array of files and directories to be included in the backup
```suggestion
	 * Returns an array of files and directories relative paths (from iTop root) to be included in the backup
```

2023-12-12 16:26 UTC, Molkobain commented
Accepted during functional review:
  - Guillaume will add a protection for file exceeding 68GB, and a conf. param to disable this if necessary
  - Guillaume will ensure that in case of a too large file, the backup fails in the same way as the usual so the admin notices it

2024-03-18 09:20 UTC, larhip commented on setup/setuputils.class.inc.php
@Molkobain since this PR is planned for iTop 3.2, could you maybe have a look at that tiny change here again? Could you imagine to include only this line already with iTop 3.1.2? Without this line I am also not able to use the config param extra_files in a proper way

2024-03-22 08:52 UTC, Molkobain commented on setup/setuputils.class.inc.php
Hello Lars,

I'll check if we can add this line in the 3.1.2 sure :)
The rest of it will only be in 3.2.0 though

2024-04-08 13:36 UTC, Molkobain commented on setup/setuputils.class.inc.php
Hello Lars,

After looking a bit more into this, I'm not comfortable setiing `777` on a folder.
Eventually we can set 755, but it should not be necessary if your permissions are ok on the current folder. Have you checked this?

2024-04-08 18:07 UTC, larhip commented on setup/setuputils.class.inc.php
Hi Guillaume,

to be honest I have busted used '0777' since that is the default, which currently means without that change it is also '0777' (https://www.php.net/manual/en/function.mkdir.php). The only difference is that from now the possibility of the recursive creation is missing.

So my intention was to keep the change as small as possible (lower risk of breaking change).
From my point of view I would be fine with '0755' as well, but especially to introduce it into a minor version (3.1.2) it might be smarter to do it in the same way as before?

Maybe it would be also a good idea for a future version (for 3.2.0 not for 3.1.2) to adapt the code and copy the original permissions? So Something like that:

```PHP
mkdir($sDest, 0777, true);
chmod($sDest, fileperms($sSource));
```

2024-04-08 19:43 UTC, Molkobain commented on setup/setuputils.class.inc.php
100% agree with all of your answer :))

2024-04-08 19:47 UTC, Molkobain commented on setup/setuputils.class.inc.php
Done

2024-04-11 08:08 UTC, Molkobain commented
Hello Lars,

Could you please rebase your branch "onto" support/3.2 please so I can merge it? I can't do it myself as this fork doesn't allow maintainers to edit.

Thanks

2024-04-11 08:08 UTC, Molkobain commented
(If you need a hand, poke me)

2024-04-11 09:41 UTC, larhip commented
I recently did so.
(I did it via GitHub UI so changing the base branch leads to a merge commit instead of a rebase. But since commits of this PR will be squashed into one during the final merge is should be fine anyhow)

2024-04-12 07:17 UTC, merged

2024-04-12 07:17 UTC, Molkobain commented
> I recently did so. [...]

Oh my bad sorry :)