N°6766 - Javascript : function WizardHelper.UpdateFields triggered too early does not update fields
Combodo/iTop pull request #548
Opened 2023-09-21 09:10 UTC by accognet

internal

2023-09-21 09:15 UTC, Hipska requested changes

2023-09-21 09:15 UTC, Hipska commented on application/wizardhelper.class.inc.php
> +		);
Duplicate code
```suggestion
		$oPage->add_script($this->GetJsForUpdateFields());
```

2023-09-21 09:22 UTC, accognet commented on application/wizardhelper.class.inc.php
> +		);
Yes I know but GetJsForUpdateFields can (must?) be removed with this PR. I need to discuss this change with the team.

2023-09-26 10:22 UTC, Molkobain commented on application/wizardhelper.class.inc.php
> +		);
Original function is now marked as deprecated. The new one allows to feed both regular and on ready JS snippets.

2023-09-26 10:24 UTC, Molkobain approved these changes
Reviewed and accepted

2023-09-26 10:25 UTC, merged