N°5472 Add activity tab in action objects
Combodo/iTop pull request #549
Opened 2023-09-22 13:38 UTC by piRGoif

To allow easier detection of notification errors for admin, add a new "activity" tab in Action objects.
This will display all the EventNotification saved for the current action in the past 2 months.

2023-09-22 13:45 UTC, Molkobain commented
I'm not sure "Activity" tab is relevant, it's confusing, at first I thought it was something in the activity panel.
Why not name the tab "last_executions_tab" like you already did in the dictionary entries?

2023-09-22 13:52 UTC, piRGoif commented
Thanks for the feedback, renaming done !

2023-09-29 08:21 UTC, Hipska commented
May I ask why it is put as PHP code and not an `AttributeDashboard`? Looks doable for the current use-case and is more extendable.

2023-09-29 10:14 UTC, piRGoif commented
> May I ask why it is put as PHP code and not an `AttributeDashboard`? Looks doable for the current use-case and is more extendable.

Woo I missed that, thanks for the tip, I'll try !

2023-09-29 14:00 UTC, piRGoif commented
The Action class is defined in PHP, having a DisplayBareRelation override would be clearer than a new attribute defined in the Init method I think ? 
If the class was defined in XML of course the AttributeDashboard syntax would have been much better.

2023-10-03 08:29 UTC, Hipska commented
Oh, right. Another case why a lot of the standard classes should be defined in XML instead of PHP 😉

2023-10-03 08:30 UTC, Hipska approved these changes

2023-11-24 16:10 UTC, piRGoif commented
Documentation asked on 2023-10-27 FAF meeting done
Ready to be reviewed !

2023-11-24 16:12 UTC, piRGoif commented
Rebased and force pushed

2023-11-26 08:48 UTC, Molkobain commented
Questions for technical review:
- Shoudn't it be an AJAX tab? Amount of notifications sent in 2 months can be huge (take the public log on Bug ou UserRequest in our iTop)
- Should we use a time interval (eg. 1 month) ou a count limit (eg. 100) ?

2023-12-01 16:14 UTC, piRGoif commented
There is a time interval (2 months)
On previous discussions we thought having a simple query shouldn't impact perf.
There was an idea to use a dashboard attribute instead,n but as the class is defined in php it should be easier to override methods than an attribute.

2023-12-05 16:18 UTC, Molkobain commented
Technical review: Accepted if tab is switched to an ajax tab to limit performance issues.

2023-12-05 16:25 UTC, Molkobain requested changes

2023-12-05 16:25 UTC, Molkobain commented on core/action.class.inc.php
> +		$oPage->SetCurrentTab('action_errors', Dict::S('Action:last_executions_tab'), Dict::S('Action:last_executions_tab+'));
```suggestion
		$oPage->AddAjaxTab('Action:last_executions_tab', XXX, true /* bCache */, Dict::S('Action:last_executions_tab'), AjaxTab::ENUM_TAB_PLACEHOLDER_LIST);
```

For the ajax tab you can try something like this

2024-01-09 15:30 UTC, Molkobain commented
Accepted during functional review:
- Ok for 3.2.0
- Change interval to a config. param. and change it to days instead of months. (eg. `"notifications.last_executions_days" = 60`)

2024-01-10 14:26 UTC, piRGoif commented
Rebased branch

2024-01-10 14:29 UTC, piRGoif commented on core/action.class.inc.php
> +		$oPage->SetCurrentTab('action_errors', Dict::S('Action:last_executions_tab'), Dict::S('Action:last_executions_tab+'));
TODO reported in description
Closing conversation

2024-01-10 17:44 UTC, Molkobain commented on core/action.class.inc.php
> +		if ($oPage instanceof iTopWebPage) {
Can you remind me why this check is necessary? DisplayBareRelations is only called in iTopWebPage isn't it?

2024-01-10 17:46 UTC, Molkobain commented on core/action.class.inc.php
> +		}
I think it would be better to leave the tab in read only when editing the object.
It's less confusing for the user to always have the same tabs, and it can be use by the user to help fix the current action.

2024-01-10 18:01 UTC, Molkobain requested changes

2024-01-10 18:01 UTC, Molkobain commented on core/action.class.inc.php
> +		$sActionLastExecutionsPageUrl = utils::GetAbsoluteUrlAppRoot()
We should not use these endpoints anymore, you should either use the deprecated iTop Router or the Symfony Router (come see me for the draft conventions)

2024-01-10 18:01 UTC, Molkobain commented on core/action.class.inc.php
> +
This is unnecessary, the cast is already done by the \Config class
```suggestion
```

2024-01-10 18:01 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Action:last_executions_tab_panel_title' => 'Executions of this action in the past %1$s days',
Can you put a screenshot where this will be used? This looks more like a "+" entry or a table's subtitle.

2024-01-10 18:01 UTC, Molkobain commented on pages/ajax.render.php
> +			case 'notification.action.last_execution_content':
See comment above about routing

2024-01-11 10:19 UTC, piRGoif commented on core/action.class.inc.php
> +		if ($oPage instanceof iTopWebPage) {
cmdbAbstractObject::DisplayBareRelations method signature has WebPage as argument type, whereas AddAjaxTab method is defined in iTopWebPage

2024-01-11 10:23 UTC, piRGoif commented on core/action.class.inc.php
> +		}
Fixed in 12a7d95e

2024-01-11 10:27 UTC, piRGoif commented on core/action.class.inc.php
> +
Indeed, in the \Config::Set method
Test changed (actually we need to reject values <= 0) in d06a3d4e

2024-01-11 10:28 UTC, piRGoif commented on dictionaries/en.dictionary.itop.core.php
> +	'Action:last_executions_tab_panel_title' => 'Executions of this action in the past %1$s days',
Before implementing the AjaxTab, the second key was indeed a "+" key
But you can't specify "+" key to iTopWebPage::AddAjaxTab :(
So I changed the key to be displayed as a datatable panel title, see \Action::GetLastExecutionsTabContent

2024-01-11 10:29 UTC, piRGoif commented on dictionaries/en.dictionary.itop.core.php
> +	'Action:last_executions_tab_panel_title' => 'Executions of this action in the past %1$s days',
I've updated the description screenshot

2024-01-11 10:29 UTC, piRGoif commented on pages/ajax.render.php
> +			case 'notification.action.last_execution_content':
closing conversation to keep only one open on the same subject

2024-01-11 10:47 UTC, Hipska approved these changes
I'm still under the impression it better would have been a dashboard attribute. That would have solved also a few of the conversations in here..

2024-01-11 10:47 UTC, Hipska commented on core/config.class.inc.php
> +			'value' => 61,
What a strange default value. Why not `60`?

2024-01-11 12:05 UTC, Molkobain commented on core/config.class.inc.php
> +			'value' => 61,
It triggered me also, I think it's because 2 months is most of the time 30+31 days, but it's odd yes 😁

2024-01-11 12:06 UTC, piRGoif commented on core/action.class.inc.php
> +		$sActionLastExecutionsPageUrl = utils::GetAbsoluteUrlAppRoot()
Done in 494a376b
Can you review this commit ? 
I'm closing this conversation, don't hesitate to do a new review

2024-01-11 12:08 UTC, piRGoif commented on core/config.class.inc.php
> +			'value' => 61,
Apart of February, we have months that last 30 or 31 days, so I did 30 + 31 as a default value to reflect the previous "2 months" value

2024-01-11 12:16 UTC, Molkobain requested changes

2024-01-11 12:16 UTC, Molkobain commented on core/action.class.inc.php
> +		}
```suggestion
		if ($iLastExecutionDays < 0) {
			throw new InvalidConfigParamException("{$sLastExecutionDaysConfigParamName} config. parameter must be a positive integer");
		}
```

In functional review, we discussed that 0 would mean no time limit.
You'll need to adjust the OQL as well.

2024-01-11 12:16 UTC, Molkobain commented on sources/Controller/Notifications/ActionController.php
> +		$oPage = new NiceWebPage(Dict::S('UI:BrowseInlineImages'));
Why `NiceWebPage` instead of `AjaxWebPage`, and why this dict entry?!

2024-01-11 12:16 UTC, Molkobain commented on core/action.class.inc.php
> +		$sActionLastExecutionsPageUrl = $oRouter->GenerateUrl('notifications.action.last_executions_tab', ['actionid' => $this->GetKey()]);
```suggestion
		$sActionLastExecutionsPageUrl = $oRouter->GenerateUrl('notifications.action.last_executions_tab', ['action_id' => $this->GetKey()]);
```

The convention is to put an underscore.

2024-01-11 12:16 UTC, Molkobain commented on sources/Controller/Notifications/ActionController.php
> +		if (is_null($sActionId)) {
```suggestion
		$sActionId = utils::ReadParam('action_id', null, false);
		$sCannotLoadActionErrorMessage = __METHOD__ . ': invalid actionid parameter';
		if (utils::IsNullOrEmptyString($sActionId)) {
```

You need to handle `""` as well

2024-01-11 12:16 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Action:last_executions_tab_panel_title' => 'Executions of this action in the past %1$s days',
Thanks, makes sense now

2024-01-11 13:03 UTC, piRGoif commented on core/action.class.inc.php
> +		$sActionLastExecutionsPageUrl = $oRouter->GenerateUrl('notifications.action.last_executions_tab', ['actionid' => $this->GetKey()]);
Done in 4862977d

2024-01-11 13:03 UTC, piRGoif commented on sources/Controller/Notifications/ActionController.php
> +		if (is_null($sActionId)) {
Done in 4862977d

2024-01-11 13:05 UTC, piRGoif commented on core/config.class.inc.php
> +			'value' => 61,
Documented in d24ea5f0

2024-01-11 13:09 UTC, Hipska commented on core/config.class.inc.php
> +			'value' => 61,
Yeah okay, but we are talking about days here, not months. 61 is such an odd default number. In days I would have chosen 30, 50 or 60.

2024-01-11 13:11 UTC, piRGoif commented on core/action.class.inc.php
> +		}
I've changed the exception message with 5b1ff2c3
I used the param description to avoid duplicate. 
We might create a dedicated method in the Config class to check value... But it's out of scope of this PR.

2024-01-11 13:15 UTC, piRGoif commented on core/action.class.inc.php
> +		}
Woops sorry correct commit is c5f6c47c

2024-01-11 13:17 UTC, piRGoif commented on sources/Controller/Notifications/ActionController.php
> +		$oPage = new NiceWebPage(Dict::S('UI:BrowseInlineImages'));
Fixed in f18c2e1e

2024-01-11 13:27 UTC, piRGoif commented on core/action.class.inc.php
> +		}
0 as config param value : cdb5556a

2024-01-11 13:38 UTC, Molkobain commented on core/config.class.inc.php
> +			'description' => 'Number of days to display in the Action\'s last executions tab',
```suggestion
			'description' => 'Number of days to display in the Action\'s last executions tab (0 means no limit)',
```

Maybe we could precise in the description the behavior of `0`?

2024-01-11 13:42 UTC, Molkobain approved these changes

2024-01-22 15:11 UTC, piRGoif commented
Tech review OK, to check one last time in functional review

2024-02-14 08:42 UTC, piRGoif commented
Functional review ok
ready to merge !

2024-02-14 08:45 UTC, Hipska commented on core/config.class.inc.php
> +			'value' => 61,
@piRGoif You are forgetting December/January and July/August. So this calculation is wrong 4 months a year.

2024-02-14 08:48 UTC, Hipska commented
Please have a look https://github.com/Combodo/iTop/pull/549#discussion_r1489110960

2024-02-14 09:01 UTC, piRGoif commented on core/config.class.inc.php
> +			'value' => 61,
Yes you're perfectly right, 2 months isn't always the same as 61 days.
During the functional review this point was raised and everybody was ok with the default value anyway.
Closing conversation

2024-02-14 09:07 UTC, merged

2024-02-14 09:09 UTC, Hipska commented on core/config.class.inc.php
> +			'value' => 61,
Okay then 😂