🌐 Added the missing translation for Chinese (zh_cn) and some minor updates
Combodo/iTop pull request #563
Opened 2023-10-31 07:25 UTC by bdejin

1. Added the missing translation (ended with ~)
2. Updated the existing ones using below standard:
-  a space after . , ) ' " ? ]
-  a space before ( ' " [
-  no space before or after /

2023-10-31 07:57 UTC, chileeb requested changes

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> +	'DBTools:SQLquery' => 'SQL语句',
这里保留使用“SQL查询”是不是更好一些？

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
> +	'Class:FunctionalCI/Tab:OpenedTickets+' => '影响当前功能性配置项的活跃工单',
功能配置项

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> +	'Class:Incident/Attribute:origin/Value:chat' => '聊天',
聊天工具

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> +	'Class:Incident/Attribute:origin/Value:chat+' => '创建于聊天后的事件',
聊天工具的事件

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
> +	'Brick:Portal:UserProfile:PersonalInformations:Title' => '个人信息',
人员信息

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/zh_cn.dict.itop-request-mgmt-itil.php
> +	'Class:UserRequest/Attribute:origin/Value:chat+' => '创建于聊天后的需求',
聊天工具的需求

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/zh_cn.dict.itop-request-mgmt-itil.php
> +	'Class:UserRequest/Attribute:origin/Value:chat' => '聊天',
聊天工具

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-request-mgmt-itil/dictionaries/zh_cn.dict.itop-request-mgmt-itil.php
> +	'Organization:Overview:MyUserRequests' => '我在此组织的用户需求',
建议保留原翻译

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-request-mgmt/dictionaries/zh_cn.dict.itop-request-mgmt.php
> +	'Class:UserRequest/Attribute:origin/Value:chat+' => '创建于聊天后的需求',
聊天工具的用户需求

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Class:Person/Attribute:user_list+' => '所有关联到此个人的用户',
此人员

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Class:lnkPersonToTeam' => '关联个体/团队',
人员

2023-10-31 07:57 UTC, chileeb commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'theme:test-red' => '测例 (红色)',
测试（红色）

2023-10-31 09:29 UTC, Molkobain commented
Thanks the PR! Let us know (via a mention) when you all agree and the PR is ready for integration :)

2023-11-01 00:51 UTC, bdejin commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> +	'DBTools:SQLquery' => 'SQL语句',
okay

2023-11-01 00:51 UTC, bdejin commented on datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
> +	'Class:FunctionalCI/Tab:OpenedTickets+' => '影响当前功能性配置项的活跃工单',
okay

2023-11-01 00:53 UTC, bdejin commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> +	'Class:Incident/Attribute:origin/Value:chat+' => '创建于聊天后的事件',
创建于聊天工具沟通后的事件

2023-11-01 00:53 UTC, bdejin commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> +	'Class:Incident/Attribute:origin/Value:chat' => '聊天',
okay

2023-11-01 00:53 UTC, bdejin commented on datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
> +	'Brick:Portal:UserProfile:PersonalInformations:Title' => '个人信息',
okay

2023-11-01 00:55 UTC, bdejin commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Class:lnkPersonToTeam' => '关联个体/团队',
okay

2023-11-01 01:14 UTC, bdejin commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Class:Person/Attribute:user_list+' => '所有关联到此个人的用户',
绝大部分按照你的建议做了修正，同时修改了其他地方相同的翻译。我觉得之后可以全部检查下，保证所有类似的地方翻译一致。我们可以做个“中文翻译指南” :-)

2023-11-01 01:18 UTC, bdejin commented on datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
> +	'Class:Person/Attribute:user_list+' => '所有关联到此个人的用户',
这次时间仓促，主要做了缺失翻译的补充，来赶上3.2发布。之后可以全部检查下现有翻译。

2023-11-03 07:12 UTC, chileeb approved these changes
good job!

2023-11-03 07:24 UTC, bdejin commented
@Molkobain I think we're good to go. The review is done - thanks @chileeb for your time.

2023-11-03 08:10 UTC, Molkobain commented
Great job guys, thanks! It should be processed next week :)

2023-11-07 07:12 UTC, bdejin commented
> Great job guys, thanks! It should be processed next week :)

@Molkobain ooops, I did a sync for my fork and the changes were gone and PR closed. :-( How can I revert this......

2023-11-07 07:48 UTC, Molkobain commented
> > Great job guys, thanks! It should be processed next week :)
> 
> @Molkobain ooops, I did a sync for my fork and the changes were gone and PR closed. :-( How can I revert this......

Seems like you managed to re-open it :)

2023-11-07 16:07 UTC, Molkobain commented
Accepted during technical review

2023-11-08 05:26 UTC, bdejin commented
> > > Great job guys, thanks! It should be processed next week :)
> > 
> > 
> > @Molkobain ooops, I did a sync for my fork and the changes were gone and PR closed. :-( How can I revert this......
> 
> Seems like you managed to re-open it :)

Yep. Had some dig and got it back to the right trail.

2023-11-14 16:14 UTC, Molkobain commented
Accepted during functional review

2023-11-14 16:16 UTC, merged