Be able to track iTop active sessions (monitoring)
Combodo/iTop pull request #568
Opened 2023-11-07 16:15 UTC by odain-cbd

Goal

Current PR aims at being able at any time to know the amount of user currently active on iTop.
Design

For that purpose a dedicated iTop session handler extends default one. it keeps default implementation by calling each parent method first.
and then a specific iTop implementation is triggered to have local session files in data/sessions folder.

session file content
each session file is either empty when iTop session is made without any user authentified (status.php for example).
otherwise it contains below data:

    login_mode: authentication mode (among UI classical 'form', 'token', ....)
    user_id: logged in user ID
    creation_time: timestamp of the PHP session creation (used to compute session elapsed time in seconds)
    context: context of the session (empty when simple login or pick among ContextTag values like REST/Synchro/....)

Examples:
{"login_mode":"form","user_id":"1","creation_time":1699371169,"context":""}

{"login_mode":"form","user_id":"1","creation_time":1699371169,"context":""}

Cleanup
Garbage collecting of all local session files (in data/sessions folder) is made via a dedicated Background task.

2023-11-10 13:56 UTC, Molkobain requested changes
Discussed this morning with Olivier and Eric:
- I commited some changes
- Olivier will do the others

2023-11-10 13:56 UTC, Molkobain commented on sources/Application/Helper/iTopSessionHandler.php
Move this to `sources/SessionTracker/SessionHandler.php`

2023-11-10 13:56 UTC, Molkobain commented on core/cmdbsource.class.inc.php
> +			$mysqli = DbConnectionWrapper::GetDbConnection();
As this change is not really necessary for the PR, but fixed a test case, we'll see if we keep it during PR review.

2023-11-10 13:56 UTC, Molkobain commented on sources/Application/Helper/iTopSessionGarbageCollector.php
Move this to `sources/SessionTracker/SessionTrackerGC.php`

- No need to prefix with iTop
- Other GC task are suffixed with "GC" instead of "GarbageCollector"

2023-11-10 13:56 UTC, Molkobain commented on lib/composer/autoload_classmap.php
Mind to redump autoloaders after changes below.

2023-11-10 13:56 UTC, Molkobain commented on sources/Application/Helper/iTopSessionHandler.php
> +class iTopSessionHandler extends \SessionHandler
Put overrided methods first, then custom methods.

2023-11-10 13:56 UTC, Molkobain commented on sources/Application/Helper/iTopSessionHandler.php
> +					'context' => implode(":", ContextTag::GetStack())
Don't use ":" as it is already used in some context tags such as cron tasks, portal instances, synchro DS, ...
Discussed this morning, using "|" seems safe.

2023-11-10 13:56 UTC, Molkobain commented on sources/Application/Helper/iTopSessionHandler.php
> +		return glob(utils::GetDataPath() . "sessions/session_**");
```suggestion
		return glob(utils::GetDataPath() . "sessions/session_*");
```

2023-11-10 13:56 UTC, Molkobain commented on webservices/cron.php
> +					$oP->p(sprintf('| %1$-50.50s | %2$-7s | %3$-19s | %4$-19s |', $sTaskName, $sStatus, $sLastRunDate, $sNextRunDate));
```suggestion
					$oP->p(sprintf('| %1$-25.25s | %2$-7s | %3$-19s | %4$-19s |', $sTaskName, $sStatus, $sLastRunDate, $sNextRunDate));
```

My bad

2023-11-10 13:59 UTC, Molkobain commented on sources/Application/Helper/iTopSessionHandler.php
> +		IssueLog::Debug("open($session_id)");
All logs need to be more verbose: At least tell that you are doing something about the sessions. Better, add a channel and context data.

2023-11-10 14:01 UTC, Molkobain commented
_Looks like my notes for this morning review got sent with the ones I just added now. You might have received them by mail, I deleted the old ones, just mind the ones still on the PR_

2023-11-10 15:23 UTC, odain-cbd commented on core/cmdbsource.class.inc.php
> +			$mysqli = DbConnectionWrapper::GetDbConnection();
just reverted

2023-11-10 15:26 UTC, odain-cbd commented
> Discussed this morning with Olivier and Eric:
> 
>     * I commited some changes
> 
>     * Olivier will do the others

just made all corrections based on your feedbacks. thanks

2023-11-10 16:18 UTC, Molkobain commented on core/log.class.inc.php
> +	public const SESSIONTRACKER = 'SessionTracker';
```suggestion
	/**
	 * @var string Everything related to PHP sessions tracking
	 * @since 3.1.1 3.2.0 N°6901
	 */
	public const SESSIONTRACKER = 'SessionTracker';
```

2023-11-10 16:18 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> + * Class iTopSessionGarbageCollector
```suggestion
 * Class SessionHandler
```

2023-11-10 16:18 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> + * @package Combodo\iTop\Application\Helper
```suggestion
 * @package Combodo\iTop\SessionTracker
```

2023-11-10 16:18 UTC, Molkobain commented on sources/SessionTracker/SessionGC.php
> + * @package Combodo\iTop\Application\Helper
```suggestion
 * @package Combodo\iTop\SessionTracker
```

2023-11-10 16:18 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +		IssueLog::Debug("gc", \LogChannels::SESSIONTRACKER, [
```suggestion
		IssueLog::Debug("write", \LogChannels::SESSIONTRACKER, [
```

2023-11-10 16:22 UTC, Molkobain commented
Great thanks! I'll set up a meeting within engineering for the follow-up.

2023-11-10 17:55 UTC, Molkobain reviewed
Specifying the log channel is great step forward as it enables us to set the log level for these specific logs.

That being said, I think it would ease reading logs (from all channels) if the messages where a little bit more explicit and say that they are about PHP session.

What do you think @odain-cbd @eespie ?

2023-11-10 17:55 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +		IssueLog::Debug("destroy", \LogChannels::SESSIONTRACKER, [
```suggestion
		IssueLog::Debug("Destroy PHP session", \LogChannels::SESSIONTRACKER, [
```

2023-11-10 17:55 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +		IssueLog::Debug("gc", \LogChannels::SESSIONTRACKER, [
```suggestion
		IssueLog::Debug("Run PHP sessions garbage collector", \LogChannels::SESSIONTRACKER, [
```

2023-11-10 17:55 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +		IssueLog::Debug("open", \LogChannels::SESSIONTRACKER, [
```suggestion
		IssueLog::Debug("Open PHP session", \LogChannels::SESSIONTRACKER, [
```

2023-11-10 17:55 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +		IssueLog::Debug("write", \LogChannels::SESSIONTRACKER, [
```suggestion
		IssueLog::Debug("Write PHP session", \LogChannels::SESSIONTRACKER, [
```

2023-11-10 17:55 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +		$_SESSION = [];
This might not be necessary anymore. We should discuss with @rquetiez

2023-11-10 18:01 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +					'context' => implode("|", ContextTag::GetStack())
```suggestion
					'contexts' => implode("|", ContextTag::GetStack())
```

Making this plural as it contains all context tags currently set.
@odain-cbd you might need to adjust your monitoring module.

2023-11-10 18:02 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +					'contexts' => implode("|", ContextTag::GetStack())
```suggestion
					'context' => implode("|", ContextTag::GetStack())
```

Previous change was actually stupid as we already use singular everywhere else.

2023-11-13 08:10 UTC, Molkobain commented
@odain-cbd they is an issue with the PR, there now are 29 commits and some changed files that should not be there.
Let's check together when you have a moment.

2023-11-14 10:59 UTC, Molkobain commented
Discussed IRL with Alexandre, Olivier and Romain:
- Add random session GC trigger on session opening to ensure files are cleared even without a CRON running. See what is done in `\privUITransactionFile::CleanupOldTransactions()`
- Session handler override will be conditioned to a config. param. disabled by default.
```php
		'session.enable_custom_session_handler' => [
			'type' => 'bool',
			'description' => 'Enable custom handler to have PHP sessions logs (opened, destroyed, ...) and generate additional session files for monitoring purposes',
			'default' => false,
			'value' => false,
			'source_of_value' => '',
			'show_in_conf_sample' => false,
		],
```

2023-11-15 14:41 UTC, rquetiez commented on core/config.class.inc.php
> +		'sessions_tracking_enabled' => [
It is more common to use a dot between a feature name and the various settings.
=> 'sessions_tracking.enabled'

2023-11-15 14:42 UTC, rquetiez commented on core/config.class.inc.php
> +			'description'         => 'probability in percent for the garbage collector to be triggered (100 mean always)',
What does that mean? What happens when the garbage collector is triggered?

2023-11-15 14:54 UTC, rquetiez commented on sources/SessionTracker/SessionHandler.php
> +class SessionHandler extends \SessionHandler
This is a bit mysterious. I had to focus on the namespace to figure out what was the purpose of such a class having the same name as its parent class.
I suggest adding a comment like "Tracks active user sessions in files"
Possibly also name the class like "FileTrackedSession"

2023-11-15 14:59 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +		$this->assertEquals($sUserId, $aJson['user_id'] ?? '', $sContent);
In case the test fails, the message will be cryptic => $sContent
I would rather have something like "Session content should have the user_id entry, found $sContent"

2023-11-15 15:01 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +		$this->assertEquals($sUserId, $aJson['user_id'] ?? '', $sContent);
Same comment for most of the assertions above.

2023-11-15 15:10 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testTouchSessionFile_UserLoggedInWithImpersonation(){
The first part (until UserRights::Impersonate) seems 100% redundant with the preceding test. Either keep only this test (prefered for speed of tests), or remove all the assertions of the first part.

2023-11-15 15:20 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testGenerateSessionContentWithSessionContextChange(){
The first part is 100% identical to the previous tests.
Please Keep the complete version and rename it to testGenerateSessionContent, for the sake of clarity.

2023-11-15 15:26 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +			$this->assertTrue(is_file($sFile));
$this->assertTrue(is_file($sFile), 'list_session_files is should return only existing files. Not found: '.$sFile);

2023-11-15 15:30 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +		for($i=0; $i<=1; $i++) {
Please use a constant or variable to help the reader understanding the relation between this loop and the assertion on line 264.
Suggestion :
for ($i = 0 ; $i < FAKE_FILE_COUNT ; $i++)

2023-11-15 15:32 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +		for($i=0; $i<=1; $i++) {
for ($i = 0 ; $i < FAKE_FILE_COUNT ; $i++)

2023-11-15 15:37 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testGgcWithTimeLimit_EmptyFile($iTimeLimit, $iExpectedProcessed) {
What is the difference between an empty file and a file containing the word "fake"?
I wonder if this test could be merged with the previous one.

2023-11-15 21:51 UTC, odain-cbd commented on core/config.class.inc.php
> +		'sessions_tracking_enabled' => [
yes it could be nicer. but this is not compliant with other existing variables like _transactions_gc_threshold_...

i could also have added an array instead (my first choice before seeing transaction* vars):
```
'sessions_tracking' =>
[ 'enabled' => true, 'gc_collector' => 'xx', 'gc_timelimit' => 'YY']
```

2023-11-15 21:53 UTC, odain-cbd commented on core/config.class.inc.php
> +			'description'         => 'probability in percent for the garbage collector to be triggered (100 mean always)',
it is the probability the gc is triggered in fact at each Session.start(). nothing new as I relied on transaction existing cleanup logic

2023-11-15 22:00 UTC, odain-cbd commented on sources/SessionTracker/SessionHandler.php
> +class SessionHandler extends \SessionHandler
good point. still name should end with SessionHandler at least.

defaut PHP SessionHandler already relies on files. this new iTop SessionHandler keeps on calling his parent first. and afterwards creates files apart in itop folders (/data/...) with very few data.

what about FileActiveSessionTrackerSessionHandler? or ActiveSessionTrackerSessionHandler? seems quite long, no?

2023-11-15 22:02 UTC, odain-cbd commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testGgcWithTimeLimit_EmptyFile($iTimeLimit, $iExpectedProcessed) {
one test consists in checking empty files are cleaned up. 

the other is a mix where I test cleanup works on a list of existing non empty files and files that do not existing (fake should be renaming: non-existing-file).

2023-11-15 22:05 UTC, odain-cbd commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testGgcWithTimeLimit_EmptyFile($iTimeLimit, $iExpectedProcessed) {
empty files are for unauthentified active sessions (when we call status.php). in most cases files are not empty and there are authentication data inside (login_mode/context/user_id).

2023-11-16 15:05 UTC, odain-cbd commented on sources/SessionTracker/SessionHandler.php
> +class SessionHandler extends \SessionHandler
add phpdoc only but no renaming

2023-11-16 15:06 UTC, odain-cbd commented on tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
> +	public function testTouchSessionFile_UserLoggedInWithImpersonation(){
merged some tests and add comments in case of failures

2023-11-16 15:07 UTC, Hipska commented on sources/SessionTracker/SessionHandler.php
> +class SessionHandler extends \SessionHandler
What about `TrackingSessionHandler`?

2023-11-16 15:49 UTC, Molkobain commented on sources/SessionTracker/SessionHandler.php
> +class SessionHandler extends \SessionHandler
I asked Olivier to named it like that.

For information, it is very common (and a good practice) to have a class with the same name as the one it is extending, the namespace is here to differenciate them.

To ease the understanding, the usual convention is to do something like this (I'm not asking Olivier to do it, just we spread awereness):

```php
namespace A\B;

use SessionHandler as BaseSessionHandler; // This makes an alias for this class to be used in this file

class SessionHandler extends BaseSessionHandler
{
    [...]
}
```

2023-11-22 16:44 UTC, rquetiez approved these changes
Reviewed the tests

2023-11-22 16:46 UTC, merged