Avoid behat scenario loading issues on portal modal
Combodo/iTop pull request #569
Opened 2023-11-08 16:57 UTC by piRGoif

Factorize the existing ready script workaround to use it also in field_set.js (used to display forms in portal modal)

2023-11-08 16:58 UTC, piRGoif commented
@odain-cbd  and @Molkobain can you do a review before I can merge ?

2023-11-09 08:44 UTC, piRGoif commented
Review with Olivier : we should avoid setting done too soon... 
For example : 

1. process A does start
2. process B does start
3. process B does end
4. process A does end

The body attr should only be set to end on 4, not on 3...

Maybe we could simply add a counter as another body attr ? There could be issues with concurrency, but as we just have few consumers now and considering the need (not doing end too soon) it might be not worse it to handle it.

2023-11-09 10:46 UTC, piRGoif commented
> we should avoid setting done too soon...

Done with 927d985a

@odain-cbd can you have a look ?

2023-11-09 11:12 UTC, odain-cbd approved these changes
muy bien!

2023-11-09 11:27 UTC, Molkobain commented
Will discuss IRL tomorrow with Pierre

2023-11-10 10:43 UTC, piRGoif commented
As seen with Guillaume, the process is : 

```
ajaxSend
ajaxComplete
object create ready START
field_set START
field_set END
object create ready END
```

As a consequence I moved the start/finish to the object template.

@Molkobain can you do a final review ?

2023-11-10 13:20 UTC, Molkobain commented on js/field_set.js
Can you revert this file from the PR so we don't get mislead when overlooking at the history?

2023-11-10 13:22 UTC, Molkobain requested changes

2023-11-10 13:22 UTC, Molkobain commented on js/utils.js
> +}
```suggestion
	BODY_DATA_ATTR_NAME_READY: "data-ready-scripts",

	/**
	 * Counter so that we set the flag as done only on the last call
	 * @type number
	 */
	iOngoingScriptsCount: 0,

	SetScriptOngoing: function() {
		this.iOngoingScriptsCount++;
		$("body").attr(this.BODY_DATA_ATTR_NAME_READY, "start");
	},

	SetScriptFinished: function() {
		this.iOngoingScriptsCount--;

		if (this.iOngoingScriptsCount < 1) {
			$("body").attr(this.BODY_DATAATTR_NABODY_DATA_ATTR_NAME_READYE_READY, "done");
		}
	}
}
```

2023-11-10 13:30 UTC, Molkobain requested changes

2023-11-10 13:30 UTC, Molkobain commented on js/utils.js
> +		if (this.OngoingScriptsCount < 1) {
```suggestion
	iOngoingScriptsCount: 0,

	AddOngoingScript: function() {
		this.iOngoingScriptsCount++;
		$("body").attr(this.BODY_DATAATTR_NAME_READY, "start");
	},

	RemoveOngoingScript: function() {
		this.iOngoingScriptsCount--;

		if (this.iOngoingScriptsCount < 1) {
```

To be consistent with other helpers, then ok to merge.

2023-11-10 13:57 UTC, piRGoif commented on js/utils.js
> +}
Done in 9ba4cf0d

2023-11-10 13:57 UTC, piRGoif commented on js/utils.js
> +		if (this.OngoingScriptsCount < 1) {
Done

2023-11-10 13:58 UTC, piRGoif commented on js/field_set.js
Done in d3e2dd4a !

2023-11-10 14:10 UTC, merged