N°6228 php constraint and computation
Combodo/iTop pull request #573
Opened 2023-11-17 10:18 UTC by eespie

Handle with_php_constraint and with_php_computation for cascading CheckToWrite and EVENT_DB_LINKS_CHANGED

2023-11-17 14:54 UTC, piRGoif requested changes
Some questions : 
- CheckPhpConstraint : shouldn't we protect the new call by ensuring the attr is part of changes ?
- AttributeDefinitionTest : we could add a test for GetHasComputation (but might not be that usefull ?)

And some remarks on CheckToWritePropagationTest:
- the code is very hard to read, instead of doing a review on my own can we organize a workshop with Olivier ?
- on my laptop 12s to process for 18 tests, we should search if we can improve perfs !

2023-11-20 08:21 UTC, Hipska commented on core/attributedef.class.inc.php
> +	public function GetHasComputation()
Double action in the name
```suggestion
	public function HasComputation()
```

2023-11-22 09:45 UTC, Molkobain commented on core/dbobject.class.php
> +	final protected function TriggerOnRemoteObjectUpdate(): void
There is still this method to rename to as for now it feels like this is for when the remote object has been updated when it is actually to trigger the remote object because there has been an update on the current object.

Also "target" instead of "remote".

2023-11-22 09:51 UTC, Molkobain commented on core/attributedef.class.inc.php
> +	public function HasConstraint()
```suggestion
	public function HasConstraint(): bool
```

2023-11-22 09:51 UTC, Molkobain commented on core/attributedef.class.inc.php
> +	public function HasComputation()
```suggestion
	public function HasComputation(): bool
```

2023-11-22 09:51 UTC, Molkobain commented on core/attributedef.class.inc.php
> +	public function HasConstraint()
Why not call it `HasPHPConstraint` to match the property name? If we introduce another type of constraint, we'll be stucked.
Same for `HasComputation`

2023-11-22 09:51 UTC, Molkobain commented on core/trigger.class.inc.php
> +	 * @throws \OQLException
```suggestion
	 * @throws \OQLException
	 * @since 3.1.1 3.2.0 N°6228
```

2023-11-22 09:51 UTC, Molkobain commented on core/userrights.class.inc.php
> +	}
Why is that here? It is a very specific profile check. Last time we discussed about this, It was reverted as it was stated that a modelisation of profiles dependancies should be done instead of this.

We should talk about this we @rquetiez tomorrow.

2023-11-22 13:22 UTC, eespie commented on core/userrights.class.inc.php
> +	}
reverted

2023-11-22 13:22 UTC, eespie commented on core/dbobject.class.php
> +	final protected function TriggerOnRemoteObjectUpdate(): void
done

2023-11-22 16:46 UTC, piRGoif requested changes
- excellent tests, bravo !
- warning for next time : there were multiple formatting changes pushed in DBObject which add complexity to the review process
- also the formatter used doesn't seem to be very accurate (braces on new line after if statement for example)
- if I understand correctly User::CheckPortalProfiles was removed in profit of the one and only User::CheckToWrite right ? But that makes me wonder why we kept User::CheckPortalProfiles in the first place ?
- very confusing methods names on trigger :( (TriggerOnObjectUpdate / TriggerOnTargetObjectUpdate / TriggerTargetObject)

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	protected function PostUpdateActions(array $aChanges): void
Method was public and is still on support/3.1 branch
Seems like a mistake right ?

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	final protected function CascadeCheckToWrite(bool $bIsCheckToDelete = false): void
Previous name was `CheckPhpConstraint`
I really don't like this new name which is very generic and doesn't tells AT ALL what is cascading.
I would keep the XML attr in the method name to keeps things clear functionally speaking.
Maybe something like `CheckAttrWithPhpConstraintProperty` ?

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @since 3.1.1 3.2.0 N°6228 method creation
We don't have cristal clear rules on that, but to expose the intention to everyone I would add an `@internal` pdpdoc tag ?

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	private function DoCheckToWriteOnTargetObject(string $sAction, ?DBObject $oTargetObject, string $sAttCodeMirrorLink, bool $bIsCheckToDelete): void
I would remove the "Do" cause : 
- CheckToWrite is the internal method
- DoCheckToWrite is an API hook

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
> +
```suggestion
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$sLogin = 'testCascadeCheckToWrite-'.uniqid('', true);
```suggestion
		$sLogin = uniqid('testCascadeCheckToWrite-', true);
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$sLogin = 'testCascadeCheckToWrite-'.uniqid('', true);
```suggestion
		$sLogin = uniqid('testCascadeCheckToWrite-', true);
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$this->assertArrayHasKey($this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, 'UserLocal', $sUserId1), self::$aEventCalls, 'User checkToWrite should be called when a URP_UserProfile is created');
```suggestion
		$this->assertArrayHasKey(
			$this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, UserLocal::class, $sUserId1), 
			self::$aEventCalls, 
			'User checkToWrite should be called when a URP_UserProfile is created'
		);
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$this->assertArrayHasKey($this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, 'UserLocal', $sUserId1), self::$aEventCalls, 'User checkToWrite should be called when a URP_UserProfile is updated');
```suggestion
		$this->assertArrayHasKey(
			$this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, UserLocal::class, $sUserId1), 
			self::$aEventCalls, 
			'User checkToWrite should be called when a URP_UserProfile is updated'
		);
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$this->assertArrayHasKey($this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, 'UserLocal', $sUserId2), self::$aEventCalls, 'New User checkToWrite should be called when a URP_UserProfile is moved from a User
```suggestion
		$this->assertArrayHasKey(
			$this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, UserLocal::class, $sUserId1), 
			self::$aEventCalls, 
			'Previous User checkToWrite should be called when a URP_UserProfile is moved from a User to another'
		);
		$this->assertArrayHasKey(
			$this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, UserLocal::class, $sUserId2), 
			self::$aEventCalls, 
			'New User checkToWrite should be called when a URP_UserProfile is moved from a User to another'
		);
```

2023-11-22 16:46 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/core/DBObject/CheckToWritePropagationTest.php
> +		$this->assertArrayHasKey($this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, 'UserLocal', $sUserId2), self::$aEventCalls, 'User checkToWrite should be called when a URP_UserProfile is deleted');
```suggestion
		$this->assertArrayHasKey(
			$this->GetEventKey(EVENT_DB_CHECK_TO_WRITE, UserLocal::class, $sUserId2), 
			self::$aEventCalls, 
			'User checkToWrite should be called when a URP_UserProfile is deleted'
		);
```

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	final protected function TriggerOnTargetObjectUpdate(): void
Maybe rename to something like TriggerTargetObjectOnObjectUpdate ?

2023-11-22 16:46 UTC, piRGoif commented on core/dbobject.class.php
> +	private function TriggerTargetObject(?DBObject $oRemoteObject, string $sAttCodeMirrorLink): void
Rename maybe to something like TriggerOnObjectUpdateWithTargetObject ?
Also, parameter name is "remoteObject", we should decide what to use between remote and target

2023-11-22 16:46 UTC, piRGoif commented on core/trigger.class.inc.php
> +		}
I really dislike the bGo var use :(
The dev team talked about that in the past (reducing all those unreadable if), it's far more readable to use return statements instead ! 

So I would suggest : 

```suggestion
		if (false === isset($aContextArgs['this->object()'])) {
			return;
		}
		
		/** @var \DBObject $oObject */
		$oObject = $aContextArgs['this->object()'];
		if (is_null($aAttributes)) {
			if (false === $this->IsTargetObject($oObject->GetKey(), $oObject->ListPreviousValuesForUpdatedAttributes())) {
				return;
			}
		} else {
			$aChanges = array_fill_keys($aAttributes, true);
			if (false === $this->IsTargetObject($oObject->GetKey(), $aChanges)) {
				return;
			}
		}

		/** @noinspection MissUsingParentKeywordInspection */
		parent::DoActivate($aContextArgs);
```

2023-11-23 10:16 UTC, merged