N°6933 - SF 6.4 - Remove deprecated calls
Combodo/iTop pull request #577
Opened 2023-11-22 07:21 UTC by bdalsass

Remove Symfony 5.4 related deprecated calls.
- Replace container access with constructor dependency injection
- Use setter router  dependency injection in abstract controller

2023-11-22 10:26 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/AbstractController.php
> +	private RouterInterface $oRouterInterface;
Why name the variable `$oRouterInterface` instead of `$oRouter` ?

2023-11-22 10:26 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		protected BrickCollection $oBrickCollection
With that way of declaring properties, are they visible in the IDE ? Are they visible with the Reflection API?

2023-11-22 10:35 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/AbstractController.php
> +	private RouterInterface $oRouterInterface;
👍 done

2023-11-22 10:42 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		protected BrickCollection $oBrickCollection
OK in PhpStorm and with reflexion API (cf screenshot)

![2023-11-22_11h41_00](https://github.com/Combodo/iTop/assets/95754414/61190b9d-4023-499a-9df1-554a0541a594)

The opposite would have been surprising

2023-11-23 09:53 UTC, piRGoif requested changes

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
Maybe rename to $oRequestManipulatorHelper ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +	public function __construct(
Not really useful, this phpdoc can be removed

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/CreateBrickController.php
> +	public function DisplayAction(Request $oRequest, $sBrickId) : Response
Change of a public method signature, this is risky ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
Maybe rename to oRequestManipulatorHelper ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		protected ScopeValidatorHelper $oScopeValidator,
Maybe rename to oScopeValidatorHelper ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		protected UrlGenerator $oUrlGenerator,
Add the helper suffix ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
Add the Helper suffix ?

2023-11-23 09:53 UTC, piRGoif commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		protected BrickCollection $oBrickCollection,
Add the Helper suffix ?

2023-11-23 10:01 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/CreateBrickController.php
> +	public function DisplayAction(Request $oRequest, $sBrickId) : Response
done

2023-11-23 10:35 UTC, piRGoif commented
Discussed with Benjamin : 
- X_FORWARDED const will be split in another ticket
- method signature must be restored
- var naming to be discussed, might keep it as is ?

2023-11-23 13:21 UTC, Molkobain reviewed
Just naming / PHPDoc comments, otherwise it seems all good!
As I'm a nice coworker I added all suggestions so you just have to apply them at once.

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/AbstractController.php
> +	private RouterInterface $oRouter;
```suggestion
	/**
	 * @var \Symfony\Component\Routing\RouterInterface symfony router
	 * @since 3.2.0 N°6933
	 */
	private RouterInterface $oRouter;
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/AggregatePageBrickController.php
> +	public function __construct(
```suggestion
	/**
	 * Constructor.
	 *
	 * @param \Combodo\iTop\Portal\Brick\BrickCollection $oBrickCollection
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +	public function __construct(
```suggestion
	/**
	 * Constructor.
	 *
	 * @param \Combodo\iTop\Portal\Helper\BrowseBrickHelper $oBrowseBrickHelper
	 * @param \Combodo\iTop\Portal\Helper\RequestManipulatorHelper $oRequestManipulator
	 * @param \Combodo\iTop\Portal\Helper\BrickControllerHelper $oBrickControllerHelper
	 * @param \Combodo\iTop\Portal\Brick\BrickCollection $oBrickCollection
	 *
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
```suggestion
		protected RequestManipulatorHelper $oRequestManipulatorHelper,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		$sDataLoading = ($sDataLoading !== null) ? $sDataLoading : $this->oRequestManipulator->ReadParam('sDataLoading',
```suggestion
		$sDataLoading = ($sDataLoading !== null) ? $sDataLoading : $this->oRequestManipulatorHelper->ReadParam('sDataLoading',
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		$sRawSearchValue = $this->oRequestManipulator->ReadParam('sSearchValue', '');
```suggestion
		$sRawSearchValue = $this->oRequestManipulatorHelper->ReadParam('sSearchValue', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +					$iListLength = (int)$this->oRequestManipulator->ReadParam('iListLength', BrowseBrick::DEFAULT_LIST_LENGTH,
```suggestion
					$iPageNumber = (int)$this->oRequestManipulatorHelper->ReadParam('iPageNumber', 1, FILTER_SANITIZE_NUMBER_INT);
					$iListLength = (int)$this->oRequestManipulatorHelper->ReadParam('iListLength', BrowseBrick::DEFAULT_LIST_LENGTH,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +					$sNodeId = $this->oRequestManipulator->ReadParam('sNodeId', '');
```suggestion
					$sLevelAlias = $this->oRequestManipulatorHelper->ReadParam('sLevelAlias', '');
					$sNodeId = $this->oRequestManipulatorHelper->ReadParam('sNodeId', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/CreateBrickController.php
> +	public function __construct(
```suggestion
	/**
	 * Constructor.
	 *
	 * @param \Combodo\iTop\Portal\Brick\BrickCollection $oBrickCollection
	 *
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +	public function __construct(
```suggestion
	/**
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
```suggestion
		protected RequestManipulatorHelper $oRequestManipulatorHelper,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		$sDataLoading = $this->oRequestManipulator->ReadParam('sDataLoading', $oBrick->GetDataLoading());
```suggestion
		$sDataLoading = $this->oRequestManipulatorHelper->ReadParam('sDataLoading', $oBrick->GetDataLoading());
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		$sGroupingArea = $this->oRequestManipulator->ReadParam('sGroupingArea', '');
```suggestion
		$sGroupingArea = $this->oRequestManipulatorHelper->ReadParam('sGroupingArea', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +						$iListLength = (int)$this->oRequestManipulator->ReadParam('iListLength', ManageBrick::DEFAULT_LIST_LENGTH,
```suggestion
						$iPageNumber = (int)$this->oRequestManipulatorHelper->ReadParam('iPageNumber', 1, FILTER_SANITIZE_NUMBER_INT);
						$iListLength = (int)$this->oRequestManipulatorHelper->ReadParam('iListLength', ManageBrick::DEFAULT_LIST_LENGTH,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		$sRawSearchValue = trim($this->oRequestManipulator->ReadParam('sSearchValue', ''));
```suggestion
		$sRawSearchValue = trim($this->oRequestManipulatorHelper->ReadParam('sSearchValue', ''));
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
```suggestion
		protected RequestManipulatorHelper $oRequestManipulatorHelper,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		protected UrlGenerator $oUrlGenerator,
Wrong line I guess?

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', '');
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$sBrickId = $this->oRequestManipulator->ReadParam('sBrickId', '');
```suggestion
			$sBrickId = $this->oRequestManipulatorHelper->ReadParam('sBrickId', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', '');
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$sBrickId = $this->oRequestManipulator->ReadParam('sBrickId', '');
```suggestion
			$sBrickId = $this->oRequestManipulatorHelper->ReadParam('sBrickId', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', '');
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$sActionRulesToken = $this->oRequestManipulator->ReadParam('ar_token', '');
```suggestion
			$sActionRulesToken = $this->oRequestManipulatorHelper->ReadParam('ar_token', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			'sActionRulesToken' => $this->oRequestManipulator->ReadParam('ar_token', ''),
```suggestion
			'sActionRulesToken' => $this->oRequestManipulatorHelper->ReadParam('ar_token', ''),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sFormManagerData = $this->oRequestManipulator->ReadParam('formmanager_data', '', FILTER_UNSAFE_RAW);
```suggestion
		$sFormManagerClass = $this->oRequestManipulatorHelper->ReadParam('formmanager_class', '', FILTER_UNSAFE_RAW);
		$sFormManagerData = $this->oRequestManipulatorHelper->ReadParam('formmanager_data', '', FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +				'currentValues' => $this->oRequestManipulator->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```suggestion
				'currentValues' => $this->oRequestManipulatorHelper->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$aObjectIdsToIgnore = $this->oRequestManipulator->ReadParam('aObjectIdsToIgnore', null, FILTER_UNSAFE_RAW);
```suggestion
		$iPageNumber = $this->oRequestManipulatorHelper->ReadParam('iPageNumber', static::DEFAULT_PAGE_NUMBER, FILTER_SANITIZE_NUMBER_INT);
		$iListLength = $this->oRequestManipulatorHelper->ReadParam('iListLength', static::DEFAULT_LIST_LENGTH, FILTER_SANITIZE_NUMBER_INT);
		$bInitialPass = $this->oRequestManipulatorHelper->HasParam('draw') ? false : true;
		$sQuery = $this->oRequestManipulatorHelper->ReadParam('sSearchValue', '');
		$sFormPath = $this->oRequestManipulatorHelper->ReadParam('sFormPath', '');
		$sFieldId = $this->oRequestManipulatorHelper->ReadParam('sFieldId', '');
		$aObjectIdsToIgnore = $this->oRequestManipulatorHelper->ReadParam('aObjectIdsToIgnore', null, FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sObjectField = $this->oRequestManipulator->ReadParam('sObjectField', '');
```suggestion
		$sObjectClass = $this->oRequestManipulatorHelper->ReadParam('sObjectClass', '');
		$sObjectId = $this->oRequestManipulatorHelper->ReadParam('sObjectId', '');
		$sObjectField = $this->oRequestManipulatorHelper->ReadParam('sObjectField', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$iCacheSec = $this->oRequestManipulator->ReadParam('cache', 0, FILTER_SANITIZE_NUMBER_INT);
```suggestion
			$iCacheSec = $this->oRequestManipulatorHelper->ReadParam('cache', 0, FILTER_SANITIZE_NUMBER_INT);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$sOperation = $this->oRequestManipulator->ReadParam('operation', null);
```suggestion
			$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', null);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +				$sTempId = $this->oRequestManipulator->ReadParam('temp_id', '');
```suggestion
				$sFieldName = $this->oRequestManipulatorHelper->ReadParam('field_name', '');
				$sObjectClass = $this->oRequestManipulatorHelper->ReadParam('object_class', '');
				$sTempId = $this->oRequestManipulatorHelper->ReadParam('temp_id', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +					'sObjectId' => $this->oRequestManipulator->ReadParam('sAttachmentId', null),
```suggestion
					'sObjectId' => $this->oRequestManipulatorHelper->ReadParam('sAttachmentId', null),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$aObjectAttCodes = $this->oRequestManipulator->ReadParam('aObjectAttCodes', array(), FILTER_UNSAFE_RAW);
```suggestion
		$sObjectClass = $this->oRequestManipulatorHelper->ReadParam('sObjectClass', '');
		$aObjectIds = $this->oRequestManipulatorHelper->ReadParam('aObjectIds', array(), FILTER_UNSAFE_RAW);
		$aObjectAttCodes = $this->oRequestManipulatorHelper->ReadParam('aObjectAttCodes', array(), FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sDateTimePickerWidgetParent = $this->oRequestManipulator->ReadParam('sDateTimePickerWidgetParent', array(), FILTER_UNSAFE_RAW);
```suggestion
		$sObjectClass = $this->oRequestManipulatorHelper->ReadParam('sObjectClass', '');
		$sLinkClass = $this->oRequestManipulatorHelper->ReadParam('sLinkClass', '');
		$aObjectIds = $this->oRequestManipulatorHelper->ReadParam('aObjectIds', array(), FILTER_UNSAFE_RAW);
		$aObjectAttCodes = $this->oRequestManipulatorHelper->ReadParam('aObjectAttCodes', array(), FILTER_UNSAFE_RAW);
		$aLinkAttCodes = $this->oRequestManipulatorHelper->ReadParam('aLinkAttCodes', array(), FILTER_UNSAFE_RAW);
		$sDateTimePickerWidgetParent = $this->oRequestManipulatorHelper->ReadParam('sDateTimePickerWidgetParent', array(), FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', '');
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			$sBrickId = $this->oRequestManipulator->ReadParam('sBrickId', '');
```suggestion
			$sBrickId = $this->oRequestManipulatorHelper->ReadParam('sBrickId', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			'ar_token' => $this->oRequestManipulator->ReadParam('ar_token', ''),
```suggestion
			'ar_token' => $this->oRequestManipulatorHelper->ReadParam('ar_token', ''),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		$sBrickId = $this->oRequestManipulator->ReadParam('sBrickId', '');
```suggestion
		$sBrickId = $this->oRequestManipulatorHelper->ReadParam('sBrickId', '');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
```suggestion
		protected RequestManipulatorHelper $oRequestManipulatorHelper,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
> +		$sMessageContent = $this->oRequestManipulator->ReadParam('sContent');
```suggestion
		$sMessageSeverity = $this->oRequestManipulatorHelper->ReadParam('sSeverity');
		$sMessageContent = $this->oRequestManipulatorHelper->ReadParam('sContent');
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
```suggestion
		protected RequestManipulatorHelper $oRequestManipulatorHelper,
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		protected BrickCollection $oBrickCollection,
Wrong line i guess?

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +			$aCurrentValues = $this->oRequestManipulator->ReadParam('current_values', array(), FILTER_UNSAFE_RAW);
```suggestion
			$aCurrentValues = $this->oRequestManipulatorHelper->ReadParam('current_values', array(), FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', null);
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', null);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +				$sFormManagerData = $this->oRequestManipulator->ReadParam('formmanager_data', null, FILTER_UNSAFE_RAW);
```suggestion
				$sFormManagerClass = $this->oRequestManipulatorHelper->ReadParam('formmanager_class', null, FILTER_UNSAFE_RAW);
				$sFormManagerData = $this->oRequestManipulatorHelper->ReadParam('formmanager_data', null, FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +					'currentValues' => $this->oRequestManipulator->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```suggestion
					'currentValues' => $this->oRequestManipulatorHelper->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +			$this->oRequestManipulator->ReadParam('operation', null);
```suggestion
			$this->oRequestManipulatorHelper->ReadParam('operation', null);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +				$sFormManagerData = $this->oRequestManipulator->ReadParam('formmanager_data', null, FILTER_UNSAFE_RAW);
```suggestion
				$sFormManagerClass = $this->oRequestManipulatorHelper->ReadParam('formmanager_class', null, FILTER_UNSAFE_RAW);
				$sFormManagerData = $this->oRequestManipulatorHelper->ReadParam('formmanager_data', null, FILTER_UNSAFE_RAW);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +					'currentValues' => $this->oRequestManipulator->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```suggestion
					'currentValues' => $this->oRequestManipulatorHelper->ReadParam('current_values', array(), FILTER_UNSAFE_RAW),
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		$sOperation = $this->oRequestManipulator->ReadParam('operation', null);
```suggestion
		$sOperation = $this->oRequestManipulatorHelper->ReadParam('operation', null);
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +
```suggestion
	/**
	 * @since 3.2.0 N°6933
	 */
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
> +	public function __construct(
```suggestion
	/**
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-23 13:21 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +	public function __construct(
```suggestion
	/**
	 * @since 3.2.0 N°6933
	 */
	public function __construct(
```

2023-11-24 07:13 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
done

2023-11-24 07:13 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
done

2023-11-24 07:13 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
> +		protected ScopeValidatorHelper $oScopeValidator,
done

2023-11-24 07:14 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +		protected UrlGenerator $oUrlGenerator,
done

2023-11-24 07:14 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
> +		protected RequestManipulatorHelper $oRequestManipulator,
done

2023-11-24 07:14 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
> +		protected BrickCollection $oBrickCollection,
done

2023-11-24 07:14 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
> +	public function __construct(
keep for now

2023-11-24 07:55 UTC, merged