Hungarian translations based on iTop 3.0.2-1
Combodo/iTop pull request #584
Opened 2023-12-11 17:43 UTC by piRGoif

This is an integration of @tacsaby translations
Many thanks for this big work !

I ran tests and fixed some placeholder errors
Then ran a manual check, some remarks will follow as PR comments

Also note that modifications are based on the support/3.0 branch, but product team might decide to integrate this work in another version (3.1.x or 3.2.0). This will be discussed during functional review.

2023-12-11 17:46 UTC, piRGoif commented
I modified some "+" keys from the `'~~'` value to simply `''`
But there were lots of them so I stopped. 
In your future translations @tacsaby you may do this : it is a clear statement that the key was reviewed and stays with an empty value in this language.

2023-12-11 17:49 UTC, piRGoif commented
Alors, there were lots of "+" dict keys that remains with their english values, whereas they non "+" counterparts were translated. I would expect those "+" values would be emptied ?

What keys I saw : 

datamodels/2.x/itop-change-mgmt/dictionaries/hu.dict.itop-change-mgmt.php
Class:Change/Attribute:category/Value:application+
and the following keys


datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
Class:SoftwareInstance/Attribute:status/Value:active+
Class:SoftwareInstance/Attribute:status/Value:inactive+

Class:Model/Attribute:type/Value:Enclosure+
Class:Model/Attribute:type/Value:MobilePhone+
Class:Model/Attribute:type/Value:NAS+
Class:Model/Attribute:type/Value:NetworkDevice+
Class:Model/Attribute:type/Value:PC+
Class:Model/Attribute:type/Value:PDU+
Class:Model/Attribute:type/Value:Peripheral+
Class:Model/Attribute:type/Value:Printer+
Class:Model/Attribute:type/Value:Rack+
Class:Model/Attribute:type/Value:SANSwitch+


datamodels/2.x/itop-incident-mgmt-itil/dictionaries/hu.dict.itop-incident-mgmt-itil.php
Menu:IncidentManagement+

Class:Incident/Attribute:resolution_code/Value:assistance+
Class:Incident/Attribute:resolution_code/Value:bug fixed+
and the following keys

Class:Incident/Attribute:user_satisfaction/Value:1+
Class:Incident/Attribute:user_satisfaction/Value:2+
and the following keys


datamodels/2.x/itop-knownerror-mgmt/dictionaries/hu.dict.itop-knownerror-mgmt.php
Class:KnownError/Attribute:domain/Value:Application+
Class:KnownError/Attribute:domain/Value:Desktop+
Class:KnownError/Attribute:domain/Value:Network+
Class:KnownError/Attribute:domain/Value:Server+


datamodels/2.x/itop-request-mgmt/dictionaries/hu.dict.itop-request-mgmt.php
Class:UserRequest/Attribute:request_type/Value:incident+
Class:UserRequest/Attribute:request_type/Value:service_request+

Class:UserRequest/Attribute:priority/Value:1+
Class:UserRequest/Attribute:priority/Value:2+
and the following keys

Class:UserRequest/Attribute:urgency/Value:1+
Class:UserRequest/Attribute:urgency/Value:2+
and the following keys

Class:UserRequest/Attribute:origin/Value:mail+
Class:UserRequest/Attribute:origin/Value:monitoring+
Class:UserRequest/Attribute:origin/Value:phone+
Class:UserRequest/Attribute:origin/Value:portal+

Class:UserRequest/Attribute:escalation_flag/Value:no+
Class:UserRequest/Attribute:escalation_flag/Value:yes+

Class:UserRequest/Attribute:resolution_code/Value:assistance+
Class:UserRequest/Attribute:resolution_code/Value:bug fixed+
Class:UserRequest/Attribute:resolution_code/Value:hardware repair+
Class:UserRequest/Attribute:resolution_code/Value:other+
Class:UserRequest/Attribute:resolution_code/Value:software patch+
Class:UserRequest/Attribute:resolution_code/Value:system update+
Class:UserRequest/Attribute:resolution_code/Value:training+

Class:UserRequest/Attribute:user_satisfaction/Value:1+
Class:UserRequest/Attribute:user_satisfaction/Value:2+
Class:UserRequest/Attribute:user_satisfaction/Value:3+
Class:UserRequest/Attribute:user_satisfaction/Value:4+


datamodels/2.x/itop-request-mgmt-itil/dictionaries/hu.dict.itop-request-mgmt-itil.php
Menu:UserRequest:Provider+

Class:UserRequest/Attribute:request_type/Value:service_request+

Class:UserRequest/Attribute:priority/Value:1+
Class:UserRequest/Attribute:priority/Value:2+
and the following keys

Class:UserRequest/Attribute:urgency/Value:1+
Class:UserRequest/Attribute:urgency/Value:2+
and the following keys

Class:UserRequest/Attribute:origin/Value:mail+
Class:UserRequest/Attribute:origin/Value:monitoring+
Class:UserRequest/Attribute:origin/Value:phone+
Class:UserRequest/Attribute:origin/Value:portal+

Class:UserRequest/Attribute:escalation_flag/Value:no+
Class:UserRequest/Attribute:escalation_flag/Value:yes+

Class:UserRequest/Attribute:resolution_code/Value:assistance+
Class:UserRequest/Attribute:resolution_code/Value:bug fixed+
Class:UserRequest/Attribute:resolution_code/Value:hardware repair+
Class:UserRequest/Attribute:resolution_code/Value:other+
Class:UserRequest/Attribute:resolution_code/Value:software patch+
Class:UserRequest/Attribute:resolution_code/Value:system update+
Class:UserRequest/Attribute:resolution_code/Value:training+

Class:UserRequest/Attribute:user_satisfaction/Value:1+
Class:UserRequest/Attribute:user_satisfaction/Value:2+
and the following keys


datamodels/2.x/itop-service-mgmt/dictionaries/hu.dict.itop-service-mgmt.php
Class:SLT/Attribute:priority/Value:1+
Class:SLT/Attribute:priority/Value:2+
and the following keys

Class:SLT/Attribute:request_type/Value:incident+
Class:SLT/Attribute:request_type/Value:service_request+

Class:SLT/Attribute:unit/Value:hours+
Class:SLT/Attribute:unit/Value:minutes+


datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
Class:ServiceSubcategory/Attribute:request_type/Value:incident+
Class:ServiceSubcategory/Attribute:request_type/Value:service_request+

Class:SLT/Attribute:priority/Value:1+
Class:SLT/Attribute:priority/Value:2+
and the following keys

Class:SLT/Attribute:metric/Value:tto+
Class:SLT/Attribute:metric/Value:ttr+

Class:SLT/Attribute:unit/Value:hours+
Class:SLT/Attribute:unit/Value:minutes+


datamodels/2.x/itop-structure/dictionaries/hu.dict.itop-structure.php
Class:Contact/Attribute:notify/Value:no+
Class:Contact/Attribute:notify/Value:yes+

2023-12-11 17:51 UTC, piRGoif commented
I saw twice the same translation duplicated in the "+" keys, and same I would expect the "+" key to be empty instead of a duplicate of the label ?


datamodels/2.x/itop-request-mgmt-itil/dictionaries/hu.dict.itop-request-mgmt-itil.php
Menu:RequestManagementProvider+
Menu:UserRequest:EscalatedRequests+


dictionaries/hu.dictionary.itop.core.php
Core:AttributeEmailAddress+
Core:AttributeIPAddress+

2023-12-11 17:51 UTC, piRGoif commented
In the months names, 11 and 12 have the same value of the english labels, is it normal ?

dictionaries/hu.dictionary.itop.ui.php
Month-11
Month-12

2023-12-11 17:54 UTC, piRGoif commented
datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
Class:Contract/Attribute:cost_currency/Value:dollars

DO NOT replace the dollar by your own currency. If you want to remove dollar and add your own national currency, create an iTop extension.

I did revert this change with d424a29e

2023-12-11 17:55 UTC, piRGoif commented
@tacsaby can you tell what you think of my different remarks ?

2023-12-12 08:53 UTC, Molkobain requested changes

2023-12-12 08:53 UTC, Molkobain commented on datamodels/2.x/combodo-webhook-integration/hu.dict.combodo-webhook-integration.php
This file is not part of this repo, it should be proposed on combodo-webhook-integration repo.

2023-12-12 09:21 UTC, Hipska requested changes
Some cosmetic changes, I can't evaluate the correctness of the translations..

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
> +));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/hu.dict.combodo-backoffice-darkmoon-theme.php
>  ));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
> +));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-config/dictionaries/hu.dict.itop-config.php
> +));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-faq-light/dictionaries/hu.dict.itop-faq-light.php
> +
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
> +));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +    'Class:Change/Attribute:parent_name+' => '~~',
Should empty `'~~'` always be removed? Maybe do a find and replace?

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
>  ?>
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/hu.dict.itop-incident-mgmt-itil.php
> +
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-oauth-client/hu.dict.itop-oauth-client.php
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-oauth-client/hu.dict.itop-oauth-client.php
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-problem-mgmt/dictionaries/hu.dict.itop-problem-mgmt.php
>  ));
```suggestion
));

```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-request-mgmt/dictionaries/hu.dict.itop-request-mgmt.php
> +
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
> +
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-service-mgmt/dictionaries/hu.dict.itop-service-mgmt.php
> +));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on datamodels/2.x/itop-structure/dictionaries/hu.dict.itop-structure.php
> +
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on dictionaries/ui/components/field/hu.dictionary.itop.field.php
>  ));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on dictionaries/ui/components/global-search/hu.dictionary.itop.global-search.php
>  ));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on dictionaries/ui/components/input/hu.dictionary.itop.input.php
>  ));
Missing newline

2023-12-12 09:21 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/hu.dictionary.itop.navigation-menu.php
```suggestion
```

2023-12-12 09:21 UTC, Hipska commented on dictionaries/ui/pages/errorpage/hu.dictionary.itop.errorpage.php
>  - The R&amp;D Team~~',
```suggestion
- The R&amp;D Team',
```

2023-12-12 11:01 UTC, piRGoif commented on datamodels/2.x/combodo-webhook-integration/hu.dict.combodo-webhook-integration.php
File removed with 74ada97c
I've done a whole check again, didn't find any other concerned modules

2023-12-12 11:07 UTC, piRGoif commented on datamodels/2.x/combodo-webhook-integration/hu.dict.combodo-webhook-integration.php
Modifications pushed to another PR in the module repo : Combodo/combodo-webhook-integration#19

2023-12-12 11:10 UTC, piRGoif commented on datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
> +));
Where ? Do you mean having an empty line on the end of file ?

2023-12-12 11:10 UTC, piRGoif commented on datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/hu.dict.combodo-backoffice-darkmoon-theme.php
>  ));
Same question as discussion above ?

2023-12-12 11:13 UTC, piRGoif commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +    'Class:Change/Attribute:parent_name+' => '~~',
Lay not ba that bad, we'll see during reviews

2023-12-12 11:24 UTC, Hipska commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +    'Class:Change/Attribute:parent_name+' => '~~',
Yeah, this PR is confusing as it is removing them on some places and in other places it is adding them, which is inconsistent.

2023-12-12 11:29 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
> +));
Yes, see the [complete file](https://github.com/Combodo/iTop/pull/584/files/d424a29e3cf9a0cc474eea752cf4e254567347fa#diff-545c7b287c788f069e51d2ec5180c24df281c0028fa314002228119a2b360cd3), there is a missing EOL at EOF, which is shown by a ⛔ icon.

2023-12-12 11:37 UTC, Hipska commented on datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/hu.dict.combodo-backoffice-darkmoon-theme.php
>  ));
Same response as above.

2023-12-12 16:35 UTC, Molkobain commented
Accepted during functional review:
  - Still corrections to be done
  - Ok for support/3.0 branch
  - If not ready before 3.0.4, will be merged in 3.0 branch anyway even though they will not be any 3.0.5 (upgrade to 3.1.x necessary)

2023-12-12 16:37 UTC, piRGoif commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +    'Class:Change/Attribute:parent_name+' => '~~',
I agree ! 
We discussed this during the review : 
- no problem to keep `'~~'`
- for + keys having same value as their counterpart, we can keep exact duplicates as iTop handles it, but if the key is translated and not its + key, then either copy / paste the translation or empty the + key

2023-12-13 08:21 UTC, Molkobain requested changes

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
`~~`added on some lines, should be reverted

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-problem-mgmt/dictionaries/hu.dict.itop-problem-mgmt.php
Many `~~` added on empty entries

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-knownerror-mgmt/dictionaries/hu.dict.itop-knownerror-mgmt.php
`~~` added on some empty entries

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-service-mgmt/dictionaries/hu.dict.itop-service-mgmt.php
`~~` added on some empty entries

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-structure/dictionaries/hu.dict.itop-structure.php
`~~` added on empty entries

2023-12-13 08:21 UTC, Molkobain commented on datamodels/2.x/itop-tickets/dictionaries/hu.dict.itop-tickets.php
`~~` added on empty entries

2023-12-13 08:21 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.core.php
`~~` added on empty entries

2023-12-13 08:21 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.ui.php
`~~` added on empty entries

2023-12-14 16:03 UTC, piRGoif commented on datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
> +));
Ok thanks.
This is not really a strict rule at Combodo.
I've done it this time (commit 3d372dde), but won't be blocking on next contributions.
Closing this conversation and other ones on same topic.

2023-12-14 16:07 UTC, piRGoif commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
> +    'Class:Change/Attribute:parent_name+' => '~~',
Reverted the '~~' + dict keys with 59233800
Closing conversation

2023-12-14 16:20 UTC, Hipska approved these changes
Great work!

2023-12-15 16:21 UTC, piRGoif commented on datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
Should be fixed in all files now (wasn't easy :/)

2023-12-15 16:41 UTC, piRGoif commented
> Alors, there were lots of "+" dict keys that remains with their english values, whereas they non "+" counterparts were translated. I would expect those "+" values would be emptied ?

Should be fixed in 3b3d9c7f

2023-12-15 16:44 UTC, piRGoif commented
We are close to be ready to merge !

@tacsaby only one thing remaining, can you confirm the month names values ? 

dictionaries/hu.dictionary.itop.ui.php
Month-11
Month-12

2023-12-18 08:47 UTC, Molkobain approved these changes
Good work!

2023-12-18 10:15 UTC, tacsaby commented
Hello,

the same
11 is november
12 is december

Pierre Goiffon ***@***.***> ezt írta (időpont: 2023. dec.
15., P 17:44):

> We are close to be ready to merge !
>
> @tacsaby <https://github.com/tacsaby> only one thing remaining, can you
> confirm the month names values ?
>
> dictionaries/hu.dictionary.itop.ui.php
> Month-11
> Month-12
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Combodo/iTop/pull/584#issuecomment-1858168563>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU2J7G6ZCGEFS25A7FKZZMDYJR45XAVCNFSM6AAAAABAQE4TGCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYGE3DQNJWGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-20 11:15 UTC, piRGoif commented
Many thanks for the answer @tacsaby !
We should be ready to merge, I'll check with the rest of the team ! (and also will add a README modification as it seems we forgot to add you in the contributors list last time :/ )

2023-12-20 13:44 UTC, Molkobain commented on README.md
> +- Tarjányi, Csaba (a.k.a [tacsaby](https://github.com/tacsaby))
```suggestion
- Stukalov, Ilya (a.k.a [@ilya](https://www.github.com/ilya-stukalov))
- Tarjányi, Csaba (a.k.a [@tacsaby](https://github.com/tacsaby))
```

2023-12-20 14:52 UTC, merged

2024-01-04 08:13 UTC, piRGoif commented
Hello,
I've merged the translations to the support/3.1 and develop branches. There were lots of conflicts on the support/3.1 merge... I've chose to keep the support/3.0 modifications on each modification.
@tacsaby can you please have a look ? You can comment directly in the corresponding merge commit (379062f), as a general commit or on specific lines