N°7059 - Symfony 6.4 - Application skeleton - sources registration
Combodo/iTop pull request #589
Opened 2023-12-14 10:19 UTC by bdalsass

- add namespace alias

2023-12-14 10:55 UTC, Molkobain commented
Discussed with Benjamin IRL, we'll add a namespace on \WebPage classes as well to remove this exception in the symfony configuration. Aliases will be there retro-compatibility as well.

2023-12-20 10:48 UTC, Molkobain requested changes

2023-12-20 10:48 UTC, Molkobain commented on setup/wizardsteps.class.inc.php
> +	public function Display(WebPage $oPage)
`use` statement missing for the WebPage namespace

2023-12-20 10:48 UTC, Molkobain commented on application/datatable.class.inc.php
> +use Combodo\iTop\Application\UI\Base\Component\DataTable\DataTableSettings;
Isn't there a missing `use` statement? `WebPage` is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on application/displayblock.class.inc.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on application/forms.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on application/ui.extkeywidget.class.inc.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on application/wizardhelper.class.inc.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/bulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/csvbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/displayablegraph.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/excelbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/htmlbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/pdfbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/spreadsheetbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/tabularbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/tagsetfield.class.inc.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on core/xmlbulkexport.class.inc.php
> -	 * @param \WebPage $oP
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on datamodels/2.x/itop-attachments/ajax.itop-attachment.php
> - * @param \AjaxPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on datamodels/2.x/itop-attachments/main.itop-attachments.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on datamodels/2.x/itop-attachments/renderers.itop-attachments.php
> -	 * @param \WebPage $oPage
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on pages/UI.php
> - * @param \WebPage $oP WebPage The page for output
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on pages/ajax.render.php
> -		// If response isn't a \WebPage, it is most likely that the output already occured, stop the script.
Isn't there a missing `use` statement? WebPage is used in some methods prototypes.

2023-12-20 10:48 UTC, Molkobain commented on sources/Application/WebPage/UnauthenticatedWebPage.php
> +	protected $sPortalPublicFolderAbsUrl;
```suggestion
	/** @since 3.2.0 */
	protected string $sPortalBaseFolderRelPath;
	/** @since 3.2.0 */
	protected string $sPortalSourcesFolderRelPath;
	/** @since 3.2.0 */
	protected string $sPortalPublicFolderRelPath;
	/** @since 3.2.0 */
	protected string $sPortalBaseFolderAbsPath;
	/** @since 3.2.0 */
	protected string $sPortalSourcesFolderAbsPath;
	/** @since 3.2.0 */
	protected string $sPortalPublicFolderAbsPath;
	/** @since 3.2.0 */
	protected string $sPortalPublicFolderAbsUrl;
```

2023-12-20 10:48 UTC, Molkobain commented on sources/Application/WebPage/UnauthenticatedWebPage.php
> +	private function Init()
```suggestion
	private function Init(): void
```

2023-12-21 07:04 UTC, bdalsass commented on setup/wizardsteps.class.inc.php
> +	public function Display(WebPage $oPage)
done

2023-12-21 07:04 UTC, bdalsass commented on application/datatable.class.inc.php
> +use Combodo\iTop\Application\UI\Base\Component\DataTable\DataTableSettings;
done

2023-12-21 07:04 UTC, bdalsass commented on application/displayblock.class.inc.php
> -	 * @param \WebPage $oPage
done

2023-12-21 07:04 UTC, bdalsass commented on application/forms.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:04 UTC, bdalsass commented on application/ui.extkeywidget.class.inc.php
> -	 * @param \WebPage $oPage
done

2023-12-21 07:04 UTC, bdalsass commented on datamodels/2.x/itop-attachments/renderers.itop-attachments.php
> -	 * @param \WebPage $oPage
done

2023-12-21 07:04 UTC, bdalsass commented on pages/UI.php
> - * @param \WebPage $oP WebPage The page for output
done

2023-12-21 07:04 UTC, bdalsass commented on pages/ajax.render.php
> -		// If response isn't a \WebPage, it is most likely that the output already occured, stop the script.
done

2023-12-21 07:05 UTC, bdalsass commented on application/wizardhelper.class.inc.php
> -	 * @param \WebPage $oPage
done

2023-12-21 07:05 UTC, bdalsass commented on core/bulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:05 UTC, bdalsass commented on core/csvbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:05 UTC, bdalsass commented on core/displayablegraph.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:05 UTC, bdalsass commented on core/excelbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:05 UTC, bdalsass commented on core/htmlbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:05 UTC, bdalsass commented on core/pdfbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:06 UTC, bdalsass commented on core/spreadsheetbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:06 UTC, bdalsass commented on core/tabularbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:06 UTC, bdalsass commented on core/xmlbulkexport.class.inc.php
> -	 * @param \WebPage $oP
done

2023-12-21 07:06 UTC, bdalsass commented on datamodels/2.x/itop-attachments/ajax.itop-attachment.php
> - * @param \AjaxPage $oPage
done

2023-12-21 07:06 UTC, bdalsass commented on datamodels/2.x/itop-attachments/main.itop-attachments.php
> -	 * @param \WebPage $oPage
done

2023-12-21 07:06 UTC, bdalsass commented on core/tagsetfield.class.inc.php
> -	 * @param \WebPage $oPage
done

2023-12-21 08:49 UTC, Molkobain approved these changes

2023-12-21 09:18 UTC, merged