:bug: composer.json dependencies correctness
Combodo/iTop pull request #59
Opened 2019-03-11 11:07 UTC by bruno-ds

Two dependencies which should not block composer are moved into the `suggest` block.
Several wrong dependencies are removed from `require`.
The `config` block was misused.

2019-03-11 11:12 UTC, Molkobain commented on composer.json
> +    "ext-ldap": "This extension is required to use LDAP as an identity provider"
Suggestion

```suggestion
    "ext-ldap": "Required to use LDAP as an identity provider"
```

2019-03-11 11:12 UTC, Molkobain commented on composer.json
> +    "ext-mcrypt": "can be used as a polyfill if either libsodium and openssl are not installed (libsodium and openssl are more secure)",
Typo

```suggestion
    "ext-mcrypt": "Can be used as a polyfill if either libsodium and openssl are not installed (libsodium and openssl are more secure)",
```

2019-03-11 14:19 UTC, piRGoif commented on composer.json
> -    "ext-cli": "*",
[Is documented as required](https://wiki.combodo.com/doku.php?id=latest:install:installing_itop#installing_the_prerequisites_on_debian_or_ubuntu_1604_and_above), but this package is only to have a /usr/bin/php, [as documented on Debian packages](https://packages.debian.org/fr/sid/php-cli)
So this is not a required php extension at all !

2019-03-11 14:20 UTC, piRGoif submitted a review, later dismissed

2019-03-11 14:28 UTC, piRGoif commented on composer.json
> +    "ext-ldap": "Required to use LDAP as an identity provider"
Only used for UserLDAP, non blocking for login (see \SetupUtils::CheckPhpAndExtensions)

2019-03-11 15:15 UTC, piRGoif commented
Discussed with Bruno : PhpStorm uses composer.json to fix PHP language level (see https://blog.jetbrains.com/phpstorm/2017/07/configuring-with-composer-in-phpstorm-2017-2/). Removing config/platform/php might not be a good idea...

2019-03-11 15:25 UTC, bruno-ds commented
I force-pushed a new version with 
```json
 "config": {
    "platform": {
      "php": "5.6.0"
    }
  }
```

As explained by @piRGoif it is required in order to 
 - force PHPstorm to syntax check the source code on the lowest supported version
 - force composer to install only dependencies compatible with the lowest supported version (instead of the local CLI version)

2019-03-11 15:26 UTC, bruno-ds commented on composer.json
>        "php": "5.6.0"
- force PHPstorm to syntax check the source code on the lowest supported version (see https://blog.jetbrains.com/phpstorm/2017/07/configuring-with-composer-in-phpstorm-2017-2/)
 - force composer to install only dependencies compatible with the lowest supported version (instead of the local CLI version)

2019-03-12 08:09 UTC, piRGoif commented
> I force-pushed a new version with

http://www.commitstrip.com/en/2019/03/11/the-force/

;o)

2019-03-12 08:09 UTC, bruno-ds commented on composer.json
> +    "ext-posix": "Not required by the core, but some extensions uses it."
Required at least by itop-integrity. 
Adding this suggest entry removes PHPstorm warnings.

2019-03-12 08:25 UTC, Hipska commented
Maybe also suggest IMAP. Or is this already included? (Used by mail-to-ticket)

2019-03-12 15:27 UTC, Hipska commented on composer.json
> -    "ext-cli": "*",
Isn't that needed to run the cron.php?

2019-03-12 17:49 UTC, piRGoif commented
> Maybe also suggest IMAP. Or is this already included? (Used by mail-to-ticket)

I created the /composer.json initially just to have an automatic switch in PHP Storm for the language level config entry. I also added some extensions to have an idea of what was mandatory to run iTop, but that was just the cherry on the cake ;).

Now Bruno really uses the file for its real purpose, and the as it was not really well written he created this PR as a place to exchange on its evolution.

Our main goal for now is to have a file :
* that won't raise an error when using Composer
* usable by PHP Storm to fix its language level
* eventually, *that would list PHP extensions required to run iTop*

As iTop requirements are listed in the official Wiki, the last point is really just an option, that we could drop. Concerning extensions requirements, we might have something in the extensions themselves (nested composer files ??), but we will see that later.

2019-03-12 17:52 UTC, piRGoif commented on composer.json
> +    "ext-posix": "Not required by the core, but some extensions uses it."
Eric confirms that this is not at all an iTop requirement, but only PHP Storm is concerned.

2019-03-13 07:29 UTC, bruno-ds commented
I use composer, but only on feature branches, in order to create quick POC.

At the moment there is no plan to use composer farther than that.

2019-03-15 13:33 UTC, piRGoif commented
Comment after our team review : just add the openssl lib as suggest :)

2019-03-15 13:34 UTC, piRGoif requested changes
add openssl  in suggest

2019-03-18 10:24 UTC, Hipska commented on composer.json
> +    "ext-opênssl": "Can be used as a polyfill if libsodium is not installed",
`ê` -> `e`

2019-03-18 10:26 UTC, bruno-ds commented on composer.json
> +    "ext-opênssl": "Can be used as a polyfill if libsodium is not installed",
corrected, thank you

2019-03-18 10:27 UTC, bruno-ds commented
On my development env. I now have :
```shell
composer check-platform-reqs
ext-dom     20031129    success  
ext-gd      7.2.15      success  
ext-iconv   7.2.15      success  
ext-json    1.6.0       success  
ext-mysqli  7.2.15      success  
ext-soap    7.2.15      success  
ext-zip     1.15.4      success  
php         7.2.15      success  
```

2019-03-18 12:54 UTC, piRGoif approved these changes

2019-03-18 14:00 UTC, merged