N°2039 - Add iTop notifications to newsroom
Combodo/iTop pull request #590
Opened 2023-12-19 09:34 UTC by steffunky

Allows you to create Actions which, when triggered by a Trigger (🙃), will create notifications in the user's newsroom.

![image](https://github.com/Combodo/iTop/assets/5959857/40590df7-9c7f-4214-977a-f1192de4b713)

2023-12-19 09:39 UTC, Hipska commented on sources/Core/Notification/Action/ActioniTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeString("url", array("allowed_values" => null, "sql" => "url", "default_value" => null, "is_null_allowed" => true, "depends_on" => array(), "target" => "_bl
Why not defined in datamodel xml so it can be modified/extended easily?

2023-12-19 14:40 UTC, steffunky commented on sources/Core/Notification/Action/ActioniTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeString("url", array("allowed_values" => null, "sql" => "url", "default_value" => null, "is_null_allowed" => true, "depends_on" => array(), "target" => "_bl
We might go this way, I was a bit hesitant because I had never added any XML to the core data model file :grin:

2023-12-19 15:01 UTC, Molkobain requested changes

2023-12-19 15:01 UTC, Molkobain commented on sources/Core/Notification/Action/ActioniTopNotification.php
> +			}
Surround this with a if to check if we have the `this->object()` argument.
Move the default `$this->url()$` value to the attribute definition and make it mandatory.

2023-12-19 15:05 UTC, Molkobain requested changes

2023-12-19 15:05 UTC, Molkobain commented on sources/Application/UI/Base/Component/PopoverMenu/NewsroomMenu/NewsroomMenuFactory.php
> +		$aProviders = utils::GetClassesForInterface('iNewsroomProvider', '', array('[\\\\/]lib[\\\\/]', '[\\\\/]node_modules[\\\\/]', '[\\\\/]test[\\\\/]', '[\\\\/]tests[\\\\/]'));
Refactor in `pages/preferences.php` L240 and L830 as well.
Create ticket to deprecate usage of MetaModel::EnumPlugins('iNewsroomProvider').
Update unit test.

2023-12-19 19:33 UTC, jbostoen commented
For this feature: a competing product makes a difference between "news" (announcing their updates etc) and "activity".

I definitely like the concept; but it might indeed be best to re-use the system and still have fast access to mere activities (rather than the news being in the same spot).

Although it could also lead to more people reading the news messages of course ;)

2023-12-20 09:10 UTC, Molkobain requested changes

2023-12-20 09:10 UTC, Molkobain commented on core/action.class.inc.php
> +	public function SetNotificationLanguage($sLanguage = null, $sLanguageCode = null){
Add PHPDoc (`@since` at least), type hinting

2023-12-20 09:10 UTC, Molkobain commented on core/action.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeApplicationLanguage("language", array("sql"=>"language", "default_value"=>null, "is_null_allowed"=>true, "depends_on"=>array())));
Data migration for current `ActionEmail` objects to do.
Where? TBD.

2023-12-20 09:10 UTC, Molkobain commented on core/config.class.inc.php
> +			'default' => true,
```suggestion
			'default' => 182,
```

2023-12-20 09:10 UTC, Molkobain commented on core/config.class.inc.php
> +			'default' => true,
```suggestion
			'default' => 5,
```

2023-12-20 09:11 UTC, steffunky commented on core/action.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeApplicationLanguage("language", array("sql"=>"language", "default_value"=>null, "is_null_allowed"=>true, "depends_on"=>array())));
Either itop-structure module installer or a new module installer for iTop core

2023-12-20 09:19 UTC, Molkobain commented on sources/Application/Newsroom/iTopNewsroomProvider.php
> +		return ITOP_APPLICATION_SHORT;
Maybe we should use a dictionary entry instead (which would be that constant) so people can customize it.

2023-12-20 09:23 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		if($iContactId !== '') {
```suggestion
		if (\utils::IsNotNullOrEmptyString($iContactId)) {
```

`null` can be returned as well

2023-12-20 09:41 UTC, Molkobain requested changes

2023-12-20 09:41 UTC, Molkobain commented on sources/Application/Newsroom/iTopNewsroomProvider.php
> +		return utils::GetAbsoluteUrlAppRoot().'pages/ajax.render.php?route=itopnewsroom.' . $sRouteCode;
Use `\Combodo\iTop\Service\Router\Router::GenerateUrl()` instead

2023-12-20 09:41 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +					'url' => utils::GetAbsoluteUrlAppRoot() . '/pages/UI.php?route=itopnewsroom.view_event&event_id='.$oMessage->GetKey(),
Use `\Combodo\iTop\Service\Router\Router::GenerateUrl()` instead

2023-12-20 09:41 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		if($iContactId !== '') {
```suggestion
		if (\utils::IsNotNullOrEmptyString($iContactId)) {
```

`null` can be returned as well

2023-12-20 09:41 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +			}
Testing if `$oEvent !== null` seems irrelevant as there will be an exception if not found.

Also, maybe we could change the test condition and throw a 404 if the contact is not the one it is supposed too. That would make it consistent with other similar use cases and put the main logic out of the if condition.

2023-12-20 09:41 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationGC.php
> +			$oDBObjectSearch = DBObjectSearch::FromOQL("SELECT EventiTopNotification WHERE read='yes' AND read_date < DATE_SUB(NOW(), INTERVAL :deletion_time DAY)", ['deletion_time' => $sDeletionTime]);
```suggestion
			$iDeletionTime = (int) MetaModel::GetConfig()->Get('notifications.itop.read_notification_retention');
			$oDBObjectSearch = DBObjectSearch::FromOQL("SELECT EventiTopNotification WHERE read='yes' AND read_date < DATE_SUB(NOW(), INTERVAL :deletion_time DAY)", ['deletion_time' => $iDeletionTime]);
```

So we know what we are manipulating.

2023-12-20 11:20 UTC, steffunky commented
> For this feature: a competing product makes a difference between "news" (announcing their updates etc) and "activity".
> 
> I definitely like the concept; but it might indeed be best to re-use the system and still have fast access to mere activities (rather than the news being in the same spot).
> 
> Although it could also lead to more people reading the news messages of course ;)

Currently, only iTop hub "news" are shipped with iTop; other providers, such as Molkobain and TeemIp, only display news for Administrators (also users of your news provider can customize who sees your news). Therefore, I believe that non-admin end users won't be bothered by "news" in their activity feed, if an Administrator is bothered by these news, they can still unsubscribe in their preference page; since fewer people see them, it's less of a nuisance.

But since there's a priority level in newsroom messages but it's not currently used we could make "activity" more visible or display firsts unless a news has a strong priority

2023-12-20 16:11 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationGC.php
> +class EventiTopNotificationGC implements iBackgroundProcess
We still need to consider the "advance background task" thing, as this could have a huge volume, especiqlly if it runs only once per day.

2023-12-20 16:12 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/application/applicationextension/ApplicationExtensionTest.php
> -			],
Don't remove it, just use `static::ENUM_API_CALL_METHOD_GETCLASSESFORINTERFACE,` as for `\iFieldRendererMappingsExtension::class`

2023-12-20 16:12 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/application/applicationextension/Delta/application-extension-usages-in-snippets.xml
Same comment as above

2023-12-21 09:41 UTC, Hipska commented on sources/Core/Notification/Action/ActioniTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeString("url", array("allowed_values" => null, "sql" => "url", "default_value" => '$this->url()$', "is_null_allowed" => false, "depends_on" => array(), "tar
Please have it in `datamodel.xml` to allow extending/modifying..

2023-12-21 09:42 UTC, Hipska commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
Please have it in `datamodel.xml` to allow extending/modifying..

2023-12-21 09:54 UTC, steffunky commented on sources/Core/Notification/Action/ActioniTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeString("url", array("allowed_values" => null, "sql" => "url", "default_value" => '$this->url()$', "is_null_allowed" => false, "depends_on" => array(), "tar
![image](https://github.com/Combodo/iTop/assets/5959857/7db71278-f82e-4b32-b55c-af246eb7c995)

2023-12-21 09:55 UTC, steffunky commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
![image](https://github.com/Combodo/iTop/assets/5959857/e7eb8009-ded3-4f74-bae5-d3513f6d4aef)

2023-12-21 10:01 UTC, Hipska commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
You're saying you will go this way, but aren't doing it? 🤷 😕 

Also, why not doing it because you never done it? It is the best way to do it for the classes in this case..

2023-12-21 14:17 UTC, steffunky commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
Yeah I prioritized fixing functional issues before focussing on extensibility moreover, there's no class declared in `datamodel.core.xml` yet, I need to be sure it works as modules datamodel before pushing it to this branch

2023-12-21 15:23 UTC, Hipska commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
Oh, okay. I thought you misunderstood me or I misunderstood you... As long as it will be defined as xml datamodel before it gets merged, we are all good!


Ps, if you are still working on it, then it is better to mark the PR as draft, to let reviewers know it's not finished yet..

2023-12-22 10:12 UTC, steffunky commented on sources/Core/Notification/Event/EventiTopNotification.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id",array("targetclass" => 'Contact', "allowed_values" => null, "sql" => "contact_id", "default_value" => null, "is_null_allowed" => f
@Hipska Your Christmas gift came a bit early [9459f26](https://github.com/Combodo/iTop/pull/590/commits/9459f26666b46b70a7b4c9c2d2674606e61301ec)

2023-12-22 10:52 UTC, Molkobain requested changes

2023-12-22 10:52 UTC, Molkobain commented on core/datamodel.core.xml
> +          <default_value>1</default_value>
```suggestion
          <default_value>4</default_value>
```

Did you mean "4"? Otherwise all messages will be critical by default

2023-12-22 10:52 UTC, Molkobain commented on core/datamodel.core.xml
> +          <default_value>1</default_value>
```suggestion
          <default_value>4</default_value>
```

Same comment

2023-12-22 10:52 UTC, Molkobain commented on core/datamodel.core.xml
> +		$oRecipientsSet = new DBObjectSet($oRecipientsSearch);
```suggestion
		$oRecipientsSearch = DBObjectSearch::FromOQL($this->Get('recipients'));
		$oRecipientsSearch->AllowAllDate();
		$oRecipientsSet = new DBObjectSet($oRecipientsSearch);
```

2023-12-22 11:00 UTC, Molkobain approved these changes

2023-12-22 11:00 UTC, Molkobain commented
Good job mv! 🙌

2023-12-22 11:02 UTC, merged

2023-12-22 11:06 UTC, Hipska requested changes

2023-12-22 11:06 UTC, Hipska commented on core/autoload.php
>  MetaModel::IncludeModule('core/trigger.class.inc.php');
These don't exist anymore

2023-12-22 11:06 UTC, Hipska commented on dictionaries/ui/application/newsroom/en.dictionary.itop.newsroom.php
> +));
Missing EOL

2023-12-22 11:06 UTC, Hipska commented on core/datamodel.core.xml
> +          </values>
Since iTop 3.1 there is no need to work with numerical values for an enum anymore.

2023-12-22 11:06 UTC, Hipska commented on core/datamodel.core.xml
> +          <default_value>1</default_value>
Value `4` is translated as `Standard`. Shouldn't default be that instead?

2023-12-22 11:06 UTC, Hipska commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:EventiTopNotification/Attribute:url+' => '',
Some additional info that it uses placeholders might be useful here

2023-12-22 11:06 UTC, Hipska commented on core/datamodel.core.xml
> +              public function DoExecute($oTrigger, $aContextArgs)
Method id is `ComputePriority` but the code has different name?

These methods can maybe still be defined in a specific php class/file? Might be easier than in the XML?

2023-12-22 11:06 UTC, Hipska commented on core/datamodel.core.xml
> +          <target_class>Contact</target_class>
Will it ever be anything else than `Person`?

2023-12-22 11:06 UTC, Hipska commented on core/datamodel.core.xml
> +        <parent>Action</parent>
Nice, how does this work so it does not conflict with the `ActionNotification` defined in PHP?

2023-12-22 11:06 UTC, Hipska commented on pages/preferences.php
> +	foreach($aProviders as $cProvider)
The old method looks a lot cleaner IMHO.

Also what does the c in `$cProvider` mean? Typo for `$sProvider`?

2023-12-22 11:06 UTC, Hipska commented on sources/Service/Notification/Event/EventiTopNotificationGC.php
> +}
Missing EOL

2023-12-22 11:06 UTC, Hipska commented on sources/Application/Newsroom/iTopNewsroomProvider.php
> +}
Missing EOL

2023-12-22 11:06 UTC, Hipska commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +}
Missing EOL

2023-12-22 11:06 UTC, Hipska commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +				$Message = $oMessage->Get('message');
```suggestion
				$sMessage = $oMessage->Get('message');
```

2023-12-22 11:06 UTC, Hipska commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +				$sIcon = $oMessage->Get('icon') !== null ?
```suggestion
				$sIcon = !is_null($oMessage->Get('icon')) ? 
```

2023-12-22 11:06 UTC, Hipska commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		echo $sOutput;
Shouldn't this be added to `$oPage` somehow?

2023-12-22 11:06 UTC, Hipska commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +					$oEvent->Set('read_date', time());
```suggestion
					$oEvent->SetCurrentDate('read_date');
```

2023-12-22 13:14 UTC, Molkobain commented on core/datamodel.core.xml
> +          <default_value>1</default_value>
Done in the meantime

2023-12-22 13:15 UTC, Molkobain commented on core/autoload.php
>  MetaModel::IncludeModule('core/trigger.class.inc.php');
Fixed in the meantime

2023-12-22 13:15 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +					$oEvent->Set('read_date', time());
Good point

2023-12-22 13:18 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		echo $sOutput;
Actually, I think we should have use a `JsonPPage` to avoid that and setting the content type manually

2023-12-26 08:58 UTC, steffunky commented on pages/preferences.php
> +	foreach($aProviders as $cProvider)
It's used in other parts of the code that call `utils::GetClassesForInterface` and stands for `class`, so it doesn't look weird when you instantiate it with `new $cProvider`

2023-12-26 09:01 UTC, steffunky commented on core/datamodel.core.xml
> +        <parent>Action</parent>
The `<meta>` tag is only read by the designer when querying for an attribute list for a class that has a `<php_parent>` attribute, as PHP classes aren't loaded in the Designer it helps define what attributes it will inherit

2023-12-26 09:16 UTC, steffunky commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		echo $sOutput;
I'll give it a try but I only copied what was done by other newsroom providers :grin:

2023-12-26 09:17 UTC, Hipska commented on core/datamodel.core.xml
> +        <parent>Action</parent>
Ooh, thanks, couldn't see this was inside `<meta>`.

2023-12-26 09:18 UTC, Hipska commented on pages/preferences.php
> +	foreach($aProviders as $cProvider)
Still looks that should have been `$sProvider` to me. "class" isn't a variable type in PHP.