N°7085 - login page infinite loop until fatal error
Combodo/iTop pull request #592
Opened 2023-12-21 17:33 UTC by odain-cbd

When iTop authentication is badly configured, login page can lead to a fatal error page.
![image](https://github.com/Combodo/iTop/assets/56586767/70c150d1-d3c9-491e-8775-b5c3c9bf624c)

Current PR avoids iTop to be trapped in an infinite loop. the application will answer immediately instead (white page).

To reproduce:
- configure a dummy login mode in iTop configuration
`'allowed_login_types' => 'form|external|dummy_login_mode|basic',`

- call iTop/pages/UI.php?login_mode=dummy_login_mode URL

2023-12-22 10:16 UTC, Molkobain requested changes

2023-12-22 10:16 UTC, Molkobain commented on core/config.class.inc.php
> +		}
```suggestion
		if (in_array($sLoginMode, $aAllowedLoginTypes)){
			return;
		}

		$aAllowedLoginTypes[] = $sLoginMode;
		$this->SetAllowedLoginTypes($aAllowedLoginTypes);
```

2023-12-22 10:16 UTC, Molkobain commented on application/logindefault.class.inc.php
> +			exit;
Would it be relevant to `exit(-1)` in case it happens when a CLI script tries to log on?

2023-12-22 10:58 UTC, odain-cbd commented on application/logindefault.class.inc.php
> +			exit;
good point

2023-12-22 13:06 UTC, Molkobain approved these changes

2023-12-22 14:28 UTC, eespie approved these changes

2024-01-02 09:58 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/application/LoginTest.php
> +		$this->sConfigPath = MetaModel::GetConfig()->GetLoadedFile();
Not needed: iTopTestCase::tearDownAfterClass already resets the configuration by reloading it from disk.

2024-01-02 10:03 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/application/LoginTest.php
> + * @backupGlobals disabled
@preserveGlobalState and @backupGlobals are not necessary anymore and should be removed

2024-01-02 11:02 UTC, rquetiez requested changes

2024-01-02 11:02 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/application/LoginTest.php
> + * @runTestsInSeparateProcesses
Is process isolation really a must?
If so, please explain (at least the symptom, which is the other test affected?)

2024-01-12 07:11 UTC, odain-cbd commented on tests/php-unit-tests/unitary-tests/application/LoginTest.php
> + * @runTestsInSeparateProcesses
it is not needed in fact. i will remove it

2024-01-12 07:13 UTC, merged