Dark night97boss patch 1
Combodo/iTop pull request #594
Opened 2023-12-23 16:31 UTC by DarkNight97boss

2024-01-02 14:00 UTC, Molkobain requested changes
Thanks for the PR and the huge amount of translations @DarkNight97boss !

Just 2 things to correct please:
- Revert changes to `datamodels/2.x/authent-cas/src/CASLogger.php` as it is not part of the translations and was already done in #593 
- For each dict entry translated in italian, please remove the trailing `~~`. These symbols are only there for un-translated entries to help translators find new entries.

2024-01-02 14:01 UTC, Molkobain commented on datamodels/2.x/authent-cas/dictionaries/it.dict.authent-cas.php
> +	'CAS:Login:SignInTooltip' => 'Clicca qui per autenticarti con il server CAS~~',
```suggestion
	'CAS:Error:UserNotAllowed' => 'Utente non autorizzato',
	'CAS:Login:SignIn' => 'Accedi con CAS',
	'CAS:Login:SignInTooltip' => 'Clicca qui per autenticarti con il server CAS',
```

Example of entries that should no longer have trailing `~~`

2024-01-02 14:16 UTC, DarkNight97boss commented
> Thanks for the PR and the huge amount of translations @DarkNight97boss !
> 
> Just 2 things to correct please:
> 
> * Revert changes to `datamodels/2.x/authent-cas/src/CASLogger.php` as it is not part of the translations and was already done in [🐛  Fixing error during setup #593](https://github.com/Combodo/iTop/pull/593)
> * For each dict entry translated in italian, please remove the trailing `~~`. These symbols are only there for un-translated entries to help translators find new entries.

Done!

can you remove unnecessary trailing yourself? if not, I can do it for you! but i need some days

2024-01-02 15:11 UTC, Molkobain commented
It would be best if you could do it yourself, thanks. No hurry though, don't worry :)

2024-02-06 10:05 UTC, Molkobain requested changes

2024-02-06 10:05 UTC, Molkobain commented on datamodels/2.x/authent-ldap/dictionaries/it.dict.authent-ldap.php
> +	'UserLDAP:server' => 'Specifiche LDAP~~',
```suggestion
	'UserLDAP:server' => 'Specifiche LDAP',
```

2024-02-06 10:05 UTC, Molkobain commented on datamodels/2.x/authent-local/dictionaries/it.dict.authent-local.php
> +	'Class:UserLocal/Error:OneTimePasswordChangeIsNotAllowed' => 'Impostare la scadenza della password su "Password monouso" non è consentito per il proprio utente~~',
```suggestion
	'Class:UserLocal/Attribute:expiration' => 'Scadenza della password',
	'Class:UserLocal/Attribute:expiration+' => 'Stato della scadenza della password (richiede un\'estensione per avere effetto)',
	'Class:UserLocal/Attribute:expiration/Value:can_expire' => 'Può scadere',
	'Class:UserLocal/Attribute:expiration/Value:never_expire' => 'Non scade',
	'Class:UserLocal/Attribute:expiration/Value:force_expire' => 'Scaduta',
	'Class:UserLocal/Attribute:expiration/Value:otp_expire' => 'Password monouso',
	'Class:UserLocal/Attribute:expiration/Value:otp_expire+' => 'La password non può essere cambiata dall\'utente.',
	'Class:UserLocal/Attribute:password_renewed_date' => 'Rinnovo della password',
	'Class:UserLocal/Attribute:password_renewed_date+' => 'Quando è stata cambiata l\'ultima volta la password',
	'Error:UserLocalPasswordValidator:UserPasswordPolicyRegex:ValidationFailed' => 'La password deve essere di almeno 8 caratteri e includere lettere maiuscole, minuscole, numeri e caratteri speciali.',
	'UserLocal:password:expiration' => 'I campi sottostanti richiedono un\'estensione',
	'Class:UserLocal/Error:OneTimePasswordChangeIsNotAllowed' => 'Impostare la scadenza della password su "Password monouso" non è consentito per il proprio utente',
```

2024-02-06 15:08 UTC, Molkobain commented
Technical review:
  * Dict entries must be clean to remove trailing `~~`
  * Guillaume will handle the cleaning and rebase the branch
  * Then we can move the PR to functional review

2024-02-07 14:58 UTC, Molkobain approved these changes

2024-02-08 10:12 UTC, Molkobain commented
Why did you merge develop in this branch @DarkNight97boss ? It did a big mess.
Don't touch the PR branch, I'll fix it. BTW we fixed the remaining issues yesterday.

2024-02-08 10:12 UTC, Molkobain requested changes
Need to revert last merge from develop branch

2024-02-13 16:21 UTC, Molkobain commented
Accepted during functional review. I'll fix the branch and merge in the coming days.

2024-02-14 11:30 UTC, DarkNight97boss commented
> Accepted during functional review. I'll fix the branch and merge in the coming days.

Great! sounds good... about data sync issue?

2024-02-14 13:37 UTC, Molkobain commented
I'll handle it, don't worry :)

2024-02-14 13:39 UTC, Molkobain approved these changes

2024-02-14 13:47 UTC, Molkobain commented
@DarkNight97boss can you send me your full name and postal address to guillaume.lajarige @ combodo.com please? We would like to send you [thankful stickers](https://github.com/Combodo/iTop/blob/develop/.doc/contributing-guide/2023.contributing-stickers-side-by-side.png) for your contributions :)

2024-02-14 15:57 UTC, merged