Some Chinese Translation:ActioniTopNotification & EventiTopNotification
Combodo/iTop pull request #595
Opened 2023-12-25 07:52 UTC by chileeb

As following picture shows:
<img width="1411" alt="image" src="https://github.com/Combodo/iTop/assets/13185930/d3d8c388-7c67-476b-ab99-7fb5ad225995">
<img width="1411" alt="image" src="https://github.com/Combodo/iTop/assets/13185930/fbc2d374-4928-4841-8950-1aa80b524fb4">

2023-12-25 07:53 UTC, chileeb commented
@annProg @bdejin Please Review.

2023-12-26 01:54 UTC, annProg commented
对比 ActionEmail 翻译成 邮件通知，Action应该不需要直译。ActioniTopNotification 字面意思大概是iTop通知，可能类似于站内信概念

2023-12-26 02:50 UTC, chileeb commented
> 对比 ActionEmail 翻译成 邮件通知，Action应该不需要直译。ActioniTopNotification 字面意思大概是iTop通知，可能类似于站内信概念

好主意。

2024-01-02 15:17 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'ActioniTopNotification:settings' => 'ActioniTopNotification:settings',
@steffunky these were missing from the original commit or are they elsewhere?

2024-01-02 15:18 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:EventiTopNotification/Attribute:priority/Value:1+' => 'Critical',
This is not translated, is it on purpose?

2024-01-02 15:18 UTC, Molkobain requested changes

2024-01-02 15:18 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:ActioniTopNotification' => 'iTop通知',
```suggestion
	'Class:ActioniTopNotification' => ITOP_APPLICATION_SHORT.'通知',
```

2024-01-03 10:53 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'ActioniTopNotification:settings' => 'ActioniTopNotification:settings',
```suggestion
	'ActioniTopNotification:content' => 'Content',
	'ActioniTopNotification:settings' => 'Settings',
```

2024-01-03 20:53 UTC, Molkobain approved these changes

2024-01-03 20:55 UTC, Molkobain commented
All good for me! Is it all good for you as well @chileeb @annProg @bdejin ?

2024-01-05 04:50 UTC, chileeb commented
> All good for me! Is it all good for you as well @chileeb @annProg @bdejin ?

That's good!

2024-01-09 15:18 UTC, Molkobain commented
Accepted during functional review. Just keep in mind that the newsroom feature is not finished and dict entries may change.

2024-01-09 15:58 UTC, merged