N°4368 Fix CORB blocking regression
Combodo/iTop pull request #598
Opened 2024-01-04 10:12 UTC by piRGoif

We added the X-Content-Type-Options HTTP header, in consequence CORB blocking may now occurs. 
With those modifications : 
- sending the header is disabled for certain WebPage impl
- a new `security_header_xcontent_type_options` config parameter can be used to disabled header sending

2024-01-04 16:26 UTC, Molkobain requested changes

2024-01-04 16:26 UTC, Molkobain commented on application/ajaxwebpage.class.inc.php
> +	 * @return void
Maybe add an `@since` with the ticket number so we can trace it meaning back,

2024-01-04 16:26 UTC, Molkobain commented on core/config.class.inc.php
> +			'default' => 'true',
```suggestion
		'security.enable_header_xcontent_type_options' => [
			'type' => 'bool',
			'description' => 'If set to false, iTop will stop sending the X-Content-Type-Options HTTP header.',
			'default' => true,
```

- Namespace the conf. param. like for all new params.
- Fix default value to bool instead of string.
- Maybe we could explain in the description for which reasons it could be good to switch it to false?

2024-01-04 16:26 UTC, Molkobain commented on application/webpage.class.inc.php
> +			$bSendXContentTypeOptionsHttpHeader = $oConfig->Get('security_header_xcontent_type_options');
```suggestion
			$bSendXContentTypeOptionsHttpHeader = $oConfig->Get('security.enable_header_xcontent_type_options');
```

See comment below

2024-01-04 16:26 UTC, Molkobain commented on application/webpage.class.inc.php
> +	 * Sending header can be disabled globally using the `security_header_xcontent_type_options` optional config parameter.
```suggestion
	 * Warning: this header will trigger the Cross-Origin Read Blocking (CORB) protection for some mime types (HTML, XML except SVG, JSON, text/plain)
	 * In consequence some children pages will override this method.
	 *
	 * Sending header can be disabled globally using the `security.enable_header_xcontent_type_options` optional config parameter.
```

See comment below

2024-01-04 16:26 UTC, Molkobain commented on application/xmlpage.class.inc.php
> +	 * @return void
Maybe add an `@since` with the ticket number so we can trace it meaning back,

2024-01-05 09:14 UTC, piRGoif commented on core/config.class.inc.php
> +			'default' => 'true',
Argll good catch for the default value :(
I changed also the description
Done in 5a1dd9ff

We'll have a chat on renaming

2024-01-05 09:14 UTC, piRGoif commented on application/ajaxwebpage.class.inc.php
> +	 * @return void
Done in 5a1dd9ff

2024-01-05 09:14 UTC, piRGoif commented on application/xmlpage.class.inc.php
> +	 * @return void
Done in 5a1dd9ff

2024-01-05 09:29 UTC, piRGoif commented on core/config.class.inc.php
> +			'default' => 'true',
Renaming done in c630a3f1

2024-01-05 09:29 UTC, piRGoif commented on application/webpage.class.inc.php
> +			$bSendXContentTypeOptionsHttpHeader = $oConfig->Get('security_header_xcontent_type_options');
Done in c630a3f1

2024-01-05 09:29 UTC, piRGoif commented on application/webpage.class.inc.php
> +	 * Sending header can be disabled globally using the `security_header_xcontent_type_options` optional config parameter.
Done in c630a3f1

2024-01-05 09:37 UTC, piRGoif commented on core/config.class.inc.php
> +			'default' => 'true',
Woops renamed done in da941fca actually (missed the enable prefix)

2024-01-05 09:39 UTC, Molkobain approved these changes

2024-01-05 09:41 UTC, merged