N°4164 - Portal: Hide log off button when user can't actually log off (eg. SSO using SAML or other providers)
Combodo/iTop pull request #599
Opened 2024-01-05 10:16 UTC by Molkobain

**Symptom**
For some users using SSO (eg. SAML), they can't log off through iTop as it will show them an error page.

**Proposed solution**
Do exactly as in the backoffice, only show the "log off" button is the user can actually log off, which is based on a session variable that can be retrieved through `\utils::CanLogOff()`

_**Important:** Careful when merging in support/3.1 branch as the `UserProvider` part changed a lot when migrating to Symfony 5.4_

_Desktop_
![image](https://github.com/Combodo/iTop/assets/5130468/e64b708d-6826-42db-8151-192c5aded11e)

_Mobile_
![image](https://github.com/Combodo/iTop/assets/5130468/aa84c99d-e443-427b-9d58-f0ce1678f179)

2024-01-08 08:00 UTC, bdalsass approved these changes

2024-01-09 08:49 UTC, Hipska requested changes

2024-01-09 08:49 UTC, Hipska commented on datamodels/2.x/itop-portal-base/portal/src/EventListener/UserProvider.php
> +        $this->oContainer->set('combodo.current_user.can_logff', utils::CanLogOff());
```suggestion
        $this->oContainer->set('combodo.current_user.can_logoff', utils::CanLogOff());
```

2024-01-09 08:49 UTC, Hipska commented on datamodels/2.x/itop-portal-base/portal/templates/layout.html.twig
> +    {% set bUserCanLogOff = app['combodo.current_user.can_logff'] %}
```suggestion
    {% set bUserCanLogOff = app['combodo.current_user.can_logoff'] %}
```

2024-01-09 08:58 UTC, Molkobain commented on datamodels/2.x/itop-portal-base/portal/src/EventListener/UserProvider.php
> +        $this->oContainer->set('combodo.current_user.can_logff', utils::CanLogOff());
Good catch, thanks!

2024-01-09 09:05 UTC, Hipska approved these changes

2024-02-06 15:41 UTC, Molkobain commented
Accepted during technical review

2024-03-11 20:13 UTC, merged