fix(compiler): Provide empty string instead of null value
Combodo/iTop pull request #600
Opened 2024-01-08 12:33 UTC by Hipska

The methods `FilterDictString` and `FilterDictString` both use `strpos` or `str_replace` who give a deprecation notice when the argument is `null`:

```
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/setup/compiler.class.inc.php on line 3231
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/setup/compiler.class.inc.php on line 1146
```

This message is repeated for each empty dictionary item, which seems to happen on a Professional instance connected to the Designer.

Logs taken from a iTop Professional 3.1.0-3. The null argument gives a deprecation notice since [PHP 8.1](https://3v4l.org/W5mRs), which is supported for this iTop version.

2024-01-10 16:39 UTC, piRGoif commented
Hello Thomas,
Can you provide some sample dict keys to reproduce the issue ?

2024-01-11 09:15 UTC, Hipska commented
I guess it is just `<entry id="dict:code"/>`.

2024-02-02 08:26 UTC, Hipska commented
Other PHP 8.1 findings:

```
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/core/ormcaselog.class.inc.php on line 172
Deprecated: md5(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/core/ormdocument.class.inc.php on line 346
```

2024-02-02 15:21 UTC, piRGoif commented
Hello,
Thanks for the 2 other deprecated notices on PHP 8.1, I've created N°7212
Can you detail how to reproduce them, especially the one on ormDocument ?

2024-02-02 15:24 UTC, Hipska commented
Already discussed with @Molkobain on Slack.

Displaying a Person on the portal (e.g. click on manager on profile page) causes the `ormDocument` notice.

The other one was when going to a User's details page (might be related to having the activity panel open)

2024-02-02 16:07 UTC, piRGoif commented
ormCaselog error is handled in #607

2024-03-06 14:05 UTC, Hipska commented
Having this issue as well with 3.1.1:

```
Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/setup/compiler.class.inc.php on line 3264
Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/setup/compiler.class.inc.php on line 1170
```

2024-03-06 16:50 UTC, Hipska commented
Even replacing this line with the following isn't a suitable workaround:
```xml
<entry id="Class:Display/Attribute:type_id+" _delta="define"></entry>
```

Looks like there is no way anymore to define an empty dict in xml !!!

2024-03-07 09:39 UTC, piRGoif commented
Woops absolutely sorry I forgot this PR :(
I've just tried to reproduce on a standard support/3.1 clone, and I got it ! 
I'll rewrite the description a little, and send the PR back for review.

2024-03-07 09:44 UTC, piRGoif commented
@Molkobain will be the new assignee for the reviews next month.

2024-03-07 16:11 UTC, Molkobain requested changes
Technical review: We would rather fix the root cause than the symptom:
  * `FilterDictString()`
    * Method type hinting can be enforce as it is only used within the compiler: `FilterDictString(string $s): string`
    * Fix te one usage in the line below your proposal: `self::FilterDictString($sValue ?? '')`
  * `QuoteForPHP()`
    * As it is used in many places, fix its internal usages with `$s = $s ?? '';` at the begining of the method.

2024-05-06 14:29 UTC, Molkobain requested changes

2024-05-06 14:29 UTC, Molkobain commented on setup/compiler.class.inc.php
>  				$aEntriesPHP[] = "\t'$sStringCode' => ".self::QuoteForPHP(self::FilterDictString($sValue), true).",";
```suggestion
				$sValue = $oEntry->GetText();
				$aEntriesPHP[] = "\t'$sStringCode' => ".self::QuoteForPHP(self::FilterDictString($sValue ?? ''), true).",";
```

See last comment in the conversation

2024-05-06 14:33 UTC, Hipska commented on setup/compiler.class.inc.php
>  				$aEntriesPHP[] = "\t'$sStringCode' => ".self::QuoteForPHP(self::FilterDictString($sValue), true).",";
Hmm, I thought "We would rather fix the root cause than the symptom" would mean you wanted the root cause fixed instead of adding a workaround?

2024-05-06 16:07 UTC, Molkobain commented on setup/compiler.class.inc.php
>  				$aEntriesPHP[] = "\t'$sStringCode' => ".self::QuoteForPHP(self::FilterDictString($sValue), true).",";
Yes, what we meant by that is that the `FilterDictString` should be stricter to avoid this symptom. But I overlooked your proposition, it's actually ok. Thanks.

2024-05-06 16:07 UTC, Molkobain approved these changes

2024-07-10 06:59 UTC, Molkobain commented
Functional review: Accepted.

2024-07-10 08:07 UTC, merged