N°7194 - Datamodel - Make classe name clickable on every object.
Combodo/iTop pull request #613
Opened 2024-02-13 09:37 UTC by accognet

When the cursor is over the class name, its color and the cursor indicate that it is a link
![image](https://github.com/Combodo/iTop/assets/57360138/a74f8b67-eb91-41f3-aa8b-14b8c0770fb6)
clicking on the class name opens the current class schema screen in a new tab

2024-02-13 10:03 UTC, Hipska commented
What about permissions? Is every user able to open the schema page?

2024-02-27 15:43 UTC, piRGoif requested changes

2024-02-27 15:43 UTC, piRGoif commented on sources/Application/UI/Base/Layout/Object/ObjectDetails.php
> +use GuzzleHttp\Utils;
I didn't find the usage, is it necessary ?

2024-02-27 15:54 UTC, accognet commented on sources/Application/UI/Base/Layout/Object/ObjectDetails.php
> +use GuzzleHttp\Utils;
No, I'll delete it. It's an automatic addition made by PHP Storm...

2024-02-27 16:27 UTC, piRGoif approved these changes

2024-03-25 19:18 UTC, Molkobain commented on css/backoffice/layout/object/_object-details.scss
> +  display: inline-flex;
```suggestion
  display: inline-flex; /* To avoid having spaces around the class name due to the indentation */
```

2024-03-25 19:22 UTC, Molkobain requested changes

2024-03-25 19:22 UTC, Molkobain commented on dictionaries/en.dictionary.itop.ui.php
> +	'UI:Details:LinkToClassDatamodelSchema' => 'Link to %1$s class data model schema',
All new dict entries must be placed in `dictionaries/ui/layouts/object-details/en.dictionary.itop.object-details.php` (`'UI:Layout:ObjectDetails:DatamodelSchemaLink:Tooltip'`)

2024-03-25 19:22 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.ui.php
> +	'UI:Details:LinkToClassDatamodelSchema' => 'Lien vers le modèle de données de la classe %1$s.',
Same comment as above

2024-03-25 19:22 UTC, Molkobain commented on sources/Application/TwigBase/Twig/Extension.php
> +		// Usage in twig: {% if is_backoffice_menu_enabled(''DataModelMenu) %}
```suggestion
		// Usage in twig: {% if is_backoffice_menu_enabled('DataModelMenu') %}
```

Typo

2024-03-26 07:48 UTC, Hipska commented
@accognet? https://github.com/Combodo/iTop/pull/613#issuecomment-1941023398

2024-03-26 08:04 UTC, accognet commented
> What about permissions? Is every user able to open the schema page?

Only users who can see data model menu have this link

2024-03-26 08:31 UTC, Hipska approved these changes

2024-03-26 08:31 UTC, Hipska commented on dictionaries/ui/layouts/object-details/nl.dictionary.itop.object-details.php
> +	'UI:Layout:ObjectDetails:DatamodelSchemaLink:Tooltip' => 'Class data model schema~~',
```suggestion
	'UI:Layout:ObjectDetails:DatamodelSchemaLink:Tooltip' => 'Objecten schema van deze klasse',
```

2024-03-26 09:31 UTC, Molkobain approved these changes

2024-03-26 09:32 UTC, Molkobain commented
Ok for me. You need to rebase your branch first as there are some conflicts. Then you can squash & merge.

2024-03-26 10:35 UTC, merged