N°7243 - Add toast notifications to iTop
Combodo/iTop pull request #614
Opened 2024-02-14 09:48 UTC by steffunky

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | 
| Type of change?                                               | Bug fix / Enhancement / Translations

## Symptom (bug) / Objective (enhancement)
The objective of this enhancement is to implement toast notifications within iTop. This feature will provide users with non-intrusive notifications for various system events or user actions. Toast notifications will improve the user experience by providing timely updates without interrupting their workflow.

![ezgif-6-0b9be9fa65](https://github.com/Combodo/iTop/assets/5959857/247dd032-40d8-46cd-a624-2bf2b7e519ee)

## Proposed solution (bug and enhancement)
This solution uses Toastify library and implements a JS API similar to iTop 3.1's modal API available in the backoffice and the portal. It also let the end-user choose in its preferences if he'd rather want to see them at the top or at the bottom.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested all changes I made on an iTop instance
- [x] Would a unit test be relevant and have I added it? Nay
- [x] Is the PR clear and detailled enough so anyone can understand digging in the code?

2024-02-14 13:47 UTC, Hipska approved these changes

2024-02-15 13:52 UTC, Molkobain requested changes

2024-02-15 13:52 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--padding-left: 18px !default;
Can't we use our spacing variables?

2024-02-15 13:52 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--close--background: transparent !default;
```suggestion
$ibo-vendors-toastify--close--background-color: transparent !default; 
```

2024-02-15 13:52 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +  background: $ibo-vendors-toastify--close--background;
```suggestion
  background-color: $ibo-vendors-toastify--close--background-color;
```

2024-02-15 13:52 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +}
I think this should rather be in a dedicated partial (and variables) with other components.

2024-02-15 13:52 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +  max-width: -moz-fit-content;
If the second is really necessary, then maybe it should also be on the rule below?

2024-02-15 13:52 UTC, Molkobain commented on js/utils.js
> +let CombodoToast= {
```suggestion
let CombodoToast = {
```

2024-02-15 13:52 UTC, Molkobain commented on js/utils.js
> +		// Meant for overlaoding
```suggestion
		// Meant for overloading
```

2024-02-15 13:52 UTC, Molkobain commented on node_modules/toastify-js/example/pattern.png
We should not version this kind of file. Check if we can make a cleanup script after install like for composer packages

2024-02-15 13:52 UTC, Molkobain commented on pages/preferences.php
> +	$oMiscOptionsFieldset->AddSubBlock(GetToastPositionFieldBlock());
```suggestion
	$oMiscOptionsFieldset->AddSubBlock(GetToastsPositionFieldBlock());
```

2024-02-15 13:52 UTC, Molkobain commented on pages/preferences.php
> +	$oSelect->AddSubBlock(SelectOptionUIBlockFactory::MakeForSelectOption("top", Dict::S('UI:Preferences:General:Toast:Top'), $sPosition === "top"));
```suggestion
function GetToastsPositionFieldBlock(): iUIBlock
{
	$sPosition = appUserPreferences::GetPref('toasts_vertical_position', "bottom");

	$oSelect = SelectUIBlockFactory::MakeForSelectWithLabel('toasts_vertical_position', Dict::S('UI:Preferences:General:Toasts'));
	
	$oSelect->AddSubBlock(SelectOptionUIBlockFactory::MakeForSelectOption("bottom", Dict::S('UI:Preferences:General:Toasts:Bottom'), $sPosition === "bottom"));
	$oSelect->AddSubBlock(SelectOptionUIBlockFactory::MakeForSelectOption("top", Dict::S('UI:Preferences:General:Toasts:Top'), $sPosition === "top"));
```

2024-02-15 13:52 UTC, Molkobain commented on pages/preferences.php
> +					appUserPreferences::SetPref('toast_vertical_position', $sToastVerticalPosition);
```suggestion
				// - Toast notifications
				$sToastsVerticalPosition = utils::ReadParam('toasts_vertical_position', "bottom");
				if(utils::IsNotNullOrEmptyString($sToastsVerticalPosition) && in_array($sToastsVerticalPosition, ["bottom", "top"], true)) {
					appUserPreferences::SetPref('toasts_vertical_position', $sToastsVerticalPosition);
```

2024-02-15 13:52 UTC, Molkobain commented on sources/Application/WebPage/iTopWebPage.php
> +		// Toast
```suggestion
		// Toasts
```

2024-02-15 13:52 UTC, Molkobain commented on dictionaries/ui/pages/preferences/en.dictionary.itop.preferences.php
> +	'UI:Preferences:General:Toast:Top'                                 => 'Top',
```suggestion
	'UI:Preferences:General:Toasts'                                     => 'Toast notifications position',
	'UI:Preferences:General:Toasts:Bottom'                              => 'Bottom',
	'UI:Preferences:General:Toasts:Top'                                 => 'Top',
```

2024-02-15 14:09 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--padding-left: 18px !default;
You're right

2024-02-15 14:11 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--close--background: transparent !default;
This `background` rule comes from Toastify CSS file, I only put a variable in case anyone wants to overload it

2024-02-15 14:12 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +  background: $ibo-vendors-toastify--close--background;
This `background` rule comes from Toastify CSS file, I only put a variable in case anyone wants to overload it, I'm not sure we should modify it if it's only to precise it's a color

2024-02-15 14:13 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +  max-width: -moz-fit-content;
It comes from Toastify CSS file, I'm not sure we should modify it

2024-02-15 14:16 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--close--background: transparent !default;
Alright then 👍

2024-02-15 14:17 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +  background: $ibo-vendors-toastify--close--background;
Alright then 👍

2024-02-15 14:17 UTC, Molkobain commented on css/backoffice/vendors/_toastify.scss
> +  max-width: -moz-fit-content;
Alright then 👍

2024-02-15 14:18 UTC, Molkobain commented on js/pages/backoffice/toolbox.js
> +		gravity: GetUserPreference('toast_vertical_position', 'bottom'),
```suggestion
		gravity: GetUserPreference('toasts_vertical_position', 'bottom'),
```

2024-02-16 09:49 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +$ibo-vendors-toastify--padding-left: 18px !default;
Done in [9f0a978](https://github.com/Combodo/iTop/pull/614/commits/9f0a9785c99bf42aa28239b0029de298339edfcf)

2024-02-16 09:49 UTC, steffunky commented on css/backoffice/vendors/_toastify.scss
> +}
Done in [9f0a978](https://github.com/Combodo/iTop/pull/614/commits/9f0a9785c99bf42aa28239b0029de298339edfcf)

2024-02-16 09:57 UTC, Molkobain approved these changes

2024-02-16 09:58 UTC, Molkobain commented
You can merge, I'll handle the NPM post install cleanup script in a separate ticket.

2024-02-16 09:59 UTC, merged