N°7163 - "No results" displayed when having 0 as "items per page"
Combodo/iTop pull request #616
Opened 2024-02-15 10:26 UTC by accognet

New protections.
If the "items per page" value is not correct, it reverts to the default value

2024-02-15 12:44 UTC, Hipska approved these changes

2024-02-15 12:52 UTC, Molkobain commented on js/dataTables.settings.js
> +					if (isNaN(iPageSize) || iPageSize <= 0) {
```suggestion
					// Fallback to default page size in case of invalid number
					if (isNaN(iPageSize) || iPageSize <= 0) {
```

2024-02-15 12:53 UTC, Molkobain approved these changes

2024-02-15 12:56 UTC, Molkobain requested changes
We should also protect the "configure this list" input so we can't pass invalid value. To do so, just change the input type from `type="text"` to `type="number"` and add a `min="1"` attribute to avoid setting 0 and below.

Protection / fallback as already implemented by the PR remain mandatory though, as users can have an invalid value in their preferences.

2024-02-26 10:10 UTC, Hipska approved these changes

2024-02-26 10:11 UTC, Hipska commented
0 could be interpreted as "no limit"?

2024-02-26 12:45 UTC, Molkobain requested changes

2024-02-26 12:45 UTC, Molkobain commented on css/backoffice/components/datatable/_datatableconfig.scss
> +  border: 1px solid $ibo-color-grey-500;
```suggestion
  border: 1px solid $ibo-input--border-color;
```

Try to use this instead. I think partials dependencies will be ok.

2024-02-26 13:18 UTC, accognet commented on css/backoffice/components/datatable/_datatableconfig.scss
> +  border: 1px solid $ibo-color-grey-500;
with a slightly different patch, I have this display
![image](https://github.com/Combodo/iTop/assets/57360138/0cd70ccf-1024-49c6-86f8-fdb53a79c7bc)

2024-02-27 14:02 UTC, Molkobain requested changes

2024-02-27 14:02 UTC, Molkobain commented on css/backoffice/components/datatable/_datatableconfig.scss
> +  display: unset;
```suggestion
  display: initial;
```

We usually put `initial` instead to restore the default behavior.

2024-02-27 14:02 UTC, Molkobain commented on css/backoffice/components/datatable/_datatableconfig.scss
> +  display: unset;
Once this is fixed, you can:
- Rebase on support/3.2
- Change target branch to support/3.2
- Sqaush and merge (mind to keep the PR number)

2024-02-27 16:34 UTC, merged