N°2039 - Rework view all notifications page
Combodo/iTop pull request #617
Opened 2024-02-16 10:36 UTC by steffunky

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N°2039
| Type of change?                                               | Enhancement

## Objective (enhancement)
Rework of the view all notifications page added with #590

## Proposed solution (bug and enhancement)
Specifications made by @v-dumas and @Molkobain:

Displaying all news limited to those of the current user without being able to remove this filter criterion.

We start with a simple page. Being able to mark a notification as (un)read for one's own management of ongoing tasks (in bulk or individually). Being able to delete a notification (in bulk or individually). Sorting notifications by unread/read, then by descending dates. There will be no criteria on the page, just the actions to mark as read/delete/go to the notification url.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have tested all changes I made on an iTop instance
- [x] Would a unit test be relevant and have I added it?
- [x] Is the PR clear and detailled enough so anyone can understand digging in the code?

2024-02-16 12:00 UTC, Hipska commented
> [x] Would a unit test be relevant and have I added it?

Where is the test? Just untick if you didn’t add it. Please don’t lie.

2024-02-16 13:30 UTC, steffunky commented
> > [x] Would a unit test be relevant and have I added it?
> 
> Where is the test? Just untick if you didn’t add it. Please don’t lie.

It's not relevant in this case. I ticked it so the pull request doesn't appear unfinished as Github considers checkboxes as tasks.
![image](https://github.com/Combodo/iTop/assets/5959857/7ce0192d-611e-4805-8530-53d76ee04165)
 
 Also, I use PR so it's easier for us to review big commits on multiple files, I could just push it right away to the main branch otherwise

2024-02-16 14:05 UTC, Molkobain commented
The meaning of this checkbox is actually to force the PR's author to think about a unit test.
- If one would be relevant, the checkbox should not be checked until it's added
- If one isn't relevant, than the checkbox can be checked as well as it's not waiting for one

The idea is to complete the checklist and think about adding a test if relevant to the PR.
If that is more clear, maybe we could rephrase it? If you have a proposition, feel free to share it here :)

2024-02-16 14:18 UTC, Molkobain commented on css/backoffice/pages/_notifications.scss
> +}
Nicely done

2024-02-16 14:33 UTC, Molkobain approved these changes

2024-02-16 16:02 UTC, Hipska commented
> If that is more clear, maybe we could rephrase it? If you have a proposition, feel free to share it here

Yes, rephrasing is needed. I think the one [here](https://github.com/Combodo/itop-data-collector-base/blob/master/.github/pull_request_template.md) is already a bit better.

2024-02-19 09:03 UTC, Molkobain commented
Indeed, it was supposed to be on the template, but I forgot to update the one for this repo. It's now done!

2024-02-22 16:55 UTC, Molkobain commented on dictionaries/ui/application/newsroom/fr.dictionary.itop.newsroom.php
> +	'UI:Newsroom:iTopNotification:SelectMode:Label' => 'Mode de sélection',
It feels a bit weird to see this next to a toggle button doesn't it? You activate something, but the "mode" isn't explicit.
I mean, would "Sélection multiple" be better in opinion?

2024-02-22 17:12 UTC, steffunky commented on dictionaries/ui/application/newsroom/fr.dictionary.itop.newsroom.php
> +	'UI:Newsroom:iTopNotification:SelectMode:Label' => 'Mode de sélection',
Yea

2024-02-22 17:47 UTC, Molkobain requested changes

2024-02-22 17:47 UTC, Molkobain commented on dictionaries/ui/application/newsroom/fr.dictionary.itop.newsroom.php
> +	'UI:Newsroom:iTopNotification:ViewAllPage:Action:DeleteSelected:Label' =>  'Supprimer sélectionné',
```suggestion
	'UI:Newsroom:iTopNotification:ViewAllPage:Action:MarkSelectedAsRead:Label' => 'Marquer sélectionnée(s) comme lu',
	'UI:Newsroom:iTopNotification:ViewAllPage:Action:MarkSelectedAsUnread:Label' => 'Marquer sélectionnée(s) comme non lu',
	'UI:Newsroom:iTopNotification:ViewAllPage:Action:DeleteSelected:Label' =>  'Supprimer sélectionnée(s)',
```

2024-02-22 17:47 UTC, Molkobain commented on js/pages/backoffice/itop-newsroom.view-all.js
> +$('body').on('itop.notification.unread', '.ibo-notifications--view-all--container', fReadUnreadDisabled);
```suggestion
$('body').on('itop.notification.read itop.notification.unread', '.ibo-notifications--view-all--container', fReadUnreadDisabled);

$('body').on('itop.notification.unread', '.ibo-notifications--view-all--container', fReadUnreadDisabled);
```

This might be simplified to this, see example at the end of [this page](https://api.jquery.com/on/).

2024-02-22 17:47 UTC, Molkobain commented on sources/Application/UI/Base/Component/Input/InputUIBlockFactory.php
> +	public static function MakeInputWithLabel(string $sName, string $sLabel, Input $oInput, ?string $sId = null)
Add in the PHPDoc that the visibility changed from private to public since 3.2.0 please

2024-02-22 17:47 UTC, Molkobain commented on sources/Application/UI/Base/Component/Input/InputWithLabel.php
Why did you need to add that? It doesn't seem used.

2024-02-22 17:47 UTC, Molkobain commented on sources/Application/UI/Base/Component/Input/Toggler.php
> + * @package Combodo\iTop\Application\UI\Base\Component\Input
```suggestion
 * @package Combodo\iTop\Application\UI\Base\Component\Input
 * @since 3.2.0
```

2024-02-22 17:47 UTC, Molkobain commented on sources/Application/UI/Base/Component/Input/Toggler.php
> +	public function SetIsToggled($bIsToggled)
```suggestion
	public function SetIsToggled(bool $bIsToggled): static
```

2024-02-22 17:47 UTC, Molkobain commented on sources/Application/UI/Base/Component/Input/Toggler.php
> +	public function IsToggled()
```suggestion
	public function IsToggled(): bool
```

2024-02-22 17:47 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +	public function OperationMarkAsUnread(): JsonPage
Please factorize code of these operations (mark as read, mark as unread, delete), 90% of the code is the same. Seems like it has been generated by AI.

![image](https://github.com/Combodo/iTop/assets/5130468/3cdc1d09-4603-4b86-8e20-e36fc64b258a)

![image](https://github.com/Combodo/iTop/assets/5130468/d5a01c03-4436-48d2-b748-a7c8441eca83)

2024-02-22 17:47 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +	public function OperationMarkMultipleAsUnread(): JsonPage {
Same comment for the 3 "multiple" methods

![image](https://github.com/Combodo/iTop/assets/5130468/aa518ce1-ea22-4fb3-a728-88250947d1da)

2024-02-22 17:47 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
> +		$sCSRFToken = utils::ReadParam('token', '', 'raw_data');
Use the utils::ENUM_SANITIZATION_FILTER_RAW_DATA constant

2024-02-22 17:47 UTC, Molkobain commented on templates/base/components/input/input-toggler.ready.js.twig
Why do you need to set the `checked` property manually? The toggler is full CSS isn't it? (I get the trigger so other components can react to it)

2024-02-22 17:47 UTC, Molkobain commented on sources/Controller/Newsroom/iTopNewsroomController.php
>  	public function OperationViewAll()
I'll dg into that operation later, seems like a lot of code. We might be able to simplify it.

2024-02-22 17:47 UTC, Molkobain commented on css/backoffice/pages/_notifications.scss
> +  justify-content: center;
```suggestion
  @extend %ibo-fully-centered-content;
  flex-direction: column;
```

2024-02-22 18:49 UTC, steffunky commented on templates/base/components/input/input-toggler.ready.js.twig
No, there is a wrapper to make the background and another div to make the slider. The checkbox itself is hidden

2024-02-22 20:21 UTC, Molkobain commented on css/backoffice/pages/_notifications.scss
> +svg {
```suggestion
  svg {
```

2024-02-22 20:23 UTC, Molkobain commented on dictionaries/ui/application/newsroom/fr.dictionary.itop.newsroom.php
> +	'UI:Newsroom:iTopNotification:SelectMode:Label' => 'Mode de sélection',
```suggestion
	'UI:Newsroom:iTopNotification:SelectMode:Label' => 'Sélection multiple',
```

2024-02-23 09:59 UTC, steffunky commented on sources/Application/UI/Base/Component/Input/InputUIBlockFactory.php
> +	public static function MakeInputWithLabel(string $sName, string $sLabel, Input $oInput, ?string $sId = null)
Done in [0de2935](https://github.com/Combodo/iTop/pull/617/commits/0de2935210cf9df22fdc4f4bebeb24333dac965f)

2024-02-28 08:17 UTC, Molkobain approved these changes

2024-02-28 08:22 UTC, merged