N°6086 - Import csv : Treat the first line as a header
Combodo/iTop pull request #621
Opened 2024-02-27 09:07 UTC by bdalsass

2024-02-27 14:40 UTC, Molkobain requested changes
Rather include the column number in the dict. entry and use `\Dict::Format()`, that way both the symbol (`"#"` is anglo-saxon oriented, in latin languages we might use something else) and the placement (for those who want to put the number first)

2024-02-27 15:36 UTC, piRGoif requested changes
Nice work thanks !
As this is a bugfix, can this be rebased to support/2.7 ? The decision on which versions the PR will be merged are made during functional review, but it's easier to base on the lowest branch

2024-02-27 15:36 UTC, piRGoif commented on pages/ajax.csvimport.php
> +				// iterate throw data elements...
```suggestion
```

2024-02-27 15:36 UTC, piRGoif commented on pages/ajax.csvimport.php
> +					// get data element
```suggestion
```

2024-02-27 15:36 UTC, piRGoif commented on pages/ajax.csvimport.php
> +					// when first line
I would suggest removing the comment, and renaming $i to something like `$iDataLineNumber` ?

2024-02-27 19:54 UTC, Molkobain commented on pages/ajax.csvimport.php
> +							$aColumns[] = ["label" => Dict::Format('UI:CSVImport:Column',$j+1)];
```suggestion
							$aColumns[] = ["label" => Dict::Format('UI:CSVImport:Column', $j+1)];
```

2024-02-27 19:55 UTC, Molkobain approved these changes

2024-02-27 19:57 UTC, Molkobain commented
Ok for me, mind to change the target branch to support/3.2

2024-02-28 12:36 UTC, Hipska commented
Also, https://github.com/Combodo/iTop/blob/4e53deec9d96093df87b233249a9c071ae458d40/.github/pull_request_template.md?plain=1#L3-L5

2024-02-28 15:32 UTC, bdalsass commented on pages/ajax.csvimport.php
> +					// when first line
oky done

2024-02-28 16:06 UTC, closed without merging

2024-02-28 16:09 UTC, bdalsass commented
Le changement de cible m'a foutu un vrac pas permis avec conflit et plein de truc en sortie.
J'ai récupéré les commits et changé un bout de code sur la gestion du nombre max d'éléments qui n'était pas cohérent si on utilise la première ligne comme entêtes.