feat(ModuleInstaller): Add method to rename tables in the DB
Combodo/iTop pull request #623
Opened 2024-02-28 12:32 UTC by Hipska

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N/A
| Type of change?                                               | Enhancement

## Objective

To have a helper method that can rename a table in DB during setup. The helper method can silently ignore the renaming if the origin table doesn't exist or the destination table already exists. This to avoid errors when running the setup again after the migration has ben done before.

## Proposed solution

Creation of `ModuleInstallerAPI::MoveColumnInDB`.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have tested all changes I made on an iTop instance
- [x] I have added a unit test, otherwise I have explained why I couldn't
- [x] Is the PR clear and detailled enough so anyone can understand digging in the code?

2024-02-28 17:40 UTC, Molkobain commented on setup/moduleinstaller.class.inc.php
> +			return;
Maybe in case the destination table already exists we should put something in the log? It would help troubleshooting why a table remains in the DB whilst we expected it to be renamed.

2024-02-28 17:43 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +		$this->assertEquals($aOrigTableInfo, CMDBSource::GetTableInfo($sDstTable), 'Table was not renamed');
After checking that everything went as expected, you should rename the table back to its original name, otherwise you might pollute other (futures) tests.

2024-02-28 17:43 UTC, Molkobain requested changes
See comment on test

2024-02-29 09:29 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +			return;
I took example from the `MoveColumnInDB` helper which also doesn't do this: https://github.com/Combodo/iTop/blob/187a895265eaa90f1a600a614653a92b2dc907ae/setup/moduleinstaller.class.inc.php#L261-L272


Also see what I wrote in the objective about this.

2024-02-29 09:33 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +		$this->assertEquals($aOrigTableInfo, CMDBSource::GetTableInfo($sDstTable), 'Table was not renamed');
Hmm, aren't tests in php run in their own isolated environment and teardown afterwards? https://github.com/Combodo/iTop/blob/187a895265eaa90f1a600a614653a92b2dc907ae/tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php#L28-L35

2024-02-29 16:32 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +		$this->assertEquals($aOrigTableInfo, CMDBSource::GetTableInfo($sDstTable), 'Table was not renamed');
* PHP Unit tests are run in the "iTop" production environment (99%) unless specified otherwise (see `\Combodo\iTop\Test\UnitTest\ItopCustomDatamodelTestCase`).
  * PHP Unit tests are run in the same process, there is no isolation for performance reasons. Previously, most tests were isolated but their execution took way too much time due to the MetaModel being started everytime.
  * Also, DDL statements can't be rollbacked during a transaction as they are committed instantly.

So it's best to revert the table to its original state in order to keep it clean for other tests.
Moving the revert in the teardown method would not pollute other test classes, but it would impact other tests from the current class.

2024-02-29 16:33 UTC, Molkobain commented on setup/moduleinstaller.class.inc.php
> +			return;
> Also see what I wrote in the objective about this.

What do you mean?

2024-02-29 16:37 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +			return;
This exactly:

>The helper method can silently ignore the renaming if the origin table doesn't exist or the destination table already exists. This to avoid errors when running the setup again after the migration has ben done before.

2024-02-29 16:50 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +		$this->assertEquals($aOrigTableInfo, CMDBSource::GetTableInfo($sDstTable), 'Table was not renamed');
Okay, added a revert.

2024-03-01 10:31 UTC, Molkobain approved these changes

2024-03-01 10:31 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +		$this->assertEquals($aOrigTableInfo, CMDBSource::GetTableInfo($sDstTable), 'Table was not renamed');
Thanks

2024-03-01 16:00 UTC, piRGoif requested changes
Great work, thanks !
My remarks are mostly questions, and also we may add more uses cases in the phpunit

2024-03-01 16:00 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +	 * @param $sDstTable string
```suggestion
	 * @param string $sOrigTable
	 * @param string $sDstTable
```

2024-03-01 16:00 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +	{
Maybe check that orig and dest aren't the same ?

2024-03-01 16:00 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +		}
Shouldn't an exception being thrown ? Like a `CoreUnexpectedValue` ?

2024-03-01 16:00 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +		CMDBSource::Query($sQueryRename);
I think the @throws in the method phpdoc are because of this call ? 
Maybe we should surround with a try/catch and throw only one exception like a `MySQLException` ?

2024-03-01 16:00 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> -		if (!CMDBSource::IsTable($sOrigTable) || !CMDBSource::IsField($sOrigTable, $sOrigColumn))
Ok, we already have the table existing test in IsField()

2024-03-01 16:00 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
> +	public function testRenameTableInDB()
I would also test : 
- orig and dest on the same existing table name
- orig and dest on the same non existing table name
- orig on a non existing table name
- dest on an existing table name

This may be easier to code using a dataprovider returning orig and dest names, and expected result ?

2024-03-02 12:07 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +	 * @param $sDstTable string
Strange, PHPStorm generated it this way I think.

2024-03-02 12:11 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +		}
See the `MoveColumnInDB` method where I copied the behaviour from.

2024-03-02 12:14 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +		CMDBSource::Query($sQueryRename);
What should be done with the catched `CoreException` then? IMHO those should not be trowed by `CMDBSource::Query` in the first place.

2024-03-04 08:54 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +	{
Well actually, they would also not error out since the check for existing destination table would return the method..

2024-03-07 10:03 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +		}
Ok right, indeed there are only return in \ModuleInstallerAPI::MoveColumnInDB
This method was added in 2018 so not to far away, it is quite a strange choice :/ 
To be discussed during next review !

2024-03-07 10:17 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +		CMDBSource::Query($sQueryRename);
What I see is that the throws annotations in the `CMDBSource::Query` phpdoc block are wrong starting in support/2.7 : neither me or PHPStorm are finding what would throw a CoreException in this method.
I've fixed the block with da490739 !

Considering `CMDBSource::Query` will only returns a `MySQLException` (or its `MySQLHasGoneAwayException` child) no need anymore to have a try/catch. 
Can you rebase, and adapt the throws annotations in your method to have either only one `@throws MySQLException`, or both throws for `MySQLException` and `MySQLHasGoneAwayException` ?

2024-03-07 15:31 UTC, Molkobain requested changes
Technical review:
  * Unit test:
    * Move table revert in tearDown() method for better robustness in case there is an issue within the test method
  * New method:
    * Add `SetupLog` message in exit conditions (except the `!MetaModel::DBExists(false)`). See `RenameEnumValueInDB()` for a real example, `MoveColumnInDB()` is a bad one.

2024-03-07 16:30 UTC, piRGoif commented on setup/moduleinstaller.class.inc.php
> +		}
Closing conversation, we discussed during tech review and this is no longer valid.

2024-03-21 15:01 UTC, Hipska commented on setup/moduleinstaller.class.inc.php
> +		CMDBSource::Query($sQueryRename);
It turns out the `CoreException` comes from `MetaModel::DBExists`. So it needs to stay even after merge with current develop branch.

2024-05-13 14:14 UTC, Hipska commented
Okay @Molkobain, but earlier you said this:
> So it's best to revert the table to its original state in order to keep it clean for other tests. Moving the revert in the teardown method would not pollute other test classes, but it would impact other tests from the current class.

So I understand that it might impact other tests and thus it needed to be added within the test?

About the exit conditions, I thought this was also discussed and agreed before?
> Ok right, indeed there are only return in \ModuleInstallerAPI::MoveColumnInDB This method was added in 2018 so not to far away, it is quite a strange choice :/ To be discussed during next review !

Followed by
> Closing conversation, we discussed during tech review and this is no longer valid.

Do I understand this wrong?

2024-07-10 08:48 UTC, Hipska commented
@Molkobain?

2024-07-16 07:58 UTC, Molkobain commented
Hello Thomas, nevermidn about the revert table comment, leave it as it is.
Just missing the `SetupLog` messages, then alright for me. :)

2024-07-16 20:12 UTC, Molkobain approved these changes

2024-07-16 20:12 UTC, Molkobain commented
Thanks!

2024-07-24 08:49 UTC, Molkobain approved these changes

2024-07-24 08:51 UTC, merged

2024-07-24 08:51 UTC, Molkobain commented
Done, thanks a lot Thomas!