Bring unattended-install CLI script in iTop repository
Combodo/iTop pull request #624
Opened 2024-02-28 13:33 UTC by odain-cbd

This script is useful to install iTop via CLI. this is already used in our CI and SaaS tools. 

We decided to provided it directly in iTop github repository. as long as it is protected from any HTTP access.

2024-02-28 13:39 UTC, Hipska commented on setup/unattended-install/README.md
> +Unattended-install : this scripts allows to script iTop install and / or updates.
```suggestion
# Unattended-install

This scripts allows to script iTop install and / or updates.
```

2024-02-28 14:50 UTC, jbostoen commented
Could indeed be good to think about https://github.com/Combodo/iTop/pull/223 as well

2024-02-28 16:25 UTC, Molkobain commented on setup/unattended-install/README.md
> +Unattended-install : this scripts allows to script iTop install and / or updates.
+1 would look nicer :)

2024-02-28 16:28 UTC, Molkobain commented on setup/unattended-install/unattended-install.php
> +require_once(dirname(__FILE__, 3) . '/approot.inc.php');
```suggestion
require_once(dirname(__FILE__, 2) . '/approot.inc.php');
```

Shouldn't it be 2 instead?

2024-02-28 16:36 UTC, Molkobain requested changes

2024-02-28 16:36 UTC, Molkobain commented on setup/unattended-install/unattended-install.php
> +}
```suggestion
if ($bUseItopConfig){
	$oConfig = new Config(APPROOT . "/conf/$sTargetEnvironment/config-itop.php");
	$aDBXmlSettings['server'] = $oConfig->Get('db_host');
	$aDBXmlSettings['user'] = $oConfig->Get('db_user');
	$aDBXmlSettings['pwd'] = $oConfig->Get('db_pwd');
	$aDBXmlSettings['name'] = $oConfig->Get('db_name');
	$aDBXmlSettings['prefix'] = $oConfig->Get('db_subname');
	$oParams->Set('database', $aDBXmlSettings);
	$oParams->Set('url', $oConfig->Get('app_root_url'));
}
$aDBXmlSettings = $oParams->Get('database', array());

```

2024-02-28 16:36 UTC, Molkobain commented on setup/unattended-install/unattended-install.php
> +			copy($sConfigFile, "$sConfigFile.backup");
What do you do with that backup file? It stays here? If everything goes fine, we should clean up.

2024-02-29 08:16 UTC, piRGoif requested changes
Thanks for the modification ! 
I would just suggest moving the informations in the README.md to a phpdoc block in the unattended-install.php file header ?

2024-02-29 08:22 UTC, piRGoif commented
> Could indeed be good to think about #223 as well

@jbostoen are you referring to https://github.com/Combodo/iTop/pull/223#issuecomment-1652440721 ?

I don't recall all the discussions that happened in this PR and the modification asked in this comment on the unattended script, but I would prefer we first integrate the current version : that way the git history will be cristal clear. Any modifications could be done later in subsequent pr / commits.

2024-02-29 10:15 UTC, odain-cbd commented on setup/unattended-install/README.md
> +Unattended-install : this scripts allows to script iTop install and / or updates.
if we keep README.md, it is nicer and i will keep your proposal.

Pierre proposed to move this content in unattented script php doc. it is also a good idea to reduce the amount of files to open.

2024-02-29 10:19 UTC, odain-cbd commented on setup/unattended-install/unattended-install.php
> +}
when $bUseItopConfig enabled, setup is run based on db configuration settings. but there were 2 missing settings that I will take into account in next github push: db_tls_enabled / db_tls_ca

2024-02-29 10:26 UTC, odain-cbd commented on setup/unattended-install/unattended-install.php
> +require_once(dirname(__FILE__, 3) . '/approot.inc.php');
indeed it does not work with current proposal

2024-02-29 10:32 UTC, Hipska commented on setup/unattended-install/README.md
> +Unattended-install : this scripts allows to script iTop install and / or updates.
If you keep this readme file, then GitHub will show this as default context when opening this `setup/unattended-install` directory. No need to do an extra click to see the content of the script in that case 😉

2024-02-29 10:52 UTC, odain-cbd commented on setup/unattended-install/unattended-install.php
> +}
just discussed with Pierre. current PR should remain simple. I remove SaaS option to read db settings from itop configuration. it will come but after merging the PR (same logic applied to Jeffrey PR regarding switch_env).

2024-02-29 10:53 UTC, odain-cbd commented on setup/unattended-install/unattended-install.php
> +			copy($sConfigFile, "$sConfigFile.backup");
removed that part also. keep it for another PR.

2024-02-29 11:13 UTC, Hipska approved these changes

2024-02-29 16:44 UTC, piRGoif commented on setup/unattended-install/README.md
> +Unattended-install : this scripts allows to script iTop install and / or updates.
Yes you're right about the README being automatically displayed !

But as what we want to add is just a little phrase and mainly the wiki URL,
And because the wiki page is this sole script documentation,
I still think it would be better to add it as a PHPDoc block at the script beginning.

Having documentation as closed to the code is my preferred option...
Plus this is a particular tool, aiming at technical people for automatic installations purposes.

2024-03-01 10:43 UTC, Molkobain requested changes

2024-03-01 10:43 UTC, Molkobain commented on setup/unattended-install/unattended-install.php
> +require_once(dirname(__FILE__, 3) . '/approot.inc.php');
Just this, then ok for me

2024-03-07 14:47 UTC, Molkobain approved these changes

2024-03-07 14:47 UTC, Molkobain commented on setup/unattended-install/unattended-install.php
> +require_once(dirname(__FILE__, 3) . '/approot.inc.php');
Discussed IRL with Olivier. He tested in real conditions with "3" and it works.

2024-03-12 16:08 UTC, Hipska commented on setup/unattended-install/unattended-install.php
> +require_once(dirname(__FILE__, 3) . '/approot.inc.php');
It probably is "2" when you use `__DIR__`.

2024-03-25 19:33 UTC, Molkobain commented
@odain-cbd what's the status on this PR?
Do you have an internal ticket number that we can prepend on the title?

2024-03-26 07:45 UTC, Hipska commented on tests/php-unit-tests/unitary-tests/setup/unattended-install/UnattendedInstallTest.php
> +		$this->assertEquals("Mode CLI only", $sJson, "even without HTTP protection, script should be called directly by HTTP");
This comment looks wrong?

2024-03-29 10:08 UTC, odain-cbd commented on tests/php-unit-tests/unitary-tests/setup/unattended-install/UnattendedInstallTest.php
> +		$this->assertEquals("Mode CLI only", $sJson, "even without HTTP protection, script should be called directly by HTTP");
agreed and fixed

2024-03-29 10:09 UTC, merged