N°2039 - Allow Actions to be asynchronous
Combodo/iTop pull request #625
Opened 2024-02-28 15:04 UTC by steffunky

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N°2039
| Type of change?                                               | Enhancement

## Symptom (bug) / Objective (enhancement)
Email and webhooks actions in iTop can be asynchronous but they implement their own way to configure themselves. This pull request aims to harmonize these configurations and allow single actions to be asynchronous, or not.

## Proposed solution (bug and enhancement)
An attribute in the Action class that defines if we are asynchronous, synchronous, or if we follow the global rule for this class.
A method that is overridable on each Action class to define what will be the global rule for this type of action.

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [X] Is the PR clear and detailled enough so anyone can understand digging in the code?

2024-02-28 17:29 UTC, Molkobain requested changes

2024-02-28 17:29 UTC, Molkobain commented on core/action.class.inc.php
> +	public function IsAsynchronous(): bool
Should we make this final?
Should we make this protected?

2024-02-28 17:29 UTC, Molkobain commented on core/action.class.inc.php
> +	public function GetAsynchronousGlobalSetting(): bool
Should we make this protected?

2024-02-28 17:29 UTC, Molkobain commented on core/action.class.inc.php
> +	 * @return bool
```suggestion
	 * Will be overloaded by the children classes to return the value of their global asynchronous setting (eg. `email_asynchronous` for `\ActionEmail`, `prefer_asynchronous` for `\ActionWebhook`, ...)
	 *
	 * @return bool true if the global setting for this kind of action if to be executed asynchronously, false otherwise.
```

2024-02-28 17:29 UTC, Molkobain commented on core/action.class.inc.php
> +	 * @return bool
```suggestion
	 * @return bool true if that action instance should be executed asynchronously, otherwise false
```

2024-02-28 17:29 UTC, Molkobain commented on core/action.class.inc.php
> +		return MetaModel::GetConfig()->Get('email_asynchronous');
```suggestion
		return utils::GetConfig()->Get('email_asynchronous');
```

We rather use the `utils::GetConfig()` pattern instead as in some cases the metamodel isn't loaded. even though it is the case here, one could copy / paste this pattern elsewhere.

2024-02-28 17:29 UTC, Molkobain commented on core/asynctask.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("trigger_id", array("targetclass"=>"Trigger", "allowed_values"=>null, "sql"=>"trigger_id", "default_value"=>null, "is_null_allowed"=>true, "on_
Should these attributes be null allowed?

2024-02-28 17:29 UTC, Molkobain commented on core/asynctask.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeText("message", array("allowed_values"=>null, "sql"=>"message", "default_value"=>null, "is_null_allowed"=>true, "depends_on"=>array())));
If these can be null, then you might have an issue at some point with `AddToQueue()`

2024-02-28 17:29 UTC, Molkobain commented on core/asynctask.class.inc.php
> +	 * @throws \ArchivedObjectException
```suggestion
	 * @throws \ArchivedObjectException
```

2024-02-28 17:29 UTC, Molkobain commented on core/asynctask.class.inc.php
> +	 */
```suggestion
	/**
	 * @inheritDoc
	 */
```

2024-02-28 17:29 UTC, Molkobain commented on core/datamodel.core.xml
> +    }
```suggestion
    }
    
```

2024-02-28 17:29 UTC, Molkobain commented on core/asynctask.class.inc.php
> +	public static function AddToQueue(int $iActionId, int $iTriggerId, array $aRecipients, string $sMessage, string $sTitle, string $sUrl, int $iObjectId, string $sObjectClass): void
```suggestion
	public static function AddToQueue(int $iActionId, int $iTriggerId, array $aRecipients, string $sMessage, string $sTitle, string $sUrl, int $iObjectId, ?string $sObjectClass): void
```

2024-02-28 17:29 UTC, Molkobain commented on core/datamodel.core.xml
> +		return MetaModel::GetConfig()->Get('notifications.itop.send_asynchronously');
```suggestion
		return utils::GetConfig()->Get('notifications.itop.send_asynchronously');
```

2024-02-28 17:29 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background',
How about overloading this entry for `\ActionEmail` so it explicits which setting it will follow?
eg. `'Class:ActionEmail/Attribute:asynchronous' => 'Whether this action should be sent using the "email_asynchronous" setting or override it',`

Same for the news action.

2024-02-28 17:29 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background through the CRON job or not',
```

2024-02-28 17:29 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'L\'action est-elle exécutée de manière asynchrone ?',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'L\'action est-elle exécutée de manière asynchrone par le CRON ?',
```

2024-02-28 17:29 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationService.php
> +
```suggestion
<?php
namespace  Combodo\iTop\Service\Notification\Event;

```

2024-02-28 17:29 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationService.php
> +	public static function MakeEventFromAction(Action $oAction, int $iContactId, int $iTriggerId, string $sMessage, string $sTitle, string $sUrl, int $iObjectId, string $sObjectClass, string|null $sDate
```suggestion
	public static function MakeEventFromAction(Action $oAction, int $iContactId, int $iTriggerId, string $sMessage, string $sTitle, string $sUrl, int $iObjectId, ?string $sObjectClass, string|null $sDate = null): EventiTopNotification
```

2024-02-28 17:29 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationService.php
> +	 * @param string $sObjectClass
```suggestion
	 * @param string|null $sObjectClass
```

2024-02-28 17:29 UTC, Molkobain commented on sources/Service/Notification/Event/EventiTopNotificationService.php
> +		if($sDate !== null){
```suggestion
		if ($sDate !== null) {
```

2024-02-28 17:29 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
> +				false,
```suggestion
				true,
```

Did you mean true?

2024-02-28 17:29 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
> +				true,
```suggestion
				false,
```

Did you mean false?

2024-02-28 17:32 UTC, Molkobain commented
I know I was the one to come up with `'follow_global_setting' => 'Follow global settings'`, but it feels weird.
Do you think there is a better alternative? `'use_global_setting' => 'Use global settings'` ?

2024-02-28 18:55 UTC, steffunky commented on core/action.class.inc.php
> +	public function IsAsynchronous(): bool
Maybe some classes will want more checks before allowing asynchronous (if a specific class exists, if a method exists, if a php extension is enabled)

2024-02-28 18:56 UTC, steffunky commented on core/action.class.inc.php
> +	public function GetAsynchronousGlobalSetting(): bool
Same as above but I think this one is ok to actually be protected

2024-02-28 19:01 UTC, steffunky commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background',
Yea I had the same idea but was not sure if it was relevant to put iTop config variables here at it's probably not the same persons that edit the config and configure the notifications

2024-02-28 19:03 UTC, steffunky commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background',
Should we hardcode that it's the CRON that do this job? In the future it might be another PHP thread, a remote service or even a local script that does this. I'm ok to do that for ActionEmail and ActioniTopNotification but I'm not sure about all Actions

2024-02-28 19:03 UTC, steffunky commented on dictionaries/fr.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'L\'action est-elle exécutée de manière asynchrone ?',
Same as above

2024-02-28 19:07 UTC, steffunky commented on tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
> +				true,
![image](https://github.com/Combodo/iTop/assets/5959857/57fe67ff-77c5-4820-9232-3f99ab518d11)

2024-02-28 19:08 UTC, steffunky commented on tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
> +				true,
![image](https://github.com/Combodo/iTop/assets/5959857/2cca2f59-6ae0-4d12-87ee-a1cbeb35a1ec)

2024-02-28 19:09 UTC, steffunky commented
> I know I was the one to come up with `'follow_global_setting' => 'Follow global settings'`, but it feels weird. Do you think there is a better alternative? `'use_global_setting' => 'Use global settings'` ?

Yea sure that could work too

2024-02-28 20:01 UTC, Molkobain commented
> > I know I was the one to come up with `'follow_global_setting' => 'Follow global settings'`, but it feels weird. Do you think there is a better alternative? `'use_global_setting' => 'Use global settings'` ?
> 
> Yea sure that could work too

Any thoughts @jbostoen @Hipska @larhip ?

2024-02-28 20:07 UTC, Molkobain commented on dictionaries/en.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background',
Initially I specified "CRON" so people explicitly understand that they need their CRON job to be up and running for these actions to be executed. But you are right, it's probably better and less techy to just say "background". I'll adjust the suggestion.

2024-02-28 20:08 UTC, Molkobain commented on dictionaries/fr.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'L\'action est-elle exécutée de manière asynchrone ?',
Updated suggestion

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/es_cr.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/de.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/da.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/cs.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/hu.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/it.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/ja.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/nl.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/pl.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/pt_br.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/ru.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/sk.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/tr.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:40 UTC, Molkobain commented on dictionaries/zh_cn.dictionary.itop.core.php
> +	'Class:Action/Attribute:asynchronous+' => 'The action is executed in background~~',
```suggestion
	'Class:Action/Attribute:asynchronous+' => 'Whether this action should be executed in background or not~~',
```

2024-02-28 20:56 UTC, larhip commented
> > > I know I was the one to come up with `'follow_global_setting' => 'Follow global settings'`, but it feels weird. Do you think there is a better alternative? `'use_global_setting' => 'Use global settings'` ?
> > 
> > 
> > Yea sure that could work too
> 

In general I like this PR :-)

Regarding the naming of that specific setting:
IMHO I would prefer `use_global_setting`. That sound a little bit more straight forward to me..

Maybe it would make sense to "override" the translation in the final class, depending on the implementation. For example:
```
'Class:Action/Attribute:asynchronous/Value:use_global_setting' => 'Use global setting',
'Class:ActionEmail/Attribute:asynchronous/Value:use_global_setting' => 'Depends on configuration',
```
But just an idea. And it is already quite late so it might be nonsense :-P

2024-02-29 10:26 UTC, steffunky commented on core/asynctask.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeText("message", array("allowed_values"=>null, "sql"=>"message", "default_value"=>null, "is_null_allowed"=>true, "depends_on"=>array())));
Done in [955acec](https://github.com/Combodo/iTop/pull/625/commits/955acec870993f1d1811de2d47df36ed99b34729)

2024-02-29 10:26 UTC, steffunky commented on core/asynctask.class.inc.php
> +		MetaModel::Init_AddAttribute(new AttributeExternalKey("trigger_id", array("targetclass"=>"Trigger", "allowed_values"=>null, "sql"=>"trigger_id", "default_value"=>null, "is_null_allowed"=>true, "on_
Done in [955acec](https://github.com/Combodo/iTop/pull/625/commits/955acec870993f1d1811de2d47df36ed99b34729)

2024-02-29 14:03 UTC, steffunky commented on core/action.class.inc.php
> +	public function IsAsynchronous(): bool
Seen with Guillaume, it stays public

2024-02-29 14:04 UTC, steffunky commented on core/action.class.inc.php
> +	public function GetAsynchronousGlobalSetting(): bool
Seen with Guillaume, it stays public but it's now static

2024-02-29 16:34 UTC, Molkobain approved these changes

2024-02-29 16:35 UTC, Molkobain commented
Nice job

2024-02-29 16:37 UTC, Molkobain commented
> But just an idea. And it is already quite late so it might be nonsense :-P

Actually a good idea IMHO as we discussed it as well 😁
But we were not very sure if putting the conf. param. name in the dict entry would be very relevant to the user as it is very techy. Your approach sounds good :)

2024-03-01 08:27 UTC, merged