N°7302 Fix unit name in \SetupUtils::HumanReadableSize
Combodo/iTop pull request #626
Opened 2024-02-28 17:14 UTC by piRGoif

Was sending Hb instead of Eb (exabyte)

2024-02-28 18:38 UTC, Molkobain approved these changes

2024-02-29 09:52 UTC, Hipska requested changes

2024-02-29 09:52 UTC, Hipska commented on setup/setuputils.class.inc.php
> +     */
Are these links really necessary?

2024-02-29 09:52 UTC, Hipska commented on setup/setuputils.class.inc.php
> +        $aSizes = array('bytes', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb');
Actually, the first one says bytes and all the others are about bits?
```suggestion
        $aSizes = array('bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB');
```

See https://en.wiktionary.org/wiki/EB#Symbol vs https://en.wiktionary.org/wiki/Eb#Symbol

2024-02-29 16:24 UTC, Molkobain commented on setup/setuputils.class.inc.php
> +        $aSizes = array('bytes', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb');
Good catch!

2024-02-29 16:45 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +     */
I wasn't very sure about the units used above terra bytes, they aren't so common :)
So having references for anyone seems like a good idea ?

2024-02-29 16:52 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +        $aSizes = array('bytes', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb');
You're perfectly right ! I was wondering also why we had "b" and not "B" ?
I've just checked, values processed are from `disk_free_space()` of `filesize()`, so they are indeed in bytes.
I'll fixed that, thanks

2024-02-29 16:54 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +        $aSizes = array('bytes', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb');
Fixed in 684fa2d4

2024-02-29 16:56 UTC, Hipska commented on setup/setuputils.class.inc.php
> +     * @return string formatted string, for example "161.62 Gb"
```suggestion
     * @return string formatted string, for example "161.62 GB"
```

2024-02-29 16:58 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +     * @return string formatted string, for example "161.62 Gb"
Fixed, thanks !

2024-02-29 17:03 UTC, Hipska requested changes

2024-02-29 17:03 UTC, Hipska commented on setup/setuputils.class.inc.php
> +		$aSizes = array('Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB');
Actually it can be lowercase. Also, the k in kilobytes is also lowercase
```suggestion
		$aSizes = array('bytes', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB');
```
See https://en.wikipedia.org/wiki/Kilobyte

2024-03-01 08:32 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +		$aSizes = array('Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB');
Yes indeed, thanks !
About bytes VS Bytes : 
https://en.wiktionary.org/wiki/byte#English
https://en.wiktionary.org/wiki/Byte

2024-03-01 08:35 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +		$aSizes = array('Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB');
Fixed in 590c8ce3

2024-03-01 09:10 UTC, Hipska approved these changes

2024-03-01 10:23 UTC, Molkobain approved these changes

2024-03-04 13:09 UTC, Molkobain commented
Accepted during support PRs review

2024-03-12 15:17 UTC, Molkobain commented
Accepted during functional review

2024-03-12 17:09 UTC, piRGoif commented on setup/setuputils.class.inc.php
> +     */
Closing conversation as in the reviews there was no objection to keep those url references

2024-03-12 17:09 UTC, merged