Feature/doc object manipulation API
Combodo/iTop pull request #63
Opened 2019-03-13 16:18 UTC by bruno-ds

The goal of this PR is to generate a phpdoc of the object manipulation API.

It will be an iterative process, with many drafts.

2019-03-18 11:32 UTC, piRGoif requested changes
Some generic comments :
* always add type hinting when adding @param
* beware of the useless { and [
* sometimes @link is a better fit than @see
* not sure "@todo: better document this method" are a good idea... I would better create a ticket referencing all of the methods that needs to have better doc ?
* some lines with useless spaces, beware of your code formatter

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
>  	// Read-only <=> Written once (archive)
Remove this or move it to the PHPDoc block !

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * Whether the object is already persisted in DB or not.
This is duplicating the m_bIsInDB attribute phpdoc... I would either replace all of this with a @see, or the opposite (only a @see on the attribute and the doc in the method). I would prefer the 1st solution

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * @param $sClass
add the type hint string ?

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * This representation is subject to change.
are @api and "subject to change" compatible ? O:)

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * In almost every case it is preferable to use {@see DBObject::m_bFullyLoaded}.
I would have written @link instead of @see, but maybe I'm wrong ?

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @param bool $bAllowAllData @deprecated the reload must never fail
This phrase is not very clear, I don't understand it... The attribute is not used in the method anymore, what was it used for ?

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * @param $value
don't forget to add type hinting...

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * Get the {@see AttributeDefinition}'s label.
Definitively, here it should be a @link instead of a @see

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     *
there are lots of spaces on this line, beware of configuring your code formatter properly

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
>  	 * @return array List of attcodes
Sure ? The code does : `return null;`

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * @return int
You should add some @link to the corresponding constants

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @return bool
it would be interesting to know here what happens if the method returns false (or why should you override this ?)

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * @param null $sKeyAttCode
string instead of null

2019-03-18 11:32 UTC, piRGoif commented on core/dbobject.class.php
> +     * @param null $sKeyAttCode
string instead of null

2019-03-18 11:32 UTC, piRGoif commented on core/dbobjectsearch.class.php
> +/** @internal Dev hack for disabling the some query build optimizations (Folding/Merging) */
"for disabling some query ..." (remove "the")

2019-03-19 07:17 UTC, piRGoif reviewed
Is the  ast.dump file should be versionned ?

2019-03-21 16:14 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Whether the object is already persisted in DB or not.
on the resulting phpdoc, the navigation is not really easy. I'd rather attach meaningful information the the api endpoint.

2019-03-21 16:17 UTC, bruno-ds commented on core/dbobject.class.php
> +     * In almost every case it is preferable to use {@see DBObject::m_bFullyLoaded}.
mmh, the difference is so subtle that I don't understand it:
> https://docs.phpdoc.org/guides/docblocks.html#list-of-tags
> link: indicates a relation between the associated element and a page of a website.
> see: indicates a reference from the associated element to a website or other elements.

for now I decided to use @see for internal relations and @link for link to external websites.
Do you disagree?

2019-03-21 16:19 UTC, bruno-ds commented on core/dbobject.class.php
> +	 * @param bool $bAllowAllData @deprecated the reload must never fail
AllowAllData has a strong sematic: if true, then the user rigths overs the classes are not check. it's like a [ring 0](https://en.wikipedia.org/wiki/Protection_ring)

2019-03-21 16:22 UTC, bruno-ds commented on core/dbobject.class.php
> +     *
I tried to respect a schema: 
/**
* Title
* [space]
* long description, possibly multiline
* [space]
* @api and associates
* [space]
* @param
* [space]
* @return
* [space]
* @throws
*/

What format would you prefer?

2019-03-21 16:24 UTC, Hipska commented on core/dbobject.class.php
> +     *
No space between @ items.

PS, use ` to comment code.

2019-03-21 16:27 UTC, bruno-ds commented on core/dbobject.class.php
> +	 * @return bool
By reading the use of the method, the signature should be 
```
@return bool|string true mean the consistency is correct, returning a string mean the consistency is not correct, the string should be a human readable description of the problem
```

2019-03-21 16:36 UTC, bruno-ds commented on core/dbobjectsearch.class.php
> +/** @internal Dev hack for disabling the some query build optimizations (Folding/Merging) */
corrected.
But since it has the @internal tag, it is now excluded, soit should be out of scope.

2019-03-21 16:43 UTC, piRGoif commented on core/dbobject.class.php
> +     *
I meant, on the line 686 you had *<space><space>... (trailing spaces)

2019-03-21 16:44 UTC, piRGoif commented on core/dbobject.class.php
> +	 * @return bool
That's better :) But if you return a string that means persisting is cancelled ?

2019-03-26 16:09 UTC, bruno-ds commented on core/dbobject.class.php
> +	 * @return bool
if the !== true then DoCheckToWrite() append a $this->m_aCheckIssues[], then CheckToWrite return fale, then,  DBObject trigger a  CoreCannotSaveObjectException while cmdbAbstractObject simply refuse to write the object.

=> the final behaviour vary, but in general, yes, "persisting is cancelled".

@rquetiez will probably finalize the comments, I'll let him coose how far we go in the phpdoc.

2019-03-26 16:11 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Whether the object is already persisted in DB or not.
finaly, the attributes are excluded from the doc, they generated too much noise.

2019-03-26 16:12 UTC, piRGoif commented on core/dbobject.class.php
> +     * Whether the object is already persisted in DB or not.
Ok :) It would be nice to have only a @see on the attribute so...

2019-03-26 16:12 UTC, bruno-ds commented on core/dbobject.class.php
> +     * This representation is subject to change.
We'll debate of this internaly

2019-04-03 15:44 UTC, piRGoif commented on core/dbobject.class.php
> +     * Is the current instance fully or partially loaded.
I prefer this to be on the @return line, what do you think ?

2019-04-04 06:48 UTC, bruno-ds commented on core/dbobject.class.php
> +     * @see MetaModel::NewObject()
beware: 
Since `MetaModel` is not yet included in the scope of the generated doc, 
this `@see MetaModel::NewObject()` will result in a dead link on the generated API page.

2019-04-04 06:56 UTC, bruno-ds commented on core/dbobject.class.php
> +     * @internal The availability of this method is not guaranteed in the long term, you should preferably use MetaModel::NewObject().
Putting an @internal will prevent this method to be present in the generated doc.
It is probably by intent, so feel free to close this without comment  ;)

2019-04-04 06:57 UTC, bruno-ds commented on core/dbobject.class.php
> +        $sFriendlyname = $this->GetAsHTML('friendlyname');
For the sake of clarity of those commits, you should avoid changes in the code ;)

2019-04-04 07:01 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Is the current instance fully or partially loaded.
I'm ok with you, but a title as to be present otherwise the next bloc of text will become the title, it would be awful in the generated doc.

2019-04-04 07:05 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Getter : get a value from the current object of from a related object
typo `of from`

2019-04-04 13:59 UTC, bruno-ds commented on core/dbobject.class.php
> +	 * Returns the label as defined in the dictionary for the language of the current user
shouldn't this be in the @return tag?

2019-04-04 14:01 UTC, bruno-ds commented on core/dbobject.class.php
> +     * @see DBWrite
@see must have a very special signature as stated in the known limitations here : 
https://github.com/Combodo/iTop/blob/feature/doc-object-manipulation/.doc/README.md

2019-04-04 14:03 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Pior to the delete the object, it checks if this is feasible to guarantee the DB integrity.
multiple typos : 
> *Pior* to *the* delete the object
Prior to delete the object

2019-04-04 14:04 UTC, bruno-ds commented on core/dbobject.class.php
> +     * Suitable for use as a lifecycle action
maybe we could create a @lifecycle  in order to put an emphasis on this key principle?
(I could render it as IO did for the @api-advanced)

2019-05-06 13:21 UTC, piRGoif commented
Rebased manually branch with @bruno-ds to avoid future conflicts (there was one on /composer.json)

2019-05-16 06:33 UTC, piRGoif approved these changes

2019-05-21 10:05 UTC, merged