N°7331 - Add cleanup script for NPM dependencies
Combodo/iTop pull request #631
Opened 2024-03-11 15:09 UTC by Molkobain

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N°7331
| Type of change?                                               | Bug fix / Enhancement / Translations

## Objective (enhancement)
Do like we do for Composer dependencies: Remove tests, examples and demo files to minimize the package size and vulnerabilities.

## Proposed solution (bug and enhancement)
This PR does 3 things:
  * Refactor current Composer implementation in order to use the mechanism with another dependency manager
  * Add an implementation for NPM
  * Remove these files for NPM packages

## Checklist before requesting a review

- [X] I have performed a self-review of my code
- [X] I have tested all changes I made on an iTop instance
- [X] I have added a unit test, otherwise I have explained why I couldn't
- [X] Is the PR clear and detailed enough so anyone can understand digging in the code?

## Checklist of things to do before PR is ready to merge

2024-03-11 17:16 UTC, Molkobain commented
Just ran all Behat tests: Ok

2024-03-12 11:03 UTC, piRGoif requested changes

2024-03-12 11:03 UTC, piRGoif commented on node_modules/.htaccess
> +	<FilesMatch ".+\.(css|scss|js|map|png|bmp|gif|jpe?g|svg|tiff|woff2?|ttf|eot1)$">
```suggestion
	<FilesMatch ".+\.(css|scss|js|map|png|bmp|gif|jpe?g|svg|tiff|woff2?|ttf|eot)$">
```

2024-03-12 11:03 UTC, piRGoif commented on .make/dependencies/rmUnnecessaryFolders.php
> +	throw new \Exception("Usage: " . __FILE__ . " --manager composer|npm");
Use one of the typed SPL Exception ? 
Ref https://www.php.net/manual/en/spl.exceptions.php
I would choose InvalidArgumentException ?

```suggestion
	throw new \InvalidArgumentException("Usage: " . __FILE__ . " --manager composer|npm");
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/AbstractHook.php
> +abstract class AbstractHook
I would rather use a name like AbstractDependenciesFoldersAnalyzer ?

2024-03-12 11:03 UTC, piRGoif commented on .make/dependencies/rmUnnecessaryFolders.php
>  		throw new \Exception("$sDir must end with /Test/ or /test/");
```suggestion
		throw new \RuntimeException("$sDir is in the denied list but doesn't comply with the rule (see IsQuestionnableFolder method)");
```

2024-03-12 11:03 UTC, piRGoif commented on .make/dependencies/rmUnnecessaryFolders.php
>  		throw new \Exception("$sDir must end with /Test/ or /test/");
But shouldn't we list all corresponding dirs then exit, instead of exiting on the first one encountered ?

2024-03-12 11:03 UTC, piRGoif commented on .make/dependencies/rmUnnecessaryFolders.php
> +$aExistingDirs = $oDependenciesHandler->ListAllQuestionnableFoldersAbsPaths();
I found the methods name without "questionnable" clearer ? I like the "AbsPath" though :)

2024-03-12 11:03 UTC, piRGoif commented on .make/dependencies/rmUnnecessaryFolders.php
> +		.'  They must be declared either in the allowed or denied list in '.$sDependenciesHandlerFQCN." (see N°2651).\n"
Might be misleading to keep the old ticket reference as the code has evolved since then. 
Having both tickets references is too much also... 
I think simply having the message is enough ? 

```suggestion
		."  They must be declared either in the allowed or denied list in {$sDependenciesHandlerFQCN}\n"
```

2024-03-12 11:03 UTC, piRGoif commented on node_modules/.package-lock.json
> +  "name": "dev-support-3.2",
Oh yes, this seems to be generated automatically :/ 
I think we are missing the name field in the package.json file right ? https://docs.npmjs.com/cli/v10/configuring-npm/package-json#name

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/AbstractHook.php
> + */
```suggestion
/**
 * Class AbstractHook
 *
 * Extend this class to enable a dependency manager such as Composer or NPM to clean unnecessary files after an installation or update of a package.
 *
 * @author Guillaume Lajarige <guillaume.lajarige@combodo.com>
 * @package Combodo\iTop\Dependencies
 *
 * @since 3.2.0 N°7331 class creation to have managers for both Composer and NPM (only Composer was existing before)
 */
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/Composer/iTopComposer.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/Composer/iTopComposer.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/Composer/iTopComposer.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/Composer/iTopComposer.php
> +		];
To ease readability and maintenance I would extract prefix ? Something like : 

```suggestion
		$aDeniedDirs = [
			'/doctrine/lexer/tests',

			'/goaop/framework/tests',

			'/laminas/laminas-servicemanager/src/Test',

			'/nikic/php-parser/test',

			'/pear/archive_tar/tests',
			'/pear/console_getopt/tests',
			'/pear/pear_exception/tests',

			'/psr/log/Psr/Log/Test',

			'/symfony/cache/Tests',
			'/symfony/cache/Tests/DoctrineProviderTest.php',
			'/symfony/class-loader/Tests',
			'/symfony/config/Tests',
			'/symfony/console/Tests',
			'/symfony/css-selector/Tests',
			'/symfony/debug/Resources/ext/tests',
			'/symfony/debug/Tests',
			'/symfony/dependency-injection/Tests',
			'/symfony/dotenv/Tests',
			'/symfony/event-dispatcher/Tests',
			'/symfony/filesystem/Tests',
			'/symfony/finder/Tests',
			'/symfony/http-client-contracts/Test',
			'/symfony/http-foundation/Test',
			'/symfony/http-kernel/Tests',
			'/symfony/service-contracts/Test',
			'/symfony/framework-bundle/Test',
			'/symfony/mime/Test',
			'/symfony/routing/Tests',
			'/symfony/stopwatch/Tests',
			'/symfony/translation-contracts/Test',
			'/symfony/twig-bridge/Test',
			'/symfony/twig-bundle/Tests',
			'/symfony/var-dumper/Test',
			'/symfony/var-dumper/Tests/Test',
			'/symfony/var-dumper/Tests',
			'/symfony/web-profiler-bundle/Tests',
			'/symfony/yaml/Tests',

			'/tecnickcom/tcpdf/examples',

			'/thenetworg/oauth2-azure/tests',

			'/twig/twig/src/Test',
			'/twig/twig/lib/Twig/Test',
			'/twig/twig/doc/tests',

			'/laminas/laminas-servicemanager/src/Test',
		];

		$aDeniedDirsAbsPath = array_map(function ($sRelDir) use ($APPROOT_WITH_SLASHES) {
			return $APPROOT_WITH_SLASHES . $sRelDir;
		}, $aDeniedDirs);

		return $aDeniedDirs;
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/Composer/iTopComposer.php
> +		];
Same suggestion as below, extract the prefix ?

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/NPM/iTopNPM.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/NPM/iTopNPM.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/NPM/iTopNPM.php
> +	 */
```suggestion
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/AbstractHook.php
> +	abstract protected function GetDependenciesRootFolderAbsPath(): string;
I would rather make this method impl in the abstract class
But each impl to have a new GetDependenciesFolderName() to implement ?

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/NPM/iTopNPM.php
> +			$APPROOT_WITH_SLASHES . '/ace-builds/src-noconflict',
```suggestion
			// ACE Editor see https://www.npmjs.com/package/ace-builds for dir contents
			$APPROOT_WITH_SLASHES . '/ace-builds/demo',
			$APPROOT_WITH_SLASHES . '/ace-builds/src',
			$APPROOT_WITH_SLASHES . '/ace-builds/src-min-noconflict',
			$APPROOT_WITH_SLASHES . '/ace-builds/src-noconflict',
```

2024-03-12 11:03 UTC, piRGoif commented on sources/Dependencies/NPM/iTopNPM.php
> +			$APPROOT_WITH_SLASHES . '/jquery-ui/ui',
Isn't just the root dir enough ? 

```suggestion
			$APPROOT_WITH_SLASHES . '/jquery-ui',
```

2024-03-12 11:03 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/sources/Dependencies/Composer/iTopComposerTest.php
> +	public function testIsTestFolder($sDirName, $bIsTest)
We are testing the abstract class, we should move this to a new class to test the abstract class ?

2024-03-12 11:03 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/sources/Dependencies/Composer/iTopComposerTest.php
> +			$this->assertMatchesRegularExpression(iTopComposer::QUESTIONNABLE_FOLDER_REGEXP, $sDirName, "Directory not matching test dir : $sDir");
We should call IsQuestionnableFolder() instead, compile all false results to an array, and at the very end assert that the array is empty
Actually exactly what is done in testListDeniedTestFolderAbsPaths :)

2024-03-12 11:03 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/sources/Dependencies/Composer/iTopComposerTest.php
>  		$oiTopComposer = new iTopComposer();
Extract this in the setUp method to factorize ?

2024-03-12 11:03 UTC, piRGoif commented on tests/php-unit-tests/unitary-tests/sources/Dependencies/Composer/iTopComposerTest.php
> +	public function testAllFoldersCovered()
If we have a test class for the abstract class, we could factorize this method for both impl
Do a loop on each children...

2024-03-12 15:32 UTC, steffunky approved these changes

2024-03-13 10:58 UTC, Molkobain commented on .make/dependencies/rmUnnecessaryFolders.php
>  		throw new \Exception("$sDir must end with /Test/ or /test/");
Discussed with Pierre, this will be tracked in an enhancement ticket, this PR didn't change this.

2024-03-13 10:59 UTC, Molkobain commented on .make/dependencies/rmUnnecessaryFolders.php
> +$aExistingDirs = $oDependenciesHandler->ListAllQuestionnableFoldersAbsPaths();
Discussed with Pierre, will remove the word "questionnable"

2024-03-13 11:03 UTC, Molkobain commented on node_modules/.package-lock.json
> +  "name": "dev-support-3.2",
Pierre will check if this can be fixed by setting a name in the package.json file

2024-03-13 13:12 UTC, Molkobain commented on sources/Dependencies/Composer/iTopComposer.php
> +	 */
Actually, I think I will restore them, because it makes it more clear that it's an overloaded method, which isn't visible in editors like GitHub PRs, vi or else.

2024-03-13 14:07 UTC, Molkobain commented
Updated with review comment.
Comments regarding the unit test have not been done yet as it requires too much time ad are out of this PR scope. They will be tracked in a new enhancement ticket with others comments.

2024-03-13 14:07 UTC, merged