N°7146 - Fix style not applied in list in the end-users portal in iTop 3.0+
Combodo/iTop pull request #635
Opened 2024-03-15 16:04 UTC by accognet

Add markup in order to use custom style  on status attributes

2024-04-15 13:11 UTC, Molkobain approved these changes

2024-04-15 13:11 UTC, Molkobain commented
Support PRs review: Code factorized to match what is already done in the manage brick. Ready to merge.

2024-04-15 14:26 UTC, Molkobain requested changes
Contact add doesn't work anymore, but we didn't find yet why.

2024-05-13 13:00 UTC, Molkobain commented
Support PRs review: Contact add has been fixed, but some ext. keys lost their hyperlink. We will investigate further more.

2024-07-10 07:05 UTC, Molkobain commented
Functional review: Accepted for 3.2

@accognet you can squash & merge (mind to keep the PR # in the commit)
I'll add the tests to do in the ticket.

2024-07-12 09:28 UTC, Hipska requested changes

2024-07-12 09:28 UTC, Hipska commented on datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
> +			'attributes'        => [],
Don't know why these were added, before looked better:
```suggestion
			'id'         => $oObject->GetKey(),
			'name'       => $oObject->GetName(),
			'attributes' => [],
```

2024-07-12 12:46 UTC, Hipska requested changes
Could you please check your IDE settings and replace all spaces with tabs?

2024-07-12 12:46 UTC, Hipska commented on sources/Renderer/Bootstrap/FieldRenderer/BsLinkedSetFieldRenderer.php
> +                                    if(row.limited_access)
It looks like your editor has wrong indentation settings configured..
```suggestion
									if(row.limited_access)
```

2024-07-12 12:46 UTC, Hipska commented on sources/Renderer/Bootstrap/FieldRenderer/BsLinkedSetFieldRenderer.php
> +
```suggestion
								var metadataNames = ['object_class', 'object_id', 'attribute_code', 'attribute_type', 'value_raw'];

```

2024-07-12 12:46 UTC, Hipska commented on sources/Renderer/Bootstrap/FieldRenderer/BsLinkedSetFieldRenderer.php
> +                                var metadataNames = ['object_class', 'object_id', 'attribute_code', 'attribute_type', 'value_raw'];
```suggestion
								var cellElem;
								var metadataNames = ['object_class', 'object_id', 'attribute_code', 'attribute_type', 'value_raw'];
```

2024-07-24 15:19 UTC, Molkobain approved these changes

2024-07-24 15:20 UTC, merged