N°7371 - Bug when saving public and private log at same time
Combodo/iTop pull request #636
Opened 2024-03-20 08:44 UTC by accognet

Internal

2024-03-20 10:49 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +				this.options.show_multiple_entries_submit_confirmation = false;
I would rather put this after the SetUserPreference, so the UI is updated only if the call to the server went well.

2024-03-20 10:49 UTC, Molkobain approved these changes

2024-03-20 10:50 UTC, Molkobain commented
Please set a PR title explaining the symptom; not a generic one.

2024-03-20 10:54 UTC, Hipska commented
> Please set a PR title explaining the symptom; not a generic one.

Yes, as it now looks like this PR introduces that bug..

2024-12-09 14:46 UTC, Molkobain requested changes

2024-12-09 14:46 UTC, Molkobain commented on js/utils.js
> +			}); // Make it persistent
Comment is misleading. Making the POST call actually persist the preference, so it doesn't do "nothing" and it's not L221 that persists it (it updates local state).

2024-12-09 14:46 UTC, Molkobain commented on js/layouts/activity-panel/activity-panel.js
> +					&& (Object.keys(this._GetEntriesFromAllForms()).length > 1)) {
This feels messy, if the return type isn't strict maybe you should wrap this in a helper to always return a boolean.

2024-12-10 08:22 UTC, accognet commented on js/layouts/activity-panel/activity-panel.js
> +					&& (Object.keys(this._GetEntriesFromAllForms()).length > 1)) {
I need to find what the "real" value is. I did a lot of testing and changed the value to 'true' many times that's why this test doesn't look good.

2024-12-10 10:45 UTC, Molkobain commented
![image](https://github.com/user-attachments/assets/1777e874-7129-4d38-89de-341274d4f48c)

Careful, rebase of the branch wasn't done correctly, you have 237 commits coming to support/3.2 ! :)

2025-01-30 14:55 UTC, merged