N°7385 - Trigger on mention executed even if it's not a mention with @
Combodo/iTop pull request #638
Opened 2024-03-22 10:35 UTC by accognet

Internal

2024-07-10 07:28 UTC, Molkobain requested changes
**Review of the current proposition**
Mentions are not only for Contact (`@` marker by default), it can be for any kind of objects. So your current implementation breaks it for all other classes.

If we are to go further with this ticket, then we must check if the mentioned object matches the marker it begins with.

**Use case that led to this PR**
When pasting text from an iTop; if the text contains the hyperlink to an object with the same meta data as the mentions, then the mention will be triggered again even if the hyperlink doesn't start with the marker (`@` for Contact).

@v-dumas had this behaviour recently and thought it was nice. So there is obviously a discussion to be done, so we all decide what behaviour we want.

2024-07-10 07:29 UTC, Molkobain commented
I'm moving this PR to "Functional review" even though the technical one didn't occur yet, so the important point can be discussed before going any further.

2024-08-13 14:21 UTC, Molkobain commented
Functional review:
  * Expected behavior: Only trigger a mention, if the hyperlink starts with the corresponding marker (e.g. `@` for `Person`)
  * Target version: 3.2.x if code changes are not too risky, 3.3.0 otherwise. Will be determined, once PR is corrected

2025-01-28 14:33 UTC, rquetiez commented
Code review : the preceding character must be dehardcoded from '@' to the one given in the configuration, depending on the object class.

2025-01-31 14:37 UTC, Molkobain requested changes

2025-01-31 14:37 UTC, Molkobain commented on application/utils.inc.php
> +			if (str_starts_with($sMatchedName,$sMentionPrefix) === false) {
`str_starts_with()` doesn't handle multibyte caracters (non latin alphabets, emojis, ...), you should rather use `mb_strpos()`

2025-01-31 14:37 UTC, Molkobain commented on application/utils.inc.php
> +			//tests if the name starts with $sMentionPrefix (@)
```suggestion
			//tests if the name starts with $sMentionPrefix (e.g. '@' for 'Contact' class)
```

2025-02-03 13:10 UTC, accognet commented on application/utils.inc.php
> +			if (str_starts_with($sMatchedName,$sMentionPrefix) === false) {
As the first character always starts as the first byte, mb is not a problem. See specific test case with an emoji.

2025-02-03 13:23 UTC, rquetiez reviewed
1. Two little typographic rules to fix
2. Having utilsTest derived from iTopDataTestCase seems overkill Is there an alternative?
3. My mistake on my previous review: multi-byte safe function has no sense when it comes to checking the very first character of a byte sequence. Moreover, a test has been added with an emoji as the "marker".

2025-02-03 13:23 UTC, rquetiez commented on application/utils.inc.php
> +			if (str_starts_with($sMatchedName,$sMentionPrefix) === false) {
typographic rules: a space is expected after a coma

2025-02-03 13:23 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/application/utilsTest.php
> +    const USE_TRANSACTION = false;
This statement is a trap in the future: adding a test altering the data will leave the DB changed.

Disabling transaction is required here because there is a "data provider" that invokes setUp(), causing a false negative error "two many transactions left open". This issue was revealed when the class inheritance was changed from `ItopTestCase` to `ItopDataTestCase`.

Solution:
- Rework the current proposal to move the new tests into a dedicated test class derived from `ItopDataTestCase`, and leave the existing test class unchanged (derived from `ItopTestCase`)
- Fix the existing test class will be done in a separate flow

2025-02-03 13:23 UTC, rquetiez commented on tests/php-unit-tests/unitary-tests/application/utilsTest.php
> +        MetaModel::GetConfig()->Set('mentions.allowed_classes', ['@' => 'Person','😊#' => 'Team']);
typographic rules: a space is expected after a coma

2025-02-10 13:50 UTC, rquetiez approved these changes
Ok for merging

2025-04-18 12:52 UTC, merged