N°6365 - Ease iTop installation via unattended CLI by using installation.xml choices
Combodo/iTop pull request #641
Opened 2024-03-29 11:10 UTC by odain-cbd

### Enhancement
It would be nice to ease iTop installation via unattended CLI. Current PR aims at adding an option to this script to compute extensions/modules to activate via installation.xml file.

```
php unattended-install.php -- use-itop-config=1 --response_file=setup_path --use_installation_xml=./datamodels/2.x/installation.xml
```

When using the option there a few usecases:
- **no extensions are specified in XML setup file**
In that case unattended CLI will install iTop in non ITIL mode with all possible extensions based on dependencies (like error and problem management). the list of modules inside XML are not used at all.

setup XML file:
```
<selected_extensions type="array"></selected_extensions>
```

- **extensions are specified in XML setup file:**
In that case unattended CLI will install iTop based only on the list of extensions provided. the list of modules inside XML are not used at all.

Example: 
with below XML setup file iTop will be installed with all ITIL modules + error management modules (and without problem management)

```
<selected_modules type="array">
    <item>itop-config-mgmt-datacenter</item>
    <item>itop-config-mgmt-end-user</item>
    <item>itop-config-mgmt-storage</item>
    <item>itop-config-mgmt-virtualization</item>
    <item>itop-service-mgmt-enterprise</item>
    <item>itop-ticket-mgmt-itil</item>
    <item>itop-ticket-mgmt-itil-user-request</item>
    <item>itop-ticket-mgmt-itil-incident</item>
    <item>itop-ticket-mgmt-itil-enhanced-portal</item>
    <item>itop-change-mgmt-itil</item>
    <item>itop-kown-error-mgmt</item>
</selected_modules>
```

2024-04-05 07:41 UTC, rquetiez commented
As this script is becoming a bit harder to use, it would be nive to have a "usage" explanation when no argument 'or --help) is provided.
The current behavior is:
`> php .\unattended-install.php
No `--response_file` param specified, using default value !
Param file `default-params.xml` doesn't exist ! Exiting...
`

2024-04-05 07:56 UTC, rquetiez commented
A comment on the message given when no response file is provided:
```
No `--response_file` param specified, using default value !
Param file `default-params.xml` doesn't exist ! Exiting...
```
This message is confusing to me because "response file" means "output" of the current script.
On the second line, the "response file" is referred to as "param file".
Furthermore, I do not know where the "default-params.xml" should be placed.

I would rather have this report
```
No `--response_file` param specified, using default value: default-params.xml
Response file `/var/www/itop/setup/unattended-install/default-params.xml` doesn't exist !
Exiting...
```

2024-04-05 08:52 UTC, Molkobain requested changes
2 comments apart, it's fine by me like that. Installation script seems ok and information messages in the CLI are ok for me.

2024-04-05 08:52 UTC, Molkobain commented on setup/unattended-install/InstallationFileService.php
> +}
```suggestion
require_once(APPROOT.'/core/config.class.inc.php');
require_once(APPROOT.'/core/log.class.inc.php');
require_once(APPROOT.'/core/kpi.class.inc.php');
require_once(APPROOT.'/core/cmdbsource.class.inc.php');
require_once(APPROOT.'/application/clipage.class.inc.php');
```

Then during the 2.7 => 3.0 merge, remove these lines.
As this file is part of the iTop repo, we rather adapt the code in the branches rather than maintaining "ifs" (which we do in modules)

2024-04-05 08:52 UTC, Molkobain commented on setup/unattended-install/install-itop.sh
> +echo php $DIR/unattended-install.php --use-itop-config=1 --use_installation_xml="$INSTALLATION_XML" --response_file="$XML_SETUP"
I would use underscores instead of dashes to ease usage for users.
```suggestion
echo php $DIR/unattended-install.php --use_itop_config=1 --use_installation_xml="$INSTALLATION_XML" --response_file="$XML_SETUP"
```

2024-04-08 09:12 UTC, Molkobain requested changes

2024-04-08 09:12 UTC, Molkobain commented on tests/php-unit-tests/unitary-tests/setup/unattended-install/UnattendedInstallTest.php
> +		exec("php ".$cliPath, $aOutput, $iCode);
With this, it will use PHP version from the OS path.
There is a method to use the same PHP binary as PHPUnit, otherwise this can lead to unexpected behavior.

2024-04-09 02:54 UTC, odain-cbd commented on setup/unattended-install/InstallationFileService.php
> +}
ok i will keep it in mind

2024-04-09 07:35 UTC, merged

2024-11-07 15:27 UTC, Hipska commented
Can this branch be removed? It's the last one not being in a directory structure..

2024-11-08 13:23 UTC, odain-cbd commented
yes you are right. sorry for leaving it as is.

2024-11-27 15:49 UTC, Hipska commented on setup/unattended-install/unattended-install.php
> +
@odain-cbd I have a question about this section. When no issues are found, the setup is finished and the config file is readonly again. Then why to try overriding the config file with the backup?