N°7397 - Update welcome popup content for iTop 3.2
Combodo/iTop pull request #648
Opened 2024-05-26 21:14 UTC by Molkobain

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N°7397
| Type of change?                                               | Enhancement

## Objective (enhancement)
Update of the welcome popup content for iTop 3.2 which also introduces features highlights.
This PR is mostly meant to share the WIP to @bdalsass and @dcoille for validation / completion while I'm off.

## Proposed solution (bug and enhancement)
The following screenshots come from the introduction of Delphine's texts into the application.
Mind that texts relative to the modules will be done later in other repos.

![image](https://github.com/Combodo/iTop/assets/5130468/faf68e01-2ab5-4664-9c9a-f77e29f31cdf)

![image](https://github.com/Combodo/iTop/assets/5130468/9baf960e-d643-4ba7-9601-3a8d4d6475f0)

![image](https://github.com/Combodo/iTop/assets/5130468/c32ad64e-7444-40f7-8b32-c0343c27e128)

![image](https://github.com/Combodo/iTop/assets/5130468/26c0a2b7-0dcb-4ba5-96f2-8317cfc0899c)
_Notifications managers only_

![image](https://github.com/Combodo/iTop/assets/5130468/3880b3b7-2544-49b3-b3be-fff9eba58264)

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested all changes I made on an iTop instance
- [X] I have added a unit test, otherwise I have explained why I couldn't => Not necessary
- [X] Is the PR clear and detailed enough so anyone can understand digging in the code?

## Checklist of things to do before PR is ready to merge
- [ ] Validate text contents
- [ ] Add / update images for each news (proposition: put them into `images/illustration/welcome-popup`)
- [ ] Add french translations
- [ ] ...?

2024-05-26 21:19 UTC, Molkobain commented on sources/Application/WelcomePopup/Provider/DefaultProvider.php
> +		if (UserRights::IsActionAllowed(\Trigger::class, \UR_ACTION_MODIFY))
@dflaven is this the proper way to handle "admin" features for SaaS instances or is there another way? I refered to the access for the "notifications" menu

2024-05-30 09:12 UTC, dcoille commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +	'UI:WelcomePopup:Message:320_01_Welcome:Description' => '<div>Congratulations, you landed on '.ITOP_APPLICATION.' '.ITOP_VERSION_NAME.'!</div>
Is iTop 3.2 still named "Fullmoon"?

2024-05-30 09:29 UTC, dcoille requested changes

2024-05-30 09:29 UTC, dcoille commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div>In addition to introducing new features like Newsroom, we\'ve also made significant improvements in terms of compatibility with popular frameworks and databases, ensuring that your '.ITOP_APPLIC
<b>Newsroom</b>
Link Newsroom to the tab 'Say "Hello" to the newsroom'

2024-05-30 09:29 UTC, dcoille commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> -<div>Customize your '.ITOP_APPLICATION.' preferences for a personalized experience.</div>',
Add a link to the "how to manage preferences " 
https://www.itophub.io/wiki/page?id=3_0_0:user:main#managing_your_preferences

2024-05-30 12:53 UTC, Hipska commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +	'UI:WelcomePopup:Message:320_01_Welcome:Description' => '<div>Congratulations, you landed on '.ITOP_APPLICATION.' '.ITOP_VERSION_NAME.'!</div>
The reference to "fullmoon" is removed because of this change, so I guess not.

2024-05-30 14:32 UTC, Hipska commented on sources/Application/WelcomePopup/Provider/DefaultProvider.php
> +				Dict::S("UI:WelcomePopup:Message:320_05_A11yThemes:Description"),
Dictionary items for 05 are missing.

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +	'UI:WelcomePopup:Message:320_01_Welcome:Description' => '<div>Congratulations, you landed on '.ITOP_APPLICATION.' '.ITOP_VERSION_NAME.'!</div>
It's still present through the `ITOP_VERSION_NAME` variable. Fullmoon is/was the design introduced with iTop 3.0, it's still relevant for people who'll jump from 2.7 LTS to 3.2 LTS

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div>We\'re excited to announce long-term support for this new release. </div>
I don't think this is the place to talk about LTS/release as this message will be displayed to all backoffice users, not only admins

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div>In addition to introducing new features like Newsroom, we\'ve also made significant improvements in terms of compatibility with popular frameworks and databases, ensuring that your '.ITOP_APPLIC
Same here, I don't think end-users need to know about frameworks, databases and maybe security too

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div> Plus, our team has worked tirelessly to include critical security patches and enhance accessibility, so you can be confident that your data is always protected and accessible to all users. </di
Talking about users seems odd and admin-focused again

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +	'UI:WelcomePopup:Message:320_05_A11yThemes:Description' => '<div>In addition to '.ITOP_APPLICATION_SHORT.' 3.0 high-contrast theme in '.ITOP_APPLICATION_SHORT.' portal and WCAG compliant architectur
Portal high contrast theme was never released as we never packaged it. Also, I think it was created before 3.0. In the second sentence, we could use `ITOP_APPLICATION_SHORT . ITOP_VERSION_NAME` as we're talking about Fullmoon theme being themed

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +	<li><b>Color blind theme</b></li>
There are 3 themes, I don't know if we should write their names as they describe what kind of color blindness they aim for

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div>Our <b>priority-based scheduling</b> ensures that important messages are sent first, while our URL customization options allow you to direct recipients to the right place. </div>
Priority does not change sending priority, but are displayed first in endusers newsrooms

2024-07-10 06:49 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div>And with support for <b>multiple languages and asynchronous actions</b>, you have complete control over how all kinds of notifications are sent and received. </div>
They do not change how notifications are received but we should add that they make the application faster for the users when sending multiple notifications at once or when emails takes time to send

2024-07-10 07:30 UTC, Hipska commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div> Plus, our team has worked tirelessly to include critical security patches and enhance accessibility, so you can be confident that your data is always protected and accessible to all users. </di
On the other hand, usually most iTop users don't see these messages as they are portal-only. This message is only displayed to back-end users and those usually have knowledge other users exist?

2024-07-10 07:52 UTC, steffunky commented on dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
> +<div> Plus, our team has worked tirelessly to include critical security patches and enhance accessibility, so you can be confident that your data is always protected and accessible to all users. </di
Sure, but in my opinion it is a bit insensitive and it is more relevant in technical sentences (User has the right to, users won't be logged out) while using `people`, `person`, or `you` makes sentences more natural and treat users more as humans rather than a developer/admin concept (But as we have no guidelines for this in iTop this is open to discussion 😁 )

2024-07-15 14:12 UTC, merged