Correctly identify as iTop in cURL requests
Combodo/iTop pull request #652
Opened 2024-07-10 08:43 UTC by Hipska

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N/A
| Type of change?                                               | Enhancement

## Objective

Outgoing HTTP requests are identified with "spider" user agent, which can simply be blocked sometimes.

## Proposed solution

Use for example `iTop/3.2.0` as user agent when doing HTTP requests to other services..

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [x] Is the PR clear and detailed enough so anyone can understand digging in the code?

2024-07-10 09:01 UTC, Molkobain approved these changes

2024-07-10 09:02 UTC, Molkobain commented
Good idea. I don't know if it can have any side effects though?

2024-07-10 09:04 UTC, Hipska commented
Well, the adverse. So, if an external API refuses to connect anything else than `spider` 😉

2024-07-13 08:28 UTC, jbostoen commented
Just wondering if there should be a config setting as well to override this, and set a custom user agent string? (Or we can simply wait for the first real use case where it's necessary and would need to imitate a regular browser string for some reason).

2024-07-31 07:18 UTC, Molkobain commented
I'll raise the question during functional review :)

2024-09-03 16:40 UTC, Molkobain requested changes
Technical review:
  * Ok for the principle
  * But use a conf. param.
    * Name : `http.request.user_agent` (another name might be proposed)
    * Default value : `ITOP_APPLICATION.'/'.ITOP_VERSION`

The conf. param. will allow to change it to something specific when needed and to revert it to "spider" for cases where people would have used that information.

2024-09-13 16:47 UTC, Molkobain approved these changes

2024-10-11 08:11 UTC, jf-cbd commented
Accepted during functional review. Will be in next iTop version.

2024-11-14 13:44 UTC, Hipska commented
So it can be merged?

2024-11-14 14:18 UTC, merged

2024-11-14 14:19 UTC, jf-cbd commented
Yep, thanks @Hipska for the PR !