:sparkles: Allow AttributeSet in XML sample file
Combodo/iTop pull request #654
Opened 2024-07-12 06:20 UTC by GurneyHallack

In XML Data Loader, manage AttributeSet class and its children to be imported , in sample XML files.

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | NA
| Type of change?                                               | Enhancement

## Symptom (bug) / Objective (enhancement)
In the setup (unattended or not), it's not possible to load extensions which contains sample XML file which contain AttributeEnumSet, AttributeClassAttCodeSet, AttributeQueryAttCodeSet or AttributeTagSet attribute, with values (not empty).
It generates an error :

```
Ok. 80 % done.
Loading data
Executing 'load-data'

Fatal error: Uncaught Error: Call to a member function Count() on string in /var/www/html/core/attributedef.class.inc.php on line 10832

Error: Call to a member function Count() on string in /var/www/html/core/attributedef.class.inc.php on line 10832

Call Stack:
    0.0009     618840   1. {main}() /var/www/html/setup/unattended-install/unattended-install.php:0
    0.2085   26345952   2. ApplicationInstaller->ExecuteAllSteps($bVerbose = ???, $sMessage = ???, $sInstallComment = ???) /var/www/html/setup/unattended-install/unattended-install.php:303
   11.4550   61076744   3. ApplicationInstaller->ExecuteStep($sStep = 'load-data', $sInstallComment = NULL) /var/www/html/setup/applicationinstaller.class.inc.php:117
   11.4551   61077480   4. ApplicationInstaller::DoLoadFiles($aSelectedModules = [0 => 'authent-cas', 1 => 'authent-external', 2 => 'authent-ldap', 3 => 'authent-local', 4 => 'combodo-backoffice-darkmoon-theme', 5 => 'itop-backup', 6 => 'itop-config', 7 => 'itop-files-information', 8 => 'itop-portal-base', 9 => 'itop-profiles-itil', 10 => 'itop-sla-computation', 11 => 'itop-structure', 12 => 'itop-welcome-itil', 13 => 'itop-config-mgmt', 14 => 'itop-attachments', 15 => 'itop-tickets', 16 => 'combodo-db-tools', 17 => 'itop-core-update', 18 => 'itop-hub-connector', 19 => 'itop-oauth-client', 20 => 'itop-themes-compat', 21 => 'itop-bridge-cmdb-ticket', 22 => 'itop-service-mgmt', 23 => 'itop-bridge-cmdb-services', 24 => 'AttributeClassAttCodeSet'], $sModulesDir = 'env-production', $aParamValues = ['mode' => 'install', 'db_server' => 'mariadb', 'db_user' => 'root', 'db_pwd' => 'password', 'db_name' => 'itop', 'new_db_name' => 'itop', 'db_prefix' => '', 'db_tls_enabled' => '', 'db_tls_ca' => '', 'application_path' => 'http://localhost:8080/', 'language' => 'EN US', 'graphviz_path' => '/usr/bin/dot', 'source_dir' => 'datamodels/2.x/'], $sTargetEnvironment = 'production', $bOldAddon = '', $bSampleData = TRUE) /var/www/html/setup/applicationinstaller.class.inc.php:356
   11.4568   61215840   5. RunTimeEnvironment->LoadData($aAvailableModules = ['_Root_' => ['version_db' => '', 'name_db' => '', 'version_code' => '3.2.0-dev-svn', 'name_code' => 'iTop'], 'AttributeClassAttCodeSet' => ['label' => 'AttributeClassAttCodeSet', 'category' => 'admins', 'dependencies' => [...], 'mandatory' => FALSE, 'visible' => TRUE, 'datamodel' => [...], 'webservice' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/AttributeClassAttCodeSet', 'module_file' => '/var/www/html/env-production/AttributeClassAttCodeSet/module.AttributeClassAttCodeSet.php', 'version_db' => '', 'version_code' => '1.0.0', 'install' => [...]], 'authent-cas' => ['label' => 'CAS SSO', 'category' => 'authentication', 'dependencies' => [...], 'mandatory' => TRUE, 'visible' => TRUE, 'datamodel' => [...], 'webservice' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/authent-cas', 'module_file' => '/var/www/html/env-production/authent-cas/module.authent-cas.php', 'dictionary' => [...], 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'authent-external' => ['label' => 'External user authentication', 'category' => 'authentication', 'dependencies' => [...], 'mandatory' => FALSE, 'visible' => TRUE, 'datamodel' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/authent-external', 'module_file' => '/var/www/html/env-production/authent-external/module.authent-external.php', 'dictionary' => [...], 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'authent-ldap' => ['label' => 'User authentication based on LDAP', 'category' => 'authentication', 'dependencies' => [...], 'mandatory' => FALSE, 'visible' => TRUE, 'installer' => 'AuthentLDAPInstaller', 'datamodel' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/authent-ldap', 'module_file' => '/var/www/html/env-production/authent-ldap/module.authent-ldap.php', 'dictionary' => [...], 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'authent-local' => ['label' => 'User authentication based on the local DB', 'category' => 'authentication', 'dependencies' => [...], 'mandatory' => TRUE, 'visible' => TRUE, 'datamodel' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/authent-local', 'module_file' => '/var/www/html/env-production/authent-local/module.authent-local.php', 'dictionary' => [...], 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'combodo-backoffice-darkmoon-theme' => ['label' => 'Backoffice: Darkmoon theme', 'category' => 'business', 'dependencies' => [...], 'mandatory' => TRUE, 'visible' => FALSE, 'datamodel' => [...], 'webservice' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/combodo-backoffice-darkmoon-theme', 'module_file' => '/var/www/html/env-production/combodo-backoffice-darkmoon-theme/module.combodo-backoffice-darkmoon-theme.php', 'dictionary' => [...], 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'itop-attachments' => ['label' => 'Tickets Attachments', 'category' => 'business', 'dependencies' => [...], 'mandatory' => FALSE, 'visible' => TRUE, 'installer' => 'AttachmentInstaller', 'datamodel' => [...], 'webservice' => [...], 'dictionary' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/itop-attachments', 'module_file' => '/var/www/html/env-production/itop-attachments/module.itop-attachments.php', 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'itop-backup' => ['label' => 'Backup utilities', 'category' => 'Application management', 'dependencies' => [...], 'mandatory' => TRUE, 'visible' => FALSE, 'datamodel' => [...], 'webservice' => [...], 'dictionary' => [...], 'data.struct' => [...], 'data.sample' => [...], 'doc.manual_setup' => '', 'doc.more_information' => '', 'settings' => [...], 'itop_version' => '1.0.2', 'root_dir' => '/var/www/html/env-production/itop-backup', 'module_file' => '/var/www/html/env-production/itop-backup/module.itop-backup.php', 'version_db' => '', 'version_code' => '3.2.0', 'install' => [...]], 'itop-config' => ['label' => 'Configuration editor', 'category' => 'Application management', 'dependencies' => [...], 'mandatory' => TRUE, 'visible' => FALSE, 'datamodel' => [...], 'webse [...]

2024-07-12 07:17 UTC, Hipska approved these changes
Looks very good!

IMHO wouldn't it be better to remove the `elseif` section and just add the `$value = $oAttDef->MakeRealValue($value, $oTargetObj);` part in the existing `else`?

2024-07-15 08:20 UTC, Molkobain commented
Hello Guy,

Thanks for the PR and for the unit test! Seems like a good idea.
Like @Hipska I'm wondering if we could reduce the code duplication, will be discussed during technical review.

2024-07-19 20:21 UTC, GurneyHallack commented
Hello,
I did it first like this, as I wanted to use sample data for an extension with an AttributeClassAttCodeSet, and also because there was already an elseif for AttributeTagSet 😁.
I think indeed it would be better like you said, but i need to update the unit test to check for all Attributes classes available and writable (like AttributeCaseLog).

2024-09-03 16:33 UTC, Molkobain requested changes
Technical review: The actual fix would be to fix the general else case and remove the TODO:
  * Remove the existing `elseif` for `AttributeTagSet` (and your `elseif`)
  * In the final `else`
    * Replace `$res = $oTargetObj->CheckValue($sAttCode, $value);`
    * With `$res = $oTargetObj->CheckValue($sAttCode, $oAttDef->MakeRealValue($value, $oTargetObj));`

2024-09-10 14:47 UTC, jf-cbd commented
Accepted in functional review.

Thanks @GurneyHallack for the contribution, we'll make the last edits.

2024-09-10 19:27 UTC, GurneyHallack commented
Hello,
I'm sorry for the delay on feedback on this one, I didn't took the time needed during the summer.

If we change the "else", ideally, we would need to check for every type of Attributes possibles, and with empty or not empty values.

In the XMLDataLoaderTest.php, there is : 
- Found with values
  - AttributeString
  - AttributeEnum
  - AttributeFriendlyName
  - AttributeFinalClass
  - AttributeObsolescenceFlag
- Added with current PR
  - AttributeEnumSet
  - AttributeClassAttCodeSet
  - AttributeClass
  - AttributeOQL
- Found but with empty
  - AttributeEmailAddress
  - AttributePhoneNumber
  - AttributeDashboard
  - AttributeLinkedSet
  - AttributeLinkedSetIndirect
  - AttributeObsolescenceDate
  - AttributeHierarchicalKey
  - AttributeExternalKey
  - AttributeExternalField
  - AttributeText
  - AttributeImage
- Missing but could be found in XML classes declarations
  - AttributeIPAddress (eg.: DatacenterDevice)
  - AttributeInteger (eg.: DatacenterDevice)
  - AttributeTagSet (eg.: FAQ FAQ-light)
  - AttributeRedundancySettings (eg.: DatacenterDevice)
  - AttributeHTML (eg.: FAQ FAQ-light)
  - AttributeStopWatch (eg.: UserRequest)
  - AttributeSubItem (eg.  UserRequest)
  - AttributeDateTime (eg.: UserRequest)
  - AttributeBlob (eg.: Attachment)
  - AttributeURL (eg.: DocumentWeb)
  - AttributeDate (eg.: Contract)
  - AttributeDuration (eg.: UserRequest)
  - AttributeMetaEnum (eg.: Ticket, with UserRequest)
  - AttributeCaseLog (eg.: UserRequest)
  - AttributePassword (eg.: OAuthClient (abstract))
  - AttributeBoolean (eg.: lnkActionNotificationToContact)
  - AttributeObjectKey (eg.: Attachment)
  - AttributeDecimal  (eg.: IPInterface)
- Missing but could be found in PHP classes declarations
  - AttributePropertySet (eg.: appUserPreferences)
  - AttributeTable (eg.: EventNotificationEmail)
  - AttributeOneWayPassword (eg.: UserLocal, from UserInternal)
  - AttributeTemplateHTML (eg.: ActionEmail)
  - AttributeTemplateString (eg.: ActionEmail)
  - AttributeLongText (eg.: AsyncSendEmail)
  - AttributeEncryptedString (eg.: CMDBChangeOpSetAttributeEncrypted)
  - AttributeApplicationLanguage (eg.: ActionNotification (abstract), which EventNotificationEmail inherites)
  - AttributeClassState(eg.: TriggerOnStateChange (asbtract))
- Missing and I didn't found them in iTop's classes (PHP nor XML):
  - AttributePercentage
  - AttributeDBFieldVoid (normal as it's basic, but it's not abstract)
  - AttributeDBField (normal as it's basic, but it's not abstract)
  - AttributeTemplateText
  - AttributeDeadline
  - AttributeQueryAttCodeSet
  - AttributeCustomFields
  - AttributeArchiveFlag (magic with archive xml, but didn't check well enough yet to test it)
  - AttributeArchiveDate (magic with archive xml, but didn't check well enough yet to test it)

2024-12-12 16:50 UTC, jf-cbd commented
Thanks for the details @GurneyHallack.
We improved your test and edited the functionality based on @Molkobain's recommendation.

You're right we should check all of these types ; that said, the proposed changed won't bring more troubles than the previous implementation, that were based on a string value. 

The only drawback is that the limitation (knowing which type of attribute works or not) isn't documented.

2024-12-13 09:02 UTC, Hipska approved these changes

2025-05-15 14:00 UTC, merged

2025-05-15 14:01 UTC, jf-cbd commented
Thanks for your contribution @GurneyHallack 😊