:globe_with_meridians: Translations - British English
Combodo/iTop pull request #677
Opened 2024-11-07 15:34 UTC by larhip

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Combodo ticket? | N°7932
| Type of change?                                               | Translations

## Symptom (bug) / Objective (enhancement)
New language files for British English 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [x] Is the PR clear and detailed enough so anyone can understand digging in the code?

2024-11-07 15:53 UTC, Hipska commented
@larhip You branched from `develop`, then you should also select this as **base** branch on the PR.

2024-11-07 15:57 UTC, larhip commented
@Hipska thanks for your hint!!
I was sitting at my screen a thought "What the hell is the f**cking problem??"
Everytime I was trying the change the base branch from develop to support 3.2 there was a lot more changes and commit than I expected.
But the only problem was related to the fact that I have selected 3.2.0 in stead of 3.2 -.-

Thanks again for your hint :-)

2024-11-07 16:02 UTC, Hipska requested changes

2024-11-07 16:02 UTC, Hipska commented on dictionaries/en_gb.dictionary.itop.core.php
> + * along with iTop. If not, see <http://www.gnu.org/licenses/>
I think this part can be removed from each file?

2024-11-07 16:02 UTC, Hipska commented on dictionaries/en_gb.dictionary.itop.core.php
> + * @copyright Copyright (C) 2010-2024 Combodo SAS
The file is just created, so you can't claim copyright as of 2010.
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
```

(The same for all files)

2024-11-07 16:08 UTC, Hipska commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBAnalyzer-Integrity-RootFinalClass' => 'Field `%2$s`.`%1$s` must contain a valid class',
Isn't this just a typo on EN US?

2024-11-07 16:08 UTC, Hipska commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBTools:LostAttachments:Disclaimer' => 'Here you can search your database for lost or misplaced attachments. This is NOT a data recovery tool, it does not retrieve deleted data.',
Also a typo I guess

2024-11-07 16:09 UTC, larhip commented on dictionaries/en_gb.dictionary.itop.core.php
> + * along with iTop. If not, see <http://www.gnu.org/licenses/>
I have created the translation with the support of a little script. This script copies the original English files and checks every file line by line.

From my point of view it would be a good idea to have the same content and line numbering in en an en_gb files, wouldn't it?

2024-11-07 16:11 UTC, larhip commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBAnalyzer-Integrity-RootFinalClass' => 'Field `%2$s`.`%1$s` must contain a valid class',
in fact it is, but it was a lot easier for me to(in a first step) to fix those typos in the new translations files :-)

2024-11-07 16:11 UTC, larhip commented on dictionaries/en_gb.dictionary.itop.core.php
> + * @copyright Copyright (C) 2010-2024 Combodo SAS
true :-(
I check this

2024-11-07 16:12 UTC, Hipska commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBAnalyzer-Integrity-RootFinalClass' => 'Field `%2$s`.`%1$s` must contain a valid class',
Okay, as long as you fix them in EN US as well, all fine for me.

2024-11-07 19:20 UTC, larhip commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBAnalyzer-Integrity-RootFinalClass' => 'Field `%2$s`.`%1$s` must contain a valid class',
Done (see #678)

2024-11-07 19:20 UTC, larhip commented on datamodels/2.x/combodo-db-tools/dictionaries/en_gb.dict.combodo-db-tools.php
> +	'DBTools:LostAttachments:Disclaimer' => 'Here you can search your database for lost or misplaced attachments. This is NOT a data recovery tool, it does not retrieve deleted data.',
Done (see #678)

2024-11-07 19:28 UTC, larhip commented on dictionaries/en_gb.dictionary.itop.core.php
> + * @copyright Copyright (C) 2010-2024 Combodo SAS
Done (see 41082639)

2024-11-08 09:35 UTC, Hipska commented on dictionaries/en_gb.dictionary.itop.core.php
> + * along with iTop. If not, see <http://www.gnu.org/licenses/>
Hmm not sure, for example the `EN GB` could have other `@author` references than the `EN US` versions, so line numbers will be hard to match anyway.

2024-11-08 09:46 UTC, jf-cbd commented
Accepted in functional review, thanks for the contribution @larhip ! We'll see in technical review if some changes are needed.

2024-11-08 09:52 UTC, Hipska requested changes
Almost good regarding the copyright and license.

Didn't realise there are so many inconsistencies in these dict files. But when starting from scratch for a new language, we should better get them all right and aligned from the start 😉

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/en_gb.dict.authent-cas.php
> + * @copyright   Copyright (C) 2024
```suggestion
 * @copyright   Copyright (C) 2024 Combodo SAS
```

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/authent-external/dictionaries/en_gb.dict.authent-external.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
Misaligned URL, I would just all have only a single space:
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```
Maybe Combodo will ask to align them..
I also think the URL needs to be https.

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/en_gb.dict.itop-attachments.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/itop-oauth-client/dictionaries/en_gb.dict.itop-oauth-client.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/itop-portal-base/dictionaries/en_gb.dict.itop-portal-base.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on datamodels/2.x/itop-themes-compat/dictionaries/en_gb.dict.itop-themes-compat.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/application/bulk/en_gb.dictionary.itop.bulk.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/application/display-block/en_gb.dictionary.itop.display-block.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/application/links/en_gb.dictionary.itop.links.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/application/newsroom/en_gb.dictionary.itop.newsroom.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/application/object/en_gb.dictionary.itop.object.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/breadcrumbs/en_gb.dictionary.itop.breadcrumbs.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/datatable/en_gb.dictionary.itop.datatable.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/field/en_gb.dictionary.itop.field.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/global-search/en_gb.dictionary.itop.global-search.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/input/en_gb.dictionary.itop.input.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/modal/en_gb.dictionary.itop.modal.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/components/quick-create/en_gb.dictionary.itop.quick-create.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/layouts/activity-panel/en_gb.dictionary.itop.activity-panel.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/layouts/navigation-menu/en_gb.dictionary.itop.navigation-menu.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/pages/errorpage/en_gb.dictionary.itop.errorpage.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/pages/notifications-center/en_gb.dictionary.itop.notifications-center.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/pages/oauth.landing/en_gb.dictionary.itop.oauth.landing.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:52 UTC, Hipska commented on dictionaries/ui/pages/preferences/en_gb.dictionary.itop.preferences.php
> + * You should have received a copy of the GNU Affero General Public License
```suggestion
 * @copyright Copyright (C) 2024 Combodo SAS
 * @license https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 09:58 UTC, Hipska commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
Did @BenGrenoble create this translation?

2024-11-12 16:06 UTC, BenGrenoble commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
No. Its must be a copy past from another dict file.

2024-11-12 16:25 UTC, Hipska commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
@larhip please fix ;)

2024-11-12 16:40 UTC, larhip commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
For sure it is a copy of the English dictionary file :-)
As I wrote previously I did not create those translations all by hand but used a script which copies all en files an go through every line to check whether there is the need to change it in British English. 

This makes it pretty easy for me to update all translations (I.e. with a new version of iTop). 

As soon as I will change all those requested change by you @Hipska it will become a lot more work to create new translations with a new version. 

In this case it would be great to have a feedback from the iTop maintainer which means Combodo. @BenGrenoble maybe you as PO could give us your opinion or make a decision between more or less “automated” British English translations and perfectly clean files (which is currently not the case for EN US)?

Don’t get me wrong: for me both is absolutely fine, but in case of preferring clean files (even if this is not the case for en.dict.*) there might be a higher risk that British English will be not that good maintained in case of new translations.

hope you got my point 😊

2024-11-12 16:44 UTC, Hipska commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
I would not worry for new translations (dict items) as you are stating, since Combodo maintainers run an automated tool to copy these new items to the other languages and marks them to be translating by adding `~~` suffix, so everybody knows its a dict item that still needs to be translated.

2024-11-13 10:21 UTC, BenGrenoble commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/en_gb.dict.itop-bridge-cmdb-services.php
> +* @author       Benjamin Planque <benjamin.planque@combodo.com>
You're right we will run an automated script on these dict. 
For me it's ok if the names or the legal informations in the headers are not modified. As long as the format of the file is ok and the translation are good. 
We've the history of the commit and @jf-cbd will double check while integrating the PR.

2024-11-15 09:23 UTC, jf-cbd commented
Accepted in technical review. I'll perform the necessary edits.

2024-11-15 13:56 UTC, jf-cbd commented on dictionaries/en_gb.dictionary.itop.core.php
> + * along with iTop. If not, see <http://www.gnu.org/licenses/>
Yes, it's good to include only the copyright and license line. That said, it's not bad if files contain more information on licenses. I will apply the suggested modifications as they make sense.

2024-11-15 15:58 UTC, jf-cbd commented
Hello @larhip, I don't have the rights to push on your branch, so I made one with your modifications and some editions. Could you please merge [my branch](https://github.com/Combodo/iTop/tree/fork-jf-cbd/itomig-de/feature/translations_en_gb) in your branch so I can accept the PR please ?

2024-11-15 16:13 UTC, jf-cbd commented
Hello @larhip, I don't have the rights to push on your branch, so I made one with your modifications and some editions. Could you please merge [my branch](https://github.com/Combodo/iTop/tree/fork-jf-cbd/itomig-de/feature/translations_en_gb) in your branch so I can accept the PR please ?

2024-11-16 12:28 UTC, larhip commented
Hey @jf-cbd ,
Thanks a a lot for your efforts!

Since my fork is done in an organization (itomig-de/iTop instead of larhip/iTop) it is somehow impossible to allow you to modify this PR, we discussed that already in the past with Guillaume. It seems to be a restriction of GitHub.
Anyhow, your modifications are merged now, so you should be able to accept this PR.

Thanks again! :-)

2024-11-18 08:13 UTC, jf-cbd commented
Hey @larhip, thanks for the explanation :)
I did a last update to make some tests pass. May you please merge once more ? After this, I'll accept the PR.
Thanks !

2024-11-18 08:24 UTC, larhip commented
@jf-cbd modifications merged :-)

2024-11-18 13:38 UTC, merged