🌐 Translations - improved translation for zh cn 20241108
Combodo/iTop pull request #679
Opened 2024-11-08 08:22 UTC by purplegrape

improved translation for zh cn 20241108

this pr is for zh-cn entries in web/dictionaries/

1.fix some missing line (compared to en.dict )
2. minor translation improvement

2024-11-08 08:35 UTC, purplegrape commented
The structure of entries in datamodels change a lot, just do as en.dict

2024-11-08 09:32 UTC, Hipska requested changes
I have some objections regarding the file headings..

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/zh_cn.dict.authent-cas.php
> + * @copyright   Copyright (C) 2013 XXXXX
This is not good, please keep as it was:
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
```

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/authent-external/dictionaries/zh_cn.dict.authent-external.php
> - * @author Robert Deng <denglx@gmail.com>
Not nice to remove original authors. Same remark for the other files where You removed the `@author`.

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/authent-local/dictionaries/zh_cn.dict.authent-local.php
> +	'Class:UserLocal/Attribute:expiration/Value:force_expire+' => '',
Aren't these items supposed to be sorted alphabetically?

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/zh_cn.dict.combodo-backoffice-darkmoon-theme.php
> +]);
Please re-add the missing newline at end of file.

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/itop-attachments/dictionaries/zh_cn.dict.itop-attachments.php
> - * @license    https://opensource.org/licenses/AGPL-3.0
Previous way was more correct, please revert this.

2024-11-08 09:32 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
Please revert to https:
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```
(Also on all other files)

2024-11-08 09:45 UTC, purplegrape commented on datamodels/2.x/authent-cas/dictionaries/zh_cn.dict.authent-cas.php
> + * @copyright   Copyright (C) 2013 XXXXX
plz update en.dict first

2024-11-08 09:49 UTC, purplegrape commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
plz update en.dict first

2024-11-08 09:56 UTC, purplegrape commented on datamodels/2.x/authent-external/dictionaries/zh_cn.dict.authent-external.php
> - * @author Robert Deng <denglx@gmail.com>
Robert Deng is the zh cn maintainer quite many years ago，I am the main contributor of zh-cn in the recent 2 years
in my mind，the “@author” line was removed by me since itop 2.4 or 2.5
why it appears in iTop 3.2 again？

2024-11-08 09:59 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/zh_cn.dict.authent-cas.php
> + * @copyright   Copyright (C) 2013 XXXXX
You changed in the Chinese version, Combodo normally uses a script that generates/updates the new dict items without changing the header in a file. They don't do a full copy.

2024-11-08 10:02 UTC, Hipska commented on datamodels/2.x/authent-external/dictionaries/zh_cn.dict.authent-external.php
> - * @author Robert Deng <denglx@gmail.com>
He still is the original author. Should not be removed, only add a new `@author` if needed.

2024-11-08 10:05 UTC, Hipska commented on datamodels/2.x/itop-backup/dictionaries/zh_cn.dict.itop-backup.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
Why is that relevant? It was correct on this file before and you changed it.

2024-11-08 10:17 UTC, Hipska reviewed
Still some to fix..

Note I didn't put suggestions for every file, but I think you get it, please apply on all files where necessary.

2024-11-08 10:17 UTC, Hipska commented on datamodels/2.x/itop-themes-compat/dictionaries/zh_cn.dict.itop-themes-compat.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright   Copyright (C) 2010-2024 Combodo SAS
 * @license     https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 10:17 UTC, Hipska commented on dictionaries/core/orm-value/orm-document/zh_cn.dictionary.itop.orm-document.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license   https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 10:17 UTC, Hipska commented on dictionaries/core/uniqueness-rule/zh_cn.dictionary.itop.uniqueness-rule.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license   https://opensource.org/licenses/AGPL-3.0
```

2024-11-08 10:37 UTC, purplegrape commented
> Still some to fix..
> 
> Note I didn't put suggestions for every file, but I think you get it, please apply on all files where necessary.

In your words，there is too much work to do
I've checked line by line against en.dict 
I think it's fine to overwrite the files directly if no php syntax error

2024-11-08 10:47 UTC, purplegrape commented
fixed, this pr should merge to support/3.2 , no conflicts now

2024-11-13 08:27 UTC, jf-cbd commented
Hello, thanks a lot @purplegrape for your contributions and editions :D 
I will perform the final checks and make any necessary edits.

2024-11-13 08:31 UTC, Hipska commented
@purplegrape The current state of your PR is also undoing all the fixes in EN US dicts done by #678

2024-11-13 08:39 UTC, jf-cbd commented
> @purplegrape The current state of your PR is also undoing all the fixes in EN US dicts done by #678

True, but the current PR was created before I merged #678, so I'll address this.

2024-11-13 08:46 UTC, Hipska commented
That should not happen by default. Its the way @purplegrape did a rebase and then copied over his old files or something..

2024-11-13 10:57 UTC, Hipska requested changes
New batch of changes to apply

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/authent-cas/dictionaries/zh_cn.dict.authent-cas.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/zh_cn.dict.combodo-backoffice-darkmoon-theme.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/authent-ldap/dictionaries/zh_cn.dict.authent-ldap.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
 * @author Robert Deng <denglx@gmail.com>
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/authent-local/dictionaries/zh_cn.dict.authent-local.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
 * @author Robert Deng <denglx@gmail.com>
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
> + * @license	http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/itop-bridge-cmdb-services/dictionaries/zh_cn.dict.itop-bridge-cmdb-services.php
> +* @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
 * @author Benjamin Planque <benjamin.planque@combodo.com>
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/zh_cn.dict.itop-bridge-cmdb-ticket.php
> +*/
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
 * @author Benjamin Planque <benjamin.planque@combodo.com>
 */
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/itop-change-mgmt-itil/dictionaries/zh_cn.dict.itop-change-mgmt-itil.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/itop-change-mgmt/dictionaries/zh_cn.dict.itop-change-mgmt.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 10:57 UTC, Hipska commented on datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska requested changes

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-config/dictionaries/zh_cn.dict.itop-config.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-core-update/dictionaries/zh_cn.dict.itop-core-update.php
> + * @license	http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-faq-light/dictionaries/zh_cn.dict.itop-faq-light.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-files-information/dictionaries/zh_cn.dict.itop-files-information.php
> + * @license	http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-hub-connector/dictionaries/zh_cn.dict.itop-hub-connector.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-knownerror-mgmt/dictionaries/zh_cn.dict.itop-knownerror-mgmt.php
> + * @license    http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-oauth-client/dictionaries/zh_cn.dict.itop-oauth-client.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
> + * Copyright (C) 2013-2024 Combodo SAS
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
```

2024-11-13 11:04 UTC, Hipska commented on datamodels/2.x/itop-portal/dictionaries/zh_cn.dict.itop-portal.php
> + * @license     http://opensource.org/licenses/AGPL-3.0
```suggestion
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
 * @author Benjamin Planque <benjamin.planque@combodo.com>
```

2024-12-16 10:39 UTC, merged