N°7219 - Dashboard issue (fix 3.1)
Combodo/iTop pull request #682
Opened 2024-11-14 14:33 UTC by bdalsass

Problème d'encodage des dashboards.

https://support.combodo.com/pages/UI.php?operation=details&class=Bug&id=7219&

2024-11-15 08:37 UTC, steffunky approved these changes

2024-11-22 08:19 UTC, rquetiez requested changes

2024-11-22 08:19 UTC, rquetiez commented on application/dashboard.class.inc.php
> +		$sTitle = utils::EscapeHtml($this->sTitle);
Un double encodage va persister sur les caractères comme &, < et >. De plus, je pense que cela va régresser si le titre contient une simple quote. json_encode() serait l'outil approprié pour ce cas.

2024-11-22 13:04 UTC, bdalsass commented
I close this PR, correction for 3.x branches will be the same than the one applied to 2.7
https://github.com/Combodo/iTop/pull/681

2024-11-22 13:04 UTC, closed without merging