N°7995 - Allow to redefine portal twig template for all bricks in a portal
Combodo/iTop pull request #686
Opened 2024-11-28 14:49 UTC by steffunky

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | N°7995
| Type of change?                                               | Enhancement

## Objective 
When redefining a brick template, you need to overload the `<template>` for every brick definition.
It works well for one specific iTop, but as we plan to release an extension bringing the 3.3.0 portal design compatible with iTop 3.2.1+, we need to be able to overload templates for all bricks in a portal without overloading every brick definition

## Proposed solution

This pull request use the `<template>` defined in the portal properties, allowing it to define new default templates that bricks will take into account if they do not have a specific template in their definition.

Example of a customization that'll affect every BrowseBrick in a portal: 
```
  <module_design xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="itop-portal" xsi:type="portal">
  <properties>
    <templates>
      <template id="Combodo\iTop\Portal\Brick\BrowseBrick:page" xsi:type="Combodo\iTop\Portal\Brick\BrowseBrick" _delta="define">itop-custom-browse-brick/templates/page.html.twig</template>
    </templates>
  </properties>
  </module_design>
```

## Checklist before requesting a review

- [X] I have performed a self-review of my code
- [X] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [X] Is the PR clear and detailed enough so anyone can understand digging in the code?

2024-11-28 15:26 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Brick/AbstractBrick.php
> +			$this->{$sSetTemplateMethodName}($sTemplate);
Handle potential exception (bad configuration) with a try catch block and throw a comprehensible exception.

2024-11-28 15:26 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Brick/BrickCollection.php
> +	public function __construct(ModuleDesign $oModuleDesign, ContainerInterface $container)
Container injection is not a good design patter, prefer parameter injection via Symfony configuration.

2024-11-28 15:26 UTC, bdalsass commented on datamodels/2.x/itop-portal-base/portal/src/Brick/BrickCollection.php
> +					$oBrick->LoadFromPortalProperties($oPortalConf['properties']);
Maybe could we use cache system to avoid parsing properties for each brick ?
The ScopeValidatorHelper service do something like this.

2024-11-29 08:12 UTC, steffunky commented on datamodels/2.x/itop-portal-base/portal/src/Brick/BrickCollection.php
> +					$oBrick->LoadFromPortalProperties($oPortalConf['properties']);
We could, but not in this PR :grin:

2024-11-29 08:34 UTC, steffunky commented on datamodels/2.x/itop-portal-base/portal/src/Brick/BrickCollection.php
> +	public function __construct(ModuleDesign $oModuleDesign, ContainerInterface $container)
Fixed in [2f2e8c8](https://github.com/Combodo/iTop/pull/686/commits/2f2e8c8945b47e0e6b64bf201e864e51530897ff)

2024-11-29 08:35 UTC, steffunky commented on datamodels/2.x/itop-portal-base/portal/src/Brick/AbstractBrick.php
> +			$this->{$sSetTemplateMethodName}($sTemplate);
Fixed in [2f2e8c8](https://github.com/Combodo/iTop/pull/686/commits/2f2e8c8945b47e0e6b64bf201e864e51530897ff) with a more defensive approach than try/catch

2024-11-29 14:28 UTC, bdalsass approved these changes

2024-12-02 15:40 UTC, rquetiez requested changes

2024-12-02 15:40 UTC, rquetiez commented on datamodels/2.x/itop-portal-base/portal/src/Brick/AbstractBrick.php
> +	public function LoadFromPortalProperties($aPortalProperties) {
Coding convention : method opening bracket expected on the next line

2024-12-02 15:40 UTC, rquetiez commented on datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
> +							$sXsiType = $oSubNode->getAttribute('xsi:type');
Using xsi:type is problematic:

- xsi:type should refer to an itop XML grammar
- The same values are already used under /bricks/brick, where they refer to a real grammar
- xsi:type should be present for every template/template nodes, which is not the case for existing layout and home nodes.

Suggested alternative: fetch the type from the node id: **id="`type`:`page-ref`"**

2024-12-03 08:14 UTC, steffunky commented on datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
> +							$sXsiType = $oSubNode->getAttribute('xsi:type');
Fixed in [705c86c](https://github.com/Combodo/iTop/pull/686/commits/705c86c04616b3668fcc960e3cc20f57fee5e404)

2024-12-03 08:14 UTC, steffunky commented on datamodels/2.x/itop-portal-base/portal/src/Brick/AbstractBrick.php
> +	public function LoadFromPortalProperties($aPortalProperties) {
Fixed in [705c86c](https://github.com/Combodo/iTop/pull/686/commits/705c86c04616b3668fcc960e3cc20f57fee5e404)

2024-12-03 09:11 UTC, bdalsass approved these changes

2024-12-03 09:41 UTC, merged