🐛 Unattended Install: unable to connect to MySQL with TLS
Combodo/iTop pull request #694
Opened 2024-12-19 18:38 UTC by tomrss

## Base information
| Question                                                      | Answer 
|---------------------------------------------------------------|--------
| Related to a SourceForge thead / Another PR / Combodo ticket? | No
| Type of change?                                               | Bug fix

## Symptom (bug) / Objective (enhancement)

Unattended install process does not support TLS connections to MySQL.

## Reproduction procedure (bug)

1. On iTop 3.2.0-2 (not related to version)
2. With PHP 8.3.12 (not related to version)
3. MySQL instance configured with `require_secure_transport=ON`
4. Setup MySQL connections with TLS (config `db_tls.enabled` and `db_tls.ca`)
5. Then launch the `setup/unattended-install/unattended-install.php` script
6. Finally, see that the TLS connection to MySQL cannot be established:
```
Fatal error: Uncaught mysqli_sql_exception: Connections using insecure transport are prohibited while --require_secure_transport=ON. in /var/www/html/setup/unattended-install/unattended-install.php:313
```

## Cause (bug)

TLS connection not implemented in the unattended install script:

https://github.com/Combodo/iTop/blob/ea5473ad775297e58a0a8418be1ccee822036066/setup/unattended-install/unattended-install.php#L220-L221

and

https://github.com/Combodo/iTop/blob/ea5473ad775297e58a0a8418be1ccee822036066/setup/unattended-install/unattended-install.php#L313-L314

## Proposed solution (bug and enhancement)

Add support for TLS connection based on [this code in the docs](https://www.itophub.io/wiki/page?do=export_code&id=latest:install:php_and_mysql_tls&codeblock=0) and existing MySQL connection code in the app:

https://github.com/Combodo/iTop/blob/ea5473ad775297e58a0a8418be1ccee822036066/core/cmdbsource.class.inc.php#L174-L186

Disclaimer: PHP is not my language, sorry if something is broken or strange! Just let me know and I'll fix it.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [x] Is the PR clear and detailed enough so anyone can understand digging in the code?

2025-01-07 10:28 UTC, Hipska approved these changes
Looks good, may as well make use of the return value of the connect method..

2025-01-07 10:28 UTC, Hipska commented on setup/unattended-install/unattended-install.php
>  		if ($oMysqli->connect_errno)
```suggestion
		if (!$oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
```

2025-01-07 10:28 UTC, Hipska commented on setup/unattended-install/unattended-install.php
>  		if (!$oMysqli->connect_errno)
```suggestion
		if (!$oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
```

2025-01-07 10:47 UTC, Hipska commented on setup/unattended-install/unattended-install.php
> +		if (!$oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
```suggestion
		if ($oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
```
Oops mistake from my end..

2025-01-07 10:53 UTC, Hipska requested changes

2025-01-07 10:53 UTC, Hipska commented on setup/unattended-install/unattended-install.php
> +		if ($oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
Now you made a mistake :smile:
```suggestion
		if (!$oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
```

2025-01-07 10:55 UTC, Hipska approved these changes

2025-01-07 10:56 UTC, tomrss commented on setup/unattended-install/unattended-install.php
> +		if ($oMysqli->real_connect($sDBServer, $sDBUser, $sDBPwd, null, null, null, $iMySqlFlag))
😅

2025-01-15 07:14 UTC, odain-cbd approved these changes

2025-01-16 16:57 UTC, jf-cbd commented
Accepted in functional review, it should be added in iTop 3.2.1.

2025-01-22 10:07 UTC, rquetiez requested changes
Though the fix is relevant, it would be even more relevant to invoke `CMDBSource::GetMysqliInstance` to do the job:

1. This refactor is feasible because `GetMysqliInstance` is purely **static**. Note that it throws Exceptions in case of failure.
2. There is already another difference between the proposed implementation and the implementation of `GetMysqliInstance` that is relevant to all use cases. See the call to real_connect on line 186 that takes into account the PHP setting `mysqli.default_socket`
3. We will automatically benefit from future improvements of `GetMysqliInstance`

2025-01-22 14:05 UTC, tomrss commented
Thanks for the feedback @rquetiez , i copied the snippet exactly from that class, but I didn't know if coupling with core part was desirable.

I'll implement the requested changes within a couple of days.

2025-01-24 15:07 UTC, Hipska approved these changes

2025-01-31 13:23 UTC, rquetiez approved these changes

2025-01-31 13:45 UTC, merged

2025-01-31 13:46 UTC, jf-cbd commented
Thank you for this contribution @tomrss 😊

2025-03-11 16:24 UTC, tomrss commented
Hi @Hipska @jf-cbd, I noticed from the changelog of 3.2.1 that this patch should be included, but I obtain the same TLS error as in 3.2.0. I checked that the zip downloaded from https://sourceforge.net/projects/itop/files/itop/3.2.1/iTop-3.2.1-16429.zip/download does not contain this patch. Am I missing something? Thanks!

2025-03-11 16:43 UTC, Hipska commented
You're right, this was merged into `develop` branch, not the `support/3.2`. So I guess it will be included earliest of iTop 3.3

2025-03-11 16:49 UTC, jf-cbd commented
Hello @tomrss, the branch [tomrss:unattended-install-tls-mysql](https://github.com/tomrss/iTop/tree/unattended-install-tls-mysql) has been created from [Combodo:develop](https://github.com/Combodo/iTop/tree/develop) branch, so it has been merged in this branch. This branch is used for the next major version, aka 3.3.0.
But you're right, it is in the changelog. I don't why, I'm going to investigate and see where the error comes from (bad changelog or bad merge, depending on Combodo's decision)
Thanks for reporting, sorry for the mistake, I'll keep you updated.

2025-03-12 13:51 UTC, tomrss commented
Ok! Thank you for your feedback @jf-cbd

2025-03-13 08:27 UTC, jf-cbd commented
Ok, so your fix should have been included in 3.2.1, but I merged your PR in the wrong branch, my bad.
I'll put it in the branch support/3.2, so your fix will be included in the 3.2.2 release, which is scheduled for this summer.
Sorry again 😅