[POC] reduce metamodel serialized size
Combodo/iTop pull request #72
Opened 2019-03-26 13:51 UTC by bruno-ds

# [POC] reduce metamodel serialized size ...
... by storing class name instead of class instance. 

This could be extended to more properties.

for now the metamodel is a 2.3Mo serialized string, this is huge.

2019-03-26 16:51 UTC, Hipska commented
I don't see any difference as you initiate them anyway, which now makes it even bigger..

2019-03-26 16:52 UTC, Hipska requested changes
Indentation is wrong/different compared to other code in this file.

2019-03-26 18:05 UTC, bruno-ds commented
The data stored in APC cache was an array of instances, it is now an array of class names.
The in memory footprint is a little bigger, but the serialized footprint (stored in APC) is way smaller.

For the indent: let's consider it's just a POC I'll work on it it the poc is accepted.

2019-03-26 23:48 UTC, Hipska commented
Oh okay, you are talking about data you put in APC. I thought you were talking about memory size of `MetaModel` class. It wasn’t clear, but now it is, and it’s fine for me.

2019-03-27 07:25 UTC, bruno-ds commented on core/metamodel.class.php
> +				$aCache['m_aExtensionClassNames'] = self::$m_aExtensionClassNames;
This is where the magic happens: storing  `array of string` instead of `array of instances`

2019-05-17 09:27 UTC, bruno-ds commented
To move forward, some benchmark would be needed in order to determine if there is a real gain

2019-12-20 16:22 UTC, Molkobain commented on test/core/MetaModelTest.php
> +	 * @param $m_aExtensionClassNames
We don't have to start properties name with "m_" anymore. It was an old convention in the begining of iTop.

2019-12-20 16:22 UTC, Molkobain commented on test/core/MetaModelTest.php
> +	 * @param $className
But we do start properties name (and variables) with it type (eg. $aArray, $iInteger, $oObject, $sString, ...)

2019-12-20 16:22 UTC, Molkobain commented on test/core/MetaModelTest.php
> +	 * @param $m_aExtensionClassNames
We don't start properties name with "m_" anymore, it was an old convention from the begining of iTop.

2019-12-20 16:22 UTC, Molkobain commented on test/core/MetaModelTest.php
> +	 * @param $className
But we do start properties and variables name with their types (eg. $aArray, $iInteger, $sString, $oObject)

2020-05-22 15:46 UTC, rquetiez commented
I think the benefit in performance is negligible: the time spent unserializing MetaModel data is 99% related to the classes and their attributes.

Anyhow, I see a great opportunity in this proposal: it is a **first step** toward slicing up MetaModel into smaller pieces, moving forward to the dependancy injection model.

As it is a first step, let's make it a template for next steps! I would therefore suggest a few improvements:

1. Implement new classes into separate files
2. How about namespaces/autoloading?

2020-08-10 09:11 UTC, merged

2020-08-10 09:11 UTC, odain-cbd commented
branch merged