Add controls for treeview
Combodo/iTop pull request #87
Opened 2019-06-18 14:52 UTC by scheibling

Add controls for expanding or collapsing treeview.
Set standard to collapsed tree for user to decide state closed or open.
Add css to properly style controls.

2019-06-18 15:01 UTC, piRGoif commented
For information, this is a suggested fix for https://sourceforge.net/p/itop/tickets/1761/
Thanks Lars, we will review this !

2019-06-18 17:14 UTC, jbostoen requested changes

2019-06-18 17:14 UTC, jbostoen commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add("<div class=\"treecontrol\" id=\"treecontrolid\"><a href=\"?#\">Collapse All</a> | <a href=\"?#\">Expand All</a></div>");
Needs to use dictionary entries I think (Dict::S), rather than hardcoded strings?

Also, if you use Combodo's convention of writing PHP, they usually use single quotes - which makes it unnecessary to escape the double quotes.

2019-06-18 17:14 UTC, jbostoen commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview(control: #treecontrolid);\n");
I've done some work in JavaScript, but is this correct? 

I'd be expecting something like .treeview({ control: '#treecontrolid' }) or something? (not entirely sure about which lib the treeview comes from, but it seems like you're trying to define a property)

2019-06-19 07:18 UTC, piRGoif commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add("<div class=\"treecontrol\" id=\"treecontrolid\"><a href=\"?#\">Collapse All</a> | <a href=\"?#\">Expand All</a></div>");
You're perfectly right, thanks Jeffrey !
You can refer to the translation guide : https://www.itophub.io/wiki/page?id=2_6_0%3Acustomization%3Atranslation

2019-06-24 11:45 UTC, scheibling commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add("<div class=\"treecontrol\" id=\"treecontrolid\"><a href=\"?#\">Collapse All</a> | <a href=\"?#\">Expand All</a></div>");
Right, I'll add the dictionary entries! Regarding the quotes, I basically copied the convention used in the rest of the file. I can change that as well.

2019-06-24 11:55 UTC, scheibling commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview(control: #treecontrolid);\n");
Not quite an expert on JS either, the limited documentation I could still find on that instance of treeview.js suggested this style. Since it's been deprecated in favor of jqTree, it's been removed from the jquery.com-website. I'll try your suggestion as well, I agree, if that works it seems like the right way to go.

2019-06-24 13:28 UTC, Hipska approved these changes

2019-06-24 14:17 UTC, piRGoif commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add("<div class=\"treecontrol\" id=\"treecontrolid\"><a href=\"?#\">Collapse All</a> | <a href=\"?#\">Expand All</a></div>");
Our coding standards are documented here : https://www.itophub.io/wiki/page?id=latest%3Acustomization%3Acoding_standards
Indeed it does not cover this particular point, we'll discuss with the team if it should be added.

2019-06-24 14:59 UTC, jbostoen commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview(control: #treecontrolid);\n");
It does look like an old library; perhaps this is something which will change in 2.8.

2019-06-24 15:02 UTC, jbostoen commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview({ control: '#treecontrolid',	persist: 'false'});\n");
Couldn't find the proper documentation; but it seems persist expects string values of either 'location' or 'cookie'? (I looked it up because for boolean values I'd simply expect persist: false)

( I actually took a look at https://github.com/Combodo/iTop/blob/96334d859aaa695aa128fe562256dad1cd6603cf/js/jquery.treeview.js#L191 ).

2019-06-25 09:05 UTC, piRGoif commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview(control: #treecontrolid);\n");
> It does look like an old library; perhaps this is something which will change in 2.8.

We're not sure yet : we began a big work on all of our dependencies (inventory, create forks when possible, ...), this is still in progress. Sure the JQuery plugins will be updated, but we don't have a clear roadmap for now, especially for this one.

The first step was to upgrade JQuery itself : we moved to 3.3.1 for 2.6.0 and change deprecated code as much as possible. We will move to 3.4 and change some plugins for 2.7.0 (we're aiming for the autocomplete for example but not sure we will have enough resources).

Step by step ;)

2019-11-04 14:48 UTC, Hipska commented
Do you also have an example image?

2019-11-12 09:51 UTC, scheibling reviewed
Correction to the treeview class

2019-11-12 09:51 UTC, scheibling commented on application/ui.extkeywidget.class.inc.php
> +		$oPage->add_ready_script("\$('#tree_$this->iId ul').treeview({ control: '#treecontrolid',	persist: 'false'});\n");
That's absolutely correct.

2019-11-12 09:52 UTC, scheibling commented
Yes, sorry for the delay. 

![image](https://user-images.githubusercontent.com/24367830/68660824-33970a00-053a-11ea-977b-aa3626d471aa.png)

2020-02-07 13:39 UTC, piRGoif commented
This was submitted in Combodo ticket DB as N°2764, candidate for iTop 2.8.

2020-02-07 13:41 UTC, piRGoif commented
@scheibling sorry it took us so much time to accept this PR... We were (and still are in a way) quite busy with the 2.7.0... We are aiming to integrate this in 2.8.0.
As your branch as conflicts, can you rebase on Combodo/iTop develop branch ? You may also allow us to write on your branch (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

2020-02-10 09:41 UTC, scheibling commented
$piRGoif No worries, I'll look at it during the week. Thanks for the heads up!
I've also opened it to you in case you see something I've missed.

2020-03-27 15:10 UTC, piRGoif commented
Hello,

As we are now ready to integrate PR for 2.8.0, I tried to test your changes. As there are still conflicts, I reported your changes myself. While testing it came to me that displaying those buttons if no child leaf is present is king of weird, so I added a test. 
See the 3 commits in the  feature/pr87_treeview_expand-collapse branch.

I'm ready to integrate this from this branch, don't hesitate to give your feedback in the coming days !

2020-04-24 13:09 UTC, piRGoif commented
I'm closing this as no answer for the original submitter, and because we already discussed on #132 with the rest of the team.

2020-04-24 13:09 UTC, closed without merging